### ISSUE TITLE
Implement more options when reporting illegal content.

### ISSUE THREAD

**Issue by real-rouse** [lbryio/lbry-desktop#1001]
I can see there is more illegal/copyrighted material being published to LBRY lately.
[A movie copyrighted by Universial Pictures](https://spee.ch/a353dbac2555f7d4565f9131562289c81b644633/Screen-Shot-2018-02-07-at-121041)

See https://explorer.lbry.io/claims for the latest claims.

What if there was more options presented when you click the "Report" button?

**- Right now the report button is only for the copyright owners.**

**What if you were asked:**

- Are you a owner of copyrighted material? Report it to us, so we can remove access to it.
- Are you a volunteer who suspects this content is copyrighted? Report to us, so we can take direct contact with the owners.
- Is this content illegal in the U.S? Report it, so we can take it down.

If LBRY Inc. + community contributors could report directly to the owners (e.g sending an e-mail directly to Universal Pictures), we may get a better standing with bigger content creators. Of course, only do the takedowns if the actual owners report it.

I think this may improve LBRYs image, and may allow for greater chance of adoption from these big companies. Otherwise, I think this may turn LBRY into "another ThePirateBay" in the eyes of new users.

This will of course require more resources and staff from LBRY Inc.'s side.

Maybe even incentivizing/giving bounties to contributors for successful takedowns could be a part of the pre-mined LBC. (Maybe have selected community-reporters to make these reports, to prevent spam.)

Maybe this is a bad idea, but I would like to discuss it.

**Comment by tzarebczan** [comment]
@kauffj / @lyoshenka what are your initial thoughts on this? I'm not sure about getting copyright reports from 3rd parties, but I was recently thinking more along the lines of having some way to report illegal/horrific as a user.

**Comment by real-rouse** [comment]
Maybe is not LBRY Inc.'s responsibility to start policing content before the owners come. I can understand that. I don't think Youtube did that either in the beginning.

**Comment by alyssaoc** [comment]
Issue moved to [lbryio/lbry.io #822](https://github.com/lbryio/lbry.io/issues/822) via [**ZenHub**](https://www.zenhub.com/)
