### ISSUE TITLE
Can't see history of content/channels I've viewed

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#1009]
## The Issue
Can't see history of content/channels I've viewed

### Steps to reproduce
1. Navigate to a channel/content from the homepage but don't watch it
2. Wait for it to be taken off the home page
3. Try to get back to it

### Expected behaviour
I should be able to see my navigation history, similar to a web browser. This would consist of content pages only (I think?) and not app pages like wallet, settings, etc.

### Actual behaviour
I have to remember channels/videos if I want to go back to them. I think this leads to a lot of content that is lost as soon as it's taken off the homepage

**Comment by daovist** [comment]
@seanyesmunt I'm having some trouble making this work in `navigation.stack`

when a user reloads the app, should they be taken to the last page they visited? Are we pushing `/discover` to the end of the `navigation.stack` array?

because if `index` is 0 or 1 and the user clicks a link it will remove all history beyond `index`--a browser with back and forward navigation wouldn't work otherwise

or I'm just approaching this from the wrong angle again...

**Comment by seanyesmunt** [comment]
If the user reloads the app should stay on the same screen. @daovist Is it not working by just adding `'navigation'` here? 
https://github.com/lbryio/lbry-app/blob/master/src/renderer/store.js#L101

**Comment by daovist** [comment]
Oh, okay. I didn't think we would want it to work like that. I would prefer it start on the home page with new content but am not picky.

What you've described is now the case in the master branch and it loads the last page, so I'll just make the History page to display.

FYI the new master isn't working quite right on my machine (Ubuntu 16.04.3). There is no scrolling except for non-video content e.g. UC Berkeley index. When trying to access a page I searched for by name I get reference error: normalizeURI not found. Should I make be making submitting issues or PRs to fix these?

I'm dealing with merge issues all over the place and trying not to revert to making all new PRs but may end up going that route.

**Comment by tzarebczan** [comment]
Recently Viewed would be a good title for this area. Should we track this in the sqlite database through the daemon? Decision would be based on cross device syncing solution (is there one yet?)
