### ISSUE TITLE
Organizing Content for Creators 

### ISSUE THREAD

**Issue by LupoTV** [lbryio/lbry-desktop#1016]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by LupoTV** [comment]
I know you guys are working on an update, so please consider making a way to organize our channels better.  I already have so many stories up it is a mess to try and find something.  I ask you guys to develop a playlist feature and maybe a basic layout for channel homepages.  I know the idea of just making new channels to organize content better is being considered.  The issue with that is it spreads your content out and weakens your brand.  As a content creator I hope when someone finds one of my stories that they then go check out and binge watch all my old stuff.  If all my stuff is in different channels everywhere that won't happen.  Thanks for considering my feedback. 
Thanks for reporting an issue to LBRY and helping us improve!

**Comment by liamcardenas** [comment]
@LupoTV thanks for the suggestion! I will bring this up with the app/ux team and find out how best to move on this!

**Comment by alyssaoc** [comment]
closing, we have split this into smaller issues that will be added to app incrementally
