### ISSUE TITLE
Send error when there is a space in front of the address 

### ISSUE THREAD

**Issue by LavRadis** [lbryio/lbry-desktop#1062]
## The Issue
I accidentally copy-pasted an address in the send field that had an extra space in front of the address. An error message appeared but without error description. It took me some time to figure out that there is an extra space since it is hard to notice. Could be confusing to users.

### Steps to reproduce
1. Enter a valid address in the send field
2. Add a space in front of it
3. When you send, the error will appear 

### Expected behaviour
Two things could happen:
Error message with an explanation like "Invalid address, please enter the correct format" or 
The app recognizes the extra space and automatically resolves the correct address. 

### Actual behaviour
Error notification appeared, but without any help or description that could help solve the issue. 

## System Configuration

- LBRY Daemon version: 0,18,2
- LBRY App version: 0.20.0
- LBRY Installation ID: 7tYN144rHXrspzJG9xLP28fi1JztXnbpKro6DBJEQyzBmXTyDgqRLfYsUvHYFVmMe2
- Operating system: Win 10

## Screenshots

![transaction failed error](https://user-images.githubusercontent.com/10566738/36919478-c10daeb8-1e5d-11e8-9099-54ba4e81ca8a.jpg)

**Comment by tzarebczan** [comment]
The error from the daemon is below. Should we be stripping off white spaces on the app side, or leave it up to the daemon (which doesn't handle it well right now)?
`{
  "error": {
    "code": -32500,
    "data": {
      "traceback": [
        "Traceback (most recent call last):",
        "  File \"site-packages\\lbrynet\\daemon\\auth\\server.py\", line 240, in render",
        "    ",
        "  File \"site-packages\\lbrynet\\daemon\\auth\\server.py\", line 355, in _render",
        "    ",
        "  File \"site-packages\\twisted\\internet\\defer.py\", line 150, in maybeDeferred",
        "    ",
        "  File \"site-packages\\twisted\\internet\\defer.py\", line 1445, in unwindGenerator",
        "    ",
        "--- <exception caught here> ---",
        "  File \"site-packages\\twisted\\internet\\defer.py\", line 1299, in _inlineCallbacks",
        "    ",
        "  File \"site-packages\\lbrynet\\daemon\\Daemon.py\", line 2370, in jsonrpc_wallet_send",
        "    ",
        "  File \"site-packages\\lbryschema\\address.py\", line 27, in decode_address",
        "    ",
        "  File \"site-packages\\lbryschema\\base.py\", line 15, in b58decode",
        "    ",
        "exceptions.OverflowError: Python int too large to convert to C long",
        ""
      ]
    },
    "message": "Python int too large to convert to C long"
  },
  "id": 61,
  "jsonrpc": "2.0"
}
`

**Comment by kauffj** [comment]
IMO it'd be good to have a common `trim` property across text based inputs. If true, `String.trim()` should be applied on paste, on blur, and whenever the value is requested or stored.

**Comment by btzr-io** [comment]
Related https://github.com/lbryio/lbry-app/issues/564

**Comment by alyssaoc** [comment]
closing, has been fixed
