### ISSUE TITLE
Auto-claim YouTube Sync Reward

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#1063]
1. Add the reward `youtube_creator` to the list of possible rewards.
2. This reward should be automatically requested on first-run (? not 100% on this, but probably). No additional parameters are required to claim this reward.
3. If not claimed, the reward text should prompt a user to visit lbry.io/youtube to learn more.
4. If is claimed, or eligible to be claimed, the reward text should drive a user to `lbry.io/youtube/status/<token>` for full details.

After writing this out, I suspect most of this is done on the API side since that's where reward descriptions come from currently. All that the app needs to handle is step 1/2.

**Comment by kauffj** [comment]
@liamcardenas this is another one that needs to get bumped and would ideally make it into next release (so we're not blocked by an app-release to launch YouTube program).

@nikooo777 please see above and file any of this on lbryio/internal-apis that needs to be.

**Comment by alyssaoc** [comment]
@kauffj Do you still want this auto-claimed? The user might miss it if is automatic

**Comment by kauffj** [comment]
I think this can be closed.
