### ISSUE TITLE
Remove call to lbry.report_bug

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#1078]
This call is deprecated and will be removed in the next daemon release.

It is still being used by the `<ReportPage>` component.

Instead, an API call should be made directly to HelpScout.

**Comment by tzarebczan** [comment]
Already reported here https://github.com/lbryio/lbry-app/issues/759, feel free to close this one/mine

**Comment by kauffj** [comment]
See https://developer.helpscout.com/help-desk-api/

**Comment by seanyesmunt** [comment]
Can we make this call from the app? Or does it have to go through the api?

**Comment by tzarebczan** [comment]
Good point - since there is authentication required for the Helpscout API, we probably can't do this directly from the app right? @kauffj, thoughts?

**Comment by seanyesmunt** [comment]
I think it might be ok to keep the api key in the app, since it will be less prone to abuse than phone verification. Not sure if one is better than the other. Easier to keep it in the app

**Comment by kauffj** [comment]
@tzarebczan @seanyesmunt yes it can be in the app. It's already in the daemon (until `report_bug` dies) and there's no real difference.

It may be preferable to only check in a dev/test key (if such exist) and have the build process inject the real key, but I don't want to over-engineer this either.

**Comment by lyoshenka** [comment]
I put the daemon command back for now so this is not a release-blocker anymore. Turns out "deprecated" in the daemon actually means "removed".

**Comment by tzarebczan** [comment]
This is now going to internal apis on master, closing
