### ISSUE TITLE
Automated app tests

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-desktop#1080]
We need tests in the app. The best place to start is something simple and end-to-end (e.g. does the homepage load, does a video play)

Some considerations:
- how easy is it to write tests (the easier it is, the more like it is that we'll have good coverage)
- storing test metrics (how fast did homepage load? how long did it take video to play?)
- can travis run these tests
-

**Comment by alyssaoc** [comment]
closing in favor of #1776
