### ISSUE TITLE
thumbnail selector slider for videos and process automatically for other file types

### ISSUE THREAD

**Issue by liamcardenas** [lbryio/lbry-desktop#1088]
similar to spee.ch thumbnail slider

**Comment by tzarebczan** [comment]
From @kauffj: For other file types that we can process/view, we should automatically propose a thumbnail (e.g. when a PDF is uploaded, you could create an image from the first page). 

Should we still upload one automatically if the user chooses not to? 

Would go nicely with https://github.com/lbryio/lbry-desktop/issues/1968 and being able to crop/resize the thumbnail before it's uploaded (or maybe with some parameters on thumbnail url?)

**Comment by tzarebczan** [comment]
Completed in https://github.com/lbryio/lbry-desktop/pull/2492
