### ISSUE TITLE
App support for wallet encryption

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#1097]
### Enabling / Disabling Encryption

1. Add a setting to the settings page with a checkbox that says "Encrypt Wallet and Require Startup Password".
2. If checked, an additional input field (`type="password"`) folds out with a button to submit the password.
3. When submitted, call `wallet_encrypt` with the password.
4. If the checkbox moves from checked to unchecked (turning encryption off), call `wallet_decrypt`.

### Running the App

1. When `status` returns for the first time, check if `wallet_is_encrypted` is true.
2. If true, move the user to a single screen prompting for a password. Copying the existing UI of authentication is a good idea here.
3. When provided, call `wallet_unlock` and proceed assuming that call passes.

**Comment by tzarebczan** [comment]
More details about available commands here: https://github.com/lbryio/lbry-app/issues/762#issuecomment-352646085

I think we also have the ability to store the password in their auth token, but I haven't explored that option myself. See other comments from the linked issue above.

**Comment by skhameneh** [comment]
Working on this

**Comment by kauffj** [comment]
@skhameneh I believe by convention we're not closing issues until merged, even if the PR has been submitted.

Also, if you have Zenhub installed then you will see a "Connect with an Issue" button on the PR near the bottom of the page above the comments.

Using this will improve board organization and I believe auto-close the issue on merge.
