### ISSUE TITLE
Trim claim_id

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry-desktop#1169]
## The Issue
The claim id is too hard to read, remember and takes a lot of extra space.

### Steps to reproduce
1. Go to channel page.
2. See long channel name: `claim_name + claim_id`

### Expected behaviour
Trim or hide (if possible) the `claim_id` at least on channel page.

### Actual behaviour
A long string `id / name` appears and takes extra space.

### Solution

A nice approach would be the way github handles commits links:

| Commit link | Full commit hash
| --- | --- |
| https://github.com/lbryio/lbry-app/commit/fcdb935687daa8c9ce7bac5f67c14b061781d933 | `fcdb935687daa8c9ce7bac5f67c14b061781d933` |

We could integrate something like that in the app:

| Channel name | Full Channel / Claim id
| --- | --- |
| `@Sidequest#62dcc87` | `62dcc87d735db6627ca5bcb467ddad5af1bc341d` |

## Screenshots

![_claim_id](https://user-images.githubusercontent.com/14793624/37796484-a89329b8-2dd4-11e8-9aea-69a8e49fbfc5.jpeg)

**Comment by kauffj** [comment]
Related: https://github.com/lbryio/lbry/issues/958
