### ISSUE TITLE
Sometime, there is only title is displayed when clicking on "@xxxchannel name" at bottom of the Movie frame in "Discover" page

### ISSUE THREAD

**Issue by namujan78** [lbryio/lbry-desktop#1191]
## The Issue
Sometime, there is only title is displayed when clicking on "@xxxchannel name" at bottom of the Movie frame in "Discover" page (refer to **Image01** below)

### Steps to reproduce
1. Open app
2. Click on "@xxxchannel name" (example @karmakut, @imineblocks) at bottom of frame (refer to **Image01** below)
3. Repeat step 2 for about 10 times with others @xxx
**Frequency: 1/7**

### Expected behaviour
It should display full information with fetching contents... (refer to **Image02** below)

### Actual behaviour
Sometime, there is only title is displayed. (refer to **Image03** below)

## System Configuration
- LBRY Daemon version: 0.19.1
- LBRY App version: 0.21.2
- LBRY Installation ID: N/A
- Operating system: Windows (Windows-10-10.0.16299)
- Wallet (lbryum): 3.2.0

## Anything Else
N/A

## Screenshots
**Image01**
![image](https://user-images.githubusercontent.com/37721875/37939633-16ff2e30-318e-11e8-95a4-5fcd9e8f2ea9.png)
**Image02**
![unknown 2](https://user-images.githubusercontent.com/37721875/37939739-b825997a-318e-11e8-9198-b7d30006d78b.png)
**Image03**
![unknown 1](https://user-images.githubusercontent.com/37721875/37939744-bfee0dd6-318e-11e8-85b8-189c70f4943e.png)

**Comment by tzarebczan** [comment]
@namujan78 thanks for opening this! Sent you LBC on Discord for creating a well-defined issue.

How often does this happen to you? You mentioned that the page returns if you wait a bit - how long is that time usually? I'm thinking something is happening in the background on the daemon and it's waiting too long for a response. Another one of our pain points in terms of slowness is the wallet server which validates /returns claim information - something we are also working on improving internally.

**Comment by namujan78** [comment]
@tzarebczan I have just tried 2 times:
First time: wait about 2 minutes, it become normally.
Second time: wait about 4 minutes, it become normally.
this issue is not often, the frequency is about 1/6.
