### ISSUE TITLE
Windows: Installer does not kill daemon process

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1192]
## The Issue
When on 0.21.2 and running the 0.21.2 installer while LBRY is running, the installer tries to shutdown the lbrynet-daemon.exe process. Since two processes are spawn during app launch, the installer is able to kill the first, but not the 2nd because it's a child of a child. This becomes a concern during updates when we upgrade the daemon version because the user will have to kill the current daemon after app install and then re-install the app again so the new daemon is written into the file system. 

Startup process (per Igor):
App => Daemon process 1 => Daemon process 2

### Steps to reproduce
1. Run LBRY 0.21.2
2. Launch 0.21.2 installer process 
3. Notice that the daemon continues running and app restarts using that daemon process

### Expected behaviour
Installer should kill all daemon processes

### Actual behaviour
Daemon continues running

## System Configuration

 

- LBRY Daemon version: 0.19.1
- LBRY App version: 0.21.2
- LBRY Installation ID:
- Operating system: Windows

**Comment by tzarebczan** [comment]
We should look into this before the redesign release, especially if we will be updating the daemon along with it. 

I'll try this on Mac to see if it's happening there.

**Comment by IGassmann** [comment]
The solution has to be implemented on the daemon. The daemon has to kill its children process if it's being exited.

**Comment by tzarebczan** [comment]
We are working with the daemon team to see if they can get the daemon to run as a single process. If this is the case, we can update the predesign version to the latest daemon. 

The upgrade procedure would be:
1) Don't autoupgrade - close LBRY completely and download latest installer from lbry.io/get
2) Run installer manually

or (most will opt for this because they will see the message)
1) Run autoupdate 
2) App restarts to incompatible daemon screen which allows them to quit daemon and shows them https://lbry.io/faq/incompatible-protocol-version which walks them through making sure the daemon is killed, downloading installer and re-running

**Comment by tzarebczan** [comment]
Did a little more digging - went back to 0.21.2 to perform in-app upgrades and it looks like we have a different issue. When upgrading in app, you get 2 prompts to run the installer, one after another. If you wait for a few seconds after the first to click proceed on the 2nd, then you end up in a situation where LBRY is killed but the daemon is left running. Still not sure why there are 2 UAC prompts, but one  is run with --updated --force-run parameter and then a second time with --updated /S. I'll open a separate issue for this.

This issue (daemon not getting closed) is still valid, but it only affects manual installation while LBRY is running and not the in-app upgrade process.

**Comment by tzarebczan** [comment]
Opened https://github.com/electron-userland/electron-builder/issues/2894
