### ISSUE TITLE
Different categories within a channel

### ISSUE THREAD

**Issue by m160** [lbryio/lbry-desktop#1215]
## The Issue
People have various interests and LBRY allows for many different filetypes. This makes LBRY a great outlet for creative people. You can be a musician, photographer, videographer and writer all at once and put all your work in one place no matter if it's a .mp3, .jpg, .mp4 or .pdf. Your channel becomes a portfolio of all your creative work.

This is great for die hard fans that wants to follow everything you do. Chances are that most people are not interested in **all** your creative work though. Some might only be interested in your music, others might only be interested in your photography and so on.

Today you stand between two choices: Either you post everything on one channel and 'spam' followers with **all** your different content whether they're interested in it all or not. Or you make a separate channel for each interest. With many different channels you will constantly have to inform about your other channels, not to mention if you want to announce to your subscribers that you're going to attend that great LBRY conference next week, you'll have to do it for each channel seperately.

Neither is ideal. I think LBRY has an opportunity to innovate in this area.

### Suggested Solutions
An option for content creators to make custom categories within a single channel.
New subscribers get a pop-up with each category ticked:
:ballot_box_with_check: Music
:ballot_box_with_check: Photography
:ballot_box_with_check: Videography
:ballot_box_with_check: Literature

If they're interested in everything, they just confirm. If they're not interested in some of the categories they simply uncheck them. Now they only get notified when content is posted with the chosen category tagged.

It could even be taken a step further with subcategories:
:ballot_box_with_check: Music
> :black_square_button: Metal
> :ballot_box_with_check: Electronic
> :ballot_box_with_check: Orchestral

:ballot_box_with_check: Photography
> :ballot_box_with_check: Street photography
> :black_square_button: Portraits
> :black_square_button: Landscape

:ballot_box_with_check: Videography
> :ballot_box_with_check: Travel
> :black_square_button: Food

:black_square_button: Literature
> :black_square_button: Drama
> :black_square_button: Science fiction

Having a gaming channel with game reviews and let's play videos?

:ballot_box_with_check: Game Reviews
> :black_square_button: Playstation Games
> :ballot_box_with_check: Xbox Games

:ballot_box_with_check: Let's play
> :black_square_button: Counter-Strike
> :ballot_box_with_check: Battlefield
> :ballot_box_with_check: World of Warcraft

Now subscribers can really customize their subscription to only be served the content they're really interested in opposed to being 'spammed' with notifications about content they don't care about.

**Comment by tzarebczan** [comment]
@m160 thank you for filing this suggestion! This would most likely require development on the protocol side to be able nest channels in the way you described. I'll check if we have anything similar to this already and if not, I'll open the issue there.

**Comment by tzarebczan** [comment]
I think these can be covered under playlists, and we'll need to have https://github.com/lbryio/lbry-desktop/issues/6255 in order for users to be notified about them.
