### ISSUE TITLE
Feature requests for comments and tipping

### ISSUE THREAD

**Issue by m160** [lbryio/lbry-desktop#1216]
1. When a comments section is implemented, have a tip button next to comments. This can work as an incentive for people to leave better comments. Others can reward good comments with more than just thumbs up. (The publisher may, or may not, get a cut from the tipped comments on their content).

2. Show who has tipped content/comments and have the option to tip anonymously or under your channel name.

3. When commenting, have an option leave a tip with the comment. Comments with tips rank higher in the comments section.

**Comment by tzarebczan** [comment]
@m160 thanks for the suggestions!  We have a similar issue filed under: https://github.com/lbryio/lbry-app/issues/788 but we can keep both open for awareness.

**Comment by kauffj** [comment]
Using #4018
