### ISSUE TITLE
Make channel hyperlinks on tiles stick out more

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1251]
## The Issue
Channel links on claim pages used to be green and would underline when mousing over. We should make that they are clickable more apparent in the re-design.  Maybe a mouse over
![channels](https://user-images.githubusercontent.com/8120721/38217901-f2dda2ce-369d-11e8-8ada-92c3114f9f04.png)
 tool tip as well? 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by alyssaoc** [comment]
closing while tom is on vacation
