### ISSUE TITLE
Dynamic updates on Overview/Transaction page

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1258]
## The Issue
Currently, if you leave the Overview/Transaction page open, it will not update with any new transactions or change status from pending unless you leave/reopen the page. It would be a nice UX enhancement to have these pages update silently. 

Should we open a daemon side issue to allow transaction_list to have a parameter passed that would allow the return of recent transactions only so that the entire tx history is not fetched on each call?

### Steps to Reproduce
1. Send a tx
2. Go to history page
3. Wait
4. Tx does not update

### Expected Behaviour
Update transaction information silently

### Actual Behaviour
Have to leave page/come back to get update

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version: 0.19.1
- LBRY App version: master
- LBRY Installation ID:
- Operating system:

**Comment by ceoger** [comment]
well, i think a refresh feature on the transaction history page could be handy, so you'll just have to click a button to refresh the page whiles you await for transaction to be updated without having to leave the page

**Comment by tzarebczan** [comment]
There is now a refresh feature, we won't be updating dynamically.
