### ISSUE TITLE
Setting to keep Wallet and My LBRY tray open

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1265]
## The Issue
Currently, when you navigate away from either the Wallet or My LBRY pages, the tray closes and you need to expand it again to access to the various areas inside. It would be a nice UX improvement to allow the tray to be kept open - maybe some kind of pin icon next to the titles? 

![tray](https://user-images.githubusercontent.com/8120721/38263940-8414bb14-373f-11e8-8b3f-c34bc2d62b4d.png)

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
This should be another setting similar to how `enableOSNotifications` is implemented. 

We can have a new card `UI Settings` (better name to come) that will house this.

There may need to be some changes made to how links are handled. Currently, we change the top level header "Wallet", "My LBRY", etc to the last link visited.

**Comment by tzarebczan** [comment]
Solved in the latest side bar redesign
