### ISSUE TITLE
Add referral FAQ to Invites screen

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1282]
## The Issue
On the invites screen, add "Read our FAQ to learn more" after "Or an enemy. Or your cousin Jerry, who you're kind of unsure about." 

FAQ should be a hyperlink to https://lbry.io/faq/referrals

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by ykris45** [comment]
#1286
