### ISSUE TITLE
feat: receive push notifications

### ISSUE THREAD

**Issue by IGassmann** [lbryio/lbry-desktop#1296]
## User Story

As a user, I want to receive push notifications so that I can know about new videos with the app closed and without opening an email client.

### Windows
![image](https://user-images.githubusercontent.com/4291707/38393411-b9ea3f56-38f8-11e8-8209-d22e7f506830.png)

### macOS
![image](https://user-images.githubusercontent.com/4291707/38393495-f502c52c-38f8-11e8-8fdc-d4757d78babd.png)

## Good to Know

- Feature only available on Windows 10 and macOS.
- App has to be published to the Windows Store
  - Updates will have to be made through the Windows Store instead of using the auto-update feature. Fortunately, Windows Store updates are also automatic.

**Comment by tzarebczan** [comment]
This would require PWA to receive them in browser, which there's another issue filed for.
