### ISSUE TITLE
Email verification should not be required to happen on the same device

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#1299]
Some users will pull the verification email up on their phone rather than the computer they downloaded the desktop application on. The app should not require email verification to happen on the same device that it is installed on.

Instead, when on the email verification screen, the app can poll the API server periodically to see if the user has a verified email. It can then advance past this screen regardless of what device verification happens on.

**Comment by kauffj** [comment]
As I think about this more... why do we require the user to enter the token in the app at all? If the user clicks a link in the email, isn't this everything we need? @liamcardenas

**Comment by seanyesmunt** [comment]
@lyoshenka Does internal api's have everything needed when you click on the email link? Or can we implement that feature? I agree with @kauffj, the process of manually adding the verification code is very cumbersome.

**Comment by lyoshenka** [comment]
No, we'd need to make some changes on internal-apis side to make this work. I'm guessing to make it work really well, we'd need some way to notify the app that signin has occurred (long-polling? websockets? idk)

**Comment by seanyesmunt** [comment]
Polling wouldn't be hard. Websockets would be nice. I'm not sure what future use case there may be to have a websocket with internal apis.
