### ISSUE TITLE
Publish page - refreshing after clearing doesn't work as expected

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1357]
## The Issue
If you are in the middle of publishing and then clear the page (using the option in the top right), then press ctrl-R to reload the app and go back to Publish, the cleared text is re-inserted. 

### Steps to Reproduce
1. Start publishing 
2. Clear the page
3. Reload the app
4. Go back to Publish

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
This also happens if you Publish > dismiss modal > ctrl-R, then go to Publish to make a new one - the data form the previous publish is seen.

**Comment by Invariant-Change** [comment]
I can't recreate this issue. Has it been fixed?

**Comment by tzarebczan** [comment]
I'm able to reproduce it. Go to publish, enter data, leave screen, go back to publish, clear, ctrl-R. Edge case, but it happens :)

**Comment by tzarebczan** [comment]
This is no longer an issue.
