### ISSUE TITLE
Add support for .cbr and .cbz files (comics) in the app viewer

### ISSUE THREAD

**Issue by LavRadis** [lbryio/lbry-desktop#1377]
## The Issue

We had a comic author in the Discord who is interested in publishing his work on LBRY. Comics are a huge market and a lot of them come in .cbz or .cbr format (rar or zip files with images) or PDF. It would be great if we could have an in-app comic file viewer. There should be many open source viewers available. Here is one: [https://github.com/codedread/kthoom](https://github.com/codedread/kthoom)

**Comment by tzarebczan** [comment]
Thanks for opening this @LavRadis !

**Comment by btzr-io** [comment]
@LavRadis I'm currently working on one, it's open source and should be easy to integrate using an iframe or a `react-component`, I'll try to make a demo for next week...

If you have any features in mind just post it here.

**Comment by btzr-io** [comment]
Related https://github.com/lbryio/lbry-app/issues/932

**Comment by btzr-io** [comment]
@LavRadis here is the demo: 
https://btzr-io.github.io/comic_book_reader/#/reader

**Comment by LavRadis** [comment]
@btzr-io I've tested it and it works great!

**Comment by seanyesmunt** [comment]
@btzr-io Any plans to add that viewer for comics?

**Comment by btzr-io** [comment]
@seanyesmunt  currently is a web app, not sure if an `iframe` would work :upside_down_face:

**Comment by btzr-io** [comment]
If not we need to port it to a react component :stuck_out_tongue:

**Comment by seanyesmunt** [comment]
Ah I didn't realize that. Ok. Well this isn't a high priority, maybe someone will pick it up.

**Comment by btzr-io** [comment]
Due to the complexity of this viewer I decided to create a separate modular component:
> Small update on this issue:
I created a new react component (WIP) but it should be compatible with preact:
https://github.com/btzr-io/Villain

https://github.com/workhorsy/comic_book_reader/issues/121#issuecomment-491163549
