### ISSUE TITLE
Consider removing or updating welcome pop-up in app

### ISSUE THREAD

**Issue by DiSae** [lbryio/lbry-desktop#1380]
Please consider removing or updating the welcome text about a centaur when launching the app.
It's fun and good for giggles, but not really professional. Youtube also doesn't welcome you when visiting their website.
Also, if LBRY becomes a big thing in a few years, kids and elder people will use the app, they may not even know what centaurs are and be like 'what the heck did I sign up for'.

![lbry welcome](https://user-images.githubusercontent.com/31828724/39177520-d12353f4-47af-11e8-813f-9b2b673c368f.png)

**Comment by tzarebczan** [comment]
@DiSae thanks for the feedback, totally understand where you are coming from based on our discussion on Discord. I think we can get away with the playfulness/cleverness in the short / mid term :)

**Comment by alyssaoc** [comment]
this will be considered as a first user re-design
