### ISSUE TITLE
Mouse over tooltips in Explorer pages/tiles

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1388]
Currently we have some tooltips in the app but we don't on the homepage due to some weird css behavior.

In some cases, tooltips are cutoff if they extend beyond their parent container. There is some CSS fix that will need to be made. See screenshot:

<img width="284" alt="screen shot 2018-10-01 at 3 59 59 pm" src="https://user-images.githubusercontent.com/16882830/46312451-19e36f00-c593-11e8-8656-912244f5e17e.png">

**Comment by seanyesmunt** [comment]
starting on this

**Comment by seanyesmunt** [comment]
The new tooltip is in master. It was added to the community top bids section and on the search page. 

I also added it to the file page for featured content. Some work is still needed to get it on the file cards, there are some overlap issues. We can keep this open.

**Comment by tzarebczan** [comment]
@seanyesmunt can you share the pattern to add tooltips? I can try to help out in some places.
