### ISSUE TITLE
Add channel information on mouse over

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1393]
## The Issue
Per a suggestion from a reddit user, it would be a nice feature to have channel stats when mousing over anywhere in the app. Right now we can include how many videos are in the channel, but in the future we can include things like: # of subscribers, channel description, etc. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by shamoons** [comment]
What is considered a `channel`?

**Comment by tzarebczan** [comment]
@shamoons anything with an @ infront of it. You'll notice them on the discover page, show page and in other parts of the app. If there is no channel, it will show anonymous.

**Comment by seanyesmunt** [comment]
Possibly we could wrap anything we want to have a hover message in a custom comopent

```
<WithHover onHover="This is the hover message"> // that could also take a react component as props
    <UriIndicator uri={uri} />
</WithHover>
```

**Comment by tzarebczan** [comment]
We can now entertain this feature given we have channel metadata :)

**Comment by btzr-io** [comment]
Is anyone working on this ?

**Comment by tzarebczan** [comment]
@btzr-io , nope, she's all yours! I'd say it would be a condensed version of what's on the channel page - potentially total number of claims, title, canonical url (coming soon), description (truncated?), number of subs (coming soon), email, thumbnail, tip (not on channel page yet) and sub buttons.

**Comment by btzr-io** [comment]
I made some initial progress on this, just added some basic information (thumbnail, description and channel name):

<img src=https://spee.ch/1/channel-tooltip.gif />

**Comment by btzr-io** [comment]
I' don't think `email` is that important ?

**Comment by kauffj** [comment]
@btzr-io that looks awesome! I agree on not adding email or probably anything else.

**Comment by tzarebczan** [comment]
This was implemented in the latest release
