### ISSUE TITLE
Add "Tip the creator" button on channel page

### ISSUE THREAD

**Issue by LavRadis** [lbryio/lbry-desktop#1397]
## The Issue

To reward creator they subscribe to directly, users could simply use "Tip the creator" button inside subscription overview. The user could send a one-time donation in LBC.

**Comment by tzarebczan** [comment]
Thanks for filing! It should be fairly easy to add a tip button similar to the ones on the claim pages. This tip would go directly to the creator's channel as a support, as opposed to their content. They can choose to leave it (to increase their effective bid) or claim it (be able to use it).  

This button should also be added on channel pages.

**Comment by vv181** [comment]
@timurista Can I take over on the issue?

**Comment by timurista** [comment]
@vv181 sure, sorry I haven't been able to get to this. No Problem.
