### ISSUE TITLE
Rename this repo to lbry-desktop

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#1400]
Let's use this thread to build a list of actions required assuming that we'll do this.

- Create `lbry-app` repo so old links still work (if GitHub doesn't redirect after a rename)
- Fix links in lbry.io
- Fix links in lbry.tech
- Fix links/references in source

**Comment by tzarebczan** [comment]
Devs should run `git remote set-url origin https://github.com/lbryio/lbry-desktop.git` (or ssh URL)

https://help.github.com/articles/renaming-a-repository/

**Comment by kauffj** [comment]
@tzarebczan poke

**Comment by tzarebczan** [comment]
Just renamed it! The old URL should autoredirect. Github recommends it's safer to point local repos at the updated URL, see https://github.com/lbryio/lbry-desktop/issues/1400#issuecomment-387398545. 

Will follow up on fixing links in other repos and in this source.

**Comment by tzarebczan** [comment]
Reverting back for now: api redirects aren't handled well by github, so this result fails and the app crashes when going to the Help page on Windows/Mac, and crashes on startup for Linux: https://github.com/lbryio/lbry-desktop/blob/master/src/main/index.js#L172

**Comment by tzarebczan** [comment]
Will track LBRY app upgrade % (through new daemon release since we don't have version information) until it hits a critical point when it's safe to make this change. 0.21.5 has the fix for this.

**Comment by tzarebczan** [comment]
Done! A couple remnants that don't need to be changed: https://github.com/search?q=org%3Albryio+lbry-app&type=Code
