### ISSUE TITLE
Home/subscription scrolling state lost on navigation

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1402]
## The Issue
If you navigate horizontally using the arrows on the home/subscription pages, go into a claim, then go back, you end up at the left-most position (resets). Shouldn't it go back to where it was previously scrolled to? 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
I would say ideally it would, but it would be a decent amount of work. It
would require moving this data outside of the component, and into the redux
store. It wouldn't be that hard, but time consuming.

This would probably live in the `app` reducer

**Comment by tzarebczan** [comment]
This is no longer valid for the new app. Please open any restoration issue separately.
