### ISSUE TITLE
Large Images Won't Load Entirely The First Time

### ISSUE THREAD

**Issue by LeRatton** [lbryio/lbry-desktop#1439]
Portrait Style Images Won't Load Entirely
- I uploaded some pictures to my @Danielo channel using Spee.ch. Some pictures were portrait style with the height length longer than the width. These pictures load 100% when viewed on Spee.ch but won't load completely when viewed on the LBRY app for the first time. The images then show 100% after going back out of the Lightbox to the root and viewing the image a second time.

### Steps to Reproduce
1. Load Portrait Style picture to LBRY chain using spee.ch
2. Open LBRY App
3. Search and View picture
4. The picture will stop loading
5. Go Back out of the Lightbox and open the image again
6. The image will show correctly.

### Expected Behaviour
The image should load 100%.

### Actual Behaviour
The image stops loading at 50% to 70% below.

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

![screen shot 2018-05-06 at 11 19 23 am](https://user-images.githubusercontent.com/29220975/39676422-66443d5e-511f-11e8-92a4-0041c1499bfe.png)

![screen shot 2018-05-06 at 11 20 19 am](https://user-images.githubusercontent.com/29220975/39676434-93518d2e-511f-11e8-95ab-74e3354e5ef0.png)

## Screenshots

![screen shot 2018-05-05 at 11 51 33 pm](https://user-images.githubusercontent.com/29220975/39676467-315fa67c-5120-11e8-8623-194996e3de72.png)
![screen shot 2018-05-05 at 11 49 27 pm](https://user-images.githubusercontent.com/29220975/39676468-319658a2-5120-11e8-9f51-f82bd12a1306.png)
![screen shot 2018-05-05 at 11 48 33 pm](https://user-images.githubusercontent.com/29220975/39676469-31b12ac4-5120-11e8-95c1-425eada1a4d9.png)

**Comment by tzarebczan** [comment]
@LeRatton good find and thanks for filing!  Can confirm this is also happening on the pre-redesign version.

**Comment by tzarebczan** [comment]
Happening here too: lbry://TotW-NYC on a landscape photo. I'm pretty sure it has something to do with file size. It may be trying to read the file before it's fully written. Adding to the video player epic.

**Comment by seanyesmunt** [comment]
Fixed with new player
