### ISSUE TITLE
"No Content Found" When Navigating Through Video Contents By Page Using The Page List

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry-desktop#1472]
## The Issue

So i go to subscriptions, and click on a channel name, this channel has about 108 videos, i then try to navigate to the numbers one by one, like 104 then i click 104, 106 like that, and when i keep selecting the numbers and shows no results.

This happens when I keep navigating through the numbers a little faster, it takes a little while to load, and this happens often when i do not wait long enough for each number to load completely before clicking another number

### Steps to Reproduce
1. go to subscriptions
2. click on a channel name
3. try to navigate to the numbers one by one, like 104 then i click 104, 106 like that, and when i keep selecting the numbers little faster

### Expected Behaviour
It should take you to the page selected for the contents to load

### Actual Behaviour
Instead, The the numbers showing the list of videos disappear and shows no results. or  The numbers will still be there and yet displays no results or nothing found

### Suggested Solutions
The number page should be responsive whenever a specific number page is called at all times.

## System Configuration

- LBRY Daemon version: 0.19.3
- LBRY App version: 0.21.4
- LBRY Installation ID: 3cXLZiAWXwwJbv4fjhbXVgFtaBuUiFQM7afXmFYu5ss1chD1WCpxGUp8aW68gjeNRC
- Operating system: Widows 10

## Screenshots

https://cdn.discordapp.com/attachments/377895389992321064/444182779597684736/search.JPG

**Comment by tzarebczan** [comment]
@ceoger can you see if this still happens? In the last version we added caching to channels. Rarely I'd run into a message about "no content found" briefly but it ends up loading.

**Comment by ceoger** [comment]
I checked now and everything looks fine, I get the video list for each number I select.

**Comment by tzarebczan** [comment]
Can you modify this issue or create a new one to fix the "no content found" message when navigating? Maybe you can grab a screenshot of it too!

**Comment by tzarebczan** [comment]
Going to close this as it doesn't happen anymore. There may still be a short loading hiccup with "no context found", but I think multithreading enhancements will improve this.
