### ISSUE TITLE
watch script for redux changes

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1485]
## The Issue
Currently when developing in the LBRY app and making redux changes, redux needs to be rebuilt and the app needs to be refreshed manually in order to see changes. 

One proposed solution would be some type of watch script that could handle this scenario and automatically perform the necessary actions in order to see the most recent changes. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by skhameneh** [comment]
My general approach:
- Add `webpack --watch` as `yarn dev` command to `lbry-redux`
- Add `./node_modules/lbry-redux` to the watch paths in `lbry-desktop`

**Comment by skhameneh** [comment]
I should have a working PR shortly 😃
