### ISSUE TITLE
Download search only works for full word matches, it should work for partial string matches too

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#1489]
## The Issue
To see a downloaded file, I need to type one full word that matches a piece of metadata for that file.

### Steps to Reproduce
1. Download a file, ex: lbry://iconoclasts-review-the-wrench-of-freedom#2b4a3ee4d865c66e6f2545a74c0f21f0ac02d0f3
2. Search for "icono" and notice it doesn't match
3. "iconoclats" does work

### Expected Behaviour
It should find files from partial string matches

### Suggested Solutions
The change will need to be made to this function https://github.com/lbryio/lbry-redux/blob/master/src/redux/selectors/file_info.js#L109 

Instead of checking individual words against the file metadata, we can just concat all the metadata into one long string. Then break up the search query by spaces and do a regex search against the long string on each query part.

**Comment by jeffslofish** [comment]
I'm not sure when this got fixed, but as of the latest release, v0.44.0, partial string matches are working great for downloaded content. I recommend this issue be closed.
