### ISSUE TITLE
yarn dev:offline - Stub lbry data and allow the app to run offline for dev

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#1491]
This definitely issn't a pressing issue but it's something I've thought about for a while and it would be really nice (ex: wanting to do dev on a plane)

This would involve stubbing all the lbry calls, so I think most of it would go inside `lbry-redux`

Not really sure what kind of changes would be necessary, and ideally it wouldn't change the code very much.

**Comment by alyssaoc** [comment]
closing for a future world
