### ISSUE TITLE
Black screen on LBRY video player

### ISSUE THREAD

**Issue by samdisk11** [lbryio/lbry-desktop#1524]
### Steps to Reproduce
1. Use Sony Vegas 13.0 to render a .mp4 video
2. upload MP4 to LBRY
3. attempt to view video

### Expected Behaviour
Tell us what should happen.

The video should be playing like this (example)
![image](https://user-images.githubusercontent.com/24478471/40580944-31f214ca-6111-11e8-8b66-24f6a6245482.png)

### Actual Behaviour
Tell us what happens instead.

The video's music plays with a solid black screen, as shown here.
![image](https://user-images.githubusercontent.com/24478471/40580953-5de42e10-6111-11e8-9663-2ca6847ec4da.png)

### Suggested Solutions
Tell us your suggested solutions if you have any.

Repair/Replace the video player or use external program to play video (VLC is a good candidate)

## System Configuration

![image](https://user-images.githubusercontent.com/24478471/40580962-92cfe844-6111-11e8-8c6d-fefe1acc0fa2.png)
 please PM me if you NEED the email

- LBRY Daemon version: 0.19.3
- LBRY App version: 0.21.4
- LBRY Installation ID: 8HVF913zcxrSRHcyhJy6yhsy612pVoFMY7iV6R6NP298gZoX6wdg8x561NkQZD9sjH
- Operating system: Windows 10 Pro, Build 1511

## Anything Else

the video does play on VLC and other video-playing programs.

## Screenshots

 the actual video in Sony Vegas 13.0 :
![image](https://user-images.githubusercontent.com/24478471/40580977-0997741a-6112-11e8-90e7-6c3c381b0f08.png)

the bug: 
![image](https://user-images.githubusercontent.com/24478471/40580984-37fb7a5e-6112-11e8-84ef-60ba518e9c2a.png)

**Comment by tzarebczan** [comment]
Some codes may not be supported by the video player. Try running the mp4 through handbrake with the web optimized setting, please see https://lbry.io/publish for more info about recommended upload formats.

Can you bring up the console (ctrl shift I) and check for any errors while playing. Thanks! 

The app player needs some work to support additional formats.

**Comment by samdisk11** [comment]
it uses the codecs listed in 
https://lbry.io/publish 
and i used handbreak but it is still black.

**Comment by kauffj** [comment]
@tzarebczan can you try seeing if the file plays fine in other players so we can figure out of it's an encoding or player/app issue?

**Comment by skhameneh** [comment]
Hey @samdisk11 can you open your file in VLC, press `CTRL+J` and share the information?  
  
That would be very helpful

**Comment by tzarebczan** [comment]
@skhameneh see here: https://www.screencast.com/t/I2yms80Z4Yt, looks like it's in mpeg format. I tried the video on instant.io (uses our same player, and the screen is blank there too). It's probably just an unsupported codec in render-media. 

Stephen reached back to out to @samdisk11 on Discord and was able to convert his file via handbrake, which resulted in a playable file within the app. 

I have a tasker to do a bit more research on our current player limitations and see if the render-media maintainer would like to do some work for us.
