### ISSUE TITLE
Integrate Cura (3D File Slicing) Source Code for in-app .gcode (geometric code) exporting 

### ISSUE THREAD

**Issue by jamesbiller** [lbryio/lbry-desktop#1527]
When a standard 3D file type like STL or OBJ is downloaded onto a maker's computer the maker has to "slice it" using a slicing program, the most popular of which is [Cura, fortunately, their code is open source.](https://github.com/Ultimaker/Cura) 

The new file type is called a .gcode

What would be awesome is if we could offer OBJ & STL file-slicing in-app so that users don't even have to go to a separate app like Cura to prepare their file for their 3D printer's specifics.

**Maybe users don't even download the STL or OBJ files, but only download the .gcode that they actually need.**

This would give LBRY App a practical benefit over 3D file-sharing sites like Thingiverse & MyMiniFactory because it would cut-out a step in the making process- the need to slice.

Users initially wouldn't be prompted to download .gcode, but after they've clicked 'download' on any STL or OBJ file there should be a message that comes up saying something like "Input your printer's .gcode requirements and skip the step of slicing."

Then whenever makers click "download" LBRY app is actually slicing a .gcode in the background.

Makers should also be prompted on whether or not they would like to download the STL/OBJ file, maybe a checkbox saying "Check here if you'd still like to download the original file"

I don't think that this should take a super long time since the Cura code is open source.

**Comment by alyssaoc** [comment]
closing
