### ISSUE TITLE
Batch resolving for downloads/related/search

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1531]
## The Issue
Somewhat related to https://github.com/lbryio/lbry-app/issues/1203 - currently, we run a separate resolve for each claim in downloads/publishes. We should batch these into larger resolve calls, each with X (homepage does 80+) URLs. 

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
@tzarebczan Does the daemon handle batched calls quicker? Would it wait to return until it has the data for all urls? I think it would be ok to resolve individually since they are quick and it lets a user see files as soon as they are ready.

**Comment by seanyesmunt** [comment]
Cool. I agree some testing is needed.

**Comment by tzarebczan** [comment]
This is happening now with related/search.
