### ISSUE TITLE
Add draggable feature to Picture in Picture if PR 1523 gets merged.

### ISSUE THREAD

**Issue by dan1d** [lbryio/lbry-desktop#1535]
No one asked @kauffj to chime in :D, but what he said makes a lot of sense to me and actually helped me to almost finish issue #579 
Copied [from here](https://github.com/lbryio/lbry-app/pull/1523#issuecomment-393588369)

@kauffj commented:
It's always good to look at what other well-designed sites do that have spent a lot of time thinking about this (e.g. maybe Netflix or Twitch?)
While I support draggability, I actually don't consider draggability to be a core requirement for this to be finished. It's a nice-to-have. As an example, Twitch doesn't even appear to support moving the window they provide.
If the window is draggable, it ought to retain it's position, even across sessions/restarts.
I'd support being able to drag the window via a click and hold anywhere on the entire component
I'd also support showing a titlebar on mouseover similar to what Twitch always shows on their component. This titlebar could have both a close icon and a move icon. The move icon wouldn't really be any different than clicking-and-holding, it'd just serve as an additional cue.

**Comment by alyssaoc** [comment]
closing, will re-evaluate with new video player
