### ISSUE TITLE
The end of the video should have a re-play button

### ISSUE THREAD

**Issue by DaniNz** [lbryio/lbry-desktop#1567]
### Steps to Reproduce
1. End a video 
2. There is no button to replay

### Expected Behaviour
Should have a replay button when the video ends.

### Actual Behaviour
At the end of a video there is the possibility to see it again, but there is no visible way to replay the video, except for the mouse pointer when hovering in the video.

### Suggested Solutions
Add a button with the **watch again** action.

## System Configuration
- LBRY Daemon version: 0.19.3
- LBRY App version: 1.8.7
- LBRY Installation ID: 7ouMXkWNi2G1Q4HVLzEVDHqZtDAGLhr69C91XSbetVLP9DQscyevMgGFinWmVThtrg
- Operating system: Linux (Linux-4.15.0-22-generic-x86_64-with-Ubuntu-18.04-bionic)

## Anything Else
Maybe when the video ends, in addition to the button, the video container may have some opacity.

## Screenshots
![screenshot from 2018-06-08 17-47-21](https://user-images.githubusercontent.com/16692007/41181751-43017f34-6b49-11e8-8506-99589db330b4.png)

**Comment by tzarebczan** [comment]
@DaniNz do you plan on working on this?

**Comment by DaniNz** [comment]
yes @tzarebczan, I'll work on this.

**Comment by DaniNz** [comment]
yes @tzarebczan, I'll work on this.

**Comment by tuxfoo** [comment]
The default behavior atm is to auto-play another video.
If you turn off the autoplay, then when the video ends you can just click play to watch it again.

Are you suggesting that the play button change to a replay icon?

**Comment by kauffj** [comment]
Rolling this into #2921 which is expected to be worked on soon and closing this ticket
