### ISSUE TITLE
Cannot play large (4+GB) video in app

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1577]
## The Issue
Might be related to https://github.com/lbryio/lbry-app/issues/937, recently tried playing a file which is 4.8 GB and the app player says "sorry you can't play this file" and then the app becomes slow/unresponsive. 

### Steps to Reproduce
1. Play lbry://theunmasking-part3-theprojections
2. Let it download
3. Can't play video / app performance may degrade

### Expected Behaviour
Tell us what should happen.

### Actual Behaviour
Tell us what happens instead.

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by btzr-io** [comment]
https://github.com/feross/render-media/issues/28

**Comment by alyssaoc** [comment]
@tzarebczan  is this still an issue?

**Comment by seanyesmunt** [comment]
Fixed with new player
