### ISSUE TITLE
Log time to video start

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#1578]
It'd be good to collect some explicit data here, especially so we can see improvements related to @shyba's work.

**Comment by seanyesmunt** [comment]
This should be pretty straight forward.

Start a timer when user clicks play, then stop the timer when the content actually starts to play. @kauffj is that what you were thinking?

**Comment by tzarebczan** [comment]
See discussion in https://github.com/lbryio/internal-apis/issues/452#issuecomment-408924440 for app side changes required
