### ISSUE TITLE
Show smaller NSFW tag if it's my content

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#1581]
## The Issue
If I have `Show NSFW content` unselected, and have published NSFW content, the title and thumbnail will not be visible. We should still show them.

### Steps to Reproduce
1. Make sure `Show NSFW content` is unselected in settings
2. Publish a NSFW claim
3. View your list of published claims

### Expected Behaviour
I should be able to see the title/thumbnail for every claim I've published

### Actual Behaviour
NSFW content isn't fully visible

### Suggested Solutions
`fileCard/view.jsx` should check if the url is mine, if it is, ignore NSFW

**Comment by seanyesmunt** [comment]
After https://github.com/lbryio/lbry-app/pull/1585 we don't show the NSFW cover which is much better, maybe we don't even need to show a NSFW marker? If we do show it, i'm not sure how it should be presented. I'll keep this open for now if anyone has ideas.

**Comment by alyssaoc** [comment]
closing
