### ISSUE TITLE
Review isPlayable() function

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1590]
## The Issue
Related to work done for https://github.com/lbryio/lbry-app/issues/1503 

Some zip files (and possibly other formats), like the one at lbry://ScreenToGif12-50-45590#f8866c585e39d26f87039547e0c51b2614280eb0, show up as playable files (show Play button and then say "this file cannot be played"). We should review the isPlayable function to ensure it only shows play on valid media types (reference render media?). 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
Render media: https://github.com/feross/render-media

This is a powerful package that handles many file types like video (.mp4, .webm, .m4v, etc.), audio (.m4a, .mp3, .wav, etc.), images (.jpg, .gif, .png, etc.), and other file formats (.pdf, .md, .txt, etc.).

**Comment by tzarebczan** [comment]
Sample files:
Text: lbry://textfile#e39b887ff0c06438f673067f94243b33bde44518
HTML: lbry://htmlfile#67f030c9c658d2797ddfa08ee5657e6896759044

**Comment by tzarebczan** [comment]
The above was only happening with https://github.com/lbryio/lbry-app/pull/1589  that didn't end up getting merged. Will keep open as we should investigate this line change: https://github.com/lbryio/lbry-app/pull/1589/commits/daeb02cd3777c5aa7ed4ef46656719f3b8a0e10d#diff-df116a02bf8da7997de2245267390707R118

**Comment by tiger5226** [comment]
the default [mime.json](https://github.com/feross/render-media/blob/master/lib/mime.json#L80) has .zip in it. So wouldn't that find a match if we passed in .zip? 
Instead of trying to find in the mime set, we should instead check against [MEDIASOURCE_EXTS](https://github.com/feross/render-media/blob/master/index.js#L30) which should only give us audio/video formats.

**Comment by tiger5226** [comment]
fixed with https://github.com/lbryio/lbry-app/pull/1623

We just need to compare mediatype and only allow video and audio to be playable.

**Comment by tzarebczan** [comment]
Reverting the above PR since it doesn't take into account image types.

**Comment by btzr-io** [comment]
Also `pdf`, `3D-files`, `e-books`

**Comment by tzarebczan** [comment]
@btzr-io lbry://mpgfile#077ec523f7a6950476cd071d3190228e564b4472 shows play for an mpg file.  https://github.com/sinabio/Eleven - old.

**Comment by seanyesmunt** [comment]
I think we can close this. We properly show the view button.
