### ISSUE TITLE
"Open Log Folder" opens the wrong folder

### ISSUE THREAD

**Issue by LavRadis** [lbryio/lbry-desktop#1600]
## The Issue
The new button "Open Log Folder" does not open the folder. It opens the "Roaming" folder. 

### Steps to Reproduce
1. Just click "Open Log Folder" button in the Help section
2.
3.

### Expected Behaviour
it should open the proper folder with log file

## System Configuration

- LBRY Daemon version: 0.20.0
- LBRY App version: 0.22.0-rc.11
- LBRY Installation ID: 7tYN144rHXrspzJG9xLP28fi1JztXnbpKro6DBJEQyzBmXTyDgqRLfYsUvHYFVmMe2
- Operating system: Win 10

**Comment by tzarebczan** [comment]
It does open to the parent folder of lbrynet and highlights it, but yes, it should go into the lbrynet folder itself. It looks like a pretty simple fix/refactor.
