### ISSUE TITLE
Open Folder Button for Backups

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry-desktop#1601]
As per ***open folder button*** for **logs**. Would be good and **consistent** to have one for **backups** too.

![image](https://user-images.githubusercontent.com/29914179/41470057-c2c847c6-70f2-11e8-9867-3709da30bdb0.png)

**Comment by tzarebczan** [comment]
@amitnndn looks like another perfect one for you :)

**Comment by Grayyyyy** [comment]
I've created the button, pushing a commit now

**Comment by Grayyyyy** [comment]
Had a lot of IRL stuff happen recently, but I’ll try to pick this back up 🙂

**Comment by tzarebczan** [comment]
This is implemented in the latest app along with a way to zip a backup.
