### ISSUE TITLE
Some users are sent to home screen after a file is deleted

### ISSUE THREAD

**Issue by LavRadis** [lbryio/lbry-desktop#1602]
## The Issue
Some users (one guy named Tom) report that after they delete a claim in "Downloads" they do not stay in that folder but the app focuses on the main screen. 

### Steps to Reproduce
1. Go to "Downloads" and delete one of the claims which are not yours. If you are sent to different app part, you have the issue. 
2.
3.

### Expected Behaviour
The user should stay on the claim page after they delete a downloaded file. Unless it's their published claim that they are deleting, then it should go to home/publishes.

## System Configuration

- LBRY Daemon version: 0.20.0
- LBRY App version: 0.22.0-rc.11
- LBRY Installation ID:
- Operating system: Win 10

**Comment by LavRadis** [comment]
I have tried to reproduce the issue but in my app installation, I remained in the "Downloads" folder. @Electron also.

**Comment by tzarebczan** [comment]
This is expected.
