### ISSUE TITLE
Users can't differentiate which one is OLD or NEW (latest) video in homepage

### ISSUE THREAD

**Issue by iamuditpatel** [lbryio/lbry-desktop#1605]
to fix this problem we have to add date or something like 1day ago, week ago, year ago like that or we should add "new" label in the bottom of thumbnail too..

![lbry3](https://user-images.githubusercontent.com/11346292/41474929-f98937e2-70da-11e8-842d-f3cd0bdcea01.PNG)

**Comment by kauffj** [comment]
IMO if we're showing a relative/age date it should be from time added to LBRY, not the original creation date of the content.

If there are performance concerns about calling `block_show` 100 times on the homepage, we could simply do an approximately accurate calculation app-side.
