### ISSUE TITLE
Investigate E2E testing solutions

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#1607]
It would be great to have some sort of end to end tests in the app.

No idea what it would take, or what resources are out there. This issue is just to explore different options available.

**Comment by tzarebczan** [comment]
Have something similar filed under: https://github.com/lbryio/lbry-app/issues/1080

**Comment by seanyesmunt** [comment]
👍 This one is just for investigating. I think that can stay open for implementing them.

**Comment by skhameneh** [comment]
Here's what I've found

- Spectron is _the_ tool to use for Electron -> https://github.com/electron/spectron
- Spectron is unopinionated and calls out Mocha, Jasmine, AVA, and Chai.
- I'm a fan of Mocha and their unopinionated model, combined with Chai; Jasmine is the primary tool for Angular dev (less relevant here).
- AVA looks like a nice new(er) test runner with improvements over Mocha; I am very interested in what AVA has to offer.  It's had time time to mature and it looks like a great contender.

Overall, I'd suggest taking a deeper look at Spectron + AVA.
I'm really liking what I see -> https://github.com/avajs/ava

**Comment by skhameneh** [comment]
I spent a considerable amount of time on this.

Universal findings:
- `electron-webpack` does not work well with `spectron`, see electron-userland/electron-webpack#75

Dev + Spectron:
- All attempts to get basic Spectron methods stall or fail, e.g. `client.waitUntilWindowLoaded()` stalls indefinitely.
- The application will execute within the test script, no testing interfaces work as expected.

Production + Spectron:
- The unpackaged app does not run easily in production mode, it looks like `electron-is-dev` is uglified out to `"renderer"===process.type` which results in a false positive.  Adding additional fallback checks such as `process.env.NODE_END === 'production'`help resolve this.
- The production output relies on `process.resourcePath` (converted from `__static`) which is a hard coded value, see https://github.com/electron/electron/blob/3d4487ccfd08341ea1cd93bc98fa50a24f3f5902/electron.gyp#L472
- Changing `process.resourcePath` to a valid path allows the app to start, but only a green background renders.  It appears this breaks other dependency paths.
