### ISSUE TITLE
Improve Wallet Backup UX

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#1635]
1. If we're printing the path, let's use the input type that makes it easy to select and copy it. Most likely the identical component used for Receiving Credits in the Wallet would work.

2. Add a button that opens the folder or file directly.

**Comment by tzarebczan** [comment]
We have a pr for the button already.. Probably just needs some positioning/styling fixes. 
https://github.com/lbryio/lbry-app/pull/1628

Agreed with the copyable field.

**Comment by Grayyyyy** [comment]
I'll try to work on 1. too
