### ISSUE TITLE
Add loading screen after publishing, before success message

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1647]
## The Issue
After you click the publish button, the content get's unfocused (as if you were starting a new publish) and then a few seconds later, you get the modal with the success message. We should add a loading indicator during this process.

### Expected Behaviour
Tell us what should happen.

### Actual Behaviour
Tell us what happens instead.

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
Just going to disable the file input for now. In the future we will add some loading styling on the confirmation modal

**Comment by tzarebczan** [comment]
A user just ran into what he thought was a bug because the publish took longer than expected (will happen with larger files). I think a loading screen would have at least let them know something was in progress.

**Comment by seanyesmunt** [comment]
I think for now we can just add the spinner component next to the button when it's publishing.

**Comment by shahsank3t** [comment]
@tzarebczan @seanyesmunt - I would like to contribute to this issue if it's still open.

**Comment by jessopb** [comment]
@shahsank3t Thanks! I'm about to PR my publish changes for llbrytv which somewhat deal with this issue.

**Comment by shahsank3t** [comment]
@jessopb cool, no worries :)

**Comment by jessopb** [comment]
New "publishing..." empty state
and a couple more tests with and without confirmation needed.
