### ISSUE TITLE
After deleting videos locally, videos get stuck and need to restart to get the workaround.

### ISSUE THREAD

**Issue by vv181** [lbryio/lbry-desktop#1662]
## The Issue
Deleting locally a downloaded video then opening it again on LBRY shows its stucks on "Waiting for Metadata". The app needs to be restarted to get the workaround, then it shows "the files missing, rebuilding".
### Steps to Reproduce
1. Play / Download videos
2. Delete the file locally on the drive
3. play the videos, it gets stuck at "Waiting for metadata"

### Expected Behaviour
It should show "the files missing, rebuilding" text. but it only happens after if we restart the app.

### Actual Behaviour
Stuck at "Waiting for metadata"

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version: 0.20.1
- LBRY App version: 1.8.7
- LBRY Installation ID: 9KLc1UCu9qGpkZ3NF2CGY1rfJhFb9zikrLHM9GqPyC7nRdHdxANjv8iamafRvUDgGh
- Operating system: Linux x64

**Comment by tzarebczan** [comment]
Thanks for filing! Easiest solution would be to refresh fileinfo when going into a file page.

**Comment by tzarebczan** [comment]
This will be fixed in the next release. Should work as long as the file isn't deleted when you are on the page (very unlikely), without refreshing.
