### ISSUE TITLE
Missing Community URL Info on Cards

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry-desktop#1667]
When you have **multiple** items, all with the same **title** and **thumb**, it's hard to know which one is which if you need to edit one.

This might also be a problem for content which have the same thumbs with **similar titles**, which are **truncate**, so you **can't** see the last part, such as "**Part Two**"

Showing the **Community** URL would be suffice, avoiding the long tailed permanent URL's which wouldn't fit well here.

![image](https://user-images.githubusercontent.com/29914179/41714526-f44b7f3e-7593-11e8-98bb-42c3833fbe24.png)

**Comment by tzarebczan** [comment]
We used to have this a while ago, the solution would probably be https://github.com/lbryio/lbry-app/issues/1394

**Comment by alyssaoc** [comment]
@tzarebczan Can this be closed in favor of #1394

**Comment by tzarebczan** [comment]
@alyssaoc yep, added information about the URL to #1394
