### ISSUE TITLE
Use TinyPNG API in App to Compress Files Before Sending to Spee.ch

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry-desktop#1670]
## Smaller Files = Faster Files, Less Storage, Less Overheads.

[TinyPNG ](https://tinypng.com/developers) is a service I can't live without for my web development work, even after professionally compressing in Photoshop, I can still save a further 40% with [TinyPNG](https://tinypng.com/developers).

Many/most content providers have no idea how to compress images for the web. With this in the LBRY app, they wouldn't have to, they would get vastly small files without having to do anything.

[TinyPNG ](https://tinypng.com/developers) supports lossless, lossy and resizing. Lossless should be mandatory with other options being optional.

However, there is a charge, like Amazon AWS. But if it works out that you save more from smaller files then it's not only worth in terms of finance, but also in terms of having a better experience with faster files and less congestion.

The below image (thumbs.jpg) was a typical image a typical user would upload to LBRY.

![image](https://user-images.githubusercontent.com/29914179/41731043-b639cfca-75c0-11e8-84d4-96dacee05ff8.png)

**Comment by Invariant-Change** [comment]
**Example:**

```
curl --user api:YOUR_API_KEY \
     --data-binary @thumbs.jpg -i https://api.tinify.com/shrink
```

**Comment by btzr-io** [comment]
Open source: https://github.com/lovell/sharp

**Comment by Invariant-Change** [comment]
I was going to suggest adding an open source option but didn't know of any or if they produced good results. I'll see if there is a test area for the one above and give it a go.

**Comment by alyssaoc** [comment]
@tzarebczan should this be closed in favor of 1770?

**Comment by tzarebczan** [comment]
Issue moved to [lbryio/spee.ch #599](https://github.com/lbryio/spee.ch/issues/599) via [**ZenHub**](https://www.zenhub.com/)
