### ISSUE TITLE
Price Can Change When Scrolling in Edit 

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry-desktop#1674]
## Price Can Change When Scrolling in Edit

On several occasions the **Price** has changed when I've **scrolled** to the publish button at the bottom of the page. I only become aware of this **after** publishing, so then I have to go back and **re-edit**.
This could lead to content providers **accidentally** selling their content at a vastly **reduced price** or **higher** price if they scroll up.

#### My two suggestions to fix this are as follows.

1. Make the **mouse-wheel** value change a `Ctrl+Scroll` event. User shown they can do this in a `Tool Tip`.
2. Have a **confirmation pop-up** when the **publish** button is **clicked**, detailing all the provided info and asking if it's **correct** - `YES` or `NO`. If `NO`, user is sent back to the **editor**.
3) Both.

![image](https://user-images.githubusercontent.com/29914179/41779884-81b25e28-7676-11e8-848e-31334a778137.png)

![scrollwheel](https://user-images.githubusercontent.com/29914179/41780399-f5ebae7e-7677-11e8-9732-0c962f61a60f.gif)

**Comment by tzarebczan** [comment]
Not only in edit, but in Publish mode too. Yea not sure how I feel about this, but ran into it myself also. Clicking shift and scrolling isn't intuitive, and a tooltip doesn't really help there. 

@seanyesmunt wants to add a confirmation prompt, that would be a separate issue.

**Comment by Invariant-Change** [comment]
But more importantly, do you like the mouse wheel gif? 😂

**Comment by seanyesmunt** [comment]
Hoping to add a confirmation modal at some point. We should be able to just disable mouse scroll on these inputs.
