### ISSUE TITLE
Feature Request: Download-button on thumbnails

### ISSUE THREAD

**Issue by m160** [lbryio/lbry-desktop#1676]
## The Issue
There's no easy way to prepare content for later. Say I'm on the **Explore** page and I discover several videos I want to watch, but before watching I want to scroll through the **Explore** page to see if there's anything else I want to watch too. I either have to try to remember everything so I can click through it later, or I have to click into each video and press download so it gets stored in the **Downloads** of **My LBRY**. That's a lot of unnecessary back and forth clicking though. 

### Expected Behaviour
When hovering over thumbnails a 'download' or 'watch later'/'add to playlist' button should appear, clicking it downloads the content in the background while you continue exploring.

When done exploring, the content can be found in **Downloads**, or even better, **Watch Later**/**Name of Playlist** which of course has a 'Play All' button that subsequently goes through all the content with no additional clicking. Depending on how much time was spent on exploring, there's no waiting for anything to download either. Win-win!

**Comment by seanyesmunt** [comment]
I think a basic version of this would include an icon that appears when you hover over the file card. 

This could go in the top corner of a file card. 

It should use the same icon as the one we use as for the download button on the file page. 

Maybe we could add a tooltip? I don’t know if we need one. 

I would try to copy the YouTube experience for their “watch later” button.

**Comment by abueide** [comment]
@seanyesmunt I'm sorry I'm new to the project. Could you explain where the file page is and where to find the download icon used there?

**Comment by m160** [comment]
I guess this one can be closed as the feature is now implemented. Thank you! :)

**Comment by tzarebczan** [comment]
Thanks for the heads up!
