### ISSUE TITLE
Set and document icon naming standard

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#1683]
Should icon constants be named after the icon display or the icon purpose?

For example, should the constant for the subscribe icon, currently a heart, be `HEART` or `SUBSCRIBE`?

Typically (e.g. FontAwesome), icons are named after the display. But I'd actually argue that for a single application, the icons should be named after the purpose (i.e. `SUBSCRIBE` would be a better name than `HEART`).

Traditionally icons are named after the display, but I think once you are in a specific application, naming for purpose is superior since it helps encourage you to use the icon in one and only one way.

Either way, I'd like a choice made here and a short comment added to the top of the file indicating which you should do.

**Comment by seanyesmunt** [comment]
I'm beginning to think it should be based on the purpose. Mainly to prevent the same icon being used for two different actions.

Ex: If we had a like button, maybe someone would just see the `HEART` icon and use that. If it was called `SUBSCRIBE` instead the chance of that happening is much lower.

**Comment by seanyesmunt** [comment]
Done in https://github.com/lbryio/lbry-desktop/pull/2221
