### ISSUE TITLE
Show progress for blockchain_headers download on first launch

### ISSUE THREAD

**Issue by akinwale** [lbryio/lbry-desktop#1686]
Currently, the daemon downloads the `blockchain_headers` file when the app is launched for the first time, and the only message displayed on the desktop splash screen is "Catching up with the blockchain...".

The daemon's `status` call has been updated to return 2 additional fields in the `blockchain_status` property.
`is_downloading_headers` which is a boolean flag that indicates whether or not the headers file is being downloaded.
`headers_download_progress` which represents the percentage progress of the file download.

With these fields available, a progress bar can be displayed to the user which improves the user experience.

For additional details, please refer to:
* https://github.com/lbryio/lbry/issues/1263
* https://github.com/lbryio/lbry-android/pull/188 (Android mobile implementation)

**Comment by seanyesmunt** [comment]
Blocked until the next daemon release

**Comment by seanyesmunt** [comment]
Closing this in favor of #1728
