### ISSUE TITLE
Handle ERR_CONNECTION_RESET and restart app without quitting

### ISSUE THREAD

**Issue by LavRadis** [lbryio/lbry-desktop#1689]
## The Issue
Before testing the RC15, my RC14 did not start the automatic upgrade prompt. After few moments it reported the ERR_CONNECTION_RESET. After clicking "OK" on the error message, the entire app crashed. I remember one-two other users reporting the same error.
Tom has my logfile on Discord.

### Steps to Reproduce
1. Not sure how to reproduce it.
2.
3.

## System Configuration

- LBRY Daemon version: 0.20.2
- LBRY App version: 0.22.0-rc.14
- LBRY Installation ID: 4bV2hxTd3CkUuRGaXtstb2x822HHfaSu59WM3FGzMgMwU2zB7cTP1nJDhNoZQy8kVb
- Operating system: Windows (Windows-10-10.0.17134)

## Screenshots
![lbry net error rc14](https://user-images.githubusercontent.com/10566738/41875866-7ab9d896-78cc-11e8-96c1-21e2e64327e3.jpg)

**Comment by tzarebczan** [comment]
Thanks for filing! We'll need to deal with daemon resets better in more general terms.  Maybe the app can start the daemon back up instead of quitting.

**Comment by tzarebczan** [comment]
The daemon log shows:
```
2018-06-25 22:42:18,096 ERROR    lbryum.socket_pipe:58: pipe (socket error): [Errno 10054] An existing connection was forcibly closed by the remote host
2018-06-25 22:42:18,098 WARNING  lbryum.interface:186: connection closed remotely
2018-06-25 22:42:18,177 ERROR    lbryum.socket_pipe:58: pipe (socket error): [Errno 10054] An existing connection was forcibly closed by the remote host
2018-06-25 22:42:18,177 WARNING  lbryum.interface:186: connection closed remotely
```

**Comment by tzarebczan** [comment]
@shyba will take a look into this from lbryum side

**Comment by shyba** [comment]
@tzarebczan maybe this was related with that bug that got solved during restart? that caused troubles on startup if one of the wallet servers were out?
lbryum is being deprecated and the wallet servers got a new release. I wonder if the new one still disconnects or if it got solved.

**Comment by tzarebczan** [comment]
Haven't seen this in a while, may have fixed itself with Electron updates.
