### ISSUE TITLE
Suggestion: Separated NSFW section for mainstream adoption

### ISSUE THREAD

**Issue by m160** [lbryio/lbry-desktop#1695]
## The Issue
Having hardcore porn on the front page will hold LBRY back from mainstream adoption.
It will make me and others less inclined to promote our content on LBRY and can even make content creators go elsewhere. It also makes LBRY unsuitable for kids, which is a huge demographic.

### Steps to Reproduce
1. Open app
2. Scroll down to Community Top Bids
3. Porn:
![capture1](https://user-images.githubusercontent.com/34570404/41916882-16989d74-7927-11e8-9f1b-bbaefc066408.PNG)
Alternatively:
![capture2](https://user-images.githubusercontent.com/34570404/41916890-19271926-7927-11e8-98b5-51fcf8cea143.PNG)

### Expected Behaviour
No NSFW content on front page.

### Actual Behaviour
NSFW content on front page.

### Suggested Solutions
NSFW content should have its own section that is hidden by default. To show the NSFW page/tab you would have to unlock it in the settings. The unlock should also have the option to be password protected so kids can't go and unlock it easily.

Keeping it separated is better for everyone: Those who are not interested in NSFW don't have to see it, and those who are interested get it all in one place. NSFW content having its own place in the app also makes it possible for it to have its own top bids and trending etc.

Everyone wins the way I see it :)

## System Configuration

- LBRY Daemon version: 0.20.2
- LBRY App version: 0.22.0
- LBRY Installation ID: 2XLeCW8MRiQYbQvU57s3aFVvvGFqymwMuBngLZTL9qWHNazFkSauVgyq6Hdib8ieqr
- Operating system: Windows 10

**Comment by tzarebczan** [comment]
The business team decided that this section should be called "LBRY After Dark" if and when it's implemented.

**Comment by tzarebczan** [comment]
Closing this with the new design - no more community top bids. The next steps would be giving users more control over granular items they see/don't see in the app.
