### ISSUE TITLE
Sidebar too narrow to fit Subscription count on larger displays

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1705]
## The Issue
See below
![bleed](https://user-images.githubusercontent.com/8120721/41977230-ceaef3b6-79ec-11e8-9813-7d9672844d6b.jpg)

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
Reopening: https://www.screencast.com/t/HS3BiqDU

**Comment by seanyesmunt** [comment]
Will be fixed in https://github.com/lbryio/lbry-desktop/pull/1817 since I'm making some changes to the side bar
