### ISSUE TITLE
Feature request: Option to keep LBRY on top of other windows

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1706]
## The Issue
Suggestion from a community member was to have an option (maybe in the tray?), to force LBRY to stay on top of other windows.  Maybe there's a way to do this with Electron.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tombiju** [comment]
@tzarebczan I'd like to try this out if it's still needed

**Comment by BrannonKing** [comment]
This is plenty doable, but what would be the purpose?

**Comment by kauffj** [comment]
Not sure what resuscitated this ticket (and apologies for not acknowledging you soon @tombiju - a contribution would still be most welcome!), but I think this should just be closed as it can be done at the operating system level.
