### ISSUE TITLE
Misleading thumbnails (or lack thereof) on channel pages

### ISSUE THREAD

**Issue by m160** [lbryio/lbry-desktop#1708]
## The Issue
With the limit of only displaying 10 thumbnails on the channel pages, some can be misled to believe that this is all the content on a particular channel, especially if the screen size/resolution leaves an open space on the two last thumbnail 'spots' (see screenshot below)

There's a 'go to page' below the thumbnails, but it can be off the screen in window mode.

### Steps to Reproduce
1. Go to channel page
2.
![capture](https://user-images.githubusercontent.com/34570404/41948240-c9232d58-7989-11e8-8bde-e16baae43354.jpg)

### Expected Behaviour
All 'spots' having a thumbnail if there's enough content on the channel.

### Actual Behaviour
Two 'spots' are blank.

### Suggested Solutions
1. Display thumbnails in the empty spots.
2. Put a tile in the empty spot saying 'Next Page'.

## System Configuration
- LBRY Daemon version: 0.22.2
- LBRY App version: 0.22.0
- LBRY Installation ID: 2XLeCW8MRiQYbQvU57s3aFVvvGFqymwMuBngLZTL9qWHNazFkSauVgyq6Hdib8ieqr
- Operating system: Windows 10

## Anything Else
Would be nice if more thumbnails was displayed on each page of the channel too.

**Comment by tzarebczan** [comment]
Thanks for filing this! My original suggestion was to have some type of indicator at the end that more pages are available - since some people overlook the page indicator at the bottom. Another option is to fetch content dynamically to fill up the entire area (doesn't solve the issue of users not knowing there's a next page). I'm sure @Invariant-Change would want lazy scroll here - and maybe that's now possible with the quick resolve times :)

**Comment by m160** [comment]
I put that under suggested solutions: **2. Put a tile in the empty spot saying 'Next Page'.**
When the page is filled up with thumbnails it's more natural to try to scroll though.

If lazy scroll is what YouTube does, I prefer pages. A couple more rows of thumbnails per page would be nice though.

**Comment by tzarebczan** [comment]
We also discussed bringing in more than 10 results: https://lbryio.github.io/lbry/cli/#claim_list_by_channel

**Comment by tzarebczan** [comment]
Closing, this is no longer an issue after increasing number of tiles on channels.
