### ISSUE TITLE
Improve channel definition experience on Explore page

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1717]
## The Issue
When using channel definitions, there are a few issues on the home page:
1) The styling of the channel name is different from the rest of the categories
2) No way to pass a channel description from our API
3) When new users load the app (or after going to Settings > clear the cache), the row is blank until resolved. 

The channel definition is currently returned as: `"@CryptoCandor#9152f3b054f692076a6882d1b58a30e8781cc8e6" : [],`

1  & 2 are solved by allowing/parsing channel descriptions from the API. the API will return something like (tbd, but I'm sure @kauffj / @lyoshenka would want to weigh in): 
`"Description goes here" | @CryptoCandor#9152f3b054f692076a6882d1b58a30e8781cc8e6" : [],`
or
`"@CryptoCandor#9152f3b054f692076a6882d1b58a30e8781cc8e6" : ["Description goes here"]`

Note: Try to maintain backward compatibility if possible, but if the solution proves to be cleaner, go in that direction. 

3) Sean suggested something similar to for loading tiles:
![screenshot_20180628-174957](https://user-images.githubusercontent.com/8120721/42064107-faa0bcc2-7b02-11e8-8436-02ca7e78f684.png)

At a minimum, it should set the min-height. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
Fixed in 1711

**Comment by tzarebczan** [comment]
The content URLs are now passed from Chainquery. Will create separate issues for making the channel name be clickable and for loading tile revamp.

**Comment by tzarebczan** [comment]
Closing in favor of https://github.com/lbryio/lbry-desktop/issues/1819 / https://github.com/lbryio/lbry-desktop/issues/1820
