### ISSUE TITLE
Support new daemon startup process

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1728]
## The Issue
When https://github.com/lbryio/lbry/pull/1164 is merged, the status calls returned to the app will be different. From [changelog](https://github.com/lbryio/lbry/blob/26098879e77149fc8401b0e9f04436964f83013c/CHANGELOG.md#removed):
`STARTUP_STAGES from status API and CLI call, it instead returns a dictionary of components along with their running status(this is a potentially breaking change if STARTUP_STAGES is relied upon) `

This might be a good opportunity to make the startup messages more user friendly. 

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
@tzarebczan Is this different from #1686 ?

**Comment by seanyesmunt** [comment]
Oh. Just saw you referenced a PR, which has been reverted.
