### ISSUE TITLE
Nothing Happens When You Click On Continue After Getting Authentication Failure Message

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry-desktop#1732]
## The Issue
Nothing Happens When You Click On Continue After Getting Authentication Failure Message At The App Start Up
### Steps to Reproduce
0. Close LBRY app from the taskbar/ kill LBRY process
1. Change date and time settings to some months back(maybe 2 months back)
2. Open LBRY app and you get Authentication Failure
3.  Click continue and nothing happens

### Expected Behaviour
Tell us what should happen.
When the user clicks continue, something should happen, or warning message like (check time and date settings and try again)
### Actual Behaviour
Tell us what happens instead.
Nothing happens when you click continue

### Suggested Solutions
Tell us your suggested solutions if you have any.
I solved this problem of Authentication failure by making sure the system time and date was correct, once it was set correct, the message never comes up and lbry loads fine, so there should be a message that prompts the user to make sure their date and time are correct when they get the Authentication Failure message. this message can pop up when they click continue as nothing happens when *continue is clicked* as at now

## System Configuration

- LBRY Daemon version: 0.20.2
- LBRY App version: 0.22.0
- LBRY Installation ID: 	42HthHLazo5VAqJvoditQUxCkTm7QxNKyuJt5idW593ektCzUR5fdLnqWTKje9Pcdo
- Operating system: 	Windows (Windows-10-10.0.15063)

## Anything Else

The `Authentication Failure ` message was due to the time and date being wrong and dating back to April 2018, no amount of troubleshooting got the app to load pass the Authentication failure issue can be reproduced in the same way mentioned above 

## Screenshots

https://cdn.discordapp.com/attachments/440189329139171350/464495435814273055/date.JPG

**Comment by tzarebczan** [comment]
Thanks for filing this Clement! It could be a modal issue with the continue button. If someone does continue, I don't think the app will function correctly without an API key, but that case might be different for the date/time issue. 

Can you tell if an API key is passed via the network tab when this occurs?

**Comment by ceoger** [comment]
it only gives err_insecure_response, the insecure response in my opinion is cos of the wrong date/time.
usually that is what you will get in an actual web browser when the date is wrong, you get certificate error and insecure connection error

another thing i just saw was when i click anywhere on the page, it reloads, anywhere on the lbry app

https://cdn.discordapp.com/attachments/440189329139171350/464561321489334332/unknown.png

**Comment by tzarebczan** [comment]
@seanyesmunt I'm guessing this is another close modal issue, I'll try to take a look myself :)

**Comment by tzarebczan** [comment]
Keyring has been removed, this should no longer be an issue
