### ISSUE TITLE
Ability to search within channels

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbry-desktop#1735]
Depends on https://github.com/lbryio/lighthouse/issues/90

When on the channel page, searching should search within the channel results only. There will be a new parameter to the search api where a channel can be specified. 

Also referenced in https://lbry.io/news/lbry-development-community-update-june-2018

@seanyesmunt any particular vision for this or is this above what you had in mind?

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by seanyesmunt** [comment]
Yeah that is basically it. Somewhere there will be a search input on the channel page. Longer term it might be nice if we could include `similar content`?

Ex:
```
- On channel A
- Search term returns 0 results for channel A
- Search api returns x results for search term so the user isn't looking at a blank screen.
```

After typing that out though I think it might be better to just show a button on the page if there are no search results `Search other channels for this content` or something.

**Comment by seanyesmunt** [comment]
The api is documented here https://lbryio.github.io/lighthouse/

**Comment by seanyesmunt** [comment]
Added in #2887
