### ISSUE TITLE
Civic Integration 

### ISSUE THREAD

**Issue by ElectronEsq** [lbryio/lbry-desktop#1737]
## Optional Civic Integration 

Optional Civic integration to **protect** wallets, enable or prevent viewing of **NSFW** and to prevent **rewards abuse**. It could make the app **safer**, more resistant to **scams** and more **family friendly**.
Or just use for rewards to prevent **abuse**. It would be a **good** partnership.

[![image](https://user-images.githubusercontent.com/29914179/42417653-d6f09a86-82d2-11e8-8575-802d03cc8081.png)](https://www.civic.com/)

**Comment by LavRadis** [comment]
or lbry should develop its own identity app. it would be in line with developing the lbry ecosystem. you could obtain your LBRY CARD to access any of the apps! (i'm not sure how are they called in the usa)

**Comment by tzarebczan** [comment]
Thanks for creating this issue! Something we should definitely explore. I remember looking into this a while ago but Civic wasn't well developed. Does anyone want to do research into what it would take to get this integrated?

**Comment by Invariant-Change** [comment]
They have a [Civic Community Developer Program](https://www.civic.com/developers/community-developer-program/)

**Comment by tzarebczan** [comment]
Think I've done that already and dm'd with him about it (a while ago) . Now it's just a matter of digging into their api and integrating it.

**Comment by Invariant-Change** [comment]
Seems pretty straightforward. Create a [JWT token](https://docs.civic.com/#Browser) to authenticate a users account. The rest is done via Civic I guess?

https://docs.civic.com/#Browser
