### ISSUE TITLE
Show Community Top Bids only when NSFW enabled

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1742]
## The Issue
As an immediate step to make the Explore page friendlier for all audiences, only show the Community Top Bids if the NSFW setting is enabled. 

Do we want to hint at its existence / explain how to enable on the explore page? 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
Please make sure that there is some cue to new users that this exists and do not just silently hide it.
