### ISSUE TITLE
Add recommended content to File Page

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#1743]
This is part two after #1249 is implemented

## The Issue
Currently there is no way to discover content on the File Page

### Expected Behaviour
There should be some list of files to view (semi) related to the file you are currently viewing.

### Actual Behaviour
There is nothing on the File Page except the content you are viewing.

### Suggested Solutions
Possibly perform a search based on the title? That would be a good step in the right direction. Not sure what the exact search query would be. It couldn't be the exact title, but probably some snippet of it.

**Comment by tiger5226** [comment]
Sean, the way elastic search will work if you send in the title is it breaks down each word in the title and returns the results based on the scoring of those words in other claims. I think that is a great solution actually. I would just make sure you ignore the highest ranking result which would be itself.
