### ISSUE TITLE
"Upgrade on Close" doesn't close because multiple modals open

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1747]
## The Issue
If a user has the LBRY app open and an update is out, it will create a modal every 10 minutes. So if you try to click the "Upgrade on Close" button - it won't actually close because you need to click it multiple times.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by doniyor2109** [comment]
I have tested "Upgrade on Close"  button but it works as expected

**Comment by doniyor2109** [comment]
What is the platform name that the case occurred?

**Comment by tzarebczan** [comment]
@doniyor2109 - did you leave the app open more than 10/20 minutes? The upgrade on close stack up on one another when the updater checks for new updates. This would only happen on Mac/Windows.

**Comment by doniyor2109** [comment]
I waited sometime nothing happened. I will wait sometime again

**Comment by tzarebczan** [comment]
Nothing is meaning you weren't notified of an update or you didn't run into the modals stacking?

To reproduce, you must download an earlier version like https://github.com/lbryio/lbry-desktop/releases/tag/v0.22.2

**Comment by tzarebczan** [comment]
@doniyor2109 you should be able to reproduce if you are on 0.23.0 (0.23.1 launched today) on Windows/Mac.

**Comment by doniyor2109** [comment]
Sorry for late response. Can you check the PR for the issue? I have linux so I could not test it.
