### ISSUE TITLE
Add warning when opening files externally

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1761]
## The Issue
When using the open button (and possibly when clicking the file location at the bottom of a downloaded claim), we should warn users that they are opening at their own risk. FIles played inside the app are sandboxed, but anything opened externally could be a risk. Maybe we only do this for non-playable/viewable types? 

It would be similar to the modal when clicking a hyperlink in a claim. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
This should use the same styling as the `openExternalLink` modal. Maybe we can combine them into one modal?

@btzr-io This might be a good one for you if you are interested.

**Comment by tzarebczan** [comment]
This was completed in https://github.com/lbryio/lbry-desktop/pull/2478
