### ISSUE TITLE
Improve UX around returned results setting

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1764]
## The Issue
We recently added the ability to change the number of search results returned. If a user changes this setting, the search page is not automatically refreshed with the new number of search results. It seems only new searches take the setting into account. So if you search "test", change the setting, and search "test" again, it won't take the new setting into account. It does take it into account for new search terms. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
closed with #2282
