### ISSUE TITLE
Snackbar blocks other notifications (snackbars/modals)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1767]
## The Issue
If a snackbar is shown on the screen, other actions which result in a notification (modal/snackbar) are blocked until the snackbar disappears. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
Easy to reproduce:

- go to the `Send & Receive` page
- populate the `send credits` fields (amount & address)
- click the `copy address` button
- click the `send` button to open the confirmation modal
  - This will be delayed until the snackbar goes away for the `address copied` message

**Comment by tzarebczan** [comment]
Doesn't seem to be an issue anymore.
