### ISSUE TITLE
Subscriptions should autodownload on startup

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1775]
## The Issue
We tell users that "This app will automatically download new free content from channels you are subscribed to." but this only occurs if you had the LBRY app opened while the content was posted. We should be auto-downloading subscribed free content (lastest single upload) on app startup. 

## System Configuration

- LBRY Daemon version: 0.20.3
- LBRY App version: 0.22.2
- LBRY Installation ID: Private
- Operating system: Windows

**Comment by tzarebczan** [comment]
@daovist you are working on this in your autodownload branch, right?

**Comment by daovist** [comment]
yes
