### ISSUE TITLE
Rewards refresh enhancements

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1780]
## The Issue
1) To support tiered rewards, we should refresh the reward list after a reward is claimed. 
2) Instead of calling the reward list when going to the Rewards page, call it on the Overview page. This ensures that the user is shown accurately rewards information on Overview. 

@tiger5226 can you confirm that the next level in a tiered reward will be available right after the previous level is claimed successfully?  I'm assuming they should only see 1 level at a time. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tiger5226** [comment]
They will see 1 level at a time, and once claimed they will see the next level if the api is called again. This work is ready and should be merged for our internal-apis soon, specifically for many download levels and subscription levels.

**Comment by kauffj** [comment]
This shows merged so I'm closing, re-open if I'm missing something.
