### ISSUE TITLE
Feature Suggestion: Option to enable/disable desktop notification

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1788]
## The Issue
Currently, we use desktop notifications when a file has completed downloading. These notifications may extend to other areas in the future. 

A setting to enable/disable these notifications should be available for users who don't want to to see them.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by dan1d** [comment]
Hi I've added the setting there, should I create a new section?
![screenshot from 2018-07-30 21-10-53](https://user-images.githubusercontent.com/3293616/43429990-170e0434-943d-11e8-9cea-01cdac97c374.png)

**Comment by tzarebczan** [comment]
Merged in master with https://github.com/lbryio/lbry-desktop/pull/1834, will be in next release.
