### ISSUE TITLE
Arm build problems

### ISSUE THREAD

**Issue by kodxana** [lbryio/lbry-desktop#1790]
### Expected Behaviour
Build script produce .deb file
### Actual Behaviour
Crash at fpm step.

### Suggested Solutions
Scripts download fpm x86 package. Mayby it is possible to use system instaled fpm insted of packaged version downloaded from github.
Link to package: https://github.com/electron-userland/electron-builder-binaries/releases/tag/fpm-1.9.3-2.3.1-linux-x86_64

## System Configuration
Raspberry Pi 3 Model B armv7l
- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system: Rasbian stretch

## Screenshots
![obraz](https://user-images.githubusercontent.com/16674412/42958005-946559e4-8b84-11e8-9346-fe8600d4a8df.png)
![obraz](https://user-images.githubusercontent.com/16674412/42958013-9be98a00-8b84-11e8-817e-e29d6c88af74.png)
![obraz](https://user-images.githubusercontent.com/16674412/42958032-a8c1873c-8b84-11e8-964b-5dab42a4601a.png)
![obraz](https://user-images.githubusercontent.com/16674412/42958044-b53a6178-8b84-11e8-9878-5560a6d6ee15.png)

**Comment by tzarebczan** [comment]
@kodxana should we close this?

**Comment by kodxana** [comment]
Yup :)
