### ISSUE TITLE
Sorting on channel page different from Subscriptions page

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1805]
## The Issue
When there are multiple claims in the same block, sorting differs on the channel page vs the subscriptions page. See lbry://@Dota2Divine#2d2c1a3dc98ca868d1f2bfe76b8a1bb820857c5a as an example. 

Note: You'll have to be subbed to more than 1 channel to see the bug. 

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
Discussed with @seanyesmunt, he'll take a look at this one. If not addressed, it may make it seem like subscriptions are not working properly. Having multiple claims in the same block will be common for youtube synced channels.

**Comment by seanyesmunt** [comment]
On the channel you linked to I see the same sorting

**Comment by tzarebczan** [comment]
Replied on Slack and updated issue: you need to be subbed to more than 1 channel, that's when this bug rears its ugly head.

**Comment by tzarebczan** [comment]
Looked like it was fixed, but still coming up as an issue in some scenarios. 
![image 1](https://user-images.githubusercontent.com/8120721/44736016-0f2d4a00-aabc-11e8-8fd9-8e30aa236445.png)

**Comment by tzarebczan** [comment]
Sorting should be the same now on release date.
