### ISSUE TITLE
Publish screen shows it's in editing mode on first run (no publishes)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1807]
## The Issue
When running the app for the first time, you'll see "edit this file" even though you aren't editing anything. This is because this line returns "undefined" = "undefined" - https://github.com/lbryio/lbry-desktop/blob/32942ed349c5587a60da3e406efb29781ed35003/src/renderer/redux/selectors/publish.js#L66

See state here: https://www.screencast.com/t/Y1x4EgWZc

On another machine with publishes, currentname shows as my last published item, even though the publish page is blank. State shows this item.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
The issue is with the `parseURI` command returning `"undefined"` (string) instead of an actual `undefined` value
