### ISSUE TITLE
Differentiate between blank and incorrect URL on Publish thumbnail preview

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1808]
## The Issue
Currently, the same "broken" image is shown when there is no URL or an incorrect URL is entered. We should differentiate between the two scenarios to make it clearer for the user. 

![thumb preview](https://user-images.githubusercontent.com/8120721/43147556-4e1f441c-8f31-11e8-9e6f-d97acb41d6cf.jpg)

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by dan1d** [comment]
Hi, I would need an icon image to be inserted on this issue. Code is ready to be reviewed but I'm missing a second icon.
Fail url:
![screenshot from 2018-07-27 17-53-10](https://user-images.githubusercontent.com/3293616/43346123-6f106d80-91c6-11e8-95a4-f16f6a07fa90.png)
Blank url
![screenshot from 2018-07-27 17-53-21](https://user-images.githubusercontent.com/3293616/43346127-71e09b20-91c6-11e8-9dc0-62cd7a188ac3.png)

**Comment by tzarebczan** [comment]
Implemented on master via 1829, will be in next release.
