### ISSUE TITLE
Social sharing options

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1810]
## The Issue
Currently, the only thing that comes close to social sharing is the "View on Web" button that's available for free images/videos which opens a spee.ch page for the content. The goal is to allow users to share content from LBRY on their blogs or other social platforms. There would be predetermined formats/links for popular platforms like Facebook/Twitter/Reddit (spee.ch also has Tumblr). 

At a minimum, the open.lbry.io URL (https://github.com/lbryio/lbry-redux/blob/711806d1a427aece672881f218207cd9b14a62fa/src/lbryURI.js#L232) would be shown to the user. If a spee.ch link is available, there should be an option to include that as well.

The new social sharing area would prepopulate a narrative around the shared content to include the title and channel (if available, with a hyperlink?), provide a lbry.io/get link to download the app and allow the user to add any comments. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
@jessopb please post some of your mocks ups here as well :)

**Comment by seanyesmunt** [comment]
I just commented in gitter. Not sure why I didn't get any notifications when I was tagged.

**Comment by jessopb** [comment]
I'm pretty happy with this. If feathericons had a reddit icon, I'd add it; Youtube can demonstrate the potential share-to-reddit api functionality.

One small detail is that the only thing I see in the app that uses the color_secondary is the clipboard button and that color is just close enough to color_primary to look like an unintentional error. What is color_secondary for and is it even necessary?

![modalcandidate](https://user-images.githubusercontent.com/36554050/46239907-be846780-c36d-11e8-85b0-88b0544d37d1.png)
![modalcandidatedark](https://user-images.githubusercontent.com/36554050/46239908-be846780-c36d-11e8-8437-611b2aef9f5d.png)
![modalnowebcandidate](https://user-images.githubusercontent.com/36554050/46239909-be846780-c36d-11e8-8a95-7a4de7d225f5.png)
