### ISSUE TITLE
Determine when to run list_featured API call

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1812]
## The Issue
When featured content is pushed to the homepage, users won't see the ribbon unless they refresh the app since the list_featured call is only made on startup. Should it be called when the homepage is? Call in the background? 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
Candidates for times to call it:

1) When rewards are refreshed
2) Whenever discover / suggested is refreshed
