### ISSUE TITLE
Videos on Explore showing incorrect fee

### ISSUE THREAD

**Issue by 42degrees** [lbryio/lbry-desktop#1813]
Some videos on the Explore page are showing the incorrect fee information.  I have LBRY set to be NSFW (I have covered the offending thumbnails).

Here is what I see:
![2018-07-24_11-11-58 showing incorrect fee for video](https://user-images.githubusercontent.com/1676142/43154991-4dff0a10-8f33-11e8-8962-cfe0e1f958bd.png)

All three of the videos at the bottom of the image initially showed up as "Free" in the Explore page.  Clicking into the video showed that the video actually does cost money.
![2018-07-24_11-12-23 showing correct fee for video](https://user-images.githubusercontent.com/1676142/43155015-69873406-8f33-11e8-9740-65f8cb56a163.png)

Once it has displayed the correct fee on the video page, it gets displayed properly in the Explore page as well.  This happened consistently for all three of these videos.
![2018-07-24_11-12-37 now showing correct fee for video](https://user-images.githubusercontent.com/1676142/43155033-7bb31c3a-8f33-11e8-9c05-ec320a334a72.png)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
This is an edge case during a takeover bid and when the user hasn't refreshed their LBRY app in a while. There was a fix applied for the claim page with https://github.com/lbryio/lbry-desktop/issues/797. 

I'll keep this open, but the more generic issue to tackle might be: https://github.com/lbryio/lbry-desktop/issues/451

**Comment by kauffj** [comment]
Hey @42degrees, just wanted to say thanks for some of the thorough, well-written issues you've filed as well as your first contrib. I'm guessing @tzarebczan has already hooked you up with some LBC, so this is just a thank you from me and the rest of the LBRY team!

**Comment by 42degrees** [comment]
@kauffj Thanks for the compliment.  @tzarebczan has indeed been throwing shekels my way ;-)

**Comment by 42degrees** [comment]
@tzarebczan I had just upgraded to the new beta of LBRY, so I had definitely refreshed my LBRY immediately before seeing this error.  And that release had a new daemon as well, so that was brand new when I saw this problem.

**Comment by tzarebczan** [comment]
We'll see if we can get the same fix applied from https://github.com/lbryio/lbry-desktop/pull/1563 to other areas, or remove this cost-refresh dependency completely.

**Comment by tzarebczan** [comment]
This should now be fixed.
