### ISSUE TITLE
0.23 does not play, even when it has successfully downloaded

### ISSUE THREAD

**Issue by 42degrees** [lbryio/lbry-desktop#1814]
I clicked on a video, hit play.  The download counter went from 0 to 80 something percent (I wasn't watching it all that closely) then went away as if it had completely downloaded.  It would not play.  I backed out then came back in.  I hit play again and it shows "Waiting for metadata" but at the bottom of the page it says, "Downloaded to: [file]" and I checked the file and it plays fine in VLC Media Player, so it did download the file.  Here's a screen shot:

![image](https://user-images.githubusercontent.com/1676142/43155781-919e62f0-8f35-11e8-8042-eaf79a29d8b9.png)

**Comment by tzarebczan** [comment]
It's not an H264 MP4, so our in-app player doesn't support it. https://www.screencast.com/t/p2rIeElBe06W

Closing in favor of https://github.com/lbryio/lbry-desktop/issues/635 / https://github.com/lbryio/lbry-desktop/issues/1003
