### ISSUE TITLE
Deleting file issue in Windows, cannot download content after deleting (until restart)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#182]
## The Issue
After downloading a file, I clicked Options > Remove. When prompted to delete the file to from my PC, checked Yes.  The file does not get deleted, and instead, the permissions on the file get screwed up where I can't delete it normally from my download folder (don't have read access anymore).  

This usually happens when you try to download, play and then remove a few times. 

### Steps to reproduce
1. Download Video
2. Remove Video and check remove from PC
3. 

### Expected behaviour
File should get removed, allow to redownload

### Actual behaviour
File does not get removed, permissions are changed, cannot delete manually. Cannot redownload. See below for screenshot

## System Configuration

 

- LBRY Daemon version:
- LBRY App version: v0.11.9
- LBRY Installation ID:
- Operating system: Windows

## Screenshots

![lbry permissions](https://cloud.githubusercontent.com/assets/8120721/26702577/9d5eecda-46f3-11e7-9ecf-42f4465b3636.PNG)

**Comment by kauffj** [comment]
Please verify this happens in 0.12.2 or later.

**Comment by tzarebczan** [comment]
This has been happening recently again to me. The LBRY.exe process (according to process  explorer) holds a file handle on the downloaded file. Only way to get rid of the download is to restart LBRY or manually delete the file handle.

This causes issues when users try to delete and re-download content.  If a user tries to download content which this happened to, it tells them it can't access the file and does not download.

**Comment by Grayyyyy** [comment]
Can confirm, having the issue on the latest RC.

System Config:
![image](https://user-images.githubusercontent.com/37783688/41510201-db462c94-7225-11e8-83dd-244c5de5aab8.png)

**Comment by tzarebczan** [comment]
Pretty sure something in our code holds a lock on the file. Maybe render media, or Electron, not sure. 

Lock:
![locked](https://content.screencast.com/users/thomas.zarebczan/folders/Snagit/media/5f312382-de64-4b6a-9584-28e2f0487824/08.23.2018-00.13.png)
The daemon wil say:
```
2018-08-23 00:11:10,947 ERROR    lbrynet.database.storage:34: Traceback (most recent call last):
  File "site-packages\lbrynet\database\storage.py", line 31, in _open_file_for_writing
IOError: [Errno 13] Permission denied: 'D:\\LBRY Downloads Main PC\\zcqZHYo7ONs_2.mp4'
```

**Comment by kauffj** [comment]
@tzarebczan I think better rerpo would aid in resolving this. Can you try to create smallest reproducible case? e.g.

1. If I simply render a `<video>` tag, does this lock the file?
2. If I render a video tag with render-media, does this do it? etc.

**Comment by alyssaoc** [comment]
closing, reopen if this is still an issue
