### ISSUE TITLE
Clickable channel names on Explore page headings

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1820]
## The Issue
Breaking out this issue from https://github.com/lbryio/lbry-desktop/issues/1717. 

It would be nice if the channel name in the heading would be a hyperlink to the channel page. With this change, we can have internal APIs pass the long URL, and cut it off after the `#` for display purposes. 

![image](https://user-images.githubusercontent.com/8120721/43227524-f1f314dc-902c-11e8-9e92-988c03cf77e3.png)

Current Sample data:
```
  "data": {
    "Uris": {
      "Featured Content - DOTA 2 Divine | @Dota2Divine": [
        "miracle-ez-rampage-huskar-free-dmg-bonus#0703b1556ecc1cfccd66f2a1c3e89857336e05ec",
        "badman-spectre-dota-2-big-boss-shutdown#3a69f4d9e6d57e3f02dcac4f5402dfdb40323b1a",
...
```
To support this change:
```
  "data": {
    "Uris": {
      "Featured Content - DOTA 2 Divine | @Dota2Divine#2d2c1a3dc98ca868d1f2bfe76b8a1bb820857c5a": [
        "miracle-ez-rampage-huskar-free-dmg-bonus#0703b1556ecc1cfccd66f2a1c3e89857336e05ec",
        "badman-spectre-dota-2-big-boss-shutdown#3a69f4d9e6d57e3f02dcac4f5402dfdb40323b1a",
...
```

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by chrisza4** [comment]
I just realized I should comment in the issue before taking the issue. Can I take this issue?

**Comment by seanyesmunt** [comment]
All good. Checking out your PR
