### ISSUE TITLE
Spamming the Use It Now button causes the installer to run many times

### ISSUE THREAD

**Issue by 42degrees** [lbryio/lbry-desktop#1823]
I saw an upgrade notification in LBRY and so I hit the "Use It Now" button.  It didn't react right away so I hit it again.  Then I hit it a couple more times.  Each hit (more or less) resulted in an installer trying to run.  The button should be greyed out and the cursor should be changed to a busy cursor as soon as the button press has been received.

**Comment by tzarebczan** [comment]
Mine starts fairly quickly after clicking once, but indeed, we should disable it after clicking to prevent duplicate installers. Thanks for the report!
