### ISSUE TITLE
Feature Request: It'll Be Nice To See Visualizations/Album Art When Playing Audio Files

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry-desktop#1824]
## The Issue

At  the moment, audio files plays on a black background, it'll be nice to see some visualizations when playing audio files in the app

### Steps to Reproduce
1. Start playing any audio file
2. You see video playing and in a dark background
3.

### Expected Behaviour
we should see some visualization or a background images/album arts

### Actual Behaviour
black background with the player

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
Great idea, thanks for filing! Want to do some research for open source alternatives that might do this already for mp3s/audio files?

**Comment by ceoger** [comment]
yeah, i know VLC/ VideoLAN, which is a media/mp3 players, has some nice visualization, open source and AIMP3 play which i am looking into.

VLC: https://github.com/videolan/vlc

**Comment by seanyesmunt** [comment]
I'm marking this as on-hold since we are moving to a different video player (video.js)

**Comment by tzarebczan** [comment]
Closing for https://github.com/lbryio/lbry-desktop/issues/2757
