### ISSUE TITLE
Explore presenting channel suggestions on subscriptions page / modal

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1825]
## The Issue
Similar to how we currently fetch featured content, we will be implementing an endpoint  (https://github.com/lbryio/internal-apis/issues/262 - internal issue) which lists suggested channels for users to subscribe/view content from. I've also suggested a community-driven category be added to the endpoint which would list channels with the highest claim bids. The endpoint for featured subs will have a description

Since we don't have channel metadata, we'd need a clever way to engage the user/show the suggestions. 

For a user without any subscriptions, this could be shown when they enter the subscriptions page.  For those with subs already, could show it as a compact view near the top or have an option to view the suggestions.

We could also incorporate this as part of the first run experience to drive exploration/engagement.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1. Completed design and implementation
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
@alyssaoc I'll let you determine if we should be created an Epic for this as a separate issue, or possibly turn this one into an Epic

**Comment by tzarebczan** [comment]
API sample output:
https://api.lbry.io/subscription/suggest
```
{
  "success": true,
  "error": null,
  "data": {
    "featured": {
      "Crypto Candor": "@CryptoCandor#9152f3b054f692076a6882d1b58a30e8781cc8e6",
      "Dota 2 Divine": "@Dota2Divine#2d2c1a3dc98ca868d1f2bfe76b8a1bb820857c5a",
      "UC Berkeley": "@UCBerkeley#de0fcd76d525b1db36f24523e75c28b542e92fa2",
      "Mothers Basement": "@MothersBasement#65dee913b4f26144d573118b2e87704e03d01b8f",
      "bluedrake42": "@bluedrake42#32de523ba228dd3f3159eb5a6cc07b6fd51f4dc0",
      "Tech Fox": "@TechFox#2305db36455aa0d18571015b9e9bd0950262aa0f",
      "Crazy Fox Movies": "@CrazyFoxMovies#1516361918bfd02ddd460489f438e153c918521c",
      "Lunduke": "@Lunduke#e8f68563d242f6ac9784dcbc41dd86c28a9391d6",
      "grabthegames": "@grabthegames#379290e593323eb208070269ea2c29a4ddf64985",
      "Pro Tips": "@ProTips#abc44c18d8842a2dbb5db8491e91a207c1d9b7d8"
    },
    "top_bid": {
      "@Porn": "@Porn#9377895520f71f82702b2dc56cc45d2f046ada8a",
      "@LBRYCommunity": "@LBRYCommunity#a1372cf5523885f5923237bfe522f02f5f054362",
      "@invariantchange": "@invariantchange#cb8c10c765c004b0351594a9de284dd20b9b33f4",
      "@TheBlockCrypt": "@TheBlockCrypt#2ae94dafc42b4b6be170128a3bc32d2ac0bf1a14",
      "@timcast": "@timcast#c9da929d12afe6066acc89eb044b552f0d63782a",
      "@Books": "@Books#fa1c5e4636d4087018dfdbb10d5a4838a10f50dd",
      "@oakey": "@oakey#71b3ce7e10fa0e25074f6003833224e3b402d76c",
      "@ProTips": "@ProTips#abc44c18d8842a2dbb5db8491e91a207c1d9b7d8",
      "@InvariantChange": "@InvariantChange#2406a17ac686524bff75c72e9239eddfdd45a406",
      "@jack": "@jack#251305ca93d4dbedb50dceb282ebcb7b07b7ac65"
    },
    "top_subscribed": {
      "@CryptoCandor": "@CryptoCandor#9152f3b054f692076a6882d1b58a30e8781cc8e6",
      "@TechFox": "@TechFox#2305db36455aa0d18571015b9e9bd0950262aa0f",
      "@Lunduke": "@Lunduke#e8f68563d242f6ac9784dcbc41dd86c28a9391d6",
      "@Acituanbus": "@Acituanbus#aeb882df790ac1c25697954b2bf5cbb3a4ed06f9",
      "@MothersBasement": "@MothersBasement#65dee913b4f26144d573118b2e87704e03d01b8f",
      "@oniblackmage": "@oniblackmage#0ddd797e39c5fe706ed4ee62f96becb792aee03a",
      "@brightsunfilms": "@brightsunfilms#5a1b164d0a2e7adf1db08d7363ea1cb06c30cd74",
      "@davidpakman": "@davidpakman#760da3ba3dd85830a843beaaed543a89b7a367e7",
      "@3Blue1Brown": "@3Blue1Brown#ba79c80788a9e1751e49ad401f5692d86f73a2db",
      "@CrazyFoxMovies": "@CrazyFoxMovies#1516361918bfd02ddd460489f438e153c918521c"
    }
  }
}
```

**Comment by daovist** [comment]
This is gonna be part of my subscriptions epic.

**Comment by tzarebczan** [comment]
Closed in https://github.com/lbryio/lbry-desktop/issues/1825
