### ISSUE TITLE
Improve search UX / Create clickable search bar icon changer

### ISSUE THREAD

**Issue by jamesbiller** [lbryio/lbry-desktop#1828]
When people look at the search bar in the LBRY app they see a magnifying glass that symbolizes search.

However, when a word is typed in the search bar that word is not searched for, but instead, a file is attempted to be accessed at the lbry:// URL of that word.

![image](https://user-images.githubusercontent.com/38798392/43328341-b2b1b002-918b-11e8-9fbe-f7a8676291ab.png)

An easy way to fix this for users is to create a clickable icon where the magnifying glass is right now in the search bar. This feature would enable users to select what they are using the search bar for: default would be general search (magnifying glass), but click on the icon and you can make the search bar search for channels only (@ symbol) or specific URLs only (file symbol).

In addition, rather than having the 'Exact URL' pop up with a small label beside the content of lbry://content we could have it say 'lbry://content' where it says 'Exact URL' right now. This would make it more clear to users what an exact URL is in the first place, and advertises the niftiness of the LBRY protocol's URL claiming technology.

![image](https://user-images.githubusercontent.com/38798392/43328555-542e54a8-918c-11e8-88da-85000a3b6b46.png)

**Comment by tzarebczan** [comment]
@jamesbiller - agreed this can still be confusing, see the previous discussion here https://github.com/lbryio/lbry-desktop/issues/671 for why why default to lbry URLs instead of search. Think we can still improve upon the behavior. 

One of the shorter term fixes would be https://github.com/lbryio/lbry-desktop/issues/1699
