### ISSUE TITLE
Limit Thumbnail upload file types

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry-desktop#1839]
## The Issue
The error message retrieved for choosing unsupported file format as thumbnail does not contain much information as to why the file failed to upload
### Steps to Reproduce
1.try publishing a content
2.chose for example MP4 as thumbnail
3. YOu'll simpley get and error "upload failed"

### Expected Behaviour
maybe only show supported files instead of showing all files for the thumbnail option

### Actual Behaviour
shows all files

### Suggested Solutions
When the publisher chooses the option to upload thumbnail with the thumbnail tool, it should only show the supported file format in the directory

## System Configuration

- LBRY Daemon version: 	0.20.4
- LBRY App version: 0.23.0
- LBRY Installation ID: 3cXLZiAWXwwJbv4fjhbXVgFtaBuUiFQM7afXmFYu5ss1chD1WCpxGUp8aW68gjeNRC
- Operating system: Windows (Windows-10-10.0.16299)

## Screenshots

https://cdn.discordapp.com/attachments/377895389992321064/473956934626574357/unknown.png

this shows after showing "upload failed"
https://cdn.discordapp.com/attachments/377895389992321064/473957937560420405/unknown.png

**Comment by tzarebczan** [comment]
Thanks for filing! At a minimum, we should validate the file extension. If it's possible, we should open the file selection screen with only the valid types (as you mentioned).

**Comment by chrisza4** [comment]
Can I help with this issue?

**Comment by seanyesmunt** [comment]
@chrisza4 Sorry I missed this. Go ahead! You can start working on any issue with the `help wanted` tag, just leave a comment saying you are starting on it so no one else starts on the same one.
