### ISSUE TITLE
Development node_modules are bundled in the distribution, excess modules need to be pruned before packing

### ISSUE THREAD

**Issue by skhameneh** [lbryio/lbry-desktop#1841]
Use [asar](https://github.com/electron/asar) to extract the `app.asar` from the distribution; under the extracted `node_modules` folder you'll see every module used during development.

The build process and dependencies need to be adjusted so we don't package unnecessary modules.

**Comment by tzarebczan** [comment]
Sounds like it should be possible with https://github.com/electron-userland/electron-packager/blob/master/docs/api.md#ignore

**Comment by skhameneh** [comment]
Can use `package.json` to differentiate `dependencies` and `devDependencies` and do a `prune` instead; that would be my suggested long-term approach.

**Comment by tzarebczan** [comment]
If the dev dependencies have other dependencies, will it be smart enough not to package them? I can try moving the file watcher plugin to dev dependencies and see if this brings the installer size down.

**Comment by skhameneh** [comment]
I don't believe so, you'd need to do a `yarn prune` or `npm prune` before the final build @tzarebczan

**Comment by tzarebczan** [comment]
Fixed in: https://github.com/lbryio/lbry-desktop/pull/1888
