### ISSUE TITLE
Middle Click Link Error

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry-desktop#1843]
When someone **middle-clicks** on **links** within the app, it opens them up in an app window with **incorrect** formatting and also **doesn't** support the Shapeshift site.

But if clicked as normal with the **left mouse button**, they open in the default browser as **normal**.

![image](https://user-images.githubusercontent.com/29914179/43533044-3547ca78-95f7-11e8-80d4-d88fc1812657.png)

**Comment by btzr-io** [comment]
https://github.com/electron/electron/issues/2770

**Comment by tzarebczan** [comment]
Fixed in https://github.com/lbryio/lbry-desktop/issues/1844
