### ISSUE TITLE
Problem with search auto-complete menu when scrolling over file viewer

### ISSUE THREAD

**Issue by LavRadis** [lbryio/lbry-desktop#1847]
## The Issue
>  Note: All file-viewers are affected

When you try to use search with 3d printing file or PDF viewer, the search extended bar menu goes UNDER the preview 3d image/PDF. 
Other users were able to replicate this issue.

### Steps to Reproduce
1. Open a 3d printing or PDF file for preview
2. Type something in the search
3.

## System Configuration

- LBRY Daemon version: 0.20.4
- LBRY App version: 0.23.1-rc.1
- LBRY Installation ID: 7tYN144rHXrspzJG9xLP28fi1JztXnbpKro6DBJEQyzBmXTyDgqRLfYsUvHYFVmMe2
- Operating system: Win 10

## Screenshots

![lbry_2018-08-02_23-45-15](https://user-images.githubusercontent.com/10566738/43613383-77fd44d4-96af-11e8-84c1-6370ac7ea3cc.png)

**Comment by tzarebczan** [comment]
This is fixed on master, will be released with the next version!
