### ISSUE TITLE
Higher CPU/GPU usage when viewing GIF preview thumbnails

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1848]
## The Issue
When viewing the explore page which currently has the @3dprinting channel (or when going to lbry://@3dprinting), GPU and CPU usage is noticeably higher and stays as such file they are in focus.

The same happens when I visit https://giphy.com, so I'm not sure if there's any solution to this at the moment...besides potentially not allowing GIFs, or limiting their size for thumbnails. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
It's sad but probably all GIF animation on tiles needs to go :(

**Comment by tzarebczan** [comment]
Will replace with a new ticket to only loop GIFs on mouseover.
