### ISSUE TITLE
Pre-cache next page when viewing channels

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1851]
## The Issue
The experience when switching between pages in a channel has improved where pages load fairly quickly, but I think we can go another step further to make it even more seamless. If a user goes to a channel, we should call the next page (or maybe two/three pages forward?) so when they switch, it will already have all the next data. Same would happen on page 2 (get page 3). 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by dan1d** [comment]
@tzarebczan  Working on this one!

**Comment by dan1d** [comment]
Thanks @seanyesmunt , PR sent!

**Comment by tzarebczan** [comment]
Not required anymore, we'll make sure the API can return this very quickly!
