### ISSUE TITLE
Load subscription data on app startup

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1852]
## The Issue
Currently, we don't check the API or load subscription data until the user subscribes to something or visits the subscriptions page. This should be loaded on startup instead.

Side effect: Clearing cache or logging into a new PC with old account will result in a subscription 101 notification if you subscribe to something before visiting the subscription page. 

Thanks @ceogear for finding this one! 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
@daovist probably easy to roll into current sub work?

**Comment by daovist** [comment]
Yes, this is going in my subscriptions epic.

**Comment by tzarebczan** [comment]
Completed and confirmed in https://github.com/lbryio/lbry-desktop/pull/1872
