### ISSUE TITLE
"Role of the desktop app" blog post

### ISSUE THREAD

**Issue by alyssaoc** [lbryio/lbry-desktop#1862]
@seanyesmunt commented on [Mon Aug 06 2018](https://github.com/lbryio/grooming/issues/73)

**Comment by jamesbiller** [comment]
@seanyesmunt You gonna write this Sean? I'd love to be an editor

**Comment by seanyesmunt** [comment]
Just saw your comment @jamesbiller. Yes I've done a little bit on this so far. Planning on finish a rough draft this week. I'll let you know when it's done!

**Comment by seanyesmunt** [comment]
@jamesbiller I created the PR with a rough draft. 
https://github.com/lbryio/lbry.io/pull/745
