### ISSUE TITLE
Computer Interface starts to slow when viewing too many 3D files

### ISSUE THREAD

**Issue by jamesbiller** [lbryio/lbry-desktop#1863]
I've noticed that when I go from viewing one file to viewing the next eventually my computer starts to slow down so much that I have to quit the LBRY app and/or hard shutdown my computer.

It usually doesn't happen until I've viewed at least 3 files. This isn't the biggest deal in the world considering I probably do more file-viewing than anybody else using the app currently, but it will be a bigger deal the more LBRY is used for 3D printing.

**Comment by kauffj** [comment]
@btzr-io tagging you in case you don't monitor all new issues :)

**Comment by seanyesmunt** [comment]
Possibly we need to do a better job cleaning up after leaving the 3d file viewer?

**Comment by tzarebczan** [comment]
Could be related to the discussion in https://github.com/lbryio/lbry-desktop/issues/1827. I've also seen high memory usage when viewing 3d files, but never had it freeze up on me. 

From my testing on Windows: when leaving a 3d file, the memory from the 3d viewer is not released. But if I view more 3d files after, the memory will increase/decrease based on the complexity of the file, but never actually stacks up.

**Comment by tzarebczan** [comment]
Actually, I lied - the memory usage does grow when viewing multiple files. One of the processes does release it, but another continues to grow.

**Comment by btzr-io** [comment]
https://github.com/mrdoob/three.js/blob/master/examples/webgl_test_memory.html

**Comment by tzarebczan** [comment]
Fixed abnormal memory usage in https://github.com/lbryio/lbry-desktop/pull/1870
