### ISSUE TITLE
When viewing claim at vanity URL, same pice of content is in "related" content list

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#1866]
### Steps to Reproduce
1. Go to lbry://three
2. See the top item in "related"

### Expected Behaviour
That should be removed from the list

### Suggested Solutions
We need to pass in the full claim uri into `<RecommendedContent uri={full uri plus claim id} />`

**Comment by tzarebczan** [comment]
This is still occuring, reopening. Go to lbry://five, and you'll see the same claim in recommended. Maybe the difference is that it has a channel? 

![image](https://user-images.githubusercontent.com/8120721/47928400-9b813200-de9c-11e8-83b8-8fe59b6b659a.png)

**Comment by seanyesmunt** [comment]
This stopped working because previously, the exact match was always the first result. We just removed the first result assuming it would be the exact match (which is honestly not the best solution). 

Either way, the first result coming back is `lbry://two` which is a porn video with a huge bid. I created https://github.com/lbryio/lighthouse/issues/132. I think this issue should be fixed by that.

**Comment by seanyesmunt** [comment]
Fixed with https://github.com/lbryio/lbry-redux/pull/103
