### ISSUE TITLE
Allow enabling rewards for all videos on a channel

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbry-desktop#1868]
From @Feanor78 Rather than picking 10 videos to receive rewards (like we do with LBRYCast), we should be able to turn on rewards for every video on a channel, every video that's tagged with some specific tag (in the future), etc.

This is already possible with our internal-apis, but it would require some app changes. 

From @seanyesmunt Yeah looks like we need an app side change. We currently have this line in the code:

`const isRewardContent = claim && rewardedContentClaimIds.includes(claim.claim_id);`

We can just check the channel claim id and the content claim id

**Comment by tzarebczan** [comment]
LBRYCast will be replaced by a daily way reward, closing.
