### ISSUE TITLE
Asset Minification

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#1871]
This issue inspired by https://github.com/lbryio/lbry-desktop/pull/1869

1. Does asset minification provide a meaningful benefit when assets are distributed via an electron app? Either in the distribution size of the binary or in the load/render time of the app? It almost certainly affects the size on disk of the installed app, but we probably care little about this given the sizes. It may not affect the size of the binary at all if the binary already includes compression techniques.

2. If there are benefits, then the project should presumably always include un-minified plugins and all assets should be minified during the build process and/or as a a commit hook.

**Comment by skhameneh** [comment]
Minification includes some runtime optimizations as well.

We already minify all scripts; we should probably remove source maps from distribution though, that's a lot of extra weight all around.

**Comment by kauffj** [comment]
@skhameneh thanks, I'm going to close this then
