### ISSUE TITLE
[Feature Request] would be nice if the LBRY App has a feature to redeem LBC Gift Vouchers

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-desktop#1874]
## The Issue

now the LBRY App has fantastic features that are integrated with the Shapeshift Exchange. to convert BTC and other cryptocurrency to LBC (Library Credits). it would be better if you have an in-App E-LBC Voucher Generator and also Code In-App Redeem Voucher. so users can give LBC prizes to other users without the need to provide tips or press the tip button on the LBRY App. this allows if LBRY Inc. or LBRY-C holds a LBC prize contest can generate a code voucher in the app itself and give the voucher code to the winner. this also applies to other users. At Bitcoin Indonesia Exchanger has this feature and Achain App also has this feature. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
Not sure about the generation part, but we're looking into a way users can redeem codes which are given out by LBRY. Having someone else create the codes would be non-trivial.

**Comment by ykris45** [comment]
@tzarebczan Yessir. The Main Idea is Based on https://cryptovoucher.io/ . i think LBRY must have the feature so Redeem Code using LBRY App get LBC Gift.

**Comment by alyssaoc** [comment]
closing in favor of #1886
