### ISSUE TITLE
Feature: FileType Categories in 'Explore' tab.

### ISSUE THREAD

**Issue by real-rouse** [lbryio/lbry-desktop#1878]
<img width="1273" alt="screen shot 2018-08-14 at 23 40 11" src="https://user-images.githubusercontent.com/30915240/44120063-6cfd6efe-a01b-11e8-913c-0c123e5d2a96.png">

1. Excuse this design and tagline, but wouldn't it be nice to give the user an option about which file-type they want to look for BEFORE they see the files? 

2. So many people think LBRY is a video platform, this may combat that perception.

3. I put two buttons to separate 'Search' and 'Enter URL', because I think the current search bar is confusing. :) 

Please... We need more E-books on LBRY 🤓 I want to read some good books.
📖 📚

**Comment by real-rouse** [comment]
One more category could be "Archives" which could be .zip and .7zip, .tar etc...

**Comment by real-rouse** [comment]
And also one for "Applications" which could be .dmg, .exe, .pkg, .deb .... etc.

**Comment by real-rouse** [comment]
and one for torrents as well 🤷‍♂️

**Comment by seanyesmunt** [comment]
I think the largest issue with a feature like this is that we can't search by file type atm. We would just need to return a large number of results and then filter it out app-side. But the breakdown wouldn't be even.

**Comment by kauffj** [comment]
https://github.com/lbryio/lighthouse/issues/49

**Comment by tzarebczan** [comment]
This will be replaced by: https://github.com/lbryio/lbry-desktop/issues/2801
