### ISSUE TITLE
Ability to redeem LBRY generated Reward Codes

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1886]
## The Issue
The API team has almost completed implementing a feature that will allow us to generate reward codes that can be redeemed by app users for LBC. We'd need to add a feature into the UI so a user can enter the reward code to claim their credits. @tiger5226 suggested a good place for it might be the top right area of the claimed rewards section (but now that I think about it, not sure if "claimed" rewards is the best place for it). My initial thought is that it would be another tile that's clickable - but this also could be easily missed.  

Sample redemption call:
`https:api.lbry.io/reward/new?auth_token=xxxxxxxxxxxxxxxxxxxxxxxxxxxx&reward_type=reward_code&wallet_address=bQmVXv2LUP5riJ3yh8XNNd1mgYSVMiiCVB&code=xeuXjKm2pzWGNDUjfPSG`

We would show a snackbar with the reward notification text after it's claimed and it would appear in the Claimed Rewards section. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
IMO just showing this as a tile with the rest of the rewards is fine. Rather than "Get X LBC", it should say "Enter Code" or another equivalent cue. 

When clicked take the user to a screen that let's them enter the code, and that's it.

**Comment by tiger5226** [comment]
Currently it is hidden in our internal-apis. We would just need to make it visible and add a description. Then it should just work.
