### ISSUE TITLE
Claim keeps auto-redownloading on subscription with invalid signature

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1890]
## The Issue
lbry://@Lunduke has claims with invalid signatures right now. If you sub to this channel, it will keep trying to re-download the claim. You'll get a notification each time (every ~15 min). 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by alyssaoc** [comment]
this has been resolved, closing
