### ISSUE TITLE
Download progress in taskbar gets stuck sometimes

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1894]
## The Issue
I've noticed this from time to time in the past but was never able to reproduce it repeatedly. Took another look and I think it might be happening due to our written vs total bytes calculation. There are times when the total bytes is higher than written bytes due to padding. Maybe instead of using bytes, we should use blobs? Another option would be to do some rounding. 

https://github.com/lbryio/lbry-desktop/blob/863a95bffbfdbffa1ef752370d40da6866b13fa0/src/renderer/redux/selectors/file_info.js#L96

![image](https://user-images.githubusercontent.com/8120721/44403778-513a1700-a523-11e8-9ff8-98e3c4d6456a.png)

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kauffj** [comment]
@tzarebczan are app team isn't going to be the only one to run into corner cases from `written_bytes` not matching `total_bytes`. I understand why, and would also support including blob info, but I think a form of this ticket should be opened on https://github.com/lbryio/lbry. Either total_bytes should exclude padding, written_bytes should include it, or a third byte related value that makes this clear should be added.

**Comment by tzarebczan** [comment]
This feature is gone, closing.
