### ISSUE TITLE
Large "thumbnail" failed with code 524 on Spee.ch (`lbry-desktop` should optimize/resize/crop before sending to Spee.ch)

### ISSUE THREAD

**Issue by skhameneh** [lbryio/lbry-desktop#1904]
Minimum implementation:
 - `lbry-desktop` resizes all thumbnails so a "cover" scaling will match the 800x450 dimensions (one dimension can exceed 800x450, the other dimension must match 800x450).

Ideal implementation:
- `lbry-desktop` prompts the user with a scaling/cropping tool for thumbnails.

Considerations:
- Doing pre-optimization on clients helps reduce server loads
- pngquant + zopfli provide the best [post resize] PNG optimization
- ImageOptim combines many tools for [post resize] optimization

**Comment by tzarebczan** [comment]
@skhameneh see comments on https://github.com/lbryio/lbry-desktop/issues/1670#issuecomment-412516084 - I think we should open this as a spee.ch issue. The app can pass a parameter so spee.ch knows to "thumbnail" it. Can you follow up with the spee.ch issue and close one of these...then udpate one to mention the spee.ch issue and how the app would support it.

**Comment by tzarebczan** [comment]
Closing in favor of https://github.com/lbryio/spee.ch/issues/599

The app would presumably pass a parameter to spee.ch which would trigger the compression before upload.
