### ISSUE TITLE
Handle subscriptions where multiple claims posted in short period or when app is closed

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1915]
## The Issue
Currently, the subscriptions process is only able to handle 1 piece of new content that's posted either in the same block, or within the interval the internal that the app checks for new subscriptions (15 minutes).  

There are 2 scenarios:
1) The app is running and these new claims come in
2) The app was closed while the claims were posted, and then opened (this applies to all new content, not only ones posted in the same block)

For scenario 1, I'd expect that the app would try to download each piece of new content, but I could be convinced otherwise if we properly inform the user.

Scenario 2 is a bit trickier since there might be tons of new content since a user last ran the app, which would cause many downloads to start if we went all the way back to the point when the user last ran the app. In this scenario, we may want to download the single latest (or maybe up to some value) and alert the user that there are others posted, but not downloaded (and give an option to download?).

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
If I can't reliably use subscriptions to see every piece of content from a creator since the time I subscribed, then this is a bug.
