### ISSUE TITLE
Add ability to view Excel Spreadsheet files in app

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-desktop#1921]
## The Issue
Currently LBRY App can view csv,txt,html etc files in document viewer. would be nice if have feature to view xls files directly in app. i testing the latest RC and publishing excel files but it cannot view in my LBRY App. 

### Steps to Reproduce
1. Publish a Excel Files
2. wait until published excel completed
3. view your published excel. i doesnt appears in LBRY App Document viewer

## System Configuration

- LBRY Daemon version:
- LBRY App version: 0.25.0 Rc 4
- LBRY Installation ID:
- Operating system: Windows 10

## Screenshots

https://cdn.discordapp.com/attachments/377895389992321064/484112914337234979/unknown.png

**Comment by tzarebczan** [comment]
Thanks for filing @ykris45 ! Looking for a community member who might want to take this on.

**Comment by alyssaoc** [comment]
we will not support excel files in app, will improve experience via #1718
