### ISSUE TITLE
[Enhancement] Choose times for Automatic Dark Mode

### ISSUE THREAD

**Issue by VigilanteComedian** [lbryio/lbry-desktop#1922]
### Steps to Reproduce
1. Enable Automatic Dark Mode in LBRY App.
2. Observe switchover timing being restricted to 9pm and 8am.

### Requested Behaviour
The LBRY automatic dark mode should have the ability to be configured to engage at times of the users choosing.

### Actual Behaviour
Automatic dark mode only enables for 9pm and 8am switchovers.

### Suggested Solutions
Allow system time detection and create additional fields when auto dark mode is enabled, to allow users to pick times of their choosing. By the hour would be a good start but if someone is feeling brave, adding 5 minute integers might be useful as well 😛 

## System Configuration

- LBRY Daemon version: 0.21.2
- LBRY App version: 0.25.0-rc4
- LBRY Installation ID: 5e19GwgvypsHUj7dcpDCww61rdyvfDp1foZCojQqqWB1dXdnFzhDrQzsCbtUJa2tEH
- Operating system: Windows 10 x64 v1803

## Screenshots

![image](https://user-images.githubusercontent.com/42811509/44798830-67db1080-abaa-11e8-9012-79d7ca6c3cc2.png)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Thanks for joining our Discord community and for filing this issue!

**Comment by daubaris** [comment]
I'll take a look on this one!!!

**Comment by darrylpargeter** [comment]
Hey, would it be possible to give this one ago?
assuming no one else has claimed it?

**Comment by tzarebczan** [comment]
Hey @darrylpargeter, welcome to LBRY! Looks like it's all yours..let us know if you have any questions!

**Comment by seanyesmunt** [comment]
Added in #2747
