### ISSUE TITLE
[FEATURE REQUEST] Get Ability to view Powerpoint Presentation files in App

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-desktop#1923]
## The Issue
Currently LBRY has Document viewer. its a greatest feature in LBRY App. so users can view pdf, doc, html, txt or etc files directly in App. i testing publish presentation files in my LBRY App but when i click view file and the App told me "sorry we can't preview this file" its means LBRY does not have feature to view pptx files or other Powerpoint Presentation extension. so would be nice if have this feature , so users can make presentation directly via LBRY App.. 
### Steps to Reproduce
1. Publish Powerpoint Presentation
2. click view after published to the LBRY Network
3. See the message on LBRY App document viewer

## System Configuration

- LBRY Daemon version: 0.21.2
- LBRY App version: 0.25.0-rc4
- LBRY Installation ID: 8K9e1PbwApDnXBbxCBKnYbNLAd2Ytf4LabE8YmDQywbHCp2qxnKfn1cb94zkLbyFxd
- Operating system: Windows 10

## Screenshots

![image](https://user-images.githubusercontent.com/26609573/44805843-7e578b00-abef-11e8-9313-86e31c0eb629.png)

**Comment by kauffj** [comment]
Google has spent a decade on this and it still has bugs.

It is extremely unlikely we'll support complex, proprietary file formats in the app, so I'm going to close this.

You're welcome to continue to push for other types that are open or more feasible to support.
