### ISSUE TITLE
Any special character before, after or within a url breaks the app

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry-desktop#1927]
## The Issue
when you include any special character like :  (,./';][?":) within a claim url, it breaks the app
### Steps to Reproduce
1. Click on any video, 
2. once your get url in the address bar, add any special character like say , period "."
3. press enter and you get a blank screen

### Expected Behaviour
when a special character is added to the url, nothing should happen, a warning, or a search results for relevant url

### Actual Behaviour
app turns blank
### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

## Screenshots

https://cdn.discordapp.com/attachments/363049604461232148/484813043444744212/unknown.png

**Comment by tzarebczan** [comment]
To be clear, it's when it's added to the claim ID portion. The app handles the scenario where bad characters are present in the claim name.

**Comment by ceoger** [comment]
it happens also in then url as well: "lbry://real-life-cryptocurrency-purchase-and.." as well as the claim ID portion

**Comment by tzarebczan** [comment]
Fixed in https://github.com/lbryio/lbry-desktop/pull/2026
