### ISSUE TITLE
Paragraphs not rendered correctly in markdown

### ISSUE THREAD

**Issue by m160** [lbryio/lbry-desktop#1932]
When publishing content the description text is mushed into a block of text.
I think this is something that was introduce in the latest version: 0.25.0

Two screenshots says more than two thousand words.

Editor:
![screenshot from 2018-09-02 10-18-33](https://user-images.githubusercontent.com/34570404/44953988-082b8080-ae9c-11e8-84b7-1c62a26e2397.png)

Preview:
![screenshot from 2018-09-02 10-18-55](https://user-images.githubusercontent.com/34570404/44953993-0e216180-ae9c-11e8-8a2c-bd257bc52f4e.png)

**Comment by seanyesmunt** [comment]
We use https://github.com/RIP21/react-simplemde-editor for this component. This issue should be opened there.

**Comment by btzr-io** [comment]
We are using a custom markdown render not the one from `simpleMDE`

**Comment by seanyesmunt** [comment]
@btzr-io This is for the markdown preview, not for actually viewing the markdown on the file page

**Comment by btzr-io** [comment]
@seanyesmunt Yes, we use the same component on preview and on file page...

**Comment by btzr-io** [comment]
@seanyesmunt If you check the description on file-page, you can see the same bug :upside_down_face:

**Comment by seanyesmunt** [comment]
Ah you are right @btzr-io. Thanks for re-opening this issue.

@m160 Sorry about that! 

@btzr-io Do you think we can solve this with css? Or will a change need to be made to the markdown renderer?

**Comment by seanyesmunt** [comment]
FIxed with #1939
