### ISSUE TITLE
Snackbars and modals can't be displayed at the same time

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#1945]
## The Issue
Currently modals and snackbars can't be rendered at the same time.

### Steps to Reproduce
1. On the Send/Recieve page
2. Copy address with button to see the copy address snackbar
3. Press the "send" button to open up the send confirmation modal

### Expected Behaviour
The modal and snackbar should both be displayed

### Actual Behaviour
The modal isn't displayed until the snackbar goes away

### Suggested Solutions
Most likely an issue with how we are slecting notifications. If we are always taking the latest one it might be the wrong type.

**Comment by tzarebczan** [comment]
Same as https://github.com/lbryio/lbry-desktop/issues/1767? Keep whichever is clearer / has more info.
