### ISSUE TITLE
File analytics (view counts) for own published content

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1952]
## The Issue
As the first step to https://github.com/lbryio/lbry-desktop/issues/1951, allow publishers to see view counts on content within their channel. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by dereksilva** [comment]
I would really like to see this happen soon. I was hunting all over the app recently looking for view counts, subscriber counts, etc. We're not trying to monetize LBRY, but knowing that the effort is leading to some results in terms of visibility would be highly appreciated.

**Comment by kauffj** [comment]
@dereksilva I think we have everything in place to add this to the UI very soon, it will probably get assigned for work on Monday.

**Comment by seanyesmunt** [comment]
Thanks for the feedback @dereksilva. I'm going to try and get to this issue this week. If not I'll start on it next Monday by the latest.

**Comment by seanyesmunt** [comment]
@dereksilva Started on it here https://github.com/lbryio/lbryinc/pull/30!

It will be included in the next release

**Comment by seanyesmunt** [comment]
Added in #2335
