### ISSUE TITLE
[Feature/Question] Ongoing List of Blocked Videos

### ISSUE THREAD

**Issue by asddsaz** [lbryio/lbry-desktop#1958]
From my understanding .LBRY does and will block videos from the client if the break copyright laws. I have 2 questions:

1. How do the video get blocked if the client is open source and decentralized?

2. Is there public list of all videos that have been removed from the client? If no then why?

**Comment by seanyesmunt** [comment]
We maintain a list of content that is blacklisted from the app.

https://github.com/lbryio/lbry-redux/blob/master/src/redux/actions/blacklist.js

The content that is blocked can be found here https://api.lbry.io/file/list_blocked

**Comment by tzarebczan** [comment]
You can see more information about content blocking/policy at https://lbry.io/faq/content . Closing this issue for now.
