### ISSUE TITLE
[Feature] Search Other Databases

### ISSUE THREAD

**Issue by asddsaz** [lbryio/lbry-desktop#1959]
**Feature**: The ability to import from other DApps

**Why**: There are many decentralized video platforms including KopyKate , DTube, PeerTube, and more. Personally, I believe the one to win will be the one that includes all protocols in one client. 

**How**? I have seen some other networks allow users to point to a URL or Localhost and load data from there too. Obviously this will be for technical users who want to have this support.

**Comment by tzarebczan** [comment]
Similar to my response in https://github.com/lbryio/lbry-desktop/issues/1956, we will not be supporting other databases via the desktop app. Down the road the LBRY protocol will support other source content outside of LBRY's P2P system.
