### ISSUE TITLE
[Feature] Add AppImage Support

### ISSUE THREAD

**Issue by asddsaz** [lbryio/lbry-desktop#1960]
**Feature**: Create **[AppImage](https://appimage.org/)** for LBRY

**Why**? Many reasons, the main being that it is portable and easy to use.

**Comment by tzarebczan** [comment]
Thanks for opening this issue! 

Please see previous discussions about appimage in https://github.com/lbryio/lbry-desktop/issues/953 
https://github.com/lbryio/lbry-desktop/issues/332

For now we are sticking with deb files as it supports a majority of Linux users and for the reasons discussed in the issue above. We also provide flatpak support which covers other non-debian distros: https://github.com/lbryio/lbry-desktop/blob/master/README.md#install. Linux users make up a small portion of our user base, so I don't think we'll be dedicated time to this anytime soon, will close for now. 

Also, before opening issues, please do a search on github for previous discussions on the topic, thanks for understanding!
