### ISSUE TITLE
[Feature] Add BSD Binary

### ISSUE THREAD

**Issue by asddsaz** [lbryio/lbry-desktop#1961]
**Feature**: Add Binaries for BSDs like OpenBSD, LibertyBSD, and FreeBSD / TrueOS.

**Comment by tzarebczan** [comment]
Do these OSes support flatpaks? On our readme, we have a community controlled section which links to the flatpak: https://flathub.org/apps/details/io.lbry.lbry-app 

I don't see us taking this on anytime soon as the Linux userbase is one of our smallest, and BSD oses make up even a tinier portion than that.

**Comment by asdedhj** [comment]
> Do these OSes support flatpaks? On our readme, we have a community controlled section which links to the flatpak: https://flathub.org/apps/details/io.lbry.lbry-app
> 
> I don't see us taking this on anytime soon as the Linux userbase is one of our smallest, and BSD oses make up even a tinier portion than that.

https://github.com/flatpak/flatpak/issues/1985

**Comment by xliiv** [comment]
It's native binary, but it's something.

You can run LBRY-Desktop on
1. Linuxulator (https://forums.freebsd.org/threads/missing-shared-library-libffmpeg-so-while-running-electron-app-lbry-desktop-on-linuxulator.81987/#post-531578)
2. Wine-Proton (https://forums.freebsd.org/threads/missing-shared-library-libffmpeg-so-while-running-electron-app-lbry-desktop-on-linuxulator.81987/#post-531472)

From

https://forums.freebsd.org/threads/missing-shared-library-libffmpeg-so-while-running-electron-app-lbry-desktop-on-linuxulator.81987/#post-531578
