### ISSUE TITLE
Comments VMVP

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-desktop#1963]
For the comments Very Minimum Viable Product, I suggest the following:

- add a section under each video called Comments. the section would have some indicator next to it that signals that the section is closed, and that you can open or drop-down the section by clicking on it.
- when the section is opened, it contains a message saying "Comments coming soon"
- anytime someone opens the section, this is logged in analytics
- we also make sure we're tracking how many people see that page total
- after a few weeks, we compare # of people who saw the page vs # of people who opened the comment dropdown. this lets us know how many ppl are interested in commenting, and will inform our decision of implementing a full commenting system

**Comment by alyssaoc** [comment]
@lyoshenka comments are planned for app d
