### ISSUE TITLE
lbry-app has forgotten verified humanness

### ISSUE THREAD

**Issue by stevenmos** [lbryio/lbry-desktop#1965]
## The Issue
lbry-app has forgotten verified humanness

### Steps to Reproduce
1. Become verified
2. Earn rewards for nearly 1 yr
3. app forgets verified status without user consent/LBRY inc. justification

### Expected Behaviour
The lbry-app shouldn't forget, unless the user asks it to do so or the user has been notified why it has been removed.

### Actual Behaviour
lbry-app has forgotten without consent/status has been removed without justification.

## System Configuration
- LBRY Daemon version: 0.21.2
- LBRY App version: 0.25.0
- LBRY Installation ID: 9Z8TkpnE6ZQGXgqqCJTobLDXzFDCXJHYR8SvAN8cSfu9Ehbq1qShT4kA4dEWqiVPYT
- Operating system: Linux (Linux-4.18.5-90.current-x86_64-with-Solus-3.9999-shannon)

**Comment by tzarebczan** [comment]
Steven, I just re-enabled rewards on your account. (press ctrl-R in the app to refresh). Our system detected VPN/shared account use, which is one reason why we may disable rewards - please see https://lbry.io/faq/rewards.
