### ISSUE TITLE
Allow typing of encryption password without clicking entry box

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1969]
## The Issue
When starting up the app with an encrypted wallet, you are prompted for a password. In order to type the password, you must first click the entry box and then you can type.

The app should automatically select the entry box so the password can be typed without having to click anything. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
Implementation suggestion: make this a property of either an input or form, not specific to encryption component.
