### ISSUE TITLE
Obstructive notifications (snackbar)

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry-desktop#1974]
## The Issue
Snackbar notifications obstruct some elements on the header component.
~Also would be nice to have an option to remove it without having to wait.~

### Steps to Reproduce
1. Trigger a snackbar notification (click on the copy wallet address button)

### Expected Behaviour
Non-obstructive notifications.

## Screenshots

![snackbar](https://user-images.githubusercontent.com/14793624/45723967-45b52c80-bb71-11e8-95bc-d4aa709c9c73.png)

**Comment by btzr-io** [comment]
@seanyesmunt some good suggestions:
https://material.io/design/components/snackbars.html#placement

**Comment by sanketsingh24** [comment]
If this issue is free, I would like to work on this, but would need some more info on where to place the snackbar, I think adding a close button would be necessary.

**Comment by kauffj** [comment]
Material specifically does not have close buttons. Is there something unique about our app that requires them vs. Google which does not? Or do we think Google is wrong in not having them?

Unless we're answering in the affirmative to one of those questions, it is probably better to start with different/smarter placement and consider tweaking timing or usage if people feel a need to close.

**Comment by sanketsingh24** [comment]
Usually, snackbar is placed on bottom-right or bottom-left, the reason being the fact that people usually try to keep the relevent info nearer to top of the screen, and hence the bottom side of website is not used. Also, size and timing can be tweaked.

**Comment by seanyesmunt** [comment]
I think if we move the snackbar to the bottom left, a close button would not be necessary. The only reason an argument could be made to have one now is because it covers the search bar.

**Comment by btzr-io** [comment]
Yeah, we don't need the close button if isn't obstructing important stuff :+1:

**Comment by sanketsingh24** [comment]
Bottom-left is cool but might hide some menu buttons, which is my only concern.

**Comment by kauffj** [comment]
Just noticed Gmail snackbars do have close buttons.

**Comment by sanketsingh24** [comment]
Well, they have the same issue I had concerns with, and the snackbar disappear upon clicking any action button.

**Comment by btzr-io** [comment]
@sanketsingh24  Are you still working on this?
