### ISSUE TITLE
License setting is lost if you edit an item

### ISSUE THREAD

**Issue by 42degrees** [lbryio/lbry-desktop#1975]
## The Issue
If I upload an item and set the License to "Copyrighted..." when I edit the item the selection returns to "None".  

### Steps to Reproduce
1. Upload something setting the License to "Copyrighted...".
2. Edit the item and notice that the License has reverted to None

### Expected Behaviour
It should refill the License dropdown to the previous value.  It should refill the Copyright Notice (if the selection was Copyrighted) to the previous value.

### Actual Behaviour
License reverts to None on edit.

## System Configuration
- LBRY Daemon version: 0.21.2
- LBRY App version: 0.25.1
- LBRY Installation ID: 8jTfoiRnN7Gux5LUhcAb5Twq3cU4XVhnoF4Y6nr6mVVjP6piiRwXBxt2stQc6xAKfE
- Operating system: Windows 10 Pro

**Comment by kauffj** [comment]
@tzarebczan your comment above would count as Triage so you can update Pipeline. I'm adding "Consider Soon" as well, this is important to fix.
