### ISSUE TITLE
Feature: self organizable playlists 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1982]
## The Issue
The idea would be to allow users to create their own playlists in the app, outside of any playlist functionality that may be implemented on the protocol level. I'd want to be able to create/delete/edit multiple named playlists, add claims easily to the queue (from file pages, tiles, etc), re-order playlists using drag/drop features, auto play next functionality and syncing my playlists to my email/account (would require internal API work - ticket will be filed when we get closer to a data model/solution). 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by Victor239** [comment]
This feature is a must-have for users to be able to keep an organised library of their favourite content.

**Comment by exocode** [comment]
This is the only open issue since 2.5 years now. Are there any updates on this feature?
The missing "watch later" option is THE breaker for me not using LBRY each day.
Without it I have to keep open dozens of tabs/windows to follow content I wanna watch.

**Comment by tzarebczan** [comment]
We're in the final stages of development and the first version will be out in the next 2 weeks.
