### ISSUE TITLE
undecodable claims cause green screen

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#1984]
## The Issue
When viewing claims like lbry://one:15 / lbry://one:23, you'll get a green screen in the app since the claim does not decode properly. 
Console shows: `Uncaught TypeError: Cannot read property 'title' of null `

Checking with the protocol team as to what these are, but we should handle them better on the app side.

```
{
  "one:15": {
    "claim": {
      "address": "bNEh1ps7EwgUu67cL3zrf4w9tVYtWWDmgY",
      "amount": 1.0,
      "claim_id": "99e46d70a2ec0095fc71b344aa89cba1eb990783",
      "claim_sequence": 15,
      "decoded_claim": false,
      "depth": 281528,
      "effective_amount": 1.0,
      "error": "Failed to decode value",
      "height": 160783,
      "hex": "686920616c6578",
      "name": "one",
      "nout": 0,
      "permanent_url": "one#99e46d70a2ec0095fc71b344aa89cba1eb990783",
      "supports": [],
      "txid": "722b48e8f04440985439ec5213356549bc879817f1913f4dbfed27491715bde0",
      "valid_at_height": 161255,
      "value": null
    }
  }
```

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
@jessopb do you think you can take care of this one as well? This will happen for claims that can't be properly decoded because of protobuf changes or invalid claims (i.e. lbry://036pub1). We should say something like "Please make sure you are on the latest version of LBRY. If you continue seeing this error, please contact 
 [support](https://lbry.com/faq/support) with the URL you are trying to access".

It's already too late for this round of protobuf changes unless we release a patch on the current version.

**Comment by tzarebczan** [comment]
Still happens  lbry://one#99e46d70a2ec0095fc71b344aa89cba1eb990783

**Comment by jessopb** [comment]
Does not crash.
