### ISSUE TITLE
Transactions filter menu collides with transaction table

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#2000]
## The Issue
Transactions filter menu collides with transaction table on small screens. This must have happened after https://github.com/lbryio/lbry-desktop/pull/1985 was merged.

### Steps to Reproduce
1. View transactions page
2. Shrink screen until the filter menu overlaps with the table

<img width="400" alt="screen shot 2018-10-03 at 10 41 18 pm" src="https://user-images.githubusercontent.com/16882830/46450124-ae99c880-c75d-11e8-83fd-403f4261249d.png">

### Suggested Solutions
It currently uses `position: absolute` to achieve the positioning. Ideally the filter menu should just appear first in the dom so we don't need to hoist it up.

It should probably be in line with the title, just moved over to the right side.

**Comment by estevanjantsk** [comment]
nice! I'll try that one 👍

**Comment by seanyesmunt** [comment]
Awesome! Let me know if you have any more questions 🙂

**Comment by ykris45** [comment]
@seanyesmunt i tested it with position relative and the Transactions filter menu uncolides

**Comment by ykris45** [comment]
close close..hehehe

**Comment by seanyesmunt** [comment]
@estevanjantsk We found a fix for this issue but I still think the solution we discussed would be preferable. If you are still working on it feel free to submit a PR!

**Comment by seanyesmunt** [comment]
I'm going to close this for now
