### ISSUE TITLE
Blockchain hard fork testing

### ISSUE THREAD

**Issue by alyssaoc** [lbryio/lbry-desktop#2006]
## The Issue

With the blockchain upstream and normalization changes in the upcoming hard fork, 
as an app developer, 
I want to identify as many automated and manual tests as possible so that the hard fork does not break the desktop app.

## DOD/Acceptance Criteria
Identify all interactions with the blockchain and document
Identify and document possible testing scenarios for those interactions

As a goal, we should build a test environment for repeatable testing of future changes

**Comment by seanyesmunt** [comment]
I'm sure I will add more as I think of them but I don't think there will be that much to test in the app. Here are three:

```
- Create claim at lbry://x with 1lbc bid
- Create claim at lbry://X with 2lbc bid
- Navigate to lbry://x

- It should show the content published to lbry://X
- The url bar should change to lbry://X
```

```
- Publish to lbry://X with a bid of y lbc
- Begin a publish
- Set the name to lbry://x
- Check that the help text for the winning bid shows the bid at lbry://X
```
