### ISSUE TITLE
Feature: Quick Publish mode

### ISSUE THREAD

**Issue by neb-b** [lbryio/lbry-desktop#2009]
## The Issue
It would be really nice to have an option (or default to) a quick publish page. Just select your file, name and then publish. The bid amount could default to something in settings (and/or an expandable area)

Currently, it can be confusing for users who want to publish something, they may not know about bid amounts, license types, or don't need a description. This publish mode would be more like spee.ch

This is mostly to start the discussion to see how this should be implemented.

## Questions
Should the app default to quick publish?
What values should be editable on quick publish? (thumbnail?)
How do we present the option to toggle between regular publish and quick publish?

**Comment by jessopb** [comment]
How about a "publish preferences" in settings to facilitate it?

**Comment by seanyesmunt** [comment]
Yeah. That could contain settings for which one to default to, default bid amount, etc

**Comment by seanyesmunt** [comment]
I think I would be in favor of defaulting to quick publish. With a button on the publish page to "view more details" or whatever you want to call it.

**Comment by kauffj** [comment]
1) The central idea of this is fantastic and very much worth doing.
2) I think it is a mistake to think of this as a unique option and it should avoid requiring (explicit) preferences unless absolutely necessary.
3)  Focus on how we can design a page that allows the user to seamless switch between both styles. If we're concerned about user's having to perform extra actions, we can track their implicit preference by returning to the mode/view they last used.
4) If we're hiding fields, defaults are super important. Please make sure there's been explicit review of these before shipping. 
5) Related to above, the ramifications of clicking publish are significantly different than on a traditional website. It is important, especially for new users, that they are aware of that before they click. If we're concerned about real-estate usage for this, we can potentially do a one-of and permanently tracked interstitial screen on a first publish.
