### ISSUE TITLE
HTTP -> HTTPS

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry-desktop#2015]
## The Issue
HTTP is bad

### Steps to Reproduce
1. Travel in time from the past to 2018
2. Find out about sniffing, tampering, mitm and all the horrible things that are possible on http
3. panic

### Expected Behaviour
We should use https where possible

### Actual Behaviour
Some things don't

### Suggested Solutions
add an `s` here:
https://github.com/lbryio/lbry-desktop/blob/e4f4909725f52c1eca8a4c4b707fd14a9f56576d/src/renderer/component/viewOnWebButton/view.jsx#L22
https://github.com/lbryio/lbry-desktop/blob/a895617342ee942362a22fede2ea556a7c42803b/src/renderer/component/socialShare/view.jsx#L34-L35
https://github.com/lbryio/lbry-desktop/blob/b77864230d4589f16cb7ab61c7811a640ca532da/src/renderer/component/selectThumbnail/view.jsx#L92

## Screenshots
https://spee.ch/ee42d31a678720aec0e6f1417f2c462f5060a634/new-share-screen.jpg

**Comment by seanyesmunt** [comment]
Thanks @imjayanthka! 🙂
