### ISSUE TITLE
Determine what to do once ShapeShift stops working

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#2019]
At some point, shapeshift will require accounts to use it's service. We need to determine if this will affect the api, and if it does we may need to find another service to handle getting LBC inside of the app.

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by seanyesmunt** [comment]
One possible solution https://changelly.com/developers

**Comment by seanyesmunt** [comment]
Looks like ShapeShift officially stopped working.

<img width="676" alt="screen shot 2018-10-16 at 12 35 20 pm" src="https://user-images.githubusercontent.com/16882830/47037178-44fdbf00-d14c-11e8-9432-85ec1114fa97.png">

I think for now we can just remove the card if we don't implement something immediately.

**Comment by kauffj** [comment]
Agreed, just remove it. You should also check out how many people used it and share that info in chat.
