### ISSUE TITLE
App never loads on Mac

### ISSUE THREAD

**Issue by MadDataScience** [lbryio/lbry-desktop#2020]
### Steps to Reproduce
1. Start LBRY App
2. Wait for Blockchain Sync to complete
3. Wait for LBRY service to initialize
4. Go to 2.

### Expected Behaviour
The LBRY app should load

### Actual Behaviour
It just cycles through the Blockchain Sync step and the initializing LBRY service step forever.

### Suggested Solutions
I have no idea why it's in an infinite loop.

## System Configuration

Version 0.25.1 (0.25.1.3489)

(FWIW, I had installed 0.20 previously. I don't remember if I ever got that to work. When I tried it recently, this happened, so I upgraded to the latest version, and it still doesn't work.)

- LBRY Daemon version:
    ```json
    {
        "id": null,
        "jsonrpc": "2.0",
        "result": {
            "build": "release",
            "ip": "199.116.167.220",
            "lbrynet_version": "0.21.2",
            "lbryschema_version": "0.0.16",
            "lbryum_version": "3.2.4",
            "os_release": "17.7.0",
            "os_system": "Darwin",
            "platform": "Darwin-17.7.0-x86_64-i386-64bit",
            "processor": "i386",
            "python_version": "2.7.13"
        }
    }
    ```
- LBRY App version: Version 0.25.1 (0.25.1.3489)
- LBRY Installation ID: ???
- Operating system: macOS

## Anything Else
The Android version works, at least?

## Screenshots
<img width="204" alt="screen shot 2018-10-09 at 11 25 58 am" src="https://user-images.githubusercontent.com/896607/46690027-292b7380-cbb6-11e8-946b-d7eeae2d5e5f.png">

**Comment by seanyesmunt** [comment]
Hey @MadDataScience Thanks for opening the issue!

Is this when you run the app normally? Or when building from source? It sounds like it's having issues connecting to the daemon, not sure what would cause that.

**Comment by MadDataScience** [comment]
Normally. Just downloaded the app from lbry.io. Just tried reinstalling but got the same result. Realized it might be because I'm behind a company firewall? I haven't tried running it from home yet.

**Comment by seanyesmunt** [comment]
@tzarebczan Any ideas?

I think this could happen if the daemon never returns `status.is_running` as `true`

**Comment by seanyesmunt** [comment]
There have been a few issues with firewall before, that could be related.

**Comment by MadDataScience** [comment]
Come to think of it, it's almost certainly a firewall (or related) issue. The Android app isn't working either so long as I'm connected to the corporate network, though it worked fine when I was at home.

**Comment by seanyesmunt** [comment]
👍 Very interested to see if the app works for you when you are on a different network

**Comment by tzarebczan** [comment]
Yep, it's probably related to local network issues. Check out https://lbry.io/faq/startup-troubleshooting

We should probably handle this particular scenario better and alert the user to the FAQ as we do with other daemon startup errors. Opened https://github.com/lbryio/lbry-desktop/issues/2021

Going to close this for now, but @MadDataScience please let us know if you're able to get it working on your home network. If not, feel free to reach out with your [log file](https://lbry.io/faq/how-to-find-lbry-log-file) on https://chat.lbry.io or help@lbry.io

**Comment by MadDataScience** [comment]
Yup, works at home. Thanks!
