### ISSUE TITLE
Handle daemon not fully starting scenario better

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2021]
## The Issue
Handle scenarios like https://github.com/lbryio/lbry-desktop/issues/2020 where the daemon doesn't fully connect to the LBRY network, and thus the app gets stuck on initializing. We should try connecting for some period of time before timing out and showing an error message similar to:https://github.com/lbryio/lbry-desktop/blob/9844cbdaf6f6cad3eefba7dfaa1a7598cdbb1bd1/src/renderer/component/splash/view.jsx#L54
along with a link to https://lbry.io/faq/startup-troubleshooting

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by phillipyork** [comment]
**I have this exact problem .where the daemon doesn't fully connect to the LBRY network, and thus the app gets stuck on initializing.**  screen shot below 

![snapshot](https://user-images.githubusercontent.com/26136041/47797972-a6916200-dce4-11e8-8805-5378c4928a3f.PNG)

**Comment by tzarebczan** [comment]
@phillipyork can you send us your logfile (https://lbry.io/faq/how-to-find-lbry-log-file) so we can better diagnose it? Or you can also look at https://lbry.io/faq/startup-troubleshooting in the meantime.

**Comment by phillipyork** [comment]
[lbrynet.log](https://github.com/lbryio/lbry-desktop/files/2536243/lbrynet.log)

heres my log file
