### ISSUE TITLE
Separate LBRY Inc Styles from Browser Styles

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#2027]
As the first step of https://github.com/lbryio/design/issues/1, we want to:

- Review all CSS and split it into two buckets: styling that ought to apply to all of LBRY Inc. presentation and styling specific to the browser (e.g. perhaps the wunderbar or load screen).
- While reviewing and refactoring the CSS, make any other improvements related to design/presentation.

**Comment by surmistry** [comment]
Mind if I take a crack at this?

**Comment by NetOperatorWibby** [comment]
I’m already doing this @surmistry.

**Comment by seanyesmunt** [comment]
Initial PR is merged. There will be some minor cleanup but I think we are pretty close.

**Comment by seanyesmunt** [comment]
https://github.com/lbryio/lbry-desktop/pull/2045
