### ISSUE TITLE
Subtitles support

### ISSUE THREAD

**Issue by kodxana** [lbryio/lbry-desktop#2028]
I think it will be a great idea to allows people to load subtitles in str format, when publishing video.
Cause for example im making my videos in polish language but I would like to make it more international by adding translated subtitles. Its anoying to need blend subtitles into video.

**Comment by seanyesmunt** [comment]
Thanks for the issue @kodxana 🙂 

This is part of a much larger issue where we want to expand the data that can be included when you publish something. This will definitely require changes at the protocol level, so not much we can do right now. But thanks for documenting it!

**Comment by tzarebczan** [comment]
I think we should close this for now, there are other ways around it. The new video player will support subs, but I think we should have users bake them into the mp4 as opposed to a separate file. Right now you can only upload one first with a claim, so it would suck to have to go to a separate claim for the subs, and then load the subs in. Even if we had the protocol changes, would still require loading the subs manually, which is worse UX for users. We would teach creators on how to embed them instead.
