### ISSUE TITLE
Only animate GIF thumbnails on hover over

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2029]
## The Issue
Due to the finding described in https://github.com/lbryio/lbry-desktop/issues/1848, we should see if there's a way to pause animation on GIF thumbnails unless a mouse is hovered over it.  This behavior would be similar to what is seen on other popular video sites. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by CoryWritesCode** [comment]
Mind if I take a shot?

**Comment by hydrosquall** [comment]
Will have a PR for this up soon!

**Comment by seanyesmunt** [comment]
Added!

**Comment by seanyesmunt** [comment]
Thanks @hydrosquall !
