### ISSUE TITLE
Link inmediato con la búsqueda.

### ISSUE THREAD

**Issue by CJorwinJ** [lbryio/lbry-desktop#2032]
### Steps to Reproduce
1.
2.
3.

### Expected Behaviour
Tell us what should happen.

### Actual Behaviour
Tell us what happens instead.

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by CJorwinJ** [comment]
the link appears immediately at the time of the search. so that the address is already known in advance.

**Comment by CJorwinJ** [comment]
[BSk.7j](url)

**Comment by tzarebczan** [comment]
This does not look like a valid issue. Please be more mindful when opening one next time.
