### ISSUE TITLE
 when you leave several tabs without opening because you are browsing in one, the others when you open them are blank and take time to open again.

### ISSUE THREAD

**Issue by CJorwinJ** [lbryio/lbry-desktop#2033]
### Steps to Reproduce
1.Place the link
2.wait for the network
3.analyze the computer

### Expected Behaviour
Tell us what should happen.

### Actual Behaviour
Tell us what happens instead.

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
Lbry doesn't even have tabs, please stop creating issues.
