### ISSUE TITLE
Vulnerabilities in dependencies

### ISSUE THREAD

**Issue by NetOperatorWibby** [lbryio/lbry-desktop#2056]
_This issue doesn't apply to the git issue format._

### Critical Vulnerabilities
- [filewatcher-webpack-plugin](https://github.com/sap9433/filewatcher-webpack-plugin)

### High Vulnerabilities
- [filewatcher-webpack-plugin](https://github.com/sap9433/filewatcher-webpack-plugin)
- ~[fs-path](https://github.com/pillys/fs-path)~

### Low Vulnerabilities
- [filewatcher-webpack-plugin](https://github.com/sap9433/filewatcher-webpack-plugin)
- [mammoth](https://github.com/mwilliamson/mammoth.js)

These modules have not been updated in quite some time and probably will not be. I think `fs-path` can be replaced via the [now built-in](https://github.com/nodejs/node/pull/23313) recursive directory creation in recent versions of Node.js.

I'm not sure if the `mammoth` module is still necesssary.

**Comment by seanyesmunt** [comment]
Mammoth will be resolved when it releases a new version. For `filewatcher-webpack-plugin` i'm not sure what to do. It's an old module with no support. @skhameneh Any ideas or alternatives?

**Comment by seanyesmunt** [comment]
Regardless it is a dev dependency only, so we should be fine.
