### ISSUE TITLE
Channel page allows navigation to pages beyond content limit

### ISSUE THREAD

**Issue by jessopb** [lbryio/lbry-desktop#2059]
## The Issue
A Channel page presents navigation to pages beyond content limit

### Steps to Reproduce
1. Go to a channel page, such as 3Blue1Brown.
2. Click to go to page 3
3. -Whitescreen-

### Expected Behaviour
With 48 items per page, a channel with less than 96 items should not show an option to go to page 3 or higher.
### Actual Behaviour
Channel page UI presents nav options up to page 8.

## System Configuration

App | 0.25.1
Daemon (lbrynet) | 0.21.2
Wallet (lbryum) | 3.2.4
Platform | Linux (Linux-4.14.69-1-MANJARO-x86_64-with-ManjaroLinux-17.1.12-Hakoila)
Installation ID | ADdEbSfxc5sjkUMbgBugDH4Dk8C2sULhd5XyphXqq1aVrMzrJKTRvVWbfjR6YVDqyT

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by jessopb** [comment]
Is it wise to have
`export const CLAIMS_PER_PAGE = 48` for this value?
LBRY-DESKTOP:
`Lbry.claim_list_by_channel({ uri, page: page || 1, page_size: 48 }).then(result => {`
LBRY-REDUX:
`

export const makeSelectTotalPagesForChannel = uri =>
  createSelector(
    selectChannelClaimCounts,
    byUri => byUri && byUri[uri] && Math.ceil(byUri[uri] / 10)
  );
`

**Comment by seanyesmunt** [comment]
@jessopb Good find. Yeah, that would have prevented this bug in the first place.

**Comment by seanyesmunt** [comment]
@jessopb Were you planning on working on this?

**Comment by jessopb** [comment]
It's up for grabs. I'll get to it November 1st otherwise.
