### ISSUE TITLE
Share button on channel page does not use new share modal.

### ISSUE THREAD

**Issue by jessopb** [lbryio/lbry-desktop#2077]
## The Issue
Channel page still uses ViewOnWeb for share 
### Steps to Reproduce
1. Go to a channel, e.g. @MinutePhysics
2. Click Share

### Expected Behaviour
modalSocialShare should display several sharing options.

### Actual Behaviour
The original ViewOnWebButton component takes the user directly to spee.ch.

### Suggested Solutions
Implement as done in  `src/renderer/page/file/view.jsx`
```
<Button
                  button="alt"
                  icon={icons.GLOBE}
                  label={__('Share')}
                  onClick={() => openModal({ id: MODALS.SOCIAL_SHARE }, { uri, speechShareable })}
                />
```

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by jessopb** [comment]
I've started this.

**Comment by tzarebczan** [comment]
Closed via https://github.com/lbryio/lbry-desktop/pull/2088, thanks @jessopb !
