### ISSUE TITLE
Fix Travis runs on forked repos/PRs

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2093]
## The Issue
Currently, Travis fails to run on PRs that are from forked repositories due to lack of code signing access. We want to disable code signing for these builds and allow them to complete. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by alyssaoc** [comment]
@nikooo777 is this something you are working on currently?

**Comment by nikooo777** [comment]
i'll be tackling this tomorrow as part of my new sprint
