### ISSUE TITLE
Better feedback after credits are sent

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2097]
## The Issue
When a user sends LBC using the Send/Receive screen, there is a snackbar that the funds are sent (edited - we do get a snackbar, I missed it!). We also provide a link to the TX or possibly to the overview/tx page. 

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by seanyesmunt** [comment]
@tzarebczan Gonna close this. The link will be back when the new notifications PR is merged.
