### ISSUE TITLE
Cleanup Autoplay

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#2099]
See https://github.com/lbryio/lbry-desktop/issues/584  for the original discussion of autoplay.

I propose the following changes:

- Default autoplay to true
- Move autoplay setting to "settings" rather than the file page itself

However, this should not be done until autoplay reduces disk usage. Solutions:

- Wait on https://github.com/lbryio/lbry/issues/1311
- Stop downloading the file when the user navigates away unless it was specifically initiated by pressing download

**Comment by seanyesmunt** [comment]
Autoplay currently only exists in settings, but is still defaulted to `off` until lbryio/lbry#1311 is addressed.

**Comment by seanyesmunt** [comment]
Additional feature idea. Someway to autoplay content on a specific channel. If I have a channel I like, I can go to that channel and click something like "play all"

**Comment by tzarebczan** [comment]
This is now fixed.
