### ISSUE TITLE
Auto-render certain types of content

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#2100]
For certain types of content, it seems safe to automatically render it without requiring the user to press "View". Some examples: markdown, HTML (unless we think there is a security risk), 3D-printing

Related: #2099, #584 (historical discussion)

**Comment by tzarebczan** [comment]
Related: https://github.com/lbryio/lbry-desktop/issues/1850

**Comment by tzarebczan** [comment]
This happens now with autoplay enabled.
