### ISSUE TITLE
Add content filtering on search page

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#2111]
After https://github.com/lbryio/lighthouse/pull/135 is merged, we can add filtering on the search page.

### Expected Behaviour
This will probably be some sort of dropdown, similar to other filters in the app (tx list, downloads)

### Suggested Solutions
This value should persist between searches, but only for searches on the search page (not related content).

This feature will also be done in `lbry-redux`.

### Definition of Done
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Related, but for channels: https://github.com/lbryio/lbry-desktop/issues/1735

**Comment by seanyesmunt** [comment]
Closed with #2282
