### ISSUE TITLE
Show users eligible content creators to be co rewarded

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbry-desktop#2114]
This is to support the [epic](https://github.com/lbryio/lbry-desktop/issues/2113) for co-rewarding creators from users collecting rewards. [this] will provide the capability of rewarding content creators automatically. This issue is for determining how this feature will be presented to the user. One idea was showing an icon next to channels or claims that are allowed. We want the user to get the emotional reward of helping someone else out, with the ask to share that within their community/tribe. 

- [ ] How will this be presented?
- [ ] Will @lbryio/appsquad need addition requirements from @lbryio/api  to support?
- [ ] Can this be shared will mobile team or do they need their own issue?

**Comment by seanyesmunt** [comment]
I think it could be cool if the reward info contains data about who it helped and or how much was sent to them too. We could display that in the rewards table/on the success snackbar.

This can all be shared with the mobile app since all of the rewards code lives in https://github.com/lbryio/lbryinc

**Comment by tiger5226** [comment]
@seanyesmunt The idea is that all youtube sync partners will be eligible for the co-reward. What I mean was, how are we presenting letting the user know that if they watch a video for a reward, the content creator they choose gets the co reward. Or, are you saying the user should not know and it should just be a notice after the fact? 

I can certainly put who and how much was given for the co-reward as an output of the `/reward/list` API.

**Comment by seanyesmunt** [comment]
I'm not sure how (if?) we would display it to users before they claim a reward. I think if we present it somewhere before a user claims a reward, it will just be a general message and not dependent on internal apis.

**Comment by tzarebczan** [comment]
Don't think we'll be taking this on.
