### ISSUE TITLE
Pressing escape in wunderbar should do something useful

### ISSUE THREAD

**Issue by jessopb** [lbryio/lbry-desktop#2116]
## The Issue

When I click in wunderbar which is displaying current location (perhaps to copy or edit), if I start typing, or searching and don't like my progress, escape does nothing.

### Steps to Reproduce
1. Start searching.
2. Press escape. Nothing happens.
3. ???

### Expected Behaviour

Tell us what should happen.
Pressing escape should clear, then reset to fully selected current location.

### Actual Behaviour

When pressing escape, nothing happens at all.

## System Configuration

App | 0.25.1
-- | --
Daemon (lbrynet) | 0.21.2
Wallet (lbryum) | 3.2.4
Connected Email | jessopb@gmail.com
Reward Eligible | Yes
Platform | Linux (Linux-4.15.0-38-generic-x86_64-with-Ubuntu-18.04-bionic)

**Comment by seanyesmunt** [comment]
This is a great idea. I agree with the expected behavior, that is the same way chrome handles the escape key.

**Comment by adamflitney** [comment]
Could I have a go at this?

**Comment by tzarebczan** [comment]
@adamflitney she's all yours! Added the Hacktoberfest label also.

**Comment by luckymurari** [comment]
@adamflitney Are you working on this? If not, shall I have a go at this?

**Comment by adamflitney** [comment]
@luckymurari I was planning on doing it, but life got a bit busy. Happy for you to have a go rather than it be left for a while. :)

**Comment by jessopb** [comment]
https://github.com/lbryio/lbry-desktop/commit/ce7be7229bbbcfa6812a8e6400d78d9920501ece merged
