### ISSUE TITLE
Not easy enough to see content title without clicking or navigating.

### ISSUE THREAD

**Issue by jessopb** [lbryio/lbry-desktop#2117]
## The Issue

I can't see the whole title without going to the file page. Especially a problem for seeing at a glance whether something is "part 2".

### Steps to Reproduce

1. Go to any list view or channel page
2. See a title with " Blah blah ..."

### Expected Behaviour

There should be some way for the user to see the rest of the title without clicking.

### Actual Behaviour

User has to visit the file page to see the rest of the title. 

### Suggested Solutions

1) a simple tooltip expanding the title
2) title and description transform to flood the card with background on mouseover.

## System Configuration

App | 0.25.1
-- | --
Daemon (lbrynet) | 0.21.2
Wallet (lbryum) | 3.2.4
Connected Email | jessopb@gmail.com
Reward Eligible | Yes
Platform | Linux (Linux-4.15.0-38-generic-x86_64-with-Ubuntu-18.04-bionic)
Installation ID | HSS8eguzoqWKRtiWe9bFs9JbowqdD36YAbqf92Mhz1Fjp

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by seanyesmunt** [comment]
Currently, you can hover over the title and the entire title is shown in a popup, which is the same way youtube does it.

**Comment by seanyesmunt** [comment]
<img width="574" alt="screen shot 2018-11-21 at 12 54 21 pm" src="https://user-images.githubusercontent.com/16882830/48859636-9a04a480-ed8c-11e8-89ad-908eebd3b218.png">

(my mouse disappeared when taking the screenshot)

**Comment by jessopb** [comment]
Oh, ok. Then this change will be in the next release? I didn't see "title" mentioned in any issues. My 25.1 thinks it's up to date.

**Comment by seanyesmunt** [comment]
it should work in that version too

**Comment by seanyesmunt** [comment]
https://github.com/lbryio/lbry-desktop/pull/1980

**Comment by seanyesmunt** [comment]
Oh duh. I had my months off, we haven't had a release since that PR.

You can try the latest RC http://build.lbry.io/app/build-4183_commit-240ca20_tag-v0.26.0-rc.7/

It should work there.

**Comment by tzarebczan** [comment]
Works on Windows on the rc. Careful with that rc, it won't migrate a wallet correctly.

**Comment by jessopb** [comment]
OK, closing the issue.
