### ISSUE TITLE
App Storage & Social Media Integrations + Privacy Mode

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry-desktop#2118]
# LBRY Flexibility & Intergrations

## Storage Integrations

An integrations tab containing integrations options that would allow users to connect their Amazon AWS/S3, Dropbox, Google Drive, One Drive and any other popular service that can be utilised.
This would tally nicely with current LBRY mirroring servers and offer greater storage flexibility.

## Social Media Integrations

Also, having optional social media integrations would work well with automatically generated posts each time something is published, using the description, title and thumb image.
This would help get LBRY recognised as a serious contender as a publishing platform.

## Privacy Mode

The above features are useful, but there is also a large user-base that wants to use LBRY for privacy reasons, such as avoiding retaliation from oppressive corporations and governments.

A Privacy Mode would allow the LBRY app to become fully anonymous at the click of a switch, even if a user has added integrations from third parties.

**Comment by tzarebczan** [comment]
Please open only 1 issue per detailed requirement. 

1) LBRY is not meant to be used as a storage mechanism.

2) You can open a more detailed requirement for this. I assume this would mean when I publish something locally, it would automatically make a post on any social media accounts I've connected the app with. Sounds feasible long term, just not sure it's something we'd work on right away.

3) LBRY is already private if a user doesn't sign in, but I could see something like an icognito mode for certain things. You can open a separate issue for this with more detailed requirements. Also don't think we'd work on this anytime soon.
