### ISSUE TITLE
Yerbil can't count

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry-desktop#2128]
## The Issue
In Subscriptions on 0.26-rc9, Yerbil can't determine the right number of subscriptions in a channel.

I thought Yerbil said I had 5 subscriptions when I had 3, but I didn't screenshot it. So I cleared the cache and then Yerbil says:
<img width="1211" alt="screen shot 2018-11-29 at 8 04 58 pm" src="https://user-images.githubusercontent.com/1363664/49268302-9cfa3780-f413-11e8-9b59-7d3c8b05a6c9.png">

I click out of Subscriptions, go elsewhere and then return to Subscriptions and Yerbil says: 
<img width="1174" alt="screen shot 2018-11-29 at 8 05 14 pm" src="https://user-images.githubusercontent.com/1363664/49268324-b602e880-f413-11e8-8fe6-e6b0f2882699.png">

I am sure I only have 5 subscriptions, because I just added two and got "The Hoagie" reward (for 5 subscriptions.
## System Configuration

- LBRY Daemon version: 0.30.1rc6
- LBRY App version: 0.26 rc9
- LBRY Installation ID: 7hnwPnReHrWcqdJ63ULdETDwVHuNUdd2gBAHiHVsVzV5xAGncyF3TV2HBLpkfk7EqV
- Operating system: MacOS 10.14.1

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by seanyesmunt** [comment]
Thanks for the issue Julie. I'll check it out.

**Comment by tzarebczan** [comment]
The first blank one is probably because subscriptions aren't loading. The incorrect one not sure. @jsigwart can you open the console and watch the network calls to lbry.io and claim_list_by_channel on startup? You'll see what channels you are actually subbed to.

**Comment by tzarebczan** [comment]
Closing, addressed in next release.
