### ISSUE TITLE
Remember my settings (especially on file delete Modal)

### ISSUE THREAD

**Issue by oakey22** [lbryio/lbry-desktop#2132]
When you download a video and wish to delete it, you have to select "Also delete this file from my computer" every time. Can. There be a checkbox to remember this setting so I do not need to do it for every download I want to delete?

https://spee.ch/f/IMG20181204152519

**Comment by tzarebczan** [comment]
Thanks for opening this Oakey! For the download specific one, maybe it can be done along with:https://github.com/lbryio/lbry-desktop/issues/895 

We could explore to see what other settings might be in this boat.
