### ISSUE TITLE
Deleting files in My LBRY > Downloads results in empty tiles

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry-desktop#2137]
## The Issue
After individually deleting files in my Downloads in the desktop app, when I go to look at My LBRY Downloads, I have gray blank tiles showing up in places.

### Steps to Reproduce
1. Delete files in My Downloads
2. Go back to My LBRY > Downloads and see if there are gray placeholders
3. It seems to happen sometimes but not others (argh)

### Expected Behaviour
Deleting a file should remove it from the computer (if you told it to) and not give a generic gray tile in its place (sometimes).

### Actual Behaviour
Screenshots of the behavior:

<img width="1403" alt="screen shot 2018-12-06 at 9 44 13 pm" src="https://user-images.githubusercontent.com/1363664/49630426-f7127400-f9a2-11e8-8160-cffd6e8cb5c6.png">

<img width="1419" alt="screen shot 2018-12-06 at 10 01 26 pm" src="https://user-images.githubusercontent.com/1363664/49630432-01347280-f9a3-11e8-9850-ececcce6611c.png">

## System Configuration

- LBRY Daemon version: 0.30.1rc9
- LBRY App version: 0.26.0-rc.14
- LBRY Installation ID: 7hnwPnReHrWcqdJ63ULdETDwVHuNUdd2gBAHiHVsVzV5xAGncyF3TV2HBLpkfk7EqV
- Operating system: MacOS Mojave, 10.14.1

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Are you sure these are happening after deleting? The most common scenario is an abandoned file that is downloaded. Already logged under https://github.com/lbryio/lbry-desktop/issues/960 / and overall fix is part of https://github.com/lbryio/lbry-desktop/issues/1203 

run a file_list api call (or check the network) tab to see what those might be.

**Comment by jsigwart** [comment]
I had no gray boxes before I deleted files. If they were abandoned claims, then I had old files on my drive that matched up...

**Comment by jsigwart** [comment]
Still there after clearing the cache. Also tried a restart of the app, and they're still there.

**Comment by tzarebczan** [comment]
Api commands are easier to run now, just use lbrynet to call file_list.`./lbrynet file_list`

Search for lbrynet on your file system (noticed the Mac faq didn't have this location recently).

**Comment by seanyesmunt** [comment]
Should be fixed with #2129

**Comment by tzarebczan** [comment]
Closing, will be fixed in next release
