### ISSUE TITLE
Pending channel not available in Publishes screen sometimes

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2138]
## The Issue
Breaking out from: https://github.com/lbryio/lbry-desktop/issues/2125

After you create a channel, publish something, and while it's pending - if you navigate back home/other screens before going back to the Publish page, the channel may not be available. If you refresh the app, it fixes itself. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Still seems to be an issue - probably related to how we are storing pending channels in redux. Must navigate homepage + publishes / wallet, and then back to Publish page to reproduce it.

**Comment by seanyesmunt** [comment]
I think this can be closed?
