### ISSUE TITLE
Copy icon cut off for some users

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2142]
## The Issue
This is happening to @skhameneh on the address copy button as well. 
![image](https://user-images.githubusercontent.com/8120721/49882965-b5992300-fdff-11e8-8e41-60d1e9e0996d.png)

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
@Invariant-Change tracked this down and it's related to the css around the svg icon: ```To fix the SVG rendering issue, I've added the stroke-width: 1; CSS like this to _buttons.scss. I```

``` 
.btn {
  min-width: var(--btn-height);
  height: var(--btn-height);
  align-items: center;
  background-color: $lbry-teal-5;
  border: none;
  border-radius: var(--btn-radius);
  color: $lbry-white;
  cursor: pointer;
  display: flex;
  fill: currentColor; // for proper icon color
  font-size: 12px;
  justify-content: center;
  padding: 10px;
  position: relative;
  text-decoration: none;
  transition: all var(--animation-duration) var(--animation-style);

  & svg {
    stroke-width: 1;
  }
  ```

**Comment by Invariant-Change** [comment]
Since this, the code has changed and a [bug ](https://github.com/lbryio/lbry-desktop/issues/2151) is now present preventing the icons from showing to test. I will revisit once the `ModalSocialShare ` modal is fixed so that I can make sure the icon fix is working.

**Comment by Invariant-Change** [comment]
https://github.com/lbryio/lbry-desktop/pull/2167
