### ISSUE TITLE
Redesign Fixes

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#2151]
### Outstanding issues
- <> navigation issues sometimes (https://spee.ch/7/redesign-scroll)

### Fixed
- ~call reward list after getting confirmation from lbry.io - this ensures existing accounts show correct rewards.~
- ~Publish page - Price > value and drop down alignment (same with other value/dropdown pairs, i.e. settings page)~
- ~Publish page - choose thumbnail / enter url spacing~
- ~last item in row is not sized properly~
- ~File page viewer doesn't fit most thumbnails and related content requires more scrolling. I liked the related content to be on the right hand side.~
- ~Requesting stream text hard to see in some cases (previous app greyed out the thumb)~
- ~subscribe/tip/share text alignment~
- ~reward ribbon alignment in title~
- ~file action icons alignment~
- ~Play/view icon is greyed out until mouse over - intentional ? Think it looks better colored always.~
  - Going to keep this
- ~autoplay button removed from file show page?~
    - Will be re-added at a future date
- ~Media properties hard to see on search/recommended~
- ~can't click hyperlink if "more" is not clicked:~ 
  - ~lbry://test1121212121#a8f41412179debf5883cced81656357a9eb559c3~
- ~Should spacing between different elements in the same column? See Rewards area of Reward overview page.~
- ~positive value on tx history are black text in dark mode~
- ~pending publishes not greyed out~
- ~All subscriptions / Latest only should be buttons similar to Refresh? ~
    - They act as "links" so the green text makes more sense
- ~Dark mode channel page - hover over on page number whites out value~
- ~Publish success message could use some styling~
- ~Homepage extra spacing at bottom of featured section~
- ~Rewards are all in a single column now - do we want this?~
- ~Clear the cache icon is not clear~
   - possibly will increase button size so this is more clear, but keeping it for now.
- ~Subscription - header needs more space~
- ~glossy tile loading gradient looks bad (looks like the app locks up before cards are rendered)~
-  ~Meta text in light mode hard to see~
- ~Button alignment on auth screen~
- ~Invite button misaligned~
- ~History table wrong color in dark mode~
- ~Thumbnail stretches past the container on large screens on the file page.~
  - Looks ok, but I think it could be handled better
- ~File action buttons on File Page not aligned on the smallest screen size~
- ~Comments button is very close to the "Comments" header~
- ~Outline buttons are hard to see in dark mode when hovering~
- ~"New" badge spacing is different from other icons on FileCard~
- ~Can't hit > on explore page for horizontal navigation~
  - Now with trackpad scrolling!
- ~Tip modal doesn't work~
- ~Share modal doesn't work~
- ~channel page navigation area misaligned (bottom)~
- ~tables/pages stretch across horizontally on large screen sizes~
- ~transaction page: `[object Object] fee`~
- ~"Editing a claim Read our FAQ to learn more." - on same line, edit page~
  - Kept them on the same line but added a period.
- ~Transaction history - export button is small compared to dropdown~
- ~Media properties misaligned~
- ~Can't close error modal from spee.ch thumb upload~
- ~wrapping in snackbar, see below~
  - Intentional. I added some more spacing though.

![image](https://user-images.githubusercontent.com/8120721/50405094-baee5a00-077d-11e9-9994-8c5a4b0099f8.png)

**Comment by tzarebczan** [comment]
New: 
- last item in row is smaller than rest on homepage
- show page title/desc overlapping on large screen

**Comment by tzarebczan** [comment]
- icons look blurred / small 
![image](https://user-images.githubusercontent.com/8120721/51001941-bbb61880-14ff-11e9-9814-bb8305f67c1a.png)

**Comment by tzarebczan** [comment]
Some feedback about the balance in top left from community members: new users may get confused about what 0.0 LBC means. Previously it used to say "You have xx LBC", so at least it gave them a small hint. They will have more information when they click the balance from the overview screen though.

**Comment by seanyesmunt** [comment]
@tzarebczan Added a more descriptive title that is shown on hover:
`Your balance is x.x LBRY Credits`

**Comment by seanyesmunt** [comment]
Will fix the navigation issue in a future release

**Comment by tzarebczan** [comment]
- [ ] text size on manual upgrade prompt (not the automated one):
![image](https://user-images.githubusercontent.com/8120721/51135283-9c710100-1807-11e9-93d0-b097821f4fb8.png)
- [ ] mention rewards on  Invite page?
