### ISSUE TITLE
Unread count reset when navigating other channel pages

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2154]
## The Issue
Thanks to a community member (Brendon) for spotting this one. 
If you are subscribed to a channel and then navigate to any other page (besides 1), the unread count gets reset to 10 and the `new` tag comes back. It takes a few seconds for this to occur after navigating to the other page.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by seanyesmunt** [comment]
Fixed in #2176
