### ISSUE TITLE
Credits Warning After Publishing When Editing Another Claim.

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry-desktop#2158]
## The Issue
After publishing a file, the wallet balance artificially goes to zero for a short time. During this time, if you try to edit another claim, an "**LBRY Credits Needed**" warning is displayed. This could be confusing to new users.

### Steps to Reproduce
1. Publish a file.
2. Immediately edit existing claim.

### Expected Behaviour
The app should understand when the zero balance isn't artificial and suppress warnings.

### Actual Behaviour
A "LBRY Credits Needed" warning is displayed.

![image](https://user-images.githubusercontent.com/29914179/50638968-587e3080-0fab-11e9-8a31-9fd5987878d9.png)

### Suggested Solutions
An extra condition to the warning, so it only fires if all conditions are met.

## System Configuration

![image](https://user-images.githubusercontent.com/29914179/50638959-4dc39b80-0fab-11e9-8cfb-97f59fb32d59.png)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Thanks for filing this! I'm going to talk to Sean to see if this should be improved from the app side or if we need to figure out a better way to handle it on the SDK. What happens, and only in certain cases, is that the funds are marked as spent before the change arrives in another address and balance is recalculated (this should only happen for a short period of time before fixing itself, and only on larger transactions.)

**Comment by tzarebczan** [comment]
I've opened https://github.com/lbryio/lbry/issues/1740

**Comment by tzarebczan** [comment]
Closing until https://github.com/lbryio/lbry-sdk/issues/1740 is fixed. This should only rarely happen if the temp balance goes to 0.
