### ISSUE TITLE
Reward Tiles don't update properly

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbry-desktop#2161]
Currently we don't have multiple rewards of the same type so the bug is never seen. When a reward is claimed the view is regenerated and the reward of the type claimed is removed. However, if there are multiple rewards of the same type in multiple tiles, and I claim 1 of them, then of the remaining ones, one of them gets stuck in a state, only resolved by a reload of the app. 

<img width="548" alt="screen shot 2019-01-03 at 8 55 48 pm" src="https://user-images.githubusercontent.com/3402064/50671070-80ff2e00-0f9d-11e9-8394-57de0d137b00.png">

Specifically this is for the change to multiple youtube channels being possible and rewardable. In the above screenshot, you will see below I claimed a different reward than what is "stuck".

**Comment by tzarebczan** [comment]
Update with new approach from internal apis: ```now the rewards of same type are duplicating when claiming other rewards + the reward amount shows the same value (i.e i have 3 channels, 100, 200, 300 LBC, but all 3 rewards show 100 - the api call is correct```
