### ISSUE TITLE
Can't close error modal from spee.ch thumb upload

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2162]
## The Issue
If you run into an error uploading a spee.ch thumb (I ran into one on VPN before, or if it were to fail for some reason), you can't close the modal that comes up - it requires an app reboot. 

Easy way to test this at the moment is to upload a thumb with an apostrophe in the filename. 

![error](https://media.discordapp.net/attachments/377895389992321064/525948297928638485/error.jpg?width=400&height=273)

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by seanyesmunt** [comment]
Working on this
