### ISSUE TITLE
Additional search options (sorting, simple filters)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2163]
## The Issue
Along with https://github.com/lbryio/lbry-desktop/issues/2111 / https://github.com/lbryio/lbry-desktop/issues/1764 / https://github.com/lbryio/lbry-desktop/issues/1735, we should also add simple search result sorting and filtering. Examples include:

Sorting by title asc/desc
Sorting by date (currently height) asc/desc
In last day, week, year, month, etc (time period filtering)
Effective Amount asc/desc
View count (not available yet)
Paid/Free
Anonymous/ in a Channel
Only search channels
Only search description
Has Thumbnail

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by lrq3000** [comment]
Humble user opinion: sorting by date is I think the most important to implement, as regular users will want to check out the latest videos. Currently the videos seem to not be sorted at all, but to randomly populate the search results.

**Comment by kauffj** [comment]
Using #2801
