### ISSUE TITLE
Add loading animation to search page

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2171]
## The Issue
The improve the UX while searching, we should add a loading animation to the search page. Otherwise, it first says "no results" and then the results start coming in.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by nestordominguez** [comment]
fixes https://github.com/lbryio/lbry-desktop/issues/2171

**Comment by tzarebczan** [comment]
Fixed in https://github.com/lbryio/lbry-desktop/pull/2644
