### ISSUE TITLE
lazyresolve claims, especially on downloads/search page

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2172]
## The Issue
If a user has many downloads (separate issue on why we re-resolve all these filed under:https://github.com/lbryio/lbry-desktop/issues/1203)  or if many things are resolved at once (i.e on search page), the number of parallel calls may make the app lockup and put more load on the daemon. We could try resolving only when the claim is ready to be shown on the screen or optimize loading only some percentage until the user scrolls. 

Credit to @seanyesmunt for the idea...

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by seanyesmunt** [comment]
A super simple way to do this would be to add a check for every `FileCard` component to see if it's on the page, if it isn't, don't resolve.

Then listen for a scroll event and perform the check again. 

The key part would be to ensure performing all of these checks aren't equally as slow.

**Comment by seanyesmunt** [comment]
Working on this. Will implement on the homepage first, since new users won't run into issues on the other pages until they've used the app for a while. The implementation may be slightly different too.

Mostly experimenting at this point.
