### ISSUE TITLE
Shouldn't hide modals after reward is claimed, only if it's from the reward code

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2177]
## The Issue
~If you have a modal open, i.e. share, and you get a snackbar, the modal closes. This happened to me after I subbed to something and then went to share - the sub triggered a reward, which resulted in snackbar. ~

Realized this is because we hide modals on reward success, which helps with the reward code modal, we need to add a check for this so we don't hide the wrong modals

### Expected Behaviour
Tell us what should happen.

### Actual Behaviour
Tell us what happens instead.

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by Ruk33** [comment]
Hi @tzarebczan I just confirmed the issue is still happening, you mind if I work on it? Regards.

**Comment by tzarebczan** [comment]
Yep, please do...I've run into this one many times, especially when the transactions / actions take longer to come back, and you start doing something else that pops up a modal.

**Comment by Ruk33** [comment]
Hello @tzarebczan here is the PR https://github.com/lbryio/lbry-desktop/pull/5270. Please keep in mind I wasn't able to test the flow with real data since I don't have a reward code. How do you guys test this type of flows? do you have mock/test reward codes? If you have a test code I can use, I'd be happy to test it.

Thanks!
Regards.
