### ISSUE TITLE
Add new version / description on upgrade prompt

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2186]
## The Issue
On the upgrade prompt for new versions, we should list the version and/or the tag from GitHub. Most times we add a release description which should suffice: "Clarke - 0.26.1". There will be a few different prompts to ad this one (one for auto, one for manual, and Linux). 

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by Ruk33** [comment]
How about showing the release changes in the app?

I just hacked a quick sample using GitHub's release api (found in https://docs.github.com/en/rest/reference/repos#releases):

![image](https://user-images.githubusercontent.com/1719111/106523425-de894000-64bf-11eb-9d21-8a43b991a0c5.png)

The content is fetched from the latest release and then displayed using remark (markdown).

Does this works @tzarebczan ?

Regards.

**Comment by tzarebczan** [comment]
That looks great! Can we add the tag/version number next to "new version" ?

**Comment by Ruk33** [comment]
We sure can:

![image](https://user-images.githubusercontent.com/1719111/106527295-ca484180-64c5-11eb-9741-095629747d40.png)

Added loading state:

![image](https://user-images.githubusercontent.com/1719111/106527366-ea780080-64c5-11eb-9ab6-46c832fdaf21.png)

Added failure state:

![image](https://user-images.githubusercontent.com/1719111/106527392-f82d8600-64c5-11eb-9ced-1c5c1de250dc.png)

**Comment by Ruk33** [comment]
Alright, I just pushed the PR: https://github.com/lbryio/lbry-desktop/pull/5461
Regards!
