### ISSUE TITLE
Better UI indication of why taskbar icon is filling/downloading

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#2187]
(I understand what's going on here, just putting on my ignorant user hat.)

When the LBRY desktop app is running and downloading a file, it fills the icon in the taskbar as the file is downloading.

However, outside of being on the URL of the specific file being downloaded, there is no way to tell what this bar is or why it is filling. Especially for users who (already) get confused about the fact that downloads are happening when they click play, this seems somewhat likely to cause confusion.

I'm not sure what the proper solution to this is, but one idea to consider is whether we should have an indicator in some combination of Subscriptions, My LBRY, Downloads, or the cards themselves when something is actively downloading.

**Comment by tzarebczan** [comment]
Similar to https://github.com/lbryio/lbry-desktop/issues/1933 - this may also change with streaming mode (we may still want to show progress though?)

**Comment by tzarebczan** [comment]
It's been removed
