### ISSUE TITLE
Unify upgrade modals

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#2188]
`modalAutoUpdateDownloaded` and `modalAutoUpdateConfirm` appear to have both similar functionality and templating. Can they simply be the same thing?

**Comment by JakeVdub** [comment]
I'll try giving this a shot later today!

**Comment by tzarebczan** [comment]
Thanks @JakeVdub ! I'll add the Hacktoberfest label to it also. Make sure to check outhttps://lbry.com/news/hacktoberfest-2019

**Comment by pranshuchittora** [comment]
I would like to take up this issue.

**Comment by pranshuchittora** [comment]
Discussion:
As I can see that both the modals are almost same, but with a different set of strings and functions. The way I would like to combine them is to specify a different config (aka Object) for both of them which contains all different properties, keeping 80% of the structure same. 

When any of them is called, specific config is passed to the abstracted modal.

**Comment by tzarebczan** [comment]
There's already a pr for this issue, it's been claimed.

**Comment by tzarebczan** [comment]
Closed in https://github.com/lbryio/lbry-desktop/pull/2959
