### ISSUE TITLE
Subscriptions UI Changes

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#2190]
1. Can the suboptions (All, Latest) that appear at the top of the subscription area appear in the left navigation once I've clicked into the area? (Either replacing the UI element at the top, or in addition to it)
2. It seems strange that "All" and "Latest" are effectively a toggle between "By Date" and "By Channel". I understand that "All" shows me things I've already watched, maybe we can change this to be two separate toggles somehow? All / Latest and Date / Channel?
3. In general I find the navigation of the top of the subscriptions area to need a rework (if we're keeping it). It's not clear at all that the faded element is the one I have selected.

**Comment by tzarebczan** [comment]
Agree about the side navigation and quirks with top nav, this was something I was asking Sean if we should change. 

I was going to suggest a third view, which shows all subs, by channel - your suggestion should cover that! I like it even better.

**Comment by tzarebczan** [comment]
The subscription re-work should also include new channel images as a way of selecting/filtering data - potentially on top or somewhere in the side bar.
