### ISSUE TITLE
Display error message from SDK on modal

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2194]
## The Issue
There are a few different scenarios where we display the failed to download error modal, but we don't display what the error was. We just ask users to try again or contact us. Typical failure reasons would be https://github.com/lbryio/lbry-desktop/issues/1025, not having permissions to write to the download folder, timeouts, disk space or database issues. 

I believe the error modal needs to support some text styling for this to look good, otherwise injecting the error by adding a catch is fairly simple: https://github.com/lbryio/lbry-desktop/blob/3321483395241ed0621ce2eb4dfa843af871967e/src/renderer/redux/actions/content.js#L185
## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by seanyesmunt** [comment]
Fixed in #2257
