### ISSUE TITLE
amount/transaction/date being squished on smaller screens on rewards page

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-desktop#2196]
## The Issue
i use a square monitor 1024x768 screen resulution but after i tested it and go to the rewards page i seeing amount/transaction/date being squished on smaller screens on the rewards page

### Steps to Reproduce
1. use small screen e.g 1024x768 monitor resulution
2. go to rewards
3. and then you will see as i mentioned on this screenshot image

### Expected Behaviour
Tell us what should happen.

### Actual Behaviour
Tell us what happens instead.

### Suggested Solutions
Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version: 0.30.4
- LBRY App version: 0.27.0
- LBRY Installation ID: 8K9e1PbwApDnXBbxCBKnYbNLAd2Ytf4LabE8YmDQywbHCp2qxnKfn1cb94zkLbyFxd
- Operating system: Windows (Windows-10-10.0.17763)

## Screenshots

![image](https://user-images.githubusercontent.com/26609573/51211341-c7fb0500-1947-11e9-94a0-2777e4307baa.png)

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by tzarebczan** [comment]
Thanks for opening this @ykris45 !! Wanna take a shot at fixing it?
