### ISSUE TITLE
Alternative paragraph spacing rule (modalEmailCollection spacing is incorrect)

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#2202]
`modalEmailCollection` has is missing spacing below the last paragraph due to this rule:

https://github.com/lbryio/lbry-desktop/blob/bed9b1f95f6af3beb3df01db57e5dea44be773ae/src/renderer/scss/component/_card.scss#L86

I understand the utility of a `p:not(:last-child)` rule but IMO `p:not(:last-of-type)` makes this spacing tough to fix.

With `:not(:last-child)`, I can eliminate spacing on a `<p>` element by wrapping it and any relevant ancestors in `<div>`. With `:not(:last-of-type)`, I'm not sure what change you could even make to this markup to get the paragraph to have spacing.

**Comment by seanyesmunt** [comment]
Hm. Yeah this is one of the tricky things with using `margin-bottom`. Wrapping each group in a `.card__content` should fix it, and wouldn't be _that_ crazy since they are separate element groups. But I'm not a super big fan of that.

**Comment by kauffj** [comment]
I think this is why `:not(:last-child)` instead of `:not(:last-of-type)` ends up being better.

When you have a `<p>` that is a last-child and you still want spacing below it, it can be provided by the parent `<section>` or `<div>`. When you have a chained elements and you have a `<p>` that you don't want a margin-bottom on, you can wrap that `<p>` (plus possibly some of it's previous siblings) in a single unandorned `<div>`.

Alternatively, you can be explicit about which `<p>` elements do and do not get spacing, but I think that's probably silly.

**Comment by seanyesmunt** [comment]
Yeah I just messed with it a bit. I guess I was confused. 

I agree, `:not(:last-child)` is better. Will fix and include in the next release.

**Comment by seanyesmunt** [comment]
Changed to `:last-child` in https://github.com/lbryio/lbry-desktop/pull/2206
