### ISSUE TITLE
Refreshing should not should not send you back to the home screen

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#2203]
## The Issue
As a user, when I refresh something, I expect to stay on the same page
As a developer, when the app reloads after changes, I expect to stay on the same page

### Suggested Solutions
Currently, the refresh just reloads the html page. We could hijack that, but it might affect cases where the app is in a bad state and refreshing actually fixes that. We should probably only keep the current navigation state, (and publish?) and repopulate those on refresh.

**Comment by tzarebczan** [comment]
This is now fixed.
