### ISSUE TITLE
Actually report errors that cause error modals

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#2205]
## The Issue
Currently on the error modal, we say: "We're sorry that LBRY has encountered an error. This has been reported and we will investigate the problem.", but we aren't doing that. 

### Possible solutions
- Post errors to a slack channel (probably have to go through internal api's)
- Mixpanel
- Automatically take a screenshot and fax it to lbry hq

**Comment by tzarebczan** [comment]
In the short term, would like to get them the actual error shown to them: https://github.com/lbryio/lbry-desktop/issues/2194

**Comment by seanyesmunt** [comment]
This is added. We may want to suppress individual errors (like the max key fee error). But honestly that shouldn't be an error modal anyway
