### ISSUE TITLE
Fix homepage channel category loading

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2211]
## The Issue
When I added the claim ids to items on the homepage categories, the row gets treated similar to the subscription suggestions and shows 20 items at a time. This is inefficient for first start since we resolve all the homepage URIs, and then re-resolve the 20 items using claim_list_by_channel. If a user is subbed to the channel already, we call claim_list_by_channel another time too. We should also be calling a batch resolve call on these so that the channel page transition is smooth.

In the short term, we should only load the 10 items on explore page and then look to making the number of items returned to be configurable if we continue with the horizontal scrolling feature. 

The subscribe button on explore page makes for a nice addition when this is enabled, so we should consider fixing this up soon. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
This is fixed (kind of).

Improvements can still re/ re-fetching stuff we don't need to.

**Comment by seanyesmunt** [comment]
Closing this. The fetching stuff will be improved in another PR.
