### ISSUE TITLE
< > navigation problems on some screen sizes

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2215]
## The Issue
Breaking out from:
https://github.com/lbryio/lbry-desktop/issues/2151

https://spee.ch/7/redesign-scroll

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
The current solution for checking if a user can scroll right/left in a list on the homepage isn't very performant. And this bug arises when you click scroll _again_ after it hasn't fully updated after the first click.

**Comment by tzarebczan** [comment]
Gone in next version.
