### ISSUE TITLE
Feature Request: Setting to control app closing behavior

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2220]
## The Issue
Users should be able to control whether or not the app minimizes to the system tray when closing. Many users are unaware that closing the app sends it to the tray, and doesn't actually quit. Other Electron apps like Discord and Slack allow this as well. 

![image](https://user-images.githubusercontent.com/8120721/51558892-905ff180-1e4e-11e9-853a-876af7b5ad56.png)

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
Part of this should be to add `launch on login` too.

**Comment by Ruk33** [comment]
Hello I would like to work on this issue, is it free?
Regards

**Comment by seanyesmunt** [comment]
It's all yours!

**Comment by Ruk33** [comment]
Thank you! will work on it.

**Comment by Ruk33** [comment]
Ok I have sent the changes here https://github.com/lbryio/lbry-desktop/pull/4663 and in lbry-redux https://github.com/lbryio/lbry-redux/pull/346
