### ISSUE TITLE
improve confirm text when editing claim

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-desktop#2228]
When I change the description on a claim I published but don't touch the uploaded file, the confirm dialog still tells me my file has been published.

**Comment by jonnylynchy** [comment]
I can take this one. One modal for new publishes, one for updates.

**Comment by jonnylynchy** [comment]
Pending review - https://github.com/lbryio/lbry-desktop/pull/2573

**Comment by tzarebczan** [comment]
Fixed in https://github.com/lbryio/lbry-desktop/pull/2573
