### ISSUE TITLE
automatically create lbry:// hyperlinks in description

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2229]
## The Issue
https://github.com/lbryio/lbry-desktop/blob/master/src/renderer/component/common/markdown-preview.jsx#L33 works for markdown like ```[test](lbry://test)``` but we should also support regular lbry links like lbry://test / lbry://test#12312321321 / lbry://@channel, etc. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by btzr-io** [comment]
This is actually a bug on the link validation function.

**Comment by btzr-io** [comment]
Related: https://github.com/lbryio/lbry-desktop/issues/1393

**Comment by tzarebczan** [comment]
This has been implemented.
