### ISSUE TITLE
Pass error from spee.ch api on failure

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2242]
## The Issue
spee.ch upload error not being passed back into the error prompt. 
![image](https://user-images.githubusercontent.com/8120721/51933495-72a30700-23cf-11e9-8a6c-5a0ff5be9405.png)

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
Fixed in https://github.com/lbryio/lbry-desktop/pull/2254

**Comment by tzarebczan** [comment]
Right now users see Unexpected token < in JSON at position 0" / "Cannot read property 'slice' of undefined"
