### ISSUE TITLE
determine why lbry://2048 game fails / doesn't play

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2244]
## The Issue
lbry://2048#44064cadfc22dc13419843999ec80e30cf13262b

get this first, which crashes the app. 
![image](https://user-images.githubusercontent.com/8120721/51954163-24145d80-240d-11e9-97a4-9d4b246d2127.png)

reopening it leads to: 
![image](https://user-images.githubusercontent.com/8120721/51954209-5756ec80-240d-11e9-9e09-a9e4bba7822c.png)

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by skhameneh** [comment]
Might be related to Node v8 not supporting `{ recursive: true }` in `fs.mkdirSync()`, see:
https://nodejs.org/docs/latest-v8.x/api/fs.html#fs_fs_mkdirsync_path_mode

I'll make a patch to support earlier versions of Node.
