### ISSUE TITLE
Show new published icon on tiles that are own publishes

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2245]
## The Issue
Per Jeremy, we should show the published icon on tiles for own published content.  Should we also show the download icon if the file is stored locally, or is it meant to be a replacement? Probably the latter...

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
Agreed on using this as a replacement for the download icon

**Comment by seanyesmunt** [comment]
Fixed in #2249
