### ISSUE TITLE
Use broken-heart icon for unsubscribing

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#2262]
We use the heart icon for subscribe, but unsubscribe has no icon. Font awesome has a broken heart icon, let's use that.

**Comment by kuesa** [comment]
I can take this one!

**Comment by seanyesmunt** [comment]
@kauffj I'm not sure we want to use font awesome just for one icon.

@kuesa Maybe they offer svg's for their icons? But still I think it will look weird with two different icon styles next to each other. Maybe we could tweak this svg to make it a broken heart?
https://github.com/feathericons/react-feather/blob/master/src/icons/heart.js#L7-L20

Then we could add it to our list of custom icons:
https://github.com/lbryio/lbry-desktop/blob/master/src/renderer/component/common/icon-custom.jsx

**Comment by kuesa** [comment]
FontAwesome offers SVGs. I'm adding it to the custom icons, and testing to see if it looks good. Will update with a screenshot so you can see how it looks.

**Comment by seanyesmunt** [comment]
Great. Thanks @kuesa !

**Comment by kuesa** [comment]
https://origin.fontawesome.com/icons/heart-broken?style=light

This icon is pretty close, but is a "pro" icon, so it costs money.

**Comment by seanyesmunt** [comment]
Hm, I don't think we should do that. I see there is a free one, but it is solid, which is different from all of our icons. 

Maybe we should just open an issue in https://github.com/feathericons? And possibly try to build our own based on the current heart icon we use.

**Comment by kuesa** [comment]
Used the feather heart to make a couple of broken hearts. I personally prefer the second one, but let me know which one would make the most sense for the rest of the app aesthetic. I might rework the second one so that the lines are more parallel too.

![alt text](https://i.imgur.com/ETTbwVm.png)
![alt text](https://i.imgur.com/yaNBW0C.png)

**Comment by kuesa** [comment]
Here is how it looks in-app:

![unsubscribe](https://user-images.githubusercontent.com/32714062/52394123-1474c480-2a5e-11e9-8656-fdafcbc4f5f1.PNG)

**Comment by seanyesmunt** [comment]
Woah those are pretty cool! Could you share the svgs?

I think it will be easier to tell which looks better when they are on the screen next to the other icons.

**Comment by seanyesmunt** [comment]
Ah you beat me too it!

**Comment by seanyesmunt** [comment]
How does the other one look in the app?

**Comment by kuesa** [comment]
Here is the first one in app:

![unsub2](https://user-images.githubusercontent.com/32714062/52394401-04a9b000-2a5f-11e9-8260-35f43ed5a58a.PNG)

**Comment by seanyesmunt** [comment]
I definitely like the second one more (out of the first images you sent).

I wonder how it would look with less parallel lines though. If the two lines going left and right were more horizontal? I hope that makes sense 😄

**Comment by kuesa** [comment]
![bheart4](https://user-images.githubusercontent.com/32714062/52394642-ca8cde00-2a5f-11e9-85d4-0925cc25f5d6.png)

Something like this?

**Comment by seanyesmunt** [comment]
Sorry, the other icon. With just one line going down.

**Comment by kuesa** [comment]
Ah, how does this look?

![bheart5](https://user-images.githubusercontent.com/32714062/52394890-de850f80-2a60-11e9-9f6f-9db93c20fe1c.png)

**Comment by seanyesmunt** [comment]
Maybe a little bit shorter on the middle line. Could you open a PR with this change? This will be a great addition 🙂

**Comment by kuesa** [comment]
Done!

**Comment by seanyesmunt** [comment]
Whoohoo! I'll take a better look in the morning. 🙂

**Comment by kauffj** [comment]
@seanyesmunt my bad, I forgot we had moved away from fontawesome. Good stuff @kuesa!

**Comment by seanyesmunt** [comment]
No problem. @kuesa crushed it! Just merged in #2272
