### ISSUE TITLE
Sourcing Publish and Search

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbry-desktop#2265]
As part of the drive to identify users that use the app we would like to record hits for Publishing and 
 Searching. No data is to be collected other than the event itself.

The app should call `/event/search` when a user searches(excluding autocomplete).
The app should call `/event/publish` when a user publishes content. 

Standard authentication is required from the app to these APIs. No handling of the result is needed as it always returns a 202 Accepted response if authenticated.

**Comment by seanyesmunt** [comment]
Added in #2266
