### ISSUE TITLE
Inverse buttons hard to read when hovering in dark mode

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#2270]
## The Issue
On dark mode, inverse buttons are hard to read when hovering. They are missing some css.
`.btn--inverse` should use the color `$lbry-white` when hovering (in dark mode).

### Steps to Reproduce

- Hover over the refresh button on the transactions list
- Look

<img width="500" alt="screen shot 2019-02-05 at 3 51 24 pm" src="https://user-images.githubusercontent.com/16882830/52303511-30913c80-295e-11e9-85b8-985ba99f32bd.png">

**Comment by derek-yesmunt** [comment]
Hey Sean, I'll take this one.
