### ISSUE TITLE
upgrade electron to latest version

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2273]
## The Issue
https://github.com/electron/electron/releases

There was some discussion about waiting for 5 to get out of beta, or go with 5. Looks like a new update for 5 was just released 4 days ago. 

### Suggested Solutions

Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
Upgrading to 4 in https://github.com/lbryio/lbry-desktop/pull/2276/files

4 was only recently working after some of our dependencies made some updates to work properly with it. Haven't tested 5 though so that might work. I don't want to add it until it's out of beta though.

**Comment by tzarebczan** [comment]
On master...
