### ISSUE TITLE
Modify sdk download script to use build.lbry.io

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2278]
## The Issue
To make app building more flexible with unreleased SDK version, we should allow the sdk download script to use the build.lbry.io folder based on a commit. This should still support the current way when a  commit is not used (whether it downloads from build or github is debatable). 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by lyoshenka** [comment]
@seanyesmunt i kind of lost track of this. do you still want me to do it?

**Comment by seanyesmunt** [comment]
I didn't know you were ever going to. I wouldn't worry about it. I wouldn't use this, I don't think at least. I just start the sdk independently if I want to run a version that isn't released.
