### ISSUE TITLE
Be consistent between upgrade and update

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#2290]
Do users upgrade or update when they download a new version of LBRY Desktop?

The popups and buttons inconsistently switch between the two words. We should always use the same one.

I'm mildly in favor of upgrade, but both are fine.

**Comment by seanyesmunt** [comment]
I think `upgrade` is fine. To fix, you should be able to just do a global search for `"update"` and then change that to `"upgrade"`, but only for text that is visible to users, variables or comments don't need to change.

**Comment by derek-yesmunt** [comment]
Hey Sean, I'll take this one.
