### ISSUE TITLE
Don't allow downloaded videos to be NEW in subscriptions

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-desktop#2292]
## The Issue

Firstly, this is a relatively minor hiccup that occurs during upgrades and when I switch between stable and development versions. The app gets confused about which videos from subscriptions are unread, and usually marks many as unread even though I have seen them before and downloaded most of them.

### Steps to Reproduce

1. Use the stable release of LBRY and subscribe to stuff
2. Switch to a development version from the repo
3. Go to the subscriptions tab

### Expected Behavior

Ideally, unread vs. read status should persist when you change versions. Failing that, downloaded content (shown with the folder icon) should never be counted as unread.

### Actual Behavior

Videos you have in fact seen are now NEW in the subscriptions section - even ones that the app recognises as having been downloaded!

### Suggested Solutions

Make _downloaded_ imply _read_.

## System Configuration

```
{
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "desktop": "XFCE",
    "distro": {
      "codename": "Illyria",
      "id": "manjaro",
      "like": "arch",
      "version": "18.0.3",
      "version_parts": {
        "build_number": "3",
        "major": "18",
        "minor": "0"
      }
    },
    "lbrynet_version": "0.32.3",
    "lbryschema_version": "0.0.16",
    "os_release": "4.19.24-1-MANJARO",
    "os_system": "Linux",
    "platform": "Linux-4.19.24-1-MANJARO-x86_64-with-arch-Manjaro-Linux",
    "processor": "",
    "python_version": "3.7.1"
  }
}
```

**Comment by tzarebczan** [comment]
Hey Brendon, thanks for the issue. When you switch between Dev and prod modes, the local data directory is different which is why you see 2 different views of the content. There's not much you can do about this.

As far as the downloaded showing unread - we still want this to be unread until you actually go into the file. You still want to know what's new even though it auto downloaded.
