### ISSUE TITLE
Tag-interest Interface

### ISSUE THREAD

**Issue by robvsmith** [lbryio/lbry-desktop#2309]
User Story: As a user of the LBRY app, I should get a chance to select some topics I find interesting, so that my homepage can deliver new content that matches my interests and personality.

AC: Before a user arrives at the Explore page of the LBRY app, the user can select from the tags that are being created to create a custom row (or several) on their homepage. 

The tags can be seen on this dashboard - https://traction.lbry.io/dashboard/23

The custom "channel" should display at the top of the page.

Featured would be beneath it, and then trending, and then the rest of the homepage channels that we control manually. 

The user should be able to skip this step, in which case they get no custom channel. They should still be able to adjust these preferences after the initial setup.

This part of the first run experience should be the final step before getting to the Explore page.

We should consider if we can make everyone who has not done this do this the next time they run the app or they update the app. If we can, that would be good since we have a few thousand people every week and this would be a pretty major feature change.

**Comment by seanyesmunt** [comment]
Made a few minor changes. The only thing I don't really agree with is that this should be the last step in the first run process. 

The goal with the last set of first-run changes was to allow users to actually use the app before we try to get their email. I think this should be separate from that, so we don't try to collect their email _before_ they see any content.

**Comment by kauffj** [comment]
A few comments:

1) Once tags are in blockchain metadata, tags can be pulled directly from chainquery.
2) Adding tags should not be a forced step of first-run and possibly not even a strongly encouraged step. Instead, we should look to create a UX that defaults users into following some tags and encourages them to change or evolve them once they learn more or begin using it. Possibly worth cribbing from Reddit.

**Comment by robvsmith** [comment]
Fair points @seanyesmunt - feel free to work it in how you think best fits, as you do most of the work. I do think if we show them content they care about the first time, it'll be like selling someone using things they enjoy but it could be that it being last is wrong. 

@kauffj - I'm down to allow them to skip it, but not strongly encouraging them makes it a meaningless exercise. People go to all these sites and apps with all this content, and they're always asked to select a few things they would be interested in. We want them to see things they care about. Required, definitely not. We should definitely make it something people are prompted to do though. Could be I'm misreading what "...possibly not even a strongly encouraged step." means though.

**Comment by seanyesmunt** [comment]
@robvsmith An argument could be made that we lose users if we force them to make a choice before seeing any content. Some won't want to give any info to us before they know what the app _is_. If you give them a taste of what it could be, they might want to choose their topics to personalize it.

I have an idea for a layout, I'll do a quick sketch and post it here.

**Comment by seanyesmunt** [comment]
https://spee.ch/4/9D87E701-EEEF-49E4-9E2F-F61E855BC590

**Comment by seanyesmunt** [comment]
Closing in favor of #2329
