### ISSUE TITLE
Enable Enter button to work on all modals with inputs

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2312]
## The Issue
This was recently fixed on the Reward code modal, but should work on all modal where inputs are possible (i.e tip, send/receive, delete?). 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
This should be pretty straight forward. Currently we let the modal components handle the submit/cancel actions. We need to bring the buttons inside of the `form` element.

```
<Modal
  onConfirmed={submitForm}
  type="confirm"
>
  <form>
    ...
  </form>
</Modal>
```

needs to change to

```
<Modal>
  <form onSubmit={submitForm}>
    ...
    <Button type="submit" />
  </form>
</Modal>
```

**Comment by tzarebczan** [comment]
Yep, I meant to link https://github.com/lbryio/lbry-desktop/pull/2279/files#diff-921813afc64507753cab7239e29ef55dR47 as the fix for the Reward code one for reference!
