### ISSUE TITLE
Some MP3s don't stream well, allow download first?

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2314]
## The Issue
Some mp3s (test: lbry://mp3large), when initially played, will only show that only 1:27 is available when it's really 28 minutes long. Not sure if this is an issue with this specific MP3, but other larger ones like lbry://@FeralLogic#e46c575bb4b77ff3f26cd8e85aa2908d76e9972d/six also have a similar issue - it shows the correct length but you can't scrub past a few minutes.

If you refresh the app, it shows the correct time/scrubs normally. Not sure why when leaving the page/coming back this is not the case (does it use the old stream?).  This would be good to test with the new video player as well. In the meantime, just allowing full download before trying to play the mp3. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
Fixed
