### ISSUE TITLE
Titles longer than dont show the entire title

### ISSUE THREAD

**Issue by Blanxs** [lbryio/lbry-desktop#2317]
### You can reproduce by making a publish with a certain length title

1.  2.  3.

### Expected Behavior

Tell us what should happen.
The title should continue below on another line
### Actual Behavior

Tell us what happens instead.
The title gets cut off
### Suggested Solutions

Tell us your suggested solutions if you have any.

I suggest changing it so that the title continues below on another line instead of being cut off.
![test](https://user-images.githubusercontent.com/45955125/54091618-89d2fe00-4358-11e9-8f96-49f407ace191.png)

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
Thanks for the issue @Blanxs 🙂 

This must only be for titles with no spaces in them, they wrap correctly with spaces. We just need to add: `word-break: break-word` to that css style.

**Comment by Blanxs** [comment]
Awesome! Thanks for the quick response 🙂

**Comment by vv181** [comment]
It fixed only on the media title, but for the channel title and channel URL, the longer text still doesn't show / overlay.

**Comment by seanyesmunt** [comment]
I've added `...` to the end of long titles, but for titles that don't have spaces, or for claim previews, we aren't going to show the entire thing if it's past a certain length.
