### ISSUE TITLE
Search doesn't find content with exactly matching title

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-desktop#2318]
Feel free to close this if I've done something silly or misunderstood something.

## The Issue

Sometimes, when I search for something I know the exact title of, the search results cannot find that item (or it appears really low in the ranking).

### Steps to Reproduce

1.  Search for _Psychology of Redemption in Christianity_ (this is just an example, there are others)
2. Observe that content with that exact title (`lbry://jp-DtiRzQMgBDM#461f1b1b421ac2f2198e8a918a90a775978b9931`) is not returned.

### Suggested Solutions

I don't know anything about search, to be honest, but perhaps matches in the title should be prioritized in the results?

## System Configuration

```
App | 0.29.3
Daemon (lbrynet) | 0.32.4
Connected Email | brendonbrewer@hotmail.com Update mailing preferences
Reward Eligible | Yes
Platform | Linux (Linux-4.19.24-1-MANJARO-x86_64-with-arch-Manjaro-Linux)
Installation ID | 5knbgNSAYuYYHFTsHSbX89mMHE7gNRhotpsLto6x8FXUqjTVb6w7ao3RMqCkTdxHRp
```

## Screenshots

That first result looks dodgy at first but I think it's a bald guy's head, hahaha

![image](https://user-images.githubusercontent.com/1578298/54091853-f2b68680-43e9-11e9-9398-c3e4f5b3056c.png)

**Comment by tzarebczan** [comment]
Issue moved to [lbryio/lighthouse #150](https://github.com/lbryio/lighthouse/issues/150) via [**ZenHub**](https://www.zenhub.com/)
