### ISSUE TITLE
Ability to set releaseTime on publish

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2328]
## The Issue
Users will have access to a new release time (publish date/time stamp) attribute for publishing and viewing content.  Also, the NSFW/Mature field is changing to a tag.

On publish side:
Allow setting of releaseTime attribute
Defaulting of releaseTime if not set?
On Edit, default releaseTime to original publish date (allow override?)?

Viewing content:
What's the new default sorting mechanism?
Allow options for last updated vs releasetime?
If releaseTime in future (i.e. premiere / promo), mark accordingly?
Show both releaseTime and last updated on file details?
What to show on file tiles?

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
A basic version of this is working in the app to display nsfw tags. Going to move this out of the sprint until more content has the `releaseTime` field.

**Comment by kauffj** [comment]
I'm moving this to In Progress, but the primary issue I'm interested in addressing is sorting channel pages by `releaseTime`. This ticket encompasses more than that, and so shouldn't be closed when that is solved or this aspect should be split out into a separate ticket.

**Comment by kauffj** [comment]
All that needs to happen to complete this ticket is to add the `releaseTime` attribute to the publish action on create and update. On create, it should match the timestamp of when the user clicked publish. On update, it shouldn't change.

**Comment by tzarebczan** [comment]
This is happening in the background on create (setting to current date), or keeping the original tx / release_time on edit. The next step is to allow it to be changed in advanced.

**Comment by Ruk33** [comment]
Hello I believe this one is fixed:

![image](https://user-images.githubusercontent.com/1719111/106519661-68360f00-64ba-11eb-89c7-e9fc5a3d4224.png)

**Comment by seanyesmunt** [comment]
@Ruk33 That is the current date. Ideally there would be a way to set a future date for your content to be released at.

**Comment by Ruk33** [comment]
Oh thanks @seanyesmunt . I have been working on it. How about something like this?

![image](https://user-images.githubusercontent.com/1719111/106822313-addf0d00-665d-11eb-925b-0d7c1f0316aa.png)

![image](https://user-images.githubusercontent.com/1719111/106822335-ba636580-665d-11eb-81fe-894e3ed07e88.png)

**Comment by Ruk33** [comment]
Hello guys, just wanted to double check if the previous sample was ok to create a pull request?
Thanks.
Regards.

**Comment by Ruk33** [comment]
I just pushed a WIP branch to not lose the progress so far https://github.com/Ruk33/lbry-desktop/tree/2328-allow-to-set-release-date.

**Comment by tzarebczan** [comment]
This looks good so far, thank you! 

- we should not allow anything in the future - so the max date would be whatever is passed as "current date / time" today. 

- For users setting a past date, I wonder if we need to allow a time option as an advanced setting - i.e. someone wants to put multiple publishes in a chronological order for a particular date.  Probably for a later iteration vs in this one. 

- can you make sure edits work correctly and it uses the new date vs grabbing from the claim? Also, it should autopopulate this date from the claim on edit.

**Comment by kauffj** [comment]
Hope you come back to this @Ruk33 :)

**Comment by Ruk33** [comment]
Hello @kauffj , a few days ago I sent an update to https://github.com/lbryio/lbry-desktop/pull/5514. I'm waiting for @seanyesmunt 's feedback :)

![image](https://user-images.githubusercontent.com/1719111/108918771-a8e3fc80-7610-11eb-93a7-9ef99c265f4b.png)

![image](https://user-images.githubusercontent.com/1719111/108918779-abdeed00-7610-11eb-9d97-fa8cb5d998ee.png)

Regards.
