### ISSUE TITLE
Fix automatic dark mode

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2334]
## The Issue
Can't turn on unless light mode is chosen first. Thanks to @lyoshenka for pointing this out! 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by dan1d** [comment]
The checkbox option is available only when the current dark them is not selected, there is no point to set the automatic dark mode if the dark mode is already selected ?
What do you suggest ?
@tzarebczan @lyoshenka

**Comment by tzarebczan** [comment]
Hey @dan1d , welcome back!! I think someone should be able to set that option regardless of the selected theme. If it is selected, it should not allow the theme to be changed.
