### ISSUE TITLE
Open external links in new tab from lbry.tv

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2353]
## The Issue
External hyperlinks should open in a new window (i.e share links, other urls)

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
To be clear, this is just external links, right?

**Comment by tzarebczan** [comment]
Yep, updated !
