### ISSUE TITLE
App freezes when I accidentally drag text from the search bar

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-desktop#2362]
I've been getting app freezes sometimes (Ctrl+R doesn't help), and just figured out a way to reproduce it. See https://spee.ch/6/vokoscreen-2019-03-2008-58-27 for a video of how to reproduce this issue.

My system and LBRY version:

```
App | 0.29.4
-- | --
Daemon (lbrynet) | 0.32.4
Connected Email | brendonbrewer@hotmail.com Update mailing preferences
Reward Eligible | Yes
Platform | Linux (Linux-4.19.28-1-MANJARO-x86_64-with-arch-Manjaro-Linux)
Installation ID | 5knbgNSAYuYYHFTsHSbX89mMHE7gNRhotpsLto6x8FXUqjTVb6w7ao3RMqCkTdxHRp
```

**Comment by tzarebczan** [comment]
Thanks for filing @eggplantbren ! @lyoshenka actually ran into this too, but I was unable to reproduce on any of the OSes (he was using Ubuntu). Per our Discord chat, try running from source and see if this still happens on master (upgraded chrome).

**Comment by eggplantbren** [comment]
Doesn't occur on master. Closing.
