### ISSUE TITLE
Markdown not showing in search results.

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry-desktop#2369]
### Steps to Reproduce

Search for content that uses Markdown in Title/Description. 

### Expected Behavior

Clean formatted text.

### Actual Behavior

Markdown is shown.

## System Configuration

App | 0.29.4
Daemon (lbrynet) | 0.32.4
Windows 10

## Screenshots

![image](https://user-images.githubusercontent.com/29914179/54761608-22615c00-4c3e-11e9-8773-3acd09b5104e.png)

**Comment by btzr-io** [comment]
I think the best thing to do here is to render only text without formatting or styles (clean)
.

**Comment by btzr-io** [comment]
@tzarebczan search items not longer show description, so I think this is now irrelevant.
