### ISSUE TITLE
Fix show page with long links in description

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2378]
## The Issue
See lbry://@MinutePhysics#589276465a23c589801d874f484cc39f307d7ec7/extraterrestrial-cycloids-why-are-they

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
Fixed with https://github.com/lbryio/lbry-desktop/commit/9fadbc96242a68c1f0d09160f1a31f42acc921da
