### ISSUE TITLE
Address size/performance issues w/ web & desktop

### ISSUE THREAD

**Issue by skhameneh** [lbryio/lbry-desktop#2385]

**Comment by tzarebczan** [comment]
Related: https://github.com/lbryio/lbry-desktop/issues/2355

**Comment by skhameneh** [comment]
https://github.com/lbryio/lbry-desktop/pull/2387 is merged

**Comment by skhameneh** [comment]
Will continue working on this, I'd like to see the main bundle brought down to ~1MB.
