### ISSUE TITLE
codeViewer.jsx (Code Viewer and Document Viewer) shows infinite load on some files

### ISSUE THREAD

**Issue by skhameneh** [lbryio/lbry-desktop#2386]
Working on this w/ lazy-loading.

**Comment by tzarebczan** [comment]
Would this fix https://github.com/lbryio/lbry-desktop/issues/2391 ? I'll try it on your branch...

**Comment by tzarebczan** [comment]
Closing, will keep https://github.com/lbryio/lbry-desktop/issues/2391 which has examples of each.
