### ISSUE TITLE
md file not rendered (stuck at processing) - document/code viewer failures

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2391]
## The Issue
See lbry://md or ones on Antimedia channel like lbry://remembering-us-torture-abu-ghraib#c2504455454bbe6c31682ba8e521815c6cdb1c8b

codeviewer: lbry://py#1499b64a686aa1f34dbbe8e1cc84292c4e81379d / lbry://js#80d592b964ec55e7a1e4db85bd449d67e47aed8c

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
Fixed in #2466
