### ISSUE TITLE
Full screen Button Stops Working After Double Click

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry-desktop#2392]
## The Issue

Full screen button stops working after double clicking it. You have to use the keyboard or double click again to get out of it.

### Steps to Reproduce

Double click a video to make full screen. Then try coming out of full screen using the full screen icon in the bottom right.

### Expected Behavior

The icon should make the screen size normal again.

### Actual Behavior.

Does nothing.

## System Configuration

App | 0.31.1
Daemon (lbrynet) | 0.34.0
Windows 10

**Comment by tzarebczan** [comment]
Thanks for filing and vv181 for finding this! Strange that it works fine if you full screen using the button, or exit full screen when double clicking!

**Comment by btzr-io** [comment]
Is this still an issue ?

**Comment by btzr-io** [comment]
I can't recreate this issue in the latest version:
> 

App | 0.32.2
-- | --
Daemon (lbrynet) | 0.37.1

**Comment by btzr-io** [comment]
Also tested with the new player on: https://beta.lbry.tv/

**Comment by btzr-io** [comment]
probably a windows issue ?

**Comment by vv181** [comment]
> 
> 
> probably a windows issue ?

I discovered the bug on Arch. 

Recently I haven't yet upgraded nor tried the latest LBRY app. Will do it if I've some free time.

**Comment by vv181** [comment]
> Is this still an issue ?

App | 0.32.2
Daemon (lbrynet) | 0.37.1
Platform | Linux (Linux-5.1.4-arch1-1-ARCH-x86_64-with-arch)

I can confirm the issues haven't yet fixed.

**Comment by vv181** [comment]
Tested on both Windows and Linux the issue still occurs, except on the https://beta.lbry.tv/ its work as expected.

**Comment by btzr-io** [comment]
@vv181 Thanks for testing this issue, It's probably a bug on electron but new video player should fix this issue :+1:

**Comment by btzr-io** [comment]
Small update on this issue, the old `toggleFullscreen` was wrong implemented and it was requesting fullscreen mode for the container  instead of the video element.

This should be fixed on this branch: https://github.com/lbryio/lbry-desktop/tree/fullscreen
