### ISSUE TITLE
video list is upto 41, when i type 42 in the goto bar and press enter, nothing happens

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-desktop#2394]
## The Issue
video list is upto 41, when i type 42 in the goto bar and press enter, nothing happens, at least we should get a respons help to file a @ceoger report

see this screenshoot to reproduce 

## System Configuration

- LBRY Daemon version: 0.34.0
- LBRY App version: 0.31.1
- LBRY Installation ID:
- Operating system: WINDOWS 10

## Screenshots

![Screenshot_from_2019-03-28_22-34-31](https://user-images.githubusercontent.com/26609573/55179047-40d4d380-51b9-11e9-90ea-fb7d0c24b8ff.png)

**Comment by seanyesmunt** [comment]
Thanks for the issue @ykris45 

Not sure of the best fix. Maybe we can just add a simple error label over the input like we do on the send credits page when you try to send more than you have.

**Comment by tzarebczan** [comment]
pagination is gone for channel pages now.
