### ISSUE TITLE
Media Loading Icon Looks Pixelated

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry-desktop#2396]
## The Issue

The loading icon looks pixelated/grainy when spinning. Seems like the background spills out past it at various points in its rotation.

*This screenshot isn't the best. It's more apparent on other videos.

### Steps to Reproduce

Play streaming content that is waiting to load.

### Expected Behavior

Look more pleasing.

### Actual Behavior

Looks broken.

### Suggested Solutions

Replace with a nicer icon. Maybe skip using black too. Black is never a good colour for good UX. 

## System Configuration

App | 0.31.1
Daemon (lbrynet) | 0.34.0
Win10

## Screenshots
![image](https://user-images.githubusercontent.com/29914179/55215873-ea15db00-5246-11e9-87b8-50b1048ab800.png)

**Comment by tzarebczan** [comment]
I suspect this will change when we implement the new video player. Thanks for creating the issue!

**Comment by seanyesmunt** [comment]
Yep. This is also chromes video player, and we're a few version behind so maybe it's fixed upstream? I wonder if you see it when you drag the video into chrome

**Comment by tzarebczan** [comment]
This was in render media and is replaced by a new spinner in videojs.
