### ISSUE TITLE
Icon needed for app window

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-desktop#2411]
I imagine this is an unimportant feature request, but on the other hand, it should be easy to do. Many programs have an icon associated with them, which my desktop environment (XFCE on Manjaro Linux) shows in the little workspace selector. In the attached screenshot, the Brave browser has its red lion icon, but LBRY (circled in green) has nothing, and ideally it would have the LBRY icon.

![image](https://user-images.githubusercontent.com/1578298/55677499-cc2e3180-593c-11e9-8666-b559da55244c.png)

**Comment by eggplantbren** [comment]
Looks like @abueide has fixed this!

**Comment by alyssaoc** [comment]
closing for 2416
