### ISSUE TITLE
i opened a video with the open.lbry.io link and after, whenever i refresh the app it loads the same link instead of the home page

### ISSUE THREAD

**Issue by ceoger** [lbryio/lbry-desktop#2421]
## The Issue
i opened a video with the open.lbry.io link and after, whenever i refresh the app it loads the same link instead of the home page
### Steps to Reproduce

1.  2.  3.

### Expected Behavior
App should show explore page after refresh

### Actual Behavior

App goes to the link open.lbry.io link video after refresh

### Suggested Solutions

Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version: 0.34.0
- LBRY App version: 0.31.1
- LBRY Installation ID:
- Operating system:

## Anything Else
clearing cache did not help

## Screenshots
https://gyazo.com/07a04da1f318886eb695330434c3a910

**Comment by tzarebczan** [comment]
Thanks for filing this. I was able to reproduce on the current version (opened https://lbry.com/jiggytom without the app running). Will recheck it on master after the urls are fixed there.

**Comment by seanyesmunt** [comment]
Tested that it is working correctly with https://github.com/lbryio/lbry-desktop/pull/2437
