### ISSUE TITLE
File not deleted on drive when checkbox marked

### ISSUE THREAD

**Issue by temrix** [lbryio/lbry-desktop#2422]
## The Issue

"Also delete file from computer" does not delete file.

### Steps to Reproduce

1. Download something.
2. Delete this file
3. Check/uncheck checkbox.
4. Remove

### Expected Behavior

The content should not be deleted from drive if "Also delete this file from my computer" is unchecked and be deleted if it is checked.

### Actual Behavior

The content is not deleted from drive if checked and deleted if not checked. Exactly the opposite happens.

### Suggested Solutions

Either change the string or the behavior if it applies to other instances and is not a configuration bug on my side.

## System Configuration

- LBRY Daemon version: 0.34.0
- LBRY App version: 0.31.1
- LBRY Installation ID:
- Operating system: Debian 9

**Comment by tzarebczan** [comment]
Thanks for opening this issue! Can you send us your log file? https://lbry.com/faq/how-to-find-lbry-log-file

Pretty sure this is working on Windows / Ubuntu, but will give it another shot .

**Comment by tzarebczan** [comment]
Filing under https://github.com/lbryio/lbry/issues/2031. It only happens if you don't restart the sdk..that's why I was able to delete older files. 

Will reach out on Discord to send you some appreciation for the finding!
