### ISSUE TITLE
[Feature] Ability to block individual channels/tags from showing up anywhere

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#2423]
This would be like instagram/twitters block or mute features. One place that blocks them everywhere. I think this would probably go on the settings page? Not sure.

Also, what happens when I manually go to a claim that is by one of these channels? Add a warning message somewhere?

Just creating this to track discussion for now.

**Comment by tzarebczan** [comment]
This would also include tags - I can see them being implemented together.

**Comment by kauffj** [comment]
remaining changes:
- change icon to slash (possibly slash plus circle)
- change text to be word "manage" from settings
- blur images from channels that are blocked

**Comment by jessopb** [comment]
- filter claim search
