### ISSUE TITLE
lbry.tv megaissue

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2426]
## The Issue

- [x] can't unsub from channels.

- [ ] Fix brokens Settings/Rewards page

- [x] https://static/img/placeholder.png and possibly other static images don't load.

- [x] invalid claim characters from browser URL (try: https://beta.lbry.tv/proxy/en-in/ahr0chm6ly9waxjhdgviyxkuy29tlw)
```
Desktop Error: /proxy/en-in/aHR0cHM6Ly9waXJhdGViYXkuY29t

   Error: Invalid claim ID %s.
```

- [x] random desktop error (not yet reproduced)
``` Desktop Error: /

   l@https://piratebay.com/ui.js:1:1532
``` 

- [x] loading chunk failed (not yet reproduced)
```
 Error: Loading chunk 21 failed.
(timeout: https://piratebay.com/vendors~react-feather.js)
   at l (https://piratebay.com/ui.js:1:1523)
   at https://piratebay.com/ui.js:1:1651
```

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
@tzarebczan also splitting this out, we may want to avoid these mega-issue style tickets unless all of the items within are truly minor
