### ISSUE TITLE
OG image fallback to lbry.com image

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2427]
## The Issue
Prior to implementing https://github.com/lbryio/lbry-desktop/issues/2410, fall back to the lbry.com metadata image. Requires https://github.com/lbryio/lbry.com/issues/898 to be completed first. 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
https://spee.ch/3/og
