### ISSUE TITLE
Remove all uses of localStorage

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#2440]
We are using redux-persist for anything that should keep its value between app visits.

We are also manually using localStorage for some values in the settings reducer
https://github.com/lbryio/lbry-desktop/blob/master/src/ui/redux/reducers/settings.js#L5-L48

This is annoying to work with and has caused issues with values stored in localstorage replacing the values that are persisted in redux-persist. We should nuke it, but still keep whatever values users have saved currently.

**Comment by kauffj** [comment]
The only remaining ones need to be there
