### ISSUE TITLE
Comments mega issue

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2442]
## The Issue
In order to ship an app with our initial comments implementation, it should be able to meet the below criteria. Don't worry too much about the styling aspect, we can ask @NetOperatorWibby for assistance when it's ready. @kauffj / @seanyesmunt may want to chime in with a few items as well. 

Open questions:
1) What do we do about moderation of comments? I guess we can just easily delete from the database if something is super problematic. Should we have a report button?

2) Should we allow 1 level of replies? If so, the UI/sdk calls need to be adjusted to support this. 

3) Do we want to show something about how comments are stored, and that they aren't on the blockchain during the initial beta period? This could be very short with a link to a FAQ.

Bugs/suggestions: 

- [x] Have some way to select a channel or create a new one when commenting (anonymous is allowed too). Creator pages are coming, but it may just need to be a simple UI like in the publish screen for now. We may also need a way to default a channel so it doesn't have to be selected each time. 

- [x] Show date/time of comment

- [ ] Show latest X comments, with an option to "Load More"

- [x] Polling in background for new comments? Show a refresh option when new comments available? 

- [x] Refresh comments list after a comment is posted

- [x] Snackbar when a comment has been posted successfully

- [x] Comment list fails on vanity URLs

- [x] Show the channel name with link to channel (with claim id). Currently it shows the claim id, see lbry://how-have-any-stronghold-invaded-anytime#de90b0068c8f2d7a019b06ce000591172891658e

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
I think some of these are bugs, and some are improvements we can make in the future. The goal with comments is to see how (if) people use them. IMO we just release the basic super duper basic version first, then build out features.

1. Why would we need to delete comments? The final version won't have any moderation, other than possibly blocking some from the official app, but they will still be accessible from non-official apps.

2. I don't think we need to get into level 1 replies for the first release. That can be added later.

**Comment by tzarebczan** [comment]
Closing and will open a new issue with latest information.
