### ISSUE TITLE
Incorrected Link on Content.js file

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-desktop#2446]
## The Issue
https://lbry.com/support is invalid URL address, the correct URL address is https://lbry.com/faq/support 

## System Configuration

- LBRY Daemon version: 0.34.0
- LBRY App version: 0.31.1
- LBRY Installation ID: 8K9e1PbwApDnXBbxCBKnYbNLAd2Ytf4LabE8YmDQywbHCp2qxnKfn1cb94zkLbyFxd
- Operating system: WINDOWS 10

## Screenshots

![image](https://user-images.githubusercontent.com/26609573/56850674-e487df80-692f-11e9-8dc0-374403406ab0.png)
![image](https://user-images.githubusercontent.com/26609573/56850676-e81b6680-692f-11e9-8fb1-849129cf6022.png)

**Comment by tzarebczan** [comment]
I'll create an alias on LBRY.com to fix this
