### ISSUE TITLE
redirect "lbry.tv/lbry://name" to "lbry.tv/name"

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#2449]
Right now, if you go to the url `beta.lbry.tv/lbry://name` the app will crash. That isn't a valid url, we should redirect to `beta.lbry.tv/name`

This should happen in the ui server here: https://github.com/lbryio/lbry-desktop/blob/master/src/platforms/web/server.js#L7

**Comment by gagandeepp** [comment]
i am on it

**Comment by gagandeepp** [comment]
I am on it

**Comment by kauffj** [comment]
@gagandeepp you'll need to do this in server.js.

Warning: it's ugly in there :(
