### ISSUE TITLE
H264+AAC video in MP4 container doesn't play on beta.lbry.tv in Firefox

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-desktop#2461]
My video at `lbry://@BrendonBrewer/six` has the most LBRY-friendly codecs and container (h264 video, aac audio, mp4 container) and is web-optimised. It plays fine in the LBRY app and in beta.lbry.tv in Brave/Chromium. However, it fails in Firefox, saying "The media could not be loaded, either because the server or network failed or because the format is not supported".

Not sure how many people this will affect but it could be investigated. Also, apologies if this is the wrong repo for this issue. Feel free to move it if so.

**Comment by tzarebczan** [comment]
Seeing the same, and our new SDK streaming is having a similar issue in FF (keep re-requestingbut works in Chrome also. 

Can you provide the parameters used to generate the file ? I don't think it's web optimized (doesn't load right away in the app), but that should not matter on it's own. I'm reading similar issues on sites like https://www.reddit.com/r/firefox/comments/6t8efe/openload_videos_not_running_the_media_could_not/ / https://www.reddit.com/r/firefox/comments/6jz5gd/videos_showing_media_could_not_be_loaded_error/

**Comment by eggplantbren** [comment]
What parameters do you mean? I'm not sure if I have access to what I did in the past, except that I thought I did this flag with ffmpeg (from the top answer) to get the web optimisation: https://stackoverflow.com/questions/21686191/can-ffmpeg-place-mp4-metainfo-at-the-beginning-of-the-file

![image](https://user-images.githubusercontent.com/1578298/57185304-da13aa00-6f1c-11e9-8ae9-4704a656162c.png)

If other sites are having trouble it sounds like a Firefox bug.

**Comment by tzarebczan** [comment]
It most likely is...but if we knew that web optimizing helps it, we could do that on the sdk side (I found a plug-in for this). Can you try the ffmpeg command and then verify the moov atom is at the front (via atomic parsley of ffprobe)? We can then put a higher priority on that issue.

**Comment by eggplantbren** [comment]
Okay, the atomic parsley test revealed that the `movflags faststart` thing doesn't actually work. I used `qt-faststart` to move the atom instead, and atomic parsley said it was good. Published the new one at `lbry://test#d956840a662a45783af93ddb2f2e5edab5e35581` and it plays on Firefox! Yay!

IMHO, one of the good things about LBRY is that it's a _file marketplace_ and not just a video thing. So if you're going to modify people's files on upload, I'd strongly suggest making it optional (but maybe strongly recommended for video uploads), so people still have the option of uploading the original file as-is.

**Comment by tzarebczan** [comment]
I put a consider soon tag on https://github.com/lbryio/lbry/issues/1988, closing this issue for now. Not sure there's anything we can do about firefox not properly being able to read correct range requests at this time.
