### ISSUE TITLE
Videos don't play on safari

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#2467]
Videos work on mobile for chrome for me, but confirmed by two people that they don't play on safari. No idea what would cause this.

**Comment by tzarebczan** [comment]
Some references: 
https://stackoverflow.com/questions/27712778/video-plays-in-other-browsers-but-not-safari/36299252

https://stackoverflow.com/questions/30199261/why-wont-safari-play-file-without-extension-in-video/51901198#51901198

Also could be related to cloudflare, but I'm seeing the 2 things they mentioned were missing: https://community.cloudflare.com/t/accept-ranges-and-content-length-headers-not-forwarded-by-cloudflare/41445

This is what I'm seeing (sorry for screenshots, can't paste from my VM :P)
![image](https://user-images.githubusercontent.com/8120721/57388124-94a5e580-7185-11e9-813e-bd1849ed163b.png)

![image](https://user-images.githubusercontent.com/8120721/57388146-a1c2d480-7185-11e9-9092-5364d6ac638b.png)

![image](https://user-images.githubusercontent.com/8120721/57388206-b99a5880-7185-11e9-85cf-ed99d3c7f9ae.png)

![image](https://user-images.githubusercontent.com/8120721/57388247-cdde5580-7185-11e9-8044-f937411ae05f.png)

![image](https://user-images.githubusercontent.com/8120721/57388301-e8183380-7185-11e9-8388-e88354e6eec8.png)
![image](https://user-images.githubusercontent.com/8120721/57388358-00884e00-7186-11e9-87fe-c33d6758379e.png)
![image](https://user-images.githubusercontent.com/8120721/57388374-09791f80-7186-11e9-8472-3758856ec7f9.png)
![image](https://user-images.githubusercontent.com/8120721/57388393-139b1e00-7186-11e9-9e74-3dd4fa7e384d.png)
