### ISSUE TITLE
Default subscriptions (stub)

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#2468]
As part of upcoming creator partnerships, new desktop users will be by default subscribed to certain channels.

At a minimum, this will require:
- Sourcing the list (likely replacing featured from `/subscription/suggest`, or possibly a new field)
- Updating subscriptions views
- Explaining the feature
- Possibly disabling notifications until users have completed subscription first run
- Facilitating easy reset and/or mass opt-out

**Comment by m160** [comment]
Is this the place to issue critique?
I think it's a bad idea. Speaking for myself, I know I would find it annoying to have my account automatically be subscribed to channels without my consent.

Is this even something creators want?
Again speaking for myself, I would find it annoying to get a bunch of 'dead subs' on my channel, you know, people who opens the app once and never come back, or maybe creates a new account when coming back. This would make the sub count inaccurate and I'd rather know that all my subscribers have subscribed to me by their own free will. Just my 0.02 LBC.

**Comment by tzarebczan** [comment]
Thanks for the feedback @m160 ! This would be more like the suggested subscriptions we currently have - i.e. you won't get sub emails/notifications for these. We understand the sensitivity of the issue and will approach with caution so as not to force something upon users which we wouldn't expect/want ourselves.
