### ISSUE TITLE
Feature request: Add new support to claim via GUI

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#247]
## The Issue
Currently, need to use the cli to add claim support to a claim. Should be a nice publisher facing feature if you add an option to support your own claims with additional LBC at the click of one or two buttons. Or this could just be part of the larger content management system in the future.  

Also, should have an endpoint created in the app so that it can be called from the outside (such as from an explorer or LBRY app) to support the claim id and amount parameters. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by liamcardenas** [comment]
@kauffj what are your thoughts about exposing the classic claim supports within the app?

**Comment by tzarebczan** [comment]
This was added as an experimental feature. Once we/more users become comfortable with it, we can add by default, or introduce with a mini-tutorial. Or move it into an advanced features area once it's built out.
