### ISSUE TITLE
Improve startup screen

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#2472]
The current startup screen has a lot of stuff that people don't care about. We should add some custom design/animation while the app is starting up.

Sia's is really nice (minus the jumps at the end)
![](https://media.giphy.com/media/QvAuJbGs1vaqw2RyK2/giphy.gif)

**Comment by kauffj** [comment]
@seanyesmunt please comment with relevant files to edit

**Comment by seanyesmunt** [comment]
Relevant files are https://github.com/lbryio/lbry-desktop/blob/master/src/ui/component/splash/view.jsx and https://github.com/lbryio/lbry-desktop/blob/master/src/ui/component/splash/internal/load-screen.jsx

We should just get rid of the `internal/load-screen.jsx` file. It's just markup and can be brought into the top level `splash/view.jsx` component
