### ISSUE TITLE
Add UI for selecting a wallet server

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-desktop#2474]
- UI must display status information about all known wallet servers (esp. description and fee). highlight the fee and explain when/how it will be paid.
- UI should allow setting a custom wallet server domain or ip
- consider distinguishing lbry official servers from others servers
- consider having a preference order for wallet servers instead of a simple selection. i.e. user has an ordered list of wallet servers they want to use. app tries to connect to servers higher up the list as they become available. if no servers from the list are available, connect to any server.
- consider making "connect to any available server" an option. maybe ppl will prefer not to do that (e.g. if you're running your own wallet server and only want to use that one)

**Comment by kauffj** [comment]
Also, or potentially as a separate issue, it needs to be possible to select your wallet server even when the wallet server set in your settings is down or offline.

**Comment by kauffj** [comment]
Per discussion with @lyoshenka, this should be prioritized on Monday.

**Comment by kauffj** [comment]
Please make this a textarea so that input can look like this:
```
server1.com, server2.com
server3.com
server4.com, server5.com, server6.com
```

The SDK only takes a single array, so for now just collapse what was in input into a single array.

**Comment by kauffj** [comment]
@shyba can you create SDK side issue for this if it does not exist and link it here? The idea is that each row is a tier, and the SDK should only switch between wallet servers of the same tier. If all servers in a tier fail, use the next tier.

**Comment by kauffj** [comment]
Desktop side-UI should be radio toggle
- [ ] Use lbry.tv wallet servers
- [ ] Use custom wallet servers

Selecting the second folds out the text area

**Comment by tzarebczan** [comment]
SDK issue to support changes without restart: https://github.com/lbryio/lbry-sdk/issues/2341
