### ISSUE TITLE
main menu doesn't expand, started happening after update

### ISSUE THREAD

**Issue by seadox** [lbryio/lbry-desktop#2481]
main menu doesn't expand, started happening after lbry ask me to update, can't see my wallet settings too, i was trying to backup my wallet. 

![Screenshot_1](https://user-images.githubusercontent.com/38296486/57743826-f35be980-76c6-11e9-9732-60e399d777cf.jpg)

**Comment by seanyesmunt** [comment]
@seadox The menu doesn't expand on purpose. All of the other pages have been combined with other pages or brought up to the main menu. 

Backup directions are on the help page now.
