### ISSUE TITLE
Channel Cover Images crops itself, and it is not movable

### ISSUE THREAD

**Issue by canersevince** [lbryio/lbry-desktop#2482]
![Screenshot_2](https://user-images.githubusercontent.com/38296486/57748022-52762a00-76d8-11e9-8bd1-8478ddb6f466.jpg)

-->

**Comment by tzarebczan** [comment]
Thanks for opening the issue. We plan to tweak the cover image to be similar in dimensions to youtube's. It won't be "movable" but you'll be able to see what it looks like before publishing it to your channel - those enhancements will be coming in the next version or two.

**Comment by tzarebczan** [comment]
Would be covered under https://github.com/lbryio/lbry-desktop/issues/1968
