### ISSUE TITLE
App continues to display tips as unlockable after 'lbrynet support abandon --claim_id=...' withdrew them all

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-desktop#2483]
## The Issue

Described in the title.

### Steps to Reproduce

1. Tip your own content via the command line  (i'm not 100% sure this is actually needed to reproduce the issue, but I had done it)
2. Have someone else tip the content as well
3. Run `lbrynet support abandon --claim_id=...` to unlock all the tips from (1) and (2).

### Expected Behavior

The app should show the tips from others as having been unlocked, because they have been as far as I can tell (`lbrynet resolve` shows no supports).

### Actual Behavior

The little 'unlock tip' icon is still there, but if you try to do it, there will be an error unlocking the tip.

## System Configuration

App | 0.32.1
Daemon (lbrynet) | 0.37.0
Platform | Linux (Linux-5.0.9-2-MANJARO-x86_64-with-arch-Manjaro-Linux)

**Comment by tzarebczan** [comment]
If you refresh or leave/come back, does unlock go away? 

This will get built into the app but right now the app has no idea that it was abandoned without the refresh.

**Comment by seanyesmunt** [comment]
@tzarebczan Do we just need to call `support list` after abandoning?

**Comment by eggplantbren** [comment]
@tzarebczan Yes, restarting the app made the unlock icon go away. :-)

"This will get built into the app but right now the app has no idea that it was abandoned without the refresh."

It does know that an abandon action took place though, because those show up in the list. Stuff is complicated...

**Comment by tzarebczan** [comment]
He's talking about abandoning them from command line and then not allowing the app to refresh this data.  Unless it doesn't go away after refresh, then there may be a bug but I'm pretty sure I tried this and it worked. 

If it was done in app, it would be reflected. We have a separate ticket to allow this (I think, and if not, I'll open one).

**Comment by tzarebczan** [comment]
The new transactions might be there but the apps cache doesn't know the support was removed.
