### ISSUE TITLE
Channel description word cutoff

### ISSUE THREAD

**Issue by m160** [lbryio/lbry-desktop#2485]
## The Issue
Words get cut off in the right edge of description.

### Steps to Reproduce
1. Make channel description 
2. Resize app window
3. Words gets cut in two depending on the window size

### Expected Behavior
The whole word should move to the next line, not just parts of it.

## Screenshots
![Screenshot from 2019-05-16 15-06-45](https://user-images.githubusercontent.com/34570404/57857392-534daf80-77ef-11e9-9eaa-9a7402980d08.png)
![Screenshot from 2019-05-16 15-10-12](https://user-images.githubusercontent.com/34570404/57857399-58126380-77ef-11e9-91df-3e6c5927d7b4.png)

**Comment by seanyesmunt** [comment]
Thanks for opening the issue! I agree this is pretty bad. We should add a max-width to this text too.
