### ISSUE TITLE
Add missing 18n calls and document failures

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#2487]
All user-facing messages need to be wrapped in the `__` calls located in `src/ui/i18n`.

Additionally, some user-facing messages may not be wrappable due to embedded HTML or other issues. When identified, a comment containing the string `i18nfailure` should be added for tracking purposes.

**Comment by jsigwart** [comment]
These are tags Madiator reports are not translating (need to add tags?)
```"Trending": "Trendy",
  "Top": "Top",
  "New": "Nowe",
  "Dark": "Ciemny",
  "Light": "Jasny",
  "dark": "ciemny",
  "light": "jasny",
  "Enter a LBRY URL here or search for videos, music, games and more": "Wprowadź tutaj adres URL LBRY lub wyszukaj filmy wideo, muzykę, gry i wiele więcej",
```
