### ISSUE TITLE
App says "view file" instead of "view channel" when you type a channel name with the full lbry:// prefix

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-desktop#2489]
This should be a simple one so I'm not doing the whole form thing.

When you type `@MH` (say) in the top bar, it says "view channel" next to the suggestion that would just take you to that location, because it's a channel. But when you type it as `lbry://@MH`, it rightly doesn't offer to search, but says "view file". It should say "view channel".

**Comment by seanyesmunt** [comment]
Nice catch. Confirmed this is a bug.
