### ISSUE TITLE
Pick a one character symbol for LBC

### ISSUE THREAD

**Issue by jasperjansz** [lbryio/lbry-desktop#251]
(Edit from @kauffj : This applies to the price indicators as well as the wallet indicator in the top toolbar. Both should use the same symbol or label.)

## The Issue
When I first looked at LBRY, the fees on some content looked like ratings to me. 

### Expected behaviour
For a price, a currency denomination is expected. If it were dollars, you'd write $x, not just x.

### Actual behaviour
There's just a number. To figure out what that number means, you have to try and play the video. Then it says 'You don't have enough LBRY credits to pay for this stream.' And you figure, ah, I guess that's what the number means?

## System Configuration

- LBRY Daemon version: 0.11.0
- LBRY App version: 0.12.0
- LBRY Installation ID: 2tCTvcMLmPUE46D8mHVAVJXUxy8U4HX6xdV7TKQU25jsj3H6G2EnoUmxXEVhdb8hoa
- Operating system: OS X Sierra

**Comment by kauffj** [comment]
Maybe add an L? Maybe repeat the bank icon? Maybe we need a one character symbol for LBC...

**Comment by simonstead** [comment]
Could use a Blackboard Bold L?
# 𝕃
unicode: U+1D543

**Comment by seanyesmunt** [comment]
I think the "Blackboard Bold L" ^ looks cool/informative

**Comment by kauffj** [comment]
I like it, but going to try to do a public ask for ideas, and possibly a poll, before picking anything.

**Comment by zestyr** [comment]
# ⛀ 
White Draughts Man, U+26C0
# Ꝉ 
Latin Capital Letter L with High Stroke, U+A748

![image](https://spee.ch/lbry/4cb345bae48d82257d737020e4ee0630725edec1)

**Comment by marcdeb1** [comment]
U+2C60 with two bars is like a L with a book inside.
	
# Ⱡ

Or U+1EFA is nice, looks like a book too : 
# Ỻ

**Comment by hackrush01** [comment]
[This](https://unicode-table.com/en/2112/) one looks pretty neat U+2112
# &#8466;

Or Maybe if you wanna get creative then [this](https://unicode-table.com/en/0141/) is awesome too. U+0141
# &#321;

If asked to choose, I'd go with the first one.

**Comment by pfranzoni** [comment]
₤
Was used for Italian Lire but now is not used anymore since it went to Euro.

**Comment by pfranzoni** [comment]
Coin symbols are usually coming from ancient languages. Library in both Latin and Greek is translated to Bibliotheca. So also symbols like Ƀ or ƀ should go.

**Comment by pequalsnp** [comment]
:books: believe this is a valid UTF-8 Character

**Comment by pfranzoni** [comment]
This is also nice, but you should think to propose a new char to the Unicode Committee (they say it's taking one and half year usually from submission to distribution)
# **℄** (U+2104)
https://unicode-table.com/en/2104/

**Comment by tzarebczan** [comment]
What about this? 
# ℄ (U+1F17B)
http://graphemica.com/%F0%9F%85%BB

**Comment by tzarebczan** [comment]
What about this with green coloring? 

🅻 (U+1F17B) 

http://graphemica.com/%F0%9F%85%BB

**Comment by IsabelleAlt** [comment]
My contribution to the unicode quest: 
ℓ (U+2113)

**Comment by benhohner** [comment]
Just a note, "Blackboard Bold L" doesn't display on Android.

**Comment by jpinnix** [comment]
I believe Blackboard Bold is the typeface, which may be why it isn't rendering for @benhohner. The actual character is Mathematical Double-Struck Capital L.

𝕃 

@benhohner Check out this page and see if any of them render for you:
https://unicode-table.com/en/1D543/

**Comment by benhohner** [comment]
@jpinnix I tried that page and it doesn't render in-browser,  in Arial,  or in Times New Roman.

**Comment by finer9** [comment]
Agree @jpinnix not right on my Droid

**Comment by sethster82** [comment]
Perhaps some variant of the Greek Lamda? 
<img width="722" alt="screen shot 2017-06-30 at 1 50 49 pm" src="https://user-images.githubusercontent.com/29802891/27747884-3c6fc1ec-5d9b-11e7-864a-b986999d27fa.png">

**Comment by sethster82** [comment]
Or a mashup of the Egyptian Ankh (tie in to the library of Alexandria) and the Yuan Renminbi.

<img width="173" alt="screen shot 2017-06-30 at 1 53 59 pm" src="https://user-images.githubusercontent.com/29802891/27748026-bfdb40e2-5d9b-11e7-9d1a-b18e1a4ef56e.png">

**Comment by sethster82** [comment]
LOL. I think I just realized that it needs to be a symbol that is already a keyboard symbol. Scratch my last suggestions.

**Comment by sethster82** [comment]
Ʌ = Greek Lamda.

That way it's still an "L" but won't get confused with Litecoin.

**Comment by sethster82** [comment]
⥮ 
This symbol is just called "upwards harpoon with barb left beside downwards harpoon with barb right." It could signify the concept of uploading and downloading content which is relevant as viewers can also become hosts of content.

**Comment by sethster82** [comment]
# ⏣
Or the Benzene Ring with Circle, because it visually connects to the idea of a blockchain, and it just looks badass.

**Comment by jpinnix** [comment]
So I was gonna post the lower case lambda, but I think that the upper case version that @sethster82 mentioned is good too.

 λ - Lower case Greek lambda
U+03BB https://unicode-table.com/en/03BB/

λ 457
λ 0.002165

457 λ
0.002165 λ

Λ  - Upper case Greek lambda

 U+039B https://unicode-table.com/en/039B/

Λ 457
Λ 0.002165

457 Λ
0.002165 Λ

**Comment by sethster82** [comment]
# ◳    
Or, white square with upper right quadrant (U+25F3)
I like this one too because it incorporates and L and it's a box which connects the currency to the blockchain as well.

**Comment by sethster82** [comment]
# ⟑
While this is technically "and with a dot," it could be used as a variant on the Greek Lamda.

**Comment by sethster82** [comment]
# ⧍
Triangle with serifs at the bottom. Another potential variant on Lamda.

**Comment by wikidude** [comment]
📖 📖 📖 Books from the LiBraRY

**Comment by madcock** [comment]
This might be a useful way to search for unicode symbols with certain types of shapes:
http://shapecatcher.com/

It lets you draw out what you think you are looking for, and maybe find something that is close.

**Comment by liamcardenas** [comment]
@kauffj where do you want to go from here?

**Comment by etisdew** [comment]
Whatever it is, thats the symbol for lbryium, is this restricted to character codes or would you use an SVG/Image?

**Comment by NetOperatorWibby** [comment]
# `ᜢ`: `U+1742`
![ᜢ](https://user-images.githubusercontent.com/1288356/42897283-874c59c6-8a8d-11e8-8ddc-8d0857520bfb.png)

# `℄`: `U+2104`
![℄](https://user-images.githubusercontent.com/1288356/42897237-59004bfe-8a8d-11e8-935e-5b41d3ffc9bf.png)

**Comment by alyssaoc** [comment]
Issue moved to [lbryio/growth #68](https://github.com/lbryio/growth/issues/68) via [**ZenHub**](https://www.zenhub.com/)
