### ISSUE TITLE
Missing external links on channel page

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry-desktop#2519]
## The issue

`About` section on channel page is missing external links on:
- [x] Description ( see #2506 )
- [x] Website
- [x] Email ( ~Not supported by ExternalLink component~ Fixed on https://github.com/lbryio/lbry-desktop/pull/2520/commits/1edf7e06f91265e85eb2679c223b012dec46f7b5)
> Note: Links are render as plain text

**Comment by tzarebczan** [comment]
Related https://github.com/lbryio/lbry-desktop/issues/2506
