### ISSUE TITLE
[Feature] Add AppImage Support

### ISSUE THREAD

**Issue by ghbjklhv** [lbryio/lbry-desktop#2522]
**Feature**: Add [AppImage](https://www.wikipedia.org/wiki/AppImage) Binary
**Why?** .deb packages aren't universal. [AppImages](https://www.wikipedia.org/wiki/AppImage) work pretty much everywhere.
Plus, then LBRY would be eligible to get listed in [AppImageHub](https://github.com/AppImage/appimage.github.io) and all the app stores that pull data from it.[1](https://github.com/AppImage/appimage.github.io#projects-using-this-data) Another reason is that [AppImages](https://www.wikipedia.org/wiki/AppImage) are portable, .deb files are generally not.

___________________

Want to support this issue? Post a [bounty on it](https://www.bountysource.com/issues/74889650-feature-add-appimage-support)! We accept bounties via [BountySource](https://www.wikipedia.org/wiki/Bountysource).

**Comment by tzarebczan** [comment]
Thanks for opening this issue. Please search through old issues before doing so. 

If you want to see the old app image history. We may revisit later on but the transition from Deb to app image is not fun, and Linux OS support is not native for installers. We would consider snap too. We also have flatpak and aur support, see the readme. 

Also, Linux is our smallest platform, so no need to support more build processes for it. 

https://github.com/lbryio/lbry-desktop/issues/332
