### ISSUE TITLE
Remove auto-download toggle from lbrytv (at least)

### ISSUE THREAD

**Issue by jessopb** [lbryio/lbry-desktop#2526]
In lbrytv, it doesn't make sense to have this toggle.
Should it just be hidden on IS_WEB, or more delicately removed?

**Comment by seanyesmunt** [comment]
This will just be removed (for now at least) on the new subscriptions page

**Comment by seanyesmunt** [comment]
Which is on my discovery branch

**Comment by tzarebczan** [comment]
This has been removed.
