### ISSUE TITLE
Support thumbnail section from video on edits

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2531]
## The Issue
Some users may want to select a thumbnail from their video when editing a claim. Right now they need to reselect the video to do so. If we know the file path of the published file, we should be able to show them the option or tell them to re-select the file. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
@zxawry would you want to come back to this?

**Comment by tzarebczan** [comment]
Completed with https://github.com/lbryio/lbry-desktop/pull/2543
