### ISSUE TITLE
Use canonical URL throughout app

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2534]
## The Issue
Canonical URLs were implemented in v038 of the SDK for both claims and channels. If a claim has a channel, both the channel and claim will have a short ID associated with it. The app can choose to drop the short ID on the claim name (when a channel exists) since the only time the resolution will change is if the publisher themselves creates 2 claims at the same name, and with a higher effective amount. 

Something to keep in mind - canonical url won't be available on local wallet calls like channel / claim list since it requires going out to the wallet server. This may be added back later. Also, when publishing, it's not available right away until it hits a block. 

We'd probably want to use this anywhere we currently use permanent URL. 

Sample: 
```{
  "seven": {
    "address": "baNz2WjmZqjzeDTYWAC7foxQ17a6tSaDKK",
    "amount": "10000.0",
    "canonical_url": "lbry://@BrendonBrewer#3/seven#9",
```

Some applications include:
navigation
Channel pages
file tiles / list
file pages
share page
right click > copy link
https://github.com/lbryio/lbry-desktop/issues/2135
https://github.com/lbryio/lbry-desktop/issues/1393

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
thank you for filing this

**Comment by kauffj** [comment]
We will also need to audit and possibly improve how lbry-redux stores claim state.

E.g. [this object](https://github.com/lbryio/lbry-redux/blob/master/src/redux/reducers/claims.js#L16) is likely to end up with redundant claims if we're not careful.
