### ISSUE TITLE
Consider removing redux > subscription sync

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2535]
## The Issue
Currently, we populate users' subscriptions from redux state into apis mainly to work around a scenario where you turned off analytics and then turned back on - it makes sure the subs get sent to apis. Not sure what other scenario this is helpful in, but it causes issues when switching between dev and prod mode of the app (subs get repopulated from redux after unsubbing on one of other modes). And it may cause issues between multiple installs (i.e. Android/Desktop) where you unsub on Android, but the app will repopulate it. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
Removed in #2477
