### ISSUE TITLE
LBRY tv accounts Megaissue

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2540]
## The Issue

- [x] can't upload ```file-selector.jsx:72 Uncaught TypeError: this.fileInput.current.select is not a function```  / ```stubs.js:7 Uncaught Error: Need to fix this stub```

- [x] auto redeem download rewards (need to rename to stream, or make new rewards?) doesn't work, but that's related to getting proper analytics into new video player. 

- [x] don't pass auth token to lbry-tv if not email verified: https://github.com/lbryio/lbry-desktop/issues/2672

Others:

- [ ] bring back the Settings page with items that make sense for LBRY.tv and make settings persist (will need to sync settings to account)

- [x] fix https://github.com/lbryio/lbry-desktop/issues/2463

Fixed:

- [x] account balance and all other account / wallet related commands will need account id passed. 

- [x] transaction list through local tv api returns no result (maybe tv is trying to do something), but through sdk it does. Balance does show correctly. 

Tell us your suggested solutions if you have any.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
@tzarebczan why this one?

> remove get new address button - web wallet users will have only a single address

We can discuss on meeting today as well

**Comment by kauffj** [comment]
I removed "figure out what lbry.tv will use for streaming/file list. We may need to sync history (https://github.com/lbryio/internal-apis/issues/836)" as it is blocked by paid content support on lbry.tv

**Comment by kauffj** [comment]
everything here should be fixed or split out and associated with the lbry.tv epic
