### ISSUE TITLE
Please provide a 32bit .deb

### ISSUE THREAD

**Issue by traumschule** [lbryio/lbry-desktop#2548]
```
# dpkg -i LBRY_0.33.1.deb
dpkg: error processing archive LBRY_0.33.1.deb (--install):
 package architecture (amd64) does not match system (i386)
Errors were encountered while processing:
 LBRY_0.33.1.deb
```

**Comment by tzarebczan** [comment]
Sorry, we are only supporting 64 bit for the deb file. This may change down the road when we add snap support. 

You can try the flatpak community build to see if it works with 32 bit: https://github.com/lbryio/lbry-desktop#install
