### ISSUE TITLE
Failed publishes somtimes bug the publish tool

### ISSUE THREAD

**Issue by jessopb** [lbryio/lbry-desktop#2551]
## The Issue

Sometimes when publish fails, publish will be stuck in disabled mode due to publish state.

### Steps to Reproduce

Unsure exactly what causes it.

### Expected Behavior

Tell us what should happen.

### Actual Behavior

Tell us what happens instead.

### Suggested Solutions

This shouldn't happen, or a clear publish button should be available to reset it. Until then,
From LBRY App settings, Clear Cache, or
From redux tools, you can dispatch { type: 'CLEAR_PUBLISH' } to fix it.

## System Configuration

App | 0.33.1
-- | --
Daemon (lbrynet) | 0.38.0rc6
Connected Email | none set email
Reward Eligible | No
Platform | Linux (Linux-4.18.0-21-generic-x86_64-with-debian-buster-sid)
Installation ID | AJuPLr18L57rSQYjKCqoU16RY5T5JBf4UfYXNj3m1o8iYe8CYMeMW

**Comment by tzarebczan** [comment]
Many users are running into this. They need to go into settings > clear the cache. 

Can we have a clear button that would do this on the publish page also?

**Comment by kauffj** [comment]
Thanks for filing. There must be a solution to this that is better than a clear publish button. Can't we detect failure, notify user, and call clear ourselves?

**Comment by seanyesmunt** [comment]
We do handle an error from the sdk, but maybe the bug is in our error handling? @tzarebczan Do you know when this happens? Is it a timeout?

**Comment by tzarebczan** [comment]
User recently ran into this one also: https://www.reddit.com/r/lbry/comments/cqx5fi/cant_upload_video/

**Comment by tzarebczan** [comment]
There's now a clear button
