### ISSUE TITLE
Review / revamp authentication and account creation for lbry.tv/desktop

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#2554]
At a minimum, there needs to be an obvious and intuitive way to log out, log in, and create an account.

**Comment by kauffj** [comment]
Add a checkbox or birthdate collection to verify user is over 13 (@finer9 should confirm this all we need from CoPPA perspective)

**Comment by kauffj** [comment]
plus anything in https://github.com/lbryio/lbry-desktop/issues/2608

**Comment by kauffj** [comment]
https://github.com/lbryio/lbry-desktop/issues/2323

**Comment by finer9** [comment]
According to a notice issued by the Federal Trade Commission, an operator has actual knowledge of a user's age if the site or service asks for – and receives – information from the user that allows it to determine the person's age.[29] An example, cited by the FTC, includes an operator who asks for a date of birth on a site's registration page has actual knowledge as defined by COPPA if a user responds with a year that suggests they are under 13. @seanyedmunt

**Comment by finer9** [comment]
While this specifically says bday collection, I am comfortable with a simple checkbox stating they are over 13

**Comment by kauffj** [comment]
Acknowledgement of lbry.com/termsofservice should be added to first-run rather than just publish. 

https://github.com/lbryio/lbry.com/issues/430 is almost done and full terms will be on the website rather than the stub that has been there for a long time.
