### ISSUE TITLE
Suggestions / Features

### ISSUE THREAD

**Issue by leshacat** [lbryio/lbry-desktop#2559]
### **This is only a suggestion issue ticket.**

One main suggestion is it would be nice to have a website to access the content without logging in, or logging in for NSFW content.

**Features suggested:**

1. In all apps & desktop; ability to seek back and forward with arrow keys or swiping
2. In all apps & desktop; ability to adjust video quality
3. In all apps & desktop; ability to select whether each file is temporarily or permanently stored
4. In all apps & desktop; ability to allocate some or unlimited space to disk "cache" or download directory
5. In all apps; ability to download only on wifi
6. In all apps & desktop; ability to thumbs up or down content (without censoring)
7. In all apps & desktop; ability to comment (without censoring) and thumbs up and down on them too
8. In all apps & desktop; make video mark as "read" and disappear from subscriptions feed once fully watched
9. Push more advertising for apps and desktop versions - especially on YouTube

These are unorganized ideas, I will add more ideas as new posts below if I think of more.

### LBRY will dominate YouTube and suck all the users out of it :+1:

**Comment by tzarebczan** [comment]
Thanks for the feedback. Going to close this because many of these are already opened as separate issues either here or on the sdk (github.com/lbryio/lbry). 

Thanks for checking out LBRY and give us some more time to make it awesome!
