### ISSUE TITLE
App hints assume default settings

### ISSUE THREAD

**Issue by Redsandro** [lbryio/lbry-desktop#2561]
## The Issue

As a new user, first thing I always do in new apps is check the settings and disable a bunch of things. So I disabled _"automatically download new content from my subscriptions."_

Some time later, I press "subscribe" for the first time. A message pops up:

_"You've subscribed for the first time. New things will automatically be downloaded from your subscriptions. (...)"_

This confused me. I went back to the settings to see if I forgot to save my preferences. I did not. Now I guess that the help text was not inferred from settings but assumed default settings.

**Please note that this is really not that important**, and you can close this issue without addressing it. I know some people find minor issue reports annoying, while others want the new user experience to be flawless. Either way, I noticed you're logging usage statistics. You could perhaps see if a non-trivial percentage of people actually do this too (go to settings first), and decide if something minor like this is worth your time.

**-instant edit-** as I'm writing this, I realize that maybe the message continued: _"unless you've disabled this setting"_ which I might have missed because of #2560. If not, it might be as simple as adding that message or something like it, e.g.: _"(with default settings)"_

### Steps to reproduce

1. Be a new user
2. Hit "subscribe" for the first time
3. Try to read the green message.

### Expected behaviour
Help message skips the part that is no longer relevant due to changed settings

### Actual behaviour
Help message is ignoring preferences set by user

## System Configuration

- LBRY Daemon version: 0.37.5
- LBRY App version: 0.33.2
- Operating system: Linux

**Comment by tzarebczan** [comment]
Appreciate the issue, much bigger fish to fry in the meantime. Feel free to submit a pr for the text change :)

**Comment by Redsandro** [comment]
After your blessing I went in and searched for the file which is here:
https://github.com/lbryio/lbry-desktop/blob/master/src/ui/modal/modalFirstSubscription/view.jsx

The full text actually reads:

> This app will automatically download new free content from channels you are subscribed to. *You may configure this in Settings or on the Subscriptions page.*

I think this is clear enough. I just missed the (italics mine) part because the message dismissed foo fast.

**Comment by tzarebczan** [comment]
Thank you!!
