### ISSUE TITLE
Torba client error

### ISSUE THREAD

**Issue by theonelucas** [lbryio/lbry-desktop#2562]
Installed lbry app on a fresh install of manjaro, when trying to open the app it doesn't load and instead throws this error on the terminal:

`Daemon: 2019-06-21 10:57:46,438 WARNING  torba.client.basenetwork:115: Timed out while trying to find a server!`

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. Can you please send the entire log file to hello@lbry.com ? 

Let us know where you are located also. Can you also try over vpn?

**Comment by theonelucas** [comment]
I'm located in Ireland. Tried with tor, same error. Sent log via email.
