### ISSUE TITLE
When revoking a support in the app, it says "claim revoke" in the associated dialog box

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-desktop#2564]
I've been using supports a lot lately from the command line, and noticed that when you revoke them in the app, it works fine but all the dialog boxes and things act like you're revoking a claim and not just a support.

I know supports other than tips aren't fully integrated into the app yet, but this should be a simple fix  that will need to happen before they are.

![image](https://user-images.githubusercontent.com/1578298/59969485-0c976600-95a2-11e9-8690-1719c31d4216.png)

![image](https://user-images.githubusercontent.com/1578298/59969500-3f415e80-95a2-11e9-91e6-a037c525e42a.png)

**Comment by tzarebczan** [comment]
It knows you have the claim, so it tries to display that message. We'll need to use the claim type variable to determine this on the utxo instead. Should be an easy fix!

**Comment by eggplantbren** [comment]
Happens when I support other people's claims too.

**Comment by tzarebczan** [comment]
This will be fixed in the next version.
