### ISSUE TITLE
This app installs wherever without asking for a location

### ISSUE THREAD

**Issue by bug-re-port-er** [lbryio/lbry-desktop#2566]
This app installs wherever without asking for a install location or any confirmation if it is to be installed at all = pure malware behaviour.

### Steps to Reproduce

Try to install the app.

### Expected Behavior

It should ask for a install location.

### Actual Behavior

It doesn't.

### Suggested Solutions

It should ask for a install location.

## System Configuration

App | 0.33.2
Daemon (lbrynet) | 0.37.5
Platform | Windows (Windows-10-10.0.17134)

**Comment by tzarebczan** [comment]
Thanks for your feedback, we have this filed under https://github.com/lbryio/lbry-desktop/issues/446
