### ISSUE TITLE
Downloaded file names are not prepended with a date.

### ISSUE THREAD

**Issue by bug-re-port-er** [lbryio/lbry-desktop#2568]
Downloaded file names are not prepended with a date.

### Expected Behavior

They should be.

### Suggested Solutions

Prepend file names with the video release datetime or at worst with the current datetime. 

## System Configuration

App | 0.33.2
Daemon (lbrynet) | 0.37.5
Platform | Windows (Windows-10-10.0.17134)

**Comment by tzarebczan** [comment]
We will not be doing this. File names are preserved as uploaded. 

Please see my other comments in terms of opening new issues.
