### ISSUE TITLE
Roaming vs. Local

### ISSUE THREAD

**Issue by bug-re-port-er** [lbryio/lbry-desktop#2570]
LBRY is keeping wallet in

C:\Users\[...]\AppData\Local\lbry\lbryum

instead of 

C:\Users\[...]\AppData\Roaming\lbry\lbryum

In fact it appears as it’s using Local and Roaming the opposite way it is used in Windows – placing some temp like files in Roaming while putting user vital info in Local. 

### Suggested Solutions

Keep 'user files' like settings and wallets in Roaming and other stuff in Local.

## System Configuration

App | 0.33.2
Daemon (lbrynet) | 0.37.5
Platform | Windows (Windows-10-10.0.17134)

**Comment by tzarebczan** [comment]
You must have an old install, we changed everything to use local. But if you had roaming before, it would use that. The app itself uses roaming for some local cache data, otherwise the SDK uses local.

**Comment by bug-re-port-er** [comment]
I didn't have Roaming before as today was the first time I've installed lbry.

Again keeping user files like settings etc. in Local is bad these kind of files should be placed in Roaming.
