### ISSUE TITLE
Channel not selected on edit after clearing cache

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2578]
## The Issue
@Invariant-Change noticed this one, I was able to repro after clearing cache. I guess it could also happen on first run, but didn't to me.

https://cdn.discordapp.com/attachments/377895389992321064/593648694029451264/anon.mp4

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by jessopb** [comment]
I have a fix for this shortly.
