### ISSUE TITLE
cannot change/remove user from the lbry desktop app

### ISSUE THREAD

**Issue by survivor303** [lbryio/lbry-desktop#2579]
I added second and non verified account to the app, when i was first install it but then i got stuck with it, i cannot change to my default and verified account (email) from the app.

I even trying to uninstall and install the app, more than couple of times but it was stuck on that secondary account of mine and wanted to verify it. I Clear the cache, removed registry entries after uninstalling but no help on that.

Perhaps it does somekind of fingerprint of my system and add that to the first time account?

So how i can totally remove that second account that i can use my verified account?

**Windows 10 with lbry 0.33.2**

**Comment by tzarebczan** [comment]
Thanks for reaching out, please see https://lbry.com/faq/how-to-change-email. We have other issues already filed around this, closing this one for now.
