### ISSUE TITLE
Fully integrate user rewards verification into the app (stub)

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#2580]
For @tzarebczan and @jsigwart's sanity

**Comment by kauffj** [comment]
If anyone has a vision of what precisely should change, please share. Otherwise we can discuss after an upcoming standup or next planning cycle.

**Comment by kauffj** [comment]
https://verify.lbry.io/

**Comment by tzarebczan** [comment]
Sanity? What sanity? :)

Also see https://github.com/lbryio/internal-apis/issues/900 for some rough old specs for additional info.

**Comment by kauffj** [comment]
Not actually done but a lot of other improvements were made (auto-verify, re-vamped display).
