### ISSUE TITLE
Someway to refresh rewards status

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2581]
## The Issue
When we manually verify users, they have to refresh the app to get the new status. The user/me call only happens on app refresh, but some users are confused that closing/reopening the app does not refresh reward status (it doesn't if minimized to tray).  Can we have a refresh button on the rewards page somewhere? 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
Maybe just poll `/user/me` from that page or at least re-call it when navigated to?
