### ISSUE TITLE
Markdown issue: Link does not get formatted correctly

### ISSUE THREAD

**Issue by richardletshacks** [lbryio/lbry-desktop#2582]
### Steps to Reproduce

1. Upload markdown description with hyperlink (Text must have spaces between words)
2. Observer description

### Expected Behavior

Should have been formatted as clickable link

### Actual Behavior

Link wasn't formatted correctly

## System Configuration

- LBRY Daemon version: 0.37.5
- LBRY App version: 0.33.2
- Operating system: Windows 10 x64

## Screenshots

![image](https://user-images.githubusercontent.com/28305462/60304818-cee86380-993a-11e9-96a3-5ec5003587a4.png)

**Comment by tzarebczan** [comment]
Thanks for filing this, sent you some LBC appreciation on Discord.

@btzr-io , think you can take a peek?

**Comment by btzr-io** [comment]
@tzarebczan  that's the default behavior, if you zoom the image you can see is using the wrong syntax
> `[**test**]((https://github.com))`

[**test**]((https://github.com))

When it should be `[**test**](https://github.com)`
[**test**](https://github.com)

**Comment by tzarebczan** [comment]
Thanks!!!
