### ISSUE TITLE
lbry.tv marked as external site

### ISSUE THREAD

**Issue by richardletshacks** [lbryio/lbry-desktop#2583]
### Steps to reproduce
1. Find a description with a lbry.tv hyperlink
2. Click the link

### Expected behavior
You should navigate to the lbry.tv link

### Actual behavior
You'll get a warning that lbry.tv is an external site

## System Configuration

- Browser version: Microsoft Edge (Chromium) Version 77.0.197.1 (Official build) dev (64-bit)
- Operating system: Windows 10 x64

## Screenshots
![image](https://user-images.githubusercontent.com/28305462/60345269-ee25d600-99b8-11e9-924d-1c535f1d39d6.png)

**Comment by seanyesmunt** [comment]
Fixed with #2605
