### ISSUE TITLE
Do not delete channels from `myClaims` list on successful channel edit

### ISSUE THREAD

**Issue by jessopb** [lbryio/lbry-desktop#2589]
### The Issue

Trying to plot a path to correctly updating channel pages while pending and maintain a consistent redux state.

I noticed that claim_list loads myClaims with all user-owned claims:

myClaims: 
0 { name: "@mememe" ...}
1 { name: "randomClaimOfMine" }

However, when publish updates a claim, it resets myClaims to exclude channel claims.
myClaims:
0 { name: "randomClaim" }

### Suggested Solutions

the new state is built with myClaims which uses the selector
`selectMyClaimsWithoutChannels`

including one more selector to get the whole list and using that to build the new list would fix it.

Just not sure what the intended purpose of myClaims is - to include channels or not.

**Comment by seanyesmunt** [comment]
`myClaims` should be all of my claims. Then we can use `selectMyChannelClaims` and `selectMyClaimsWithoutChannels` to select individual types.

I believe this already happens? If it cleared channels from `myClaims` they wouldn't load when you go back to the publish page.

**Comment by jessopb** [comment]
They are indeed removed from MyClaims (mine goes from 0,1,2,3,4 to 0,1,2 on edit) but fetch_claim_list_mine seems to happen every 30 seconds automagically.

**Comment by seanyesmunt** [comment]
👍 That's a bug. Updated the title
