### ISSUE TITLE
Can't unsub from channels that have been abandonded

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2595]
## The Issue
If a channel is abandoned, you can't access the channel page so there's no way to unsubscribe from them.  We should have a dummy page if it's in subscriptions with the unsub button (this would still need to know/pass the claim id, which we would have). 
## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
Is this an issue in the upcoming release? I believe you can do it from the same page you manage your tags on.

**Comment by tzarebczan** [comment]
Both old and new app. Don't think it shows if it can't be resolved, but will confirm locally.

**Comment by tzarebczan** [comment]
More users are running into this now that some people delete their channels by mistake and some youtubers have multiple channels that they clean up.
