### ISSUE TITLE
Moderation of Comments

### ISSUE THREAD

**Issue by m160** [lbryio/lbry-desktop#2598]
## The Issue
Having comments that can not be moderated is a dream come true for trolls. Creators should not have to tolerate slanderous/abusive/degrading/hurtful comments directed at themselves on their own content.

### Expected Behavior
Being able to either disable the comments section, or the ability to moderate the comments section on your own content.

### Actual Behavior
No ability to disable/moderate comments.

### Suggested Solutions
I know that comments can't be fully removed if they go on the blockchain, but it should at least be possible to disable/hide comments on the app side. This is possible on [Steemit](https://steemit.com/introduceyourself/@hannahimsa/why-is-ahimsa-in-my-username-and-why-i-joined-steemit) (scroll to the bottom of the post to see how comments are hidden).

## Anything Else
Personally, I think it's less important for comments to be decentralized/censorship resistant. Everyone already have the ability to publish whatever they want on their own channels, should everyone have the right to spout whatever they want on _other_ people's channels too? It's an open question.

I think the important distinction here is that one is someone doing what they want in their own little space, on their own channel, those who don't like it can simply ignore. The other is someone being able to do whatever they want in _other_ people's space, on other people's channel/content.

My concern is that trolls being able to roam freely on creators content can quickly end up in creators leaving the platform.

**Comment by tzarebczan** [comment]
Thanks for the write up @m160 ! We'll review and prioritize. Most of the work would need to be done from the UI side, but there would be no way to "block" comments on chain / on the database.

**Comment by zxawry** [comment]
Moderating comments on the UI side sounds like a little censorship.
I think if comments are a subset of claims, then users could tip useful comments as well as abusive ones in case the published content really deserves it (as a manner of voting) and the UI could sort them out based on tips.
maybe setting a minimum of fee based on the popularity of the content (total amount of tips and support) to leave comments makes it less viable for trolls to do their annoying job.

**Comment by jessopb** [comment]
For an organization that wishes to avoid setting standards for speech, I think it's very important that we provide tools to the channel page owner to do what they wish with it. I don't see how any market or democracy is necessary for you to kick an obnoxious person out of your house, so I don't think it's very central to censorship.

**Comment by eggplantbren** [comment]
This might be either a bad suggestion or an obvious one, but it seems to me that it would be quite easy to have a special tag such as "comments disabled" which, if added to a claim, causes the (official) app not to display the comment section. This could be added to any new publish similar to how "mature" is a suggested tag with special behaviour.

**Comment by m160** [comment]
The problem is that a creator wouldn't necessarily want to disable the comments as a whole, they'd just not want haters/spammers/etc to have a platform on their content. Some creators would feel forced to disable comments because of a few trolls, when what they really wanted was a comments section without trolls.

I think [Aether](https://github.com/nehbit/aether) has a very interesting solution to not only solve how to keep it fully decentralized, but also the problem of moderation. They even have a up/down voting mechanism figured out. Certainly worth [exploring](https://getaether.net/docs/tech/).

As far as I can tell, LBRY and Aether is a match made in heaven. LBRY got the decentralized content sharing sorted, Aether got the decentralized commenting/voting/moderation sorted. [Burak](https://github.com/nehbit), the developer, also seems like a super nice helpful guy.

I'd love to hear the thoughts of someone more knowledgable than me on this :)

**Comment by tzarebczan** [comment]
I don't think we're going with a different solution if the long term goal is commenting on the blockchain, but maybe @kauffj / @grin / @seanyesmunt have some ideas here. 

In the meantime, I think we should add the ability for channel owners to mark other comments as moderated, store this in the comments database, and use that information to alert other users that comments have been hidden. If they still want to see the comments under a hidden "these may be offensive/etc" section - should users be able to see the moderated comments?

**Comment by kauffj** [comment]
@tzarebczan we're going to continue to build out and refine the centralized version of the system significantly more before moving to decentralized one. 

My inclination is to something close to your second paragraph. Comments would not be permanently deletable by creator but people would have to take extra steps to see them. One reason this is important to support is that comments are one way of fighting abusive / misleading / malicious content.

**Comment by eggplantbren** [comment]
For what it's worth I think the proposal in Tom's second paragraph is good (with users able to see the comments after a warning).

**Comment by kauffj** [comment]
Blocked by 2 SDK issues (visible if you have ZenHub)

**Comment by lrq3000** [comment]
Just a small idea: in France there recently was an online experiment for collaborative legislation proposal platform (le vrai débat), and they faced the same issue. As a balance between freedom of speech and censorship of malevolent comments, what they did is that they first used a flagging and voting system to tag these comments, but the interesting part is that the comments were not deleted, but rather all separated from the main comment box and were still accessible in a "comments bin", which was still accessible to any reader but you needed to actively seek and click this link to read the malevolent comments (the link was quite small, at the very bottom and even separated from the main comment box). Unfortunately the platform is now closed so I can't provide a direct link.

**Comment by kauffj** [comment]
Using #4947
