### ISSUE TITLE
Language selector not working

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-desktop#2603]
## The Issue
when i changes to Polish language and also Bahasa Indonesia Language in app, its not work better as previews version of lbry app 0.34.0rc3, 

### Steps to Reproduce

1.  Click Gear icon on the top of app
2.  Click Setting in the submenu of gear icon
3. head over to Experimental setting and click change language to polish or bahasa indonesia
https://spee.ch/video-embed/a/VID20190703032948 explained video on here
## System Configuration

- LBRY Daemon version: 0.38.0
- LBRY App version: 0.34.0rc4
- LBRY Installation ID: RNfrPR5YTz3sAAev3dgnXzUtdvoZg9Xgtuouav4AH5fgkgQHQfdPN9Cewii1gzXst
- Operating system: Windows 10

**Comment by seanyesmunt** [comment]
@kauffj This appears to only happen in production. Any ideas why it would only work in dev mode?

**Comment by kauffj** [comment]
https://github.com/lbryio/lbry-desktop/commit/13b8643af2c6cf015d3db6eebe74e90838955287 should fix
