### ISSUE TITLE
"Daemon has Exited" error after first time install on MacOS

### ISSUE THREAD

**Issue by george-mcintyre** [lbryio/lbry-desktop#2606]
## The Issue
LBRY hits "Daemon has Exited" error on startup then shuts down after pressing ok to acknowledge error.

### Steps to Reproduce

1. Install LBRY from dmg
2. run LBRY from Applications
3. Error displayed

### Expected Behavior

Expect no error when installing and running for first time

### Actual Behavior

- Error message "Daemon has Exited" 
- Error message detail: "The daemon may have encountered an unexpected error, or another daemon instance is already running.  For more information please visit: 
https://lbry.com/faq/startup-troubleshooting"
- When error dialog is exited by pressing OK then LBRY shuts down

### Suggested Solutions

I suspect that this is due to some incompatibility with some SDKs that may be installed on machine.  If so, suggest better version checking for preinstalled libraries during install.

## System Configuration

Note can't get to the Help page because app crashes.  Also, the daemon seems to have already crashed when the error message is displayed so I don't get anything from the suggested curl command either.
```
curl http://127.0.0.1:5279 --data '{"method":"version"}'
curl: (7) Failed to connect to 127.0.0.1 port 5279: Connection refused
```
- LBRY Daemon version: ???
- LBRY App version: 0.33.2 15.07.06 
- LBRY Installation ID: ???
- Operating system: MacOS Mojave: 10.14.5

## Anything Else
Console output:
```Current system appearance, (HLTB: 2), (SLS: 1
Post-registration system appearance: (HLTB: 2)
NSApp cache appearance:
-NSRequiresAquaSystemAppearance: 1
-appearance: (null)`
-effectiveAppearance: <NSCompositeAppearance: 0x600003feb840
 (
    "<NSAquaAppearance: 0x6000009f9fc0>",
    "<NSSystemAppearance: 0x6000009fa1c0>"
)>
nw_path_close_fd Failed to close guarded necp fd 37 [9: Bad file descriptor]
GVA info: preferred scaler idx 1
UNIX error exception: 17  [repeated 7 times]
skipping upgrade for locked keychain /Users/*****/Library/Keychains/1Password.keychain 
UNIX error exception: 17 
LSExceptions shared instance invalidated for timeout.
LSExceptions shared instance invalidated for timeout.
AggregateDictionary is not supported on this platform
```

Running directly from command line: 
```
/Applications/LBRY.app/Contents/MacOS  ./LBRY
Starting SDK
Daemon: 2019-07-04 15:43:38,498 INFO     lbrynet.extras.daemon.Daemon:402: Starting LBRYNet Daemon

Daemon: 2019-07-04 15:43:38,500 INFO     lbrynet.extras.daemon.Daemon:404: Platform: {
  "processor": "i386",
  "python_version": "3.7.3",
  "platform": "Darwin-18.6.0-x86_64-i386-64bit",
  "os_release": "18.6.0",
  "os_system": "Darwin",
  "lbrynet_version": "0.37.5",
  "torba_version": "0.5.4a0",
  "build": "release"
}

Daemon: 2019-07-04 15:43:39,235 ERROR    lbrynet.extras.daemon.Daemon:422: lbrynet API failed to bind TCP localhost:5279 for listening. Daemon is already running or this port is already in use by another application.

Daemon: 2019-07-04 15:43:39,916 INFO     lbrynet.extras.daemon.Daemon:453: stopped api components

Daemon: 2019-07-04 15:43:39,916 INFO     lbrynet.extras.daemon.Daemon:459: stopped api server

Daemon: 2019-07-04 15:43:39,917 INFO     lbrynet.extras.daemon.Daemon:462: finished shutting down
```
Port Scan with Network Utility:
```
Port Scan has started…

Port Scanning host: 127.0.0.1

	 Open TCP Port: 	22     		ssh
	 Open TCP Port: 	88     		kerberos
	 Open TCP Port: 	445    		microsoft-ds
	 Open TCP Port: 	548    		afpovertcp
	 Open TCP Port: 	3233   		whisker
	 Open TCP Port: 	4380
	 Open TCP Port: 	6263
	 Open TCP Port: 	6942
	 Open TCP Port: 	9421
	 Open TCP Port: 	10191
	 Open TCP Port: 	15292
	 Open TCP Port: 	16231
	 Open TCP Port: 	17500
	 Open TCP Port: 	17600
	 Open TCP Port: 	17603
	 Open TCP Port: 	19421
...
```

**Comment by tzarebczan** [comment]
Sorry to hear about the issue. Please see https://lbry.com/faq/startup-troubleshooting and send the complete log file to hello@lbry.com

Try restarting your PC before trying again/sending the log.

**Comment by narosis** [comment]
it's April 2022 and this error is still occurring why would you close when the situation hasn't been rectified/resolved? Why are you making no effort to fix the error?? why are you being lazy???

**Comment by narosis** [comment]
those troubleshooting instructions don't work and aren't worth a shit by the way!

**Comment by skabmedia** [comment]
Still getting the error on macOS. LBRY completely broken. No entry in lbrynet.log file at all. Time to deinstall?

**Comment by moodyjon** [comment]
See #7280 for more discussion of this.

https://github.com/lbryio/lbry-desktop/issues/7280#issuecomment-974899401

The *current* build workflow uses a `macos-latest` worker which maps to macOS 11 Big Sur.

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-github-hosted-runners
