### ISSUE TITLE
First run messaging / optional introduction

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2608]
## The Issue

- [ ] first run message for new new users - mention trending/customization?  There is currently no messaging on first run. 

- [ ] an optional explanation of what LBRY is / quick walk through of various features. 

- [ ] add email collection to main page? 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
I don't think email collection should be on the main page. 

Any additional/change in message on the home page can happen in the tag customizer area.

**Comment by tzarebczan** [comment]
You want to throw someone right into the trending by tags page without any welcome message or explanation of what LBRY is?

**Comment by seanyesmunt** [comment]
Our previous message talked about dating a centaur, which is basically like no message at all. 

I'm open to adding additional messaging, but I don't think it's a blocker

**Comment by kauffj** [comment]
closing in favor of #2554
