### ISSUE TITLE
"Your first reward" message incorrect

### ISSUE THREAD

**Issue by justFudgnWork** [lbryio/lbry-desktop#2609]
The "Your first reward" message says the wallet is it the top left but it is in the top right.
![image](https://user-images.githubusercontent.com/32168886/60764268-0046f900-a0ca-11e9-9ce6-88d70f65fe5e.png)

Windows, literally downloaded 10 minutes ago

**Comment by tzarebczan** [comment]
Thanks for pointing this out @justFudgnWork ! Can we show you some [appreciation](https://lbry.com/faq/appreciation).

Fixed on master: https://github.com/lbryio/lbry-desktop/blob/master/src/ui/modal/modalFirstReward/view.jsx#L23
