### ISSUE TITLE
Use filtered endpoint to suppress trending/top/new views

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2613]
## The Issue
Spoke to @seanyesmunt about this - currently we have a way to hide inappropriate content on the trending page, but this changes with the new version since it's not longer produced by the API. The API team added a new endpoint, similar to the blocked_list, to help us do this: https://api.lbry.com/file/list_filtered 

Most common use case will be improperly tagged content, non marked NSFW, or content that's inappropriate but not illegal. 

This should hide content from any of the trending/top/new views. It should not block the URL from being accessed directly. We may want to block from search as well. 

I think this will be removed from the desktop app eventually, but we'll need to continue doing it on lbry.tv.

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
Should this only happen on lbry.tv?

**Comment by tzarebczan** [comment]
If someone posts unmarked porn on with a 500K LBC bid, you want all app users to see that?

**Comment by tzarebczan** [comment]
So I think it needs to stay in the app until we have a solution for community tagging / blocking specific claims (even then, just seeing it will be a big deal if the viewers are underage/etc).

**Comment by tzarebczan** [comment]
Thanks @jessopb !!! Completed in https://github.com/lbryio/lbry-desktop/pull/2621
