### ISSUE TITLE
Respond to feedback from discovery release

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#2615]

**Comment by kauffj** [comment]
https://github.com/lbryio/lbry-desktop/issues/2699

**Comment by tzarebczan** [comment]
Others: https://github.com/lbryio/lbry-desktop/issues/2696
https://github.com/lbryio/lbry-desktop/issues/2695
https://github.com/lbryio/lbry-desktop/issues/2682
https://github.com/lbryio/lbry-desktop/issues/2673
https://github.com/lbryio/lbry-desktop/issues/2669
https://github.com/lbryio/lbry-desktop/issues/2659
https://github.com/lbryio/lbry-desktop/issues/2662
https://github.com/lbryio/lbry-desktop/issues/2643
https://github.com/lbryio/lbry-desktop/issues/2650
https://github.com/lbryio/lbry-desktop/issues/2652
https://github.com/lbryio/lbry-desktop/issues/2616
https://github.com/lbryio/lbry-desktop/issues/2598

**Comment by tzarebczan** [comment]
https://github.com/lbryio/lbry-desktop/issues/2709

**Comment by kauffj** [comment]
Above issues were reviewed. Selected ones were marked as In Progress in ZenHub.

Remainder will use typical scheduling process.
