### ISSUE TITLE
Allow users to follow tags/categories

### ISSUE THREAD

**Issue by avashlin** [lbryio/lbry-desktop#262]
## The Issue
- When I open LBRY, there are 4 categories ( Comedy, Trailers and Coming soon, Movies and TV ,The Tumultuous Ten - YOUR CONTENT HERE!,  CS @UCBerkeley)
- These may or may not be topics of interest to a user.
- Having to search to find your interests are a bit annoying at times

### Steps to reproduce
1. Open LBRY
2. Look at the landing page and observe categories

### Expected behaviour
User should be allowed to select high level topics that are interesting to them.

### Actual behaviour
Predefined high level topics are displayed

## System Configuration
![screenshot from 2017-06-20 15-26-07](https://user-images.githubusercontent.com/8122968/27336763-d5b9a3ea-55d0-11e7-9478-a4efcbfb0057.png)

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

## Anything Else

- In a future update, on first login allow users to choose the topics that they would prefer on their landing page
- This will allow for a more customised experience for users.
- It will also provide useful stats to publishers (maybe at a premium) on the topics that have the largest communities
- This can be somewhat dynamic eventually, with some machine learning algorithm suggesting topics based on usage.

**Comment by kauffj** [comment]
This probably won't happen until we add this at a lower level, unless we decided to do it centralized.

**Comment by kauffj** [comment]
This requires https://github.com/lbryio/lbry/issues/744

**Comment by btzr-io** [comment]
Related: https://github.com/lbryio/lbry/issues/744

**Comment by tzarebczan** [comment]
Replaced by https://github.com/lbryio/lbry-desktop/issues/2309
