### ISSUE TITLE
Bug: New tag re-appears

### ISSUE THREAD

**Issue by gsvarma** [lbryio/lbry-desktop#2626]
# The Issue

On click of "Mark all as read" disappears the New tag. After you check someother tab ( example: discover), they re-appear again.

### Steps to Reproduce

1. In subscriptions tab, you notice 2 things marked as 'New'.
![before](https://user-images.githubusercontent.com/17321286/61164215-ea3e9b80-a502-11e9-9d18-737943f11844.png)

2. Click "Mark all as read". 

3. New tag disappears.

![now](https://user-images.githubusercontent.com/17321286/61164217-f1fe4000-a502-11e9-8864-f47a32ce0844.png)

4. Click on any other tab. Example: discover

5. Then you notice it states 2 in brackets for subscriptions. 

6. When you click on the tab, you see New tag reappears.

![after](https://user-images.githubusercontent.com/17321286/61164221-f6c2f400-a502-11e9-873e-b3382f8c2fa1.png)

### Expected Behavior

Just disappear New tag once for all to the user when he/she clicked "Mark all as read".

### Actual Behavior

New tag re-appears in a way not obeying the functionality of "Mark all as read".

## System Configuration

![about](https://user-images.githubusercontent.com/17321286/61164246-165a1c80-a503-11e9-80cc-b353bf0d8030.png)

Thanks! for a great product.

**Comment by tzarebczan** [comment]
We are getting rid of this tag in the next release, closing for now.
