### ISSUE TITLE
Bug: Delete History not working

### ISSUE THREAD

**Issue by gsvarma** [lbryio/lbry-desktop#2628]
# The Issue

Deleting visited links does not remove the media thumbnails in the viewer. At first, when you delete it disappears everything as if the history deleted, but once you click on Library tab, the video thumbnails are right there/ re-appears.

### Steps to Reproduce

1. Click on Library tab.  

2. Notice the recently watched media.

![1](https://user-images.githubusercontent.com/17321286/61164616-8cac4e00-a506-11e9-8c4e-6d893f46d43d.png)

3. Select all the visited media links and delete.

4. Notice the viewer is empty.

![2](https://user-images.githubusercontent.com/17321286/61164623-946bf280-a506-11e9-9b7a-f4a73eb57435.png)

5. Later click on Library tab, the past media thumbnails are shown / re-appear.

![3](https://user-images.githubusercontent.com/17321286/61164626-9afa6a00-a506-11e9-9894-d0b5d7461485.png)

### Expected Behavior

Just empty the library viewer / container when user opts to delete the history. 

### Actual Behavior

The library tab / container shows the past media thumbnails unless they are deleted by clicking on delete icon at the media player one after other.

### Suggested Solutions

A simple 'Delete History' button to clear past media / watch history.

## System Configuration

![about](https://user-images.githubusercontent.com/17321286/61164673-0f350d80-a507-11e9-89bf-3017633d759f.png)

## Anything Else

Thanks! for the great product.

**Comment by tzarebczan** [comment]
Thanks for opening this issue! Can we show you some [appreciation](https://lbry.com/faq/appreciation) 

The history was for the portion on top, not your LBRY downloads. There's no way to mass delete downloads yet. Closing this issue as the history section is going away for the next release.
