### ISSUE TITLE
(Feature Request) Tox Notification option

### ISSUE THREAD

**Issue by danrobi11** [lbryio/lbry-desktop#2634]
Hi
I really think LBRY got good potential
I really like the crypto setup
Decentralized platform, its a must 
My only downside is the centralized email notification 
I would like to send my notification to my decentralized Tox ID Public key
Im trying to move away from the standard centralized email
So a Tox notification option would be awesome
Thanks to all the LBRY Team!
https://en.wikipedia.org/wiki/Tox_%28protocol%29

**Comment by tzarebczan** [comment]
Thanks for opening this issue! I don't think this is something we'll be doing anytime soon, so unless this you wanted to work on the code, we'll be closing it for now. LBRY's goal is to work in the mainstream environment, where a majority users use email and other traditional systems. 

We can explore this option if it proves to be popular down the road.
