### ISSUE TITLE
(Request) "Share Diagnostic Data" Info Link

### ISSUE THREAD

**Issue by danrobi11** [lbryio/lbry-desktop#2635]
Hi
About the "Share Diagnostic Data" option
I cant find any documentation about what info LBRY is collecting
Please add a link in the app under the Share Diagnostic Data option to let the users know what info exactly LBRY is collecting
Thanks!

**Comment by tzarebczan** [comment]
Thanks for opening this issue. Can we show you some [appreciation](https://lbry.com/faq/appreciation).

You can see this at https://lbry.com/privacypolicy 

We should just add a link to https://lbry.com/privacypolicy for now. I'll submit a PR for this later.

**Comment by seanyesmunt** [comment]
We just added this. It will be in the next release
