### ISSUE TITLE
Views when no channels or tags followed

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2643]
## The Issue
When you don't follow any channels and choose the "channels you follow" option, it defaults to all channels. This could be confusing and probably default to the recommended channels page instead? 

Something similar happens for tags, but this is less likely unless someone removes them all. We'd show the tag picker only in that case

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
Show an empty state for when no channels are followed.

This empty state should give two options:
- Show trending for all channels (which then updates the selector at the top)
- Show channel discovery options (which navigates to that area)
