### ISSUE TITLE
Multiple tool tips show, nav results in error sometimes

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2650]
## The Issue
When switching between pages, you may run into something like the below. If you on a tile, sometimes you'll run into: 
```
ui.js:221 TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at Object.a [as observe] (ui.js:18)
    at ui.js:18
    at mo (ui.js:221)
```
![image (4)](https://user-images.githubusercontent.com/8120721/61678359-99802d00-acd0-11e9-9572-ed70efac07b3.png)

Believe Sean is aware of what this is related to. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
@seanyesmunt fixed this in an unrelated PR
