### ISSUE TITLE
Artifacts while scrolling

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2652]
## The Issue
When scrolling in the app, there are artifacts on the side bar, top bar and sometimes in the page itself. This happens when scrolling up and down.  The video doesn't capture it all - you actually see some of the thumbnails/previews in the top bar when it's moving. 

[2019-07-23_17-37-41.zip](https://github.com/lbryio/lbry-desktop/files/3424150/2019-07-23_17-37-41.zip)

See video for demonstration. 
## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
Needs better reproduction to be workable.

**Comment by tzarebczan** [comment]
Not applicable anymore.
