### ISSUE TITLE
Don't clear tags/other settings (light/dark) when clearing cache

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2659]
## The Issue
I understand that the end goal is to save tags in the wallet sync tool,  but we should try to persist them between clearing of cache. This used to work until the recent persist changes.

We also clear out the theme setting and possibly others. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
At a minimum, add a warning until wallet is used to persist information

**Comment by tzarebczan** [comment]
Blocked by https://github.com/lbryio/lbry-sdk/issues/2222, closing for now.
