### ISSUE TITLE
Add infinite scroll and trending options to channel pages and suggest channel page

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2660]
## The Issue
The channel page should use infinite scroll similar to the other main views. We should also add the trending/top/new sorting to channel pages, with the default of new. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
Mobile has this, let's catch up!

**Comment by kauffj** [comment]
Also update this URL to something cleaner: https://lbry.tv/$/following/channels/manage

**Comment by rswinkle** [comment]
I'm glad this is being worked on, I was about to open an issue myself.  It would be useful to have sort by oldest too, especially if you do end up getting rid of pagination and moving only to infinite scroll.  It's more of a big deal on mobile, but having to scroll forever to watch things chronologically would be a pain in some cases.

Just my 2 cents.
