### ISSUE TITLE
Request: Make Top Bar and Scroll Bar on LBRY App matches with dark theme

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-desktop#2663]
## The Issue
Would be nice if top bar and scroll bar matches with dark theme. like discord dark theme for windows, because an user request this features on #ideas-and-feedback LBRY Discord channel. 

### Steps to Reproduce

1. Open LBRY App
2. Change to Dark Theme
3. See top an scroll bar navigation. as my screenshot below
## System Configuration

- LBRY Daemon version: 0.38.3
- LBRY App version: 0.34.0
- LBRY Installation ID: 2JvNoM79dcxZnM634D95WUeHTkjpR7uBWs1vXMpQWABXQgFugtwTxZfpJwoeQsSLVn
- Operating system: Windows (Windows-10-10.0.17763-SP0)

## Screenshots

![Untitled](https://user-images.githubusercontent.com/26609573/61820524-5d3eff00-ae7f-11e9-9272-3e04b9e4f094.png)

**Comment by tzarebczan** [comment]
Great suggestion Chris, thanks!

**Comment by ykris45** [comment]
you welcome Mr Thomass
