### ISSUE TITLE
Translations missing in app

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry-desktop#2664]
The following strings have been translated into Polish but are not working in the app:

- [x] - Trending
- [ ] - Top
- [x] - New
- [ ] - Your email has been successfully verified.
- [ ] - Your Email 
- [ ] - Update mailing preferences
- [ ] - Change
- [ ] - This information is disclosed only to LBRY, Inc. and not to the LBRY network. It is only required to save account information and earn rewards.
- [ ] - 20 LBC for referring a friend! This is only claimable if the invitee has proved humanness. Limited to 10 redemptions.
- [ ] - INVITEE EMAIL
- [ ] - INVITE STATUS
- [ ] - REWARD
- [ ] - Accepted
- [ ] - Not Accepted
- [ ] - Unclaimable
- [ ] - Claimed
- [ ] - TRANSACTION
- [ ] - Claimed Rewards
- [ ] - Reward history is tied to your email. In case of lost or multiple wallets, your balance may differ from the amounts claimed.
- [ ] - New Publish
- [ ] - Your Publishes
- [ ] - Follow
- [ ] - Find Assistance
- [ ] - Email Us
- [ ] - Help Us Out
- [ ] - Currently, there is no automatic backup. If you lose access to these files, you will lose your credits.
- [ ] - Read the App Basics FAQ
- [ ] - View all LBRY FAQs
- [ ] - Tip
- [ ] - Support
- [ ] - Dark
- [ ] - Light

**Comment by kauffj** [comment]
Step 6 of this doc needs to be done https://docs.google.com/document/d/1xhoiakNNpWIocPmkbW_JUGu98cBaYoMMAeGFDrP44LU/edit

And then the result needs to be opened as a PR against lbry-desktop
