### ISSUE TITLE
Page does not restore to top when navigating new tags

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2669]
## The Issue
If you scroll down one of the trending lists and then click a tag, it goes to the tag page but not to the top of it. It may cut off the header and some results. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by jessopb** [comment]
Was not able to reproduce. Instead I only found #2848

**Comment by infinite-persistence** [comment]
Hi, this one still up for grabs?  Was able to reproduce both issues and more.
