### ISSUE TITLE
Don't send auth token if email isn't verified

### ISSUE THREAD

**Issue by jessopb** [lbryio/lbry-desktop#2672]
@sayplastic requested that we only send auth token to lbrytv api if email is verified.

**Comment by tzarebczan** [comment]
Thanks, I actually had this open in a window and didn't hit create! lol

**Comment by jessopb** [comment]
I plan to discuss it with @seanyesmunt when he's back.

**Comment by seanyesmunt** [comment]
I am back

**Comment by sayplastic** [comment]
Right now it doesn't pass token to internal-apis, which breaks authentication altogether.

The idea was to exclude auth token for users with unconfirmed emails from api.lbry.tv requests, everything else should be left intact.

**Comment by seanyesmunt** [comment]
#2716 only adds this new header for lbry.tv calls. It did not change anything related to sending the auth token to internal apis.

We created this https://github.com/lbryio/lbry-desktop/issues/2719 but I have not been able to reproduce, are you still seeing that issue on beta.lbry.tv?

**Comment by sayplastic** [comment]
Strangely I don't see this issue on beta (where accounts are not enabled on the lbrytv API side btw) but I see it on dev.

**Comment by sayplastic** [comment]
Fixed, thanks @seanyesmunt
