### ISSUE TITLE
& breaks up tags, wrong tag shown

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2678]
## The Issue
Thanks to FL Studio Bits on Discord for this one. If you add a tag like `Drum & Bass` and then click on it, you'll end up at `Drum`. Not sure what other characters might behave similarly. 
## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
We should just need to use `encodeURIComponent` when we build the tag link here:
https://github.com/lbryio/lbry-desktop/blob/master/src/ui/component/tag/view.jsx#L18
