### ISSUE TITLE
Persist trending selectors between tags

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2679]
## The Issue
When switching between tags, the selector defaults back to Trending even though you had another option already selected. I think it makes more sense to persist them. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by infinite-persistence** [comment]
I'd like to try this one if it's still wanted.
`Active | Historical | All` in the `Wallet Page` seems like another candidate for persistence?
