### ISSUE TITLE
Bring back headers progress - issues with load animation

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2682]
## The Issue
Tried adding back header loading in https://github.com/lbryio/lbry-desktop/commit/d7e626941fbba1ef237f5b3285f53a51180e3964, but I had issues with the loading animation on Prod mode (dev worked fine). Happens on Linux + Win, didn't try Mac. 

If I removed the animation code, it would work fine. Also, it would work if I maximized the screen or resized it. 

Maybe @NetOperatorWibby has some ideas here. 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
Plus https://github.com/lbryio/lbry-desktop/issues/2666
