### ISSUE TITLE
Update LBRY information on website, Google play, flathub etc 

### ISSUE THREAD

**Issue by danrobi11** [lbryio/lbry-desktop#2688]
Hello
This is the first thing the users should read when they go on LBRY website, Google play, Flathub etc.
  
  "LBRY is a decentralized peer-to-peer protocol for publishing and accessing digital content. It utilizes the LBRY blockchain as a global namespace and database of digital content. Blockchain entries contain searchable content metadata, identities, rights and access rules. LBRY also provides a data network that consists of peers (seeders) uploading and downloading data from other peers, possibly in exchange for payments, as well as a distributed hash table used by peers to discover other peers." Source from: https://github.com/lbryio/lbry-sdk

As it is now, the users have to go through, about and faq to know this. 
This should to be the first thing the users read about LBRY
Thanks!

**Comment by tzarebczan** [comment]
Hey @danrobi11 , thanks for opening this issue and the suggestion. We have another ticket file to improve the first run experience and introduce folks to LBRY already. I don't think the above messaging is what we want to show most folks since it will be way over their heads.
