### ISSUE TITLE
RPC server failed to bind TCP localhost:5279

### ISSUE THREAD

**Issue by jcalfee** [lbryio/lbry-desktop#2692]
The LBRY default port 5278 is available on my computer.  But I'm still getting an RPC error.  I have disabled the ufw (firewall) and I can temporarily bind to this port using another probram..

```bash
$ netstat -a|egrep 5278
$ http-server -p 5278
Starting up http-server, serving ./
Available on:
  http://127.0.0.1:5278
  http://192.168.1.24:5278
  http://10.8.4.6:5278
Hit CTRL-C to stop the server
```

It looks like it can bind this port but errors later when it tries to make RPC connections to that port.  In my http test above I can load that folder using `http://127.0.0.1:5278` so don't think it is blocked after binding.

## The Issue

```bash
$ LBRY 
Fontconfig warning: "/etc/fonts/fonts.conf", line 100: unknown element "blank"
Starting SDK
Sandbox listening on port 5278.
Daemon: 2019-07-29 16:14:25,810 INFO     lbry.extras.daemon.Daemon:406: Starting LBRYNet Daemon

Daemon: 2019-07-29 16:14:25,813 INFO     lbry.extras.daemon.Daemon:408: Platform: {
  "processor": "",
  "python_version": "3.7.1",
  "platform": "Linux-4.9.0-9-amd64-x86_64-with-debian-9.9",
  "os_release": "4.9.0-9-amd64",
  "os_system": "Linux",
  "lbrynet_version": "0.38.5",
  "torba_version": "0.5.7",
  "build": "release",
  "distro": {
    "id": "debian",
    "version": "9",
    "version_parts": {
      "major": "9",
      "minor": "",
      "build_number": ""
    },
    "like": "",
    "codename": "stretch"
  },
  "desktop": "GNOME"
}

Daemon: 2019-07-29 16:14:26,317 ERROR    lbry.extras.daemon.Daemon:418: RPC server failed to bind TCP localhost:5279

Daemon: 2019-07-29 16:14:26,817 INFO     lbry.extras.daemon.Daemon:461: stopped api components

Daemon: 2019-07-29 16:14:26,817 INFO     lbry.extras.daemon.Daemon:467: stopped api server

Daemon: 2019-07-29 16:14:26,817 INFO     lbry.extras.daemon.Daemon:470: finished shutting down

Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

### Steps to Reproduce

`LBRY`

### Expected Behavior

Needs to startup

### Actual Behavior

Gets stuck on logo

## System Configuration

- LBRY Daemon version:
- LBRY App version: v0.34.2
- LBRY Installation ID:
- Operating system: Debian GNU/Linux 9 (stretch)

**Comment by tzarebczan** [comment]
Hey @jcalfee , sorry to hear about the trouble. The 5278 port is for our sanbox mode to support certain apps like @OpenSourceGames. 

The SDK itself binds on 5279 - `RPC server failed to bind TCP localhost:5279`. Can you see if anything is blocking that? Please reference this issue on the SDK side if you think it's related to IPV6: https://github.com/lbryio/lbry-sdk/issues/2234

Shoot us an email at help@lbry.com if you continue to have issues.

**Comment by jcalfee** [comment]
I have a VPN script that disables IPv6.  I have to stop the VPN until I find a work-around.  Unless of course I can find a IPv6 VPN provider (I'm still looking for one of those)..
