### ISSUE TITLE
"New for everyone" often contains thumbnail images with mature content

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-desktop#2695]
Most manual publishers upload a thumbnail image at publication time. The image is published as a separate claim and a spee.ch HTTP URL is used for the thumbnail. However, when publishing mature content, there is no way to say that the associated thumbnail is also mature, which it usually is.

Therefore, someone browsing "new for everyone" could easily access NSFW content if they click on one of these images. The thumbnails don't themselves have thumbnails, so it's not as though they'd see it just while scrolling, but they could easily click out of curiosity about what these nonsensical-looking claims are.

It would be good to have the thumbnails tagged as mature if the main content is, or have some other solution here (such as filtering out all thumbnails or all spee.ch posts from the "new for everyone" list, if it's not too hard to tell which ones they are).

**Comment by tzarebczan** [comment]
Thanks for the issue Brendon! I've just opened this one on the SDK side (https://github.com/lbryio/lbry-sdk/issues/2364) to help with no thumbs in general, but the scope of this issue can be to bring back the Mature content flag on thumbnail uploads.

**Comment by DispatchCommit** [comment]
Partially resolved (in SDK), closed in favor of #3336 / duplicates #3336
