### ISSUE TITLE
Wallet Page Show Links To Files - Show more of claim name

### ISSUE THREAD

**Issue by ghost** [lbryio/lbry-desktop#2701]
## The Issue

I share a lot that starts with the same name at the start, for example a series of videos. If  i look in my wallet i get to see very short names that only tell me what file it was if i click on it. 
- The fees on left don't need much space
- Type of transaction also not
- Identifier also not
So i suggest something like this picture would make the wallet more user friendly.

## System Configuration
- LBRY Daemon version: 0.38.5
- LBRY App version: 0.34.2

## Screenshots
![Suggestion](https://user-images.githubusercontent.com/52878875/62231180-d11f6100-b3c3-11e9-8bee-d1fc96986fa7.jpg)

**Comment by tzarebczan** [comment]
Thanks for opening the issue, sent you some appreciation on Discord!!

**Comment by tzarebczan** [comment]
The claim names are longer, but we don't plan to put file information there.
