### ISSUE TITLE
Improve resumption and navigation to desired content access modes

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#2702]
And come up with a better name for that ^

Some people might want a quick link to "new for channels I follow" or "trending for everyone"
or "trending for ~porn~ science"

Maybe there could be a button somewhere that opens a modal with the ability to add the current option combo to the sidebar.

I think the actual feature won't be difficult, the harder part is figuring out where that button goes and how to add it without causing more confusion

**Comment by tzarebczan** [comment]
Good idea! @m160 wanted a faster way to switch between options vs using dropdowns and I think this would fulfil that.

**Comment by seanyesmunt** [comment]
This could also be the way we add "categories" or whatever those will be called.

For example, maybe there was a button that opened a modal to create a new sidebar link with a tag. There could also be an option to add additional tags to this "category". Then I could create a `sports` "category" with `football, baseball, basketball` tags and that could be shown in a special way.

**Comment by kauffj** [comment]
Each view already has an internal URI state, doesn't it? Couldn't those be used to share/restore state?

(Not that the above idea is bad)

**Comment by seanyesmunt** [comment]
Yeah. It could literally just copy the current url and create a link to it. I think there will still need to be some "create" ui, that allows adding a name to the link at least.

**Comment by m160** [comment]
I think channels you follow should be front and center regardless of the view, so if there's new content from someone you follow, it shows on top of the front page even if you're not on the 'channels I follow' view. When clicking on the content, it gets 'marked read' and it would disappear from the front page, but can still be found in the 'channels I follow' view.

You shouldn't have to go and check 'new' for 'channels you follow' all the time to see if there's new content from channels you follow.

**Comment by seanyesmunt** [comment]
@m160 I really like that idea! I agree users shouldn't have to check for new content. They should just see it.

**Comment by kauffj** [comment]
I thought we got rid of "marked as read", is "new" still retaining that behavior?

**Comment by seanyesmunt** [comment]
I created #2723 to track this conversation since it is out of scope from the original issue

**Comment by tzarebczan** [comment]
Consider adding an option that would open the LBRY app to one of these views.

**Comment by kauffj** [comment]
Ideas discussed:
- Switching to tabs or buttons for trending / top / new
- Moving publishes/channels out of sidebar and into profile area, then using sidebar to differentiate between tags / subs / everything
- Saving state on your homepage selectors
