### ISSUE TITLE
Add message on mature tags page to say content is hidden because of users settings

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#2703]
If I go to the `porn` tag the first time I open the app I will be (hopefully) greeted with 0 porn. This is good for people who don't want to see porn, but bad for people who want that no-good, vile content.

We should show a message at the top saying, `content is hidden on this page because your settings`.

We show this on the search/channel pages

**Comment by max-arias** [comment]
I'd like to give this a shot! 🤚

**Comment by max-arias** [comment]
@seanyesmunt Could you provide a little more context on how to repro this? Every time I seach for porn  I get SFW-related porn content, so I can't implement this.

**Comment by tzarebczan** [comment]
@max-arias sorry for not replying earlier. We have a PR in progress for this already. Maybe try to find another hacktoberfest issue to tackle?
