### ISSUE TITLE
Add infinite scroll to search results / remove limit

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2705]
## The Issue
We allow a setting to choose max search results, but we can't paginate past the limit. We should remove the max setting and add infinite scroll (the search api does support pagination). 

## System Configuration

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by tzarebczan** [comment]
Mobile getting this soon, let's get it into the app!

**Comment by kauffj** [comment]
@tiger5226 what are the odds I could convince you to move lighthouse behind a configurable option of `claim_search` so that we get this for free with no work?

**Comment by kauffj** [comment]
@tiger5226 *cough*

**Comment by tiger5226** [comment]
hmmm I missed this @kauffj. Sorry about that. I was at the bottom of my notifications. It's already live in mobile for a few releases now. Could it be copy pasted by any chance? 

>move lighthouse behind a configurable option of claim_search 

I am not sure I understand what you mean by this brother.

**Comment by tzarebczan** [comment]
this is now live.
