### ISSUE TITLE
markdown formatting incorrect in some tables

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2712]
A user recently created a table in markdown and ran into some display issues:
https://open.lbry.com/Voting#4

He also wanted to put in new lines (line break) in tables - is that possible without html @btzr-io ? 

View on steemit: https://steemit.com/gridcoin/@jringo/the-gridcoin-fireside-10-voting

**Comment by kauffj** [comment]
would make sense to combine this with #2527

**Comment by btzr-io** [comment]
@tzarebczan IDK, have any examples of this?
If you can do it on github then probably :stuck_out_tongue:

**Comment by tzarebczan** [comment]
fixed in https://github.com/lbryio/lbry-desktop/pull/2717

**Comment by tzarebczan** [comment]
Thanks @btzr-io . Shoot me a DM when you're ready for some appreciation :)

As far as the new lines in tables, I think the example in the OP had this also.
