### ISSUE TITLE
Cmd+A does not select all text in any input element

### ISSUE THREAD

**Issue by sayplastic** [lbryio/lbry-desktop#2715]
**Bug**
Cmd+A should select everything typed into the address bar but doesn't.

**System Configuration**

- LBRY App version: 0.34.2.6678
- Operating system: macos

**Additional context**

Possible regression of #104 but I haven't verified on Windows.

**Comment by tzarebczan** [comment]
Works on Windows. The whole text is also selected when you click into the address bar.
