### ISSUE TITLE
Explore Discovery UX improvements (user testing, community feedback)

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#2723]
Created after discussion in https://github.com/lbryio/lbry-desktop/issues/2702

I figured we could have a general ticket to discuss improvements we could make for the discovery process. Any concrete ideas will be broken out into their own issue.

The first step of this is probably to create some new user tests, but we should figure out what questions we want to be answered in those tests. In the past, we have just said something like "search, watch something, and tell us your feedback". This has lead to some good feedback, but a lot of it ends up being something like "It's pretty cool", which is not helpful.

A hastily created list of questions/confusion points:
1. Should we combine channels and tags I follow? (Ideally if there is new content from someone I am subscribed to, I should see that right away when I open the app).
    - Should we default to channels I follow?
    - Possibly https://github.com/lbryio/lbry-desktop/issues/2702 fixes it with a quick link to `new for channels`, but I think it's still nice to show that new content immediately

(I guess that's all I have right now)

**Comment by m160** [comment]
The app should aim for as little friction as possible, right? You should just open it and have everything you're looking for right there without clicking on anything.

I'd say the front page should be occupied with "hot" content (whatever algorithm calculates that) from tags you follow, similar to how the front page of Reddit works. But channels you follow takes priority, so if a channel you follow publishes something new it goes on top. After clicking on it, or marking it as seen in another way (maybe a little x could be next to it) then it disappears from the front page (but is still in the 'channels I follow' section).

That way, when you open the app all the new stuff from your subscriptions are right there and if there are no new stuff from them, then there's still "hot" content to click on.

It would also be cool to have a (#) next to each tag you're following in the sidebar. For instance, if content with the tag 'music' was posted, say four different ones, then the tag would say music(4).

That way it's easy see if something new has been posted to an obscure tag you follow as it might drown in more popular tags. It's also just a neat visual thing to see that things are happening in the app. When you click on the tag, the number is cleared until something new is posted again. There should also be a clear all so you don't have to click into each tag to clear the (#).

**Comment by kauffj** [comment]
Closing this because I think it is not actionable and we just redesigned discovery for the nth time
