### ISSUE TITLE
Streaming remaining issues

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2728]
- [ ] figure out if we should be setting ttfb on non-streambale types (would be nice to differentiate)
- [ ] analytics event not thrown via downloads button

- [x] autoclaiming of featured and download rewards not happening. 

- [ ] Fix pop out player on small screens
- [ ] check file completed + download path - if exists, play audio/video/images from that source instead of streamingurl (otherwise, if someone turns of hosting blobs only, it will redownload blobs instead of playing from the file they have saved)
- [ ] users are confused on how to move around the pop out player...not clear you can drag the bottom part. The old version used to have a top area that was draggable. 
- [x] if you are in popout mode and delete some other file, the player disappears (thx community testing!!!) 

- [x] fix autoplay - it's working on all file types, but we say only media files (audio/video). Should probably work for audio/video/image. 

- [x] streamed files (streaming only mode) show as downloaded on claim preview (have the icon). File page shows the status correctly (not downloaded) - we use makeSelectFileInfoForUri which doesn't filter. Need to add a new selector or filter in FileProperties
 
- [x] fix file deletion - file is not deleted, you get a loading screen.

- [x] if blobs or file are deleted, call get to rebuild the file / downloaded blobs if the file not streamable or if the save file setting is on (or if add to lbry is called). If you delete a file outside of the app, it gets stuck at "loading..." when trying to play it. 

- [x] when you click "add to library" - we're missing the "connecting" status. Right now the download percentage doesn't show until it actually starts downloading.  (in streaming-only mode)

- [x] can't click "add to library" while streaming (in streaming-only mode)

- [x] on failed streams, can't exit popout player / overlapping text: 
![image](https://media.discordapp.net/attachments/377895389992321064/611223396692394014/image0.png?width=700&height=525)

**Comment by kauffj** [comment]
@tzarebczan the popout player issues are in another ticket. Can you split anything remaining here out into another ticket?

**Comment by tzarebczan** [comment]
https://github.com/lbryio/lbry-desktop/issues/2750
https://github.com/lbryio/lbry-desktop/issues/2769
https://github.com/lbryio/lbry-desktop/issues/2768
https://github.com/lbryio/lbry-desktop/issues/2770
