### ISSUE TITLE
Can't open lbry:// urls if they contain a query string

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#2733]
**Bug**
If a lbry:// url contains a query string, the app doesn't open

**To Reproduce**
1. https://open.lbry.com/%40FameFocus%2Fb9%3Fsrc%3Dlbrycast (lbry://@FameFocus/b9?src=something)

**Expected behavior**
The app should ignore query strings when opening

**Comment by tzarebczan** [comment]
@jessopb let us know if you can fix this for the next release, or maybe add a quick hack on the open.lbry.com side to slice anything after the lbry://?  / first ? . https://github.com/lbryio/open.lbry.com/blob/master/web/redirect.html#L170

valid urls: lbry://?rewards, but remove anything after the first ? after lbry://?

**Comment by finer9** [comment]
I am still not seeing traffic to lbry.com flagged as email on the query string.  Just a small amount of source=engage medium=email from the past.  Again, we want source=OURLABEL and medium=email on all email we send

**Comment by tzarebczan** [comment]
We've turned it off for subscriptions and didn't add to weekly email because of this bug.

**Comment by tzarebczan** [comment]
Here's another example with a special url (rewards page): ```
User(648133) Desktop Error: Uncaught error
app version: 0.35.1
sdk version: 0.38.7
page: #/$/rewards&_ga=2.25795901.1075258668.1566457084-298092352.1566234645
Error: URI does not include name.
   at Xe (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:24634)
   at Ze (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:26613)
   at Array.map (<anonymous>)
   at On (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:1:34721)
   at file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:22:59966
   at file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:36:211914
   at resolveUri (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:27:20837)
   at t.a.componentDidMount (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:204:130332)
   at Ho (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:240:82387)
   at Wo (file:///C:/Program%20Files/LBRY/resources/app.asar/ui.js:240:85062)
```

**Comment by tzarebczan** [comment]
This is the format when it comes to open.lbry.com urls from sub emails: https://open.lbry.com/video-games-influence-us-for-better-or%23ef85b2e7e73a200bc378715f13fae01faea08772?utm_source=subscriptions&utm_medium=email

which fails on @jessopb 's branch

**Comment by seanyesmunt** [comment]
Should be fixed now.
