### ISSUE TITLE
Blocking a channel should also block comments signed by that channel

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-desktop#2745]
**Is your feature request related to a problem? Please describe.**
Nasty comments made repeatedly by same person, also people spam-commenting to try to get you to go to their channel.

**Describe the solution you'd like**
When you block a channel, comments signed by that channel should also be filtered out.

**Describe alternatives you've considered**
The full comment moderation system which is being thought about/worked on.

**Comment by seanyesmunt** [comment]
This is a great idea, and I think it would be a good first start to comment moderation. Shouldn't be too hard to do, we can just bring in the list of blocked channels, then for each comment check if it is from a blocked channel. If it is, just hide it.

**Comment by eggplantbren** [comment]
It does seem easy, so good to have that confirmed (and that you like the idea). I was thinking it could also have a place even after moderation is in, because that would be moderation by the channel owner (potentially hiding comments), but there's no guarantee that the channel owner will hide the stuff a viewer might want them to.

**Comment by tzarebczan** [comment]
This should also apply to mature channels  + the mature content setting.  @osilkin98 do you think some of this should happen on the comments API or app side?

**Comment by tzarebczan** [comment]
Will be covered under https://github.com/lbryio/lbry-desktop/issues/2745
