### ISSUE TITLE
Update system downloads version 0.35.0 instead of 0.35.1

### ISSUE THREAD

**Issue by rockerbacon** [lbryio/lbry-desktop#2746]
**Bug**
Instead of downloading the latest .deb package (0.35.1) the client downloads version 0.35.0, making the client complain about needing an update every startup. Help > About confirms version installed is 0.35.0

This happened when updating from 0.34.2, after version 0.35.0 is installed the problem persists

**To Reproduce**
1. Open the client, a message will be displayed saying the installed version is outdated
2. Click on 'Upgrade' and wait for the download to finish
3. Open the folder where the package was installed on a terminal
4. Type the command "ls" without quotes
5. You'll see that the file is named 'LBRY_0.35.0.deb' and after it is installed the client will still claim your version is outdated on startup.

**Expected behavior**
Client should download version 0.35.1

**Screenshots**

**System Configuration**

- LBRY App version: 0.35.0
- LBRY Installation ID: 95xsrmA7V4UWowtdWaKeUTNYdDbbVf3bTLC26vs62kPYNBZdP5K5osb3x8hBSsRYZF
- Operating system: Elementary OS 5.0 Juno (Based on Ubuntu 18.04)

**Comment by tzarebczan** [comment]
It's most likely just a timing issue...try again and it should download the latest now.

**Comment by granitepenguin** [comment]
I'm seeing the same issue.  Still getting 0.35.0.  I downloaded 0.35.1 manually instead
