### ISSUE TITLE
app crash on paid content priced in USD

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2751]
Go to lbry://test-fee-2. LBC seems to work: lbry://test-fee-1

```
ui.js:240 TypeError: Cannot read property 'cost' of undefined
    at ui.js:16
    at ui.js:22
    at ui.js:36
    at play (ui.js:204)
    at e (ui.js:204)
    at Object (ui.js:204)
    at ho (ui.js:240)
    at ui.js:240
    at Vo (ui.js:240)
    at $o (ui.js:240)
```

**Comment by seanyesmunt** [comment]
This only happened for autoplay when navigating directly to files. It was trying to play the file as soon as possible, even if the cost info wasn't fetched. Fixed in next release
