### ISSUE TITLE
500 pages and error handling for lbry.tv

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#2755]

**Comment by kauffj** [comment]
There are two things to handle for errors:

- When an error happens client-side in React that cannot be recovered from, does the app end up on an error page and not result in broken behavior?
- When an error happens server-side (server.js), show a simple HTML page indicating as such.

**Comment by kauffj** [comment]
@seanyesmunt this should also largely fall out of web server architecture changes.

**Comment by seanyesmunt** [comment]
Closing in favor of #3178
