### ISSUE TITLE
Translation Text on small screen does not have space between FAQ Link and text

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-desktop#2761]
**Bug**
Translation Text on small screen does not have space between FAQ Link and text see a screenshot below

**To Reproduce**
1. Go to 'settings'
2. Click on 'polish or indonesian translation on experimental setting'
3. stay to experimental setting  'see text on above in section menu enable claim support on indonesian or polish translation'
4. See hyperlinks it need more space for it to make it perfect

**Expected behavior**

**Screenshots**

**System Configuration**

- LBRY Daemon version: 0.39.1
- LBRY App version: 0.35.2-rc.1
- LBRY Installation ID: 2JvNoM79dcxZnM634D95WUeHTkjpR7uBWs1vXMpQWABXQgFugtwTxZfpJwoeQsSLVn
- Operating system: Windows 10

**Additional context**
![image](https://user-images.githubusercontent.com/26609573/63364771-749ada80-c3a0-11e9-9364-4a4b489f6a17.png)

**Comment by kauffj** [comment]
The root of this issue is https://github.com/lbryio/lbry-desktop/issues/2555, closing as a duplicate

(but this will be fixed soon, thanks for pointing it out)
