### ISSUE TITLE
use local file for streaming if completed

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2769]
If a file is completed (which means it exists on the file system), stream from the file vs blobs.  The SDK should support this, but it's not a current priority: https://github.com/lbryio/lbry-sdk/issues/2090

most common case: If a user has blob downloads turned off but has the file, it will re-stream from blobs. Or if a user is not longer connected to the internet, can't stream from blobs currently. 

When we tried this previously, the page would re-render when the file completed. Android has a similar issue filed, so this may be a fix in redux, but I'm not sure.

**Comment by kauffj** [comment]
To me it just makes sense for the SDK to provide a different streaming URL for this case.

**Comment by tzarebczan** [comment]
We already have the download path which the video/image viewer can read from directly. I do think the SDK should support this, but it should be easy enough in-app as well.

**Comment by kauffj** [comment]
Letting the SDK fix this
