### ISSUE TITLE
error opening certain files with special characters in name

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2777]
See lbry://144BlackestNightby01GreenLantern43Prologuecbz#b

There may be other views/characters affected. 

error in console: ```vendors~comicBookViewer.js:1 Can't load archive!
file:///C:/Users/thoma/Downloads/144%20Blackest%20Night%20by%2001%20Green%20Lantern%20 net::ERR_FILE_NOT_FOUND
vendors~comicBookViewer.js:1 Request failed TypeError: Failed to fetch```

**Comment by btzr-io** [comment]
>  lbry://144BlackestNightby01GreenLantern43Prologuecbz#b

I cant open this archive on my pc either, do  you have another example?

**Comment by btzr-io** [comment]
https://github.com/btzr-io/Villain/blob/ece4aecfce2c967c19ba1a7cf580cb9299c1a0cd/src/lib/utils.js#L2-L4

This is the new regex for validation of the files names, it should take care of this in most cases

**Comment by btzr-io** [comment]
Is this still an issue ?

**Comment by btzr-io** [comment]
I found the cause of this bug, we can't use the protocol: `file://` with special characters because is interpreted as an actual `url`.

Creating an stream for the file fixes the issue.
