### ISSUE TITLE
Thumbnail for LBRY link not showing in description if original claim has a channel

### ISSUE THREAD

**Issue by Blanxs** [lbryio/lbry-desktop#2782]
**Bug**

**To Reproduce**
1. Paste LBRY link in a LBRY claim description. Claim for link needs to have a channel
2. See results

**Expected behavior**
1. Should show thumbnail

**Screenshots**
https://i.imgur.com/0V6kaq1.png

**System Configuration**

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Additional context**

**Comment by tzarebczan** [comment]
This should work now if the thumbnails worked, at least in comments. In descriptions, we've disabled the lbry links.
