### ISSUE TITLE
Infinite scrolling should activate at end of listed claims, not subscription list

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-desktop#2789]
This has been annoying me for a while because I have a long subscription list. Infinite scrolling shouldn't have anything to do with the subscription list. See attached video, I have to go to the end of the subscriptions for it to activate. After that it works well.

https://beta.lbry.tv/vokoscreen-2019-08-26_08-54-04/e
demonstrates the issue.

**Comment by jessopb** [comment]
This is "fixed" but left to do on it is to programatically detect heights rather than rely on a magic 100px.

**Comment by kauffj** [comment]
@jessopb feel free to ship it with the fixed height if it's blocked.

**Comment by jessopb** [comment]
Using #3175 for remaining refactor work.

**Comment by tzarebczan** [comment]
This bug seems to be back for me on the latest release + lbry.tv. I do have a long list that stretches past scrolling of first page of claim search. Maybe something with electron or other upgraded dependencies broke it?
