### ISSUE TITLE
Clicking enter in tag input (without typing) adds blank tag

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2798]
Thanks to MH for spotting this one. 

If you are in the customize/publish page that has the inputs for tag search and don't type anything, clicking enter adds a blank tag.

**Comment by zxawry** [comment]
a blank tag is also added if you type spaces only (unsure if people would want to follow space only tags) and if you add a tag with preceding spaces it escapes the duplicate check as well as being added into tags.

![](https://spee.ch/d/104ced03-dd22-4be9-9ea2-6c2eb253f7a7.png)

maybe input should be trimmed and checked for zero length before being added.
