### ISSUE TITLE
don't show direct URL if it's not valid

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2799]
use isurlvalid to check if it's valid before suggesting. We don't allow spaces at the moment. 

**@kauffj ninja edit attack**: when working on this, please just strip out the invalid characters and show that URL rather than hiding the resolve result

![image](https://user-images.githubusercontent.com/8120721/63794246-8fed7480-c8cf-11e9-9e39-1ce0d476cc98.png)

**Comment by tzarebczan** [comment]
another example: 
![image](https://user-images.githubusercontent.com/8120721/63961607-24d2a800-ca5f-11e9-9b72-7820990d82ad.png)

**Comment by kauffj** [comment]
^ Also get the 0 publishes off of there :stuck_out_tongue:

**Comment by jessopb** [comment]
The bug is no longer a bug, unable to repro.
0 publishes has been gone since sean killed it as well.
https://github.com/lbryio/lbry-desktop/blob/6ad31a3ce9e8ae3779b5cf360935b873c712b7c7/ui/page/search/view.jsx#L42

The added feature to take the query and fix it for them would be a new feature.

**Comment by tzarebczan** [comment]
Kind of related, but something invalid like below still tries to resolve.  This would be a good candidate for stripping using our regex url (similar how we do for files on publish, but replace with blank?)

![image](https://user-images.githubusercontent.com/8120721/69435804-406fe680-0d0e-11ea-8990-5b0e437ed127.png)
