### ISSUE TITLE
Deletion of own comments

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2807]
The SDK now supports comment deletion via the comment abandon api (https://lbry.tech/api/sdk#comment_abandon)

We should show a delete button next to your own comments. This is only possible for comments signed with a claim with the current solution (that will change once we go to the blockchain version).

**Comment by kcseb** [comment]
You can finally edit and delete your own comments. Surely this should be closed?

**Comment by tzarebczan** [comment]
Thx!
