### ISSUE TITLE
Fix og:image

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry-desktop#2824]
https://developers.facebook.com/tools/debug/sharing/?q=beta.lbry.tv
http://www.opengraphtester.com/test/

**Current tag:** ```<meta property="og:image" content="/og.png" />```

**I think this should be:** ```<meta property="og:image" content="https://beta.lbry.tv/og.png" />```

Reading the OG spec, it appears this might work as well: ```<meta property="og:image:secure_url" content="https://beta.lbry.tv/og.png" />```

**Comment by tzarebczan** [comment]
@jsigwart can you check this out again - we recently enabled the actual channel/claim OG images to show.

**Comment by jsigwart** [comment]
Much better, still not working on Twitter yet. Facebook has a couple warnings that should be fixed:

Missing Properties
The following required properties are missing: og:title, fb:app_id

Facebook debugger here (I included sample media): https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fbeta.lbry.tv%2F%40FreeYourMindArt%3Ae%2F06Phoenix%3A9

**Comment by tzarebczan** [comment]
Closing for https://github.com/lbryio/lbry-desktop/issues/3176
