### ISSUE TITLE
Interactive content no longer works

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry-desktop#2827]
Interactive content now says "Sorry, we can't preview this file."

Interactive content samples that worked in the previous released version:
lbry://16ways#7
lbry://@OpenSourceGames#e/2048#4

![Screen Shot 2019-08-30 at 8.12.42 PM.png](https://images.zenhubusercontent.com/5a7c9e5a4b5806bc2bc63025/c53b00a1-3388-4f0a-b6ad-da88a8951cba)

Version 0.35.2 (0.35.2.7092)
Mac System 10.14.6 Mojave

**Comment by seanyesmunt** [comment]
Sorry about this @jsigwart 

Fixed in https://github.com/lbryio/lbry-redux/pull/194
