### ISSUE TITLE
channel not re-selected on edit, related to capitalization

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2828]
channel won't be reselected if it has capitals in it - somewhere we normalize the channel name.

I created a test with @Test-1 and @test-1, and when editing a claim signed by @Test-1, it selects @test-1. 

This channel is @MyLBRYChannel:

![image (14)](https://user-images.githubusercontent.com/8120721/64065076-dd6f2780-cbd6-11e9-9a0e-473fde2a0ed9.png)

**Comment by seanyesmunt** [comment]
Fixed in my branch
