### ISSUE TITLE
HTML and SVG files not working in app 0.35.2

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-desktop#2830]
These used to work and are awesome, so I made an issue because I hope it comes back soon. My system info:

```
App | 0.35.2
-- | --
Daemon (lbrynet) | 0.39.3
Connected Email | brendonbrewer@hotmail.com Update mailing preferences
Reward Eligible | Yes
Platform | Linux (Linux-5.2.8-1-MANJARO-x86_64-with-arch-Manjaro-Linux)
Installation ID | 9LVZLpeTTc7PSoFxnbChuqaM7TYmbh4Ke7UR5UUfJeswaVqjQYTSzEvzwYZFgE8Ub
```

**Comment by tzarebczan** [comment]
What content type of the svg files? 

Md work...not sure why html don't.

**Comment by eggplantbren** [comment]
What does content type mean?
The SVG files and websites on my channel are an example. They worked yesterday in 0.35.1

**Comment by tzarebczan** [comment]
You'll see the content type on the file page details.

**Comment by eggplantbren** [comment]
Content-Type: image/svg+xml

**Comment by eggplantbren** [comment]
SVGs are randomly working again now (only change I know of is that I'm running daemon 0.39.3 but I don't see how that would affect it). HTML is too, but .lbry isn't.

**Comment by tzarebczan** [comment]
What do you mean by randomly? Can you send me one that doesn't work? Closing this issue for now - .lbry was fixed in master, but not released yet. We'll get a patch out tomorrow/Wednesday.

**Comment by eggplantbren** [comment]
I just meant that I have no idea why they weren't working the other day and were again yesterday. Glad .lbry will be fixed. Thanks for closing

**Comment by tzarebczan** [comment]
Can confirm this SVG says "cannot preview this file" in 0.35.2, but works in 0.35.1: lbry://@mime#6/svg#5

**Comment by eggplantbren** [comment]
I can't preview that one but I can preview this one: lbry://@BrendonBrewer#3/claims#0

**Comment by tzarebczan** [comment]
It works in streaming only mode, but not if save files are on. In this case, it tries to save the file but never sends it to the browser.

**Comment by seanyesmunt** [comment]
Fixed with my changges
