### ISSUE TITLE
Add provision for adding multiple tags by using commas

### ISSUE THREAD

**Issue by toktoakhil** [lbryio/lbry-desktop#2833]
**Is your feature request related to a problem? Please describe.**
There is no option for adding multiple tags at once 

**Describe the solution you'd like**
Add option for adding multiple tags using comma separated
![Capture](https://user-images.githubusercontent.com/11274633/64081367-80ca5480-cd1d-11e9-9b8b-cbff205d41fa.PNG)
 option

**Describe alternatives you've considered**

**Additional context**

**Comment by tzarebczan** [comment]
I like the suggestion, thanks @toktoakhil !!!

**Comment by toktoakhil** [comment]
My pleasure

**Comment by pranabs1ngh** [comment]
Hey, can this issue be assigned to me ?

**Comment by tzarebczan** [comment]
She's all yours! Thanks for taking a stab at it

**Comment by pranabs1ngh** [comment]
hey, is there a repo map to check, where all the components are used? If not, I only want to know, exactly where is the TagSelect component used.

**Comment by seanyesmunt** [comment]
Not really. You can just search for it though
https://github.com/lbryio/lbry-desktop/search?q=%3CTagsSelect&unscoped_q=%3CTagsSelect

This has made me realize we are inconsistent with our naming. If you are up to it, could you also change these to use the same name?

**Comment by pranabs1ngh** [comment]
Okay, I will change them !!

**Comment by pranabs1ngh** [comment]
Everything done. I'm trying to commit the changes to a new branch, its showing some error:

husky > pre-commit hook failed (add --no-verify to bypass)

Should I commit, without verifying?

**Comment by seanyesmunt** [comment]
That means there are Flow errors or lint errors. There should be some explanation of the error(s) if you scroll up in your terminal.

**Comment by pranabs1ngh** [comment]
[2019-10-09 01:53:48.372] Building package heap
[2019-10-09 01:53:48.517] Loading libraries
[2019-10-09 01:53:51.361] Resolving dependencies
[2019-10-09 01:54:11.380] Failed to load recheck stats from "C:\\Users\\pks\\AppData\\Local\\Temp\\flow\\CzCzBUserszBpkszBDocumentszBHacktoberzBlbry-desktop.recheck_stats". Reason: "File doesn't exist"
[2019-10-09 01:54:11.654] to_merge: Focused: 4, Dependents: 0, Dependencies: 6
[2019-10-09 01:54:11.654] unchanged_checked: Focused: 0, Dependents: 0, Dependencies: 0
[2019-10-09 01:54:11.654] Calculating dependencies
[2019-10-09 01:54:11.654] Merging
[2019-10-09 01:54:12.657] Merge skipped 0 of 10 modules
[2019-10-09 01:54:12.663] Done
[2019-10-09 01:54:12.663] Checked set: Focused: 4, Dependents: 0, Dependencies: 6

husky > pre-commit hook failed (add --no-verify to bypass)

**Comment by pranabs1ngh** [comment]
Its showing, that the recheck stats doesn't exist, is it that, or I missed something?

**Comment by seanyesmunt** [comment]
Is there anything above that message?

Maybe try running `yarn` before commiting?

**Comment by pranabs1ngh** [comment]
`ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\es7.object.get-own-property-descriptors.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 262 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\es7.object.lookup-getter.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 262 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\es7.object.lookup-setter.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 265 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\es7.reflect.define-metadata.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 265 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\es7.reflect.delete-metadata.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 267 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\es7.reflect.get-metadata-keys.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 262 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\es7.reflect.get-metadata.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 271 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\es7.reflect.get-own-metadata-keys.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 266 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\es7.reflect.get-own-metadata.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 262 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\es7.reflect.has-metadata.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 266 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\es7.reflect.has-own-metadata.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 263 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\es7.symbol.async-iterator.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 262 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\library\es6.date.to-json.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 267 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\library\es6.date.to-primitive.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 264 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\library\es6.date.to-string.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 263 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\library\es6.function.name.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 268 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\library\es6.number.constructor.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 266 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\library\es6.object.to-string.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 268 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\library\es6.regexp.constructor.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 262 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\library\es6.regexp.flags.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 262 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\library\es6.regexp.match.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 264 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\library\es6.regexp.replace.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 263 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\library\es6.regexp.search.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 262 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\library\es6.regexp.split.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 266 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\library\es6.regexp.to-string.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 262 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\library\web.dom.iterable.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 265 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\library\_add-to-unscopables.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 264 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\_array-species-constructor.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 261 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\core-js\modules\_new-promise-capability.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 267 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\source-map-support\browser-source-map-support.js
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 279 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\lib\__tests__\fixtures\dance_yorokobi_mai_man.bmp
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 283 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\lib\__tests__\fixtures\dance_yorokobi_mai_man.bmp.zst
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 281 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\lib\__tests__\fixtures\dance_yorokobi_mai_woman.bmp
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 285 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\lib\__tests__\fixtures\dance_yorokobi_mai_woman.bmp.zst
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 262 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\lib\__tests__\fixtures\lorem.txt
On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 266 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\example
ode_modules\zstd-codec\lib\__tests__\fixtures\lorem.txt.zst`

above that, something like this is repeated.
already ran yarn.

**Comment by seanyesmunt** [comment]
Hm, I'm not sure what this is. You can just use `--no-verify` and i'll check it out on my computer

**Comment by pranabs1ngh** [comment]
`On Windows, paths must be less than 248 characters for directories and 260 characters for files. This path has 277 characters. Skipping C:\Users\pks\Documents\Hacktober\lbry-desktop`

This message is repeating itself for multiple core-js dependency's files.

**Comment by seanyesmunt** [comment]
@tzarebczan Have you seen anything like that on windows?

**Comment by pranabs1ngh** [comment]
I think its some error on my PC. I'm commiting this. You verify it before merging.

Is this okay?

**Comment by seanyesmunt** [comment]
yes

**Comment by toktoakhil** [comment]
Still on android , desktop and lbry.tv coma separation for adding multiple tags is not working..... FYI

**Comment by tzarebczan** [comment]
Type type the tags comma seperated and click enter or the plus next to the suggested input.

**Comment by toktoakhil** [comment]
> Just type the tags comma seperated and click enter or the plus next to the suggested input.

Sorry my mistake.... Just confirmed.

Thanks
