### ISSUE TITLE
New or Trending for Channels you follow not displaying correctly

### ISSUE THREAD

**Issue by granitepenguin** [lbryio/lbry-desktop#2847]
**Bug**
When selecting "New" or "Trending" for "Channels you follow", I'm told "You're not following any channels" when I definitely am following channels (I currently follow four, and even get notifications about new content available, both by email and popups from the app).

**To Reproduce**
1. Go to the main screen (click LBRY in the app)
2. Select "New" or "Trending" from dropdown
3. Select "Channels you Follow" from dropdown

**Expected behavior**
When I pick "New" or "Trending" for "Channels you Follow", I expect to see the list of new content, not a message that I'm not following any channels.

**Screenshots**
![LBRY_error1](https://user-images.githubusercontent.com/913430/64262635-ff78ea80-cef3-11e9-9394-5a895542561d.png)

**System Configuration**
![LBRY_about](https://user-images.githubusercontent.com/913430/64262650-056ecb80-cef4-11e9-9f1c-807bc768c85e.png)

Thanks!

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. There are a couple known bugs in this release that would cause it to happen. Can you try going to Settings > clear the cache to see if that fixes it? This will clear out any blocked channels and invalid subscriptions. 

The main bug that could cause this is if you block/follow a channel from the homepage vs channel/content page.

**Comment by granitepenguin** [comment]
I just navigated to Settings > clear cache, hit the button, and the app crashed.  However, it does look like it cleared out enough and it's now working.

When you say follow from the homepage vs channel page, which is preferable?

For reference, I had no blocked channels, and what would be an invalid subscription?

Thanks

**Comment by tzarebczan** [comment]
Thanks for the info. Have not seen the bug on clearing cache, will see if we can reproduce. 

If you follow someone from this screen, that's when the bug would occur: 
![image](https://user-images.githubusercontent.com/8120721/64265658-4e794c80-cf01-11e9-9eb2-2d90cdedbbd7.png)

**Comment by granitepenguin** [comment]
I think it's safe to say this can be closed.  Clearing the cache (even with the weird crash) fixed this specific issue. :)

**Comment by tzarebczan** [comment]
Glad to hear it's resolved and we'll have the above issue fixed with a release today. 

Can we show you some [appreciation](https://lbry.com/faq/appreciation) for the report?

**Comment by granitepenguin** [comment]
Thanks for the appreciation. :-)

**Comment by granitepenguin** [comment]
A little update... things look good after the latest update, too.
