### ISSUE TITLE
File view not counted on LBRY.tv if using pop out player / other random times

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2851]
Views are not counted if you are using the popout player + start new video. 

Also, views don't seem to count on the first content loaded when visiting lbry.tv and possibly randomly other times.

**Comment by eggplantbren** [comment]
That's probably why my view from a Tor tab didn't count yesterday, because it was the only thing I played after starting the tab and I think you end up on a new IP address each time you start the tab.

**Comment by tzarebczan** [comment]
I'm still seeing this on about every other view on beta.lbry.tv.

**Comment by seanyesmunt** [comment]
Fixed in #2898
