### ISSUE TITLE
Ensure view counted before we check rewards

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2853]
The view may not fire by the time we check for rewards in https://github.com/lbryio/lbry-desktop/blob/c41df0dba5a6c7be572af87712f298110b196881/src/ui/component/fileViewer/index.js#L38

**Comment by tzarebczan** [comment]
A user ran into this recently on Discord. He had to start a 2nd video to get the reward.

**Comment by kauffj** [comment]
probably the same as https://github.com/lbryio/lbry-react-native/pull/41/files#diff-df6261edb1a1cfdc321e00ea839dc65dR492

**Comment by tzarebczan** [comment]
Also, it won't auto-claim the reward unless it's in the reward list (current behavior in redux). 

We should consider calling reward_list in the background every half hour or so (we used to do this with the old homepage). Another option would be to call it before a download, but we probably don't want to (and might as well remove that requirement from redux if we wanted that).
