### ISSUE TITLE
Character Counter + Max Characters Info

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry-desktop#2859]
I recently left a long comment, but when I tried to send it, I received an error and my comment was lost. It turns out there is a 2,000 characters limit.

To avoid this issues, it would be very helpful to have the characters limit shown in the comments section and would be even better to have it show remaining characters remaining when typing, similar to how comment sections work on other platforms.

Also, to avoid the error shown in the image, it would be nice to have text input disabled if you reach the limit. Or at least, disable the send button, with a warning that too many characters have been used.

![image](https://user-images.githubusercontent.com/29914179/64392395-f3299480-d08f-11e9-81c7-0d8c3edae936.png)

**Comment by danielcaldas** [comment]
I have a suggestion for this one, I can soon open a PR

**Comment by tzarebczan** [comment]
Awesome @danielcaldas, thanks for grabbing it! Please see https://lbry.tech/contribute for an overview of our platforms. Please let us know if you have any questions.

**Comment by seanyesmunt** [comment]
Nice work @danielcaldas !

You are our first Hacktoberfest community member!
