### ISSUE TITLE
Dark mode Settings changes for internationalization

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry-desktop#2867]
- [ ] "Automatic dark mode" checkbox doesn't have a way to internationalize it - not sure where the string is coming from and I can't mark it up with the {__()} notation.
- [ ] Same issue with the dark/light menu dropdown.
<img width="1033" alt="Screen Shot 2019-09-06 at 10 03 59 PM" src="https://user-images.githubusercontent.com/1363664/64470367-f99f2700-d0f6-11e9-9cc4-36167d39a3bf.png">

**Comment by kauffj** [comment]
This looks like it was done. In general I support giving @kodxana first-try at these :)
