### ISSUE TITLE
Remove all references to featured content/reward

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2872]
We support the featured content reward in a few places in the app, i.e. calling list of claim ids eligible, the ribbon, trying to claim the reward in redux, etc.

**Comment by seanyesmunt** [comment]
This should be pretty simple. A good start would be removing all instances of `TYPE_FEATURED_DOWNLOAD`
https://github.com/lbryio/lbryinc/blob/master/src/rewards.js#L13

**Comment by priyapande** [comment]
Hi, I would like to try this out. Can you please tell me this issue needs a fix in lbryinc repo and will be  propagative fixed in lbry-desktop or changes will be required in lbry-desktop repo

**Comment by seanyesmunt** [comment]
@priyapande I believe changes will be needed in both repos.

**Comment by priyapande** [comment]
@seanyesmunt how can I test this?

**Comment by seanyesmunt** [comment]
I would start with removing that constant everywhere in both repos, and making sure the app doesn't crash anywhere.
You can check this out to get `lbryinc` running locally

**Comment by priyapande** [comment]
I have built the lbry-desktop app locally. I can't find TYPE_FEATURED_DOWNLOAD being called anywhere in it's code

**Comment by seanyesmunt** [comment]
My bad then. I guess only changes in `lbryinc` will be required for that part of this issue

**Comment by priyapande** [comment]
I removed all instances of the constant TYPE_FEATURED_DOWNLOAD from lbryinc repo and also built successfully locally using symlink. How do I push these changes to remote? I have created a separate branch but it's giving permission denied on that branch as well for push

**Comment by tzarebczan** [comment]
@priyapande there is still code related to it in the desktop side - one example is that we call fetchRewardedContent. Not sure if there are others, so maybe poke around that one to see if you find anything else.

**Comment by priyapande** [comment]
@tzarebczan In the code I see that dofetchRewardedContent which is referred to as fetchRewardedContent in desktop is actually a function of the lbryinc. If references of action TYPE_FEATURED_DOWNLOAD are removed from lbryinc function it will automatically not be a part of fetchRewardedContent. Please correct me if I'm incorrectly understanding the use case.

**Comment by tzarebczan** [comment]
I'm just saying we still need a desktop PR to remove that function.

**Comment by tzarebczan** [comment]
Fixed in https://github.com/lbryio/lbry-desktop/pull/3167
