### ISSUE TITLE
Video player keyboard shortcuts

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2879]
We already do have https://github.com/lbryio/lbry-desktop/issues/2159 (which was added then removed) and https://github.com/lbryio/lbry-desktop/issues/1395 filed for shortcuts, but I wanted to get a separate issue filed specifically for ones related to the video player. 

A few users have asked for the ability to full screen and skip around with arrow keys. Volume control would be another good one. We should look at YouTube to see what other shortcuts they support.

**Comment by tommyriska** [comment]
Volume control has to be added, its not very pleasant having to change my system volume to be able to use LBRY.

**Comment by pankajpatel** [comment]
I love this feature and would love to see it in the app. I would like to try some fiddle and see where it goes.

**Comment by tzarebczan** [comment]
Awesome, thanks for taking a look! I added the Hacktoberfest label for you also. Check out https://lbry.com/news/hacktoberfest-2019

**Comment by ahmedkrmn** [comment]
Can I work on the issue?

**Comment by tzarebczan** [comment]
Looks like someone claimed it already. @pankajpatel are you still planning to work on it?

**Comment by pankajpatel** [comment]
Yes, I am checking for solutions available around the internet.
@ahmedkrmn Please go ahead if you have solution in mind; I had something in mind, though it didn't work as expected.

**Comment by kauffj** [comment]
@pankajpatel @ahmedkrmn the solution most likely involves binding to key events and performing the appropriate corresponding action in `videoViewer/view.jsx`.

**Comment by pankajpatel** [comment]
@tzarebczan @kauffj
Above MR #2999 is what I came up with; mimicking some of youtube KB shortcuts
