### ISSUE TITLE
Fix UX around publishing to already published URL

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2882]
If you select a file and the auto-suggested name collides with an existing publish, it's not super clear that this new file will overwrite your previous publish. I think we should either disable the publish button and put the "edit this claim" text near it, or make the publish button say edit with a strong warning.

![image](https://user-images.githubusercontent.com/8120721/64797129-e1903300-d54e-11e9-946e-56f6da0ccd48.png)

**Comment by tzarebczan** [comment]
A few users ran into this issue recently and overwrote other claims.

**Comment by tzarebczan** [comment]
A few users recently overwrote their claims. We should either improve this in the meantime by not allowing publish unless they click edit, or do https://github.com/lbryio/lbry-desktop/issues/3704

**Comment by ceoger** [comment]
I have also seen a few users complain about tier the last upload overwriting a previous upload.

My guess was they were probably editing a claim and ended up publishing a new file on the old claims. If that is the case, maybe we can have a warning after editing a claim where user selects  a new file.

**Comment by kauffj** [comment]
(Closed this prematurely, but fix will be merged very soon)
