### ISSUE TITLE
Blocked Mature Channels Are Hidden With Show Mature Off

### ISSUE THREAD

**Issue by FLStudioBits** [lbryio/lbry-desktop#2890]
**Bug**
Blocked Mature Channels Are Hidden On The Manage Blocked Channels Page With Show Mature Off

**To Reproduce**
1. block a mature channel
2. turn show mature off
now the mature channel is also hidden on the manage blocked channels page

App    0.35.3
Daemon (lbrynet)    0.40.1

**Comment by tzarebczan** [comment]
Thanks for finding and filing this @FLStudioBits ! Sent you some appreciation on Discord.
