### ISSUE TITLE
lbry.tv bugs megaissue

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2894]
1. [x] fix issue with no tags on first run / new user 
1. [x] always turn on sync for lbry.tv users

- [x] subscription api not called on follow, only the set/preference api

- [x] can't get back into rewards flow after skipping through it. Rewards page shows rewards greyed out. 

- [x] enable comments for signed in accounts - otherwise drive sign in.

- [x] Customize Your Homepage comes back on main page on refresh (after closing)

- [x] clear all redux state on logout (e.g. language should reset)

- [x] vanity url is navigated to on page changes. Go to lbry://@history#14fcd92ad24c1f1bc50f6cbc1e972df79387d05c and click page 3. 

- [ ]  Randomly stuck on loading: File under https://github.com/lbryio/lbry-desktop/issues/2979
![image](https://user-images.githubusercontent.com/8120721/65167983-91fbac80-da11-11e9-98a2-174930b1f0b6.png)

- [x] FILE SEPARATELY? title bar should show lbry.tv or the content you are on. If also seems to get stuck between navigation/not update. i.e. if you go to https://beta.lbry.tv/@TechFox:2/akko-3068-mechanical-keyboard-review:2 it will show in the title bar, but if you navigate away, it won't update. Doesn't update if you go to any claims from the homepage. 

![image](https://user-images.githubusercontent.com/8120721/65076011-1133a680-d966-11e9-9461-0b51056cabf6.png)

- [x] ensure token stored at / and not /$ - this happens when you sign in from a beta.lbry.tv/$ page, which is a redirect in various cases (i.e. signing out from overview page). 

- [x] Hide `You can generate a new address at any time, and any previous addresses will continue to work.` from wallet page too (we recently removed the button). 

- [x] Export button on transaction full history doesn't do anything - fix or hide for now
- [x] sync settings at some interval (5/10 minutes?)
- [x] add language and claim support to Settings 
- [x] add loading animation after email confirm/during email reward claim
- [x] if you remove a tag, it's not removed from the set api call that's sent. 
- [x] publish page crashes lbry.tv

**Comment by dan1d** [comment]
Hi @tzarebczan is this the repository for lbry.tv ?

**Comment by tzarebczan** [comment]
They both share the same code base, yes.

**Comment by dan1d** [comment]
Thank you!

**Comment by kauffj** [comment]
@dan1d actually most lbry.tv code is in this repo, the repo you found is just backend API code
