### ISSUE TITLE
Separate control for autoplay next in list

### ISSUE THREAD

**Issue by jessopb** [lbryio/lbry-desktop#2902]
To autoplay videos when you arrive on a page should be a separate control from autonavigating to the next in the list.

**Comment by tzarebczan** [comment]
This should go along with https://github.com/lbryio/lbry-desktop/issues/2921

**Comment by tzarebczan** [comment]
With playlists being added, this autoplay next option should be at least added to the playlist content view.

**Comment by kauffj** [comment]
do you want to do this @saltrafael ?

**Comment by saltrafael** [comment]
sure!
