### ISSUE TITLE
Cannot buy paid content in latest release

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-desktop#2915]
In the latest release (0.35.4) I cannot buy paid content. I don't get the confirm purchase dialog box. The waiting animation just plays indefinitely. If this is confirmed it should be fixed ASAP as some people are making quite good use of paid content (e.g., Efe Aydal has 1631 views in just a few weeks, all of paid content).

**Comment by seanyesmunt** [comment]
Confirmed 😞 

Will release a fix shortly. Thank you for reporting!

**Comment by eggplantbren** [comment]
I'm just glad we caught it early.

**Comment by eggplantbren** [comment]
Trying your latest RC and it's working. :-)

**Comment by seanyesmunt** [comment]
Great. Thanks again
