### ISSUE TITLE
Add delay / pause / interstitial to autoplay

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#2921]
Autoplaying in 3... 2... 1... [stop]

This screen should also facilitate replaying (previously #1567)

**Comment by tzarebczan** [comment]
We should really add this feature soon along with https://github.com/lbryio/lbry-desktop/issues/2902 - it's a very strange experience when it "randomly" navigates away from the content you are in (happens in pop out mode too)
