### ISSUE TITLE
Audio keeps playing after auto-played video mini-player closed 

### ISSUE THREAD

**Issue by kekkyojin** [lbryio/lbry-desktop#2922]
**Bug**
I had watched a video and then a new one auto-played. I browsed to the home page by clicking the LBRY logo and then the video was shown as a popup window. I closed it, but audio still played for a long long time. It only stopped when closing the LBRY app.

**To Reproduce**
1. Watch a video
2. wait until it ends and a new one begins to be auto-played
3. Browse to the home page
4. Close the popup window with that video been played
5. Audio of the video keeps being played

**Expected behavior**
No audio should be reproduced after popup window was closed

**System Configuration**
LBRY App: 0.35.7
Daemon: 0.40.1
OS: macOS 10.14.6 (Darwin 18.7)

**Comment by tzarebczan** [comment]
Hey @kekkyojin , thank you so much for opening this issue! Can we show you some [appreciation](https://lbry.com/faq/appreciation) for the contribution? 

We'll try to reproduce and fix this. We've seen this happen rarely in the past, so it may be an edge case / timing issue. My first attempt to reproduce was not successful, so if you can get it to happen each time, let me know the exact timing (i.e. do you close while the 2nd video is loading?)

**Comment by DispatchCommit** [comment]
should investigate this alongside #5000

**Comment by DispatchCommit** [comment]
Duplicates #5328 

Will be resolved when #5372 is merged

**Comment by kekkyojin** [comment]
How can a bug report opened in September 2019 duplicate another one opened in 2021?
