### ISSUE TITLE
Reward amount is wrongly displayed for multiple youtube channels

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry-desktop#2926]
**Bug**
When listing available rewards the response contains the following
_redacted_ (see slack)
However the displayed amount is the same for both: https://scrn.storni.info/2019-09-26_20-17-14-016761057.png

**To Reproduce**
have 2 unclaimed youtube channels to redeem

**Expected behavior**
Both channels should have their own reward value

**Screenshots**
the description contains a hacked amount that should be what's displayed on the button.
https://scrn.storni.info/2019-09-26_20-23-32-711972767.png

**System Configuration**
Master branch, on linux

**Comment by tzarebczan** [comment]
Closing for https://github.com/lbryio/lbry-desktop/issues/3403
