### ISSUE TITLE
Markdown rendering issues with lbry urls and channel mentions 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2928]
- [x] apostrophe breaks in channel name:

![image](https://user-images.githubusercontent.com/8120721/65728522-3b354900-e089-11e9-824d-cac423307884.png)
 

- [ ] @gmail tries to show gmail channel: 
![image](https://user-images.githubusercontent.com/8120721/65728116-ef35d480-e087-11e9-84e5-96a6233c11a3.png)

@btzr-io , please un-assign yourself if you won't have time to look into these. Thanks!!

**Comment by btzr-io** [comment]
@tzarebczan I have some free time this week. Do you have the url of the examples ? ^^

**Comment by kauffj** [comment]
@btzr-io awesome! looks like OP cites \@dimitri and \@gmail as two examples

**Comment by kauffj** [comment]
Sorry for the erroneous tags @dimitri and @gmail, I tried escaping your handles with a \ but that does not appear to prevent a mention.

**Comment by tzarebczan** [comment]
Fixed in https://github.com/lbryio/lbry-desktop/pull/3013
