### ISSUE TITLE
The Share - Support - Following Button on the top of channel pages Is not working on Small Screen

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-desktop#2948]
## Screenshot
![image](https://user-images.githubusercontent.com/26609573/65986416-045a9b00-e4ae-11e9-83dd-34c70049ae63.png)

## The Issue
When I click on my LBRY Channel lbry://@YULIUS-KURNIAWAN-KRISTIANTO#c and after i click that i see share - support and also following button on the top of channel pages. i try to click one of them, example share button, is not clickable. is worked if use short channel name like MemeKing channel,., 

## Steps to Reproduce
1, Find out a longest channel name like lbry://@YULIUS-KURNIAWAN-KRISTIANTO#c
2. on the top of channel page, lets click a share button
3. not working as my pointed out on above

## System Configuration

App | 0.35.7
-- | --
Daemon (lbrynet) | 0.42.0
Platform | Windows (Windows-10-10.0.17763-SP0)
Installation ID | 7CsTidYjVQPkCWHHNT8kuHRUrGoP8Hfd6wfhG6HEUEYuNYUkJomgN6mbKBbrEno8oC

**Comment by tzarebczan** [comment]
Thanks for filing @ykris45 ! This will only affect devices with small screens and long names. Wanna take a shot at fixixng it? Adding hacktoberfest label.

**Comment by ykris45** [comment]
@tzarebczan i was done my king of LBRY Discord Server
