### ISSUE TITLE
YT sync awareness on synced channel page / other driver

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#2980]
During our transfer feedback sessions, some users navigated directly to their channel via the URL bar to try to claim it. We should either put it there or give them some banner across the top of the app if one of them is transferable.

**Comment by jessopb** [comment]
There are a couple of phases of this.

First they complete the process and are queud.
For this, we could be aware of channel names during url bar search, but that might not be necessary. During this time, their @channel doesn't exist.

Second, the claim is ytsynced and transferable.
For this, a claim/transfer button on the channel page. It could either link them to channels or initiate ytchannel claim itself.

**Comment by tzarebczan** [comment]
@seanyesmunt ,  @julianchandra ran into this confusion on a recent youtuber, would be nice to get into your sync changes as well.

**Comment by julianchandra** [comment]
What we experienced was this.
1. Creator's Channel was live - I could find it and watch videos.
2. The creator/owner of the channel couldn't see his channel or videos until he claimed the channel.

Is there a way to automate the claiming channel process or to notify the creator upon login to claim the channel?

I'm aware we send an email out for notifying the user to claim their channel. 
We don't have such a template for Odysee. If we cannot do anything like what's suggested above, I can incorporate language from the email which advises the user to claim their channel into the 'your channel is live' email on Odysee.

Whatever everyone thinks is best.

**Comment by tzarebczan** [comment]
They do get prompted to claim/transfer the channel if they login + the channel is synced already. I think the confusion is about going to the Channels page - not many explore this area, and end on up on their channel page instead. I think added the claim/transfer button here would solve most issues. 

Further down the road we could sync the channels directly into their wallet if they already signed in. This would require an SDK side fix + dev time on the app+apis.

**Comment by tzarebczan** [comment]
This has been added, will be on lbry.tv soon.
