### ISSUE TITLE
Fix Web Link Sharing URL

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry-desktop#2995]
**Bug**
Forward slash in Web Sharing URL was removed in latest release

**To Reproduce**
1. Open the desktop app and select a video.
2. Click on the Share link.
3. Look at the link shown under Web link.

**Screenshots**
<img width="500" alt="Screen Shot 2019-10-07 at 10 11 54 AM" src="https://user-images.githubusercontent.com/1363664/66333729-6a9b4f80-e8ec-11e9-9c5d-217f7a6ff8b8.png">

**Comment by jessopb** [comment]
I see it.

**Comment by jessopb** [comment]
Fixed.
