### ISSUE TITLE
Customize Your Homepage Tag Page reappears after publishing/editing

### ISSUE THREAD

**Issue by FLStudioBits** [lbryio/lbry-desktop#2996]
#### Issue Summary

getting the Customize Your Homepage Tag page after you just uploaded a file when clicking on lbry in the top left of the app

#### Steps to Reproduce

1 - upload a file and add tags, complete filling in all that is needed then hit publish
2 - now after this if you click lbry in the top left of the app that will bring up the Customize Your Homepage tags

**Comment by kauffj** [comment]
@FLStudioBits thanks for filing. This looked to be related to the desktop app so I moved it there.

Clicking the LBRY logo will take you back to the home page though, so this seems like it might be correct behavior. Did your publish go through okay? What happened after you clicked publish?

**Comment by FLStudioBits** [comment]
yes desktop app, everything published just fine its just that it brings up the customize home page tags page unexpected, you basically get what you get when you click customize on the right

was asked to file it so i did, jiggytom thought this was related to some other tag related bug currently there

**Comment by kauffj** [comment]
Thanks @FLStudioBits, we'll look into it.

**Comment by FLStudioBits** [comment]
thanks, just noticed the same thing happens if you edit a claim
