### ISSUE TITLE
Saved Password Can't Be Cleared

### ISSUE THREAD

**Issue by m160** [lbryio/lbry-desktop#3004]
**Bug**
Clicking **forget** in the Clear Password window does nothing.

**To Reproduce**
1. Go to Settings
2. Click on the checked Save Password box
3. Click **forget**
4. Nothing happens until you click **Nevermind**

**Expected behavior**
Save Passwords checkbox gets unchecked.

**System Configuration**

- LBRY Daemon version: 0.42.1
- LBRY App version: 0.36.0
- LBRY Installation ID: 2P2W4YbKUARUszYRLbMDE2iKRde9FqV7xs5xiHvn5ad9Gj4GCW4zRboWLYJ7RpjkEg
- Operating system: Linux (Linux-5.0.0-31-generic-x86_64-with-debian-buster-sid)

**Comment by seanyesmunt** [comment]
Thanks for opening the issue!

**Comment by tzarebczan** [comment]
This was filed already: https://github.com/lbryio/lbry-desktop/issues/2978
