### ISSUE TITLE
add triggers to sync preferences/wallet

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3022]
Besides just syncing at a 5 minute interval, we should also sync after adding/removing a tag/subscription and after creating a channel. 

Today on LBRY.tv, you'd lose any tags if you refresh before the interval. On desktop, you'd lose it if you closed the app or refreshed. 

When we add other settings, we'll need to trigger it as well.

**Comment by kauffj** [comment]
@seanyesmunt please see my commentary on https://github.com/lbryio/lbry-react-native/pull/56 before beginning work on this.

After seeing this ticket as well it makes me think that at least logic for this should be shared between desktop and mobile. Both apps want to trigger pushing user state in the same cases (tags changing, channel creation, etc.).

How can this logic be shared and cleanly separated?
