### ISSUE TITLE
Incorrect styles of tooltip on dark theme

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry-desktop#3031]
**Bug**
There is a white border and odd spacing around the claim preview tooltip when dark theme is active.

**To Reproduce**
1. Select dark theme.
2. Go to 'Any claim'.
3. Hover a any channel link / mention to see the tooltip.

**Expected behavior**
Consistency of styles on all themes.

**Screenshots**
![tooltip-dark-bug](https://user-images.githubusercontent.com/14793624/66710457-f15d8b80-ed35-11e9-9acf-00a7887b196a.png)

**Comment by ChakshuGautam** [comment]
Would like to take this up.
Thanks.

**Comment by tzarebczan** [comment]
It's already fixed, see referenced PR

**Comment by ChakshuGautam** [comment]
Sorry I missed that because of no discussion on this. I will look for others with no PRs. :)
