### ISSUE TITLE
Missing tooltip on channel mention

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry-desktop#3036]
**Bug**
Channel links / mentions don't have the preview tooltip on markdown preview component.
**To Reproduce**
1. Go to 'Any claim that contains a channel link / mention'
2. Move the mouse over the channel link / mention

**Expected behavior**
Display channel preview tooltip on all valid channel mentions.

**Comment by tzarebczan** [comment]
Nice find, thank you for filing!
