### ISSUE TITLE
Display/hint what keyboard shortcuts are available in videos

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3041]
https://github.com/lbryio/lbry-desktop/pull/2999/files - we added keyboard shortcuts, but no one will know how to use them. We should do something similar to YouTube where there are tool tips over the actions. We may need to add an action overlay for skipping.

**Comment by kauffj** [comment]
In addition, it would be cool if you could press a key to see all shortcuts in some sort of overlay.
