### ISSUE TITLE
Recent transactions > latest transactions, use transaction list pagination

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3045]
Currently, the recent transactions we show are from the last 7 days. 

Instead we should rename this to the "latest transactions" and use page 1 (10 items?) from transaction list.

**Comment by blokboy** [comment]
Is anyone working on this yet @tzarebczan ?

**Comment by tzarebczan** [comment]
Nope, it's all yours! Sounds like this will require some redux work as well - are you comfortable with that?

**Comment by blokboy** [comment]
@tzarebczan sorry it was a busy weekend but that's fine I'm reading thru the redux repo now :)

**Comment by blokboy** [comment]
@tzarebczan I've submitted a PR for this one :) lemme know if I need to make any changes!

**Comment by tzarebczan** [comment]
This has been implemented
