### ISSUE TITLE
Can't interact with channel tooltip

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry-desktop#3050]
**Bug**
The `channel- tooltip` provides actions such as follow / unsubscribe and block / unblock,
but as soon as you move the mouse outside the link the tooltip will hide.

**Expected behavior**
User should be allowed to click the buttons or use labels instead to prevent confusion.
```
[ Follow ] ---> [ Following ]
[ Block ] ---> [ Blocked ]
```

**Comment by seanyesmunt** [comment]
IMO you shouldn’t be able to interact with tooltips. If it contains content that should be interactive, it should be replaced with a menu button. This allows mobile and keyboard users to get the full experience too.

**Comment by btzr-io** [comment]
Ok, I agree `claimPreview` needs a non interactive layout.

**Comment by seanyesmunt** [comment]
Those buttons should already be hidden from tooltips.

**Comment by seanyesmunt** [comment]
Nevermind. I see they are there. That's a bug.

**Comment by seanyesmunt** [comment]
Now their gone 🙂

**Comment by btzr-io** [comment]
Fixed on https://github.com/lbryio/lbry-desktop/commit/f1d2d0243be4e7f7c81cc116b0e7d52e09af4bb4
