### ISSUE TITLE
Ctrl taken over on file page / pop out player

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3051]
You can't click ctrl-q/ctlr-r or other ctrl commands when on the file page or when the pop out player is active. @btzr-io , this may be related to one of your recent changes, can you take a peek?

**Comment by btzr-io** [comment]
I dont thinks so :stuck_out_tongue: 
Also noticed you cant use `alt` to open the title bar (toolbar) unless you focus the search input. Odd :thinking:

**Comment by btzr-io** [comment]
Fxed on https://github.com/lbryio/lbry-desktop/commit/9a6b79c41e4e7761de9fb345aec8f468833468bb

**Comment by tzarebczan** [comment]
Thanks @btzr-io !
