### ISSUE TITLE
"Unlock Rewards" bring nothing only the loader for ever

### ISSUE THREAD

**Issue by ssynieok** [lbryio/lbry-desktop#3056]
Details:
App | 0.36.1
Daemon (lbrynet) | 0.42.1
Platform | Mac OS 18.7.0

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. What happens if you press cmd-R or close out / try again, does it work then? Was this on a new account? 

Send us an email at hello@lbry.com with the email you are trying to use as well, that may provide more clues.

**Comment by tzarebczan** [comment]
We have not been able to reproduce this. Please reach out if you are still seeing it.
