### ISSUE TITLE
Checkboxes/radio elements are inaccessible to keyboards

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#3057]
This will require changes in https://github.com/lbryio/components

`<checkbox-element>` and `<radio-element>` are unable to be focused when tabbing through the UI.

Unsure of the fix for this.

**Comment by hackily** [comment]
Pretty tricky problem solve - you would almost certainly need additional js to handle the behavior consistently across browsers

Some examples from the Web Accessibility Initiative can be found here:
https://www.w3.org/TR/wai-aria-practices-1.1/examples/radio/radio-1/radio-1.html
https://www.w3.org/TR/wai-aria-practices-1.1/examples/radio/radio-2/radio-2.html

**Comment by seanyesmunt** [comment]
Thanks for the links @hackily. I'm hoping to fix this up today and will check those out!

**Comment by seanyesmunt** [comment]
Fixed with https://github.com/lbryio/components/pull/12

Still requires a desktop fix that's happening on https://github.com/lbryio/lbry-desktop/tree/dark
