### ISSUE TITLE
Channel page search not properly clearing

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#3062]
If you search on a channel page, then delete the search, the original content doesn't come back

**Comment by consolelogreece** [comment]
Currently, as far as I can tell, you have to press enter to perform a search. As such, if you delete the search and press enter it brings back the original content. Maybe we could tie the search functionality to an onchange event? If we do, we should probably debounce it too.

**Comment by seanyesmunt** [comment]
I agree with everything you just said. Are you interested in working on this?

**Comment by consolelogreece** [comment]
Yeah i'll give it a shot!
