### ISSUE TITLE
Infinite scroll stops working when navigating to file page / back 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3071]
Reproduce:
1. Scroll down a couple of pages
2. click a claim
3. click back
4. scroll down
5. infinite scroll stops

If you go back up a little and then back down, it starts working again.

**Comment by tzarebczan** [comment]
This is one of my most annoying issues!

**Comment by HarshKhandeparkar** [comment]
I can work on this. I looked into the infinite scroll page while working on my last PR #4054 and the code is not efficient/best way. I also found that infinite scroll doesn't work at all on smaller `pageSize` i.e. number of loaded elements.

I can look into this. May I?

**Comment by kauffj** [comment]
Definitely @HarshKhandeparkar!

**Comment by HarshKhandeparkar** [comment]
@tzarebczan I wasn't able to reproduce this one. It seems like infinite scroll works fine? :man_shrugging:

**Comment by tzarebczan** [comment]
I'm able to reproduce in the all content area. First scroll down so a 2nd page loads. Then scroll down a little bit and click an item. Click back to go to all content. Scroll down again. It will stop at the bottom. Try this a couple times and see if it does it. Happens consistently here. 

If I scroll back up and down a few times, then it scrolls more.

**Comment by HarshKhandeparkar** [comment]
Okay I'll try again today. Maybe I was doing this incorrectly.

**Comment by HarshKhandeparkar** [comment]
I am still not able to reproduce this very well. The content is also not loading fast enough (Internet Cap Over, Meh). Could you record a GIF or a video of this?  TY.

**Comment by tzarebczan** [comment]
Let me know if this helps: https://photos.app.goo.gl/hgkzZ5Yo7VVZ5KJGA

Notice how sometimes it starts again when going back up and down, and other times it takes a few tries. This happens on desktop too.

**Comment by HarshKhandeparkar** [comment]
Okay got it. I was trying this on my desktop. Does it happen on a desktop
too?

**Comment by HarshKhandeparkar** [comment]
I managed to reproduce this on the desktop app too. Trying to fix...
