### ISSUE TITLE
comma separated tags on publish added one by one (or last only added)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3073]
If you comma separate tags on publish and click enter, only the last tag is added. If you click the tag name to add the list, it adds one by one. 

It works as expected on the customize homepage.

**Comment by jessopb** [comment]
Yeah - calling           
              `updatePublishForm({ tags: [...tags, newTag] });`
twice in rapid succession. 
Converting onSelect to take an array.
