### ISSUE TITLE
call preference get on startup when not signed in / not sync enabled

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3076]
This would be the use case of someone trying to use LBRY without an account, but still wanting to keep their tags/preferences synced to the wallet. 

We don't call it on startup, but do after a change, which would overwrite any existing tags.

**Comment by finleyexp** [comment]
Latest update fixed the following from #3169 

On my machine...

1. 'Spin Spin Sugar' setting stays disabled upon clicking 'I feel woozy.' <-- Seriously, thanks a lot!
2. Dark mode stays enabled
3. Customize tags no longer revert to default upon reload
4. Followers list remains enabled and visible in sidebar

Way to go LBRY Dev!! Y'all are rockin'' things over here!

**Comment by tzarebczan** [comment]
Glad to hear that's working better!

**Comment by tzarebczan** [comment]
This will be fixed in the next release, thanks @jessopb !

**Comment by tzarebczan** [comment]
This will be fixed in the next release, thanks @jessopb !
