### ISSUE TITLE
Incorrect subscription count on lbry://@LBRY.Records#3

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-desktop#3090]
Just a minor issue but possibly easy to fix. The subscription count on this channel is wrong, as you can see in the screenshot below which shows zero even though I'm subscribed. It also shows zero on beta.lbry.tv.

![image](https://user-images.githubusercontent.com/1578298/67155593-db238100-f36e-11e9-9408-166b8de99b98.png)

I suspect it might be the dot in the channel name messing up your API call.

**Comment by tzarebczan** [comment]
Thanks for filing, we are aware of this one and we just need to deploy an api fix we have. You're right, it was a valid character checker when subscribing. For it to count going forward, you'll need to unsub and resub.
