### ISSUE TITLE
Cannot enable rewards without claiming my youtube channel

### ISSUE THREAD

**Issue by jessopb** [lbryio/lbry-desktop#3093]
I created a youtube channel with an upload. 
I could not enable rewards for the entire time it was queued, and still cannot complete the process without claiming the channel.

**Comment by tzarebczan** [comment]
What's the bug? YouTube channels undergo additional review for rewards. It's only supposed to happen over a certain threshold, so I'll file a bug on apis for this.

You can't claim the channel unless it's actually synced.

**Comment by jessopb** [comment]
All rewards in the app are disabled for the duration that my youtube transfer is queued. I can't be a full lbry user until that process is done?

**Comment by tzarebczan** [comment]
I filed the internal apis issue. Yes, we've had lots of rewards abuse so these normally require additional review. 

Once it's synced, it should be claimable regardless.
