### ISSUE TITLE
Duplicate tags / can't remove tag because they are not normalized on input

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3096]
You can add 2 tags of the same name but different capitalization. You end up in a weird state where removing the tag actually adds back the other one. 

Go to the customize screen and add: crypto and click enter. 

Now add Crypto (with a capital C), click enter.

Remove the first crypto, and then try to remove the 2nd crypto - it gets added back so you end up with duplicates and you can't remove the tag.

**Comment by consolelogreece** [comment]
I'll do this

**Comment by tzarebczan** [comment]
This was fixed
