### ISSUE TITLE
lbry.tv support for edge

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#3098]
There is just a blank screen for users on edge. Not sure what's wrong.

**Comment by finer9** [comment]
HTML1300: Navigation occurred.
lbry.tv (1,1)

SCRIPT1028: SCRIPT1028: Expected identifier, string or number
ui.js (1,102646)

**Comment by jessopb** [comment]
the unexpected string is almost certainly because it doesn't understand javascript "rest" i.e. "..." operator. There's a babel plugin for that. I'll test shortly.

**Comment by seanyesmunt** [comment]
Fixed with #3268 #3267
