### ISSUE TITLE
Trying to add two identical tags doesn't add any.

### ISSUE THREAD

**Issue by consolelogreece** [lbryio/lbry-desktop#3109]
**Bug**
Trying to add two identical tags doesn't add any. For instance, adding "tag,tag", nothing will be added.

**To Reproduce**
1. Go to tags
2. try adding "tag,tag"
3. nothing happens

**Expected behavior**
should add "tag" to tags.

**Comment by tzarebczan** [comment]
Nice find and fix, thank you!
