### ISSUE TITLE
channel fails to load randomly when navigating directly to it from another page

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3112]
See https://open.lbry.com/vokoscreen-2019-10-23_11-25-17:9a5e6f1e869551a373beb645e654ca166a535034 - thanks to @eggplantbren 

It does happen a bit randomly. Usually it's when your on a channel page already, and then navigate to another channel using your follow sidebar. The channel page will show "no content available" but it does have content. Claim search on the channel being navigated to is not run in that case. 

Ctrl-R fixes it. @seanyesmunt thinks it's related to pagination somewhere.

**Comment by eggplantbren** [comment]
Possibly related, but I've also noticed that occasionally when you click onto a channel page, the page numbers at the bottom are absent.

**Comment by tzarebczan** [comment]
Other users are noticing this as well. I've run into it a few times myself. Don't have a clean repro, but does happen most often when navigating to a channel from your subscriptions sidebar. @seanyesmunt thinks it's related to pagination.

**Comment by eggplantbren** [comment]
As a frequent user of the app, I think this is the most annoying bug at the moment.

**Comment by kauffj** [comment]
@tzarebczan we didn't discuss this one today - is this workable or does it need better repro first?

**Comment by tzarebczan** [comment]
Sean pushed up a fix to lbry.tv and we haven't seen it there since. But @eggplantbren and I still run into https://github.com/lbryio/lbry-desktop/issues/3188 randomly. Closing this for now, please re-open if you see it on lbry.tv again (or after next release)
