### ISSUE TITLE
Transaction list doesn't load on lbrytv when wallet page is accessed directly

### ISSUE THREAD

**Issue by sayplastic** [lbryio/lbry-desktop#3114]
**To Reproduce**
1. Go to https://beta.lbry.tv/$/wallet directly
2. See that the Recent Transactions loading spinner is stuck indefinitely

It does load properly when accessed via the wallet menu.

**Comment by tzarebczan** [comment]
Sean is aware and this is filed in the megsissue. It's a timing problem.

**Comment by tzarebczan** [comment]
@sayplastic I think https://github.com/lbryio/lbrytv/pull/104/files should fix this. Can you make sure it's deployed on Dev to test?

**Comment by tzarebczan** [comment]
Looks like it's fixed now
