### ISSUE TITLE
Consider using --blocking with sync_apply

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3121]
I recently ran into an issue on beta.lbry.tv where I was asked to create a channel even though my account already had one. My guess is that sync apply had not finished syncing the new accounts that were added so it wouldn't know about my channel.

The downside to this is that it will take longer to sign in for the first time on existing accounts that were never synced or had lots of transactions since their last login.  We can give them a loading/waiting screen while this happens, but there's no progress indicator at this time (it may not even be possible).

**Comment by seanyesmunt** [comment]
Just added this
