### ISSUE TITLE
Sharing videos with a start timestamp

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3122]
Similar to youtube, we should be able to share a URL to a video at a certain timestamp within the video.

**Comment by tzarebczan** [comment]
We've got the reading of the ?t= tag, now just need it added to the share modal!

**Comment by jeffslofish** [comment]
I'm going to work on this now

**Comment by jeffslofish** [comment]
For the UI, how about something like this:

![Screen Shot 2020-05-02 at 9 51 54 PM](https://user-images.githubusercontent.com/1240484/80898989-38ee3980-8cbf-11ea-8efa-a390c783e6b0.png)
![Screen Shot 2020-05-02 at 9 51 06 PM](https://user-images.githubusercontent.com/1240484/80898990-3986d000-8cbf-11ea-9271-7af7b145020c.png)

**Comment by jeffslofish** [comment]
Also, should both the "LBRY Link" and "Embedded" tag have the t parameter, but not the "LBRY URL" or "Download Link"?

**Comment by tzarebczan** [comment]
@jeffslofish , that's looking great so far, thank you! Alignment could use some work, but I'll let @seanyesmunt comment further. 

And yes, this would only make sense in the LBRY link. We could make them work in the LBRY URL, but that requires: https://github.com/lbryio/lbry-desktop/issues/3972

**Comment by seanyesmunt** [comment]
Nice! I’m not sure exactly how it should look but that is a good start. That can work for now if the inputs are vertically aligned with each other.

**Comment by kauffj** [comment]
I'm here with the bikeshed of also shrink the input width if it's limited to a time value
