### ISSUE TITLE
.htm files not opened in LBRY browser

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-desktop#3124]
This should be trivial to fix. I've been using HTML files in LBRY for a while. With extension .html they are recognised. With extension .htm they are not. Example:

lbry://declaration_of_independence#b

I tried to find where to fix this in lbry-desktop and lbry-redux but I couldn't find it, sorry.

**Comment by colinfruit** [comment]
wow, someone opened my file! made a PR for this.
