### ISSUE TITLE
Pause gifs in thumbnails on first frame until hover

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-desktop#3134]
Related to https://github.com/lbryio/lbry-desktop/issues/2029

Example of an animated gif (NSFW sorry): `lbry://@15secondstofap#8` thumbnail

Resolving the claim shows that the thumbnail URL doesn't include a `.gif` extension. It looks like a directory URL. So i'm not sure how it's even getting the gif from there. But I suspect this is why the app isn't turning off the animation.

**Comment by tzarebczan** [comment]
Thanks for filing! I think we only fixed this on claim previews to prevent it happening on a whole bunch of claims on a single view. I think animating on these pages is okay.

**Comment by eggplantbren** [comment]
This one animates when you see it in trending. Is that what you mean by claim previews?

**Comment by tzarebczan** [comment]
Yes, I thought you meant it did on the channel page. Yes, then it could be related to a channel preview or the lack of a gif extension as you mentioned. Nice catch!
