### ISSUE TITLE
Ability to search through publishes

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#3139]
It should be possible to filter your own publishes via a search box, similar to the way that one can search their library or within a channel.

These PRs should the addition of this behavior for the Library area and may be a useful reference:
https://github.com/lbryio/lbry-desktop/pull/2969
https://github.com/lbryio/lbry-redux/pull/214

**Comment by jessopb** [comment]
![image](https://user-images.githubusercontent.com/36554050/160070751-1563f9ea-ee8a-4179-9844-a892bc92829e.png)
Probably lose the upload button, and add the search like on the collectoins page:

**Comment by jessopb** [comment]
![image](https://user-images.githubusercontent.com/36554050/160070889-b0edc1df-06b8-4fdf-9300-3eb1680d43c5.png)
