### ISSUE TITLE
channel edit thumbnail preview incorrect

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3161]
During edit: 
![image](https://user-images.githubusercontent.com/8120721/67974414-ca81cf00-fbe8-11e9-94f2-9d96f011945a.png)

after edit on the channel page: 
![image](https://user-images.githubusercontent.com/8120721/67974436-d40b3700-fbe8-11e9-87f6-185fd1e838c7.png)

**Comment by btzr-io** [comment]
I cant reproduce this issue
