### ISSUE TITLE
Cannot copy lbry:// video address on lbrytv

### ISSUE THREAD

**Issue by sayplastic** [lbryio/lbry-desktop#3165]
**Bug**
`lbry://` video address that is displayed under the video player is hidden behind `text-overflow: ellipsis` when the browser window is narrow enough. This makes it impossible to select or copy the whole address.

A minor UI gripe: the address looks like a plain hyperlink or something that is clickable but it really isn't.

**To Reproduce**
1. Go to https://beta.lbry.tv/@tioaventurabus:7/heading-back-to-arizona-bus-life-skoolie:1
2. Resize your window
3. Observe the address being obscured by ellipsis

**System Configuration**

- Chrome 78.0.3904.87 on macos

**Comment by tzarebczan** [comment]
It gets copied when clicked now, just pushed it up to lbry.tv. Not the best UX, but we can look how to improve that app-wide later on.
