### ISSUE TITLE
Customized Tags & Followings Revert to Default

### ISSUE THREAD

**Issue by finleyexp** [lbryio/lbry-desktop#3169]
# The BUGs
1. All user defined tags in "Customize Tags" revert to the default tags upon restart of the desktop app.
2. All the user selected accounts to Follow revert to default (not following anyone) upon restart of the desktop app.

### Customize Tags (default list)
art, automotive, blockchain, comedy, economics, education, gaming, music, news, science, sports, technology

### Customize Tags (user's list)
art, automotive, blockchain, diy, education, fiction, gardening, music, news, poetry, science, technology

## Reproduce Bugs
1. Login, vomit on login screen before clicking "I feel woozy" button, choose Customize, delete unwanted tags, add new tags
2. Choose Home, sort videos by new tags, find user to follow, click follow heart, check out other users
3. Watch some more videos, read some @gutenberg, and/or follow more whatever
4. Close the LBRY app
5. Login, vomit on the login screen before clicking "I feel woozy" button, choose Home, tada! the tags are reverted again.

## Expected behavior
1. Customized tags to remain customized, not to revert to default
2. Followed users to remain followed, not to revert to default

## System Configuration
LBRY desktop: 0.37.1
LBRY daemon: 0.43.3
LBRY Install ID: 8VabQQt1F54RuMLqr3M1eG41y7k3LDGidyhkVgT8wd6hrjKsciDy5g9nsY2gYxKd7M
OS: Windows 8.1

**Comment by tzarebczan** [comment]
Thanks for opening the issue. Are you signed into the app with an email address? If not, there's a bug already filed for this case under https://github.com/lbryio/lbry-desktop/issues/3076

And sorry about the wooziness - you should only have to disable that once...let me know if it turns back on.

**Comment by finleyexp** [comment]
I am signed in with an email address. The wooziness button setting is not sticking, I do have to turn it off every time I launch LBRY. No worries, @tzarebczan! I actually love the spinny thing, I just can't do it any more. Too many head traumas, I guess.  

I don't know what if any of this is related, but it may help troubleshooting...
1. I created the LBRY local account prior to syncing YouTube, 
2. I did name the channels the same thing, don't ask, (I won't judge, if you don't.)
3. The email address I use for YouTube is different than the email I used to set up LBRY. 
4. I received a syncing error on the YouTube status page: 
> The following error occurred: the channel properties cannot be edited anymore For support please send an email to hello@lbry.com
5. I followed the Clean Up instructions, went into Full History, found the first instance of the channel (the not sync'd to YouTube instance), there was no Trash option. I cannot delete either channel.
6. Both channels still exist. Even so, I did follow the further suggestion to transfer everything to the YouTube sync'd version of the channel.
7. Various Settings are also not sticking to user selection, but revert back to default on restart: Mature Content, Theme (Dark), Enable Claim Support

Let me know if there's any other info I can supply. Thanks for the awesome work you all are doing!

**Comment by tzarebczan** [comment]
Thanks for all the info and sorry to hear about the trouble. 

For #4, we are aware of some instances where this happens...we can merge them for you manually.  Were you trying to change the channel name there? Please email us at hello@lbry.com with the 2 emails that need to be merged.

For #5, the channel may show up as Update if there were any updates to it locally.  Let me know if you find it that way. I'll make sure that's mentioned in the FAQ. 

As far as your settings not sticking, I'm not sure why that is and can't replicate locally. You are signed into an email in the app right? These settings would not stick between installs, but should stick between restarts. What operating system are you on?

**Comment by finleyexp** [comment]
Rock on. I'll send an email with the merge request. 

Okay, here's the sysinfo from the log & an error my system is throwing:
>"processor": "Intel64 Family 6 Model 42 Stepping 7, GenuineIntel",
  "python_version": "3.7.4",
  "platform": "Windows-8.1-6.3.9600-SP0",
  "os_release": "8.1",
  "os_system": "Windows",
  "lbrynet_version": "0.43.3",
  "torba_version": "0.5.7",

2019-10-30 00:13:45,234 ERROR    lbry.extras.daemon.Components:573: failed to setup upnp
2019-10-30 00:14:23,752 WARNING  lbry.extras.daemon.Components:342: UPnP component failed to get external ip

Would this error cause the sync failures?

**Comment by tzarebczan** [comment]
Nope, would not. That happens normally on some routers/networks.

Closing this for now.
