### ISSUE TITLE
infinite scroll logic should use calculated values

### ISSUE THREAD

**Issue by jessopb** [lbryio/lbry-desktop#3175]
https://github.com/lbryio/lbry-desktop/blob/8900038a4a8d117ef66acd64307cf28087939975/src/ui/component/claimList/view.jsx#L72 uses PADDING_ALLOWANCE = 100.
calculate the actual difference and use that.

**Comment by infinite-persistence** [comment]
`Close`
Code no longer exists after several changes to infinite scroll in 2020.
