### ISSUE TITLE
make sure all lbry.tv pages have proper metadata

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3176]
@jsigwart commented on [Sat Nov 02 2019](https://github.com/lbryio/lbrytv/issues/111)

Description and other tags are not showing up for the main beta.lbry.tv siite. 

Here are sample tags appearing on an individual video:

```
<head>
    <meta charset="utf-8" />
    <meta charset="utf8"/>
    <title>NoFap Truth – One Year of NoFap from @RichardHarrisCoaching on LBRY.tv</title>
    <meta name="description" content="NoFap truth?  I reveal the truth about NoFap after one year practicing as a fapstronaut.  I talk about the benefits of NoFap, some of the challenges I faced, and some of the unexpected results after a..."/>
    <meta name="twitter:card" content="summary_large_image"/>
    <meta name="twitter:image" content="https://thumbnails.lbry.com/2ArvE-ObliQ"/>
    <meta property="og:description" content="NoFap truth?  I reveal the truth about NoFap after one year practicing as a fapstronaut.  I talk about the benefits of NoFap, some of the challenges I faced, and some of the unexpected results after a..."/>
    <meta property="og:image" content="https://thumbnails.lbry.com/2ArvE-ObliQ"/>
    <meta property="og:locale" content="en_US"/>
    <meta property="og:site_name" content="LBRY.tv"/>
    <meta property="og:type" content="website"/>
    <meta property="og:title" content="NoFap Truth – One Year of NoFap from @RichardHarrisCoaching on LBRY.tv"/>
    <meta property="og:url" content="https://beta.lbry.tv/nofap-truth-one-year-of-nofap:6e02ac0b83af31148b504561737c74362b2710dd"/><meta property="og:video" content="https://api.lbry.tv/content/claims/nofap-truth-one-year-of-nofap/6e02ac0b83af31148b504561737c74362b2710dd/stream" />
    <meta property="og:video:secure_url" content="https://api.lbry.tv/content/claims/nofap-truth-one-year-of-nofap/6e02ac0b83af31148b504561737c74362b2710dd/stream" />
    <meta property="og:video:type" content="video/mp4" />
    <meta property="og:video:width" content="1280"/>
    <meta property="og:video:height" content="720"/>
</head>
```

Here's our current head tag block for https://beta.lbry.tv:

```
<head>
  <meta charset="utf-8" />
  <!-- VARIABLE_HEAD_BEGIN -->
  <title>lbry.tv</title>
  <meta property="og:url" content="https://beta.lbry.tv" />
  <meta property="og:title" content="lbry.tv" />
  <meta property="og:site_name" content="lbry.tv"/>
  <meta property="og:description" content="All your favorite LBRY content in your browser." />
  <meta property="og:image" content="https://beta.lbry.tv/og.png" />
  <meta property="fb:app_id" content="1673146449633983" />
  <!-- VARIABLE_HEAD_END -->
 </head>
```

- [x] Write more descriptive title to replace "lbry.tv"
- [x] Add description tag
- [x] Add Twitter card and image tags
- [ ] Add ```fb:app_id``` meta tag to the dynamic meta tag creation for videos

---

@jsigwart commented on [Sat Nov 02 2019](https://github.com/lbryio/lbrytv/issues/111#issuecomment-549067943)

For reference, this is what I see when I search for "beta.lbry.tv" in Google:

<img width="638" alt="Screen Shot 2019-11-02 at 10 49 08 AM" src="https://user-images.githubusercontent.com/1363664/68075164-59195c00-fd61-11e9-9870-0d0cc9621a55.png">

Here is what I saw when searching for "piratebay.com" in Google

<img width="654" alt="Screen Shot 2019-11-02 at 10 44 11 AM" src="https://user-images.githubusercontent.com/1363664/68075165-59195c00-fd61-11e9-80ed-a2b641c1857d.png">

**Comment by kauffj** [comment]
@finer9 does `fb:app_id` need to be on all pages? do we need it at all? We're not loading the fb or twitter JS on lbry.tv, and I'd like to keep it that way.

**Comment by kauffj** [comment]
@seanyesmunt I think the only remaining change after #3193 is:

1. Answer to whatever Josh says re: `fb:app_id`
2. Make sure the other major pages google is indexing (Help, Publishes, etc.) have metadata. Although I don't know how it's even finding those...

**Comment by kauffj** [comment]
@finer9 can you comment on above?

**Comment by jsigwart** [comment]
Looking at [this](https://developers.facebook.com/tools/debug/sharing/?q=lbry.tv), it appears Facebook has figured out what the `fb:app_id` should be. So we can mark that as resolved.

<img width="720" alt="Screen Shot 2019-11-18 at 11 29 26 PM" src="https://user-images.githubusercontent.com/1363664/69125714-543ff200-0a5b-11ea-9723-347fc97d9d31.png">
Title and description still could be more descriptive.
