### ISSUE TITLE
Not all pages shown on Channels page (missing pagination)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3188]
Similar to https://github.com/lbryio/lbry-desktop/issues/3112 in that it happens randomly when viewing channels. In this case, you don't see the pagination options at the bottom but there is more than 1 page. Refreshing fixes it.  It could be some timing issue between showing the page and when we get the total number of claims in channel.

**Comment by seanyesmunt** [comment]
Fixed in #3237

**Comment by tzarebczan** [comment]
This is still happening randomly. One example I'm able to reproduce: add @JOELwindows7:a to subs, close app, reopen, and navigate to channel from sidebar.  He does have a 2nd chanenl under @joelwindows7#7, not sure if that's related to the issue here. 
 
Looks like sometimes we try to resolve the channel URL and other times not. We should not need to since the signing channel is available in the claim search response.

**Comment by tzarebczan** [comment]
This should be fixed now.
