### ISSUE TITLE
Menu bar title stuck if you navigate back

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3192]
1 ) navigate to a claim, notice title bar updates
2) click back
3) title bar stays the same

If you navigate to something new, it does update.

**Comment by tzarebczan** [comment]
Seems to happen more often now and few users have noticed. Should be a quick fix.

**Comment by dalhill** [comment]
After pulling latest master I'm not seeing the wunderbar update with the claim title.

**Comment by tzarebczan** [comment]
It's the window title, not wunderbar.

**Comment by dalhill** [comment]
@tzarebczan are you referring to this:

![image](https://user-images.githubusercontent.com/15717854/74802772-71759e00-52a0-11ea-9cba-7eb4bf208d52.png)

**Comment by tzarebczan** [comment]
Yep!

**Comment by dalhill** [comment]
It looks to be working fine, at least on my setup.

*Steps taken*
1. Click on video (title becomes video title)
2. Click back arrow (title changes as desired)

*Environment details (using master with latest commit of 022ecc1f5f65b3b81094cdb498aa8cca6613683a)*
![image](https://user-images.githubusercontent.com/15717854/74803299-fca36380-52a1-11ea-882a-bb53c580c973.png)

**Comment by tzarebczan** [comment]
Strange..I don't even see the title bar on my mac (sierra). This definitely happens on Windows/Linux. Doesn't happen on lbry.tv (in window title)

**Comment by tzarebczan** [comment]
Looks like it may have been fixed as part of your PR, no longer happening. But let's get those back/forward navigation buttons fixed :p
