### ISSUE TITLE
Make claim previews right clickable

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3200]
Hyperlinks in markdown and other places in the app should be right clickable so you can open in a new tab / copy URL.

**Comment by seanyesmunt** [comment]
The believe the fix for this is to conditionally render an `<a>` or `<Button />` here
https://github.com/lbryio/lbry-desktop/blob/master/src/ui/component/externalLink/view.jsx#L34

**Comment by tzarebczan** [comment]
This should also fix being able to right-click a video from the trending page.
