### ISSUE TITLE
Improve lbry.tv static asset caching

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#3203]
- Check all assets loaded by beta.lbry.tv to ensure they are cached and sized properly
- At a minimum, favicon.ico and the font files are not being properly cached. 
- The font files should be continued to served from dynamic URLs with `cache-control: public, max-age: <several months or a year in seconds>`
- The favicon should be checked for size/compression (168kb seems large) and served with `cache-control: public, max-age: several days`
- The font files should be put directly in `<head>` and loaded with `<link rel=preload>`. See https://stackoverflow.com/questions/42616709/preloading-fonts-in-chrome-with-preload-link-directive

**Comment by tzarebczan** [comment]
This was completed.
