### ISSUE TITLE
Too many tags - graphic problem on Publish

### ISSUE THREAD

**Issue by kodxana** [lbryio/lbry-desktop#3204]
**Bug**
When you edit claim and it have too many tags it out of the window :)

**Screenshots**

![image](https://user-images.githubusercontent.com/16674412/68621431-0877d080-04d0-11ea-9fee-7171cd656beb.png)

**System Configuration**

- LBRY Daemon version: 0.45.0
- LBRY App version: 0.37.2
- LBRY Installation ID: 7LEseQpAWJXBDuRfGh8gUVRmUGwKVgvLqybVzVwdSr6EA19bubwnAv7p3Q1RFnNpgj
- Operating system: Windows 10

**Additional context**

**Comment by tzarebczan** [comment]
![image](https://user-images.githubusercontent.com/8120721/68891705-66363380-06ef-11ea-9038-a67cc80f2875.png)
