### ISSUE TITLE
Provide Acceptable Message [  LBRY.tv is down ]

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbry-desktop#3207]
<img width="1190" alt="Screen Shot 2019-11-12 at 2 33 29 PM" src="https://user-images.githubusercontent.com/3402064/68704086-c4311280-0559-11ea-9325-70816ea51eed.png">

When LBRY.tv is purposefully down for maintenance the user should not see the above. We should show a message like "Sorry for the inconvenience, we are performing maintenance on our system, it should be back up very soon". Or something like this. @kauffj I am sure you would have a preference.

**Comment by tzarebczan** [comment]
There are now status messages
