### ISSUE TITLE
Confusing warning when deleting file but not abandoning claim in app 0.37.2-rc2

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-desktop#3232]
I started downloading a claim of mine, then changed my mind, so clicked the trash icon. I would expect that checking to delete the file but not abandon the claim would have the obvious behaviour that it has always had. However, it gave me this strange, concerning (and false?) message, so instead I used the command line to delete the file.

![image](https://user-images.githubusercontent.com/1578298/68985538-0de06c80-087c-11ea-9412-43fbff073aa2.png)

**Comment by tzarebczan** [comment]
Thanks @eggplantbren! I noticed this recently too and have a fix for it.

**Comment by tzarebczan** [comment]
Fixed in https://github.com/lbryio/lbry-desktop/pull/3234
