### ISSUE TITLE
email validation broken with uppercase letters

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3233]
If the first letter of the domain name is capitalized, it won't validate. 

![image](https://user-images.githubusercontent.com/8120721/69009926-3625a500-0928-11ea-8fa2-85f6256c1d64.png)

**Comment by seanyesmunt** [comment]
Is that a valid email?

**Comment by tzarebczan** [comment]
yep, a user ran into this and was confused.

**Comment by kauffj** [comment]
@sean I recommend dropping https://github.com/lbryio/lbry-desktop/blob/master/ui/constants/email.js

Validation already happens server-side, so there is little value in validating client side aside from UX reasons. 

If you want to do something simple to improve UX client-side, I'd reduce the regex to something like: `/^[^@]+@[^@]+$/` (there's something non-@ before an @, there's an @, and there's something non_@ after the @).

**Comment by seanyesmunt** [comment]
Changed to the simpler email regex
