### ISSUE TITLE
Page number controls sometimes missing at the bottom of channel content pages in 0.37.2-RC2

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-desktop#3235]
This report pertains to version 0.37.2-rc2.

Sometimes when using the app to browse a channel's content, the page numbers and selectors are missing from the bottom. It seems to happen randomly like some of the other similar bugs, depending on the path by which you ended up on the channel page.

Here's a screenshot of where the page numbers should be:

![image](https://user-images.githubusercontent.com/1578298/69016717-de5d6b80-0a05-11ea-8fcb-ac88c869ae45.png)

Ctrl+R fixes it.

**Comment by tzarebczan** [comment]
Thanks for filing. This is an older bug and filed under https://github.com/lbryio/lbry-desktop/issues/3188
