### ISSUE TITLE
"There's nothing at this location"/"Loading decentralized data" weird refreshing in 0.37.2-rc3 and on lbry.tv

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-desktop#3243]
Steps to reproduce: go to lbry://aslkfjksaldkfhsldfkjashlkdjfh

**Comment by tzarebczan** [comment]
Nice find, thanks for filing!

**Comment by seanyesmunt** [comment]
Fixed in https://github.com/lbryio/lbry-desktop/pull/3248
