### ISSUE TITLE
player controls / autoplay blocked when directly navigating to content

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3252]
When navigating directly to a content page with autoplay on, it may look like the video is frozen on startup. There's no video controls on mouse over, but clicking the video itself does start it (does not start work on mobile if tapped). Refreshing does not help. 

If you access the video from the channel page, it works then. Also works if autoplay is off. Seems like the browser may be blocking autoplay, which results in a bad UX. Happening in Chrome and Firefox for me.

**Comment by kauffj** [comment]
When working on this, please first ensure that the UI is clear when the video is paused, especially when auto play fails.

Ideas:
- Always show controls / play button when paused
- Revert to cover if autoplay fails
- Show cue when toggling play/pause (YouTube shows play/pause icon that fades out)
