### ISSUE TITLE
Old LBC are not claimed properly

### ISSUE THREAD

**Issue by Zettt** [lbryio/lbry-desktop#3259]
I'm using LBRY on a Mac running Catalina. Apparently I've been first installing it in 2017. The wallet page says that I have 0 LBC. However the Reward page show my "First Nickel" with the date `July 31, 2017 8:28`. I really don't know how to help you with this issue, because it is most certainly not my machine, but an issue with the blockchain(???) I suppose. Or would I need to download the blockchain again? If yes, how do I do that? I've tried deleting it from `lbryum` and making a restart, but that didn't seem to help. Do I just have to wait? If yes, how long would be appropriate? Can I check on the progress somehow? Because as far as I can tell neither the `blockchain.db` nor the `header` file is growing in size.

All I can add is that this seems to be the tx id `0d4821112eb700f6b2cd51523564b52d3bac1ea417a962a3e2ac420c267cbd04 `.

**Comment by tzarebczan** [comment]
Hey @Zettt , thanks for reaching out. Until recently, LBRY did not backup any credits/wallets for users, so it was their responsibility to do so. Unfortunately, if the default_wallet file was not backed up, these credits would be lost.  In the latest version, this would be done if you enabled (turned on by default) the sync balances setting. 

Do you remember how many credits you had? Send us an email at hello@lbry.com with your new LBC address and we'll get some over for the trouble.

**Comment by Zettt** [comment]
@tzarebczan Alright. I'll be in touch soon. Thank you.
