### ISSUE TITLE
Don't reset claim name when re-selecting a new file during an edit

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3261]
Steps: edit a claim, then reselect a new file (with a different name from the current claim name) and the claim name will update. If in edit mode, this should not happen or the user should be prompted.

**Comment by nikooo777** [comment]
from my duplicate issue: a final window with a summary of your settings should be shown (feature request I guess)

**Comment by tzarebczan** [comment]
There's a ticket filed for that.

**Comment by tzarebczan** [comment]
Fixed this, will be in next release.
