### ISSUE TITLE
"Unsupported File" message is not readable - Black on Black

### ISSUE THREAD

**Issue by 345k** [lbryio/lbry-desktop#3274]
LBRY.tv currently shows a message "Unsupported File" when it cannot view a file on the browser. The message is appearing as Black text on Black background and is unreadable.

For example, if I open [this post](https://lbry.tv/@Gutenberg:a/0042869:6) it shows the message but it is not readable.

[Screenshot](https://i.imgur.com/3dTQcCh.png)

**Comment by tzarebczan** [comment]
Thanks for filing this! Going to group these under https://github.com/lbryio/lbry-desktop/issues/3275
