### ISSUE TITLE
Add button to request manual youtube video sync

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3284]
Some YouTubers may want to request a content sync as soon as they post a video. Now there's an endpoint where they can do this manually. We should show this on the channel page or overview - it would be 1 per channel that's in `Synced` status only. The status token is available on the user me call. 

Endpoint: https://api.lbry.com/yt/ping?status_token=STATUSTOKENHERE

**Comment by kauffj** [comment]
@nikooo777 why can't we get them immediately via https://developers.google.com/youtube/v3/guides/push_notifications ?

**Comment by nikooo777** [comment]
Great one! yes this is what I think could be the real solution.
I can schedule this in my next sprint and see if it works fine for all the channels we have

**Comment by kauffj** [comment]
@nikooo777 please file and tag consider soon if you want to address it next sprint planning
