### ISSUE TITLE
Adding number of claims to channel

### ISSUE THREAD

**Issue by Blanxs** [lbryio/lbry-desktop#3291]
**Is your feature request related to a problem? Please describe.**

Number of claims should be visible inside the channel somewhere. Currently you can only see it in the search, and the channel is a result.

**Describe the solution you'd like**

Possibly located next to number of subscribers.

**Describe alternatives you've considered**

**Additional context**

**Comment by tzarebczan** [comment]
Good idea and thanks for filing!

**Comment by kauffj** [comment]
@jessopb maybe you could knock this out while working on #3185?

**Comment by tzarebczan** [comment]
This is now shown on the About page
