### ISSUE TITLE
Support : in LBRY URLs in app

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3293]
You can copy/paste an entire lbry.tv url into wunderbar, but you can't past something like `Mt-Talbot-Small-Painting---Painting-Demo:e` . Does this require a bigger discussion around supporting : on the SDK or just fix it on the apps for now?

**Comment by eggplantbren** [comment]
This page seems to suggest that `:` has another meaning, or will have in the future, and that `$` will as well.

https://lbry.tech/spec#url-resolution-examples
Am I wrong/confused?
