### ISSUE TITLE
audit selectable languages against sdk types

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3298]
Some languages, like jp, fail when trying to publish. The language must be in https://github.com/lbryio/types/blob/master/v2/proto/claim.proto#L115 and conform to ISO 639-1

**Comment by jeffslofish** [comment]
I'll take a look

**Comment by jeffslofish** [comment]
All 184 languages with a two letter code (as documented here: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes#Table_of_all_possible_two_letter_codes) are accounted for in https://github.com/lbryio/types/blob/master/v2/proto/claim.proto#L115. 

However, https://github.com/lbryio/lbry-desktop/blob/master/ui/constants/languages.js is missing two languages: ae and nb and has two extra languages which are deprecated: mo and sh.

The supported languages list (https://github.com/lbryio/lbry-desktop/blob/master/ui/constants/supported_languages.js) is much shorter and only includes 29 languages: cs,da,de,en,es,fr,gu,hi,hr,id,it,jv,kn,ml,mr,ms,nl,pa,pl,pt,ro,ru,sk,sr,sv,tr,uk,ur,zh. 

Also, jp is not an officially assigned language code according to the ISO table. Do you mean ja (Japanese)?

**Comment by tzarebczan** [comment]
We now link these with the supported app languages. If a language is missing, it needs to have a translation added first.
