### ISSUE TITLE
Changing claim name of an already published claim disables the publish button

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry-desktop#3301]
I went on to edit the claim I had just published to adjust the claim name. I understand that isn't possible, so perhaps that field shouldn't be shown or should be disabled for already published claims with some sort of explanation

**Comment by tzarebczan** [comment]
There's already a warning about this but I guess we can make it clearer. A common use case would be starting with an existing claim and using the metadata to create a new one.

**Comment by tzarebczan** [comment]
We now grey out the name while in edit mode.
