### ISSUE TITLE
When editing your channel, clicking a subscribed channel results in a display error.

### ISSUE THREAD

**Issue by kcseb** [lbryio/lbry-desktop#3306]
**Bug**
When you are editing your channel and click a channel that you are subscribed to (on the right-hand side), it will result in some wonky behaviour, displaying whatever channel you clicked on instead of yours at the top. 

**To Reproduce**
1. Go to a channel that you have claimed
2. Click on the edit button
3. Click on a channel you are subscribed to. 

**Expected behavior**
This should prompt you to either save your changes or discard them, OR just simply take you to the channel that you clicked. 

**Screenshots**
GIF Showing the Bug: https://i.imgur.com/aV04lG5.gif

**System Configuration**

- LBRY Daemon version: 0.46.1
- LBRY App version: 0.37.2
- LBRY Installation ID: 2TxtRu7JxCpVxNF572y4tir3kiiH3ni5djXhQo9CTzY2V7vAPB94cEd3cBeSaaKDJu
- Operating system: Windows 10

**Comment by ProfessorDey** [comment]
Can confirm this does occur on my EndeavourOS Linux install (Arch derivative), kernel 5.3.12-arch1-1.

**Comment by seanyesmunt** [comment]
Thank you for the solid bug report. Should be simple to fix.
