### ISSUE TITLE
Warn users of file size limits on web version

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry-desktop#3310]
Trying to upload a file that is too big for lbry.tv fails, however there are no warnings nor errors when the file is selected.
A warning should be displayed and an error shown if someone selects a big file.

**Comment by tzarebczan** [comment]
This broke recently, I had added it to https://github.com/lbryio/lbry-desktop/issues/3275

**Comment by tzarebczan** [comment]
We should warn even before hand.

**Comment by tzarebczan** [comment]
This is now shown on the publish page.
