### ISSUE TITLE
Settings V2 reorganization for preference flow and simplicity

### ISSUE THREAD

**Issue by jessopb** [lbryio/lbry-desktop#3328]
To improve ease of preference sync, redesign settings reducer.

move settings constants to lbry-redux
separate client_settings into local_settings and shared_settings 
preference sync shared_settings
implement preference store and populate for daemon_settings
update necessary selectors throughout the app

**Comment by tzarebczan** [comment]
Many users complain about losing various settings when local app data is wiped out and between app instances. Should consider Android settings too.
