### ISSUE TITLE
Video Freezes during full screen mode

### ISSUE THREAD

**Issue by franny23dmt** [lbryio/lbry-desktop#3339]
LBRY desktop freezes  regularly,  usually 2-10 mins into it.  Have to kill process & restart to use LBRY again.   Video frame remains visible & audio continues playback 

Ubuntu 16.04 
 i7-4820K CPU 
16 Gb RAM

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble and thanks for filing the issue. So this only happens when the video is in full screen mode? Any lock ups when it's not or during other activities?

**Comment by franny23dmt** [comment]
oh sorry, I must not have saved the update edit i made ... it happened during normal mode (not fullscreen) 5 mins after posting this. 
  **edit** actually, the message body did save but the thread title didn't, not sure why? 

Chromium freezes for videos & also one of the forks of Chromium, Dissenter browser. When that happens, I have to use my computer's reset button & reboot to use computer again.  (not even Terminal keybindings loads Terminal )  These Chromium freezes are much less frequent, every few days it seems. 
Audio also continues during these freezes, but stops at what seems to be the end of the loaded cache.   I will leave LBRY running next time to see if audio stops eventually.   
No freezes during any other activity, only streaming video.

**Comment by tzarebczan** [comment]
Thanks so much for the feedback! So it sounds like you have similar issues in other browsers? 

In the meantime, maybe you can use lbry.tv instead if the desktop app keeps freezing more often.

**Comment by tzarebczan** [comment]
Sounds like a local issue, closing for now.
