### ISSUE TITLE
Brightness and Contrast

### ISSUE THREAD

**Issue by tuxfoo** [lbryio/lbry-desktop#3349]
**Bug**
Brightness and Contrast in the LBRY client are incorrect. This is effecting both the light and dark modes. The videos, thumbnails and everything else are dim.

**Screenshots**
In the following screen shots I compare the LBRY client to lbry.tv in Firefox.
![screen2a](https://user-images.githubusercontent.com/1560023/70499493-22174100-1b7e-11ea-82fb-f0374b59061b.jpg)
![screen1a](https://user-images.githubusercontent.com/1560023/70499499-22afd780-1b7e-11ea-8261-6f0e309bc145.jpg)

**System Configuration**
Ubuntu 19.10
LBRY 0.37.2

**Additional context**
This issue may have occured as a result of upgrading from Ubuntu 18.04 to 19.10. I tried changing the themes in gnome tweaks but it had no effect.

**Comment by tzarebczan** [comment]
Thanks for reaching out! We recently pushed out a redesign on lbry.tv but it hasn't made it into a desktop app update - that's probably the discrepancy you are seeing. It should be out later this week.

**Comment by tuxfoo** [comment]
> Thanks for reaching out! We recently pushed out a redesign on lbry.tv but it hasn't made it into a desktop app update - that's probably the discrepancy you are seeing. It should be out later this week.

That would account for the different colors, being a electron app the CSS for lbry.tv might be different.
How ever, I do not think that would account for the dark videos and thumbnails.

The issue with the videos and thumbnails has gone away, it might be because I restarted my computer.

**Comment by kauffj** [comment]
The CSS is the same. @tuxfoo it looks like you're an active dev, if you want to contribute to LBRY it's pretty easy to get started: https://lbry.tech/contribute

**Comment by tuxfoo** [comment]
This issue seems to be reoccurring.

**Comment by tuxfoo** [comment]
Launching lbry with the following argument fixes the issue. The colours will then be correct and the videos are no longer dim.
```
-force-color-profile
```

The bug appears to be in electron.
https://github.com/electron/electron/issues/10732
