### ISSUE TITLE
Add uptime monitoring for lbry.tv

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#3352]

**Comment by kauffj** [comment]
@nikooo777 did you do something basic for this? Can you? This would be for both lbry.tv web server itself and api.lbry.tv.

**Comment by nikooo777** [comment]
@sayplastic do you have an API endpoint that I can query (GET) to retrieve the status?

**Comment by sayplastic** [comment]
No but there's [an issue for that](https://github.com/lbryio/lbrytv/issues/124), I'll do it in the course of cluster deployment effort.

**Comment by kauffj** [comment]
Handing this ticket over to the people actually doing the work. No @lbryio/appsquad members are working on this. Ideally, there would be an endpoint (separate?) that lets us simply check if lbry.tv "should" be working, so we can direct to static page when down and prevent full app from loading and breaking.

**Comment by lyoshenka** [comment]
@sayplastic saw you just merged the status endpoint PR. are you handling this issue? is there anything i can contribute?

**Comment by sayplastic** [comment]
I created an endpoint for @nikooo777, I think he will take it from here. Let me know if any improvements are needed.

**Comment by nikooo777** [comment]
As mentioned on slack, i can only do string matching from uptimerobot
id appreciate if you could add a top level key that reports the general status:
if everything is "ok" then just have it report:

`"general_state": "ok"`

**Comment by andybeletsky** [comment]
Status endpoint is ready: https://api.lbry.tv/internal/status

**Comment by kauffj** [comment]
@andybeletsky should lbry.tv be updated so that when `general_state` != `ok`  we should display an alternative/status/issue page? If not that specifically, can you clarify how endpoint could/should be used?

**Comment by andybeletsky** [comment]
The idea was to integrate this into https://status.lbry.com — @nikooo777 is on it I believe.

There's nothing stopping us from displaying this somewhere in the UI of lbrytv. We can even display it in case of SDK troubles on the instance the current user is on but it will require more work from the app team.

**Comment by kauffj** [comment]
First step is for @seanyesmunt to display indicator (nag? but different color) when performance is degraded. Then assign back to @andybeletsky for further development.
