### ISSUE TITLE
better handling of markdown content

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3373]
See https://lbry.tv/@lbry:3f/Nov-2019-CommunityUpdate:6

Compare to: https://lbry.com/news

- [x] heading sizes seem wrong
- [ ] links should open in new window
- [ ] we have anchors {#updates} in sections, but they would just be rendered as text (removed at the moment) 
- [x] better image sizing?

**Comment by jsigwart** [comment]
additional css changes for class "markdown-preview":
[ ] fix padding or margin between elements
[ ] add padding below </ul>
[ ] p text is larger than h2
[ ] spacinig between li elements seems a bit large
