### ISSUE TITLE
video length and tag cut off

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3374]
lbry://@FredBouchal#e

![image (19)](https://user-images.githubusercontent.com/8120721/70838271-76682e00-1dd5-11ea-868f-548204386be8.png)

**Comment by myungwoo-Y** [comment]
Hi, I interested in this issue. 
Can I work on this issue?

**Comment by tzarebczan** [comment]
Sure, take a look! Also, see https://lbry.tech/contribute

**Comment by Ruk33** [comment]
Hello, I would like to help in this issue although it seems it has already been solved. The duration of the video now appears on the video thumbnail, is this correct?:

![image](https://user-images.githubusercontent.com/1719111/90048389-d6d3a600-dca9-11ea-82c1-3c29a4d8feec.png)

Regards.
