### ISSUE TITLE
Share experience 2.0

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#3390]
Our share dialog has slowly improved from moderate to a slightly better version of moderate.

### Ideas for changes
- Options for sites other than facebook/twitter
- Analytics event for opening the share dialog, and another if they copy the text/click a buttton to get some rough stats for people that actually share after opening the modal.
- Direct content link (embed link minus the html)

**Comment by kauffj** [comment]
Great ideas!

**Comment by jsigwart** [comment]
UX fix: We need to provide the correct links to match the type of content. Right now, if you view a STL (3D) file in the desktop app, and you click "Share," you get this link: https://open.lbry.com/@GRAVITYSHAPES:f/stl:b

That automatically opens the web and tells you that you need to view the file in the desktop app.

**Comment by kauffj** [comment]
Download links are coming soon enough that I think we can just fix the unsupported file UX fundamentally rather than work around it in share dialogs.

**Comment by tzarebczan** [comment]
Direct link would definitely be needed for non-video content
