### ISSUE TITLE
Add comments notification

### ISSUE THREAD

**Issue by auber262** [lbryio/lbry-desktop#3401]
**Is your feature request related to a problem? Please describe.**
I never know when anyone has commented on one of my videos. It makes sense to factor in an email (or push notification on the android app) when comments get made so responding to the comment doesn't get missed.

**Describe the solution you'd like**
For desktop an email, sent according to the user-defined time frame (once a day/week/month) that summarised the posts that comments have been made. If no comments, no email is sent.

For the desktop, perhaps a visual indicator that there is a comment on the publishes page.

**Describe alternatives you've considered**
Emails work well for the desktop version but push is better for android app.

**Additional context**
This came about as I missed someone making a nice comment and wanted to thank them - the only way I found it was when I had to revisit the video to do an edit and realised there was a comment there.

**Comment by tzarebczan** [comment]
Thanks for opening the issue Mark! We've got this feature request filed under https://github.com/lbryio/lbry-desktop/issues/695 - first we need a framework for notifications in general. As I mentioned on Discord, we may roll out email notifications beforehand.

**Comment by auber262** [comment]
ah ok cool - I did have a look through to make sure it hadn't already been logged. Must have missed it in the 14 pages of items ;-)!
