### ISSUE TITLE
setting option to disable run at bootup

### ISSUE THREAD

**Issue by Goddard** [lbryio/lbry-desktop#3410]
I open the app on linux i downloaded from flathub and it doesn't give me any option to disable run at startup of OS.

it also doesn't even show up in gnome tweaks startup applications.

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. Do you not see the startup config in Settings? 

Maybe it doesn't work with the flatpak?

**Comment by Yamboy1** [comment]
@Goddard Are you on version 0.37.2?

**Comment by Goddard** [comment]
Yes.  It is a flatpak.

**Comment by Goddard** [comment]
I just got an update request, but in the app it says I need to input a command myself of - sudo dpkg -i /tmp/Oati9l/LBRY_0.38.0.deb

Only problem is it is a flatpak so the path is wrong I think.  It is sandboxed right?

Any way the command doesn't work because the file doesn't exist.

**Comment by tzarebczan** [comment]
You'll need to wait for the flatpak to be updated, we don't support in app updates for flat pak at this time. You can ignore the upgrade message until then.


Please let me know if you were able to find the startup setting and if it works.

**Comment by Goddard** [comment]
No sir, I cannot find it.  Perhaps you can tell me the location it should be?

**Comment by tzarebczan** [comment]
If you scroll down in settings, do you see 
![image](https://user-images.githubusercontent.com/8120721/71311690-5fd26000-23ef-11ea-9ba7-0b648c3e5099.png) ?

**Comment by tzarebczan** [comment]
Closing for now, let us know if that's not in the app or doesn't work with the flatpak.
