### ISSUE TITLE
Ability to remove videos while on the Library page itself

### ISSUE THREAD

**Issue by walidmujahid** [lbryio/lbry-desktop#3416]
**The Problem**

Earlier today, I forgot how to remove videos from the Library page. Usually, when I am done, I simply delete video files through the file manager -outside of LBRY. 

I use the Library page more as a bookmarks or playlist of videos I may want to watch again, or videos that take too long to download and want to watch later after I forget about them. If I do not remove some videos from the Library list internal to LBRY desktop, then it becomes a useless list of history to me.

So, in order to figure out how to delete a video, I was looking through the settings and even help page. It was only when I was watching a video that I noticed something strange. A disposables bin icon under the video. My first thought was actually "Wait, I can delete other people's videos?"

It was when I saw the tooltip that I remembered that, I am pretty I faced this problem before. 

I also do not want to click and go the pages of each previous video I want removed in order accomplish the goal of removal from the list.

**Preferred Solution**

Add a small red button with "remove" actually typed out as an option to each video in the list in Library page. 

**Alternative Solutions**

- A disposables bin -rubbish bin? trash bin?- icon could also work as it would have more context on this page to be clear along with this page being the more more obvious place to remove videos from.
- Removing the video from the Library when the file is deleted outside of LBRY Desktop. But this is horrible as I actually see the video list.
- Turn the Library page into a list of "playlists", have a default Watch Later and History playlists with the History playlist having a simply button to clear all videos in it. Of course, under each video, you have the option to add it to a certain playlist or create a new playlist to add the video to -like YouTube.

**Additional context**

The Library should be the logical first location that people would find a way to from which to remove **previous** videos:

![0](https://user-images.githubusercontent.com/1489224/71310662-9c4c8e80-23e4-11ea-8a41-f2be44724877.png)

**Comment by tzarebczan** [comment]
Thank you for the write-up and suggestions. We have something along these lines under https://github.com/lbryio/lbry-desktop/issues/1394

The playlists feature is a separate issue as well.

**Comment by walidmujahid** [comment]
@tzarebczan Is there a feature request for playlists? Or were just mentioning that it was really irrelevant to the issue I was bringing up?

Thank you providing a link to #1394. I will go comment under it.

**Comment by tzarebczan** [comment]
Yep, https://github.com/lbryio/lbry-desktop/issues/1982

**Comment by walidmujahid** [comment]
@tzarebczan Thanks!
