### ISSUE TITLE
Add analytics event for video buffering

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#3421]
We want to know when a video starts playing but stops.

**Comment by kauffj** [comment]
@sayplastic we're going to tackle this this week - is there anywhere you want this logged specifically for lbry.tv?

**Comment by sayplastic** [comment]
What metrics are available, apart from the obvious time into stream/duration?

I would like to have as much data as possible, but prometheus is poll-based so I will need to implement some kind of collector endpoint on the lbrytv API side.

**Comment by seanyesmunt** [comment]
@sayplastic We could easily send these (probably more too but this was the first thing I saw

```
secondsToLoad: Total amount of time in seconds buffering took
bufferCount: Total buffer events for this source
```

**Comment by seanyesmunt** [comment]
@sayplastic we are now sending events to GA for video buffer events. Once there is an api set up on your end we can send anything you want.
