### ISSUE TITLE
Channel headline overlaps other elements

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry-desktop#3426]
**Bug**
The h1 on a channel overlaps the Share/Tip/Support/Follow/Block controls above it. See screenshot. I can't click on any of them.

**Screenshots**
<img width="1168" alt="Screen Shot 2019-12-27 at 11 10 53 PM" src="https://user-images.githubusercontent.com/1363664/71540381-6afd2280-28fe-11ea-99e2-ca2ed58b8e5f.png">

**System Configuration**

- LBRY Daemon version:
- LBRY App version: LBRY.tv on Chrome
- LBRY Installation ID:
- Operating system: Mac OS 10.14.6

**Comment by seanyesmunt** [comment]
this is now fixed
