### ISSUE TITLE
Feature request: Search order by date + normal links (to open in tabs)

### ISSUE THREAD

**Issue by lrq3000** [lbryio/lbry-desktop#3428]
First off, amazing project! I'd like to propose 2 enhancements for the user interface on the web app lbrytv:

1. When doing a search, old and new videos are mixed up. Would be nice to allow to order by "most recent" or "most pertinent" (current default?).
2. The lists of videos are not displayed as normal links, so it's not possible to open multiple videos in tabs. That's a very important feature for most "seasoned" youtube watchers.

**Comment by tzarebczan** [comment]
Hey @lrq3000 , thank you for opening this issue and checking out LBRY! Our main repo for these types of issues would be under https://github.com/lbryio/lbry-desktop 

We've got the first feature request filed under https://github.com/lbryio/lbry-desktop/issues/2163

2nd under https://github.com/lbryio/lbry-desktop/issues/3200
