### ISSUE TITLE
Error When Running io.lbry.lbry-app

### ISSUE THREAD

**Issue by bradfonseca** [lbryio/lbry-desktop#3430]
Hello,

I'm running flatpak 1.4.1 on Mageia Linux 7. I have installed the app as per the given directions [(https://flathub.org/apps/details/io.lbry.lbry-app)](https://flathub.org/apps/details/io.lbry.lbry-app):

> Command line instructions
Install:
Make sure to follow the setup guide before installing
flatpak install flathub io.lbry.lbry-app
Run:
flatpak run io.lbry.lbry-app

When I attempt to run the app from the command line I get the following:

`$ flatpak run io.lbry.lbry-app`
`/app/bin/lbry-app: line 2: /app/lbry-app/lbry-app: No such file or directory`

What am I doing wrong?

Thanks,

Brad

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. Maybe @kcseb has some ideas here on what might be wrong. I assume you followed the flatpak setup guide?

**Comment by kcseb** [comment]
Hey there, Brad. Sorry to hear about this. We are aware of the issue regarding Flatpak and will be reverting the Flatpak version to the last known working version of LBRY (0.37.2) ASAP!

**Comment by bradfonseca** [comment]
Okay, I've uninstalled the app on my system. Please let me know when I should try to install again.

**Comment by kcseb** [comment]
@bradfonseca - This is to be considered resolved as per pull [49](https://github.com/flathub/io.lbry.lbry-app/pull/49)

**Comment by kcseb** [comment]
Reminder - Please close all issues that are solved. Thank you! @bradfonseca

**Comment by tzarebczan** [comment]
Thanks again @kcseb !
