### ISSUE TITLE
Redirected to Nothing

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry-desktop#3451]
After the [video](https://lbry.tv/@artiintel:e/Internet-GOD:a) I was watching finished, the auto play next item, redirected to nothing with the following [URL](https://lbry.tv/internet-god-by-arti-intel:0b39c287a1953f34127a5b53b8b8071fe8cc7c54).

I pressed the spacebar on the empty page and the previous video started playing.
The video remains playing when navigating back and forth from the empty URL.

[See video screen capture here](https://spee.ch/6/navplay)

![image](https://user-images.githubusercontent.com/29914179/71865715-67b03500-314f-11ea-99f1-f726b0393391.png)

**Comment by tzarebczan** [comment]
Looks like an abandoned URL that's not shown, will check it out. Either a chainquery or lighthouse issue.

**Comment by tzarebczan** [comment]
This should no longer occur.
