### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by earthjeffone** [lbryio/lbry-desktop#3454]
Greetings,

Nice job on the software thus far. I have been playing with the app for a few days and wanted to give some feedback/ glitches.

It is true we need to redesign the protocol layers of the web to facilitate a healthier ecosystem.

Functional stuff,
OS: MACOS 10.13.6
Large Monitor: (The App looks great but there needs to be more size give the thumbnails when searching for content on a larger screen)
latest version of lbry

issues: 

After the app has been open for awhile, it will tend to hang up, refuse to return search results and require a restart, Forcing a Reload from developer tools is ineffective. a couple of times the app froze on startup, though mostly it starts okay! The fractal is too intense on a large screen, something more serene would be nice

Make explicit to the user, the idea around mirroring content, I need a way to easily remove videos I may have downloaded that I am uninterested in mirroring. This is especially important for users of limited resources or accidental hosting of illegal content.

  Allow people  to offer monetization for hosting of content. For Example, I am a channel owner and I want my content to be reliably available, I can offer .001 LBC for a host to mirror my content, it is a way for users with resources to organically increase the global access to their content, as well as a way for users to offer a service to the network, and be rewarded, which can also lead to greater engagement with the environment. 

At present I can only block a channel, I would like to be able to block individual videos, which would also block any content that particular channel. Give the user as many tools to remove the ugly.

Lots of other ideas for another time. Feel Free to ask any follow up questions. 

Have a good one

Thanks,

Jeff

**Comment by tzarebczan** [comment]
Thanks for the feedback! The fractal can be disabled on startup if you don't enjoy it. 

As far as the freezing, we haven't seen this locally but will keep an eye on it. Let us know if it happens in any particular cases, etc. 

You can remove content from the Library page > clicking an item > trash can icon, we have a  separte feature request filed for making this possible in batches. 

Data hosting fees is something we want to do down the road, we have a feature request filed fro this on lbry-sdk. 

Blocking improvements are also part of a separate issue that's filed. 

Can we show you some [appreciation for the feedbacl](https://lbry.com/faq/appreciation)?
