### ISSUE TITLE
https://lbry.tv/@çokkomik - url won't load, too many redirects

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3464]
This page isn’t workinglbry.tv redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

**Comment by Yamboy1** [comment]
Can't reproduce. Just says `There's nothing available at this location.`

**Comment by tzarebczan** [comment]
He deleted it, but you can try creating the same channel name

**Comment by infinite-persistence** [comment]
Can't reproduce with today's lbry.tv.  Seems to load ok.

**Comment by seanyesmunt** [comment]
Seems to work for me too. Closing this.
