### ISSUE TITLE
hyperlinks should open in new tab

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3467]
When clicking a hyperlink in descriptions or on markdown files, it opens in the same window.

**Comment by bitcoinbrisbane** [comment]
Opens in a new tab for me
- FireFox
- Ubuntu Desktop 19.10

**Comment by jeffslofish** [comment]
I'm looking into this issue now.

**Comment by tzarebczan** [comment]
Thanks for chiming in on a few issues @bitcoinbrisbane ! Can we [show you some appreciation](https://lbry.com/faq/appreciation) ? 

This will be fixed once https://github.com/lbryio/lbry-desktop/pull/4111 is merged.

**Comment by bitcoinbrisbane** [comment]
> Thanks for chiming in on a few issues @bitcoinbrisbane ! Can we [show you some appreciation](https://lbry.com/faq/appreciation) ?
> 
> This will be fixed once #4111 is merged.

Sounds good!  I hope to make some code contributions soon, but keep getting beaten!
