### ISSUE TITLE
Request: cross-platform portable AppImage build.

### ISSUE THREAD

**Issue by Tcll** [lbryio/lbry-desktop#3469]
Hello :)
I'd like to make a request for an AppImage binary that can be run from a flash drive or separate hard drive on almost any Linux or BSD machine.

I've been moving away from debian-based distros because of systemd, and building is rather cumbersome.
(I run Void Linux and OpenBSD myself)

Flatpak and Snap are alternatives, but they're not as portable and can't be run from anywhere like AppImage can.

Extra info:
I'd just recently found out you can run AppImage even on BSD as long as the base dependencies are satisfied :)

hopefully this request helps reach out to a much larger audience rather than being dependent on apt. ;)

**Comment by tzarebczan** [comment]
Thanks for opening the issue. You can see the previous discussion here: https://github.com/lbryio/lbry-desktop/issues/953

Try out this build: https://build.lbry.io/app/build-9009_commit-7b07b3e/electron/LBRY_0.38.2.AppImage 

It is still really clunky that you need to set as executable IMO, which is the main reason we haven't provided it. Hopefully, that support improves. May not work on all systems due to the dependency on keytar/keyrings.

**Comment by Tcll** [comment]
thanks :)
though just before I download and give it a try, I wanted to note there's been a few appimages I've downloaded I haven't had to set perms for, I think nextcloud and keepassxc are a few, utox might be another but I could be wrong there.

point be made, yeah you can set the perm before release, it's just only recommended that you don't for extra security reasons. ;)

also I want to add, it is usually noted that you'd have to set the perm regardless
especially if there's an explicit download page for it, so it's kinda common knowledge at this point ;)
(I'm aware there are users who ignore everything and complain when they find out they have to set it)

**Comment by cmatomic** [comment]
Does not start on Ubuntu 16.04 xenial lts, when new version off this appimage  should mention which GNU / Linux distributions the appimage supports
exemple:
https://github.com/cmatomic/VLCplayer-AppImage

`  ./LBRY_0.38.2.AppImage
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /tmp/.org.chromium.Chromium.sjq4aE: nÃ£o foi possÃ­vel mapear segmento apartir de objecto partilhado
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:169:18)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/tmp/.mount_LBRY_0rVnqQH/resources/app.asar/node_modules/keytar/lib/keytar.js:1:169)
    at Object.<anonymous> (/tmp/.mount_LBRY_0rVnqQH/resources/app.asar/node_modules/keytar/lib/keytar.js:61:3)
  `

**Comment by Tcll** [comment]
@cmatomic that's weird, but I suppose I can add and confirm it works just fine on Xubuntu 16.04

I haven't been able to test on Void or anything else yet because I've been having issues with my subnet PC (home-built router)
(I'm not lying, just none of my PCs on my subnet have internet, so testing is kinda pointless)

crypt_luks is quite finicky when the OS you're installing doesn't support booting from it :D

**Comment by seanyesmunt** [comment]
added in https://github.com/lbryio/lbry-desktop/pull/3497!

**Comment by xliiv** [comment]
For subscribed to this thread BSD users:

Not sure how you run AppImage, but it's possible to run LBRY-Desktop via emulators, see
https://github.com/lbryio/lbry-desktop/issues/1961#issuecomment-920300261
