### ISSUE TITLE
Warn if Data Rate is Below the Recommended.

### ISSUE THREAD

**Issue by Invariant-Change** [lbryio/lbry-desktop#3471]
For video files, a informational notice could be displayed if the data rate is higher than the recommended.

Using using a file size and video length calculation, the app could warn if the data rate is below the recommended for streaming, with a orange caution icon along with a short sentence saying something along the lines of. 

> This video's has a higher than recommended data rate. You may experience some streaming issues.

This would help people understand why the video isn't streaming well and help prevent people blaming the app and moaning about it all over social media and YouTube.

**Comment by tzarebczan** [comment]
We'll be introducing a way for users to opt into transcoding. We don't have information about bitrates int the files, only size / width / height.
