### ISSUE TITLE
Navigate forward/backward multiple pages

### ISSUE THREAD

**Issue by seanlis** [lbryio/lbry-desktop#3474]
**Is your feature request related to a problem? Please describe.**
Each time the forward/backward button is clicked, you move one page forward/backward. One might need to click multiple times to reach the desired page.

**Describe the solution you'd like**
As in chrome or firefox, when right-click the forward/backward buttons, display the browsing history from which you could select the page you want.

![image](https://user-images.githubusercontent.com/7328445/72200012-140b5780-347f-11ea-85f6-0aaed6640919.png)

**Comment by tzarebczan** [comment]
Thanks for the feature suggestion!

**Comment by dalhill** [comment]
I'll give this a shot

**Comment by seanyesmunt** [comment]
Added in #3547!
