### ISSUE TITLE
local video quality transcoding

### ISSUE THREAD

**Issue by Tcll** [lbryio/lbry-desktop#3478]
since LBRY is basically a local video player, the option to transcode a lower quality copy for potato PCs like mine would really help.
(I have the HDD space for it, along with seeding other videos)
essentially this allows YT-like transcoding functionality where peers can seed lower quality versions of videos.

my issue and why I need it:
anything above 720p_30 is almost unplayable for me with the cruddy web-based ffmpeg decoder LBRY uses.
(I have YouTube locked to 480p since you can't specify 720p**_30**)

here's my CPU use just playing a video (downloaded prior to watching) through LBRY:
![LBRY CPU](https://user-images.githubusercontent.com/773959/72219831-69477780-3518-11ea-9d68-c8df6b6ef6b4.png)
the experience is slow motion video with normal audio which cuts and loads every 5 seconds to align the video to the audio.

if the video is paused, the CPU use drops to around 2%:
![CPU](https://user-images.githubusercontent.com/773959/72220271-fab8e880-351c-11ea-8377-a47aa3879886.png)

however when I view the same video in SM Player, I have no issues playing it, and the CPU use is quite low:
![SMPlayer CPU](https://user-images.githubusercontent.com/773959/72219887-fbe81680-3518-11ea-86fc-b94fce585655.png)
of course, with SM Player, I can watch up to 4k_60 with no problem.
(that even beats VLC which is worse than the web decoder)

my CPU is a trash-picked potato Atom D2550 with HT disabled for performance

not sure if there's anything you guys can do to improve performance (and security) aside from rebuilding the app in C/++
ditching the cruddy web decoder in the process ;)

EDIT:
labels for the bars in my images:
core0 | core1 | RAM | swap | download | upload

**Comment by tzarebczan** [comment]
Thanks for opening the issue and the feedback. I don't think there's much we can do with low powered hardware. We will be introducing a setting to transcode on upload soon, which may help in some cases. We do not and probably won't transcode while playing anytime soon, but we'll consider this in the future.
