### ISSUE TITLE
Language of post reverts back to English on edit

### ISSUE THREAD

**Issue by auber262** [lbryio/lbry-desktop#3479]
**Bug**
If I create a post that is, for example, in Spanish (my default language being set as English), it is fine to set the Spanish language of the post but if I need to edit the title or something about that post, it reverts back to the default language (for me English) without editing that aspect.

E.G - I made some Spanish language graphics. Made the new post and selected Spanish as the language. I noticed a typo after it was published so edited it but it then also automatically changed the language of the post to English and did not retain the Spanish setting.

**To Reproduce**
1. Create a new publish and make the language for another language, not yours.
2. Publish
3. Once live, then edit it - perhaps there is a typo in the description. 
4. If you scroll down to the language selector before republishing you will see it has reverted to your language and has not retained the original chosen.

**Expected behavior**
It should retain the language you set when you post.

**Screenshots**

**System Configuration**

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Additional context**

**Comment by Yamboy1** [comment]
Gonna do this issue :wink:

**Comment by auber262** [comment]
Cool. Let me know when you would like me to test. Cheers.

**Comment by Yamboy1** [comment]
Made PR: #3481
