### ISSUE TITLE
Translations missing in app

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry-desktop#3480]
Many of the strings on the Rewards page have not been translated including:
- Referral section
- Channel subscriber rewards
- View rewards
- Daily Watch Reward

There may be others, but those are the ones I'm seeing.

**Comment by seanyesmunt** [comment]
Specifically for rewards, since those strings are set on internal-apis, we would need a way to pass the current language to the `reward/list` call. And have the api return translated strings.

**Comment by kauffj** [comment]
Closing in favor of https://github.com/lbryio/internal-apis/issues/1186
