### ISSUE TITLE
[Linux][Kubuntu] Sign in does not work or respond on desktop app.

### ISSUE THREAD

**Issue by iverik-no** [lbryio/lbry-desktop#3483]
When trying to log in to my account, via the desktop app, entering account email and clicking Continue, the button just greys out, and nothing further happens. I've tried moving directories from my laptop, but no success.

I'm currently signed in on my laptop (for some reason that worked. Several months ago, though), but I can't log in on my desktop.

Kubuntu 19.10 (KDE) with backports, on both desktop and laptop.

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. This is related to a keyring dependency. We're looking into removing it soon, but in the meantime, you can try this appimage: https://build.lbry.io/app/build-9009_commit-7b07b3e/electron/LBRY_0.38.2.AppImage
