### ISSUE TITLE
Improve UX for CSV for tags

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry-desktop#3489]
https://www.reddit.com/r/lbry/comments/eo8huv/100k_youtuber_trying_out_lbrytv_some/

8. Using carriage returns rather than commas to separate the tags means you can't copy and paste plain text to populate the tags, like you can with YouTube and Vimeo.

**Comment by tzarebczan** [comment]
This is possible today, but the UX is not clear.

**Comment by tzarebczan** [comment]
It's clearer now - we show the list with the + button.
