### ISSUE TITLE
Choosing Same File Twice in Publish Form

### ISSUE THREAD

**Issue by dalhill** [lbryio/lbry-desktop#3490]
**Bug**
1. Unable to select the same file multiple times in a row from the publish form.
2. Unable to select the same thumbnail multiple times in a row from the publish form.

**To Reproduce**
This applies to both the upload file and the upload thumbnail
1. Navigate to publish form
2. Choose a file to publish
3. Clear the form
4. Choose the same file from step 2 (won't work)

**Expected behavior**
When following the steps above, a user should be able to successfully complete step 4.

**Screenshots**
![publish](https://user-images.githubusercontent.com/15717854/72317684-a66a5180-365f-11ea-8bdb-cebdda60d654.png)

**System Configuration**
![image](https://user-images.githubusercontent.com/15717854/72317601-6acf8780-365f-11ea-9e05-160ac2b1d25f.png)

**Comment by tzarebczan** [comment]
Nice catch!

**Comment by Yamboy1** [comment]
It looks like when you try to clear the file input with `clearPublish`, you don't actually clear the internal file input. If the file input is given the same input twice, it ignores the second one, and that's what is happening here

**Comment by Yamboy1** [comment]
Should probably close this issue now @tzarebczan

**Comment by tzarebczan** [comment]
Thanks !!
