### ISSUE TITLE
Add like and dislike buttons

### ISSUE THREAD

**Issue by paju1986** [lbryio/lbry-desktop#3491]
For more feature parity with youtube and other platform it will be good to implement the like/dislike buttons.

I could serve as well as a search filter, like only search videos with N* likes etc...

**Comment by tzarebczan** [comment]
Thanks for the feature request, we will not be keeping track of this data. LBC are used in the LBRY economy and recommendation engine to determine quality of content. We'll expose this more as well as other ways users can determine what's reputable.

**Comment by snakyjake1** [comment]
Since I cannot vote using LBRY, I switch to Odysee to vote.
