### ISSUE TITLE
Clicking space in full screen to pause minimizes video (firefox only?)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3498]
If you full screen a video and click space, the full screen mode ends. Seems to happen on Firefox and not Chrome.

**Comment by Meantub** [comment]
This happens because when you click the full screen button it receives focus for the keyboard. Kinda like when you click into a textbox it focuses it. So when you press space it presses the full screen button again, minimizing the video.

**Comment by dalhill** [comment]
I'll look into changing the focus from the full-screen button after the user presses it initially. This should cause Firefox to act more like chrome. The current Firefox behavior does seem a little buggy.
