### ISSUE TITLE
Support drag-and-drop file publishing

### ISSUE THREAD

**Issue by ghost** [lbryio/lbry-desktop#350]
## The Issue
On Publish, dragging a file you want opens the file inside the electron app rather than into the file selection box, subsequently requiring app closure to reset.
### Steps to reproduce
1. Go to Publish
2. Drag/Drop the file you're going to publish from desktop into "Choose a file" field
3. View result

### Expected behaviour
Queue up file selection for upload

### Actual behaviour
File playback

## System Configuration

 

- LBRY Daemon version:
- LBRY App version: 13.0
- LBRY Installation ID:
- Operating system: Mac OS

**Comment by tzarebczan** [comment]
Currently, it's possible to drag and drop a file onto any LBRY app screen (content shows, but need to restart app) - should that be disabled and only allowed in the Publish screen?  Not sure if I should make a separate issue for it or it can be handled under this one.

**Comment by kauffj** [comment]
I think dropping a file on LBRY should start a publish regardless of the screen the user is on.

**Comment by hackrush01** [comment]
To clarify, by screen you mean whichever page user is on? And dragging a file there should take him to the publish screen and input the path of the file, and some other default values?

**Comment by kauffj** [comment]
Yes, my inclination is to have the drop of a file move the user to the Publish page regardless of what page they are on.

If that can potentially cause bad or confusing UX, then there could be an intermediate modal like:

Do you want to publish <file>? 
[Continue] [Cancel]

But I'm not convinced we need to add that up front.

**Comment by hackrush01** [comment]
Ok, so I'll dive into it later.

**Comment by reillysmith** [comment]
The most important behavior to add is it actually inputting the file path first when dropped--initiating playback is a bug.

**Comment by kauffj** [comment]
I looked at this and re-based it to master. It is going to need to some work. It probably makes sense to hold on this until a larger publishing refactor.

**Comment by hackrush01** [comment]
I saw the comment just now, what kind of work, UX or functionality?

**Comment by daovist** [comment]
I'm gonna look into implementing this feature.

**Comment by aruniverse** [comment]
I'm interested in attacking this, any updates? I tried dragging and dropping in the publish section, and doesn't seem like that works at all. Would a good first pass be just being able to drag and drop files into the publish section, which would just set the filepath and the name?

**Comment by kauffj** [comment]
@jessopb is it safe for @aruniverse to work on this or should he wait until https://github.com/lbryio/lbry-desktop/pull/3016 is merged into `master`?
