### ISSUE TITLE
Tooltip/mouseover text incorrect for support abandon

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-desktop#3505]
This issue has existed in previous versions of the app and remains present in 0.39.0-RC3. The tooltip text for the trash icon next to a support should say "abandon support" or "revoke support", but instead it says "abandon claim".

![image](https://user-images.githubusercontent.com/1578298/72571741-4c9aad80-3925-11ea-8310-cd88acb1ce41.png)

**Comment by tzarebczan** [comment]
This was fixed.
