### ISSUE TITLE
please add easy copying for links that are in video description

### ISSUE THREAD

**Issue by groowyCZ** [lbryio/lbry-desktop#3512]
**Is your feature request related to a problem? Please describe.**
my problem is that I'm lazy to copy it by selecting the text

**Describe the solution you'd like**
I'd be happy if you'd add it to the popup menu

**Describe alternatives you've considered**
not being lazy to copy it by selecting the text

**Additional context**
I find it frustrating when stuff I'm used to in every browser-like app isn't working in browser-like app. In the attached image is demonstration of the menu that should offer me to copy that link but it sadly isn't.

![menu](https://user-images.githubusercontent.com/21190479/72670570-12253380-3a3f-11ea-8157-0e291410d054.png)

**Comment by tzarebczan** [comment]
Thanks for the feedback and opening the issue! We have this filed under https://github.com/lbryio/lbry-desktop/issues/3065.
