### ISSUE TITLE
Indicate file type on claim previews  and other improvements (homepage and tiles)

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#3517]
Most likely via an icon and/or contextual information about the content (for example: "05:00 ▶" implies video")

Others from Tom for homepage/tiles:
- [x] add duration
- [ ] someway to display tags on hover?
- [x] make it more obvious that the channel name is clickable. Clicking profile pic should go to channel page too? 
- [ ] add right click > copy link functionality like we have on tiles (needs to be fixed to have : instead of #) or fix the redirect (desktop only)

**Comment by kauffj** [comment]
+ video length missing on homepage tiles

**Comment by seanyesmunt** [comment]
I will die on a hill defending that the channel name doesn't need to look "more clickable". It's not like it's some unique concept to lbry, it's a profile link. People know they can click on it.
