### ISSUE TITLE
Figure out why app image upgrade leaves 2 icons in tray

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3528]
Looks like it shutdowns and the SDK restarts, but 2 icons are in the tray. The old one is not responsive to open/quit, but the new one is. If quit, both disappear. Might be an electron builder bug, will reach out to them also.

**Comment by tzarebczan** [comment]
https://github.com/electron-userland/electron-builder/issues/4740

**Comment by er013** [comment]
Maybe related #3898

**Comment by tzarebczan** [comment]
This will be fixed in the next release.
