### ISSUE TITLE
Alignment issues on certain OSes

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3529]
![image](https://user-images.githubusercontent.com/8120721/72938358-d937d800-3d38-11ea-910a-1fab15eedd48.png)

**Comment by tzarebczan** [comment]
This also happens on FireFox

**Comment by tzarebczan** [comment]
This is still an issue, and does happen on Firefox on one of my machines. Might be related to resolution. A few community members have noticed it as well.

**Comment by cassidypignatello** [comment]
@tzarebczan I'd like to take this one if no one's working on it!

**Comment by kauffj** [comment]
You got it @cassidypignatello!

We're pretty good about keeping issues we're working on actively assigned (it's much more likely someone is *not* working on something that is assigned than vice versa).

So generally feel free to pick up any issue you think you can make progress on if it's unassigned.

**Comment by cassidypignatello** [comment]
Right on @kauffj, great to know!

**Comment by kauffj** [comment]
@cassidypignatello if you want extra insights into our work status you can install Zenhub plugin. I believe those are publicly visible to everyone with the plugin.

**Comment by cassidypignatello** [comment]
Awesome, thanks for the tip @kauffj! I just installed Zenhub and can see everything now.
