### ISSUE TITLE
Add Danish to languages

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry-desktop#3533]
Danish is complete on Transifex - please add to the app language menu.

**Comment by tzarebczan** [comment]
@jsigwart can you take another scan and add others that may be completed? I think Romanian is ready too.

**Comment by jsigwart** [comment]
**We need to add Danish, Romanian, and Urdu.**

**24 total languages (not counting English) should be included:**

Chinese (zh) 99.12% translated
Czech (cs) 100% translated
**Danish (da) 100% translated**
Dutch (nl) 100% translated
French (fr) 100% translated
German (de)  91.47% translated
Gujarati (gu) 89.39% translated
Hindi (hi) 89.39% translated
Indonesian (id) 100% translated
Italian (it) 96.39% translated
Malay (ms) 100% translated
Malayalam (ml) 89.39% translated
Marathi (mr) 89.39% translated
Panjabi (Punjabi) (pa) 89.39% translated
Polish (pl) 100% translated
Portuguese (pt) 89.39% translated
**Romanian (ro) 100% translated**
Russian (ru) 100% translated
Serbian (sr) 100% translated
Slovak (sk) 100% translated
Spanish (es) 100% translated
Swedish (sv) 89.39% translated
Turkish (tr) 100% translated
**Urdu (ur) 89.39% translated**

**5 languages are in progress but less than 50% translated:**

Croatian (hr) 40.92% translated
Finnish (fi) 22.1% translated
Estonian (et) 21.88% translated
Ukrainian (uk) 16.52% translated
Slovenian (sl) 11.38% translated

**Comment by tzarebczan** [comment]
@Madiator2011 can you add these?
