### ISSUE TITLE
blobfiles using an obnoxious amount of disk space

### ISSUE THREAD

**Issue by Tcll** [lbryio/lbry-desktop#3538]
I just recently tried to install a system update and wasn't able to do so because of low disk space.
after installing baobab, I nearly had a heart attack finding out `~/.local/share/lbry/lbrynet/blobfiles` was using around 13.2 GiB of space.

I'm not sure what this directory is, or if I can delete everything in this directory without screwing something up...
but this may have been the reason for recent videos hanging at 30% downloaded >.>

I have my home folder on my small 30GiB OS partition (among multiple OS partitions), while all my programs and associate data is stored on a separate HDD.
so that's why ~14GiB of drive use cripples my OS

I haven't updated yet, but I'm posting this issue as I don't see anyone else mentioning it
hopefully it's already fixed.

**Comment by tzarebczan** [comment]
Please see https://lbry.com/faq/host-content and options on your settings page. 

Covered in https://github.com/lbryio/lbry-desktop/issues/1966 / 
https://github.com/lbryio/lbry-desktop/issues/3477 / 
https://github.com/lbryio/lbry-sdk/issues/1311

**Comment by Tcll** [comment]
ah, so it might just screw something up if I delete that stuff, alright then...
here I'd thought my library folder was what was shared, I guess not... :P

wish that would've been made a bit more clear and not buried in some obscure location so I could've known to symlink that directory.
