### ISSUE TITLE
startup failure

### ISSUE THREAD

**Issue by Tcll** [lbryio/lbry-desktop#3540]
latest version won't launch:
![](https://user-images.githubusercontent.com/773959/73071533-f7a8eb00-3e80-11ea-9a9d-a7ea7b1db42f.png)

when launching via terminal, here's the output I get:
```
$ firejail --noprofile ./LBRY_0.39.0.AppImage
Parent pid 3214, child pid 3215

Child process initialized
Starting SDK
Sandbox listening on port 5278.
Daemon: [60] Error loading Python lib '/tmp/_MEI1eWR4E/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEI1eWR4E/libpython3.7m.so.1.0)

Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

parent is shutting down, bye...
```

**Comment by tzarebczan** [comment]
It's a known bug on xenial systems we have filed on the sdk. 

See lbry.com/faq/startup-troubleshooting for a download link.

**Comment by Tcll** [comment]
@tzarebczan just to note, the link is a blank page:
https://build.lbry.io/app/build-9203_commit-87dddee/electron/
it might be because I'm blocking google trackers and 3rd-party frames... :P

I tried finding the commit ID on here, and I'm having issues finding a direct appimage download...
could I get a link to the associate release please. :/

**Comment by tzarebczan** [comment]
Yea it's probably your blocker.

Try https://build.lbry.io/app/build-9203_commit-87dddee/electron/LBRY_0.39.0.AppImage

**Comment by Tcll** [comment]
thank you
it works like a charm ;)

btw, word of advice, **all** google domains invade your privacy, doing more than just delivering the referenced content you expect (eg: fonts.googleapis.com), especially if you have a blink-based browser.
if they didn't track you, I'd have no problem unblocking the domain.

**Comment by Tcll** [comment]
can I request the appimage builds for older glibc be included in the release assets:
![](https://user-images.githubusercontent.com/773959/73689713-de801580-469c-11ea-8f88-9416bb8fdbd6.png)

I can't upgrade to Void Linux on this machine currently and am stuck on Xubuntu 16.04 until I can successfully install Void on crypt-luks on my router (repurposed PC), and get my primary and server machines online to cut ties to this machine.

**Comment by tzarebczan** [comment]
Right now we have them up on the startup troubleshooting page since it affects such a small number of users. I'll consider adding it there with our next release.
