### ISSUE TITLE
LBRY does not run on Ubuntu 16.04 due to glibc 2.25 not found

### ISSUE THREAD

**Issue by dan-gph** [lbryio/lbry-desktop#3548]
LBRY 0.39.1 does not run on Ubuntu 16.04 because glibc 2.25 is not found. This is what happens when it is run from the command line:

```
$ lbry
Starting SDK
Sandbox listening on port 5278.
Daemon: [8965] Error loading Python lib '/tmp/_MEIadz2oN/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIadz2oN/libpython3.7m.so.1.0)

```
Earlier builds used to work. [Ubuntu 16.04 ("Xenial") has glibc 2.23](https://packages.ubuntu.com/source/xenial/glibc).

**Comment by dan-gph** [comment]
I see it was already reported. Sorry.

**Comment by dan-gph** [comment]
https://github.com/lbryio/lbry-desktop/issues/3540

**Comment by tzarebczan** [comment]
Thanks for following up and closing!
