### ISSUE TITLE
Optional transcoding

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#3574]
UI-side ticket for https://github.com/lbryio/lbry-sdk/pull/2726#issuecomment-579387575

- If SDK indicates transcoding is available, show checkbox on publish
- If checkbox is published, call `publish` with appropriate additional encoding flags
- Do additional magic to handle/explain/report the wait-time caused by this?

**Comment by kauffj** [comment]
@BrannonKing desktop ticket for https://github.com/lbryio/lbry-sdk/pull/2726

**Comment by jsigwart** [comment]
@cocacolamanager#6534 in Discord is asking for specifications as to the transcoding. Their wishes:

<img width="639" alt="Screen Shot 2020-03-21 at 11 46 54 AM" src="https://user-images.githubusercontent.com/1363664/77234190-b32c8980-6b69-11ea-8123-65f4eded80f5.png">
<img width="738" alt="Screen Shot 2020-03-21 at 11 46 30 AM" src="https://user-images.githubusercontent.com/1363664/77234192-b4f64d00-6b69-11ea-8459-253bdc5aca16.png">
<img width="623" alt="Screen Shot 2020-03-21 at 11 46 00 AM" src="https://user-images.githubusercontent.com/1363664/77234193-b58ee380-6b69-11ea-8048-bcb98f2f75be.png">

**Comment by tzarebczan** [comment]
First version will be shipping with the next app release, will create a new ticket for next steps/enhancements.
