### ISSUE TITLE
Handle/ignore markdown in OG embed description

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3575]
https://lbry.tv/@lbry:3f/trending-discovery-lbry:8 comes over as:

```
LBRY.tvLBRY.tv
Is Discovery and Trending Decentralized on LBRY?
A quick impromptu look at how decentralized discovery and trending are on the LBRY network. [Trending FAQ](https://lbry.com/faq/trending) [Wallet server FAQ](https://lbry.com/faq/wallet-servers)
```

**Comment by Invariant-Change** [comment]
More info: https://github.com/lbryio/lbrytv/issues/230

**Comment by Invariant-Change** [comment]
I couldn't find where the meta/OG tags were generated in the SDK. Can anyone point me in the right direction?

**Comment by Ruk33** [comment]
Hello, I believe this one has already been solved:

![image](https://user-images.githubusercontent.com/1719111/90054965-fe7b3c00-dcb2-11ea-8e84-a9e7ed8e8c4d.png)

Notice how the description handles markdown properly.

Regards.

**Comment by tzarebczan** [comment]
This is in reference to OG metadata, not the descriptions on the site itself.

**Comment by Ruk33** [comment]
Oh this one you mean @tzarebczan 

![image](https://user-images.githubusercontent.com/1719111/106021763-e56d1880-60a3-11eb-9c65-df236c562ca9.png)

I can work on it if it's free.

**Comment by tzarebczan** [comment]
All yours! I think the goal there would be to remove the  [] and URLs.

**Comment by Ruk33** [comment]
Ok guys, here is the PR: https://github.com/lbryio/lbry-desktop/pull/5415. But please, take a look at the note I left:

>NOTE: Please double check if these changes indeed solve the issue. I tried testing it using yarn dev:web but the og:description content was always the value of SITE_DESCRIPTION. I tried using the production build; using the dev web server (yarn dev:web-server); and even with pm2 just in case but the descriptions weren't generated as seen in lbry.tv.

Regards.
