### ISSUE TITLE
Show content view counts on channel pages

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3587]
The view api accepts multiple claim ids at once.

**Comment by seanyesmunt** [comment]
Would this require passing every claim_id from a channel? Or could we pass the channel claim_id?

**Comment by tzarebczan** [comment]
We can get a new endpoint setup to do it by channel id, but we may not have all the information on apis linked together. Should work for the most part, and if we don't find one, maybe we can call it with claim id.

I'll get an issue filed.
