### ISSUE TITLE
Embed issues - thumbnail, audio card, autoplay param

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3592]
embeds should not autoplay unless some param is specifically passed. It should show the thumbnail by default also.

Example: https://lbry.com/news/210-Malabarize-se

**Comment by kauffj** [comment]
@jessopb I'd like to come back and address these ASAP since we haven't announced this feature yet.

**Comment by jessopb** [comment]
we can useParams in embedwrapper to detect ?autoplay
<video ref={videoRef} poster={embedded && thumbnail} className="video-js" /> will put the thumbnail back. will do.

**Comment by tzarebczan** [comment]
Autoplay works, thumb would be next.

**Comment by jessopb** [comment]
Also, audio links don't work
`if (claim.source_media_type && claim.source_media_type.startsWith('video/')) {`
