### ISSUE TITLE
Cannot do most actions on OpenRC

### ISSUE THREAD

**Issue by enderger** [lbryio/lbry-desktop#3605]
**Bug**
When running an OpenRC system (in my case Artix Linux), the lbry desktop app does not allow signin or video viewing.

**To Reproduce**
1. Install lbry on any OpenRC system, such as Artix Linux or Devuan Linux
2. Start up lbry
3. Attempt to sign in OR view a video

**Expected behavior**
I would expect a video to load or sign in to process

**Screenshots**

**System Configuration**

- LBRY Daemon version: rolling
- LBRY App version: 0.39.1
- LBRY Installation ID: 6d1WiUCPS1TnPuo4eHS9RvaenVrKVBDPFSzaw8zxV2aFU3RNgy92zwfP3qhFFstdqc

- Operating system: Artix Linux

**Additional context**

**Comment by tzarebczan** [comment]
Sorry to hear. This is related to not having gnome keyring installed most likely.  This may still not work with some distros.

We recently moved to a cookie but have not fully removed it yet. Covered under https://github.com/lbryio/lbry-desktop/issues/386 / https://github.com/lbryio/lbry-desktop/issues/1620

We only officially support Debian based linux. We'll try to get more support later this year by removing it completely.  We may also need to upgrade the electron subsystem for it to work fully.



For now, you can try lbry.tv on the web.

**Comment by enderger** [comment]
I do believe this issue may occur on Devuan Linux, a Debian derivative that uses OpenRC. As for Gnome Keyring, it does happen to be installed on the computer. The complaint from the program mentions an unclosed catch block.
