### ISSUE TITLE
Change Color of Dark Mode Checkmarks on Settings Page

### ISSUE THREAD

**Issue by JakeVdub** [lbryio/lbry-desktop#3608]
**Is your feature request related to a problem? Please describe.**
When using the desktop app on Linux Mint with darkmode turned on it can be very hard to tell whether or not a box is checked on the settings page. 

**Describe the solution you'd like**
A solution would be to change the color of the checkmark so that it has more contrast. This could be done for just users in darkmode.

**Describe alternatives you've considered**
An alternative would be to turn off darkmode, which is pretty dire..

**Additional context**
![Screenshot from 2020-02-03 08-19-25](https://user-images.githubusercontent.com/8801299/73660493-eb314900-465d-11ea-83e8-a98314481851.png)
![Screenshot from 2020-02-03 08-19-03](https://user-images.githubusercontent.com/8801299/73660494-eb314900-465d-11ea-8f30-5f2c4656f0bd.png)

**Comment by tzarebczan** [comment]
Thanks for opening this issue! It doesn't look too bad here, but I'm sure we can improve it.

**Comment by seanyesmunt** [comment]
Fixed with https://github.com/lbryio/lbry-desktop/pull/3648
