### ISSUE TITLE
Viewed content marking

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3614]
We used to show a different shade on claim tiles when content was already viewed. A few people have asked when this feature would be coming back. We'd need something for the homepage. 

If we want this to persist across devices, we'd need to sync to wallet (but that's too much data to move around).

**Comment by aboimpinto** [comment]
right now my recommended feed is full of videos I already saw and I cannot find new videos ... 

I would suggest increasing the priority of this feature

**Comment by tzarebczan** [comment]
Needs some API improvements, but work can probably start app side. 

Much requested and long overdue feature.

**Comment by jessopb** [comment]
Will style this a bit more.

**Comment by jessopb** [comment]
This will be enhanced by #7543
