### ISSUE TITLE
Show total amount of tips on videos

### ISSUE THREAD

**Issue by paju1986** [lbryio/lbry-desktop#3620]
It will be good to show the total amount tipped to a video right to the views. It will be kinda like the "likes" on youtube.

**Comment by JupyterJones** [comment]
That information is too personal. I would not like it displayed. If they go that route it must be allowed to be hidden from from viewers.

**Comment by paju1986** [comment]
@JupyterJones As I understand, that information is already available publically on the blockchain is only not displayed on a friendly way on the app.
