### ISSUE TITLE
Custom Installation (Windows)

### ISSUE THREAD

**Issue by DAMO238** [lbryio/lbry-desktop#3625]
**Is your feature request related to a problem? Please describe.**
I am forced to use what is essentially an electron wrapper due to the size of my uploads, however, my C drive (Windows) is mostly full of development dependencies and so space there is a premium. The fact that there is no option to install anywhere else means I either have to sacrifice video quality/length or run into issues with disk space.

**Describe the solution you'd like**
Allow a custom installation into a directory of your choice.

**Describe alternatives you've considered**
Unrealistic: Overhaul the app to be a standalone app, without relying on the existing web app.
Realistic partial solution: Allow unlimited uploads on the web app through a browser

**Comment by tzarebczan** [comment]
Thanks for opening the issue and for the feedback. It's not actually the install location of the app, that's only a few hundred MB, but instead where the SDK stores the data. 

The easiest way around it right now would be to create a symlink to the blob files folder. 

We have these issues filed to cover this:
https://github.com/lbryio/lbry-desktop/issues/3477
https://github.com/lbryio/lbry-desktop/issues/1966
https://github.com/lbryio/lbry-desktop/issues/3475 (downloads, but this is configurable in settings) 
https://github.com/lbryio/lbry-desktop/issues/446 (the issue you reported)
