### ISSUE TITLE
Language switch does not take effect right away

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3641]
Requires a restart/navigating away:
![image](https://user-images.githubusercontent.com/8120721/73863851-b44e6500-480e-11ea-931f-a17f71d33940.png)

**Comment by infinite-persistence** [comment]
_This seems related, so I'm putting it here instead of submitting a new one_
### Issue:
I noticed recently that Desktop always starts in English.  I seldom get to see "Spin Spin Sugar" in it's translated form.
