### ISSUE TITLE
@lbrycast hyperlink in text of new post going to incorrect channel

### ISSUE THREAD

**Issue by earthjeffone** [lbryio/lbry-desktop#3649]
Hey,
Found a small error...

Go to the Green New Post of introducing @lbrycast

![Screen Shot 2020-02-06 at 3 41 29 PM](https://user-images.githubusercontent.com/34739321/73988512-c821c600-48f7-11ea-93ef-0ebc017858a3.png)

Click on it, and try the link in the text.
Notice that it takes you to a different @lbrycast channel

![Screen Shot 2020-02-06 at 3 48 44 PM](https://user-images.githubusercontent.com/34739321/73988654-2ea6e400-48f8-11ea-9c29-b2dc95b776c4.png)

Clicking on the link in text goes to incorrect channel:

![Screen Shot 2020-02-06 at 3 50 02 PM](https://user-images.githubusercontent.com/34739321/73988727-601faf80-48f8-11ea-9f47-726d9e876fb7.png)

Clicking on the thumbnail goes to the proper channel:

![Screen Shot 2020-02-06 at 3 53 00 PM](https://user-images.githubusercontent.com/34739321/73988908-f227b800-48f8-11ea-87ed-8a67bbf05c2a.png)

The problem exists in lbry.tv and in the app, on Mac. It looks like it is an old channel that claimed the name, and the new @lbrycast has a separate link.

Hope this helps :)

Jeff

bJFQtNLwPC28mzLRMDH4eRGD4LN3ksBnPw

**Comment by tzarebczan** [comment]
Thanks for the heads up! We'll fix the link to the channel, there are multiple and we didn't point to the right one.

**Comment by tzarebczan** [comment]
Can we show you some [appreciation](https://lbry.com/faq/appreciation)? 

You can also report issues like this to us at https://chat.lbry.com
