### ISSUE TITLE
Display wallet balance anywhere credits are used

### ISSUE THREAD

**Issue by auber262** [lbryio/lbry-desktop#3653]
**Is your feature request related to a problem? Please describe.**
In some instances, when credits are spent (tips, supports etc) the balance is not displayed and so you do not know how much you have when making a payment. If you want to support a claim with, say 200 LBC, you need to be able to see your wallet balance before, rather than rely on entering a figure only to get the error of 'you do not have enough credits'.

**Describe the solution you'd like**
In all places where credits are spent, for the balance to be displayed. This needs to be not only on the desktop app but also on lbry.tv - mobile view from phone particularly.

If you use lbry.tv on your phone and you go to support a claim, the dialog box is very limited.
![suggestion](https://user-images.githubusercontent.com/39855197/74046218-100f1e80-49c6-11ea-83ec-1bce5780e521.PNG)
![current](https://user-images.githubusercontent.com/39855197/74046222-10a7b500-49c6-11ea-99ff-6d42fe5cfbb5.PNG)

**Describe alternatives you've considered**
Toggling back and forth from wallet to page or claim / tip support page (which is a nightmare!)

**Additional context**
Image of current and suggestion of solution attached

**Comment by tzarebczan** [comment]
Thanks for opening this, certainly needed in a few places where we use credits!

**Comment by seanyesmunt** [comment]
Added this for mobile views
