### ISSUE TITLE
Video tags, time and icon are clipped when tags are longer (while others aren't)

### ISSUE THREAD

**Issue by 345k** [lbryio/lbry-desktop#3658]
**Bug**
A video named "8 Phone Numbers That Are Too Creepy to Call" is clipped, where other entries are fine. I believe (not sure) this is happening because the tags are longer.

**To Reproduce**
1. Go to `lbry://@Paranormal-ghost-videos#9` on the desktop app
2. Look for the video in the list named `8 Phone Numbers That Are Too Creepy to Call`
3. The tags, time and other info on the right is outside the area and clipped (screenshot below)

**Expected behavior**
I expect it to show it within the area

**Screenshots**
https://spee.ch/c/temp3.png

**System Configuration**

App:	0.41.0
Daemon (lbrynet):	0.54.1
- Operating system: Linux 64 bit

**Additional context**
Is this video haunted or something? (just joking)

**Comment by tzarebczan** [comment]
Thanks for opening the issue! We have a similar one filed under https://github.com/lbryio/lbry-desktop/issues/3374
