### ISSUE TITLE
Autoplay + Related go into loops ( infinite ) sometimes

### ISSUE THREAD

**Issue by adam-dorin** [lbryio/lbry-desktop#3661]
**Bug**
The related videos make the user go into play infinite loops if they have autoplay feature turned on.
This happens because the first related video is either the same video, or alternate secondary video that points back to the original one that you are watching.

**Expected behavior**

If the first related is autoplayed, I would expect my past watch history ( at least for this session) to be taken into account when deciding the first related video.

**Relation**

Video1 => has as First related Video2
![Video1](https://user-images.githubusercontent.com/1072815/74099950-a875e200-4b31-11ea-9418-7308c2dabc07.PNG)

Video2 => has as first related Video1
![video2](https://user-images.githubusercontent.com/1072815/74099948-a7dd4b80-4b31-11ea-812a-0feff3a69f35.PNG)

Video3=> has as first related Video3
![video3](https://user-images.githubusercontent.com/1072815/74099947-a6ac1e80-4b31-11ea-9d53-6849e07cc623.PNG)

**System Configuration**

- App | 0.41.0
- Daemon (lbrynet) | 0.55.0
- Platform | Windows (Windows-10-10.0.19041-SP0)

**Comment by tzarebczan** [comment]
Thanks for filing @adam-dorin!
