### ISSUE TITLE
Wallet filters by publish title

### ISSUE THREAD

**Issue by auber262** [lbryio/lbry-desktop#3662]
**Is your feature request related to a problem? Please describe.**
It's not related to a problem but as a publisher, when you look at your published pieces it's difficult to be able to see which posts have what tips and support. It makes sense to be able to either add filters or clickable column titles so that you can filter or sort each published item in the wallet so that you can better manage the tips/support.

**Describe the solution you'd like**
Either some filters to show wallet type content (tips, support, abandon, etc) by each item. A simple way to handle this would be to add a sorting feature by the column title (s la Excel) but the better more robust way is to add filtering by publish title so you can see exactly all the actions against each published piece.

**Describe alternatives you've considered**
Reviewing my wallet, the pagination only shows a few at a time and are chronological - so it is difficult to see all the actions against each publish. The pagination also only shows a truncated part of the publish title - so difficult to know one from another.

**Additional context**

**Comment by tzarebczan** [comment]
Thanks for the issue and idea! This will probably be part of https://github.com/lbryio/lbry-desktop/issues/3159

**Comment by tzarebczan** [comment]
It's now easier to filter for all tips on the transaction page, and we'll work on another view / way to see only claims with tips.
