### ISSUE TITLE
lbry driver in embed (on hover?)

### ISSUE THREAD

**Issue by jessopb** [lbryio/lbry-desktop#3664]
For discussion:
copy and appearance of button
whether to show related (same channel?) content at end

**Comment by MichaelTunnell** [comment]
I think related/more from channel content would be a good option if it is adjustable by the person embedding through a URL parameter. I would be fine with it in some cases and it would be a problem in other cases so I would want the option to use them or not.

The appearance of the button I think applies to the play button on the player and that has been improved lately via my contribution.
