### ISSUE TITLE
Desktop privacy changes

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#3668]
- [x] By default, tracking is off in desktop
- [x] Analytics message in settings is rewritten for clarity
- [x] Analytics preferences are synced across sessions.
- [x] In Wallet area, clearly communicate wallet custody when signed in to lbry.tv
- [x] Prompt people on desktop first-run to opt-in to sharing data

Do all of this in a way that minimally impacts usage for the 95% of people who don't think a lot about privacy.

**Comment by jessopb** [comment]
After some discussion,
The first page of sign in can be Privacy notification, sign/rewards offer.
We force sign-in-flow, but not sign-in.
SDK can default to no sharing.

How granular are privacy settings?

**Comment by kauffj** [comment]
>  Prompt people on desktop first-run to opt-in to sharing data 

^ suggested copy for this in privacy video
