### ISSUE TITLE
Improve first run messaging / auto approval / rewards

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3670]
- [x] nicer message when not auto-approved
- [x] make sure it's communicated that rewards are optional and may not be available in all regions
- [ ] ability to dismiss rewards

**Comment by kauffj** [comment]
- [ ] use the word validated

**Comment by tzarebczan** [comment]
- [ ] If user is pending review/denied (reward validated = 0, identity validated =1), send to rewards page with pending review info (today they end up at the page where they are asked for phone/credit again)
- [ ] the above should be dismissable/ not shown anymore if the user will use without rewards
- [ ] if not reward approved/not identity validated, allow dismissing/not showing on login
