### ISSUE TITLE
reposts feedback

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3676]
- [x] fix collapse (shows channel only, hides URL)( when claim name exists + you type something into the name 
- [x] Somewhere display what the repost claim name is (if you come from a repost into the claim? On the repost itself on hover? ) 
- [x] Ability to turn off seeing reposts completely 
- [ ] handle scenario where multiple channels you follow repost the same thing
- [ ] handle scenario where a single channel you follow reposts a claim to X different urls 
- [x] better display of repost channel on channel view? Feedback is that it looks like it's for the item above, not below. -
- [x] reposted claims so wrong effective amount

**Comment by kauffj** [comment]
remaining items to be split out

**Comment by tzarebczan** [comment]
These were broken out. The duplicates are filed under SDK issue: https://github.com/lbryio/lbry-sdk/issues/2812
