### ISSUE TITLE
Floating video player disappearing - audio playing

### ISSUE THREAD

**Issue by omarly666** [lbryio/lbry-desktop#3677]
**Bug**
Floating video player disappearing. 

**To Reproduce**
1. Using LBRY, playing any content
2. Click on any of LBRYs app buttons
3. 
4. See error: Nothing to view, just audio - I have to click back button, one or more times, to get back to video viewer

**Expected behavior**
A minimized window should appear, like if I do same in chrome

**Screenshots**

**System Configuration**

![Screenshot from 2020-02-11 23-36-18](https://user-images.githubusercontent.com/60946081/74286238-a37a8380-4d27-11ea-8637-62b97a2ecbbd.png)

 curl 'http://localhost:5279' --data '{"method":"version"}'
{
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "desktop": "Unity",
    "distro": {
      "codename": "bionic",
      "id": "ubuntu",
      "like": "debian",
      "version": "18.04",
      "version_parts": {
        "build_number": "",
        "major": "18",
        "minor": "04"
      }
    },
    "lbrynet_version": "0.54.1",
    "os_release": "4.15.0-87-generic",
    "os_system": "Linux",
    "platform": "Linux-4.15.0-87-generic-x86_64-with-Ubuntu-18.04-bionic",
    "processor": "x86_64",
    "python_version": "3.7.6",
    "version": "0.54.1"
  }
}

**Additional context**
None

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. What do you mean by See error: Nothing to view, just audio? 

Can you give us specific videos this happens with? Does it happen every time? Do you have the floating player option enabled in Settings?

**Comment by omarly666** [comment]
Every time I play a video and push an app button -> audio only
Floating player is enabled.

Like the player is "invisible". Alt-Tab will not show it either

**Comment by omarly666** [comment]
Now playing Lunduke - hearing audio but no sign of player
![Screenshot from 2020-02-11 23-58-37](https://user-images.githubusercontent.com/60946081/74287536-78ddfa00-4d2a-11ea-8db4-30768875930c.png)

**Comment by omarly666** [comment]
New updates on ubuntu seems to solve the problem. I did an update and reboot <1hr ago and problem solved. Probably something about ubuntu, not LBRY

**Comment by tzarebczan** [comment]
Glad to hear that! Also,try resizing your app window next time...maybe the player got "lost" somewhere.

**Comment by omarly666** [comment]
I got dual screens. Screenshot of only the LBRY app. Done a bit of bug rep on ubuntu, but now it seems to work real easy. also due to hw more linux friendly
