### ISSUE TITLE
Channel icons missing at smaller window sizes for app/lbry.tv

### ISSUE THREAD

**Issue by er013** [lbryio/lbry-desktop#3678]
Channel icons at frontpage disappear in 3-in-row layout - and are present at 4-in-row one. Former having larger items, so way more space available... 
![2020-02-12-151602-import](https://user-images.githubusercontent.com/60119125/74338775-7c659580-4dab-11ea-99d5-34db41824495.png)
![2020-02-12-151610-import](https://user-images.githubusercontent.com/60119125/74338778-7cfe2c00-4dab-11ea-9cdb-84c837c3f231.png)

**Comment by tzarebczan** [comment]
Thanks for filing! Also, since we show 8 items, there's a seemingly missing tile in the last row that looks strange.

**Comment by er013** [comment]
Ah yes, forgot to mention that. Some sections also had like 4 - mostly had multiples of 4, tailored for 4-in-row layout. Trending from my tags has 7 at the moment, trending from lbry the same. That could be made layout-dependant, so no short rows, no matter which layout variant is in use.
