### ISSUE TITLE
Seeing "Unused" as reposting channel

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#3681]
![Screenshot from 2020-02-12 13-49-49](https://user-images.githubusercontent.com/530774/74366802-b11f2000-4d9e-11ea-989f-9b77f3c9c645.png)

**Comment by tzarebczan** [comment]
Even after refresh? That should be the lbry-curator channel...seems to work here.

**Comment by seanyesmunt** [comment]
I think this could happen if resolving the channel fails? Not sure.

**Comment by tzarebczan** [comment]
Closing for now, let us know if it happens again.
