### ISSUE TITLE
Won't play vidoes in standalone LBRY App..

### ISSUE THREAD

**Issue by SeeYaw** [lbryio/lbry-desktop#3696]
Only loads a blank screen with title bar.  Can't go back, only option is to close app..
![Screenshot_20200216_071855](https://user-images.githubusercontent.com/59984729/74605314-add0b080-508c-11ea-8f96-03177d95450b.png)

**Comment by tzarebczan** [comment]
If you are on Linux, try the build at LBRY.com/faq/startup-troubleshooting

We'll try to get this fixed in the main release soon.
