### ISSUE TITLE
Repost error not shown in mobile view

### ISSUE THREAD

**Issue by auber262** [lbryio/lbry-desktop#3697]
When using lbry.tv, going to a post and selecting to repost something, if the URL is not changed, the error handling and messaging are out of position and you cannot clear the page or move forward.

Suggest some better on-page instructions to the user and some mobile UI improvements to make messages and buttons accessible.

Screenshot attached.
![Screenshot_20200216-073231](https://user-images.githubusercontent.com/39855197/74600854-1de03600-508f-11ea-9899-7584a0401417.png)

**Comment by tzarebczan** [comment]
It's still frozen because of lbry.tv slowness from your previous repost, which is a different issue we are still trying to track down.

This issue should cover making the error visible.
