### ISSUE TITLE
Add Finnish language to content language options

### ISSUE THREAD

**Issue by survivor303** [lbryio/lbry-desktop#3698]
When publish new content, there are just a few language options to choose from.
![image](https://user-images.githubusercontent.com/3097696/74673214-7c083880-51b7-11ea-8d3c-9fad32c8dd58.png)

I publish mainly finnish content and i want that all the matadata what we users can add to content, to be accurate as possible, but now i cannot choose my language.

So please add more languages to this list.

Odd thing is that, when i sync from youtube, then it can show "fi" on content language field on it's metadata:
![image](https://user-images.githubusercontent.com/3097696/74673268-94785300-51b7-11ea-9020-6713ea0a8f7c.png)

**Comment by tzarebczan** [comment]
There's an existing issue here to audit the list and add them to the app - but feel free to add finish according to the correct iso code: https://github.com/lbryio/lbry-desktop/issues/2455

**Comment by tzarebczan** [comment]
There's a PR for this, closing.
