### ISSUE TITLE
Support independent lbry.tv instances

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#3702]
- [x] lbry-desktop is modified to run in one of two _modes_: `desktop` or `web`
- [x] web mode replaces lbry.tv (e.g. `web` folder not `lbrytv` folder). lbrytv _should not appear in code outside of comments when complete_. The web URL, SDK API URL, player URL, and any other lbry.tv specific features are turned into configuration variables.
- [x] the domain property is posted to `/user/install` and/or any other calls (see https://github.com/lbryio/internal-apis/issues/1305)
- [x] there is some ability to override default `<HomePage>` areas, ideally via configuration rather than overriding component (worth discussing sync) (see #4041?)
- [x] `'en'` as default language is abstracted to pull from configuration in all or key places
- [ ] theme scss file overridable / locally usable (worth discussing sane practices here based on lessons from spee.ch)
- [x] logo URL local to project, any other lbry.tv specific images in source control moved to configuration or out of source control
- [ ] Possible, but not necessary for MVP: ability to add site-specific filters to `claim_search` and lighthouse search (example first use case: no porn)

**Comment by jessopb** [comment]
lbry.tv currently has a dependency on chainquery credentials.

**Comment by jessopb** [comment]
"install" as the call from web to note users?
what about "user/new"?

**Comment by kauffj** [comment]
I may have gotten call wrong. Whatever passes `web` or whenever `web` is passed, domain should be passed too.

**Comment by kauffj** [comment]
@jessopb hard dependency or just dependency for metadata? When not present, omit metadata.
