### ISSUE TITLE
Failure to load video

### ISSUE THREAD

**Issue by CompSciGuyIT** [lbryio/lbry-desktop#3703]
**The issue**
Videos refuse to load and error message appears

**Steps to reproduce**
Click on any video to begin watching

**Expected behavior**
Videos begins to download and play as normal

**Actual behaviour**
When I play the video, the message below appears and the the video sits in perpetual loading.
![lbry](https://user-images.githubusercontent.com/9046434/74697998-1ca63900-5248-11ea-9020-6b051886a3ba.PNG)

**Temporary solution**
Logging out and logging back in again isn't enough to resolve the issue.
I must log out and shut down LBRY, then open up a task manager and kill all LBRY processes,
before logging back in again.

**Affected system**
Desktop running Windows 10

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. Can you send us your log file (see Help page) to hello@lbry.com so we can take a closer look? Closing this issue for now as it's most likely related to something in the SDK / local network issues.
