### ISSUE TITLE
Refreshing LBRY TV

### ISSUE THREAD

**Issue by Blanxs** [lbryio/lbry-desktop#3710]
When the user is already on the main page, and clicks the LBRY button it should refresh the main page of LBRY tv. I just notice that after I refreshed the website that clicking that button didnt refresh the page for me.

**Comment by HarshKhandeparkar** [comment]
Hi! Can I work on this?

**Comment by HarshKhandeparkar** [comment]
I have figured out which file to change but I want to know what I should change. Should the whole location be reloaded using something like `window.location.reload()` or some react trickery to reload certain parts?

**Comment by HarshKhandeparkar** [comment]
Or should I just make it a NavLink to `/`?

**Comment by HarshKhandeparkar** [comment]
Okay it apparently already navigates to `/`, so should I just make it reload if it is on `/`?

**Comment by HarshKhandeparkar** [comment]
@tzarebczan ?

**Comment by kauffj** [comment]
@HarshKhandeparkar that seems like a good solution, thanks!

**Comment by HarshKhandeparkar** [comment]
Thanks for the green signal! I'll open a PR soon.

**Comment by HarshKhandeparkar** [comment]
@seanyesmunt this can be closed ig?

**Comment by seanyesmunt** [comment]
Yep!
