### ISSUE TITLE
32bit appimage

### ISSUE THREAD

**Issue by Tcll** [lbryio/lbry-desktop#3713]
basically, I have a decent amount of desktop machines that constantly change use cases depending on performance needs vs what machines are operational...
sometimes I end up needing to use my 32bit machines for major jobs like hosting a web service...

so yeah, I'm in need of an appimage for the latest 32bit Void kernel

EDIT: got my kernel version: 5.4.20_1

**Comment by tzarebczan** [comment]
Sounds like it's not supported anymore: https://www.electronjs.org/blog/linux-32bit-support

Does the deb work? I think that may also be 64 bit.

**Comment by Tcll** [comment]
> Does the deb work? I think that may also be 64 bit.

I haven't installed apt support (just xbps currently)
I will if I have to, but I'd prefer something portable :/

**Comment by Tcll** [comment]
yeah it looks like I might be out of options for an appimage, unless you guys can pull a miracle
(I could say a thing about bad devs (electron), but I'm sure you guys know already)
hoping for a portable multi-platform C++/Qt app in the future :)

so I tried installing apt/dpkg
and already [I ran into headaches](https://github.com/void-linux/void-linux.github.io/issues/78)
but at least I seem to be making progress ;)
(I feel disgusting for using apt)
