### ISSUE TITLE
Another way to sign-in

### ISSUE THREAD

**Issue by jurgen-74** [lbryio/lbry-desktop#3730]
Hi all,

I am not sure whether I should post this here but hey, you can always tell not to do it anymore :)

I am very enthusiastic about LBRY! 
However, I live and work in a very remote area on Madagascar. This means that our internet is terrible. Sometimes I can't even download flat-txt email (EDGE is not even that slow). 

The problem for me thus is login in. Giving my email, fetching email, opening the link and then being able to use the app (desktop and Android alike) is a pain. This procedure fails mostly for me.

Now I understand the whole security issue on logins and what not. Would it be an idea to give an option to login in the old fashion way (just storing a password offline). This way, people with slow internet can choose to login in a different, more suitable way.

Blessings
Jurgen

**Comment by tzarebczan** [comment]
Thanks for opening the issue! This is something we plan to do later this year after we support passwords across all our platforms.

**Comment by tzarebczan** [comment]
This is not live on lbry.tv and will be coming to a desktop app later this week!
