### ISSUE TITLE
Request: Add a Open on LBRY option to the Embedded Player UI

### ISSUE THREAD

**Issue by MichaelTunnell** [lbryio/lbry-desktop#3731]
This is not technically a bug or anything but I do see it as an opportunity to improve the player. When I embed a video from LBRY.tv it works great and I am already a big fan of using it for my embeds, especially with y'all being so receptive to input regarding it.

The thing I noticed is that once I embed the video I can't really interact with it beyond playing the content. For example, I would like to open the LBRY.tv page for the video and maybe make a comment, tip, etc but unfortunately its currently very difficult to do that.

The way YouTube handles this function is to have the title of the video at the top left of the Player when Hovering it and making that a direct link to the video page. I think this would be a great addition to the LBRY page to encourage interaction.

Alternatively, you could add a [linkout button](https://fontawesome.com/icons/external-link-alt?style=solid) to the Player Controls for the same function as well but I think the title at the top is more valuable . . . maybe a combination of both with a linkout icon at the top right of the player and the title at the top left. :sunglasses: 

Maybe something like this:
![lbry-embed-top](https://user-images.githubusercontent.com/1056731/75094590-49ad6100-5552-11ea-8cbd-f9e5e3e7ef27.gif)

This GIF demonstrates what I mean and the elements are the title, link to LBRY with icon, and a black to transparent gradient from the top to make the text more visible regardless of what the content of the video is.

**Comment by seanyesmunt** [comment]
Thanks for the issue. This is definitely something we plan to add. I like the button you added in the gif!

**Comment by tzarebczan** [comment]
I like this - should be combined with https://github.com/lbryio/lbry-desktop/issues/3664

**Comment by MichaelTunnell** [comment]
@tzarebczan I think these are very much related issues but I think it is better to not combine because progress can be tracked better and organization can be cleaner that way. I have had many issues sent into a project before that were ignored for years because it was buried by merging stuff. I am not saying it would happen here, just that I have seen it many times before.

**Comment by tzarebczan** [comment]
This is covered in a recent PR and will be live next week.
