### ISSUE TITLE
double nag on open.lbry.com

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3734]
If a user goes to open.lbry.com to hyperlink to content they wish to open in the app, they first see the privacy warning, which they need to close out of, and then they finally see the open in lbry prompt. Can we show both? Show only the open in app first?

**Comment by kauffj** [comment]
IMO we should just fix this more generally

- If open.lbry.com link, user is visiting on mobile, and `/user/me` has mobile, show nag
- If open.lbry.com link, user is visiting on desktop, and `/user/me` has desktop, show nag
- Re-write nag: "It looks like you may have [LBRY Desktop | LBRY Android] installed. [Open in App]"
- Always show nag, and show this nag over the privacy one
