### ISSUE TITLE
forward and back mouse buttons broken

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3744]
On Desktop after https://github.com/lbryio/lbry-desktop/pull/3650

**Comment by dalhill** [comment]
I'll take a look at this soon

**Comment by tzarebczan** [comment]
Another thing that broke is refreshing from an existing page - it would take you back to that page, but now it goes back to the homepage. Probably not a huge deal, but that was nice.

**Comment by tzarebczan** [comment]
Confirmed fix is working, will be in next app release.
