### ISSUE TITLE
better display of broken thumbs

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3751]
![DEADTHUMB](https://user-images.githubusercontent.com/8120721/75357078-cdcb5580-587e-11ea-83c5-48071aeb4a42.png)

Thanks @jessopb !

**Comment by infinite-persistence** [comment]
In today's code, the `alt` text has been removed, so it looks somewhat ok.  The only issue left is probably the default "broken image" picture not fitting the theme, and that the empty space could be improved.

With `img:after`, we could paint over the section with minimal code.  It works on Desktop, but I believe some browsers don't support it, so it might not work in lbry.tv.  However, it should be a no-op, so it won't be any worse for those browsers.

Here's from my experiment, opting to display something simple (I vote to just display a blank box with dashed border):
![image](https://user-images.githubusercontent.com/64950861/83252451-d022b000-a1dd-11ea-96cc-708eaafd540e.png)

Would you guys be interested in this solution?

**Comment by Ruk33** [comment]
Hello @tzarebczan , I would like to work on this one, can I take it?
Regards.

**Comment by Ruk33** [comment]
Hello guys, I just sent a small PR for this one https://github.com/lbryio/lbry-desktop/pull/5426. Regards.

**Comment by jessopb** [comment]
This got reverted...?
