### ISSUE TITLE
Video play button issues / remove play button from center of videoplayer when playback is paused.

### ISSUE THREAD

**Issue by er013** [lbryio/lbry-desktop#3765]
Older suggestion from ideas-and-feedback:

er 01/20/2020
one suggestion: dont display that large green play button in the middle of videoplayer screen when it is started playing and then paused. sometimes one needs to pause playback in order to read/inspect something in this frame and this huge thing just is in a way. its plenty to toggle play/pause icons at bottom/left.

Another one from help:
Jason Khanlar (@jasonkhanlar) Today at 12:36 PM
uhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh, double you teee eff? How come in the LBRY.tv website, when I pause a video, there is a play icon covering the center of the video? That is so annoying and disruptive! I want to take a screenshot of something quickly, but now I need to edit the CSS to hide that icon!

Adding to it that "minor ui thing" or not, its in a users face every time he uses lbry. Each and every time he plays/pauses something. Wants to read some text in video frame, wants to screenshot... It should not be classified as minor.

**Comment by tzarebczan** [comment]
Just a little history about this one - this was done as a workaround to how autoplay is handled on different browsers. Without the play icon, some users would not be able to play a file if it was paused by the browser. 

Thanks for filing!

**Comment by er013** [comment]
but play/pause in videoplayers bottom control-bar - they dont get to see them?

**Comment by seanyesmunt** [comment]
https://github.com/lbryio/lbry-desktop/commit/2d56518ffe1a95bac6d5667bb5d4032c9190b6b4 fixes this for non-mobile views. We need a better solution to properly handle failed autoplay on mobile
