### ISSUE TITLE
[desktop] Wrong downloaded item added (vanity) on reposts / can't delete?

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3767]
Make sure download files is enabled. Go to @lbryio channel and view + download the @lbrytech claim Hello, World claim. Check Library and you'll see the wrong claim added...and when you click it, it downloads that. It looks like it adds the vanity url hello

You end up in a situation where that file is in your Library, but you can't remove it.

**Comment by davidpgil** [comment]
I have experienced this issue!

The delete button allows me to delete the video (yes a window pops up confirming this) but then if i browse my library the the reference to the video is still there. When i click on the video link again, the trash bin is gone. if i play the video, it downloads again, repeating the issue.

**Comment by tzarebczan** [comment]
Closing for https://github.com/lbryio/lbry-desktop/issues/4420 which has a repro.
