### ISSUE TITLE
improve blocked channel experience

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3769]
if a user blocks a channel, we should make it clearer that they don't see content because it's blocked.

- [ ] not show the follow button
- [ ] blur out channel/cover thumbs (we recently got a complaint here)
- [ ] hide page counts
- [ ] hide content in comments/about

**Comment by er013** [comment]
... or leave channel in question unaffected. user navigated here by himself, nobody forced him here. noneed to hide channels content while at channels page. if its blocked or not is shown by block/unblock link presence.

**Comment by tzarebczan** [comment]
This messaging is now improved.
