### ISSUE TITLE
Volume control slider behavior

### ISSUE THREAD

**Issue by ProjektRoot** [lbryio/lbry-desktop#3775]
Hi :)

Would be nice if changing volume will be possible by clicking on slider (after clicking on volume button). For now, requiters to hold right mouse button and moving left, right which is a bit annoying when using touch pad.

If you guys find time for this will be cool or rather Superb Cool :smile: 

Regards and Thank You for your hard work :)

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. Which platform are you seeing this on? I can click inside the volume slider and set it. Maybe it's because the clickable area is small? Give it another shot and re-open the issue if it's not possible.

**Comment by ProjektRoot** [comment]
"Which platform are you seeing this on?"
I use Linux (Manjaro)

I've checked this today once more and it's actually working and I know what gave me false impression. Area on slider is one to one slider height (or something similar) where on timeline I can click pretty much anywhere to move slide. So it's kinda false alarm.

"Maybe it's because the clickable area is small?"
Will be possible to make it a bit bigger or same as timeline?
