### ISSUE TITLE
[desktop] Show hyperlink on status bar / copy hyperlink 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3776]
Suggestions from Discord - should be able to view where a hyperlink takes you on hover, and be able to right click > copy. 

Thanks MH/er!

**Comment by infinite-persistence** [comment]
Would like to give this a shot if it's still valid (seems like some parts have been implemented).

Questions:

1. By `status bar`, do you mean you would like to see an introduction of a bottom status bar (either a permanent one like in old Windows apps, or a transient one like in Google Chrome)?
2. I noticed that some hyperlinks already support `right click > copy link`, but there seems to be a few bugs:
[ ]On some links (I forgot which one; need to search), the `copy link` button is grayed out, and that the real way to copy the link is to left-click.  Should we just remove the left-click behavior, and stick to `right click > copy link` for all these links?
[ ] On the main page, the channel link underneath each thumbnail shows `copy ctrl+c`.  (1) The keyboard shortcut doesn't seem to make much sense here (2) It's always grayed out.  
Is there a reason for disabling them (else I'll try to enable)?
![image](https://user-images.githubusercontent.com/64950861/82653164-5d4f8d00-9c51-11ea-8c9b-685f96341141.png)
3. I assume we'll only want this behavior for link that will open externally? (i.e. for channel links like in the image above, we don't want to display the hyperlink value to reduce clutter).

**Comment by tzarebczan** [comment]
Thanks for doing some digging!
1) I'd say a transient one like Chrome
2) I'd say anything that's a hyperlink can be right clicked > copied.  The copy link has a bug too - it needs to replace # with : for the URLs. The right click is greyed out by mistake most likely. 
3) external ones should copy https:// urls, whereas the internal ones, like channel, should copy the lbry:// url? Does that make sense?

**Comment by infinite-persistence** [comment]
Adding PR for the Status Bar...

**Comment by tzarebczan** [comment]
This is done!
