### ISSUE TITLE
prevent display from sleeping when fullscreen video is playing

### ISSUE THREAD

**Issue by colinfruit** [lbryio/lbry-desktop#3789]
**Is your feature request related to a problem? Please describe.**
A user action is necessary to keep the display alive when watching videos.

**Describe the solution you'd like**
The ability to watch videos, full-screen, without having to make a user action to keep the display alive.

**Describe alternatives you've considered**
I could change my machine's display settings, but this isn't practical for the single use case of watching a video.

**Additional context**
Fedora 31 - KDE
I'd be happy to send a PR if this feature is desired.

**Comment by tzarebczan** [comment]
Thanks for filing! @colinfruit we'd appreciate any help fixing this, so please do send a PR! I think this would be expected in full screen mode, but not sure about regular mode - maybe if the video is playing? What if it stops playing in full screen mode?

**Comment by colinfruit** [comment]
Looks like this is an issue with flatpak only. Submitted this PR: https://github.com/flathub/io.lbry.lbry-app/pull/61 and will close this issue.

**Comment by tzarebczan** [comment]
Awesome, thanks for looking into that! Can we show you some [appreciation](https://lbry.com/faq/appreciation)?
