### ISSUE TITLE
allow unfollow / unblock of abandoned or blocked content

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3800]
- [ ] if you've blocked channels that have been DMCA's, you can't remove them since the follow button is hidden and they are hidden from the block list

- [ ] if you've blocked channels that have been removed, you can't unblock from since they don't resolve

**Comment by bitcoinbrisbane** [comment]
Has this been started in the branch https://github.com/lbryio/lbry-desktop/tree/feat-channelAbandon?

**Comment by kauffj** [comment]
@bitcoinbrisbane I believe that branch is to allow deletion of channels (and publishes) directly from their respective pages and is not related to the above issue. @jessopb please confirm or correct.

**Comment by bitcoinbrisbane** [comment]
Ok, Ill take a look at this today.

**Comment by infinite-persistence** [comment]
Hi @bitcoinbrisbane, are you still working on this item?

**Comment by bitcoinbrisbane** [comment]
> Hi @bitcoinbrisbane, are you still working on this item?

Sorry :(

**Comment by seanyesmunt** [comment]
@bitcoinbrisbane no problem! It was just merged! 🙂
