### ISSUE TITLE
Incorrect information on Comment Acknowledgement Modal

### ISSUE THREAD

**Issue by kcseb** [lbryio/lbry-desktop#3802]
**Bug**
On fresh / update installs of LBRY desktop, the comment modal shows with incorrect information;
"Deleting or editing comments is not currently possible. Please be mindful of this when posting."

**To Reproduce**
1. Install a fresh version of the LBRY app (Or update, I believe)
2. Click on any comment section to trigger the _Comment Acknowledgement_ modal. 
3. See second bullet point.

**Expected behavior**
Should have accurate information. 

**Screenshots**
https://imgur.com/hlcecbN.png

**System Configuration**
- LBRY Daemon version: 0.63.0
- LBRY App version: 0.43.3
- LBRY Installation ID: 2RTkKvAYNegBK7ChCvgSgLfcrQT9smihqoejSytEqtCHvDNdo4bcCD8GqwPKBXrY91
- Operating system: Linux (Linux-5.5.7-arch1-1-x86_64-with-arch)
--

**Comment by tzarebczan** [comment]
Nice catch! Wanna take a shot a PR to remove it?
