### ISSUE TITLE
Time since last reward claim is off by the timezone offset

### ISSUE THREAD

**Issue by kekkyojin** [lbryio/lbry-desktop#3805]
**Bug**
When you claim the daily reward, the 'last time claimed' count-down is off by the timezone offset amount. I've just claimed it and it shows it can be claimed again in 22:54 hours, while it should be 23:54 hours. My timezone is UTC+1.

**To Reproduce**
1. Claim the Daily Reward
2. 'Claimable again in' label is off by the timezone offset

**Expected behavior**
The reward is claimable again in 24 hours, no matter the timezone, so the offset should not be taking into count on the label.

**System Configuration**

- LBRY Daemon version: 0.63.0
- LBRY App version: 0.43.3
- LBRY Installation ID:
- Operating system: macOS 10.15.3 es-ES

**Comment by tzarebczan** [comment]
We give a buffer of ~1 hour, that's why it's shown as 23.  Thanks for checking in!
