### ISSUE TITLE
Option to show/hide reposts in Publishes (claim type filter?)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3808]
Right now, your publishes page will show your reposts, which has been confusing to some folks. It doesn't even show you reposted it, just looks like one of your claims.  We should at least mark them in the UI.

This may be a good opportunity to add a claim type filter to this area and show reposts = off by default?

**Comment by seanyesmunt** [comment]
The repost label not showing is fixed with https://github.com/lbryio/lbry-redux/pull/284 and https://github.com/lbryio/lbry-desktop/commit/80dddf8f9eb6ba11d7890a5ffbc612f4e3897a48

**Comment by tzarebczan** [comment]
This is now possible.
