### ISSUE TITLE
Video elapsed/duration in the player

### ISSUE THREAD

**Issue by alojzjakob** [lbryio/lbry-desktop#3813]
video duration in the player is strange, i want to see elapsed/total instead of the countdown to the end (dont try to reinvent the wheel and be different at any cost (KISS))

**Comment by kauffj** [comment]
Thanks for filing @alojzjakob -- I believe this is simply a videojs default

If you want to try modifying it, contributions are appreciated :)

**Comment by tzarebczan** [comment]
I think it would be here: https://docs.videojs.com/docs/api/duration-display.html

**Comment by jeffslofish** [comment]
I will take a look at this
