### ISSUE TITLE
Mark viewed content

### ISSUE THREAD

**Issue by NChechulin** [lbryio/lbry-desktop#3827]
**Describe the solution you'd like**
Mark viewed videos/articles/etc with a tick, eye icon or progress bar in the bottom part of thumbnail.
It will make using LBRY much more simple, because the same videos are recommended everywhere even if user has already seen them.

**Describe alternatives you've considered**
YouTube has this feature. You have a red line which acts like a progress bar.

**Comment by tzarebczan** [comment]
Thanks for the issue! We have this filed under https://github.com/lbryio/lbry-desktop/issues/3614
