### ISSUE TITLE
my dear sir my rewards  verification piyoush786#0229 my gmail pappugautamaz@gmail.com my chainal @PiyoushGautam

### ISSUE THREAD

**Issue by pappu7868** [lbryio/lbry-desktop#3829]
**Bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Configuration**

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Additional context**

**Comment by tzarebczan** [comment]
Please don't do that, follow the rules.
