### ISSUE TITLE
Appimage package support

### ISSUE THREAD

**Issue by philipzae** [lbryio/lbry-desktop#3843]
**Is your feature request related to a problem? Please describe.**
Running a linux distro where i cant install a .deb package

**Describe the solution you'd like**
Have a self-contained appimage that can run on any distro

**Describe alternatives you've considered**
Considered the flatpak and snap but dont want it installed on my root partition.

**Additional context**
More details can be found at the link below on how to create one.
https://github.com/probonopd/linuxdeployqt

**Comment by tzarebczan** [comment]
See lbry.com/get on Linux - there's an appimage available.

**Comment by philipzae** [comment]
Thanks. I didnt see it on the main readme.md on this github repo, so presumed it wasnt available.

**Comment by tzarebczan** [comment]
We'll get that added, as well as the snap!
