### ISSUE TITLE
App always starts in maximized window 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3859]
Not sure if this is windows only or not, but if you are in windowed mode / certain size, and then quit + restart, the app starts maximized. It used to store the last window state.

**Comment by infinite-persistence** [comment]
Seems like issue is no longer present in `0.45.2`, both in Linux and Windows.

**Comment by Prajakta-collab** [comment]
I wanna work on this issue ! I m new to open source can u plz suggest me how I can do it

**Comment by DispatchCommit** [comment]
This seems to be resolved now (not reproducible).
