### ISSUE TITLE
Make it clearer that repost count option is clickable

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3879]
Lots of users don't seem to know you can click the number next to reposts to see all reposts. Maybe make it a different color? 

Both repost and the number are underlined on hover over the number, so it may not be clear how to repost if someone does that first.

**Comment by kauffj** [comment]
Yeah this is just bad all around. What idiot added this?

**Comment by tzarebczan** [comment]
This is now on the file details, which is even harder to find.

**Comment by tzarebczan** [comment]
This is back next to the reposts, closing for now.
