### ISSUE TITLE
Blobfiles vs. Downloaded files

### ISSUE THREAD

**Issue by vitormilagres1992** [lbryio/lbry-desktop#3891]
Hi, I have recently joined LBRY on my Linux Mint desktop. During the initial setup I chose to use my external HDD for the downloaded files directory. However, after a couple weeks I noticed that my home directory was running out of space, and I looked through the directories and realized it was the blobfiles directory. I do not publish any content on my own, everything I do is download a video I like and seed it to others.

So I have a couple questions:
1 - What is the difference between those two directories (blobfiles and downloaded files)?
2 - When I seed a video to other people, where do they get the video from? Blobfiles or downloaded files?
3 - What happens if I delete blobfiles and keep downloaded files?
4 - What happens if I delete downloaded files and keep blobfiles?

Thanks

**Comment by tzarebczan** [comment]
Hey, thanks for using LBRY and the question! Check out https://lbry.com/faq/host-content for more information on how this works. You can configure which are saved in the Settings section of the app.

Majority of things work off the blob files - deleting them will cause them to be redownloaded if you watch the video again. 

Moving them to another drive is covered under: https://github.com/lbryio/lbry-desktop/issues/1966

**Comment by klesun** [comment]
@tzarebczan thanks for the partial answer, but what is the point in _Downloaded directory_ then? The article you posted only speaks about `/blobfiles/`, but it does not mention anything about data being duplicated to two directories and why it's done so.

Can I conclude from your answer that _Download directory_ does not interact with the app whatsoever, and only serves as a junk heap where all watched videos are copied? Can it be disabled somehow then?

**Comment by klesun** [comment]
Upd.: oh, it was in _Advanced settings_

![image](https://user-images.githubusercontent.com/5202330/111960191-1728bb80-8af8-11eb-8d2e-915625796825.png)

I assume the point of duplicating data to _Download directory_ is to ensure paid content did not get lost...

**Comment by klesun** [comment]
Related: https://github.com/lbryio/lbry-sdk/issues/3149
