### ISSUE TITLE
Building lbry-desktop on 32 bit Linux fails

### ISSUE THREAD

**Issue by ChrisAbela** [lbryio/lbry-desktop#3897]
I have written a script that builds lbry-desktop from source for 64bit Slackware Linux but it fails on the 32 bit installation with a SIGSEV interrupt. I note that static/daemon/lbrynet is a 64-bit executable on my 32 bit installation. May I know if I can obtain the 32bit version? Any other hints would be appreciated.

[lbry-desktop.txt](https://github.com/lbryio/lbry-desktop/files/4386945/lbry-desktop.txt)

**Comment by tzarebczan** [comment]
Thanks for trying this out and opening an issue. The SDK is built in 64 bit by default, so you'd need to build your own by following https://github.com/lbryio/lbry-sdk / https://github.com/lbryio/lbry-sdk/blob/c9305fd070fff02dd484dbe9fcdfb94bf280bbb7/.gitlab-ci.yml. I don't think we plan to maintain a 32bit binary at this time. 

See if that helps, let us know! Closing this for now.
