### ISSUE TITLE
Clicking "Use the App" button does not work if app not installed

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry-desktop#3910]
Using Chrome on Macintosh, I click the "Use the App" button from the blue banner at the bottom of the window. It opens a blank window but does not open the app.

<img width="438" alt="Screen Shot 2020-03-27 at 3 55 01 PM" src="https://user-images.githubusercontent.com/1363664/77806964-8255c400-7043-11ea-81f8-1649236f005f.png">

**Comment by jsigwart** [comment]
But I DO have the app installed on my mac!

**Comment by tzarebczan** [comment]
Works here, not sure why it's an issue in your Chrome. Maybe a reinstall of LBRY might help, or maybe it was denied/disabled in the past. 
![image](https://user-images.githubusercontent.com/8120721/77809675-213fe780-7067-11ea-8a03-da85cce3de2e.png)

**Comment by seanyesmunt** [comment]
@jsigwart do you see any errors or anything? Or just no response?
