### ISSUE TITLE
Linux Apps won't sign in, won't play content ant won't submit feedback

### ISSUE THREAD

**Issue by jg-fossh** [lbryio/lbry-desktop#3911]
Tried the Flatpak on Clear linux and the .deb package on Ubuntu 19.10 both had the same behavior. When trying to Sign In or Add Email  after clicking on the 'Continue' button nothing happens, it never signs in nor does it display any change. When clicking on the content on the front page or using the search bar the app screen just goes blank and the only way to recover the front page is with ctrl+r. And finally using the feedback form in the app might not work, when clicking on 'Submit' the button change state to 'Submitting' but no feedback is given to whether the submit process was successful or not.

**Comment by tzarebczan** [comment]
Sorry to hear, this should be fixed in the next release. We mentioned this on our releases page and on a faq, but it's not super clear.

Try this build, it should work: https://build.lbry.io/app/build-10125_commit-5d7a123/electron/
