### ISSUE TITLE
Mobile style cleanup

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#3914]
There are still a few places (mostly in the file viewer) that mobile styles can be improved. This is mostly increasing the size of buttons, and decreasing/increasing different text sizes

**Comment by kauffj** [comment]
Turning all of the buttons on `<FileActions>` into a nice grid of squares is high on my mobile want list

**Comment by seanyesmunt** [comment]
This is mostly done. I fixed up font sizes in a few places, and improved the file action buttons
