### ISSUE TITLE
Feature Request: Progress indicator for ffmpeg video transcoding

### ISSUE THREAD

**Issue by kamotswind** [lbryio/lbry-desktop#3924]
I think it would be more user-friendly to have some sort of progress indicator when utilizing the new transcoding option for publishing video content. While there is a time estimate listed before submitting, it isn't obvious that the processing is happening unless you look at which processes on the system are using CPU time.

This example, while using PHP instead of Python, should help: https://stackoverflow.com/a/11455839

**Comment by tzarebczan** [comment]
Per Discord convo, covered under https://github.com/lbryio/lbry-desktop/issues/3893
