### ISSUE TITLE
reselect channel as "replying as" when switching channels

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3926]
If you click reply and then switch channels, the channel is not updated. Thanks to @er013 for the catch.

**Comment by bitcoinbrisbane** [comment]
@tzarebczan confirm this test scenario: 

- Given a channel,
- And it has a comment,
- And I click reply,
- And I add a message,
- When I switch channels,
- Then the channel

**Comment by jtwebman** [comment]
Going to give it a try to fix this as the first issue I try in this codebase.

**Comment by tzarebczan** [comment]
@bitcoinbrisbane / @jtwebman thank you!!

**Comment by bitcoinbrisbane** [comment]
> Going to give it a try to fix this as the first issue I try in this codebase.

How did you go?  I was looking at it too.

**Comment by jtwebman** [comment]
The merge above https://github.com/lbryio/lbry-desktop/pull/4110 fixed it.

**Comment by tzarebczan** [comment]
Woohoo!
