### ISSUE TITLE
Long commenter name (channel name) causes whole comment wrapper to be expanded

### ISSUE THREAD

**Issue by er013** [lbryio/lbry-desktop#3930]
Looks like long channel name of comment author makes some unusable comment.

![2020-04-01-192903-import](https://user-images.githubusercontent.com/60119125/78163079-840ef580-7450-11ea-81ed-369eafe232a9.png)
![2020-04-01-193522-import](https://user-images.githubusercontent.com/60119125/78163085-883b1300-7450-11ea-80dc-503c1601cbf2.png)

sources:
lbry://@kauffj#f/014-illegal-walk-to-work-processed#8
lbry://@kauffj#f/walktowork013#9

**Comment by infinite-persistence** [comment]
Similarly, a long comment without any spaces will cause the same problem.  A real-life example could be a long URL pasted into the comments section (I wanted to try it out, but seems like the comment system is dead currently). 
![image](https://user-images.githubusercontent.com/64950861/82920882-738b7f00-9faa-11ea-8c70-0986f315328f.png)
Japanese characters (without spaces) seems to flow, however.

**Comment by DispatchCommit** [comment]
Looks like this should be resolved by #4331

**Comment by DaniNz** [comment]
I'm working on this issue.

**Comment by DaniNz** [comment]
Hi, check if this PR work for you guys: https://github.com/lbryio/lbry-desktop/pull/5431
