### ISSUE TITLE
Player bugs and improvements

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3946]
- [ ] add loader when waiting for data from lbry.tv (to differentiate between paused/stuck state)
- [ ] figure out what's breaking autoplay (need to press play twice sometimes?)
- [ ] figure out why the player gets muted randomly (I've seen it happen between refreshes)

**Comment by DispatchCommit** [comment]
1. is resolved.
2. is duplicated by another issue I saw earlier but forgot the number to.
3. is resolved by showing when the player is muted (though it's weird how *often* the player is being muted and I'll be reviewing when I look deeper into the strange autoplaying behavior.
