### ISSUE TITLE
Only call view api on embeds when actually played

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3957]
Example: https://lbry.com/news/2002dtf

The page loads and calls the view api, without the video being played/interacted with.

**Comment by kauffj** [comment]
(In case I don't do this: I suspect making the check on line 94 of https://github.com/lbryio/lbry-desktop/blob/master/ui/component/fileRenderFloating/view.jsx#L94 the same as line 104 will fix this)
