### ISSUE TITLE
Support opening timestamped videos on Desktop app

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#3972]
- [ ] if there's a lbry:// link somewhere that's timestamped, the app will says it's an invalid URL
- [ ] if it was passed via an open url, I think the URL options would get ignored
- [ ] on lbry.tv, we re-write the URL when it's passed, so someone can't copy/paste that into the deskto app / open in app.

**Comment by jeffslofish** [comment]
I'm going to look into this issue.
