### ISSUE TITLE
saved Draft/Description templates/signature

### ISSUE THREAD

**Issue by rainbowjaw** [lbryio/lbry-desktop#3978]
**Is your feature request related to a problem? Please describe.**
Uploading regularly or in large quantities can be tedious on LBRY.  Often in the description i'd like to keep a similar format, or have a signature which says the same thing on every post.  Right now I have to save solutions to this in another program. 

**Describe the solution you'd like**
I'd love a saved DRAFT/Description-Templates/Signature feature.  A place to store different descriptions that might be used for different types of content, or different channels that one is running.

**Comment by tzarebczan** [comment]
This is similar to https://github.com/lbryio/lbry-desktop/issues/2694, so I'll close it. Can you make that comment there please?
