### ISSUE TITLE
Most Thumpnails and Profile Pictures wont load on Tor

### ISSUE THREAD

**Issue by Thyferra** [lbryio/lbry-desktop#3980]
**Bug**
Most Video Thumpnails and Profile Pictures wont load when I'm connected to Tor, except for gif's  

**To Reproduce**
1. Connect your System to the Tor Network via Anonsurf or a Tor Router
2. Open the LBRY Desktop App
3. Look for some new Videos or purge the Application Cache

**Expected behavior**
All Video Thumpnails and Profile Pictures load as usual.

**Screenshots**

![Tor thumpnail loading issue](https://user-images.githubusercontent.com/63500554/79049404-02b72000-7c13-11ea-8c0e-22468dfb45f4.png)

**System Configuration**

- LBRY Daemon version: 0.67.2
- LBRY App version: 0.44.0
- LBRY Installation ID:
gtD6evJQfAMgJCvxxVMNhCLwmRXgRqy5mSA1w4P5qyVfAV6S2Jv5MwigCAyPrHirg 
- Operating system: Debian Linux

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. Not sure what we can do here if those URLs are not accessible via some relays you are connecting to. Some of the images may be hosted under spee.ch or a thumbnails.lbry.com url.
