### ISSUE TITLE
Improve channel invite page

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#4005]
We ask creators and users to share their invite links, but when users arrive at them, they are pretty bare - I think creators would rather showcase some of their content right on that page so it can interacted with / viewed. 

Some ideas:
- [x] show recent / top content 
- [ ] Add video player to latest / top content to page

**Comment by HarshKhandeparkar** [comment]
Should we add something like the YT intro video?

**Comment by HarshKhandeparkar** [comment]
Or something like a landing page for the user where the user can describe themself and the channel, decide to show a trailer/intro video or some picture that describes themself?

**Comment by HarshKhandeparkar** [comment]
May I work on this if you don't mind? I have already found what is to be changed...

**Comment by seanyesmunt** [comment]
Nice work on this @HarshKhandeparkar! 🙂

**Comment by HarshKhandeparkar** [comment]
Thabk you!
