### ISSUE TITLE
don't use localstorage in Embed if not available

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#4017]
Brave, with shields, turned on blocks localstorage from being accessed via an iframe. Can we see if this happens and not read/store anything but still allow the embed? 

![image](https://user-images.githubusercontent.com/8120721/79602941-67fa8d80-80b9-11ea-8dc5-f89eaca8085d.png)

**Comment by jeffslofish** [comment]
Looking into this...

**Comment by jeffslofish** [comment]
Pull request submitted =)

**Comment by chron0** [comment]
Seems to be working now in chromium on linux as well. Thanks a lot!
