### ISSUE TITLE
Don't Allow Autoplay when commenting / taking other actions

### ISSUE THREAD

**Issue by CodeDragon5793** [lbryio/lbry-desktop#4021]
There has been a few times when I would be commenting or replying to a comment on someone's video and the video would autoplay to the next video while I am actively typing. When I go back, text isn't there anymore, so I have to retype. Pretty annoying from a user exeperience standpoint.

**Comment by seanyesmunt** [comment]
Great idea. I think YouTube pauses the countdown timer when the video scrolls off the page. We should probably do something similar.

**Comment by tzarebczan** [comment]
This should also be blocked when a user is reposting/tipping while the video is playing/autoplay is supposed to trigger.

**Comment by gubatron** [comment]
this just happened to when reposting, and it's bound to happen a lot because you'd think you'd only be willing to reshare good content once you've watched all the way to the end.

Reported it, and they sent me here.
