### ISSUE TITLE
Linting the source code is currently broken

### ISSUE THREAD

**Issue by jeffslofish** [lbryio/lbry-desktop#4027]
**Bug**
According to https://github.com/lbryio/lbry-desktop/blob/master/CONTRIBUTING.md#lint we should be able to lint the code by running `$ yarn lint`. However, this currently produces an error because it is trying to lint starting at the top level "src/" directory, but there is no longer a top level "src/" directory. I can fix this issue if you let me know what directories you actually want linted.

**To Reproduce**
1. Run `$ yarn lint`

**Expected behavior**
The code should be linted.

**Screenshots**
![Screen Shot 2020-04-20 at 10 19 58 PM](https://user-images.githubusercontent.com/1240484/79828725-2e927e00-8356-11ea-8e90-e144087d408e.png)

**System Configuration**

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Additional context**

**Comment by tzarebczan** [comment]
Thanks for filing this issue! I would say it's all the directories outside of the . ones.

**Comment by jeffslofish** [comment]
Linting is still broken for me, but for a different reason. With eslint in package.json set to ^5.15.2, I get the following errors:

![image](https://user-images.githubusercontent.com/1240484/106059496-a345d600-60a7-11eb-8dfe-75b20b3facc5.png)

If I set the eslint version in package.json to the latest release (^7.18.0), then this error goes away. It appears that the older eslint has problems ignoring the directory if it ends in ".js". 

Can you reopen this issue, and I'll open a pull request to fix it?

**Comment by seanyesmunt** [comment]
@jeffslofish Weird error. Just reopened!

**Comment by jeffslofish** [comment]
Actually, I found a solution to this problem here: https://github.com/eslint/eslint/issues/10880. All you have to do is add single quotes around the glob pattern and then it will work properly. Pull request coming shortly.
