### ISSUE TITLE
Add back 3d file viewer / fix cbz reader

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#4035]
After the file page refactoring, there are issues displaying 3d files.

It seems like some wrapper class is preventing the 3d canvas from expanding in height

**Comment by tzarebczan** [comment]
There's also bugs with the cbz reader: lbry://@injustice#3/01byInjustice-GodsAmongUs-Annual0012014digitalSonofUltron-Empirecbz#7 

It won't load the first time and then crashes when you leave the page. 

@btzr-io do you think you can work on these?

**Comment by btzr-io** [comment]
> It won't load the first time and then crashes when you leave the page.

hmm I think I fixed that bug or a similar problem, I'll have to search for those commits 🙃

**Comment by btzr-io** [comment]
> It won't load the first time

See: Force non-streamable content to wait for download #4074

**Comment by btzr-io** [comment]
I fixed the 3d viewer styles, the same solution can be used for the comic viewer but the other errors are probably in the `Villain` side and I'll need to publish a new version once I figure out what is the error...

Anyway let me know if this still an issue, maybe I can fix it in the process: https://github.com/lbryio/lbry-desktop/issues/2777

**Comment by tzarebczan** [comment]
These are now fixed, will open a new issue for the CBZ requiring download first.
