### ISSUE TITLE
Don't show "download completed" notifications when watching video in fullscreen mode

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-desktop#404]
The notifications are distracting. 

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by btzr-io** [comment]
I don't see any notifications for this. Is this issue still relevant ?

**Comment by tzarebczan** [comment]
Confirmed this is still an issue.

**Comment by ChakshuGautam** [comment]
Is this still open? I would like to take this one.

**Comment by tzarebczan** [comment]
Believe it is, give it a shot!

**Comment by clay53** [comment]
This issue seems to be solved. I'm not getting this issue on Windows 10 w/ Focus Assist disabled (LBRY First testing build). Is there any other way to recreate this or is it actually just solved?

**Comment by infinite-persistence** [comment]
Can't reproduce with Linux + Cinnamon either.

**Comment by jessopb** [comment]
confirmed, cannot reproduce
