### ISSUE TITLE
Video UI is hidden until video is paused

### ISSUE THREAD

**Issue by SleepingFox88** [lbryio/lbry-desktop#4047]
**Bug**
Occasionally upon playing a video, the video that is played will not have it's UI behave properly. Normally the pause/play button, volume slider, and progress bar should all be displayed at the bottom when the user mouses over the video. This issue causes that UI to only be displayed if the video is paused.

**To Reproduce**
1. Play videos until one of the videos has this issue (not yet sure how to consistently reproduce)

**Expected behavior**
Normally the pause/play button, volume slider, and progress bar should all be displayed at the bottom of the video when the user mouses over the video.

**Screenshots**
https://streamable.com/uoexjw

**System Configuration**

App | 0.45.0
-- | --
Daemon (lbrynet) | 0.70.0
Connected Email | seanloganking@gmail.com
Reward Eligible | No
Platform | Linux (Linux-5.4.34-1-MANJARO-x86_64-with-ManjaroLinux-20.0-Lysia)
Access Token | View

daemon details:
```
{
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "desktop": "X-Cinnamon",
    "distro": {
      "codename": "Lysia",
      "id": "manjaro",
      "like": "arch",
      "version": "20.0",
      "version_parts": {
        "build_number": "",
        "major": "20",
        "minor": "0"
      }
    },
    "lbrynet_version": "0.70.0",
    "os_release": "5.4.34-1-MANJARO",
    "os_system": "Linux",
    "platform": "Linux-5.4.34-1-MANJARO-x86_64-with-ManjaroLinux-20.0-Lysia",
    "processor": "",
    "python_version": "3.7.7",
    "version": "0.70.0"
  }
}
```

**Comment by SleepingFox88** [comment]
I left my ``Installation ID`` out of my listed System Configuration details. Can I assume it's safe to share with others?

**Comment by tzarebczan** [comment]
Thanks for opening the issue! Can you check if this also happens in https://github.com/lbryio/lbry-desktop/pull/3990 - there's a big player refactor there.

**Comment by SleepingFox88** [comment]
```
[logan@logan-pc lbry-desktop-0c8dad59eebd7c8b71fedc55d5f982036d5b5934]$ yarn compile:electron
yarn run v1.22.4
$ node --max_old_space_size=4096 ./node_modules/webpack/bin/webpack.js --config webpack.electron.config.js
internal/modules/cjs/loader.js:955
  throw err;
  ^

Error: Cannot find module '/home/logan/Downloads/lbry-desktop-0c8dad59eebd7c8b71fedc55d5f982036d5b5934/node_modules/webpack/bin/webpack.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:952:15)
    at Function.Module._load (internal/modules/cjs/loader.js:835:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

@tzarebczan that branch is not yet compiling for me. I can check back once they work the kinks out. Is there a specific commit that you think might have fixed this issue?

**Comment by keikari** [comment]
This can be reproduced by making the video to go to floating player. After that the player UI stays hidden until paused.

**Comment by kauffj** [comment]
@seanyesmunt can you assist on this ticket?

**Comment by seanyesmunt** [comment]
Yeah I will look into this

**Comment by tzarebczan** [comment]
Can't seem to reproduce here. @keikari can you see if it still happens here: https://github.com/lbryio/lbry-desktop/releases/tag/v0.45.1-rc.5 

@SleepingFox88 this is now merged to master, try there?

**Comment by keikari** [comment]
@tzarebczan I tested with appimage and now it worked normally. Also lbry.tv player works normally now.
Wow! That got handled quick.
