### ISSUE TITLE
'Related' column (proposal)

### ISSUE THREAD

**Issue by ProjektRoot** [lbryio/lbry-desktop#4055]
Hi guys, can you make *Related* column look like tab/column on left. Don't know how to explain this, so I've modified screenshot :)

![screenshot](https://i.imgur.com/FUtgnnK.png)

Thanks for your hard work! Regards :)

**Comment by HarshKhandeparkar** [comment]
Ty @ProjektRoot. You can put the image link in `![title](https://link.to.image)` and it will show an image preview.

**Comment by ProjektRoot** [comment]
Done :) Thank you @HarshKhandeparkar

**Comment by HarshKhandeparkar** [comment]
Thanks a ton! You can work on this if you want to.

**Comment by ProjektRoot** [comment]
With pleasure but there is one problem. My programming knowledge is limited to print 'Hello World' :D

**Comment by HarshKhandeparkar** [comment]
Oh. That's not an issue. If you ever want to learn web dev, you are always welcome. :smile:
