### ISSUE TITLE
[mobile] Show Discover New channels link / Manage tags on Your Tags page

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#4063]
Can't discover new channels on lbry.tv mobile. The UI works fine when you go to it directly (via landscape). 

Also can't manage tags from the your tags page.

**Comment by infinite-persistence** [comment]
Both buttons are available in today's code:

![image](https://user-images.githubusercontent.com/64950861/86586621-c2b9cc00-bfba-11ea-92fe-dd6af00f6c65.png)
