### ISSUE TITLE
Add referral string to embeds

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#4064]
Right now it's not generated until you navigate to the invites page. We would need to fetch it somewhere for embeds, then add it to the lbry.tv link

**Comment by tzarebczan** [comment]
I think this is really useful for tracking users who are referred from creators websites - unless they visit via the invite link, they won't get their referrer set. 

Similar to https://github.com/lbryio/lbry-desktop/issues/4668 , this should be an option.

**Comment by tzarebczan** [comment]
This was done
