### ISSUE TITLE
New channels dropdown alignment is off

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#4072]
![image](https://user-images.githubusercontent.com/8120721/80262504-9c42f080-865b-11ea-99e0-df51109f0646.png)
Thanks to Lav for spotting this one.

**Comment by bitcoinbrisbane** [comment]
How can I replicate this?  Seems fine on mine.

**Comment by tzarebczan** [comment]
Hey @bitcoinbrisbane , thanks for poking at some of the issues here, welcome to LBRY! 

I'm seeing the above both on the desktop and web - maybe it has something to do with the channels having a title vs not? You'd edit the title on the channel edit page. Have you tried with multiple channels too?
