### ISSUE TITLE
"Choose file" broken, Can't upload videos, channel avatar, background image

### ISSUE THREAD

**Issue by gubatron** [lbryio/lbry-desktop#4073]
**Bug**
Every time I try to upload an avatar or background image for a new channel, or a video for a channel I'm forced to go to lbry.tv to do so (or use URLs in the case of avatars/channel background), the file picker isn't working.

**To Reproduce**
![Screen Shot 2020-04-24 at 5 22 00 PM](https://user-images.githubusercontent.com/163977/80264094-25542a80-8650-11ea-8435-91f0f8e1dc2c.png)
None of the "Choose File" buttons will open the File picker dialogs.

**System Configuration**
macOS Catalina 10.15.3
LBRY Version 0.45.0 (0.45.0.10890)

```$ curl 'http://localhost:5279' --data '{"method":"version"}'```
```json
{
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "lbrynet_version": "0.70.0",
    "os_release": "19.3.0",
    "os_system": "Darwin",
    "platform": "Darwin-19.3.0-x86_64-i386-64bit",
    "processor": "i386",
    "python_version": "3.7.4",
    "version": "0.70.0"
  }
}
```

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. I don't think we've ever seen this reported from other Mac users, so it could possibly be a local issue. Can you check the console (ctrl-shift-i) to see if there are any errors when you do this?

**Comment by gubatron** [comment]
Tried to replicate and it didn't happen this time, grrr.

Also Ctrl-shift-i, or Cmd-shift-i isn't bringing up the debug console, it'd be nice to have it available to better report issues.

It happens quite a lot that you're playing a video, you hit Back, and the video keeps playing and you can't see where it is, only hitting forward nav takes you back and then you can stop it.

I suppose it's a bug with trying to bring the video in mini-player floating mode.

And also when that mini player is floating on the bottom left, it happens to cover the "Publish" button, I had an instance where it took me a while to figure out where the publish button was because a video player kept covering it (UX design issue), perhaps it'd be best if it floated on the top right.

**Comment by Salmawati1** [comment]
Upload slow please repair

**Comment by tzarebczan** [comment]
Closing this issue. I think the others are already logged. https://github.com/lbryio/lbry-desktop/issues/2750
