### ISSUE TITLE
Incorrect render mode on some files

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry-desktop#4075]
**Bug**
Some files are reported as `Video` on the `renderMode` prop of `fileRender` component.
```
File extension: .stl
Content Type:  application/octet-stream
````

**To Reproduce**
1. Go to any url from the examples list.
2. See error...

**Expected behavior**
Use the correct viewer for this file, or just don't try to render.

**Examples**

https://lbry.tv/@GRAVITYSHAPES:f/free-3dprint-bowl-19cm-voronoi-style-no4-stl:8
https://lbry.tv/@GRAVITYSHAPES:f/stl:b

**Comment by btzr-io** [comment]
@seanyesmunt Any reason to have `application/octet-stream` listed as `FORCE_CONTENT_TYPE_PLAYER`
https://github.com/lbryio/lbry-desktop/blob/eaca77d39430fa6f64af054ac3705c687935c18f/ui/constants/claim.js#L14

**Comment by DispatchCommit** [comment]
This looks resolved by the 2 linked PR's that are merged.
