### ISSUE TITLE
Show total balance on "Support This Claim" popup

### ISSUE THREAD

**Issue by eatdostacos** [lbryio/lbry-desktop#4081]
**Is your feature request related to a problem? Please describe.**
There isn't a problem, just a feature that would be useful.

**Describe the solution you'd like**
Put your current total balance on the "Support This Claim" popup box.

**Describe alternatives you've considered**
Maybe change the balance in the top right to be more precise.

**Additional context**
When I want to support a new video and I have over 1000 lbc the top right balance is abbreviated to be (ex. 2.92k instead of 2924) so I have to guess and increase or decrease my amount of support until I get to the total exact amount I have. If you put the exact amount on the "Support This Claim" popup you could just put the total amount of support right on and not have to guess your total number of LBC.

**Comment by tzarebczan** [comment]
We have this on mobile mode already, shouldn't be hard to add. Thanks for opening the issue!
