### ISSUE TITLE
Publishes show max of three tags on "Publishes" page

### ISSUE THREAD

**Issue by eatdostacos** [lbryio/lbry-desktop#4082]
**Bug**
The "Publishes" page only shows up to three tags per publish even though I have five tags on many of my videos.

**To Reproduce**
1. Go to 'Publishes' Page
2. Look at all your publishes
3. See error
4. Then click on a video with more than three tags and see all five tags listed in the video description.

**Expected behavior**
All five tags should show up next to each video.

**System Configuration**

- LBRY Daemon version: 0.70.0
- LBRY App version: 0.45.0
- LBRY Installation ID: 8a4pGqg7iUrLUeTuoahENKam8rfqcdfgCaagCWohC9KTU77z4TZ7qYK936xGwpZmCY
- Operating system: Windows 10 Home

**Comment by tzarebczan** [comment]
The claim previews you see only show a few tags, not all of them. This is normal and you can see the rest into the file page. Eventually we can add a mouse over that would show all of them.
