### ISSUE TITLE
Sometimes no videos show as downloaded even though they have been

### ISSUE THREAD

**Issue by eatdostacos** [lbryio/lbry-desktop#4083]
![lbrybug](https://user-images.githubusercontent.com/64234158/80322150-e2bd5a00-87d7-11ea-96a6-019563299504.png)

**Bug**
I have previously downloaded videos to my PC, but LBRY says I don't have them downloaded, and downloads the same video and saves it right next to the copy already saved from earlier. This has happened before, but doesn't happen all the time.

**To Reproduce**
1. Go to look at any video I have downloaded
2. Hover Over the video
3. It wants me to download it again
4. When you click on the video it downloads again and doesn't show as downlloaded in the file details section until it is done downloading again

**Expected behavior**
It should show as already downloaded.

**System Configuration**

- LBRY Daemon version: 0.70.0
- LBRY App version: 0.45.0
- LBRY Installation ID: 8a4pGqg7iUrLUeTuoahENKam8rfqcdfgCaagCWohC9KTU77z4TZ7qYK936xGwpZmCY
- Operating system: Windows 10 Home

**Additional context**
The picture at the top shows that I have it downloaded in my downloads folder for lbry and it still shows the little things saying I can download it. This is happening for all the videos.

**Comment by tzarebczan** [comment]
This will happen if videos are updated with a new file. There's an existing issue that covers redownloading and this requires a bigger revamp of our library section also.

Thanks for opening and hope that makes sense!
