### ISSUE TITLE
Add Tooltips To Channel Action Buttons

### ISSUE THREAD

**Issue by HarshKhandeparkar** [lbryio/lbry-desktop#4085]
### First Timers Only
This issue is reserved for people who haven't contributed to our codebase before, or never contributed to Open Source. [About First Timers Only](https://www.firsttimersonly.com/).

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new** and looking through our general [help wanted](https://github.com/lbryio/lbry-desktop/labels/help%20wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### What is to be done?

Currently only the `Tip` button on the channel pages has a tooltip.
![no-tooltip](https://user-images.githubusercontent.com/34770591/80383402-25a72c80-88c1-11ea-9480-eabcbd49942c.gif)
 Having tooltips on the other buttons will improve consistency and also be helpful.

#### :mag_right: Files To Look Into:

1. The `Tip` button, for reference.
https://github.com/lbryio/lbry-desktop/blob/8b6c64441566f345cc9204d1906340526e741743/ui/page/channel/view.jsx#L203-L209

2. The `Follow/Unfollow` button.
https://github.com/lbryio/lbry-desktop/blob/master/ui/component/subscribeButton/view.jsx

3. The `Share` button.
https://github.com/lbryio/lbry-desktop/blob/master/ui/component/shareButton/view.jsx

4. The `Block` button.
https://github.com/lbryio/lbry-desktop/blob/master/ui/component/blockButton/view.jsx

### 📋 Step by Step

- [ ] :scroll: **Read The CONTRIBUTING File**: We welcome contributions from everyone, the [CONTRIBUTING](https://github.com/lbryio/lbry-desktop/blob/master/CONTRIBUTING.md) will help you get started.

**NOTE**: Useful links:
-    - [Git Commands](https://www.siteground.com/tutorials/git/commands/)
-    - [Installation Instructions](https://github.com/lbryio/lbry-desktop#running-from-source)

- [ ] **Fork This Repository**: A [fork](https://help.github.com/articles/fork-a-repo/) is a copy of this repository that is stored under your github account. A fork can be used to test out changes separately and then request to add those to the main repository as well!

- [ ] :raising_hand: **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] **Create A New Branch**: A [branch](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/about-branches) is used to test new changes before they are merged with the stable `master` branch. You can create a new branch in the terminal. Make sure to name it descriptively!

- [ ] :memo: **Make The Requested Changes**

- [ ] :white_check_mark: **Commit Your Changes**: A Git [commit](https://help.github.com/en/desktop/contributing-to-projects/committing-and-reviewing-changes-to-your-project#about-commits) is a change that is finalized and recorded in the branch.

- [ ] :twisted_rightwards_arrows: **Start a Pull Request(PR)**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [open a PR from the browser](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork).

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

:speech_balloon: :bell:  - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need it if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://github.com/lbryio/lbry-desktop/labels/help%20wanted). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by HarshKhandeparkar** [comment]
Is this one fine for first-timers?

**Comment by seanyesmunt** [comment]
Yep!

**Comment by calvincodes** [comment]
Hi! Can I work on this issue? Thanks.

**Comment by HarshKhandeparkar** [comment]
Sure. Go ahead.

**Comment by HarshKhandeparkar** [comment]
@seanyesmunt new contributor already :rocket:!

**Comment by HarshKhandeparkar** [comment]
@calvincodes you can ask any difficulty here.

**Comment by calvincodes** [comment]
Thanks @HarshKhandeparkar. Sure, will do.

**Comment by calvincodes** [comment]
@HarshKhandeparkar What should the language/content of these messages be?

**Comment by HarshKhandeparkar** [comment]
Language should be English. Content can be whatever you feel is Intuitive.
