### ISSUE TITLE
Theme setting is reset when launching the Lbry app

### ISSUE THREAD

**Issue by rzelnik** [lbryio/lbry-desktop#4112]
**Bug**
When I set dark theme in the Settings > Appearance, the setting is remembered in 2-3 starts of the application, then it is reset back to Light theme (white background, dark text).

**To Reproduce**
1. Go to Settings > Appearance > Theme > Dark
2. Quit the Lbry app or restart the computer
3. Start Lbry again
4. The theme setting is Light

**Expected behavior**
I would expect the theme setting to remember the Dark Theme.

**System Configuration**

App | 0.45.1-rc.2
Daemon (lbrynet) | 0.70.0
Platform | Linux (Linux-5.4.0-28-generic-x86_64-with-Ubuntu-20.04-focal)
Installation ID | 61S5JWdiZ5nCb12TFuWN1uS5cntauBUFRZ7MQ8vkR2xorK5kZssijvSAReSpYRzv9t

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. Does this happen each time? Are you also signed out of the app? We are aware of issues where this happens randomly sometimes and have a separate issue to track saving this to the wallet. 

If it happens each time , you may have local issues with your user profile on Windows.

**Comment by rzelnik** [comment]
I noticed many occurences of this issue. It happens every third or every fourth start of LBRY desktop.
I don't log out when closing the app, I am still logged in.
I can check my config file if it helps. Where is the Theme setting stored?
