### ISSUE TITLE
doFetchFileInfos breaking

### ISSUE THREAD

**Issue by bitcoinbrisbane** [lbryio/lbry-desktop#4117]
On `yarn dev` off master branch, its breaking on https://github.com/lbryio/lbry-desktop/blob/master/ui/redux/actions/app.js#L355

Commenting out that line allows the app to start.

![image](https://user-images.githubusercontent.com/8411406/80856639-c9f8ec80-8c8e-11ea-84b2-87a5f387856d.png)

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. Did you have any downloaded content or was this your first time starting up?

**Comment by seanyesmunt** [comment]
@bitcoinbrisbane I just tested a fresh clone of the repo and it worked for me. That error looks like `lbry-redux` might not be setup properly on your computer. You might just need to re-run `yarn`, and possibly delete the `node_modules` folder before running that.
