### ISSUE TITLE
Rebrand and refunction of "support" button. 

### ISSUE THREAD

**Issue by rainbowjaw** [lbryio/lbry-desktop#4118]
**Is your feature request related to a problem? Please describe.**

This is an optimization recommendation. **My main point is making this button do more with fewer steps would lead to a bit more community curation/more accurate feeds to what people are interested in**

There are _barriers to entry_ on using "support", staking tokens for the sake of boosting content when a user *like* another users content (rather than their own video).
- just a guess, but majority of supports are going to a users own content.  If supports are even simpler to give, users might support content they are viewing more. 
- supports can be a little vague on what kind of effect they will have (how much do I support?).  To support 
-removing support is a barrier, it goes forgotten requires search to remove.  
-unused lbry change sits idle, or possibly for too long in a support where it no longer is helpful.  
- as an engagement "support" is a bit bland 

**Describe the solution you'd like**
Minimize Actions (currently: **click, think how much, type how much, click ok**)
Replace "support button with two" A primary "Instant support" and a smaller "custom" support button. This primary button would be designed to act similar to a "like" (actions: **just click**) button on a youtube type platform. 
Set parameters in the settings for a instant support button.  The options would ideally be:
-portion of remaining balance to support
-minimum LBC to keep in wallet
-time frame to keep supported (automatic support removal) 

they automatically support the video with a portion of their available balance.  if this could be a timed setting, it could unsupported automatically after e.g. 24 hours.   This can be a way that users can organically support video with fewer steps.  

**Describe alternatives you've considered**

If automated support removal is a step too far, an alternative might be:
Add an easy way to remove all supports that are x(hours) old.  Design with the thought: open lbry, reclaim old supports to recharge, on to boost content with instant support.

**Comment by tzarebczan** [comment]
Thanks for the detailed write up. There are some immediate things we can do as part of https://github.com/lbryio/lbry-desktop/issues/3822 and can take some ideas here. 

Automated support removal won't be a thing, but we want to make it easier eventually but we need sdk support for it (will make sure we have an issue filed for that ).

**Comment by tzarebczan** [comment]
We've made some progress with https://github.com/lbryio/lbry-desktop/issues/3822. We won't be doing any automated type stuff with supports for now, but do hope to make this easier down the road with SDK improvements around management.
