### ISSUE TITLE
Keyboard shortcuts

### ISSUE THREAD

**Issue by m160** [lbryio/lbry-desktop#4120]
Could I suggest to just blatantly copy the keyboard shortcuts from this other video platform?

`Shift` + `?` to show a map of the keyboard shortcuts available:
![image](https://user-images.githubusercontent.com/34570404/80915972-99c45300-8d4d-11ea-8062-3d26ed9c4ecb.png)

In particular I miss the `Shift` + `.`/`>` to increase playback rate, but hey, why not just copy all the shortcuts that apply to LBRY... for consistency :)

**Comment by tzarebczan** [comment]
Thanks for the issue and write up, can you please add it to https://github.com/lbryio/lbry-desktop/issues/1395
