### ISSUE TITLE
cbz/cbr file page shows download button first, and then viewer after download

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#4141]
It should just show the viewer and invoke the download.

lbry://@mxlinuxpl#f/mx-linux-polska-news-test-cbr#c

**Comment by btzr-io** [comment]
I think that's the intended behavior for files that need to be downloaded first ?

**Comment by tzarebczan** [comment]
Is that how 3d files work too? We used to just show the viewer and that would download it.

**Comment by btzr-io** [comment]
> 3d files work 
yes

> We used to just show the viewer and that would download it.

Ok, I'll see if I can show the viewer
