### ISSUE TITLE
Blank toggle preview on the publish page

### ISSUE THREAD

**Issue by m160** [lbryio/lbry-desktop#4144]
**Bug**
The toggle preview goes blank in the new update

**To Reproduce**
1. Go to the publish page
2. Type something in the description
3. Click toggle preview

**Expected behavior**
Formatted preview of the description

**Screenshots**
![image](https://user-images.githubusercontent.com/34570404/81196746-566d1d00-8fb7-11ea-8b1d-be0dfe8192b3.png)

**Comment by tzarebczan** [comment]
Hmm, it seems to be working here. Can you try again? What did you type?

**Comment by m160** [comment]
It happened when I edited the description of an existing claim. The issue seem to have disappeared now though, not sure what happened there.

**Comment by tzarebczan** [comment]
Great!
