### ISSUE TITLE
Outdated CONTRIBUTING.md

### ISSUE THREAD

**Issue by swedneck** [lbryio/lbry-desktop#4149]
**Bug**
https://github.com/lbryio/lbry-desktop/blob/master/CONTRIBUTING.md is out of date, it refers to src/platforms/electron/index.js which no longer exists.

**Comment by HarshKhandeparkar** [comment]
This is a nice first-timers-only candidate!

**Comment by HarshKhandeparkar** [comment]
Moved to #4166
