### ISSUE TITLE
Video player does not work on iPad

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#4150]
Getting reports that our video player just shows a black screen on ipad
![image1 (1)](https://user-images.githubusercontent.com/8120721/81308252-8ec03a00-904f-11ea-999c-ac8ddc05ae0f.png)

**Comment by jeffslofish** [comment]
It appears that both the native and videojs controls are hidden. I think we should show one or the other. I believe the video is not playing when you try to autoplay a non-muted video in iOS, so if the controls were there, the user could manually start the video.

If we want to show native controls, we need to add

`
html5: {
    nativeControlsForTouch: true,
},
`
here: https://github.com/lbryio/lbry-desktop/blob/master/ui/component/viewers/videoViewer/internal/videojs.jsx#L79.

If we want to show the videojs controls, we need to unhide them here: https://github.com/lbryio/lbry-desktop/blob/master/ui/scss/component/_file-render.scss#L292

@seanyesmunt What do you think?

**Comment by seanyesmunt** [comment]
That sounds good. I don't see the video-js controls on my iPhone, maybe iPad doesn't show it's own native controls unless that flag is passed in?
