### ISSUE TITLE
Dark theme for markdown editor

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry-desktop#4154]
**Bug**

The current markdown editor needs a better dark theme, right now it only changes the background color of the form field, but not the text colors.

Related issues, but there are probably more: 
- [ ] Inconsistent cursor color on dark theme, its hard to see.
- [x] Hyperlinks on markdown hard to read in dark mode #3468

**Expected behavior**
A good contrast of colors for both themes : light / dark

**Comment by btzr-io** [comment]
This will be a tedious process, since codemirror classes are mixed / overwrited by easymde

**Comment by infinite-persistence** [comment]
Hi, do you still want help for this one?
