### ISSUE TITLE
Confusing upgrade process (app should quit, not minimize into tray).

### ISSUE THREAD

**Issue by BitWizzard** [lbryio/lbry-desktop#4158]
**Bug**

When upgrading the app to a newer version on Ubuntu, a dialog pops up that says "Close the app an you will be prompted to install the new version..." and there is a button to close the app.

When I pressed the button, the app closed and I was waiting to be prompted about the installation, but nothing was happening. I thought that it didn't work. But then I noticed the app didn't quit, just minimized into the tray area. I had to click on the tray icon and select "Quit"

This is confusing for users.

**To Reproduce**
1. When the upgrade dialog ("There is a new version") pops up, click the button which starts the upgrade
2. Let the new version download
3. On the next dialog, click "Close the app"  (not sure about the exact text)

**Expected behavior**
The app should quit and not just minimize into tray.

**System Configuration**

App: 0.45.1 (after upgrade, but when the issue occurred, I had the previous version)
Daemon (lbrynet): 0.72.0
Platform: Linux (Linux-5.3.0-51-generic-x86_64-with-Ubuntu-18.04-bionic)

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble and thanks for the report. I'll give this a shot and see if it works...I know it definitely used to close the app - wonder if something hung up on your end this time.

**Comment by tzarebczan** [comment]
Just tried it and it takes a few seconds to close after it shuts down the app. But if you wait, it does so and then brings up the software center updater.
