### ISSUE TITLE
Update snap

### ISSUE THREAD

**Issue by jcalfee** [lbryio/lbry-desktop#4169]
**Bug**
Snap is out of date

**To Reproduce**
1. sudo snap refresh
2. lbry
3. UI says "Upgrade is ready", the "install" button does not upgrade

![image](https://user-images.githubusercontent.com/204121/81520261-6bc0af00-9309-11ea-87fc-1c6e8db9642a.png)

**Expected behavior**
Update snap please

**System Configuration**

- LBRY Daemon version:0.38.5
- LBRY App version:0.34.2
- LBRY Installation ID:
- Operating system: Linux (Linux-4.9.0-12-amd64-x86_64-with-debian-9.12)

**Comment by tzarebczan** [comment]
The snap is community run, we'll reach out to maintainer and get it added to the readme. Sorry for the trouble. 

For best results with auto update, we'd recommend the aur.
