### ISSUE TITLE
More security features

### ISSUE THREAD

**Issue by littlemadhatter** [lbryio/lbry-desktop#4188]
**Is your feature request related to a problem? Please describe.**
I'd like to see more security options to protect one's account

**Describe the solution you'd like**
Options to disable magic link, disable password reset when signing in, 2FA and/or require password every time you come back to the app/web (like a auto-sign out option)

**Describe alternatives you've considered**
None

**Additional context**
When changing these settings, require password, email confirmation and 2FA (if enabled)

**Comment by tzarebczan** [comment]
Thanks for opening the issue! I'll file our API side work to get the magic link disabled, and some of the other features are on our long term roadmap.
