### ISSUE TITLE
clipboard bug

### ISSUE THREAD

**Issue by lunodin** [lbryio/lbry-desktop#4191]
![1](https://user-images.githubusercontent.com/64392671/81998825-10b9ef80-965c-11ea-87c0-0415e6e3ae3a.jpg)
![2](https://user-images.githubusercontent.com/64392671/81998830-11eb1c80-965c-11ea-8b5a-0fdbaec943af.jpg)

*Buffer can be done using empty characters*
I assume that an attacker could execute malicious code.

My gmail: @falertoll

**Comment by lunodin** [comment]
Buffer can be done using empty characters
I assume that an attacker could execute malicious code.

My gmail: @falertoll

**Comment by tzarebczan** [comment]
Thanks for opening the issue - can you give us more information as to what the attack would be and what claims the above are?

**Comment by lunodin** [comment]
> Thanks for opening the issue - can you give us more information as to what the attack would be and what claims the above are?

I dont know. This is at the discretion of the attacker.

**Comment by tzarebczan** [comment]
It would just fail, I don't think there's any issue here.
