### ISSUE TITLE
[French] Following menu/page title not great

### ISSUE THREAD

**Issue by Suisse00** [lbryio/lbry-desktop#4192]
### What is to be done?
Hi!
You use the translation key `Following` as for the menu option AND page title to list videos from your subscriptions.

- In french, if we are using the same word, it would need to be plural in this specific case. Which we can't because it would also change the button in a channel that allow you to follow/unfollow.

  Alternatively, we could use another word like `Subscriptions`, which seems to already make more sense in this particular case.

- Using `Following` also is also misused/would be misunderstood:
  - The french equivalent, in this context, is mainly used to mean "X that are following me". In fact, you mean the opposite, channels that I do follow.
  - The other thing that botter me (in english as well) is that we may think it is the page that will ultimately manage our subscriptions. Which is way off, it will list videos from our subscriptions.

With all those points it could make more sense to use `Subscriptions videos` or `Following channels` (which look weird to me in english) if we want to use the same word.

**NOTE:** I know this is an issue, I don't mean to have the right answer and I'm no way linguistics. Feel free to suggest or/and comment.

#### :mag_right: Files To Look Into:
For the menu item: https://github.com/lbryio/lbry-desktop/blob/master/ui/component/sideNavigation/view.jsx#L106

For the page title: https://github.com/lbryio/lbry-desktop/blob/master/ui/page/channelsFollowing/view.jsx#L28

### Suggested labels
help wanted, level 0, area: subscriptions (I think, otherwise/and channel), good first issue

Possibly: needs: exploration

**Comment by tzarebczan** [comment]
Thanks for filing this issue! Would you want to take a shot at fixing it?

**Comment by Suisse00** [comment]
I could, however, I just need a hint of what to use in english.

**Comment by ingridxx** [comment]
I agree with @Suisse00 that in the menu bar, using `subscriptions` as a translation key would be more appropriate when translated into french (Abonnements).

**Comment by seanyesmunt** [comment]
Maybe the french translation just needs to be updated?

**Comment by Suisse00** [comment]
It won't solve the issue since the current translation key (`Following`) is used in two contexts. We would change it and break the other way.

I didn't yet write anything yet since I did notice "Subscription(s)" keys, thought I also found some code using this wording and I wanted to check if it wouldn't be a word already use (internaly or from the UI) for other purpose. (Like some subscription payment schema)

An alternative could be to create a new key with a context key (like Following_Menu). In english it would remain `Following` but in other language (read: in french) be my suggestion.

**Comment by infinite-persistence** [comment]
`Close`
- The ability to split a string into multiple contexts has been added in 2020.
- If there are more strings that need to be split, submit a request in Github indicating the affected string.  We'll handle it on a case-by-case basis when reported by translators.
