### ISSUE TITLE
Create the posibility to remove the inexistent blocked channels

### ISSUE THREAD

**Issue by TigerxWood** [lbryio/lbry-desktop#4199]
#### Issue Summary

Currently in the window where you can manage the blocked channels there is no possibility to delete the channels that no longer exist.

![Blocked_channels](https://user-images.githubusercontent.com/29385229/82092710-7496f380-9702-11ea-9138-aac7f10f6a9d.jpg)

**Comment by TigerxWood** [comment]
Thanks for the transfer, I didn't know or maybe can't remove from lbry.com and move to desktop.

**Comment by infinite-persistence** [comment]
Duplicate of #3800
