### ISSUE TITLE
Should be able to double-click in header of app to maximize window

### ISSUE THREAD

**Issue by jeffslofish** [lbryio/lbry-desktop#4207]
**Is your feature request related to a problem? Please describe.**
There is no easy way to maximize the app window without going into "full screen" mode.

**Describe the solution you'd like**
I would like to be able to maximize the app window (but not use "full screen" mode) without having to drag the app window to the upper-left of my screen and then drag the lower-right corner of the app to the lower right edge of the screen. You can do this on most applications these days by double-clicking in the header of the app.

I am using macOS, but I believe this should work the same in all operating systems.

**Comment by jeffslofish** [comment]
I'm looking into this now...

**Comment by TigerxWood** [comment]
I tested in Windows. So far it seems it works here too.
