### ISSUE TITLE
Chromebook app fails to start

### ISSUE THREAD

**Issue by bit4man** [lbryio/lbry-desktop#4237]
After having install the lbry app and configured it, everything looked fine. A few days later, I try to re-launch the app, and it just fails loading after I enter my key-password.  Repeatably hitting reload just goes to the same screen.  I'm unable to determine what version of the app is running.

**Comment by tzarebczan** [comment]
Sorry about the trouble. Which app are you running?
Have you tried rebooting the machine? 

Can you send us your log file to hello@lbry.com https://lbry.com/faq/how-to-find-lbry-log-file
