### ISSUE TITLE
Feature request: Delete/Abandon channels via channel page

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#424]
Add delete channel button to channel pages.

**Comment by liamcardenas** [comment]
This is available in the transaction list

**Comment by liamcardenas** [comment]
@tzarebczan thoughts?

**Comment by tzarebczan** [comment]
We should add this to channel pages. The tx list isn't the most intuitive place to look for this.

**Comment by tzarebczan** [comment]
Users are getting confused about where to delete channels from - sometimes it appears under Channel on the wallet page, but other times under Updates if it was updated.  It should be possible from the channel page + with a strong warning (https://github.com/lbryio/lbry-desktop/issues/3387)

**Comment by tzarebczan** [comment]
We should add this now that the warning is stronger.
