### ISSUE TITLE
Markdown "Quotes" display in Desktop is bad

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4241]
**Bug**
The markdown Quotes look bad in the Desktop.  It looks correct in lbry.tv.  Here's a comparison of a comment section of the same page:
![image](https://user-images.githubusercontent.com/64950861/82807523-80c94080-9eba-11ea-9f6d-553eb4357521.png)
**Expected behavior**
Minor differences between platforms should be ok, but the extra spaces is really odd.

**System Configuration**
```
App: 0.45.2
Daemon (lbrynet): 0.73.1
Platform: Linux (Linux-5.3.0-51-generic-x86_64-with-LinuxMint-19.3-tricia)
```

**Comment by btzr-io** [comment]
duplicate of **Extra spacing in markdown quotes in comments** #3522

It should be fixed on `master`.

**Comment by infinite-persistence** [comment]
Sorry, I wasn't thorough enough in my github search.  Works fine in today's `master`.

**Comment by infinite-persistence** [comment]
### Re-opening
There is one unhandled case:  "extra space in bullets in quotes". Github's MD doesn't have show extra space.
![image](https://user-images.githubusercontent.com/64950861/84570735-f80b3980-adc1-11ea-879e-e1d0a3915d4e.png)

**Comment by infinite-persistence** [comment]
Closing this (consolidate to 4401)
