### ISSUE TITLE
an "open.lbry.com" url-redirect to "lbry.tv" fails because of a upper/lowercase issue

### ISSUE THREAD

**Issue by r-hmn** [lbryio/lbry-desktop#4284]
**Bug**
I paste an "open.lbry.com" link in a browser, and the link ends up on the wrong "lbry.tv" page, because of an upper/lowercase issue. 

**To Reproduce**
0. i copied an url from a video thumbnail in the Windows LBRY 0.45.2 desktop app.

1.  paste that link in a browser
https://open.lbry.com/@Fasting#a/Why-Dry-Fasting-Health-Benefits,-OMAD,-Ketosis,-Metabolic-Water,-BMR#4

2. notice the redirects happen, and you end up at an empty channel.
But the channel writes @ fasting  (with a lowercase F) while the title text says "Fasting"
This is not the correct channel..

3. Search using LBRY.tv for  @ fasting.
You notice there are two results. @ fasting and @ Fasting.
(The wrong one. Empty, no decorations, no publications):
https://lbry.tv/@fasting:8
(The other one which it should have directed to, because that channel contains the video i copied the link of using my lbry desktop app.):
https://lbry.tv/@Fasting:a

4. The url used in step .1  should have redirected to @ Fasting, not @ fasting,
because on that channel, the video i copied the link of, actually exists.
I am not sure how @ fasting came to exist. Maybe it's part of the same problem.

**Expected behavior**
Paste the link in the browser:
https://open.lbry.com/@Fasting#a/Why-Dry-Fasting-Health-Benefits,-OMAD,-Ketosis,-Metabolic-Water,-BMR#4
End up on the page:
https://lbry.tv/@Fasting:a/Why-Dry-Fasting-Health-Benefits,-OMAD,-Ketosis,-Metabolic-Water,-BMR:4

**Screenshots**
n.a.

**System Configuration**
it's all happening at the lbry website.

**Additional context**

**Comment by tzarebczan** [comment]
Thanks for opening this issue. Where did you grab that URL from? Since URLs don't support #, we use : instead on our share pages.

**Comment by r-hmn** [comment]
> 
> 
> Thanks for opening this issue. Where did you grab that URL from? Since URLs don't support #, we use : instead on our share pages.

As i said, i copied an url from a video thumbnail in the Windows LBRY 0.45.2 desktop app, using right click "copy link" fro a video-thumbnail-title.
So maybe this bug should go to the "Windows LBRY desktop app", instead of closing it.

**Comment by tzarebczan** [comment]
We'll get this fixed for the next release, thanks!
