### ISSUE TITLE
Bid text message when publishing on your own channel may confuse people

### ISSUE THREAD

**Issue by Suisse00** [lbryio/lbry-desktop#4291]
**Bug**
**WARNING:** I'm not a user of lbry. Please double check this is indeed a "bug"/could be hidden and if there is more that should be hidden (like the deposit form? I don't think)

**To Reproduce**
1. Go on the publish windows
2. Fill the form so you can select a channel
3. Select a channel you own
4. In the next block (the one about both the effective URL and the URL bid) you use https://github.com/lbryio/lbry-desktop/blob/master/ui/component/publishName/bid-help-text.jsx to display the deposit but as well as a message about the bid on the URL.
Since I'm publishing on my own channel there should have no need to display the message `If you bid more than %amount% LBC, when someone navigates to %uri%, it will load your published content. However, you can get a longer version of this URL for any bid.`. (See the red rectangle (1) in the screenshot) From my little understanding it should display `Any amount will give you the highest bid, but larger amounts help your content be trusted and discovered.` (so the `amountNeededForTakeover` property should be false which isn't).

I don't know if this releated or not (if not that may be a new ticket to create) but in the `If you bid more than %amount% LBC, when someone navigates to %uri%, it will load your published content. However, you can get a longer version of this URL for any bid.` (See the red rectangle (1) in the screenshot) message the %uri% value (yellow rectangle 2.2) doesn't match what the NameHelpText (the user friendly full URI just above the deposit LBC field; see the yellow rectangle (2.1)) is

the %uri% if from an "anonymous" channel (lbry://\<file name>) but the `NameHelpText` is lbry://@user/\<file name>

**Expected behavior**
 `If you bid more than %amount% LBC, when someone navigates to %uri%, it will load your published content. However, you can get a longer version of this URL for any bid.` should never be display but instead it should be `Any amount will give you the highest bid, but larger amounts help your content be trusted and discovered.`

If you go by the code https://github.com/lbryio/lbry-desktop/blob/master/ui/component/publishName/bid-help-text.jsx variable amountNeededForTakeover should never be true from https://github.com/lbryio/lbry-desktop/blob/master/ui/component/publishName/view.jsx when publishing on a channel.

**Screenshots**
![lbry_publish_url](https://user-images.githubusercontent.com/6698931/83342474-e3a54800-a2bd-11ea-994d-9fc31d572cfc.png)

**System Configuration**

- LBRY Daemon version:
- LBRY App version: 0.45.2
- LBRY Installation ID:
- Operating system:

**Possible labels**
- area: creator
- help wanted
- level: 2 (code not really, assume more about the internal of the system)
- type: improvement

**Comment by tzarebczan** [comment]
Since URLs resolve at both channel paths and ones without a channel, we still show this message regardless. Someone may want to know what the highest bid at a URL is regardless of it they are using a channel or not.
