### ISSUE TITLE
Channel deletion confirmation does not work

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4295]
**Bug/To Reproduce**
When deleting a channel, there will be a confirmation dialog asking the user to type the name of the channel to prevent accidental deletion.  I just typed `dsfdsafdsfsaff` and it still went through  T_T

**Expected behavior**
Cancel the deletion since the strings did not match.

**System Configuration**
```
App: 0.45.2
Daemon (lbrynet): 0.73.1
Platform: Linux (Linux-5.3.0-51-generic-x86_64-with-LinuxMint-19.3-tricia)
```

**Comment by tzarebczan** [comment]
Good catch, it definitely used to work!

**Comment by tzarebczan** [comment]
This should be fixed now, thanks again for pointing it out. Sent a tip the other day on Discord.
