### ISSUE TITLE
Missing requirement to build from source (python)

### ISSUE THREAD

**Issue by Suisse00** [lbryio/lbry-desktop#4296]
**Bug**
I'm trying to build the projet on Windows and got a surprise from node-gyp

`gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.`

I'm not sure of the minimum python requirement yet (probably 2.7?)
  EDIT: node-gyp v2.7, v3.5, v3.6, v3.7, or v3.8 (I just don't know if there is other python dependencies)

**To Reproduce**
1. clone de master repo
2. yarn.cmd (on Windows, because otherwise it try to use yarn.ps1 which has a policy and won't allow it. yarn.cmd will run yarn from node)

**System Configuration**

- git: https://github.com/lbryio/lbry-desktop/commit/39913ec4f9c599bc4cc810e0fb6524d3a67f2053 (master)
- node -v v14.2.0
- node-gyp -v v3.8.0
- Operating system: Windows_NT 10.0.18363

**Additional context**
node-gyp is a dependency of node-sass

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. I don't think you need python at all. Did you install yarn?  You should not be running yarn.cmd or ps, just yarn. Let us know.

**Comment by Suisse00** [comment]
> Did you install yarn?
Yes, yarn is trying to setup node-sass which require node-gyp which require python

> You should not be running yarn.cmd or ps, just yarn. Let us know.
Don't forget I'm on Windows, there is not shebang, the "shebang" is by extension.

ps1 is recognized as an executable extension, so using `yarn` (no .cmd nor .ps1) will use `yarn.ps1`.

When looking at: `yarn.ps1`, `yarn.cmd` and `yarn` all those will do only one thing: start `node yarn.js`

So this isn't a mater about what yarn I'm using.

**Comment by infinite-persistence** [comment]
I just spun up a fresh Windows VM to try, and the 3 steps in the readme is all that you need.  Yarn will handle every thing. 

Try running the following in the **Git Bash** in Windows:
```
$ git clone ...
$ cd lbry-desktop
$ yarn
$ yarn dev
```
Other things that you can try:
1. Environment variables conflict or something?
2. Use node v10 instead of the latest v12.

**Comment by Suisse00** [comment]
By the way, this ticket is just only about adding python as a requirement.
I created https://github.com/lbryio/lbry-desktop/issues/4297 for a python 3 issue with node-gyp. (which is what prevent me to run yarn successfully right now)

So this remove `Environment variables conflict or something?` from the list since it does detect python.

**Comment by infinite-persistence** [comment]
The point we are trying to make is an explicit python install is not needed.  So, I made that sentence as a guess to see if your existing variables are causing an unnecessary conflict.  Having said that, I think the build is/should be sandboxed, so it shouldn't matter (I don't know).

Have you tried running in bash?

**Comment by Suisse00** [comment]
The git bash took a while but it finished, and I still have the issue (thought this new test had python installed so I had to uninstall it first).

Maybe now will be a good idea to provide to log

[lbry-desktop_4296_yarn.log.txt](https://github.com/lbryio/lbry-desktop/files/4718640/lbry-desktop_4296_yarn.log.txt)

I will look a little bit into node-sass to find out when node-gyp is used, but I expected to avoid to do so :/

**Comment by Suisse00** [comment]
Well it went pretty fast

> ## Install
>
>```shell
>npm install node-sass
>```
>
>Some users have reported issues installing on Ubuntu due to `node` being registered to another >package. [Follow the official NodeJS docs]>(https://github.com/nodesource/distributions/blob/master/README.md#debinstall) to install >NodeJS so that `#!/usr/bin/env node` correctly resolves.
>
>**Compiling on Windows machines requires the [node-gyp prerequisites](https://github.com/nodejs/node-gyp#on-windows).**

**Comment by infinite-persistence** [comment]
Are you using Node14?  If yes, use 10.

**Comment by Suisse00** [comment]
Nope, had mess up something and was still on node 14...

And my brain didn't pickup the v10 required (use to read the minimal version, not to use THAT specific version).

Turn out node-sass v4.13.1 support up to node 13.... oupsy
So if somebody end up with a line like "unable to download https://github.com/sass/node-sass/releases/download/v4.13.1/win32-x64-83_binding.node" well this probably mean you are using an unsupported node version for node-sass and it will try build node-sass, which then need the node-pyg and python...

You can throw some rock at me, thank !
PS. node 12 still doesn't work, yarn dev will fail. I will stick to node 10

**Comment by infinite-persistence** [comment]
It's stated in the readme to use v10 only.
