### ISSUE TITLE
Python 3 not supported when building from source

### ISSUE THREAD

**Issue by Suisse00** [lbryio/lbry-desktop#4297]
**Bug**
When running yarn for the first time I got an error from node-gyp:

```
>>> import sys; print "%s.%s.%s" % sys.version_info[:3]
  File "<stdin>", line 1
    import sys; print "%s.%s.%s" % sys.version_info[:3]
                      ^
SyntaxError: invalid syntax
```

when looking at the code you must use [node-gyp  >= 4.0.0](https://github.com/nodejs/node-gyp/commit/0c6bf530a070022235240a8d7be1ff091710689f#diff-7ad6309831a48a234780b58baca65710)

I tried to upgrade it from yarn so I could report to you possible issue but yarn seem to fetch initial dependencies first then upgrade... so I have a nice chicken and egg issue.

**To Reproduce**
1. clone the master branche ( https://github.com/lbryio/lbry-desktop/commit/39913ec4f9c599bc4cc810e0fb6524d3a67f2053 )
2. yarn.cmd (on Windows, because otherwise it try to use yarn.ps1 which has a policy and won't allow it. yarn.cmd will run yarn from node)

**System Configuration**

- Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)] on win32
- node -v v14.2.0
- node-gyp -v v3.8.0
- Operating system: Windows_NT 10.0.18363

**Additional context**
Could be releated to #4296 if somebody is screaming at me about why the hell I do need python

**Comment by tzarebczan** [comment]
See comment in https://github.com/lbryio/lbry-desktop/issues/4296#issuecomment-637551221
