### ISSUE TITLE
After abandoning identity, App must be reloaded to clear it out in Publish

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#430]
## The Issue
After abandoning an identity, it still shows in Publish. Disappears after clearing the app. 

### Steps to reproduce
1. Create identity
2. Abandon identity
3. Check Publish

### Expected behaviour
App should be aware it was abandoned

### Actual behaviour
Still shows identity in the dropdown.

## System Configuration

 

- LBRY Daemon version: 0.14.2
- LBRY App version: 0.14.2
- LBRY Installation ID:
- Operating system: Win 10

**Comment by liamcardenas** [comment]
@tzarebczan is this still happening?

**Comment by tzarebczan** [comment]
Yep, still happening. Don't think the channel list mine call is made again after deleting the channel, so when you go to the publish page, it still shows it. An app refresh fixes it.

**Comment by seanyesmunt** [comment]
This should be possible by just calling `channel_list` after abandoning a claim. It should refresh the list of your channels.

**Comment by alyssaoc** [comment]
closing, reopen if this is still an issue
