### ISSUE TITLE
Comments broken in "master : c6bd2804 : v0.46.0-rc.6"

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4306]
1. I noticed that it was stuck in Advanced Mode for new comment posts (probably due to my previous stashed setting).  The button to toggle between normal and advanced was missing for new posts.
2. Then, when replying a comment (I noticed we've limited it to normal mode), the field is stuck showing "[object]" only when typed.  I think this is because the New Post is still in Advanced, and there's probably a shared state.

Reverting be10041 `disabled advanced editor for comment replies` seems to fix it, though.

**Comment by seanyesmunt** [comment]
Good find. Will fix this

**Comment by seanyesmunt** [comment]
fixed in #4308
