### ISSUE TITLE
Add a "Reposts" tab on channel pages

### ISSUE THREAD

**Issue by LBRYansUnited** [lbryio/lbry-desktop#4327]
I would like to suggest the addition of a 4th tab on channel pages called [Reposts] (probably between [Content] and [About] tabs) I am not a coder, but I am a content creator. As such, I want to make it as easy as possible for folks to view MY content on my channel. I also want to share content from other creators. (Reposts) From creators that I want to support/like/approve of/etc. What I don't want, is for people to see a single list which combines both of those different categories. (The current [Content] tab) The way it is set up now seems to blur the line between:

1. Things that I have actually created and published. 

and 

2. Content that I like, that did NOT create, but have reposted to my channel.

Sure, I am sharing it on my channel page because I think "you" might like it too. But I also do not want someone to have to scroll through 10+ reposts to finally get back to content I DID actually make. Because, by then, I may have lost their interest. I know how quickly people abandon new adventures into the unknown online. Generally people will not go beyond a single clickable link to "try out/explore" something new. (Like a new LBRY channel) I want to do anything that I can to make that 30 seconds to a minute of someone's curiosity journey easier for them, and more beneficial for me, and the platform as well. 

It would be amazing if someone could build a filter that automatically sorts out MY publishes (Content tab) from OTHER creators' content that I am also sharing on my channel (Reposts tab). Thus simplifying the content search process for platform users/potential channel followers. I think it adds a useful additional layer to the personality of any given channel. It helps people differentiate between "Hey this is me, and here is some cool stuff I have done" and "Hey if you like my stuff, then you are gonna love these guys" Which again, I think would help the content creator community to better support one another as well. 

Again, I am NOT a coder. So although my proposed solution seems easy enough, I understand that the behind the scenes side of things is probably much more difficult. I truly appreciate ALL of the hard work that everyone here has put into, and continue to put into this project. Thank you all for reading through all of that and considering my suggestion. I hope that my small contribution here can help the project out somehow. 🍻📚✊

![20200604_131231](https://user-images.githubusercontent.com/66438731/83839263-8b10e900-a6c9-11ea-9ac1-f2e9745d0bed.jpg)

**Comment by unklebonehead** [comment]
I have to agree with this one. It only makes sense. I would repost more myself if it was seperated from my original content. I personally, when visiting someones channel, have made it my personal policy that I will not follow a channel if all I see are reposts without scrolling. If I have to scroll to find someone original content then they do not make enough for me to follow.

**Comment by BrodieRobertson** [comment]
As someone who uploads content daily I find it difficult to justify reposting videos because it'll always be making it harder for someone to see my video which has only just come out, I completely agree that it should be separated, I'd be way more likely to use the feature.

**Comment by kauffj** [comment]
Feedback heard that we should do something here, thanks

**Comment by Invariant-Change** [comment]
This would be an awesome feature and help keep the interface clean 👍

**Comment by tzarebczan** [comment]
This is now live :)

**Comment by LBRYansUnited** [comment]
I know! I saw that and was SUPER excited! Thank you so much. You guys rock!
🤘🍻📚✊
