### ISSUE TITLE
Instances of string overflow

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4331]
**Bug**
Various instances of string overflow.

1. Re-post » Long channel name causes the "new channel name" field to go off screen. (the screenshot below show it's still within the dialog, but I've seen instances where it's off screen due to super long channel-name)
![image](https://user-images.githubusercontent.com/64950861/83910819-ca106e80-a79d-11ea-87d4-4f39d9245a1c.png)

2. Comments that are too long and without any spaces in the sentence causes the "Edit | Delete" button to not be visible.
![image](https://user-images.githubusercontent.com/64950861/83910996-152a8180-a79e-11ea-8b09-d85297d011d1.png)

**Expected behavior**
Need to either reflow or truncate with ellipsis or something.

**System Configuration**
v0.46.0-rc.11

**Comment by tzarebczan** [comment]
Thanks for the issue. These are filed under https://github.com/lbryio/lbry-desktop/issues/3930 https://github.com/lbryio/lbry-desktop/issues/3697
