### ISSUE TITLE
Video transcode setting not reflected correctly (MP3 incorrectly transcoded to MP4)

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4332]
**Bug**
If you previously transcoded an MP4 file and published, and later want to publish an MP3, the MP3 gets incorrectly transcoded to MP4 despite the checkbox showing unchecked.  

I think the setting isn't being reflected correctly, and it's because MP3 are supposed to gray out the checkbox anyway, so it didn't "update" the checkbox when the file was selected, but the publish process still uses that setting.

**To Reproduce**
1. I selected a video file in an odd format, and check "trancode".  I then proceeded to publish that.
2. Hours later (I believe I have closed or restarted the app several times by then), I wanted to publish an MP3.  I selected the music file, and the "transcode" option remains grayed out and unchecked as normal since it's music.  However, when I publish, I noticed it was transcoded and published as MP4.

To fix this, I had to:
1. Go to Publish again
2. Select an MP4 file so that the "trancode" won't get grayed out.  And as I suspected, the checkbox is checked.
3. Uncheck the checkbox.
4. Cancel the publish.
5. Now I'm able to publish music!

**Expected behavior**
The GUI and the setting should match.  

**System Configuration**
```
App 0.45.2
Daemon (lbrynet) 0.73.1
Platform Linux (Linux-5.3.0-51-generic-x86_64-with-LinuxMint-19.3-tricia)
```

**Comment by tzarebczan** [comment]
Nice catch, thanks for the issue!
