### ISSUE TITLE
BUG: Upgrade command missing version number

### ISSUE THREAD

**Issue by leshacat** [lbryio/lbry-desktop#4345]
**Bug**
Upgrade command missing version number

**To Reproduce**
1. Get notified/asked for upgrade
2. Start/download the upgrade file
3. Copy / Paste command shown to you into console
4. Backspace removing "undefined.deb"
5. Press tab to auto fill the version number
6. Click begin upgrade

**Expected behavior**
Add version number (not 'undefined') so when you paste the command it works. The file "LBRY_undefined.deb" does not and never will exist unless the bug affects the downloading of the upgrade file as well (currently it does not).

**Screenshots**
![IMG1](https://i.imgur.com/V25ayiT.png)

**System Configuration**

```
{
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "desktop": "XFCE",
    "distro": {
      "codename": "buster",
      "id": "debian",
      "like": "",
      "version": "10",
      "version_parts": {
        "build_number": "",
        "major": "10",
        "minor": ""
      }
    },
    "lbrynet_version": "0.73.1",
    "os_release": "4.19.0-9-amd64",
    "os_system": "Linux",
    "platform": "Linux-4.19.0-9-amd64-x86_64-with-debian-10.4",
    "processor": "",
    "python_version": "3.7.7",
    "version": "0.73.1"
  }
}
```

- LBRY Daemon version: 0.75.0
- LBRY App version: 0.46.0
- LBRY Installation ID: 27Cu3L1HhLDPRNckGcSj9GZ35DUcaVWM8uQHVhTbZzg1emDTuCbjP2jcECdhfDE59f
- Operating system: Debian 10 + XFCE

**Additional context**
Thank LBRY for saving us from YouTube! You're the best! <3 <3 <3 <3

**Comment by tzarebczan** [comment]
Thanks for filing the issue - we'll look into this. Can we show you [some appreciation](https://lbry.com/faq/appreciation)?

**Comment by tzarebczan** [comment]
I'm not seeing the same here when coming from 0.45.2. Which distribution of the LBRY app do you have installed? Do you recall which version you were on? If you install 0.45.2 (https://github.com/lbryio/lbry-desktop/releases/tag/v0.45.2) and try again, what do you see? 
![image](https://user-images.githubusercontent.com/8120721/84074522-b54ff880-a9a0-11ea-9515-ca41d58467d4.png)

**Comment by tzarebczan** [comment]
Closing for now, let me know if you see it again. May need to test it out on a debian VM.
