### ISSUE TITLE
**Bug** Help button

### ISSUE THREAD

**Issue by unklebonehead** [lbryio/lbry-desktop#4348]
"Ohm" 
Installed from AUR

Help button under the settings "cog" sends you to your "new" following list.

**Comment by tzarebczan** [comment]
Thanks for the report. Does it not show the help page? It seems to be working here - can you try again?

**Comment by unklebonehead** [comment]
Oops. Nevermind. Its my shitty touchpad. I checked on the other computer. Definitly my error.
