### ISSUE TITLE
LBRY version 0.46.1 downloads page missing signature

### ISSUE THREAD

**Issue by afwang** [lbryio/lbry-desktop#4362]
**Bug**
When I check the releases page - https://github.com/lbryio/lbry-desktop/releases/tag/v0.46.1 - the downloadable assets do not include a signature file, whose contents contain a signed list of hashes of the LBRY AppImage file.

This information is helpful for users to verify that the released LBRY packages are the packages the developer intends users to download and use.

**To Reproduce**
1. Go to https://github.com/lbryio/lbry-desktop/releases/tag/v0.46.1
2. Expand the "Assets" list.
3. Scan the Assets list.
4. Note that a signature file is missing.

**Expected behavior**
A signature file is present.

Love the work so far!

**Comment by tzarebczan** [comment]
Thanks for raising the issue. We'll get this added soon.

**Comment by seanyesmunt** [comment]
@afwang Thanks for openeing this issue. I added my signatures to 0.46.0 and 0.46.1
