### ISSUE TITLE
"Use the App" nag seems incorrectly invoked

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4375]
**Bug**
I don't have the app installed in another computer, but this still appears:
![image](https://user-images.githubusercontent.com/64950861/84431415-d7c26a00-ac5d-11ea-95f9-528bb469917d.png)
Although it did say "may", seems odd for it to appear.  Pressing the button simply opens up a blank tab.

**To Reproduce**
1. Open lbry.tv in Incognito Mode on a PC without Desktop installed.
2. Log in.

**Expected behavior**
Don't show this if Desktop is not installed.  The other nag underneath it ("Get the App") is more appropriate and sufficient.

**Comment by tzarebczan** [comment]
This is linked to a signed-in account based on installations you have, we have no other way of telling (at least not right now). Incognito should not show you this unless you've signed into an account there.
