### ISSUE TITLE
Tip Modal improvements

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4380]
![image](https://user-images.githubusercontent.com/64950861/84593400-b42a3a00-ae7e-11ea-9d33-bcfd699bf53a.png)

### 1. There's an extra space before the channel name
This one's a bit subjective and perhaps added to cover a corner-case that didn't have a space already to the left of the URI string.
But I think we should just let clients add the spacing when needed instead of fixed it into the component?

### 2. Differentiate the claim name using a different style
I recall seeing the following used to display the claim/channel names in a sentence, which is good:
- Quotes surrounding the name
- Italicized.

Anything to differentiate the claim name from the sentence would make it easier to read.  Consistently using the style on all places would help as well.
Using a different font is another option.

**Comment by seanyesmunt** [comment]
This modal is being overhauled. You can see the new one at dev.lbry.tv

**Comment by tzarebczan** [comment]
It's live on lbry.tv now, please take a look and let us know if you have any issues with it.
