### ISSUE TITLE
Support for hvec / h265 videos.

### ISSUE THREAD

**Issue by KamenkoTV** [lbryio/lbry-desktop#4381]
**Is your feature request related to a problem? Please describe.**
I would like to upload my videos in a codec thats small and uses little bandiwth, so i choose hvec because its small and uses little bandwith and allows me to have higher quality videos at a smaller size,

**Describe the solution you'd like**
Add hvec video support into lbry

**Describe alternatives you've considered**
Add option to stream videos in a video player like vlc or mpv.

**Additional context**
https://caniuse.com/#feat=hevc
The LBRY app is a graphical browser for the decentralized content marketplace provided by the LBRY protocol. It is essentially the lbry daemon bundled with a UI using Electron
Under the hood, Electron is powered by the Chromium rendering engine and Node. js.
chromium doesnt support h265 / hevc, and that's why i was unable to view all my videos that are h265.

**Comment by tzarebczan** [comment]
Thank you for opening the issue. I don't think we'll be supporting this until major browsers all have support for h265 content because of the lbry.tv use case. LBRY does not transcode any content, so the viewers would need support on their browser.
