### ISSUE TITLE
Tag query URL goes on indefinitely as you change between [Trending|New|Top]

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4393]
**To Reproduce**
1. lbry.tv
2. `Your Tags`
3. Click on one of your tags on the right bar.
4. Click `New`
5. Keep changing between `Trending`, `New` and `Top`.  URL keeps going longer.

![image](https://user-images.githubusercontent.com/64950861/84785113-ac54cc00-b01d-11ea-8e74-16d55a0f96f9.png)

The query still works, just that the URL gets weird.

**Comment by infinite-persistence** [comment]
The following `append` code is causing it:

```
  function buildUrl(delta) {
    const newUrlParams = new URLSearchParams(location.search);
    CS.KEYS.forEach(k => {
      // $FlowFixMe append() can't take null as second arg, but get() can return null
      if (urlParams.get(k) !== null) newUrlParams.append(k, urlParams.get(k));
    });
...
```
It seems like `URLSearchParams` is already returning the current query in the constructor, so the `append` caused the duplicate.  Not sure why `append` is used instead of `set`, so most likely I'll break something if I simply removed the `forEach`, or tweak it to check for duplicates.

(Not sure who to tag, so tagging @seanyesmunt for now for any ideas of the history/intention).

**Comment by seanyesmunt** [comment]
I think this can just be changed to `set`

**Comment by ElectronEsq** [comment]
`set` definitely looks like the fix. Was this pushed. The problem still exists.
![image](https://user-images.githubusercontent.com/29914179/97259199-f10f3000-1865-11eb-9107-2751d8ee0de2.png)

**Comment by infinite-persistence** [comment]
Not yet

**Comment by ElectronEsq** [comment]
Awesome 👍
