### ISSUE TITLE
add exif data to downloaded videos

### ISSUE THREAD

**Issue by nycex** [lbryio/lbry-desktop#4415]
**Is your feature request related to a problem? Please describe.**
When downloading the actual video files via the option in the Network and Data Settings, the filenames aren't always very clear, e.g. they are abbreviations of the title with the ending stripped away or just the youtube video id. That makes viewing those files offline by using a standard video player much harder.

**Describe the solution you'd like**
Add the video title as exif data to the downloaded file, maybe also the name of the channel as the author or something like that and other useful data like the upload data.

**Describe alternatives you've considered**
Make the downloaded videos have the title of the video plus the extension their filename. This would certainly make things easier, too, but the additional exif data would still be a good idea.

**Comment by eatdostacos** [comment]
I'm not sure how this would work as currently content file names are just the file names given by the creator. If you changed it when it was being published, it may cause some sort of error or incompatibility unless the app changed the name of the original file on the publisher's computer. Another option could be a very basic offline mode if the app detects no internet connection. This offline mode could include all the downloaded files in your library and have the most recently downloaded claim info included with it.

**Comment by nycex** [comment]
> I'm not sure how this would work as currently content file names are just the file names given by the creator. If you changed it when it was being published, it may cause some sort of error or incompatibility unless the app changed the name of the original file on the publisher's computer. 

That's a reason why I thought using exif titles would be a better option, the filename could stay as it is.
> Another option could be a very basic offline mode if the app detects no internet connection. This offline mode could include all the downloaded files in your library and have the most recently downloaded claim info included with it.
So you mean it would download the info for the files, but only add it into them when the app is running without internet connection?

**Comment by tzarebczan** [comment]
Thanks for the suggestion, but as explained above, this matches the file name given by the user. In the future we can make it clearer to users when they publish that this will occur.

**Comment by nycex** [comment]
I understand not wanting to change the filename, but that is no argument about the exif data, is it?
