### ISSUE TITLE
Daemon crashes on startup with /tmp mounted on RAM

### ISSUE THREAD

**Issue by LendoK** [lbryio/lbry-desktop#4425]
**Bug**
Lbry not starting.

**To Reproduce**
1. mount your temp folder on ram. tmpfs /tmp tmpfs defaults,noexec,nosuid 0 0 (fstab)
2. start lbry
3. see error

Daemon: /opt/LBRY/resources/static/daemon/lbrynet: error while loading shared libraries: libz.so.1: failed to map segment from shared object

**Expected behavior**
daemon not crashing

**Screenshots**
![Error](https://i.imgur.com/NELe1QH.png)

**System Configuration**

- LBRY Daemon version: 0.76.0
- LBRY App version: 0.46.2
- LBRY Installation ID:
- Operating system: Linux (Linux-5.7.4-zen1-1-zen-x86_64-with-arch)

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. Can you try with sudo, like ```sudo mount /tmp -o remount,exec```

Also, you can try something like this: 

```mkdir /usr/local/tmpdir
export TMP=/usr/local/tmpdir
```

**Comment by LendoK** [comment]
@tzarebczan after `sudo mount /tmp -o remount,exec` I can start the daemon. But this is only a temporary solution. Why is the ticket closed?

**Comment by LaurentOngaro** [comment]
same issue for me. 
Making tmp files executable could not be a good solution, just a workaround
