### ISSUE TITLE
Tip-unlock: Problems entering decimal places

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4428]
**Version Found**
lbry.tv - 2020-06-24

**Bug**
When unlocking a support on a claim, I can't enter decimal places directly in some scenarios.

**To Reproduce**
1. I have a claim with "_185.05 LBC to unlock_"
2. I tried to type **85.05**, but the period doesn't work ❌
3. Typing **185.05** surprisingly worked ✔️
4. Dragging the slider does produce decimal points. To get my desired value of **85.05**, I had to drag the slider to the closest value, then edit the characters.

**Comment by dgarrett01** [comment]
I have a similar issue. If I want to unlock an amount less than 1, I'm unable to start by typing the decimal point. I get a message saying something to the effect of, "the amount must be a number." And if I start by typing 0 first, I get a message saying the amount can't be zero. I also find myself having to drag the slider to the nearest amount and then editing the numbers to get the amount I want.
