### ISSUE TITLE
Unresolved string: "You sent ${amount} LBC"

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4429]
**Version Found**
lbry.tv 2020-06-24

**Bug**
Sent LBC to someone and got this:
![image](https://user-images.githubusercontent.com/64950861/85504196-14a73d00-b61e-11ea-9f09-4b3f5ed8590f.png)

**Comment by tzarebczan** [comment]
There's also one on the "large account history" string on app startup (splash file).

**Comment by infinite-persistence** [comment]
> There's also one on the "large account history" string on app startup (splash file).

This one? https://github.com/lbryio/lbry-desktop/pull/4440

**Comment by infinite-persistence** [comment]
**Close**
- The change in redux has been incorperated.
- The "large account history" issue has been fixed.
