### ISSUE TITLE
"Publish to lbry://xxx" button doesn't pre-populate publish address?

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4431]
![image](https://user-images.githubusercontent.com/64950861/85532978-b771b280-b642-11ea-8e2c-e0834578a104.png)
When I click the the "Publish to" button above, I was expecting that the Publish Page would have pre-populated the "new channel" or address field with the said value, since the text above it says "claim this spot".  Otherwise, it's no different than having to manually copy the claim URI (which we can't at the moment) and going to the publish page as normal.

**Comment by infinite-persistence** [comment]
If the intention is not to pre-populate the field in the first place, perhaps we can just remove/replace the button to become a short link.  This should indirectly solve the space problem in #4434 `[Mobile] Reflow issues for abandoned channels in Blocked Page` as well.

**Comment by seanyesmunt** [comment]
It should definitely pre-populate. Maybe we should cut it off after 20 characters or something to help with the overflow issues.

**Comment by infinite-persistence** [comment]
**This is no longer valid** after #4433 `Option to remove abandoned claims from Blocked Channels page`.  The component in the screenshot above is not supposed to appear in the blocked list, which probably explains why it didn't populate the URL field.  In the normal cases (outside of Blocked Page), that button does populate the URL field.
