### ISSUE TITLE
FR: Support to (download and) play audio only.

### ISSUE THREAD

**Issue by mschilli87** [lbryio/lbry-desktop#4435]
**Is your feature request related to a problem? Please describe.**
Sometimes, the image part of a video is more of a nice-to-have and all relevant information is actually contained in the audio.
Being on small bandwidth and/or low-powered hardware, downloading and rendering the video can actually become a bottleneck causing the playback to pause for downloading or the CPU to run hot due to the heavy load of processing all that (non-essential) video information.

**Describe the solution you'd like**
I'd like to see a feature similar to the mute button that switches to 'audio only' (you could also call it 'podacst') mode, preferentially not even downloading the extra bits.

**Describe alternatives you've considered**
My current workaround is setting the video to download, letting it complete (at least far enough that I'm confident it will finish before playback catches up) and playing the audio using and external media player (*e.g.* `mplayer`).
That solves the CPU issue, but besides requiring me to put in the extra effort, still requires me to download a lot of data that I know in advance I won't be needing.

**Additional context**
This is clearly just a nice-to-have suggestion and as I don't have the time to provide a patch, I don't expect this request to have any consequences. I just thought at least I can put it out and maybe it turns out more simple than I imagine.

With that all I have left to say is thank you for what you are doing and keep up the good work.

**Comment by tzarebczan** [comment]
Thanks for opening the issue. We do hope to support lower quality video formats in the future, but most likely won't support audio only. I will link this issue here https://github.com/lbryio/lbry-sdk/issues/2879 to see if we can consider it.
