### ISSUE TITLE
Notifications and Blocked "Manage" button doesn't work with 0 blocked channels

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4447]
`Notifications` and `Blocked` _Manage_ button doesn't work with 0 blocked channels.
- The former should work regardless of blocked channel count?
- The latter is technically correct, but no harm to just enter the page since it will show a _When you block a channel, all content from that channel will be hidden._ message which seems useful for beginners?

![image](https://user-images.githubusercontent.com/64950861/86107454-6eaf7300-baf4-11ea-9e5a-1e7e56995474.png)

**Comment by seanyesmunt** [comment]
I agree it probably is worth it to show the blank page so users see that help message. I'll keep this open.
