### ISSUE TITLE
Better presentation for disabled button

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4448]
The disabled button (at least for the "secondary" type) looks the same as the active button. The only indication of disabled is whether a mouse-hover will highlight it, which is irrelevant for mobile.  Perhaps it should be grayed out instead.

![image](https://user-images.githubusercontent.com/64950861/86109661-33fb0a00-baf7-11ea-9bba-b22286f88de3.png)

**Comment by seanyesmunt** [comment]
I will fix this. Just need to add a variable. Thanks for reporting.
