### ISSUE TITLE
Video never starts playing

### ISSUE THREAD

**Issue by arthurferrai** [lbryio/lbry-desktop#4462]
**Bug**
I'm trying to play [this video](https://lbry.tv/@gamefromscratch:1/wicked-engine-gets-more-wicked:f) but it never starts on my machine

**To Reproduce**
1. Go to https://lbry.tv/@gamefromscratch:1/wicked-engine-gets-more-wicked:f
2. Click on Play button
3. Video is stuck on thumbnail.

**System Configuration**
MacBook Pro (Retina, 13-inch, Late 2013) with macOS 10.15.5 using Safari 13.1.1

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. Getting stuck on the thumbnail seems strange. Does this happen on this video only or on all? Can you try again with another browser to see if that helps?

**Comment by arthurferrai** [comment]
Tried right now on same browser, this time using private browsing (cmd + shift + N) and it plays as expected.
I'll download opera and test it again.

**Comment by arthurferrai** [comment]
On Opera, in logged window I need to wait some minutes for video to play (it keeps on "Loading decentralized data..." for a long time). Playing from private browsing works as expected.

**Comment by tzarebczan** [comment]
Glad to hear that!

**Comment by arthurferrai** [comment]
It's not exactly solved (since safari still doesn't play the video as expected).

**Comment by tzarebczan** [comment]
You wrote "Tried right now on same browser, this time using private browsing (cmd + shift + N) and it plays as expected"  

Maybe you have some extension or blocker in Safari on your main tab? Sounds like a local issue.

**Comment by arthurferrai** [comment]
Yeah, looks like a local issue. Now the same video is working (even without private browsing).
Sorry for bothering 😅
