### ISSUE TITLE
lost settings on bad network connection

### ISSUE THREAD

**Issue by Tcll** [lbryio/lbry-desktop#4467]
whenever loading the app, sometimes you'll get an error message just after the loading screen
after that, all your prior settings are lost and everything is reset
this can also happen when a page takes a while to load, and also happens on the site

I've even had it happen where after setting my reset settings, I click "Home" and my settings are reset again
really annoying and happens almost every day
especially when on a VPN, which is made even more annoying by the fact the app uses malicious Amazon services just to launch.
(I block AWS in iptables)

**Comment by tzarebczan** [comment]
Sorry about the trouble. What error message do you see? That should not reset the settings, but we are aware of some rare cases it does. The solution is filed under this issue: https://github.com/lbryio/lbry-desktop/issues/3328 and we'll be working on it soon.

**Comment by Tcll** [comment]
alright thank you, and sorry if I'm posting this on thin patience

I probably wouldn't've even created this issue if everything weren't working against me (not a typical bad day)

hope things get sorted out soon :)
