### ISSUE TITLE
Translation - selectAsset dynamicaly generate the string key / ratio title partialy translated

### ISSUE THREAD

**Issue by Suisse00** [lbryio/lbry-desktop#4472]
**Bug**
This is likely to be a two part issue (first part is to clarify then take action).

I was poking the code to fix a non translation string in the edit channel page.

[Thumbnail <recommendation ratio>](https://github.com/lbryio/lbry-desktop/blob/8b266ebacb0fc4d3c9673a5ef4da22d0d61d681d/ui/component/channelEdit/view.jsx#L119), [Cover <recommendation ratio>](https://github.com/lbryio/lbry-desktop/blob/8b266ebacb0fc4d3c9673a5ef4da22d0d61d681d/ui/component/channelEdit/view.jsx#L126) which all use the [selectAsset](https://github.com/lbryio/lbry-desktop/blob/master/ui/component/selectAsset/view.jsx) aren't fully translate.

When looking at the code I found that all those translation key are in fact dynamicaly generated. (For the URL title we append `assetName` and the `recommended` property for the ratio. We do also append `assetName` with the literal "source" for the sources dropdown titles)

1) Is this a good practice on your end? As a translator that look for context into the code it add some complexity to it. (Not much but as a developper I also know itsn't a huge change and dynamic keys may be bad for futur maintainer).

2) If we want to keep the code as it we will need a little fix. https://github.com/lbryio/lbry-desktop/blob/8b266ebacb0fc4d3c9673a5ef4da22d0d61d681d/ui/component/selectAsset/view.jsx#L115 is expecting `recommended` property to be a translation key. However callers ( https://github.com/lbryio/lbry-desktop/blob/8b266ebacb0fc4d3c9673a5ef4da22d0d61d681d/ui/component/channelEdit/view.jsx#L123 &  https://github.com/lbryio/lbry-desktop/blob/8b266ebacb0fc4d3c9673a5ef4da22d0d61d681d/ui/component/channelEdit/view.jsx#L130 ) send the translated value.

**To Reproduce**
(For the explanation on number 2)
1. Set LBRY for any language except english
2. Go on the edit  page of a channel - The first two lines, the URL textbox control title will display "Thumbnail" <something that should be translated> and "Cover" <something that should be translated>.

**Expected behavior**
Title for controls of selectAsset to be translated.
(NOTE: If you test with the latest stable version the sources dropdown lists aren't translated. I found a change (11 days ago) that should fix it)

**System Configuration**

- LBRY Daemon version: 0.76.0
- LBRY App version: 0.46.2
- Language: french

**Comment by Suisse00** [comment]
Suggested labels: good first issue, level 1, type: discussion, type: task

**Comment by infinite-persistence** [comment]
`Close`
The string concatenation problem has been fixed.
