### ISSUE TITLE
Double "@" in New Channel desktop notification

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4485]
Create a channel and wait for the confirmation.  I've seen various behavior:
- no notification
- got the notification but with double "@"
   ![image](https://user-images.githubusercontent.com/64950861/86633979-eb19e880-c003-11ea-831a-99652952062a.png)
- notification appears correctly

Not sure how to reproduce, but this was the second time.

```
yarn dev @ d8cec3f6 (but seen it in earlier commits too)
```

**Comment by seanyesmunt** [comment]
Probably not worth fixing for now. I plan to get rid of this notification in favor of in-app notifications once that is complete.
