### ISSUE TITLE
Highlight the "More" filter button for Refugee filter?

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4486]
Normally, the "More" filter button would be highlighted when the filter is auto-expanded.  The Refugee list does auto expand, and it includes a "clear" button, but it doesn't highlight the button.  There's no indication that it has been filtered after collapsing the area.
![image](https://user-images.githubusercontent.com/64950861/86635670-f66e1380-c005-11ea-8e72-4ded666afed3.png)

**Comment by kauffj** [comment]
Ideally everything that we can do via URL is doable via the UI directly. The "advanced filter" thing is a hack from our ability to filter out-racing our ability to build a UI.

tl;dr - build a multi-channel selector :sunglasses:
