### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by ole-tange** [lbryio/lbry-desktop#4501]
I am visually handicapped. This mean that I always increase the font size to 200% - sometimes even more.

I have found no way to do that in LBRY.

Ideally I would like it to work as smoothly as in Firefox: CTRL + and CTRL - to zoom. CTRL scrollwheel also zooms.

But it would also be acceptable, if I could change the font size in settings.

As it is now, I cannot use the Desktop app - simply because the font size is too tiny for me to read. And I find that a silly limitation.

**Comment by tzarebczan** [comment]
Thanks for opening the issue!
