### ISSUE TITLE
Can't play videos from some channels, only download

### ISSUE THREAD

**Issue by kabo** [lbryio/lbry-desktop#4503]
**Bug**
Some channels have videos I can't play, but I can download them and play them in VLC just fine.

**To Reproduce**
1. Go to lbry://@SciShow#6 or lbry://@The-King-of-Random#a or lbry://@PBS-Space-Time#e (I'd say SciShow, PBS Spacetime, and The king of random are pretty big content creators and probably know what they're doing)
2. Click on any video
3. Can't play the video, only download it

**Expected behavior**
That I can play the video

**Screenshots**
![Screenshot from 2020-07-09 20-26-17](https://user-images.githubusercontent.com/357601/87016329-1a745500-c1be-11ea-82a6-e181177aa815.png)
![Screenshot from 2020-07-09 20-27-18](https://user-images.githubusercontent.com/357601/87016344-1e07dc00-c1be-11ea-8769-85ed908a74a8.png)

**System Configuration**
![Screenshot from 2020-07-09 20-29-33](https://user-images.githubusercontent.com/357601/87016517-57d8e280-c1be-11ea-899c-971ba7d43297.png)

**Comment by tzarebczan** [comment]
Looks like this user is publishing files without a file extension which is why the app / SDK can't detect the correct file type to stream it. 

I'll try to reach out to him and see why this is not failing on the SDK side. Thank you for brining this up! Will send a tip over on Discord.
