### ISSUE TITLE
Make it clearer how I likely I am to be able to view a video without buffering

### ISSUE THREAD

**Issue by kabo** [lbryio/lbry-desktop#4504]
**Is your feature request related to a problem? Please describe.**
Sometimes when I watch a video it buffers for 10 seconds, plays for 5 seconds, buffers for 10, plays for 5, over and over. And if I try to download the video it takes longer to download than the play time of the video.
If I click some other video it plays without a hitch.

**Describe the solution you'd like**
I'd like to have some sort of indicator of how good of a connection I have to the servers serving the video. Something to manage my expectations.

**Describe alternatives you've considered**
More servers serving content?

**Comment by tzarebczan** [comment]
Thanks for opening this issue! We're aware this is a common issue on lower bandwidth connections / areas where we don't have good coverage yet. Hope to make some enhancements in the future.

**Comment by jessopb** [comment]
This has improved a lot lately.

**Comment by slrslr** [comment]
I am seeing this too in LBRY_0.53.6.AppImage
like 3-5 second playback and same time buffering -> LBRY not useable for me. Unless i use this hack:
Click volume icon, do something else 15+ minutes and play video again.
I did 4 tests with different servers at https://librespeed.org getting download:
16mbit/s
2mbit/s - i suspect slow server
15mbit/s
20mbit/s
I consider this a big usage problem.

LBRY should do more clever buffering for better user experience. Or allow user to click download whole video and then play (maybe even auto play) once done or once it estimate that it downloaded enough data so playback wont be interrupted.
