### ISSUE TITLE
Highlight url instead of text when embedding a link

### ISSUE THREAD

**Issue by clay53** [lbryio/lbry-desktop#4505]
**Is your feature request related to a problem? Please describe.**
It really annoys me every time I press ctrl+k with the display text selected and I accidentally paste over it and then have to undo that, select the "https://" thing, and then paste the url. Please make it so that it just goes straight to highlighting the "https://".

**Describe the solution you'd like**
When writing text, make it so that if display text is already selected and the link embed shortcut is pressed, auto select the url instead of the display text.

**Describe alternatives you've considered**
Being slower when embedding links.

**Additional context**
In case it's not clear, I'm talking about the "advanced" text editor when writing descriptions for videos/channels.
![image](https://user-images.githubusercontent.com/16981283/87044159-295e0600-c1c4-11ea-98cf-e66ce193b982.png)

**Comment by infinite-persistence** [comment]
Waiting for [Better cursor handling when creating links and pasting URLs](https://github.com/Ionaru/easy-markdown-editor/issues/85).
