### ISSUE TITLE
Add ability to support on publish page

### ISSUE THREAD

**Issue by clay53** [lbryio/lbry-desktop#4506]
**Is your feature request related to a problem? Please describe.**
Add ability to support the publish on the publish page so you don't have to wait until after the claim is confirmed to add support.

**Describe the solution you'd like**
Add a field below the deposit to stake revocable support.

**Describe alternatives you've considered**
Making it so that users are able to view their publish before it's done confirming.

**Comment by tzarebczan** [comment]
This won't be possible since the claim needs to be crested before it can be supported. You can add a bigger initial deposit or wait until it's confirmed.

**Comment by clay53** [comment]
Would it be impossible to add it to a kind of queue in the app and just say to wait for it to go through before closing?
