### ISSUE TITLE
splash screen internationalization bug

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#4525]
![photo_2020-07-13_18-10-11](https://user-images.githubusercontent.com/8120721/87358655-4122ea80-c534-11ea-9e30-447619a192c4.jpg)

**Comment by infinite-persistence** [comment]
Should be a duplicate of https://github.com/lbryio/lbry-desktop/pull/4440 `Fix unresolved translations in the Splash Screen.`, unless it's happening again.

**Comment by tzarebczan** [comment]
Maybe it was on an earlier version that I saw this. Closing for now!
