### ISSUE TITLE
Channel-creation in "Tip|Support" Modal shouldn't submit LBC immediately

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4544]
1. Click `Support` on somebody's Channel Page.
2. Select a `New channel` and hit "create channel".
   - If the current selection is a `Support`, **the LBC is submitted directly.  I haven't properly selected my amount yet, since one would do things from top to bottom**.
(On another instance, the modal goes away but I don't see the support in my transaction.  I think it's because the channel creation was pending for a while.  I ended up with a new channel but no support.  This is confusing)
   - If the current selection is a `Tip`, it goes straight to the confirmation dialog.  Phew ... but it shouldn't do that in the first place.

I think we should stay in the dialog when `Create channel` is clicked, and resolve the channel first instead of overloading this button to submit the LBC.

**Comment by tzarebczan** [comment]
I ran into this today - should definitely not do that when you click "create new channel" haha
