### ISSUE TITLE
Double underscore string formatting function in UI components

### ISSUE THREAD

**Issue by ycohen-dev** [lbryio/lbry-desktop#4548]
I find all over the codebase , any time we're dealing with a string that will be presentable in the UI,  
a call to a string formatting function (I persume) - that looks like this:  
`property=__('text')`  
  
I have tried to look it up in ES6 documentation and React documentation to no avail.  
  
I'm 99% sure I'm missing somethin fundemental , and if I am - please direct me toward the right documentations.  

If I'm not - and it is an internal function - does it have something with locating texts from a resource file? maybe something like:  
`__('LookupThisKeyInsideTranslatableStringFile')`

**Comment by kauffj** [comment]
https://github.com/lbryio/lbry-desktop/blob/master/ui/i18n.js#L56

**Comment by ycohen-dev** [comment]
Thank you!
