### ISSUE TITLE
Bad postinstal: lbry (0.47.0-12433) over (0.46.2-11876)

### ISSUE THREAD

**Issue by minzak** [lbryio/lbry-desktop#4551]
It is not so hard bug, but need to fix.

```
me@e7470 /tmp/rIwDEX $ sudo dpkg -i LBRY_0.47.0.deb 
(Reading database ... 284327 files and directories currently installed.)
Preparing to unpack LBRY_0.47.0.deb ...
Unpacking lbry (0.47.0-12433) over (0.46.2-11876) ...
Setting up lbry (0.47.0-12433) ...
chmod: cannot access '/opt/LBRY/chrome-sandbox': No such file or directory
/var/lib/dpkg/info/lbry.postinst: line 10: update-desktop-database: command not found
Processing triggers for mime-support (3.62) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...

me@e7470 /tmp/rIwDEX $ sudo mcedit /var/lib/dpkg/info/lbry.postinst
```
I also have not update-desktop-database command.
Need to do: `apt-get install desktop-file-utils`

P.S. I not use and don't want to use CHROME! Only OpenSource like Mozilla Firefox.

**Comment by tzarebczan** [comment]
Thanks for filing the issue...I don't think this causes any issues in app - notice any? 

The electron framework is chrome based, so that's where that portion comes from. We'll need to see if this is a known issue with the desktop file utils.

**Comment by bizlevel** [comment]
No, all works fine.
Just need create subdir and some install.
After upgrade - just delete subdir.
