### ISSUE TITLE
Many missing options or just completely irrelevant options in 'Email Preferences'

### ISSUE THREAD

**Issue by kcseb** [lbryio/lbry-desktop#4552]
**Bug**
Navigating to `Settings -> Notifications -> Manage -> Email Preferences` produces a massive list of checkboxes with missing options or options that I don't think end-users should have access to. 

**To Reproduce**
1. Go to`Settings -> Notifications -> Manage -> Email Preferences
3. Scroll down...

**Expected behavior**
Would expect just casual options for email notification preferences. 

**System Configuration**
- LBRY Daemon version: 0.77.0
- LBRY App version: 0.47.0
- LBRY Installation ID: 2TxtRu7JxCpVxNF572y4tir3kiiH3ni5djXhQo9CTzY2V7vAPB94cEd3cBeSaaKDJu
- Operating system: Windows 10 Pro 1909

**Additional context**
Seems this is an issue that isn't affecting a lot of people, can confirm that the few people I asked about this are unable to replicate it.

**Comment by kcseb** [comment]
I have an idea of what might be causing this, but I am not too sure. Might be something to do with commander.

**Comment by tzarebczan** [comment]
Yes, it's users with mod permissions since they see all tags for other functions, not just public ones. We have this filed internally under our APIs and will fix.
