### ISSUE TITLE
Implement new buffering metrics collection

### ISSUE THREAD

**Issue by andybeletsky** [lbryio/lbry-desktop#4559]
UI should send data when video playback or buffering occurs:

- anonymized user id hash
- content url (lbry://...)
- buffering position
- buffering duration
- content duration
- bitrate

Check [OpenAPI spec](https://github.com/lbryio/lbrytv/blob/feature/collector/apps/collector/openapi.yml) for detailed fields description.

**Comment by tzarebczan** [comment]
We don't have the bitrate stored anywhere - we should get this added as metadata on the SDK (probably along with some other metadata we didn't think of initially) but we can also calculate this from the file size/length which is in the metadata.
