### ISSUE TITLE
"Up Next" doesn't work until you scroll down to load "Related" at least once

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4561]
"Up Next" doesn't work until you scroll down to load the "Related" section at least once.  Feels like an odd behavior.

**Comment by tzarebczan** [comment]
That's a good find - we delayed loading of related until a user sees that part for performance improvements. We can probably just trigger the load when the video ends / upnext logic is run.

**Comment by infinite-persistence** [comment]
`Close`
No longer relevant today after `Related` was moved to the right and the delay was removed (even in mobile).
