### ISSUE TITLE
Comments by '@çokkomik' persist after channel is deleted

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4571]
I made comments a long time ago using two separate channels:
(1) `@çokkomik`
(2) `@blah`

I deleted both channels today and expected both comments to be gone.  The second one is gone, but the first one persists despite the channel being fully deleted.  I wonder if the `ç` is causing problems.

**Comment by tzarebczan** [comment]
The comments are stored in a comment database and it has no idea the channels were deleted. We'd need to clean them up there. 

Eventually this will be on the protocol so it should be more natively supported.

**Comment by tzarebczan** [comment]
Actually, we resolve the channels to get the thumbnails / other data, so we can handle it then. Maybe take a look at this as part of the lazy loading you said you'd look at.

**Comment by infinite-persistence** [comment]
`Close`
- No longer reproducible.
