### ISSUE TITLE
Unknown channel!?

### ISSUE THREAD

**Issue by bizlevel** [lbryio/lbry-desktop#4572]
Very interesting, I have 3 channels.
![channels](https://user-images.githubusercontent.com/12154217/88273675-38c07180-cce3-11ea-8b36-7b5170734a58.png)

But when I invite new members I see 4 channels! Why?
![invite](https://user-images.githubusercontent.com/12154217/88273684-3cec8f00-cce3-11ea-82b7-7ba301eb1c3c.png)

**Comment by seanyesmunt** [comment]
That "4th channel" is just an invite code. Used to share a link that you don't want to be tied to one of your channels.

**Comment by bizlevel** [comment]
Thanks.

**Comment by seanyesmunt** [comment]
No problem. Thanks for bringing up your confusion! We will try to make this easier to understand in the future 🙂
