### ISSUE TITLE
Unnecessary picture in picture when going to lbry.tv link with # behind claim id instead of :

### ISSUE THREAD

**Issue by clay53** [lbryio/lbry-desktop#4582]
**Bug**
When you go to a url with a # before the claim id, when it is switched to a :, it adds an unnecessary picture-in-picture.

**To Reproduce**
1. Go to https://lbry.tv/@3Blue1Brown#ba79c80788a9e1751e49ad401f5692d86f73a2db/the-impossible-chessboard-puzzle:7
2. See error

**Expected behavior**
Shortens link and plays normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/16981283/88421414-8ce85600-cdb6-11ea-8b06-8b3025384e66.png)

**System Configuration**

- Operating system: pop!os

**Comment by tzarebczan** [comment]
Thanks for the issue. Where did you copy that url from? It should not have a # in it. Maybe there's a bug in the apps right click > copy url feature.

**Comment by clay53** [comment]
@tzarebczan I didn't copy the url from anywhere, I was writing a thing to translate lbry:// urls to lbry.tv urls (and I guess I didn't do it quite right).

**Comment by DispatchCommit** [comment]
I can't reproduce this anymore.
