### ISSUE TITLE
URL/Search bar says "view channel" when a stream/repost canonical URL is entered

### ISSUE THREAD

**Issue by eggplantbren** [lbryio/lbry-desktop#4607]
If you type or paste a canonical URL into the search/navigation bar of the LBRY app or lbry.tv, it says that you would "view channel" if you were to navigate there, even though the URL is pointing to a stream. Example:

![image](https://user-images.githubusercontent.com/1578298/88907529-d8b26800-d2ac-11ea-9642-12a5383f40ad.png)

I assume it's doing this because the URL starts with the channel part, but once you add the extra slash or maybe one more character beyond that it should recognise that you're not going to the channel page anymore and should say "view file".

**Comment by ioancole** [comment]
Hi, I'll take this as a first issue if it hasn't already been stolen? It seems like it's actually a bug in the parseURL function in the lbry-redux project. I will dig deeper and fix

**Comment by tzarebczan** [comment]
Thanks @ioancole , she's all yours!

**Comment by ioancole** [comment]
Please see PR #4719

**Comment by tzarebczan** [comment]
This is fixed now!
