### ISSUE TITLE
If claim search on latter page fails, don't clear out all previous data

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#4609]
See https://lbry.tv/$/discover?t=imherelbry&t=imherelbry&t=imherelbry&t=imherelbry&t=imherelbry&t=imherelbry&content=video

**Comment by tzarebczan** [comment]
(also not sure why the tag duplicated in URL)

**Comment by infinite-persistence** [comment]
> _(also not sure why the tag duplicated in URL)_

Covered in [4393](https://github.com/lbryio/lbry-desktop/issues/4393)

**Comment by tzarebczan** [comment]
@infinite-persistence this still happens, can you take a peek?

**Comment by infinite-persistence** [comment]
> (also not sure why the tag duplicated in URL)

For the tag duplication part, 4393 seems to still be working.  Changing [Trending|New|Top] now no longer appends more tags, and also clears out any existing ones. 

>  If claim search on latter page fails, don't clear out all previous data

For this part, I'm not sure what it meant.  Is it saying that when changing [Trending|New|Top] and if the query fails, show the `Sorry, your request timed out. Modify your options ...` message but don't clear out any existing found tiles?  But the query has changed, so clearing the tiles should be correct?

**Comment by tzarebczan** [comment]
What happens is that the first page may load, but a subsequent may fail - so instead of clearing out all results, we should show another message that says "can't retrieve more information, try again later". Right now it clears the first page and shows the error too. 

Though this is something that will hopefully be fixed with our SDK revamp, so not a huge deal right now unless it's easy to do so.

**Comment by infinite-persistence** [comment]
`Change`

Reverted back to the simple version of just using an existing flag + not purging if results already exists. The only downside to this is that the "timeout" message will no longer appear, and it might look unresponsive when switching between various filters that all result in timeout.
