### ISSUE TITLE
Can't create Comments if you recently deleted a channel

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4621]
I recently deleted a bunch of test channels.  Later, I wanted to make a comment on a post, but the comment doesn't get through.  The loading icon goes on forever, and the error message is as reported by [#3013 Impossible to add comments](https://github.com/lbryio/lbry-sdk/issues/3013).  I checked the values and it is showing the "comment as xxx" being one of the channels that I just deleted, despite the drop-down clearly highlighting a valid channel.  This can be clearly seen in the GUI if you make a comment in the Channel (instead of post), or anywhere where it says "comment as xxx" (I think a Reply will show this string).

**Workaround:** I can't recall the full steps, but it's something like toggling the dropdown to a different channel a few times, or create a new channel.

Seems like there is a database mismatch after a channel-deletion process.

**Comment by tzarebczan** [comment]
This could also happen in other ways where the user must re-select the channel. Probably also some strange redux/state issue. I thought I had it filed but I could not find.
