### ISSUE TITLE
allow embed on audios

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#4622]
Right now we only allow it for videos

**Comment by DispatchCommit** [comment]
Do audio file embeds _not_ work? They seem to work fine in my testing

https://lbry.tv/@bitwave:a/BitwaveBanner:0?lc=6d7e0ddf137849e76467ccfade07835f36f3d97d852b2688119049f7a717ba6e

**Comment by tzarebczan** [comment]
I think we used to hide the embed share dialog for none video, looks like it's fixed there now!
