### ISSUE TITLE
[help wanted] German translation

### ISSUE THREAD

**Issue by TecCheck** [lbryio/lbry-desktop#4638]
Hi,
I just started using lbry.tv and it's really nice. I noticed that there are some areas where there is no translation. I haven't looked into the source code, so I'll just list the strings I found on the website and their translation. I need to say that I'm not a professional translator in any way. I am from Germany and I think I understand English enough to translate it into German. 
Hope this is going to help :wink: 

| English | German | Location|
| ------- | ------ | ------- |
| Purchased | Gekauft| right side bar|
| Resources | Ressourcen | footer|
| Policies| Richtlinien| footer|
| Terms of Service| Nutzungsbedingungen| footer|
| Privacy Policy| Datenschutz| footer|
| Advanced Settings | Erweiterte Einstellungen | Settings|
| Channels| Kanäle (currently spelled wrong) | Account dropdown|
| Publishes | Veröffentlichungen | channels overview |
| Nothing uploaded to LBRY yet. | Noch nichts hochgeladen. | empty uploads page|
| Upload something new| Etwas neues hochladen| empty uploads page|
| You haven't uploaded anything with this channel yet!| Du hast mit diesem Kanal noch nichts hochgeladen | Creator Analytics page|
| Customize link| Link anpassen| Invite page |
| Invite someone you know by email and earn LBC when they join lbry.tv. | Lade jemanden den du kennst per E-Mail ein und verdiene LBC, wenn dieser lbry.tv beitritt. | Invite page |
| Invite| Einladen | Invite page (Invite Button) |
| Check the status of various LBRY services.| Sieh dir den Status verschiedener LBRY Services an.| Help page |
| Check Status| Status ansehen | Help page (Check Status Button) |
| Live help is available most hours in the #help channel of our Discord chat room. Or you can always email us at help@lbry.com. | Live-Hilfe ist fast rund um die Uhr im Kanal #help unseres Discord Chat-Rooms erhältlich. Alternativ können Sie uns jederzeit eine E-Mail an help@lbry.com schreiben. | Help Page
| Changelog | Änderungsverlauf | Help page (About App) |

If you have any more suggestions on translations or you think that the translation is not correct let me know. I'm open to them.

**Comment by tzarebczan** [comment]
Thanks for opening the issue. We have a translation channel on chat.lbry.com where you can come learn more how to contribute. You can also start signing up here: https://www.transifex.com/lbry/lbry-desktop
