### ISSUE TITLE
Collect tips button

### ISSUE THREAD

**Issue by clay53** [lbryio/lbry-desktop#4643]
**Is your feature request related to a problem? Please describe.**
The wallet interface can be kinda slow which can make it annoying to go through each individual tip to claim them.

**Describe the solution you'd like**
A button that allows you to collect tips based on how long ago they were sent.

**Describe alternatives you've considered**
Doing it manually.

**Comment by tzarebczan** [comment]
Thanks for filing! We do have this capability in the SDK for both supports/tips or supports+tips together. 

Similar to the unlock button, we should warn the user that this will decrease discovery. Also give an option to resupport their latest content or channel maybe (this may require a blockchain confirmation for large transactions though.

**Comment by kauffj** [comment]
If shipping this it must catch time out errors for large wallets and provide a smooth transition to support

**Comment by clay53** [comment]
Was this issue added to lbry? I saw that it's added on Odysee but I don't have tips to check.
