### ISSUE TITLE
Markdown Preview breaks when <iframe> is present

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4644]
When creating a markdown post, type something simple like:
```
Hello baby
```
When you click the "markdown preview" eye icon, everything works as usual.

Now, add an embed, plus another simple text:
```
Hello Baby:
<iframe src="lbry://@lbry#3f/befreeonlbry#5"></iframe>
Hello baby
```
The preview is not correct after the embed.

**Comment by tzarebczan** [comment]
Thanks for filing, I had mentioned this one in https://github.com/lbryio/lbry-desktop/issues/4639#issue-674368990 

We should at least try to at least show all the other data and not break.
