### ISSUE TITLE
Synced data cleared out if preferences fail to load - prevent sync of new data until prefs work

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#4645]
We've gotten a few reports that users following/tags list is cleared out. This usually happens when they see the error notification about preferences not being loaded. What must be happening here is that the local state doesn't have any data, and then a sync triggers and it overwrites their previous synced data

- [ ] figure out why preferences fail to load sometimes (could be connection issues, api hiccup, etc). 
- [ ] If they fail, retry? 
- [ ] If they fail, don't allow new sync data to overwrite. Contact LBRY?

**Comment by kauffj** [comment]
we're assuming this is fixed, re-open if it happens again
