### ISSUE TITLE
ffmpeg detection

### ISSUE THREAD

**Issue by kodxana** [lbryio/lbry-desktop#4646]
**Describe the solution you'd like**
Add detection system for ffmpeg for
Linux - If user install ffmpeg from APT or AUR
Windows - If user have installed ffmpeg manually and set System Env Path ( read from PATH)

**Comment by tzarebczan** [comment]
This is done on the SDK, not the app. We'd need to understand exactly what is happening on flatpak/AUR/appimage. It should be reading from the system path already, same for Windows (did you confirm this doesn't work? I know it used to - but it won't work from protected windows folders). 

Once you have more info, please open on SDK side.
