### ISSUE TITLE
':' is not in the list of reserved symbols despite reporting an error.

### ISSUE THREAD

**Issue by clay53** [lbryio/lbry-desktop#4653]
**Bug**
`:` is not in the list of reserved symbols in the reserved symbols error when setting a channel name

**To Reproduce**
1. Go to create channel
2. Click on name
3. Type `:`

**Expected behavior**
A `:` is in the list of reserved symbols in the error.

**Screenshots**
![image](https://user-images.githubusercontent.com/16981283/89916254-6eab9400-dbc5-11ea-9ce9-6d51268f77cd.png)

**System Configuration**

- LBRY App version: lbry.tv Aug 11 2020

**Additional context**
`:` is a reserved symbol used in lbry.tv links.

**Comment by tzarebczan** [comment]
Thanks for the issue! I've updated it here: https://github.com/lbryio/lbry-desktop/commit/7b504b5fa7d523e349789a532e1f262a4263e2d3 

Also added ?  which was missing. 

Will send a tip over to your channel!

**Comment by clay53** [comment]
@tzarebczan  Wow, that was fast. Thanks. (channel [here](https://lbry.tv/@ClaytonDoesThings:8) if you need it)
