### ISSUE TITLE
Add ability to initiate YouTube sync from lbry.tv (and potentially during first run)

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#4661]

**Comment by bitcoinbrisbane** [comment]
Was just about to add this as an issue but found this instead.  Do you want to pull down from YouTube or publish to YouTube when you publish on lbry?

I'd like to see publish to YouTube from lbry so the platform becomes the tool to distribute content.  Maybe even a delayed sync so lbry gets first views?

**Comment by tzarebczan** [comment]
This is actually already a feature during first run and we have an option to add it from the upload page on odysee.com.
