### ISSUE TITLE
Download doesn't trigger on web until 2nd attempt

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#4669]
I notice many times when I click download, it won't start until I click it a 2nd time.

**Comment by mohamed0group** [comment]
hi

I think i fixed now

**Comment by mohamed0group** [comment]
hey bro, I want to submit a new pull request for this issue and....
![Screenshot 2020-08-26 at 6 40 55 AM](https://user-images.githubusercontent.com/34784505/91256336-62980880-e767-11ea-8e4a-d8330321ce1a.png)
I don't know, can you tell me what to do next?

**Comment by tzarebczan** [comment]
You can learn more here: 

https://opensource.com/article/19/7/create-pull-request-github

**Comment by mohamed0group** [comment]
I think it's done now.

Wallet Address 	    bXTpJWJTPxzF6tAk23LzDBz5WKy9QDvyuP

**Comment by mohamed0group** [comment]
nice

**Comment by tzarebczan** [comment]
We don't see a PR from you, sorry. Please double-check the documentation.
