### ISSUE TITLE
ensure wallet sync setting adheres to local data on Desktop

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#4670]
With the recent settings v2 revamp, we defaulted to true. 

- [x] LBRY APIs wallet sync should default to local storage setting
- [x] save sync setting to wallet
- [x] if not syncing to APIs, it should still write to local wallet

**Comment by tzarebczan** [comment]
This is still an issue, gave Sean some feedback via DM:

- sync section also says "to enable this feature, click save password on app startup" and it's greyed out (I had checked it during sign in).  This is supposed to refer to the sync balances/data setting, not password.

- sync apply call failed when going to settings page and would lock up app instead of prompting me for a password. 

- wallet was decrypted somehow still - would need to try to repro, but I think sync apply with a blank password was called while it was unlocked (running daemon in the background).

**Comment by jessopb** [comment]
Top bullets done - still interested in repro for some of the bottom bullets:
First - We talked about this messaging - going to leave it as is, but perhaps change the unsigned in text.
Second - This probably won't happen after fixing the checkSync bug on the settings page.
Third - Need repro?
