### ISSUE TITLE
Video Embed will only work 1 time

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4731]
1. Turn on `Floating Player` in the settings.
2. Visit https://open.lbry.com/@dev-test:8/test-embed:b
3. Click the first video.
    - on Web, the floating player appears ✔️
    - on Desktop, nothing happens ❌ (unless you turn off `Floating Player`, which it'll then bring you to the video's page)
4. Close the Floating Player.
5. Click the first video again.  The floating player doesn't re-appear. ❌
  The only workaround found so far is to reload the app/website entirely.

**Comment by tzarebczan** [comment]
Thanks for filing the issue! Definitely confirmed the issue after closing it + clicking same video. It does seem to work on Desktop on master for me though. It does take a couple of seconds to popup the video player.

**Comment by infinite-persistence** [comment]
The embed player's click handler is this:
<details>
  <summary>handleClick( ) - <em>click to expand</em></summary>
   
```javascript
  function handleClick( ) {
    . . .
    if (isMobile || !floatingPlayerEnabled) {
      const formattedUrl = formatLbryUrlForWeb(uri);
      push(formattedUrl);
    } else {
      doPlayUri(uri, undefined, undefined, fileInfo => {  // <-- I.P.: focus is here
        doSetFloatingUri(uri);
        doAnaltyicsPurchaseEvent(fileInfo);
      });
    }
  }
```
</details>

Somewhere down the trails for `doPlayUri`, as long as `fileInfo.streaming_url` has been cached for a particular file, the following short-circuit will run because `alreadyStreaming` will be `true`:
<details>
  <summary>doPurchaseUri( ) - <em>click to expand</em></summary>

```javascript
export function doPurchaseUri(
  uri: string,
  costInfo: { cost: number },
  saveFile: boolean = true,
  onSuccess?: GetResponse => any
) {
  return (dispatch: Dispatch, getState: GetState) => {
    dispatch({
      type: ACTIONS.PURCHASE_URI_STARTED,
      data: { uri },
    });
    . . .
    const fileInfo = makeSelectFileInfoForUri(uri)(state);
    const downloadingByOutpoint = selectDownloadingByOutpoint(state);
    const alreadyDownloading = fileInfo && !!downloadingByOutpoint[fileInfo.outpoint];
    const alreadyStreaming = makeSelectStreamingUrlForUri(uri)(state);

    if (!saveFile && (alreadyDownloading || alreadyStreaming)) {   // <--- Here!
      dispatch({
        type: ACTIONS.PURCHASE_URI_FAILED,
        data: { uri, error: `Already fetching uri: ${uri}` },
      });

      Promise.resolve();
      return;
    }
   . . .
}
```
</details>

This causes the success-callback to never run.

## Questions
I'm thinking of two approaches:
#### 1. Consider the short-circuit as 'success' and run the callback. 
The return statement would then look something like this:
```javascript
  onSuccess(fileInfo); //<--- add this?
  Promise.resolve;
  return;
```
While it seems to fix the issue, I have doubts:
- Since `ACTIONS.PURCHASE_URI_FAILED` is also dispatched, it's confusing to clients -- is it then a success or failure?
- Quite a number of `doPlayUri` callers to test. Changing the meaning seems risky. Any callers rely on this scenario being a failure and should do nothing?

#### 2. Add another optional boolean `considerFetchedAsSuccess` before doing item-1?
This will minimize the impact of the change to just the Embed Player, but it has the band-aide dirty feel.

**Comment by infinite-persistence** [comment]
`Close`
This is no longer relevant after the refactoring in 295b8cf2.  Embed videos now play directly without needing to invoke the floating player, and there's no issue for the test case above (able to play another video, and load the first video again).
