### ISSUE TITLE
Annoying menu bar at the top goes away and reappears at random

### ISSUE THREAD

**Issue by CHJ85** [lbryio/lbry-desktop#4734]
The file menu at the top randomly appears then it goes away. Very annoying. So please ,either have it stay there or remove it completely. Thank you.

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. Which OS are you using? The menu bar would appear if you pressed the alt button, similar to other apps. Is this maybe what's happening?

**Comment by CHJ85** [comment]
I'm on Ubuntu. The ALT key did the trick. Thank you.
On your next version, it'd be a good idea to have it hidden by default though. Because what an annoying menu.
I don't see a purpose of it even being there.

**Comment by CHJ85** [comment]
Anyway. This file menu is driving me nuts.
Is there a way to get rid of it?
Also there is another annoying bug too.
When you zoom (alt+mousewheel) it also scrolls the page up and down.

**Comment by CHJ85** [comment]
Is there a way I can get rid of it for good though?
The ALT key works, but I have to press it every time I open the app.
