### ISSUE TITLE
daemon mode for lbry-desktop

### ISSUE THREAD

**Issue by ITwrx** [lbryio/lbry-desktop#4735]
**Is your feature request related to a problem? Please describe.**
videos take too long to download and/or buffer too much to be practical/popular.

**Describe the solution you'd like**
As a predecessor to a more robust service node infrastructure, like mentioned in #3413, it would be nice if lbry-desktop had a daemon mode so that the user could close the application window, but lbry would continue sharing in the background. It would be nice to have a scheduler (share midnight -8am, for instance), and upload bandwidth limit setting. Bonus points if LBRY issues LBC rewards based on sharing amount periodically. Being able to set a share folder would be nice too, so you could choose which files get shared in daemon mode, if you can't already specify that with normal mode. That would allow you to only use bandwidth for files you really care about sharing. Maybe a "selfish mode" setting where only the files in your channels get shared, without the need for special folders.

**Describe alternatives you've considered**
Waiting for full blown service node infrastructure and/or using a client that can't play a video without buffering constantly. :)

**Comment by tzarebczan** [comment]
The app already continues to run when you close it. The other various suggestions already have separate issues in their respective repos

**Comment by ITwrx** [comment]
Ok. I should have checked that. Sorry for the noise.  

Just for the record, i think that "hide" when user clicks "close/quit" is an anti-pattern if it's not exposed as an option to the user.

**Comment by tzarebczan** [comment]
It will be in the next release actually!

**Comment by ITwrx** [comment]
that's great! thanks
