### ISSUE TITLE
in-app robots.txt 

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#4739]

**Comment by kauffj** [comment]
add config value for indexable?

**Comment by kauffj** [comment]
provide default, do not require configuration

**Comment by seanyesmunt** [comment]
This doesn't seem to work in production. I think this is the issue

"Lighthouse doesn't check that your robots.txt file is in the correct location. To function correctly, the file must be in the root of your domain or subdomain."

https://web.dev/robots-txt/?utm_source=lighthouse&utm_medium=devtools
