### ISSUE TITLE
"Password updated successfully" kept showing up

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4749]
1. Login to lbry.tv
2. Go to `Settings Page`
3. I added a password to my account. _Password updated succesfully_ appeared as expected.
4. Go into `Settings > Notifications`.
5. I unchecked my email to opt-out entirely, then clicked `Done`.  _Password updated succesfully_ appeared again. ❌
6. Go into `Settings > Advanced` and back out with `Done`.  _Password updated succesfully_ appeared again. ❌
7. Do your normal stuff (watch content), and return to `Settings` later.  _Password updated succesfully_ appeared again. ❌

**Comment by tzarebczan** [comment]
Nice bug find!
