### ISSUE TITLE
Channel search is broken

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4751]
1. `master` = `72187ca5`
2. Type "@lbry", then select the 2nd selection.  You get a 404.  Used to work to go into the channel directly.

**Comment by infinite-persistence** [comment]
@seanyesmunt , reverting the `Search percent sign bug` seems to fix it.  Or perhaps there is a matching change in redux that is pending?

**Comment by ioancole** [comment]
lbryio/lbry-desktop#4753

Updated original PR (lbryio/lbry-desktop#4730) to include fix for this bug.

**Comment by tzarebczan** [comment]
Thanks for taking care of it so quickly @ioancole ! 

Don't forget to reach out to us for some [appreciation](https://lbry.com/faq/appreciation)!
