### ISSUE TITLE
Per channel notification settings

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#4762]
Internal APIs now supports an optional param to disable notifications (default to false): NotificationsDisabled (https://github.com/lbryio/internal-apis/commit/85c0c9ba473d123c821a24dbcc15637000c6dc09#diff-0b74aa8ad1cbaacf3aa174a3ce04d627R31)

The same api can be used to edit an existing subscription. 

- [ ] Add bell icon on channel/content pages for notifications when you are subscribed, with the ability to turn on and off. Make it clear which state is turned on (some users are still confused on mobile mode with heart/broken heart). 

- [ ] store and sync notification preference in the wallet

**Comment by kauffj** [comment]
(Possibly reduce notifications to one property, with @tzarebczan )
