### ISSUE TITLE
Download link not including extension for file

### ISSUE THREAD

**Issue by Blanxs** [lbryio/lbry-desktop#4763]
**Bug**

When using the download link through "Share" on certain files, the file downloaded doesnt have the extension attatched.

**To Reproduce**
1. Go to lbry://@history#1/Osprey-NewVanguard154-BritishBattleships1939-45Part1QueenElizabethandRoyalSoverignClassespdf#5

2. Click on Share, then copy download link
3. Put download link into website url, and download
4. Error shows when the file downloads without extension

**Expected behavior**

Should download with extension. When it is downloaded through the download button on the app, it downloads with the correct extension. For this linked file, its pdf

**Screenshots**

**System Configuration**

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Additional context**

**Comment by tzarebczan** [comment]
Does the file itself have a space in the file name? Think this is a lbry.tv issue only on some browsers that's filed under https://github.com/lbryio/lbrytv/issues/232

**Comment by Blanxs** [comment]
@tzarebczan  It does, but so do others that work fine. Even lbry tv reads the file as pdf for the one that doesnt download properly with the link. Here are examples of 2 files that seem perfectly similiar, but the links work for them differently.

Download Link:   https://lbry.tv/$/download/Osprey-Elite079-TheRoyalNavy1939-45pdf/b957d41d07026712c53be3f323c3c6481421a154

LBRY TV Link:  https://lbry.tv/@history:1/Osprey-Elite079-TheRoyalNavy1939-45pdf:b

Downloaded File Name:   Osprey - Elite 079 - The Royal Navy 1939-45 (2).pdf



Download Link:   https://lbry.tv/$/download/Osprey-NewVanguard154-BritishBattleships1939-45Part1QueenElizabethandRoyalSoverignClassespdf/557fd1dc792befce69f31424a50bfeb218a1179f

LBRY TV Link:   https://lbry.tv/@history:1/Osprey-NewVanguard154-BritishBattleships1939-45Part1QueenElizabethandRoyalSoverignClassespdf:5

Downloaded File Name:  Osprey - New Vanguard 154 - British Battleships 1939-45 Part 1 (3)

**Comment by Blanxs** [comment]
Forget the numbers at the end lol. I just downloaded it a few times as a test

**Comment by stefansundin** [comment]
I think this issue is resolved now thanks to https://github.com/lbryio/lbrytv-player/commit/67249b95392200ca4a6dc46991b885475e73a4a5.

**Comment by tzarebczan** [comment]
Thanks for the poke!
