### ISSUE TITLE
Custom urls in .env not displaying correctly

### ISSUE THREAD

**Issue by michaelmitnick** [lbryio/lbry-desktop#4789]
**Bug**
When the custom (external) URL is displayed in the .env file for the sidebar, the main URL is merged and causes a 404 error. The redirect assumes it is an internal link, but I don't know how to resolve the link for that file.

**To Reproduce**
1. The link is incorporated in the .env file in lbry.lat server
2. The command is executed: NODE_ENV=production yarn compile:web
3. For localhost the link is not shown in the sidebar
4. PINNED_URI_1=https://t.me/lbrylatamoficial It should redirect to an external URL, but it looks like this: **lbry.lat/https://t.me/lbrylatamoficial**

**Expected behavior**
It is expected that it redirects to the external link with a new tab.

**System Configuration**

- LBRY Daemon version: 0.81.0
- LBRY App version: 0.47.2 - Latest changes from GitHub
- Operating system: Linux Mint 19

**Additional context**
Sidebar links don't work on localhost. If I could know how to make it work I could do more research. Thank you.

**Comment by seanyesmunt** [comment]
I see the issue. It will be fixed shortly

**Comment by seanyesmunt** [comment]
@michaelmitnick This is fixed now (will be live in 5-10 minutes).

You will need to add `http` or `https` to your links in the .env so it works.

**Comment by michaelmitnick** [comment]
Perfect, thank you very much. I'll take a look. :)
