### ISSUE TITLE
i18n: Allow support for string overloading (multiple contexts)

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4796]
## ?
Let me know what you guys think, and I can take a stab at changing the handful of reported cases.

## Issue
While a word in English can be re-used in several areas, the localized version in many languages require a different word due to difference in context and grammar (e.g. noun vs. verb, past vs. present tense, etc.)

## History
This has been briefly discussed in the past, and is still being brought up from time to time in the Translators Hives in Discord.  I believe if we perform verification on the translated strings, we'll uncover even more instances.

## Suggested fix for the short term
On a case-by-case basis (as reported by the Translators), split the affected strings into several string IDs as shown below:

**English (all resolves to the same value):**
```javascript
"SID_SUPPORT_FOR_CLAIM": "Support",
"SID_SUPPORT_FOR_HELP": "Support",
```
**Chinese**
```javascript
"SID_SUPPORT_FOR_CLAIM": "支持",
"SID_SUPPORT_FOR_HELP": "援助",
```
**Client side:**
```javascript
 label={__('SID_SUPPORT_FOR_CLAIM'} 
````
## Cons
- While the suggested fix allows better translation without major changes to the entire code base, we'll end up with a mixture of "inline string" and "string ID" usages in the code, which can be a bit messy.  But I think using all caps for the string ID should make it obvious on what is going on.

**Comment by infinite-persistence** [comment]
## Alternative syntax to convey context:

**English (all resolves to the same value):**
```javascript
"[Support] context: verb for supporting a claim": "Support",
"[Support] context: button to get help": "Support",
```
**Chinese**
```javascript
"[Support] context: verb for supporting a claim": "支持",
"[Support] context: button to get help": "援助",
```
**Client side:**
```javascript
 label={__('[Support] context: verb for supporting a claim'} 
````

## Info:
Translators will need to learn that when the `"[ ] context:"` format is seen, translate the string inside the bracket and not the context string.  We could add code to detect this and simply revert to English.

## Source
Item 2 from https://www.transifex.com/blog/2020/tips-providing-context-translation/

**Comment by kauffj** [comment]
I missed the first filing of this until the reply happened. Great work on this @infinite-persistence. It seems reasonable to me.

Whether to adopt the `[ ] context:` system or the `ID_STRING` system should be a call made by @seanyesmunt. Adopting the bracket syntax should be a relatively light change, so if that system is preferred we should just adapt it.
