### ISSUE TITLE
no followed channels in app

### ISSUE THREAD

**Issue by Tcll** [lbryio/lbry-desktop#4799]
**Bug**
app says I'm not following anyone

**To Reproduce**
1. launch the latest appimage (0.48.0)
2. wait for an error prompt (typical network error from sluggish performance that happens 90% of the time)
![Screenshot_2020-09-28_11-03-14](https://user-images.githubusercontent.com/773959/94450251-087dcf00-017b-11eb-85dd-4d6540b53185.png)
3. wait for the page to update showing an empty channel
![Screenshot_2020-09-28_11-14-14](https://user-images.githubusercontent.com/773959/94450917-d751ce80-017b-11eb-9fbd-761063675904.png)

luckilly both lbry.tv and odysee.com still show who I'm following...
I've disabled backup from the app as of this to avoid my follows being deleted a 2nd time

**Expected behavior**
should show my channel just like on lbry.tv:
![Screenshot_2020-09-28_11-19-08](https://user-images.githubusercontent.com/773959/94451534-84c4e200-017c-11eb-8063-4d4ac6e83dc6.png)
I'm following ~300 accounts

**System Configuration**

- LBRY Daemon version:
```
{
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "desktop": "XFCE",
    "distro": {
      "codename": "xenial",
      "id": "ubuntu",
      "like": "debian",
      "version": "16.04",
      "version_parts": {
        "build_number": "",
        "major": "16",
        "minor": "04"
      }
    },
    "lbrynet_version": "0.81.0",
    "os_release": "4.15.0-117-generic",
    "os_system": "Linux",
    "platform": "Linux-4.15.0-117-generic-x86_64-with-Ubuntu-16.04-xenial",
    "processor": "x86_64",
    "python_version": "3.7.9",
    "version": "0.81.0"
  }
}
```
- LBRY App version: 0.48.0
- LBRY Installation ID: <avoided unless absolutely necessary>
- Operating system: Xubuntu 16.04 (yes I'm still stuck here u.u)

**Additional context**
if this adds anything, as of last night when I went to check my account,
I was prompted with a welcome screen that wouldn't update to show the home page...
I selected the same option as I'd had on my profile (allow LBRY to collect data, but not 3rd parties) and accepted the TOS (again)
it continued appropriately with no issues until just now (the next morning)

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. The login data is stored in temp data and may log out sometimes (even though the wallet data is all there since that's outside of the lbry.tv login process). 

Try logging back in and you should see all the subs back. If not, shoot us an email at hello@lbry.com and we'll try to help recover them.

**Comment by Tcll** [comment]
I actually forgot to mention I did try that already, that's actually why I was motivated to create this issue... heh
but I just tried again anyways, and nope, they're still gone... I'll hit you guys up over email then.
at least this isn't as bad as the first time as I still have them on the websites.

**Comment by Tcll** [comment]
just wanted to mention it happened again:
![Screenshot_2020-10-28_15-00-32](https://user-images.githubusercontent.com/773959/97484515-29c70c00-192f-11eb-9392-82c0c13a125f.png)
looks like LBRY resets the profile when your HDD is busy
(was running IPFS cleanup requests when launching)
