### ISSUE TITLE
Invite links for content

### ISSUE THREAD

**Issue by nikooo777** [lbryio/lbry-desktop#4802]
**Is your feature request related to a problem? Please describe.**
When a user is redirected to a video on LBRY they should have more incentives to interact/signup. Creators can help with this.

**Describe the solution you'd like**
A creator should be able to share a video similarly to how they can share/invite users through their channel.
For example this is how it looks when a creator invites someone over to their channel: https://lbry.tv/$/invite/@femalewrestling:2
This however doesn't work for videos: https://lbry.tv/$/invite/@johnnyringo:c/Elvis-Presley-was-a-Catfight-AND-Women's-Wrestling-Fan-it-Appears!:8 but it would be interesting/good if it did.

**Comment by tzarebczan** [comment]
Users who visit content for the first time via a direct URL and don't have an inviter have one set to the channel. I think this is good enough for now.
