### ISSUE TITLE
Warn that .mov files cannot be streamed

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#482]
When a user uploads a .mov file, they expect it to be able to be streamed. However, due to the .mov not being playable by `render-media`, we cannot stream them. A warning should be displayed to users on publish that, at least for now, .mov is download only.

**Comment by btzr-io** [comment]
https://ffmpeg.org/general.html#Video-Codecs
Any chances to integrate this? ^^

**Comment by btzr-io** [comment]
https://www.npmjs.com/package/fluent-ffmpeg

**Comment by tzarebczan** [comment]
In addition to this, should we provide HTML5 streaming video guidelines? The whole metadata thing is tricky too for it to stream properly. I think that would remove some confusion.

**Comment by btzr-io** [comment]
It should also trigger a  warning for all files that can't be streamed ^^
https://www.chromium.org/audio-video

**Comment by MSFTserver** [comment]
what about an option like this in the future?
https://github.com/taltultc/react-native-mov-to-mp4

**Comment by seanyesmunt** [comment]
This will be better addressed in a larger video player re-work. But a easier fix would to just add a label if the file that a user selects is a `.mov`.

`Currently .mov files cannot be streamed inside the app. Considered uploading a different file type.` Or something similar.

**Comment by tzarebczan** [comment]
There's a note about mp4s being most compatible on publish now, closing.
