### ISSUE TITLE
remaining wallet sync / subscribe issues

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#4830]

**Comment by tzarebczan** [comment]
From Discord, another scenario: 
[1:51 AM] Steest: Well, most of the instances seem to occur when signing-in. I've reported 1 way before,  but I found another way I think.
1) Open odysee.com
2) open multiple random tabs on frontpage
3) open new odysee.com tab and sign in
4) go back to one of previous tabs that is not yet signed-in and click "like"
5) reload page
6) observe followers are gone

**Comment by kauffj** [comment]
There are two issues:
1. Multi-tab browsing (less important, potentially requires server-side adjustment/tracking)
2. An IAPI call failing, resulting in an empty subscription set, triggering an overwrite when user adds a new channel.

2 is more important than 1.

**Comment by kauffj** [comment]
There's still no loading animation while my wallet is syncing.

**Comment by tzarebczan** [comment]
What we decided:
- show error/refresh screen if sync get / preference get fail
- prevent sync set if there are no subs - call preference get/sync loop first?
