### ISSUE TITLE
Full Uninstall Option [no trace files]

### ISSUE THREAD

**Issue by MSFTserver** [lbryio/lbry-desktop#484]
## The Issue
No Complete Uninstall Option
### Steps to reproduce
Option 1
1. Select the Uninstall.exe
2. Leaves Practically Every File if not Run As Admin
3. Manually go through and delete and then use windows uninstall option to get rid of hidden junk
4. still leaves trace files after all this

Option 2
1. go to windows uninstall in control panel
2. select uninstall lbry
3. leaves files in program folders and the %appdata%

### Expected behaviour
the uninstall should have 2 options
- first way keep it like you have it
- second way have it delete every last bit of LBRY stuff as if the user wouldn't want it on that PC any longer or just doesn't want to use the app any further but also have pop up warning to backup default_wallet to ensure funds are not lost and if they don't already have it backed up and want to an option to select a new directory and copy the default_wallet over to it 
### Actual behavior
uninstall.exe doesn't really uninstall anything that would be deemed as an uninstall, even using the windows feature to uninstall leaves scrap files around that wouldn't be need if the Expected Behavior statements didn't play a role
Once a user installs you have to manually delete to get rid of everything LBRY it seems a bit intrusive

**Comment by etisdew** [comment]
It was unexpected to find a wallet backed up after removing it for the development build from source. Should I bother using the backup I made?

**Comment by tzarebczan** [comment]
Yes, the lbry data and wallet are not deleted during Uninstall, only the program related files. This is to ensure that you still have your lbry data and credits in case you reinstall lbry or bring it to another pc.

Migration guide here:
Https://lbry.io/faq/backup-data

**Comment by liamcardenas** [comment]
@tzarebczan are we not planning on implementing this feature?
