### ISSUE TITLE
App crash on invite page

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#4843]
I noticed this a few weeks ago but it only happened in some cases, but now more users are noticing it. The strange part is that it doesn't fail when you open  up dev tools - which is inline with the error, probably something around the view port. 

URL: https://odysee.com/$/invite/@timcast

Access when not logged in - this way the claim previews show. 

```
instrument.ts:129 RangeError: Invalid array length
    at view.jsx:480
```

code: 
```
 {loading && (
            <div className="claim-grid">
              {new Array(dynamicPageSize).fill(1).map((x, i) => (
                <ClaimPreviewTile key={i} placeholder="loading" />
              ))}
            </div>
          )}
```

![image](https://user-images.githubusercontent.com/8120721/95112997-ba834100-070f-11eb-805c-d84bec7781ee.png)

**Comment by seanyesmunt** [comment]
This is fixed
