### ISSUE TITLE
deb file errors and invalid mime type

### ISSUE THREAD

**Issue by Goddard** [lbryio/lbry-desktop#4853]
Current deb as of today has a few errors.  

1. Since it isn't signed most user friendly package mangers like Discover, or Gnome Store won't work.
2. If you install via the terminal you get this output.
chmod: cannot access '/opt/LBRY/chrome-sandbox': No such file or directory
Error in file "/usr/share/applications/org.kde.kdeconnect_open.desktop": "*/*" is an invalid MIME type ("*" is an unregistered media type)

The application works, but just thought I would share this to see if it can be improved.

**Comment by kauffj** [comment]
Thanks @Goddard. @jessopb is this related to Electron upgrade?

**Comment by tzarebczan** [comment]
Most likely related to certain distros...the electron upgrade may help. We should probably encourage the appimage more also.

**Comment by tzarebczan** [comment]
This sounds like an issue with KDE, I found various bugs like https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=963498  filed online. 

We also have an appimage available which provides better in-app upgrade support. 

Closing this for now.

**Comment by Goddard** [comment]
I know I posted 1 issue, but it is really 3 things.  
1. The deb should be signed which is the major issue because it causes most simple user friendly installers to not work.  It causes you to be required to drop to a terminal and run dpkg.  As opposed to Gnome Software/Discover etc..
2. chmod: cannot access '/opt/LBRY/chrome-sandbox': No such file or directory - I am not really sure if this even matters, but just bringing it to your attention.

**Comment by tzarebczan** [comment]
Signing a deb package isn't part of the electron packaging tools we're using and it's still supported in most app installers. We should really make the appimage the primary installation method since it supports autoupgrades better. 

The chmod issue only affects a few OSes and we'd need to disable sandboxing on the deb for it to work on those. Since it works without it, we'll keep it for now.
