### ISSUE TITLE
Add Confirmation before publishing file or creating channel (show fee estimate)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#486]
## The Issue
Currently, when a user clicks the Publish button to submit content there is no confirmation of their action but instead, it tells them that their publication is pending. Should we have some sort of confirmation box which would at least show the Content URL along with deposit amount? This came from a user suggestion and I thought it was worthy of at least bringing it up. 

This is possible today with the --preview feature on the SDK. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kauffj** [comment]
Yes. This would just be to generally improve the post publishing UX. Act like it is published as much as possible, but show some indicator estimating how long until others can see it.

**Comment by tzarebczan** [comment]
We now have the --preview command which will show the fees / metadata that set before the tx is created.
