### ISSUE TITLE
Overall React Lag or Extra Re-renders / Volume slider laggy since v0.48

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4862]
Version|Local debug build | Official builds
------|------|------|
`master` | laggy ❌ | dragging seems ok, but direct clicks (e.g. at 50%) seldom register
`v0.48.0` | laggy ❌| slightly laggy ✔️
`v0.47.2` | smooth ✔️| smooth ✔️

It's probably no big deal since production builds and lbry.tv is fine, but it might be a hint that something inefficient got introduced after 0.47.2.

**Comment by DispatchCommit** [comment]
This is some issue with react or redux that causes almost all the components on the page to re-render when updating the value of volume in the store.

**Comment by tzarebczan** [comment]
Issue moved to [OdyseeTeam/odysee-frontend #189](https://github.com/OdyseeTeam/odysee-frontend/issues/189) via [**ZenHub**](https://www.zenhub.com/)
