### ISSUE TITLE
AppImage update option

### ISSUE THREAD

**Issue by cmatomic** [lbryio/lbry-desktop#4888]
Is possible to update AppImages without going directly to the LBRY website , for that, the update option must be inserted in AppImage to be used later with app  [AppImageUpdate](https://github.com/AppImage/AppImageUpdate).
here you can find the information needed to implement these options
https://github.com/AppImage/AppImageSpec/blob/master/draft.md#update-information

**Comment by tzarebczan** [comment]
The app image already has an in app auto update process that follows our build processes, including release candidates, so I don't think we'll be supporting other means of updating. Thanks for the suggestion!
