### ISSUE TITLE
Ability to expand images in markdown posts for viewing

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4899]
Images are usually resized to the same width as the paragraph in an MD Post.  In the recent `@lbry` post about the economy, I wanted to view the chart in greater detail.  Messing with the browser's zoom level and changing it back wasn't the best experience.

- It would be nice if clicking the image would invoke a temporary popup to view the image in a larger size, like what Discord does for attachments.
- Github simply opens the image in another tab, which is an ok temporary alternative, imo (not the best, though)

**Comment by kauffj** [comment]
Good idea. New tab perhaps isn't ideal but it may be just a few lines of JS to wrap `<a>` around `<img>` in the markdown component.
