### ISSUE TITLE
App crashes on Take snapshot +upload in latest version

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#4902]
No crash page, just goes blank and get a web contents error. 
![image](https://user-images.githubusercontent.com/8120721/96143394-0e8ce300-0ed1-11eb-9029-0ad4dda3847e.png)

**Comment by tzarebczan** [comment]
This will be disabled for now until Electron side is fixed: https://github.com/electron/electron/issues/20750

**Comment by tzarebczan** [comment]
https://github.com/electron/electron/issues/20750#issuecomment-727066103

**Comment by jessopb** [comment]
hey! fixed!
