### ISSUE TITLE
Deeplinks not working corectly

### ISSUE THREAD

**Issue by kodxana** [lbryio/lbry-desktop#4915]
**Bug**
URL in format lbry://@Karolajn#319a7ffcebe1c4d23b5b5fc2e66452695e030e88 won't open in app. It's open app itself but won't move you to specify video/channel.
Tested with web browsers firefox/chrome/edge.

**Expected behavior**
lbry://@ format links should open specified videos instead of opening just app.

**System Configuration**

- LBRY Daemon version: 0.83.0
- LBRY App version: 0.48.2
- LBRY Installation ID: 3MraqwPqT8oNx1nrFKuQVmYEYn2tKwBCVgnLV7mswSPg8m2Pq89fSu8zFzX5zLehdy
- Operating system: Windows 10

**Comment by tzarebczan** [comment]
Nice catch. I meant to test this with the electron changes and forgot.

**Comment by 53jk1** [comment]
It's working with Linux correctly, I checked this out right now. :+1: 
Peace :heart:

**Comment by tzarebczan** [comment]
closing for https://github.com/lbryio/lbry-desktop/issues/6703
