### ISSUE TITLE
Published file stays in Publishes area after removing (without abandoning) 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#493]
## The Issue
If you remove a published file but don't check the "abandon" option, it will stay in your Publishes area but will seem like you haven't downloaded it.  I'm not sure how we would want to handle this - what would be the scenario where someone would want to remove it from their list without abandoning the claim? If they did this, they would have to manually abandon the claim via CLI right? 

### Steps to reproduce
1. Remove published file but don't check the abandon option
2. Go back into Publishes, it's still there. 

### Expected behaviour
Not sure

### Actual behaviour
Tell us what happens instead

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by MSFTserver** [comment]
yes if the user forgets to press the abandon claim they must use the CLI to abandon it, i went through this first time using it lol

**Comment by MSFTserver** [comment]
something like this would be a work around
![image](https://user-images.githubusercontent.com/18357967/29998882-efc4955c-8fea-11e7-8532-ead6473a0562.png)

**Comment by liamcardenas** [comment]
I think we should remove the option to abandon claim from claim page when clicking the remove button (or just disable the button), what do you guys think?

**Comment by MSFTserver** [comment]
not sure if this issue was addressed i think would fall under here but when i press the trash can button for one of my claims it goes oit of published but remains in downloaded, shouldnt it be removed all together from the app ui maybe not delete my file but delete blobs ect.

**Comment by kauffj** [comment]
@liamcardenas if we remove the option, are you suggesting we always abandon it? If not, I suspect at least some users will be confused that removing a file for one of their publishes does not remove the ability for others to discover and access it.

**Comment by tzarebczan** [comment]
https://github.com/lbryio/lbry-app/issues/895
