### ISSUE TITLE
Simplify / revamp search filters for odysee (and lbry.tv)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#4945]
Most sites have at least some simple search filters that we should add back to Odysee. Channel vs videos would be one, and we can also add something to sort by newest/oldest (available today) and should be able to add a "last day/month/year/etc" param (switch between date/relevance) easily. 

Also, unleash the infinite scroll!

**Comment by kauffj** [comment]
#5677 and #5181 are related tickets that it may make sense to do at the same time. Please include these if it's efficient to do so.
