### ISSUE TITLE
Restore winning claim to search results on odysee.com

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#4946]

**Comment by kauffj** [comment]
- Resolve both channel and non-channel
- Relabel (competing, remove lbry://)
- Fix display of reposted channels (lbry://666)
- If possible to do quickly, add support for reposting channels (but not called this?). If hard, file.

**Comment by kauffj** [comment]
- Community Choice -> Most Supported

**Comment by kauffj** [comment]
Do not show anything if nothing is at the name for the channel or the content. This change is fine to make on all versions.

**Comment by kauffj** [comment]
Strip characters that are not valid in names, especially spaces.

**Comment by seanyesmunt** [comment]
https://github.com/lbryio/lbry-desktop/issues/4958
