### ISSUE TITLE
Commenting moderation + mute/block rename

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#4947]

**Comment by tiger5226** [comment]
Commentron supports this now based on the requirements posted https://github.com/lbryio/commentron/issues/13

Specifically:

Block (publisher) - cannot comment on my channel
Block (site admin) - cannot comment
Block and delete all (publisher) - above, plus delete all from my channel (channels?)
Block and delete all (site admin) - above, delete all comments, everywhere


The SDK has an open issue to create a signing api so app team can implement and leverage external services with authentication. https://github.com/lbryio/lbry-sdk/issues/3109

The API is defined below: 

Method: `moderation.Block`

```golang
// BlockArgs Arguments to block identities from commenting for both publisher and moderators
type BlockArgs struct {
	//Publisher or Commentron Admin
	ModChannelID   string `json:"mod_channel_id"`
	ModChannelName string `json:"mod_channel_name"`
	//Offender being blocked
	BannedChannelID   string `json:"banned_channel_id"`
	BannedChannelName string `json:"banned_channel_name"`
	// Blocks identity from comment universally, requires Admin rights on commentron instance
	BlockAll bool `json:"block_all"`
	// If true will delete all comments of the offender, requires Admin rights on commentron for universal delete
	DeleteAll bool   `json:"delete_all"`
	Signature string `json:"signature"`
	SigningTS string `json:"signing_ts"`
}

// BlockResponse for the moderation.Block rpc call
type BlockResponse struct {
	DeletedCommentIDs []string `json:"deleted_comment_ids"`
	BannedChannelID   string   `json:"banned_channel_id"`
	AllBlocked        bool     `json:"all_blocked"`
	//Publisher banned from if not universally banned
	BannedFrom *string `json:"banned_from"`
}
```
The payload to sign is with the channel name:

https://github.com/lbryio/lbry-sdk/blob/09ee104b8cb3f198abfded05f1876da2855eb2f8/lbry/extras/daemon/comment_client.py#L56-L63

**Comment by tiger5226** [comment]
its coming. SDK update was released 1/22. Once the sdk is on nsa or prod, can work with @seanyesmunt to use it.
