### ISSUE TITLE
UI flow for competitive reposting (including channels)

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#4958]

**Comment by jessopb** [comment]
![somethingrepost](https://user-images.githubusercontent.com/36554050/99293026-0d244280-2810-11eb-85f1-ac4132373e8e.png)
Probably switch primary and secondary buttons,
Each go to a page: publish/new channel, repost.
Repost page is a claimListPicker with a searchbar similar to Content tab of Channel page, with searches constrained to name, ?isChannel, displaying compact claimPreviews.

As you type, tim , timc, etc.. you see fewer results with their number of publishes and other useful info.

**Comment by jessopb** [comment]
Probably also hide or disable some of the controls when there's nothign to control...
