### ISSUE TITLE
The new Channel Language setting doesn't seem to go through

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#4968]
1. Create a new Channel and pick any language for the `Primary Language` and `Secondary Language`
2. Wait for the confirmation
3. See the `About` section of the Channel.  The `Language` field is blank.
4. Edit the Channel and put in values for `Primary Language` and `Secondary Language` again.  Now, it appears in About.

**Comment by tzarebczan** [comment]
It's probably going through but the channel is not being re resolved after the update. Will check it out tomorrow, thank you!

**Comment by tzarebczan** [comment]
Can confirm this is a bug, good catch!
