### ISSUE TITLE
Variable bit-rate UI side

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#4980]

**Comment by Tcll** [comment]
please make sure I can disable this, I hate it when youtube does this and auto-switches to 140p
my PC can't do 720p60 (browser codec) and I'm fine with 480p static

**Comment by DispatchCommit** [comment]
The player already has the plugins `videojs-hls-quality-selector` and `videojs-contrib-quality-levels` implemented, and will appear if available in accordance with the source(s) provided to the player, and if the source(s) include lower quality transcoded streams.

The UI side is already implemented: https://github.com/lbryio/lbry-desktop/blob/master/ui/component/viewers/videoViewer/internal/videojs.jsx#L350-L352
