### ISSUE TITLE
AutoPlay in Floating Player only works one time

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#5000]
1. Play a video and go into FP mode.
2. At the end of the first video, AutoPlay does play the next video automatically.
3. At the end of the second video, AutoPlay wasn't invoked.  In non-FP mode, AutoPlay continues to work beyond the second video.

**Comment by DispatchCommit** [comment]
https://github.com/lbryio/lbry-desktop/blob/master/ui/component/viewers/videoViewer/internal/videojs.jsx#L170

I'm guessing it's related to how the player's auto play option is configured, but I need to dig deeper on *how* play is being triggered with autoplay disabled before I try touching this.
