### ISSUE TITLE
no load external link

### ISSUE THREAD

**Issue by FrancescZOE** [lbryio/lbry-desktop#5002]
https://open.lbry.com/@SomosLaDulceRevoluciòn:e/Compartiendo-Vida-con-Josep-Pamies..-Soberanía-y-Salud:6?r=5EB2RFXNqAXoK8wEFUDJYSc8AQtD3JgG

Hello , external links to content does not work.. the web browser remains ..thinking and stops.. does not loads content.

I have no problem to seeing it at my lbry account.

**Comment by tzarebczan** [comment]
Please try again now, we had some heavier than normal load yesterday.
