### ISSUE TITLE
Make arrow keys move 5 seconds instead of the 10 seconds

### ISSUE THREAD

**Issue by CyberFoxHax** [lbryio/lbry-desktop#5009]
When scrubbing with arrow keys on the keyboard, YouTube already uses 5 second increments. Personally 5 seconds is also a bit too long, but I'm already used to this.

**Comment by DispatchCommit** [comment]
On YouTube `J` `K` `L` are -10sec, play/pause, and +10sec. Arrow keys are +/-5sec increments. Period/Comma are single frames.

Would be nice to map similar behavior.

Relevant code is here: https://github.com/lbryio/lbry-desktop/blob/master/ui/component/viewers/videoViewer/internal/videojs.jsx#L287-L318

**Comment by tzarebczan** [comment]
J K L are now implemented to match YT.
