### ISSUE TITLE
links does not work

### ISSUE THREAD

**Issue by FrancescZOE** [lbryio/lbry-desktop#5025]
https://open.lbry.com/@DignidadParaTodos:9/Conversaciones-con-el-Dr.-Cristian-Duré-desde-Estocolmo-:9?r=5EB2RFXNqAXoK8wEFUDJYSc8AQtD3JgG

instead...

https://lbry.tv/@DignidadParaTodos:9/Conversaciones-con-el-Dr.-Cristian-Duré-desde-Estocolmo-:9?r=5EB2RFXNqAXoK8wEFUDJYSc8AQtD3JgG

so sharing link in the apple aplication does not works correctly

**Comment by tzarebczan** [comment]
Lbry.com is having some temporary issues.

You can also consider using odysee.com
