### ISSUE TITLE
Components don't rerender just because language changes

### ISSUE THREAD

**Issue by jessopb** [lbryio/lbry-desktop#5033]
When you change language, the buttons don't immediately rerender and call the i18n functions.
One solution might be to have each __() actually be a component that detects language setting changes, but that seems inelegant.

**Comment by kauffj** [comment]
originally this was solved by passing the language as a property to the high-level components, triggering a re-render

react components have become lightweight enough that `__` probably could become a component at this point though

**Comment by tzarebczan** [comment]
This seems to be fixed now, closing
