### ISSUE TITLE
Posts Are Too Narrow

### ISSUE THREAD

**Issue by ElectronEsq** [lbryio/lbry-desktop#5043]
**Bug**
Posts are published too narrow.
The CSS is using `width: 40em;` for the containers width, which makes the post a fraction of the containers size, which is too narrow.

**To Reproduce**
Make a post.

**Expected behavior**
The post should fit correctly in to the assigned area and be inline with the rest of the UI.

**Screenshots**
Too narrow. Can look odd:
![image](https://user-images.githubusercontent.com/29914179/99227465-01984200-2837-11eb-9d23-0fb9cfe57019.png)

Correct size:
![image](https://user-images.githubusercontent.com/29914179/99227510-11b02180-2837-11eb-8a51-535a79ae9ccb.png)

The CSS creating the issue:
https://github.com/lbryio/lbry-desktop/blob/master/ui/scss/component/_file-render.scss#L95

`width: 40em;`

```css
  .markdown-preview {
    height: 100%;
    overflow: auto;
    width: 40em;
    margin-left: auto;
    margin-right: auto;
    max-width: unset;
    min-width: unset;
```
**Related**

https://github.com/lbryio/lbry-desktop/pull/3511

**Comment by seanyesmunt** [comment]
The general recommendation for character count per line is about 50-70 characters. Longer than that and it gets hard to read. Currently, text posts are near or above 70 characters so if anything it should be slightly smaller.

**Comment by ElectronEsq** [comment]
Typically, that's for text only and for news/blogs layouts which are designed specifically for that size content.
Images and other content usually expands past recommended character length and the overall layout of the webpage is usually keeps the everything looking smooth.

The issue with LBRY having a 70 character limit for the post total width, is that it creates a lot of unsightly whitespace, which also make it look thinner than it is. Furthermore, the thick scrollbars make the look and feel of a post even less pleasing. I thought the posts were broken, hence GitHub this issue.

![image](https://user-images.githubusercontent.com/29914179/99284254-bf482280-2881-11eb-8737-74945a59ee43.png)

Ideally, it would be good for the width to be something the publisher could set themselves. However, if that's never going to be an option, I would favour a wider area for a more pleasing look.

The below 2nd image would be a good comprise. Same character count, but with larger text and a dark and thinner scrollbar. The white space is a lot more pleasing like this.

From: 
![image](https://user-images.githubusercontent.com/29914179/99284405-f1f21b00-2881-11eb-8183-9f04acf5e5b8.png)

To:
![image](https://user-images.githubusercontent.com/29914179/99284433-fae2ec80-2881-11eb-8d9b-04da0a4da2e7.png)
