### ISSUE TITLE
Symlink does not work: /home/tange/Downloads/LBRY/downloads was removed, reassigning DOWNLOAD to homedir

### ISSUE THREAD

**Issue by ole-tange** [lbryio/lbry-desktop#5065]
**Bug**
I cannot change the download directory to a directory that is symlinked to a dir.

/home/tange/Downloads/LBRY is a symlink.

**To Reproduce**
I tried setting it using the GUI for settings and could not select LBRY, and I tried by editing /home/tange/snap/lbry/134/.config/user-dirs.dirs

When I do that I get:
~~~
/home/tange/Downloads/LBRY/downloads was removed, reassigning DOWNLOAD to homedir
~~~

**Expected behavior**
I expected the dir to be used for downloads

**System Configuration**

Platform: {
  "processor": "x86_64",
  "python_version": "3.7.9",
  "platform": "Linux-5.4.0-51-generic-x86_64-with-Ubuntu-20.04-focal",
  "os_release": "5.4.0-51-generic",
  "os_system": "Linux",
  "lbrynet_version": "0.83.0",
  "version": "0.83.0",
  "build": "release",
  "distro": {
    "id": "ubuntu-core",
    "version": "18",
    "version_parts": {
      "major": "18",
      "minor": "",
      "build_number": ""
    },
    "like": "",
    "codename": ""
  },
  "desktop": "Unity"
}

- LBRY Daemon version: 0.83
- LBRY App version: 0.48.2 
- LBRY Installation ID: 4t9DvN1U9yEavW6o3GxdTLfTBLoQKyGFKKvPx5iCjBb3BBEhtC8EUjVFgYqzWri5k4
- Operating system: Linux (Linux-5.4.0-51-generic-x86_64-with-Ubuntu-20.04-focal)

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. I don't think this is an issue with the app, but potentially some permissions or the SDK. 

Which app version are you running? Deb? 

Can you try setting the download directory to the actual location vs symlink? I'm pretty sure this has worked in the past with symlinks also.

**Comment by ole-tange** [comment]
App version is given in the bug report. It is installed using Ubuntu Snap.

I want to save the file to /nfs/hpdisk/tange/tmp. This is an NFS share that is mounted on /nfs/hpdisk.

I have a work around: Use encfs to mount /nfs/hpdisk/tange/tmp as an encrypted dir in /home/tange/lbry.

LBRY will save to the encrypted dir, and encfs will then write to the NFS share. This can even be a symlink.

One of the problem seems to be that LBRY thinks that to save in /a/b/c/d it should also have permissions in /a/b and /a. This is obviously not true. You only need +x permission for those dirs - not even read permission.

What happens if you move your LBRY dir to foo and then symlink foo to the dir that LBRY is configured to use?
