### ISSUE TITLE
player doesn't close when video deleted

### ISSUE THREAD

**Issue by Tcll** [lbryio/lbry-desktop#5077]
this is really just a notice as we're on revision 10 already and I'm still having the issue after updating twice today
so I'm not certain it's known

but yeah, after deleting the video, the player continues running:
![Screenshot_2020-11-20_08-33-15](https://user-images.githubusercontent.com/773959/99822559-5aaaf300-2b21-11eb-89f3-a37747288c80.png)
and even plays again on re-download (experienced when downloading hangs and is deleted to restart)

and then when returning to the new posts, the player stays open there too:
![Screenshot_2020-11-20_08-33-56](https://user-images.githubusercontent.com/773959/99822770-9e9df800-2b21-11eb-8f26-9f874dfda039.png)

nothing is logged in the terminal when this happens.

**Comment by tzarebczan** [comment]
Thanks for filing!

**Comment by tzarebczan** [comment]
This also happens on web and it tries to play the file after deleting. We should put up a pending delete message locally until the clean is removed after confirmation.

**Comment by Tcll** [comment]
adding to that, remove the player and restore the thumbnail (you had a good system there previously) ;)

and if deletions are scheduled, have on-disk schedules already been considered to be continued after restart and cleared when finished??
(assuming a deletion takes long enough to not end before the app is closed)

**Comment by Tcll** [comment]
just want to confirm this is still an issue in 0.49.4:
![Screenshot_2021-02-24_07-16-13](https://user-images.githubusercontent.com/773959/109000610-edec4b00-7671-11eb-90fb-7158a5266444.png)
hopefully this gets a fix soon :)
