### ISSUE TITLE
LBC improvements

### ISSUE THREAD

**Issue by Tcll** [lbryio/lbry-desktop#5081]
this is actually 2 issues in 1

the most glaring issue is the lack of privacy from being based on Bitcoin instead of Monero
if odysee plans to integrate LBC-tied ads, then privacy for this is an absolute must.

and secondly the amount you earn in ~10 videos a day (the main reason for this request)
now that value has halved again, I expect to be paid for 10/10 videos rather than 1/10 a day in order for community support to not be a continued net-loss.

I know I've mentioned these in an email back in February, but now that things are happening, I feel it's time things actually be done about them.

EDIT: also yes I'm aware about the lack of privacy here on GitHub vs GitLab, please don't attack me for this.
baby steps please, not canyon jumps.

EDIT2: and no I'm not requesting payment be done in watch time as that's currently not possible due to playback issues.
I can't watch videos on the platform like I can on bittube for this to be possible as I can't set a static 480p or 720p30 resolution for the browser codec to keep up with on my machine.

if the desktop app were built in C++/Qt using mpv or local code for streaming video playback which can do 4k30 on my machine, watch time payment might actually be possible.

**Comment by tzarebczan** [comment]
Thanks for the issue. We don't plan to move away from the Bitcoin code base, but privacy improvements would come down the road when Bitcoin adds them.

Rewards are subject to change anytime, see lbry.com/faq/Rewards

We're working on improving the buffering issue and looking into transcoding.

**Comment by Tcll** [comment]
what about per-video payment awarded daily??
sure I understand they're subject to change
but I feel like I'm being ripped off and can't give back much because of it :/

tbh I actually like the daily reward system, but the issue is I'm only rewarded for the first video watched for the day
why can't that reward be tallied for the videos watched the previous day??

we need something more sustainable than 0.25 for 10 videos watched
otherwise I'll have to start really limiting my tips and reposts to 0.01 :/
I usually tip or repost for 10 when I find something I feel is very important
(would give even more if I could make content)

that's the primary issue here, I'm being choked off :/

> We don't plan to move away from the Bitcoin code base, but privacy improvements would come down the road when Bitcoin adds them.

that's a shame, and a disappointment u.u
I personally don't like the dangers of my ledgers being public.

**Comment by tzarebczan** [comment]
The LBC we have for rewards is limited and we've been spending too much with our recent growth.

**Comment by Tcll** [comment]
well... dangit >.<

btw just to be clear, I'm not ungreatful in the least, nor am I trying to sound selfish ;)
it's just I've gotten set on a community support path that's now being threatened
and on top of that I can't contribute as much as I want to currently
(I was literally just climbing out of the hole, and there's nothing I hate more than losing progress)

and no I'm not asking for LBC to give out again, please put that towards improving the platform :)
while the packages are nice, they don't exactly solve the problem I'm trying to address
I'm not sure what to recommend though, I just hope more can be done to fix it
possibly more solar-miners? idk...
