### ISSUE TITLE
Followed Channel list mistakenly centered on smaller screens?

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#5094]
1. Desktop
2. Log out
3. When the app's width is wide enough, the Followed List in the sidebar is left-justified
4. Reduce the app's width, then open the Sidebar.  The list became centered.  Might be intentional, but looks better left-justified.

![image](https://user-images.githubusercontent.com/64950861/100205077-9c7fd300-2f3f-11eb-8760-0050876bb4ca.png)

**Comment by tzarebczan** [comment]
@eggplantbren also noticed this recently, thanks for filing!

**Comment by tzarebczan** [comment]
I also see this on mobile mode.
