### ISSUE TITLE
Fix LBC symbol in daily watch reward

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#5096]
![image](https://user-images.githubusercontent.com/8120721/100249699-daaecf80-2f0a-11eb-8dfa-8a3e5afb2b83.png)

**Comment by DispatchCommit** [comment]
This looks fixed?
![image](https://user-images.githubusercontent.com/45262335/105793074-547c2d00-5f3d-11eb-8dcb-1ac7135a9d75.png)

**Comment by tzarebczan** [comment]
Yup!
