### ISSUE TITLE
Re-enable trackpad scrolling on the homepage

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry-desktop#510]
## The Issue
Prior to the navigation arrows on the home page, you could scroll the videos by swiping the trackpad.

### Steps to reproduce
1. Go to home page of the app
2. Try to swipe on the trackpad to navigate
3.

### Expected behaviour
Tell us what should happen
Scroll through the videos by swiping on the trackpad instead of having to use the navigation arrows.

### Actual behaviour
Tell us what happens instead
Swiping does not work.

## System Configuration
Macintosh.

 

- LBRY Daemon version: 0.14.2
- LBRY App version: 0.14.3
- LBRY Installation ID: 3.1.4
- Operating system: Mac OS X 15.6.0

**Comment by hackrush01** [comment]
This is the feature I would love to have back in the app. It saves a lot of
hassle.

-Regards
-Amit Tulshyan

**Comment by kauffj** [comment]
@hackrush01 I'm guessing this will require adding an explicit catch of the javascript event. But this would go nicely along with adding keyboard short cuts more generally.

How did this work previously? Did it scroll multiple rows at once? Just the top row?

**Comment by hackrush01** [comment]
@kauffj This "feature" was there in the app previously before the navigation arrows, so there was a scrollbar under each row, and each of them could be scrolled individually. I guess if need to have this feature back, we would need to re-enable scroll bars(in a hidden way maybe. I'm not sure if that's possible).

**Comment by liamcardenas** [comment]
I am closing this because this is encompassed by the homepage redesign: https://github.com/lbryio/lbry-app/issues/849

**Comment by tzarebczan** [comment]
Re-opening this because we still can't scroll horizontally in the re-design via trackpad/mouse.

**Comment by seanyesmunt** [comment]
Added in https://github.com/lbryio/lbry-desktop/pull/2164
