### ISSUE TITLE
Automatically turn timestamps in a video description into links

### ISSUE THREAD

**Issue by 12people** [lbryio/lbry-desktop#5103]
**Is your feature request related to a problem? Please describe.**
A number of YouTubers who cross-post to LBRY tend to use timestamps in their video descriptions. For example, [IvanOnTech](https://lbry.tv/@ivanontech:a/noo-way-bitcoin-dumps-faster-ready-for) or [TheCryptoLark](https://odysee.com/@TheCryptoLark:e/warning-bitcoin-dump-ethereum-pump:f). On YouTube, these timestamps are links, making it very simple to skip to whatever is interesting to the viewer. Whenever I watch these channels on LBRY, I'm frustrated that I have to find  the correct time in the video manually (especially frustrating on mobile, where it's basically impossible to find the correct timestamp, especially with longer videos).

**Describe the solution you'd like**
Timestamps in video descriptions would be automatically converted to links. Clicking a link would automatically skip to that time in the video.

**Describe alternatives you've considered**
There could be fancier ways to present these timestamps — e.g. in a separate section. However, that would remove the context in which these timestamps were added to the description, and that context could potentially be quite important.

**Comment by tzarebczan** [comment]
Thanks for filing, this would be a great feature to have!
