### ISSUE TITLE
Mouse drags draggable video player instead of volume slider

### ISSUE THREAD

**Issue by SleepingFox88** [lbryio/lbry-desktop#5116]
**Bug**
When clicking and dragging the volume slider of a draggable video player, the video player is dragged across the page instead of the volume slider being dragged with the mouse.

**To Reproduce**
1. Start playing video
2. Browse other videos, making the currently playing video displayed in the bottom left of the screen as a draggable video player.
3. click and drag the volume slider of the playing video
4. Notice that the video is being dragged instead of the volume

**Expected behavior**
The draggable video player should not move while the volume slider is being dragged with the mouse

**System Configuration**
- LBRY Daemon version: 0.83.0
- LBRY App version: 0.48.2
- LBRY Installation ID: 2HzsAmHHyMxAVUmqPe1Ld6EXwtGWYqMcMZyUhbBxik6KHge2EXmcm3Vmx7Xv1vx28u
- Operating system: Linux (Linux-5.4.80-2-MANJARO-x86_64-with-ManjaroLinux-20.2-Nibia)

**Comment by tzarebczan** [comment]
This is fixed on the web and will be included in the next app release (hopefully in the next day or two).
