### ISSUE TITLE
System tray icon is messed up on Linux Mint Debian Edition.

### ISSUE THREAD

**Issue by styromaniac** [lbryio/lbry-desktop#5125]
![Screenshot from 2020-12-02 04-48-09](https://user-images.githubusercontent.com/43807387/100856586-a16de680-3459-11eb-93b6-ab0e4af95da3.png)

**Comment by styromaniac** [comment]
Also, only the visible part of the icon is clickable. The missing space isn't clickable.

**Comment by tzarebczan** [comment]
Thanks for filing. I think i tried it there recently and it was fine. Do you have any scaling changes on your end?

**Comment by styromaniac** [comment]
> Thanks for filing. I think i tried it there recently and it was fine. Do you have any scaling changes on your end?

Nope.

**Comment by styromaniac** [comment]
I have the same configuration after I swapped drives (HDD to SSD) and reinstalled LMDE. For some reason this bug is no longer present, so if you wish, close this issue.

**Comment by tzarebczan** [comment]
Glad to hear that, thank you!
