### ISSUE TITLE
The Related Content Feature is too Broad

### ISSUE THREAD

**Issue by styromaniac** [lbryio/lbry-desktop#5126]
How is it that I end up going from chillwave, retrowave and synthwave mixes to videos about covid-19, and in languages that I do not speak? This feature needs to be reworked. It's taking all of the title and description text and assuming something completely unrelated is related just because of a single word in common. Why not decide that content is related using tags *alone*? I think that would fix it.

Also, a language filter would be very handy.

This issue is especially critical for people who just want to listen to music.

**Comment by tzarebczan** [comment]
Thanks for filing. This is handled under a separate repository and we're aware of the current limitations. Today it uses the title of the content to perform the related content search and we plan to improve this.
