### ISSUE TITLE
Video Previews

### ISSUE THREAD

**Issue by sloganking** [lbryio/lbry-desktop#5142]
**Describe the solution you'd like**
When a user's mouse hovers over a video thumbnail, a three second video previewing that video's content should be displayed in place of the thumbnail. The video should loop repeatedly until the user stops mousing over the video's thumbnail.

**Additional context**
- This feature is available on many popular video distribution sites, including YouTube. https://support.google.com/youtube/answer/7074781?hl=en

- These preview videos should be auto-generated when uploading a video.

- Preview videos should ideally be a small resolution (no larger than the resolution which video thumbnails are displayed at) so as to not waste storage space.

- Preview videos could be stored similarly to how video content is already stored and information for how to download them could be stored on the LBRY blockchain beside the information for how to download the main video.

**Comment by tzarebczan** [comment]
Thanks for the suggestion!

**Comment by DispatchCommit** [comment]
videojs-thumbnails would add support to the player, but would require video ingestion to generate WebVTT thumbnails.

**Comment by jessopb** [comment]
Good for odysee  - for Lbry-Desktop, would require sdk support somehow.
