### ISSUE TITLE
Links to comments don't always work

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#5161]
- Normally, links to comments will bring you directly to that comment.  
- However, for this one, https://odysee.com/@lbry:3f/odysee:7?lc=29f439137dbdbc662453fe8cfd27969ed716627ddf08da6c0ebeb50ba34a86f9, it does not.  It always go to the pinned comment instead. Scroll down to find it (it is still highlighted correctly).  
- The link to the comment right above this one works, though.  And other deeper replies in the upper pages works as well.
- So, I'm not sure what the faulty pattern is.  Maybe something like "if the comment is on the 3rd reply level onwards, _and_ is on "page 2" (infinite scroll) onwards in the comments section, the link does work"?

**Comment by tzarebczan** [comment]
I've also noticed that videos autoplay sometimes when clicking from notifications - should disable that too. 

Thanks for filing!

**Comment by infinite-persistence** [comment]
## Close
This has been addressed while doing Comment Pagination.

If we end up reverting again in the future, the fix for this in the "fetch all" world is just to find the comment beyond the second level of replies.
