### ISSUE TITLE
Add support for yandex video searches

### ISSUE THREAD

**Issue by neb-b** [lbryio/lbry-desktop#5166]
Only did a quick read but it looks like it might require returning a video element with the player URL in the initial HTML when it's being crawled by yandex. That definitely would be tricky.

https://yandex.com/support/video/partners/videoplayer.html

**Comment by tzarebczan** [comment]
Issue moved to [OdyseeTeam/odysee-frontend #24](https://github.com/OdyseeTeam/odysee-frontend/issues/24) via [**ZenHub**](https://www.zenhub.com/)
