### ISSUE TITLE
Channel is ignored when checking if claim already exists

### ISSUE THREAD

**Issue by AmossGuy** [lbryio/lbry-desktop#5168]
**Bug**
When attempting to create a claim with the same name as a claim on a different channel of yours, it will think the claims conflict even though they are on different channels.

**To Reproduce**
1. Create two channels. I’ll refer to them as “@Channel1” and “@Channel2”.
2. Post anything to @Channel1. (e.g. lbry://@Channel1/test)
3. Attempt to post something under the same name to @Channel2. (e.g. lbry://@Channel2/test)
4. An error will display under the name field saying “You already have a claim at lbry://@Channel2/test. Publishing will update (overwrite) your existing claim.” and the upload button will be disabled, even though lbry://@Channel2/test doesn’t exist.
5. Also, if a claim in the global namespace by that name exists, the text “If you bid more than 818.01 LBRY Credits, when someone navigates to lbry://test, it will load your published content. However, you can get a longer version of this URL for any bid.” will appear under the deposit field.

**Expected behavior**
The channels should be treated as separate namespaces, and lbry://@Channel2/test should be able to be posted without incident.

**Screenshots**
![Screenshot_20201211_115628](https://user-images.githubusercontent.com/24391700/101932064-426e4700-3ba8-11eb-9631-8ed8de2f6e75.png)

**System Configuration**

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Additional context**

**Comment by tzarebczan** [comment]
Thanks for reaching out! This is a current limitation and will be fixed with https://github.com/lbryio/lbry-desktop/issues/3704
