### ISSUE TITLE
URL Redirection to Untrusted Site ('Open Redirect')

### ISSUE THREAD

**Issue by fixit9211** [lbryio/lbry-desktop#5175]
Hi Team
I found some open redirects at the lbry.tv, 
URL :
  https://lbry.tv////bing.com/?www.omise.co/?category=interview&page=1
  https://lbry.tv//evil.com/?www.lbry.tv/
  https://lbry.tv//evil.com/?www.lbry.tv/* 
  https://lbry.tv//bing.com/?www.lbry.tv/

Steps to Reproduce  
Intercept the below url using Burp Suite & send it to repeater https://lbry.tv/
Use this attack pattern  //bing.com/?www.lbry.tv/ or //evil.com/?www.lbry.tv/* 
Now it will redirect to bing.com or evil.com 
**Request**

GET //bing.com/?www.lbry.tv/ HTTP/1.1
Host: lbry.tv
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
Connection: close
Cookie: __cfduid=dfcebb9451351645d50c441b6f88a74c11607278179; _pk_ref.3.42ca=%5B%22%22%2C%22%22%2C1607799009%2C%22https%3A%2F%2Ftemp-mail.org%2Fen%2Fview%2F41f863f2d7079abaa215d8ee9ce3ce97%22%5D; _pk_id.3.42ca=115bf5aca01b5766.1607278196.10.1607799350.1607796523.; auth_token=Gn61nFeCF98bdD2jarRjDFAkVjnjLJDg; _pk_ses.3.42ca=1
Upgrade-Insecure-Requests: 1
If-Modified-Since: Fri, 11 Dec 2020 22:20:01 GMT
Cache-Control: max-age=0

**Supporting Material/References:**
https://hackerone.com/reports/753399
https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html

**Impact:**
An attacker can use this vulnerability to redirect users to other malicious websites, which can be used for phishing and similar attacks
Users could get redirected to malicious domains .  

Screenshot:
![lbrytv_redirest request](https://user-images.githubusercontent.com/75940769/102015165-bb87ae80-3d0e-11eb-967a-3a828667bc7b.png)

I Hope that you will fix this issue as soon as possible. Looking forward to hearing from you. Thank you .  
Kind Regards,
fixitTeam 
fixit9211@gmail.com

**Comment by tzarebczan** [comment]
Thanks for the report, we'll look into this. Users clicking a link already get a warning that an external site is going to be opened.

**Comment by fixit9211** [comment]
Thanks for your feedback , As this is the most critical issue for any web
application , I Hope that you will consider our hard work and hope that you
will fix this issue as soon as possible. Looking forward to hearing from
you. Thank you .

reference report :

   - https://hackerone.com/reports/753399


Regards,
*Samuel Leach*

*(Security Researcher)*

**Comment by seanyesmunt** [comment]
@fixit9211 working on this now

**Comment by fixit9211** [comment]
Hi,

We are glad to see that you have resolved this critical issue you were
facing with our findings. I hope that you will consider our hard work. I am
writing this email to request a fair reward/bounty from your end that will
motivate our team. You know it takes some time and effort to find a bug in
a website. We did it for you to make your website more secure and safe.

Looking forward to your positive response.

Regards,

*Samuel Leach*

**Comment by tzarebczan** [comment]
Thanks so much! Please send an email to security@lbry.com with this link to claim it.

**Comment by fixit9211** [comment]
sure thanks
