### ISSUE TITLE
Static gifs

### ISSUE THREAD

**Issue by m160** [lbryio/lbry-desktop#5176]
**Bug**
I noticed that profile- and banner gifs have recently gone static. Not sure if this is done on purpose, or if it's a bug, but I'd like to know :)

**To Reproduce**
1. Go to `lbry://@MagentickA#1` or https://odysee.com/@MagentickA:1
2. See gifs being static images

**Expected behavior**
Gifs being gifs and not static images

**System Configuration**

- LBRY Daemon version: 0.86.1
- LBRY App version: 0.49.0
- LBRY Installation ID: 9iFvgSpaPfWLbrFQrt6G7Cw5w4tBpiPAocJBFm4yNBBcKeFf8gMGt2eq9vb339if5g
- Operating system: Linux (Linux-5.8.0-7630-generic-x86_64-with-Pop-20.10-groovy)

**Comment by kcseb** [comment]
Seems as though the thumbnails got uploaded as JPG's rather than GIF's. 

![img](https://spee.ch/a/641ade54cea58068.jpg)
`https://spee.ch/a/641ade54cea58068.jpg`

![img](https://spee.ch/c/dc36265b159017ef.jpg)
`https://spee.ch/c/dc36265b159017ef.jpg`

Could you give uploading the images as GIF's another go, please?

**Comment by tzarebczan** [comment]
It's related to some testing we're doing with a CDN. @nikooo777 is aware.

**Comment by ElectronEsq** [comment]
> **Bug**
> I noticed that profile- and banner gifs have recently gone static. Not sure if this is done on purpose, or if it's a bug, but I'd like to know :)

Related: https://github.com/lbryio/lbry.com/issues/1355

Social media will cache the images that are over-compressed/wrong size/converted wrong, so you'll you have to release them from the social media cache, if this is the case for you, as per the linked issue.

**Comment by nikooo777** [comment]
It looks like it's unrelated to the CDN, in fact they are also static when fetched directly from origin.
I will have to replicate this locally. Hopefully it's an easy fix

**Comment by tzarebczan** [comment]
I think we also blocked GIFs from animating, but not sure on what pages. Maybe @seanyesmunt can confirm.

**Comment by ElectronEsq** [comment]
> I think we also blocked GIFs from animating, but not sure on what pages. Maybe @seanyesmunt can confirm.
Only when over a certain size.

**Comment by tzarebczan** [comment]
The static gifs were in the profile/banner. Profile is fixed, and the banner will be soon.

**Comment by tzarebczan** [comment]
We've also turned off the compression on banners so they should look better - may require a cache clear.
