### ISSUE TITLE
Support for Proxy via I2P Network

### ISSUE THREAD

**Issue by kodxana** [lbryio/lbry-desktop#5180]
**Describe the solution you'd like**
Add support for proxy connection on LBRY SDK/ Desktop App/ Wallet Server.
So we can have fully decentralized anonymous P2P network without clearnet required.

https://geti2p.net/pl/get-involved/develop/applications
https://geti2p.net/pl/docs/api/samv3

**Comment by tzarebczan** [comment]
This would be an issue on the SDK side, but right now the focus is existing IP tech.
