### ISSUE TITLE
Upload Error

### ISSUE THREAD

**Issue by LEETUMBRA** [lbryio/lbry-desktop#5186]
It is not only appear on desktop client, also the web as well.

Error message: (1, 'the transaction was rejected by network rules.\n\nMissing inputs\n[0100000001706b75f76131591b4a6fd602d32066eafb5208f8845c0c67073255899a901b9b010000006a473044022073a48cb79492519826f34f2f6cd0f03b504afecd6d783db2c4cd7b00b0d7a2b502201f62592e7f969c4cb4dc1a0272332615931c92555c30712256d90fbad040478a012103b8ef7c29e73c4574ed6ddf9f927dd54813bd113134192425585935ed1c8dce83ffffffff028096980000000000fd3d01b5104c4252595f302e34392e312d72632e314d0d0101d23b22f41515757924c78e44c432af15b3fca529b898768abde3699bb1f54d3c4eec084567607abeb1e9ca68b06d1043d01c8d183edea66baddc7a3978489197f62c02cfee446f0826079da70a1bf58df68f27df0aa9010a9a010a308abf05174900c8f97bc7a91b001d07f9debd8bd6f244531b68a8d3e902107af754be95617666796cc29aa9fbdf6a154812144c4252595f302e34392e312d72632e312e65786518a8e79c940122186170706c69636174696f6e2f6f637465742d73747265616d32300a43595aebe0854ea461a35a370ce96b76203a6fcb4687abe342dfa110fadb2f4d49317603f04202d14ac160573b5e311a044e6f6e6528f1abe3fe054204746573745200620208016d7576a914e54af92bac88cceeb4122a33540b0d2bcec8ff6188acdc0f1d06000000001976a914aac1b6cb71a90f54d88bca92221bb75d076e546c88ac00000000]')

**Comment by tzarebczan** [comment]
Duplicate
