### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by LEETUMBRA** [lbryio/lbry-desktop#5187]
It is not only on desktop client, also odysee.com and lbry.tv as well. I have been using sync service ensuring not easy to lose.

Error message: (1, 'the transaction was rejected by network rules.\n\nMissing inputs\n[0100000001b01941adfe4c21cba70c48046801ad5c57066d8b63771efc56793e0829083ecc010000006b483045022100a09ac2f44d4383a445e2be27f92b464118c12ff8e07db6afefa27b6f00383b4b02204329f940d359fc29008d5984874dbce51f8f1637c83deace538ce4d192ac144e0121036706b54496a655c5fa5f945e1273782a9c986f931f2700af14079b7f3e9307feffffffff0240420f0000000000fdac01b54c6832303036303531325f4f6977784d787a43504e675fe38389e3838ae383abe38389e381aee38186e3828fe38195e38080e383a9e383b3e383a9e383b3e383abe383bce381a3e381a6e381aae38293e381aae38293e381a0e383bcefbc9f5f313630383031393738394d2301000a84020aeb010a30ac9ec35375e7129feeee3301be7ce0db91fd90c5e404869e512f2c4facdd2ebbe471578108bc6caa8999529fa88dec5612763332383934363930375f32303036303531325f4f6977784d787a43504e675fe38389e3838ae383abe38389e381aee38186e3828fe38195e38080e383a9e383b3e383a9e383b3e383abe383bce381a3e381a6e381aae38293e381aae38293e381a0e383bcefbc9f5f313630383031393738392e6d703418c9a3262209766964656f2f6d703432304c09e393b62d0648d8f618f4a6c1cf58097d470d0120abb056df6d4352540debfc4636e4cd3d7e96601954942b653cfa1a044e6f6e652885ade3fe055a0808c00210f001181a42134d63646f6e616c64277320496e73616e6974795200620208016d7576a914ab1d9d307dddf229828b4074b1d5fd43cf4719a688ac28e4f309000000001976a914ab1d9d307dddf229828b4074b1d5fd43cf4719a688ac00000000]')

**Comment by tzarebczan** [comment]
There are wallet server issues at the moment, check back again later.
