### ISSUE TITLE
lbry-desktop client fails to start on macOS 11.1

### ISSUE THREAD

**Issue by lijunzh** [lbryio/lbry-desktop#5188]
**Bug**
Lbry Desktop client fails to start after upgrading to the latest macOS version.

**To Reproduce**
1. Upgrade to macOS 11.1
2. Start lbry client 
3. The attached screenshot shows up

**Expected behavior**
The client should start properly.

**Screenshots**
![Screen Shot 2020-12-15 at 10 16 21 AM](https://user-images.githubusercontent.com/9093413/102241448-95a10c00-3ebe-11eb-9c40-f14d2cc31637.png)

**System Configuration**

- LBRY Daemon version: 
- LBRY App version: 0.49.0
- LBRY Installation ID:
- Operating system: macOS 11.1

**Additional context**

**Comment by tzarebczan** [comment]
Please try again in a few, it should be back up soon. We had some downtime on our wallet servers.
