### ISSUE TITLE
Don't autoplay when commenting/video off screen

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#5204]
https://github.com/lbryio/lbry-desktop/pull/4419 was supposed to fix it but it's still happening.

**Comment by infinite-persistence** [comment]
Seems ok with the current Odysee when I scroll down half of the video height.  Any way to reproduce the scenario?

![image](https://user-images.githubusercontent.com/64950861/102517543-22b8b080-40cb-11eb-9e1b-bbbc1a49cb1c.png)

**Comment by tzarebczan** [comment]
What if you scroll further down when it's out of sight? This is usually what happens on mobile and then users don't realize the page switched.

**Comment by infinite-persistence** [comment]
Yeah, that's covered.  The logic was "as long as the autoplay component is partially off screen".  Maybe the following is failing in some scenarios, but so far it works on my mobile, both portrait and landscape.
```
setTimerPaused(elm.getBoundingClientRect().top < 0);
```

**Comment by tzarebczan** [comment]
Looks like it's pretty quirky..when I scroll up and down, it changes state. But many states don't pause it, like 
![image](https://user-images.githubusercontent.com/8120721/102638774-085ff080-4126-11eb-8da4-37cebf38a00b.png)

**Comment by infinite-persistence** [comment]
Yeah, the timer will restart if `elm` (the big play button) is fully visible again, similar to YT.  YT's threshold is even worse -- it'll restart as long as the button is partially visible.

Maybe we can change `elm` to the title string, or even the entire video region?

**Comment by tzarebczan** [comment]
I think the bug I was running into was where you scroll down while the video is getting towards the end (before the timer comes up, and while it's still playing), and then it's never paused. Was able to repro it twice.

**Comment by kauffj** [comment]
IMO no need to over-engineer this for marginal benefit. If autoplay simply never starts or stops once the user has scrolled, that is delivering 95% of the value.

**Comment by infinite-persistence** [comment]
No worries.  Tom's last comment made me realize I didn't read the initial comment properly :D.  Fix is somewhat a one-liner.
