### ISSUE TITLE
"Mature" content is being censored

### ISSUE THREAD

**Issue by kareldonk** [lbryio/lbry-desktop#5210]
I noticed that content which is somehow labeled as 'mature' does not show up on my channel unless people activate the option to display mature content in their profile settings.
Effectively those videos are being censored because they don't even show up in the channel list of videos. It would be better to still show a thumbnail for those videos with a placeholder image and the video title, and a text that says that it contains mature content. That way, people would still see that the video exists and could click on it to find the link to enable mature content in their profile. 
By hiding the videos completely people never know it exists.
I also don't see why my videos are labeled as 'mature'. Here is an example https://lbry.tv/@kareldonk:8/Understanding-Women-I:e

**Comment by tzarebczan** [comment]
The sex tag is treated as mature content, you can remove it if the content isn't mature. Any of the pink tags will do that. 

We won't be changing how this works as users need to enable mature content before they are able to see it. There's a separate issue filed that should alert them when there is mature content but it's not displayed.

**Comment by kareldonk** [comment]
Thanks for the details. But why is just the tag 'sex' being considered as mature content? Don't people below 18 years also get sex education in school?
