### ISSUE TITLE
Figure out odysee-friendly way to re-enable supports

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#5226]
Conclusion is:

- Tipping and staking are always initiated via a single button labeled "Support". Default is always tip. Tip should not be selectable when the tip would come from same channel as the content was published under.
- Add high-level element, that lets you switch between Tip and Boost (stake). This should probably look like the tab switcher.
- Ensure button text and help text change when the mode switches.

**Comment by kauffj** [comment]
@julianchandra do you have thoughts on this?

**Comment by julianchandra** [comment]
I like the ideas I proposed for the wallet page, that was translatable to the 'support' on a video. We'd bring it back as 'boosting'.

Couple of things needed as part of this:
1. adding a tagline to the wild west
2. putting together a wild west explainer video

**Comment by kauffj** [comment]
- Switch to tabs
- Add element that makes each mode more obviously different

**Comment by kauffj** [comment]
Supporting my own channel on odysee.com had a submit button labeled "Boost This Video"
