### ISSUE TITLE
Video isn't playing with a message "Failed to view lbry://..."

### ISSUE THREAD

**Issue by rohandebsarkar** [lbryio/lbry-desktop#5239]
**Bug**
Whenever a video is played a message is shown with the message "Failed to view lbry://...", but when I click on the download button it starts to play.

**Expected behavior**
The video should be played.

**Screenshots**
![GitHub issue lbry app](https://user-images.githubusercontent.com/50144004/103119889-64cd8d80-469b-11eb-8df6-29afd758d50a.png)

**System Configuration**

{
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "desktop": "Unity",
    "distro": {
      "codename": "groovy",
      "id": "ubuntu",
      "like": "debian",
      "version": "20.10",
      "version_parts": {
        "build_number": "",
        "major": "20",
        "minor": "10"
      }
    },
    "lbrynet_version": "0.86.1",
    "os_release": "5.8.0-33-generic",
    "os_system": "Linux",
    "platform": "Linux-5.8.0-33-generic-x86_64-with-Ubuntu-20.10-groovy",
    "processor": "x86_64",
    "python_version": "3.7.9",
    "version": "0.86.1"
  }
}

- LBRY Daemon version: 0.86.1
- LBRY App version: 0.49.1 
- LBRY Installation ID: 2pxqdh8rQn23xjbdiqRtu47DRhrcvJxgbY7yLLDzdXW53eQCpdJ7bft2Xp1bRajPWW
- Operating system: Ubuntu 20.10

**Additional context**
I would like to mention it again that when I click on the download button, it starts downloading the video and plays it without any issue.

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. Please send your log file (see help page) to hello@lbry.com and we'll take a look. Also include details about location and bandwith.
