### ISSUE TITLE
Can't find other disks/drives on system

### ISSUE THREAD

**Issue by BrentFarris** [lbryio/lbry-desktop#5240]
**Bug**
I have an encrypted disk on my Linux laptop (not primary disk). I have my drive mounted to `/media/my_name/drive_name`. Inside of the LBRY app, in any of the file explore views, it doesn't see even the `/media` folder (which is there even if I don't decrypt/mount my disk).

**To Reproduce**
1. Have a 2nd disk installed onto your computer (make sure it is an encrypted drive so you have to decrypt and mount it)
2. Open the LBRY app
3. Make sure you are logged in
4. Go to Settings
5. Scroll down to "Download Directory"
6. Click on "Browse" button
7. Notice that you can not access your `/media` folder

**Expected behavior**
When I click on the "Browse" button it should show all my mounted disks

**Screenshots**
![image](https://user-images.githubusercontent.com/1002223/103164052-f2a89600-47cb-11eb-9fd6-303187518bd5.png)

**System Configuration**
- Computer:  System76 Lemur Pro (lemp10)
- OS:  Pop!_OS 10.04
- 1TB M.2 SSD (primary)
- 1TM M.2 SSD (secondary the problem drive)

```json
{
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "desktop": "Unity",
    "distro": {
      "codename": "Flatpak runtime",
      "id": "org.freedesktop.platform",
      "like": "",
      "version": "20.08.2",
      "version_parts": {
        "build_number": "2",
        "major": "20",
        "minor": "08"
      }
    },
    "lbrynet_version": "0.86.1",
    "os_release": "5.8.0-7630-generic",
    "os_system": "Linux",
    "platform": "Linux-5.8.0-7630-generic-x86_64-with-glibc2.4",
    "processor": "",
    "python_version": "3.7.9",
    "version": "0.86.1"
  }
}```

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. Looks like this may be specific to the flatpak and how it handles file security. Can you try the appimage to see if it works there? That's our official supported build.

**Comment by tzarebczan** [comment]
Can try opening the issue on https://github.com/flathub/io.lbry.lbry-app or check out https://askubuntu.com/questions/1086529/how-to-give-a-flatpak-app-access-to-a-directory

**Comment by BrentFarris** [comment]
> Can try opening the issue on https://github.com/flathub/io.lbry.lbry-app or check out https://askubuntu.com/questions/1086529/how-to-give-a-flatpak-app-access-to-a-directory

Oh dang, I'm dumb, I didn't pay attention to see it was flatpak. Thank you, was resolved adding specific folder using `Flatseal`  :)

**Comment by tzarebczan** [comment]
Glad to hear that, happy holidays!
