### ISSUE TITLE
repost fixes

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#5244]
- don't redirect to channel page after repost success. This should probably stay on the current page if reposting from a claim. If from top page, maybe go to reposted claim, or stay on top page with pending (did we get rid of pending?)

- should show repost and correct type (i.e. channel, not document) - maybe because it's anonymous? 

![image](https://user-images.githubusercontent.com/8120721/103295889-ee929900-49c2-11eb-8f01-1e6ba719350c.png)

**Comment by kauffj** [comment]
if reposting from a stream, return to the stream

if reposting from /top or /search, return to /top or /search (or always return to /top)

**Comment by Ruk33** [comment]
Hello guys, I can work on this if it's available. Regards.

**Comment by tzarebczan** [comment]
@Ruk33 thanks , but we'll handle this one internally. Maybe there's a smaller issue you can find on the repo?

**Comment by Ruk33** [comment]
Sure @tzarebczan no worries. Thanks!
