### ISSUE TITLE
fix NSFW + top result (see last comment)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#5245]
The top search works and param is passed correctly, but when you click view all results, it passes false when mature content is enabled. 
![image](https://user-images.githubusercontent.com/8120721/103296044-3ca79c80-49c3-11eb-9c12-959134dce834.png)

**Comment by Ruk33** [comment]
Hello @tzarebczan , I can work on this if that's ok.

**Comment by tzarebczan** [comment]
Thank you, please take a shot!

**Comment by Ruk33** [comment]
Sure thing @tzarebczan , thanks.

**Comment by Ruk33** [comment]
Hi @tzarebczan , I believe it's working just fine. If the option isn't check, we can see nsfw=false:

Web

![image](https://user-images.githubusercontent.com/1719111/103646193-08d6f480-4f38-11eb-8504-de00c92ff300.png)

App

![image](https://user-images.githubusercontent.com/1719111/103646257-2441ff80-4f38-11eb-9cdf-387d84e4007f.png)

When nsfw is enabled, the parameter isn't sent at all (and the content being displayed):

Web

![image](https://user-images.githubusercontent.com/1719111/103646588-adf1cd00-4f38-11eb-94ab-796de9d36fe7.png)

App

![image](https://user-images.githubusercontent.com/1719111/103646502-87cc2d00-4f38-11eb-9352-2ec8b19ec513.png)

Can you confirm it's also working for you too please? Thanks.

**Comment by Ruk33** [comment]
Hello @tzarebczan, sorry to bother but where you able to check my last comment? It seems to be working fine.

Thank you.
Regards.

**Comment by tzarebczan** [comment]
I'm pretty sure it's still passing it on the main search incorrectly (after you click view all results / enter), but works fine when searching in the top bar. See my intitial screenshot.

**Comment by Ruk33** [comment]
Ah got it @tzarebczan , yes I was able to reproduce it from View all results. Working on it. Thanks.

**Comment by Ruk33** [comment]
Ok, here is the PR https://github.com/lbryio/lbry-desktop/pull/5277 :)

Regards!

**Comment by tzarebczan** [comment]
Also, there's a bug where the top result is hidden for mature content even though you have mature content enabled.

**Comment by Ruk33** [comment]
Hello @tzarebczan , sorry for the huge delay, I've finally found some time to work on this. Here is the PR: https://github.com/lbryio/lbry-desktop/pull/5388.

One note though, even though now the content isn't being hidden because of nsfw settings, the content still appears as "Content hidden":

![image](https://user-images.githubusercontent.com/1719111/105877761-12a3c300-5fdf-11eb-9eed-02b35bd1b8d1.png)

I've tracked the filters and this is the logic that gets trigger to hide it:

File: `lbry-desktop\ui\component\claimPreview\view.jsx`
```
  // We're checking to see if the stream outpoint
  // or signing channel outpoint is in the filter list
  if (claim && !claimIsMine && !shouldHide && filteredOutpoints) {
    shouldHide = filteredOutpoints.some(
      outpoint =>
        (signingChannel && outpoint.txid === signingChannel.txid && outpoint.nout === signingChannel.nout) ||
        (outpoint.txid === claim.txid && outpoint.nout === claim.nout)
    );
  }
```

So I'm not sure if this is the correct result but just wanted to pointed out.

Regards!

**Comment by tzarebczan** [comment]
That one is normal and expected.
