### ISSUE TITLE
frozen downloads

### ISSUE THREAD

**Issue by Tcll** [lbryio/lbry-desktop#5250]
I have been fighting with this particular video all morning:
![image](https://user-images.githubusercontent.com/773959/103351316-de38f780-4a70-11eb-98ae-120934944248.png)
if LBRY doesn't quit trying to start a download (displaying a red balloon), then the video only downloads part of the way.
if I skip to the end of the video, the download will stay at 6%
I can play the video from here (or just skip ahead) and the download **may** (partially) resume (or just stay at 6%), but I can't watch this video here
I would actually prefer to download all videos I watch and discard them if I don't want them locally

but what good does this do for anyone if the player forces you to watch the video before you can actually watch the video?

and btw, yes, the download is still at 6% through writing, posting, and editing (multiple times) this message.
this isn't anything new btw, the fix is to delete the frozen download and start over (hoping it doesn't freeze again)

**Comment by tzarebczan** [comment]
We're working on some streaming edge cases that affect downloads which should improve this, but ultimately this is a bug that known and improvements need to be made on the SDK side in terms of how it fails and retries. 

Please send us your logfile to hello@lbry.com so we can confirm, and reference this post.

**Comment by Tcll** [comment]
uuuuh the logfile for lbrynet right??
(sadly I closed the app before seeing the reply)

though if it's known and being worked on, do you guys really need it?? :)
(I won't hold it back if so, it's just I have 7 log files to look through to find the occurrence)
I'm kinda thinking to hold out a few more versions and actually wait for improvements before giving any major input like that ;)

glad to hear it's in progress though :+1:

**Comment by Tcll** [comment]
any advancements on this??
still happening in 0.49.4
![Screenshot_2021-02-24_07-15-38](https://user-images.githubusercontent.com/773959/109001069-77038200-7672-11eb-84fa-b463eda1def0.png)

**Comment by Tcll** [comment]
still happening on 0.50.1
can this issue be re-opened please
![Screenshot_2021-03-23_10-55-35](https://user-images.githubusercontent.com/773959/112168974-2aa35780-8bc8-11eb-9909-8eb729457406.png)
how is it even possible I can watch a video on LBRY that's 0% downloaded :srs:
had to skip to the end for my view to count because I can't watch on LBRY, but if I have the content, why don't I have the download??
it really doesn't make sense why the byte stream isn't copied to the file if I can watch it...
