### ISSUE TITLE
A windows for monitoring sharing data

### ISSUE THREAD

**Issue by grubeli** [lbryio/lbry-desktop#5256]
**Is your feature request related to a problem? Please describe.**
I'm not able to see what files I'm and hosting

**Describe the solution you'd like**
I think it would be good if we have a way to see files we sharing or hosting, statistics on it, etc

**Comment by tzarebczan** [comment]
All the files in the Library tab are hosted. There's no monitoring at the moment and there's another feature request already open for this. 

Happy holidays!
