### ISSUE TITLE
cannot scrub through content on IOS + Audio

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#5263]
See https://open.lbry.com/@ChristRescues:a/Biosecurity-Pharma-challenges-overcome:8 on ios, there's no scrub bar when you click the video

**Comment by DispatchCommit** [comment]
this is caused by / duplicated by https://github.com/lbryio/lbry-desktop/issues/5323

#5344 should therefore resolve this

**Comment by DispatchCommit** [comment]
@seanyesmunt can you verify if this issue is resolved?
