### ISSUE TITLE
Watch Later Feature

### ISSUE THREAD

**Issue by DaniNz** [lbryio/lbry-desktop#5272]
**Is your feature request related to a problem? Please describe.**
Yes, I'd like to save videos to watch later.

**Describe the solution you'd like**
* Add an action button to save the video
Maybe in here: 
![image](https://user-images.githubusercontent.com/16692007/103939884-4344bb00-510b-11eb-9012-efa7baf3fa68.png)
 * And add a section where I can see all the videos that I saved with the proposed button.

**Describe alternatives you've considered**
I use the bookmark button from the browser.

**Additional context**

**Comment by tzarebczan** [comment]
This is filed under https://github.com/lbryio/lbry-desktop/issues/622
