### ISSUE TITLE
UI customization (a mode that can let user edit what parts of ui they wanna see)

### ISSUE THREAD

**Issue by Xyncgas** [lbryio/lbry-desktop#5278]
**Is your feature request related to a problem? Please describe.**
A feature

**Describe the solution you'd like**
Implement a scenario allowing users to edit the ui freely, by means of removing or re-enabling, when this mode is triggered all the selectable section would have a 'x' button floating on the corner.

**Describe alternatives you've considered**
User scripts, ditching the desktop app to use adblock instead, intergarting it in the application myself.

**Additional context**
I wanna do it myself, please point me to where I can see the components of the setting page and ui elements, I am familiar with computing languages and MVC although I am not sure how to run this app through command line to test the things I've built.

**Comment by tzarebczan** [comment]
Thanks for the feature suggestion, we won't be doing this anytime soon, unfortunately. We do plan to give users more control over the sidebar though. 

If you wanna take a shot yourself, can you start here: lbry.tech/contribute and check the readme on how to run the app in dev mode.
