### ISSUE TITLE
ability to view comments that have been "slimed to death"

### ISSUE THREAD

**Issue by Tcll** [lbryio/lbry-desktop#5279]
sometimes when you're viewing a comment thread, it helps to know the full story of what's going on.
the fact that comments are hidden at all makes the platform no better than YouTube IMO, even if the deletions are entirely user-controlled.

sure community moderation is absolutely thousands of times better than centralized moderation...
but you're not solving the problem of censorship, only shifting the governance of it to the people, which is just as unreliable due to propaganda and bias.

I personally keep seeing discussions with comments that have 15 downvotes or so, and am interested to know what was so disliked.
![Screenshot_2021-01-09_11-27-03](https://user-images.githubusercontent.com/773959/104102981-a8b0bd00-526d-11eb-843b-be8edb110ab0.png)

**I'd like to be able to expand the hidden comment to see what it's about
maybe even upvote it out of death if it turns out to just be an unpopular opinion that's actually correct**

**Comment by AmossGuy** [comment]
You can already do that by clicking on the text. Might still be a good idea to add a button to make it more clear that you can reveal it.

**Comment by Tcll** [comment]
oh heck, alright, you got me XD
last time I tried that, it didn't work, so it must've been added recently??

a button would be nice, though you could've just made the text highlight onmouseover :)
nice job regardless ;D

**Comment by Xyncgas** [comment]
how dare you

**Comment by Mistofs** [comment]
how dare you

**Comment by Mistofs** [comment]
comparing it to youtube just to prove a point how scandelless must you be to ignore the beauty

**Comment by Tcll** [comment]
not to feed the trolls, just to educate ;)

> how scandelless must you be to ignore the beauty

I see the beauty, that's why I use/support it ;)
I'm giving input to help the platform avoid becoming like the giant turd that is YT
it's called foresight, you should learn to use it if you ever hope to be an experienced developer :)

if it weren't possible to expand hidden comments, that would be a form of censorship that would tarnish the beauty of the platform and make it more like YT.

**Comment by mrhappypenguin** [comment]
I don't like this feature, even if you can click to show. It gives people the ability to silence others. LBRY is suppose to be uncensored.

**Comment by Tcll** [comment]
@mrhappypenguin somewhat agreed
though without a form of moderation, how will people know if their views are generally considered wrong?

I'm against deletion and banning (unless it's the gray area of being absolutely forbidden, like follow for follow) as that's what actually silences people.
but simply hiding comments and allowing them to be viewed and upvoted out of being hidden should at the very least allow people to apologize for their mistaken ideas.

now yes you have the other side too who would send a group of alt-bots just to get a comment hidden
to combat this, we should be able to see who upvoted or downvoted.
(it's not like the functionality isn't there when it tracks that you've already upvoted, all that's needed is the meta, like this place has)

the only place I step in is if people can use this meta against other users (such as tracking every comment they've voted on), as that shouldn't be possible.

**Comment by mayeaux** [comment]
Fwiw I like the slime feature. You could argue that it could be abused but I've only ever seen it work properly. Sometimes you want to see the rude/idiotic comment that everyone is sliming to death but sometimes you just want to read the comment section in peace lol

**Comment by Tcll** [comment]
it's a shame this issue is closed and you still can't tell if it's possible to click on slimed comments

I'd suggested making it a visible button so it's intuitive, but it seems that's not favored...

**Comment by Tcll** [comment]
can't wait to see the update in LBRY Desktop :)
hopefully now things have been made more intuitive and we won't have to constantly tell people they can click the downvoted comment to view it :D

**Comment by Tcll** [comment]
to be fair comments that are slimed are still viewable

the devs just don't want people knowing they can view the comment, or it would look like a button instead of a disabled text

**Comment by TinyJay42** [comment]
Removing speech if it gets to many downvotes... Genius! Where did you get your inspiration: Hitler, Stalin, or JewTube?
