### ISSUE TITLE
Poor UX around credit binding on publish, esp. for new users

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#528]
New users who know nothing about LBC are going to be confused about how to use their credits to both claim a channel and make a publish.

See this Twitter thread as an example: https://twitter.com/JoshStrobl/status/904615412712734720

**Comment by tzarebczan** [comment]
Related to https://github.com/lbryio/lbry-app/issues/373

**Comment by JoshStrobl** [comment]
Copying what I said in my DM (thanks @kauffj for reaching out), just my personal opinion / recommendations, excluding what is or isn't technically feasible at this moment in time:

> Yea so I had created a channel using the 5 LBC you can see in that screenshot. I thought it'd act more like an account, since I didn't really understand any other reason you'd put LBC into it. So I did that, then put 1 in (it doesn't make it clear if there is a minimum either). Went to publish, got that. Restarted my client and it no longer had the account name under the Publish section, so I opted to put 1 LBC in for account creation, 1 in for publishing the initial video, and it worked.
>
> My recommendation would be to separate out channel creation and publishing. Once you're validated (_or when / if a validation process stops occurring, during the first time to launch LBRY or click Publish_), you'd be prompted (_like with a modal dialog / fancy overlay_) to create an account before you can even start the upload process.
>
> Furthermore, explain the claims system a bit in the channel and URL setting (during video publication), like why you need to essentially pay LBC (I know you can get it back, although I didn't see anywhere in the UI to do that, nor what happens if you do request to get it back) for the URL.

**Comment by MSFTserver** [comment]
would this work? 
https://github.com/lbryio/lbry-app/pull/527

**Comment by JoshStrobl** [comment]
@MSFTserver I think that explains in a clearer manner in the current UX what the deposit is for, yes, however doesn't resolve the UX issues itself _obviously_.

**Comment by MSFTserver** [comment]
yea i wasnt gonna touch the whole UX yet as that is another issue #373 Thomas posted earlier

**Comment by btzr-io** [comment]
> My recommendation would be to separate out channel creation and publishing.

 Also separate editing claims ^^ :stuck_out_tongue:

**Comment by jsigwart** [comment]
Another small UX related thing would be to change the default deposit from 10 LBC to 1 LBC to be more user friendly.

**Comment by seanyesmunt** [comment]
@JoshStrobl I think we have improved on this experience a little bit but could still certainly improve more. Could you try this again and let us know your thoughts?

**Comment by alyssaoc** [comment]
quick publish epic
