### ISSUE TITLE
Feature request: Automatic preloading from selected channels to reduce buffer time

### ISSUE THREAD

**Issue by mateuszmp** [lbryio/lbry-desktop#5297]
**Is your feature request related to a problem? Please describe.**
Often when wanting to see something on LBRY it takes quite a while to download. The problem is exacerbated by the fact a user must manually request a file be downloaded for them to access it. From speaking to friends whom I have migrated to LBRY this seems to be their major issue.

**Describe the solution you'd like**
I'm requesting an option to automatically download (preload) from selected channels, thus as soon as the app notices a new file it would begin downloading it. This requested feature thus reduces buffer time.

I suggest the app preloads files from any, and all, channels the user follows. 

Perhaps with a setting to disable this behavior globally at first, then in the future, on a per channel basis. 

Additionally it would make sense to automatically delete the files if the user hasn't watched them (after 24h for example) since people tend not to watch everything from all of the channels they follow and might disable this feature if they see it clogging up their disk space.

Furthermore it might be worth considering to only preload a portion (beginning) of a file. This could be especially useful if a user has limited disk space and follows many channels each publishing files of many GB daily. One downside to this feature however is that, speaking from experience, a viewer will be more annoyed by a video stopping halfway through rather than having to a wait a few extra minutes before beginning to watch it.

**Describe alternatives you've considered**

**Additional context**
Eventually this could grow to a sort of "autopilot" which automagically picks files to preload based on the recommendations the app already makes for similar files.

**Comment by tzarebczan** [comment]
Sorry for the trouble with downloads, we're working on improving this for less popular content. This would need to be handled by the SDK that the app runs, and we have an issue filed there for it. We don't have an ETA on when this would be available.
