### ISSUE TITLE
LBC Repost Transactions show wrongly.

### ISSUE THREAD

**Issue by VincentYeh-dev** [lbryio/lbry-desktop#5299]
**Bug**
After reposted a video and gave some LBC for support,I saw something that is kind of weird,I not sure If it is a bug or not.

As far as I know,repost is a function that reupload the video and donate some tip to creator.
We "send" some LCB to creator.

The thing I saw on the wallet page is that LCB transaction show that 1 LBC I **earn** by reposting.
Actually,my wallet balance decrease after I repost video.

**To Reproduce**
1.Watch a video on LBRY.
2. Click Repost button.
3. 1 LBC for donating.
4. Click LBC wallet on right-top.
5. Transactions.

**Expected behavior**
LBC amount should be -1.

**Screenshots**
![bug](https://user-images.githubusercontent.com/70697719/104470444-ae532d80-55f4-11eb-9ae5-91c4b3e1d242.png)

**System Configuration**

![bug3](https://user-images.githubusercontent.com/70697719/104471617-09d1eb00-55f6-11eb-98cb-3b05d2641375.PNG)

**Additional context**
None.

**Comment by VincentYeh-dev** [comment]
change title

**Comment by tzarebczan** [comment]
When you repost, you deposit LBC so the content is available on the reposted URL on your channel (or anonymous). It's similar to making a publish where you deposit LBC. 

You can remove the repost via the trash can icon to get the deposit back, but the repost will no longer work/show on your channel.

**Comment by VincentYeh-dev** [comment]
> When you repost, you deposit LBC so the content is available on the reposted URL on your channel (or anonymous). It's similar to making a publish where you deposit LBC.
> 
> You can remove the repost via the trash can icon to get the deposit back, but the repost will no longer work/show on your channel.

OK, thank your clearly description.
