### ISSUE TITLE
Switch away from Google ReCaptcha

### ISSUE THREAD

**Issue by danuker** [lbryio/lbry-desktop#5303]
**Is your feature request related to a problem? Please describe.**
I believe the captcha used for registering a new account is a point at which Google can prevent one of its main  YouTube competitors (LBRY) from acquiring users. I was given quite a few images to classify before I could register. This could turn impossible.

In addition, by exposing even non-Youtube-Creators to Google, you might not be respecting GDPR, by using ReCaptcha. The [TOS](https://lbry.com/termsofservice) only mentions Google under "YouTube Creator Program Terms".

Even the [UK Government](https://www.gov.uk/service-manual/technology/using-captchas) advises against using them for privacy, security, and performance reasons.

**Describe the solution you'd like**
Replace Google ReCaptcha with a self-hosted captcha such as [dchest's](https://github.com/dchest/captcha) (but I have not personally tried it; I am not a Go programmer).

**Describe alternatives you've considered**

Other CAPTCHAs:

- graphical IQ test questions
- type what was heard in some audio

Alternatives to CAPTCHAs (from the UK Gov site):

- rate and connection limiting
- using honey pots (not sure how?)
- transaction monitoring

**Additional context**
Another thing to consider is accessibility. If a disabled person can still watch (or listen to) videos, they should ideally be able to solve the captcha. That is [not the case](https://news.ycombinator.com/item?id=18331862) with ReCaptcha.

**Comment by tzarebczan** [comment]
Thank you for the issue, we have this filed internally as the work doesn't pertain to this particular repo. It's on our radar and we hope to do it in a few months.
