### ISSUE TITLE
armhf build requested

### ISSUE THREAD

**Issue by phoenixbyrd** [lbryio/lbry-desktop#5320]
I've tried building on the 32bit raspberry pi, but it fails. Can you please build an armhf package or provide guidance on how to build on the raspberry pi 4 32bit?

pi@raspberrypi:~/git/lbry-desktop $ yarn compile:electron
yarn run v1.22.5
$ node --max_old_space_size=4096 ./node_modules/webpack/bin/webpack.js --config webpack.electron.config.js
/usr/bin/node[2227]: ../src/node_platform.cc:416:std::shared_ptr<node::PerIsolatePlatformData> node::NodePlatform::ForIsolate(v8::Isolate*): Assertion `data' failed.
Aborted
error Command failed with exit code 134.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by tzarebczan** [comment]
The SDK does not support 32 bit, so it all has to be done separately. We won't be supporting this at this time.  Check out https://discord.io/lbryextra for additional support.

**Comment by phoenixbyrd** [comment]
I manage to get it built for 32bit Raspberry Pi OS. Had to learn some new things but once I figured it out it was pretty easy. Shame to hear you won't be supporting it though. Runs OK and been enjoying it the past few days. :)
