### ISSUE TITLE
Comments section redirects to create channel

### ISSUE THREAD

**Issue by michaelmitnick** [lbryio/lbry-desktop#5321]
When the Odysee web application uploads a post from server resources and clicks the comment section, the channel creation section opens. This happens when you are still loading libraries and resources. I took a screenshot to represent the error. This error has not appeared on lbry.tv at the moment, only on Odysee. I can provide more details if necessary.

![image](https://user-images.githubusercontent.com/33647673/104815666-45cea100-57ec-11eb-8ca3-7a530d172249.png)

**Comment by tzarebczan** [comment]
Good catch, i've seen this before. It happens because the channel list call doesn't return before you create a comment, so it think you don't have a channel .We should block that while the call is active.
