### ISSUE TITLE
Custom themes for Desktop App

### ISSUE THREAD

**Issue by kodxana** [lbryio/lbry-desktop#5322]
**Describe the solution you'd like**
Integrated theme editor inside LBRY Desktop app that will allow users to create own themes to be used.
Could be for example added simple CSS editor with preview of changes.

Cause some people prefer Odysee over lbry.tv and not using core Desktop App cause they do not like it look.
If we focus on web based frontends we can end up on centralized network.

**Comment by tzarebczan** [comment]
Filed under https://github.com/lbryio/lbry-desktop/issues/956
