### ISSUE TITLE
Live streaming integration / development

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#5324]
Requirements:
- Enabled only for users with specified internal tag
- Present stream key on channel page
- Stream keys should reusable/replaceable/revocable 
- Only OBS interaction for live streaming ( most users...start streaming )
  - pre staged default claim templates ( title,description, category, thumbnail etc maybe date injection ? )
- update claim after livestream with new source
- live comment chat ( sort of have that now )

Nice To Haves:
- super chats ( donation alerts )
- chat overlays on stream
- timed chats on replay
- emoticon expansion!!!!
- notification of live stream launch!

**Comment by andybeletsky** [comment]
[Create an endpoint for retrieving livestream file and updating the claim](https://github.com/lbryio/lbrytv/issues/304)

**Comment by tiger5226** [comment]
Requirements:
- Present stream key on channel page
- Stream keys should reusable/replaceable/revocable 
- Only OBS interaction for live streaming ( most users...start streaming )
  - pre staged default claim templates ( title,description, category, thumbnail etc maybe date injection ? )
- update claim after livestream with new source
- live comment chat ( sort of have that now )

Nice To Haves:
- super chats ( donation alerts )
- chat overlays on stream
- timed chats on replay
- emoticon expansion!!!!
- notification of live stream launch!

**Comment by seanyesmunt** [comment]
Will update this as I think of more information

Build a new tab on the publish page "go live"
- includes all of the current publish info, but no file selector
- This will be a new type of publish with no file/sd hash

On publish
- Send claim_id (plus any other information needed) to internal-apis so a stream_key can be generated for that user/channel
- On channel page (or somewhere), fetch internal apis to retrieve that stream_key so it can be displayed in the app

On file page
- Detect if this is a "livestream publish" with no sd hash. If it is, display the livestream UI and fetch internal-apis/bitwave to see if the channel is streaming

On channel page
- claim_search to find any claims that don't have an sd hash, if it finds one, fetch internal-apis/bitwave to see if that channel is live. If they are, show a UI that links to the livestream page

**Comment by tiger5226** [comment]
DSFGDF8779887DFG87-HASH
CHANNELID 

ClaimID will be the only live stream claim id under the channel. Only one at a time so we will always know which claim id the call back api is for, for a channel.

live.stream/DSFGDF8779887DFG87?hash=98dfg787dfg&service=odysee.com&sig=df87sdfg897s987d6fg987sdf6g987s6df98g76sd9fg69s

**Comment by nikooo777** [comment]
I will remain available to support Beamer and Xander with the needed API changes

**Comment by seanyesmunt** [comment]
Something else

Bring livestream functionality into our current player, instead of using a bitwave embed. This would require the odysee apis to return the direct livestream url when calling `get`

**Comment by DispatchCommit** [comment]
currently waiting for: https://github.com/lbryio/lbry-sdk/issues/3180
