### ISSUE TITLE
Make lbry.tv pass LibreJS free js checks

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#5327]
A user mentioned that our javascript does pass the test on LibreJS checks.

**Comment by JYamihud** [comment]
For curious. 
 - Reasons to use LibreJS [here.](https://www.gnu.org/philosophy/javascript-trap.html)
 - Info about what is LibreJS [here.](https://www.gnu.org/software/librejs/)
 - Documentation [here.](https://www.gnu.org/software/librejs/manual/librejs.html)
