### ISSUE TITLE
videos play in background after floating player closed

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#5328]
Have had this happen a couple times, usually when I close the player quickly after it starts playing. The video will continue to play in the backround. If I go back to the video, it's a black window with no video.

**Comment by DispatchCommit** [comment]
finally managed to get this one to reproduce.

```
instrument.ts:129 VIDEOJS: WARN: The element supplied is not included in the DOM
```

Checking for the global `window.player` variable reveals the player instance still exists and was not disposed. Attempting to dispose the player at this point fails too, so it seems the DOM is removed before video.js is able to call dispose.

**Comment by DispatchCommit** [comment]
https://github.com/lbryio/lbry-desktop/blob/8552515e34f08d6af67ba6dd39d0e587b0497397/ui/component/fileRenderInline/view.jsx#L39

> code can currently double fire with videoViewer logic if a video is rendered by FileRenderInline
> (currently this never happens)

https://github.com/lbryio/lbry-desktop/commit/793f622d8d7ae0c333d4e20c0437b22e62014509 - "semi broken"

Should investigate the code around here.
