### ISSUE TITLE
Play All Button on Channels

### ISSUE THREAD

**Issue by MeneerGroot** [lbryio/lbry-desktop#5337]
**Describe the solution you'd like**
Play all button on channels. This is especially handy for channels with music. With the random autoplay picking random videos it's not easy listening. Mostly jump scares coming from chill music to some Russian shouting about Minecraft ro something.

**Comment by tzarebczan** [comment]
This will eventually be considered after we implement playlist functionality: https://github.com/lbryio/lbry-desktop/issues/1982
