### ISSUE TITLE
pop-up for reposting

### ISSUE THREAD

**Issue by Tcll** [lbryio/lbry-desktop#5346]
reposting is currently broken as now it's a full page that unloads everything previous that then redirects you to the creator's channel.

I understand this is likely to make it work for reposting from search results, but a popup that doesn't redirect would be much more usable.

it's really annoying when you repost in the middle of a video and it redirects you to the channel, causing the video to stutter when loading the thumbnails.

please restore the functionality of 0.49.1 while also showing the popup for search results.
I'm not sure what fueled the downgrade to a full-page redirect, but it's quite a nuisance :/
I'm going back to the 0.49.1 appimage until this is fixed.

**Comment by tzarebczan** [comment]
The redirect back to channel page has been fixed and now stays on the content page. We don't plan to bring back the pop out as they are anti patterns. The best bet would be to leave the pop out player on.

**Comment by Tcll** [comment]
I don't like the pop-out player myself and prefer to view the biggest screen possible without going fullscreen...
off topic: is theater mode coming soon as well??

if it's an anti-pattern for web display why not make it pop out into a new window like a Qt notification would do??
... or maybe I just don't understand what an anti-pattern is...

**Comment by kauffj** [comment]
maybe we could force the pop-out player even if disabled for flows initiated while a video is playing?

I can definitely understand the frustration here

**Comment by Tcll** [comment]
I'm not frustrated I can't view the video
I'm frustrated at the downgraded experience from having to load more resource when switching pages

**Comment by seanyesmunt** [comment]
@Tcll Theater mode has already been added to the video player

**Comment by Tcll** [comment]
oh nice, I hadn't noticed because I mainly watch videos with the appimage, and 0.49.1 doesn't have it
sorry bout that :)

**Comment by seanyesmunt** [comment]
@Tcll I gotcha. Expect a desktop release in the next week!
