### ISSUE TITLE
Related tab header font size bigger

### ISSUE THREAD

**Issue by ProjektRoot** [lbryio/lbry-desktop#5347]
Hi folks!
Will be possible to change *Related* font size to match size of video title? Maybe I have bad taste, but UI looks better when headers have the same size :)

If there is any purpose for the font to be smaller, feel free to delete the request. Awesome job, kudos to you guys :)

![image_1](https://i.imgur.com/qjME4RF.png)
![image_2](https://i.imgur.com/rqeMWB5.png)

**Comment by seanyesmunt** [comment]
Thanks for the sugggestion. I don't think we will make it the same size as the file title, but we have some plans to rework that area slightly once we finish building out playlists
