### ISSUE TITLE
Clear values in the upload form after submission

### ISSUE THREAD

**Issue by DispatchCommit** [lbryio/lbry-desktop#5366]
After uploading something to LBRY, the form does not get cleared when going to upload another file.

Fields such as title, description, thumbnail,  name, and deposit amount should be cleared between uploads.

I can see value in allowing users to set default values for new uploads (similar to youtube), but it's odd to return to the upload page and have it still show the same data from the last time I uploaded something.

**Comment by DispatchCommit** [comment]
Also if you go to edit a claim, choose back, and then click upload, you will return to the "editing claim" page. 

You must click `cancel` to actually clear the form.

It makes sense to save edits in case someone accidentally closes the tab / navigates away and wishes to return, but clicking submit should also clear the form. 

The edit form and upload form arguably shouldn't share cache data also IMO, even if they do internally reuse the same components.

**Comment by DispatchCommit** [comment]
Attempting to edit a claim after recently uploading content can also cause unexpected behavior such as this:

![image](https://user-images.githubusercontent.com/45262335/105577270-4788ef00-5d2d-11eb-9826-95b14679c956.png)


Where I am attempting to edit one claim (titled `XSS Test`) after having just uploaded a claim (titled: `Markdown XSS Tests`)

Closing the dialog in this case will then clear the form, and act like the normal upload page.

**Comment by tzarebczan** [comment]
Originally filed under https://github.com/lbryio/lbry-desktop/issues/5139 , but we can keep this issue. The last comment sounds like a different issue with not updating the title from the edit.

**Comment by Ruk33** [comment]
Hello guys, I can't reproduce the issue after submitting a claim.

When submitting, closing the modal clears the form correctly. I have tried:
- clicking on X
- clicking on close
- clicking on view uploads
- even clicking outside of the modal

I was able to reproduce the edit issue however. When the user edits, then tries to upload a claim you can see the previous state. Will be working on that.

**Comment by Ruk33** [comment]
Ok, pushed a PR https://github.com/lbryio/lbry-desktop/pull/5578. Please let me know if this is ok guys. Thanks!
Regards.

**Comment by tzarebczan** [comment]
Jessop also took care of this recently, shouldn't happen anymore!
