### ISSUE TITLE
Editing a comment that has an embed in the playing state, doesn't hide the player

### ISSUE THREAD

**Issue by DispatchCommit** [lbryio/lbry-desktop#5384]
Post a comment with a link to a video so it embeds the video in the comment.
Click play so the video begins playing inline within the comment.
Click edit on the comment.

The player will still be visible and most likely be covering the text field and post / cancel buttons.

![image](https://user-images.githubusercontent.com/45262335/105796697-41209000-5f44-11eb-8896-61bac6a45ac0.png)

**Comment by DaniNz** [comment]
Hello, I'm working on this issue.

**Comment by DaniNz** [comment]
Here is the PR: https://github.com/lbryio/lbry-desktop/pull/5389
