### ISSUE TITLE
Portrait mode support for streaming videos in app

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#539]
## The Issue
A user on Reddit noticed that his video, which was recorded in portrait mode, plays in landscape mode (rotated) via the app. The post is here: https://www.reddit.com/r/lbry/comments/6ykhxs/trying_to_upload_a_video_but_its_taking_forever/

Video is here: lbry://@pancake#c515f03fed88e677f28423ed175c8bbc046c8995/cauliflower

When opening the video from the downloads folder, it plays in portrait mode in my external player. 
### Steps to reproduce
1. Play lbry://@pancake#c515f03fed88e677f28423ed175c8bbc046c8995/cauliflower via LBRY app
2. Video plays in landscape mode, rotated
3. Play video in external player, plays correctly in portrait mode

### Expected behaviour
Play in portrait mode via the app

### Actual behaviour
Plays in landscape mode

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
@tzarebczan does this video play in the proper orientation when downloaded?

**Comment by tzarebczan** [comment]
Yep, that's mentioned in the issue.

**Comment by btzr-io** [comment]
![test](https://user-images.githubusercontent.com/14793624/30413360-c16eaeb0-98da-11e7-8bb1-07cd872d7d5d.jpeg)

**Comment by btzr-io** [comment]
<img width=650 src="https://addpipe.com/blog/wp-content/uploads/2015/06/Screen-Shot-2015-06-10-at-16.48.07-1024x482.png" />

**Comment by kauffj** [comment]
https://github.com/feross/render-media/issues/30

**Comment by seanyesmunt** [comment]
Fixed in new player
