### ISSUE TITLE
Autoplay & Video Viewer Lifecycle Issues to Hotfix

### ISSUE THREAD

**Issue by DispatchCommit** [lbryio/lbry-desktop#5391]
Creating this issue just to consolidate and track issues related to the video viewer's lifecycle and autoplay changes.

**Comment by DispatchCommit** [comment]
for pages that embed multiple videos, it plays them all. I think we had autoplay blocked for embeds, unless specially passed. 

https://journal.rajeshtaylor.com/p/0e5d263a-f915-48e4-859d-8ce4f3589c0a/

**Comment by DispatchCommit** [comment]
the videojs refactoring seems to have broken the 'Retry' and 'Tap to unmute' button.  Haven't looked into details yet.

Ok, I now see both cases (working and not working).
Steps:
1. Select a video. Click play (I had 'autoplay' off).
2. Mute the video.
3. Press Back to invoke Floating Player.
4. Close floating player.
5. Select another video. Click play.
6. Tap 'Tap to unmute'. Control bar stays muted.

Selecting another video from 'Related' makes it work for me, although sometimes the next video becomes muted again.  Can't reproduce this yet.

As for 'Retry', nothing is happening when I tap the button.

**Comment by seanyesmunt** [comment]
It looks like there is an issue with the quality selector not showing after the videojs refactor. Here is a video where it should be displayed.
https://odysee.com/@jackspirko:a/stop-listening-to-the-f-king-bs-tether:0
