### ISSUE TITLE
"uploads" view has issues; different ones in app and lbry.tv

### ISSUE THREAD

**Issue by er013** [lbryio/lbry-desktop#5394]
https://lbry.tv/$/uploads shows all reposts of mine as "Anonymous reposted" although, I reposted them very clearly as myself. They do exist in my channel also, no problem there. Just uploads view shows them wrong. 

https://lbry.tv/$/uploads also shows no length/type information on thumbnails for such reposts.

Desktop app 0.49.3 shows "uploads" differently - said reposts do have length and type information visible. But there is no mention of them being reposts...

**Comment by tzarebczan** [comment]
Thanks for filing. We haven't changed anything here for a while and have this issue opened to improve that experience. Today's patch may also worsen the view on desktop as we made some repost adjustments in other places. Will Make sure to add that to the issue. 
https://github.com/lbryio/lbry-desktop/issues/4563
