### ISSUE TITLE
"lbrynet: cannot execute binary file" on Debian 10 x86-64

### ISSUE THREAD

**Issue by oitdmser** [lbryio/lbry-desktop#5437]
**Bug**
lbry and lbrynet binaries not executable on Debian

**To Reproduce**
I installed LBRY_0.49.3.deb on my x86-64 Debian 10 box using `dpkg -i`, then ran `sudo apt-get install -f`. If I type `lbry start` on the command line it returns a `Segmentation fault`. If I go directly to /opt/LBRY/ and execute it with `. lbry start` it says `LBRY/lbry: cannot execute binary file`. 

Same thing happens if I try to execute the daemon in `resources/static/daemon`

just tried downloading lbrynet 0.48.zip, but same error "cannot execute binary file"

**System Configuration**

- LBRY App version: 0.48.2, 0.49.3, 0.49.4
- LBRY Installation ID:
- Operating system:
- Operating System: Debian GNU/Linux 10 (buster)
            Kernel: Linux 4.19.0-10-amd64
      Architecture: x86-64

**Additional context**

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. Can you try the app image from lbry.com/get also? Never heard about this before....sounds like something that could happen on a 32 bit system, but you mentioned yours is 64bit?

**Comment by oitdmser** [comment]
My goal is just to run the daemon to assist the network, so I'm doing all this from the command line, and as such I don't think the AppImage will work, although correct me if I'm wrong. I even tried downloading the lbrynet executable in a zip from the lbry-sdk GitHub and had the same error.

**Comment by oitdmser** [comment]
I presume the .deb installed the symlink `/usr/bin/lbry` to `/opt/LBRY/lbry`. If I run the XFCE GUI on the Debian box and run `lbry` via a console the GUI launches. If I go to `/opt/LBRY` and attempt to execute the lbry binary directly using `. lbry` I get the above mentioned error. If I try to run the daemon directly from the console in XFCE I also get the same error.

Is there no way to run LBRY as a daemon without a GUI? Most linux apps allow some sort of console-only option or at least give sane errors when run on the console, so this behavior was confusing

**Comment by oitdmser** [comment]
Whoops, it was a user error on my side. I was running it using `. lbry` and `. lbrynet and should instead have been using `./lbry` or `./lbrynet`

**Comment by tzarebczan** [comment]
Wow, I totally missed that too! Glad you got it figured out :)
