### ISSUE TITLE
Keep floating player in view area

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#5438]
- can't see x 
- not clear that it can be moved
![image](https://user-images.githubusercontent.com/8120721/106302792-66a0e880-6227-11eb-8c67-8a6c61816adb.png)

**Comment by DispatchCommit** [comment]
https://github.com/lbryio/lbry-desktop/blob/77d90b807ea359d2fbff4f6a1ffd0fdd53ec71ec/ui/component/fileRenderFloating/view.jsx#L118
