### ISSUE TITLE
Missing audio on web version (lbry/odysee) only 

### ISSUE THREAD

**Issue by foopub** [lbryio/lbry-desktop#5444]
Speech is missing, only background music can be heard:

https://odysee.com/@veritasium:f/why-are-there-huge-colorful-pools-in-the:b

https://lbry.tv/@veritasium:f/why-are-there-huge-colorful-pools-in-the:b

I don't know of any other videos affected by this. The comments suggest the desktop client has normal audio, tho I'm unable to test this personally.

**Comment by DispatchCommit** [comment]
Web and desktop use the same video player, so all I can think of is either browser differences, or audio encoding (which this video looks to have 5.1 audio support)

**Comment by tzarebczan** [comment]
That is the case indeed...wonder if there's any HTML5 hack for this, or we need to transcode. 
![image](https://user-images.githubusercontent.com/8120721/106501975-c7335e00-6491-11eb-88cf-042e478e72c7.png)

**Comment by kauffj** [comment]
We think this is an issue with videojs and are closing.
