### ISSUE TITLE
Hi "Tips" features is not updating correctly the wallet on my channel

### ISSUE THREAD

**Issue by eterniimmortali** [lbryio/lbry-desktop#5445]
Hi guys, I report an issue my selection on "tips" are no updating correctly on my wallet anymore! See issue On the page 
https://lbry.tv/$/wallet
.. if I click on any "Tip" Under list "Transactions"
The import on wallet is much less that the amount of the TIP I selected 

I'm using a regular browser google chrome for android... It was working good.....
Please help me to fix it  
Best regards Eterni

**Comment by tzarebczan** [comment]
The total balance has been changed to reflect both available and locked LBC. You won't see it change when you unlock tips, it will just move to available.

**Comment by eterniimmortali** [comment]
Thanks Thomas for your support.. I don't
see any changes when I unlock tips on "advailable" and locked lbc.. I Just see a small amount changing... Example 0,0003lbc after a tip amount of 0.78lbc.. seem no regular to me because few days ago I was checking the total amount changing of the same amount of unloked tip... I don't Understand what happen.
Please give me more help. Thank you Eterni

Il giorno 30 Gen 2021, 07:07, alle ore 07:07, Thomas Zarebczan <notifications@github.com> ha scritto:

**Comment by eterniimmortali** [comment]
I did a Test 36,74703305 Your total balance. All of this is yours, but some  is in use on channels and content right now.
7.10258257 immediately spendable
29.64445048 boosting content
I unlock tip amount 0.70168512
After unlock 0.70168512 I have:
36,74692605 Your total balance.
7.80416069 immediately spendable
28.94276536 boosting content.. Is it working good? Seem not to me
Please give me more help. 
Thank you Eterni

Il giorno 30 Gen 2021, 07:07, alle ore 07:07, Thomas Zarebczan <notifications@github.com> ha scritto:

**Comment by tzarebczan** [comment]
Your total balance will not change when you unlock. It may go down by a small amount due to the transaction fees of unlocking the tips. 

A mass tip claiming feature will be coming soon.

**Comment by eterniimmortali** [comment]
Thanks Thomas 👍... Last question sorry... Why few days ago tips-unlock where updating the wallet in total? 

Il giorno 30 Gen 2021, 18:46, alle ore 18:46, Thomas Zarebczan <notifications@github.com> ha scritto:

**Comment by tzarebczan** [comment]
The total balance has been changed to reflect both available and locked LBC. In the end, that locked LBC is in your wallet and we wanted to reflect that.

**Comment by eterniimmortali** [comment]
Hi Thomas Thank You very much for your great support best regards Max 

Il giorno 1 Feb 2021, 20:39, alle ore 20:39, Thomas Zarebczan <notifications@github.com> ha scritto:
