### ISSUE TITLE
Video showing previous audio clip's thumbnail instead

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#5450]
1. Open https://odysee.com/@Musica_Clasica:a2/Dvorak--Sinfonia-n-8--Op-88--mp3:3. I used Brave Browser
(this issue is a little bit odd. Sometimes, it's not reproducible on Desktop, but reproducible on Desktop if I pick another pair of claims, and vice-versa for Web)
2. In the `Elements` dev tools, confirm that `<audio` is there.  If not, press Back to invoke the Floating Player, then Close (this forces a `dispose`), then return to this music file.
3. In the **wunderbar**, paste https://odysee.com/@veritasium:f/why-are-there-huge-colorful-pools-in-the:b  and press Enter.  Start the video without closing the Floating Player.
--> What's on screen is not the video but the previous thumbnail. The audio of the video is audible, though.

Notice that `<audio ...>` did not switch to `<video ...>`.  When changing to a small number of claims, sometimes `dispose` isn't called (probably React did not think the component needed to unmount).

Aside: I noticed in Discord that the playback issues have been attributed to certain routers blocking the CDN.  I don't think that's the case for me, as when I force it to dispose on every claim-change in my local build, the playback error does not happen (I think it's due to syncing issues between the async `fetch` for m3u8 header and videojs's caching of sources (suspiciously related error message -- github.com/videojs /video.js/issues/3751).  
So, along with this `<audio` problem, I wonder if we should just always dispose when the source changes.

![image](https://user-images.githubusercontent.com/64950861/106421246-58f19a00-6497-11eb-8bae-8475bc91ac17.png)

**Comment by tzarebczan** [comment]
Nice catch and thank you for filing!
