### ISSUE TITLE
Create file thumbnail fallback image for odysee

### ISSUE THREAD

**Issue by neb-b** [lbryio/lbry-desktop#5457]
We just display a grey box for thumbnails that error currently. We should have some placeholder thumbnial.

<img width="421" alt="Screen Shot 2021-02-01 at 1 49 57 PM" src="https://user-images.githubusercontent.com/16882830/106504051-6e18f980-6494-11eb-8834-7eafdba8006c.png">

**Comment by tzarebczan** [comment]
Also the default gradient on channel page please! https://github.com/lbryio/lbry-desktop/issues/4928

**Comment by dejanbr** [comment]
![placeholder 500px](https://user-images.githubusercontent.com/78141757/108765646-580ece00-7554-11eb-8357-3d1467a775db.png)
![placeholder_1200px](https://user-images.githubusercontent.com/78141757/108765650-593ffb00-7554-11eb-8619-1e7b96df28ba.png)

**Comment by seanyesmunt** [comment]
I forgot the original PR that supported this was reverted. https://github.com/lbryio/lbry-desktop/pull/5430

Revert PR: https://github.com/lbryio/lbry-desktop/pull/5540

That will need to be fixed/added back before this can be added.

**Comment by tzarebczan** [comment]
Here's the image - we can pass optimized params like we did with others: 
https://spee.ch/missing-thumb-png:3.png

https://spee.ch/missing-thumb-png:3.png?quality=90&height=1200&width=630
