### ISSUE TITLE
Interact directly with commenting servers

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#5459]
- [x] Drop SDK calls (SDK is dropping `comment_xxx` commands)
- [x] Replace with direct calls to server matching `commentron` APIs
- [ ] Add setting for changing your comment server. Visible on desktop (and possibly defaulting to Odysee URL), hidden on odysee.
- [ ] Revise comment onboarding on desktop.

**Comment by lyoshenka** [comment]
@jessopb can you prioritize this next time you do sprint planning?

**Comment by lyoshenka** [comment]
@kauffj please prioritize this (at least the first two bullet points) during next sprint planning

**Comment by kauffj** [comment]
@infinite-persistence you're likely to get this on Monday and are welcome to do this instead of other work if you prefer.
