### ISSUE TITLE
Search Page / realted: Not Responsive 

### ISSUE THREAD

**Issue by gabrielleraines** [lbryio/lbry-desktop#5460]
@seanyesmunt told me to open this. The search page had content that was cut off on smaller screens. 

Page URL: https://odysee.com/$/search?q=emma%20chamberlain
![Screen Shot 2021-02-01 at 5 57 39 PM](https://user-images.githubusercontent.com/37669191/106528744-412a0e00-64b7-11eb-9a21-be63df8d58f7.png)

**Comment by tzarebczan** [comment]
Also make sure titles are not cut off in related section.
