### ISSUE TITLE
"Search only in this language by default" Also Hides Channel Content

### ISSUE THREAD

**Issue by ElectronEsq** [lbryio/lbry-desktop#5466]
# Confusing Search Option hides Channel Content

A member of the community (Eduardo Bibiano) was seeking help because the content in the channels he follows, disappeared.
The reason was, he'd set "Search only in this language by default" to his language. This feature then hid channel content that's not in his language.

This is confusing and could have a big impact on channel visibility because many people might not realise it's doing this. The setting suggests it just hides search results.

**To Reproduce**

1. Go to 'Settings'
2. Click on 'Language.'
3. Set to 'Italian'
4. Select 'Search only in this language by default'

**Expected behavior**
Still see all content in any channel you visit.

**Actual behavior**
Hides content in that channel if it's not set to the chosen language.

**Screenshots**

![image](https://user-images.githubusercontent.com/29914179/106614652-50908080-65b7-11eb-8a89-95e2f793e033.png)

## Example:
![image](https://user-images.githubusercontent.com/29914179/106614679-58e8bb80-65b7-11eb-89fa-158854f239da.png)

![image](https://user-images.githubusercontent.com/29914179/106614699-5c7c4280-65b7-11eb-923f-b7038bf297f8.png)

**Comment by ElectronEsq** [comment]
Apparently there is already an issue for this? I can't find it.

**Comment by ElectronEsq** [comment]
Found it: https://github.com/lbryio/lbry-desktop/issues/5219

**Comment by tzarebczan** [comment]
Thanks for filing, will keep the other open.
