### ISSUE TITLE
live stream bugs

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#5497]
- [ ] While a channel is active, all publishes are treated at livestreams

- [ ] After a user publishes a live stream, even if they are not setup as active live streamer, all new publishes are treated as live streams.

- [ ] very first comment won't show for poster (not sure about others) until refresh.

**Comment by DispatchCommit** [comment]
Blocked by: https://github.com/lbryio/lbry-sdk/issues/3180

**Comment by tzarebczan** [comment]
I don't think it's necessarily blocked by that, but instead it's some state-related issue. Making sure you are aware with your refactor. 

Added another commenting bug to the list.
