### ISSUE TITLE
Add support for swapping into LBC

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#5503]
- Add a new secondary button on the top of the wallet page next to "Receive" and "Send" called "Swap". It will use the bitcoin logo for the icon (I will add this)

Views:
This is the first view. Use `Lbryio.call('btc', 'rate', { satoshis: amountFromInput }) ` to get the LBC estimate
<img width="999" alt="Screen Shot 2021-03-09 at 3 04 58 PM" src="https://user-images.githubusercontent.com/16882830/110530785-d76dd700-80e8-11eb-9ab9-2c341be39cfa.png">

When users clicks "Start Swap" button, call `Lbryio.call('btc', 'swap', { lbc_satoshi_requested: lbcAmountFromRateCall, btc_satoshi_provided: btcAmountFromInput, pay_to_wallet_address: usersLbcWalletAddress })

After calling `swap`, call `Lbryio.call('btc', 'status', { pay_to_address: usersLbcWalletAddress })`

- if status is `"pending"`

<img width="652" alt="Screen Shot 2021-03-09 at 3 14 47 PM" src="https://user-images.githubusercontent.com/16882830/110532095-692a1400-80ea-11eb-8ff9-2be59800e820.png">

- if status is `"processing"`

<img width="653" alt="Screen Shot 2021-03-09 at 3 14 52 PM" src="https://user-images.githubusercontent.com/16882830/110532084-63343300-80ea-11eb-8955-e970cd087961.png">

- if status is `"success"`

<img width="648" alt="Screen Shot 2021-03-09 at 3 14 58 PM" src="https://user-images.githubusercontent.com/16882830/110532058-5c0d2500-80ea-11eb-9018-7a82259902cf.png">

**Comment by kauffj** [comment]
@seanyesmunt will flesh out this ticket and provide documentation, then hand to @infinite-persistence

**Comment by seanyesmunt** [comment]
@infinite-persistence I updated this ticket with screenshots of the UI to build. Most of it should be able to be built just from using the same styles as the send/tip confirmation modal. 
https://github.com/lbryio/lbry-desktop/blob/master/ui/component/walletSendTip/view.jsx#L173-L197

There is also another response type from the `status` call. `"error"`. I'm not sure how that should look yet, but probably just go back to the first view and trigger an error snack bar.

- While you are working on this, please change "Send" and "Receive" to be pages similar to the "Buy" page. The modals can be deleted.

**Comment by kauffj** [comment]
@infinite-persistence the vendor we decided to use for processing supports multiple coins. Can you update this PR to support them? @tiger5226 has the details.
