### ISSUE TITLE
Signing out of account causes page to break in other tabs

### ISSUE THREAD

**Issue by DispatchCommit** [lbryio/lbry-desktop#5504]
Open up multiple tabs of odysee.com.

In tab A open a video, then go to tab B and sign out of odysee. Now return to tab A and an error will popup.

**Comment by tzarebczan** [comment]
I think this was introduced when we added sync on tab activation. When you sign out, the token is invalidated and sync process will fail. Previous to this it probably would have just signed you out. 

We probably don't know the difference between an invalid token and when the tv api fails when in the sync loop. Something can maybe catch that after and see if a token doesn't exist anymore + refresh.
