### ISSUE TITLE
Fix buffering with user-driven decentralisation

### ISSUE THREAD

**Issue by IIlIIIlIIII** [lbryio/lbry-desktop#5505]
**Is your feature request related to a problem? Please describe.**
videos buffer way too much, and this is likely driving away users. adding all these niche features is great, but if you dont fix buffering, you won't have users in the first place.

**Describe the solution you'd like**
build an application that everyday people without any technical knowledge can download which lets them act as a CDN, offering their bandwidth, storage, and cpu/gpu in exchange for LBRY tokens. an example of this is the 'edge node' application that has been made by/for the theta network

**Describe alternatives you've considered**
alternatively you could try to implement the theta network directly into lbry, but i'm not sure if thats more work or less work

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. The majority of users do not see buffering. Please send us an email at hello@lbry.com with details about what content is buffering, where you are located, and your bandwidth speed at ovh.net and we'll take a closer look.
