### ISSUE TITLE
Annoying modal popups

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry-desktop#551]
## The Issue
There are some annoying and unnecessary popups inside the app.
Most of them are errors badly handled.

### Steps to reproduce
1. If you have an empty balance and go to `walletSend` 
a popup it's shown, but this is annoying and don't prevent the user of submitting the form.

2. If you try to send a higher value than your current balance an other popup it's shown, it should display the error below the input or don't allow -> `value > balance` .

### Expected behaviour
A simple example of empty-states:
![image](https://user-images.githubusercontent.com/14793624/30256765-468444e8-966a-11e7-83f8-59cad6dae75c.png)

> A list that doesn’t contain any items, or a search that doesn’t display any results, are examples of empty states. Although these states aren’t typical, they should be designed to prevent user confusion. 
### Reference
Please see this for reference:
https://material.io/guidelines/patterns/empty-states.html#
https://material.io/guidelines/patterns/errors.html#errors-user-input-errors

**Comment by btzr-io** [comment]
Split from -> https://github.com/lbryio/lbry-app/issues/531

**Comment by btzr-io** [comment]
Here is another one, fixed in #550  -> 75417949122d1f6078357f290c95441ecfca3761
![missign_parameters](https://user-images.githubusercontent.com/14793624/30408104-da50581e-98b9-11e7-8255-ae9fdf06d153.jpeg)

**Comment by liamcardenas** [comment]
@btzr-io hey great work identifying this, what are the next steps for eliminating these modals?

**Comment by btzr-io** [comment]
@liamcardenas Hi, first we would need to create an `EmptyState` component / layout:
> The most basic empty state displays a non-interactive image and a text tagline.

For the image probably use some basic illustrations or just icons...

This was intended to be part of the `material-design` refactoring / improvement,
but now that the app is moving towards @nizuka01 design maybe look for other alternatives?

https://material.io/guidelines/patterns/empty-states.html#

**Comment by alyssaoc** [comment]
most of these are fixed, please open new issues for specific modals
