### ISSUE TITLE
iOS safari / Firefox doesn't autofill saved login credentials

### ISSUE THREAD

**Issue by anohren** [lbryio/lbry-desktop#5518]
**Bug**
When trying to log in Safari on iOS 14.4 does not offer to fill in the email address for the account. 

**To Reproduce**
1. Go to https://lbry.tv/$/signin
2. Tap email field
3. Safari offers to autofill a form — not your saved login information.  

**Expected behavior**
An offer to autofill your saved login email for the domain. 

**System Configuration**

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system: iOS 14.4

**Additional context**
I was apparently logged out automatically, for some reason, unless I'm mistaken. Can't remember doing it manually anyway. In combination with this bug it creates a high threshold to choose lbry over that other service where you're already logged in.

**Comment by tzarebczan** [comment]
This also happens in Firefox apparently.
