### ISSUE TITLE
timestamps not interpreted in some cases

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#5523]
See https://odysee.com/@garrytan:e/startup-next-steps-after-raising-your:8 

I think we've seen something in the past related to it requiring new lines - so it might be that?

**Comment by infinite-persistence** [comment]
It was working in 0.49.4, but broken in latest master.  Perhaps the recent plugin updates broke it. 
I also recall supporting/testing multiple timestamps in a line (newline not required) in the past. Will look into it.
![image](https://user-images.githubusercontent.com/64950861/108013028-ca0f8080-7045-11eb-95e5-d3edcd5b5ef7.png)
![image](https://user-images.githubusercontent.com/64950861/108013058-de537d80-7045-11eb-8958-29b521ed292b.png)

**Comment by infinite-persistence** [comment]
Ah, the upgrade to `remark-breaks` was the culprit. Fix coming up...
