### ISSUE TITLE
hide offensive comments with creator tools

### ISSUE THREAD

**Issue by Tcll** [lbryio/lbry-desktop#5524]
as you guys already know, I've had an encounter with a rather aggressive individual in the comment section of my channel...

I would prefer not to delete his comments unless he explicitely requests, but I would prefer our long, drawn out threads not be so in-your-face when viewing my comment section.

would you please integrate an extension of the slime system into creator tools to allow creators to mark comments as hidden:
(which would ultimately hide the whole sub-thread by default)

> This comment was hidden by @Tcll5850. (click to show)

and also have some CSS (same as a [previous](https://github.com/lbryio/lbry-desktop/issues/5279) issue) to turn the text into a button on hover and click.

EDIT: also be able to unhide (unmark) the comment if a mistake or clarification was made

**Comment by tzarebczan** [comment]
I don't think we'll be doing a hidden option that works outside of your own view. The next release will have a mute option, but this will only be for your own account, others will still see it. You'll want to block otherwise.

**Comment by Tcll** [comment]
that's a shame
the posts being there are actually educational in a way
I just don't want them to be the primary focus

makes my comment section more difficult to read with them expanded like that

**Comment by Tcll** [comment]
I still stand behind a moderation tool to hide bloat for others
all they have to do is click the hidden comment if they want to view it

it's still a shame we don't have that to clean things up

I don't block people because it doesn't achieve what's desired
I want people to speak their mind
I just want to mark the comments as hidden for people to view if they want to

again, it should use the same mechanic as hiding disliked comments
except I should be able to toggle display in my moderation tools
