### ISSUE TITLE
Mass download options / Storage selection

### ISSUE THREAD

**Issue by Jolijar** [lbryio/lbry-desktop#5530]
I have several requests / ideas related to file downloads and hosting.
The goal of this is to make it easier to support your favorite creators by re-hosting their content.

**Feature Request 1**
In app be able to select what folder videos and blobs download to as well as set a max download cap 
**Reason:** Selecting storage area makes it clear where files are at and makes it easier to manage.

**Feature Request 2a**
Download all videos from channel button on channel page. 
**Reason:** Support Creator by hosting all their content.

**Feature Request 2b**
Download all new releases from channel
**Reason:** Support Creator by hosting all new content & no buffering if it releases and you are not there to watch it before it downloads.

**Feature Request 2c**
Premiere mode.  Allow creator to select video to be released early to those that have download all new releases selected.
**Reason:** Additional benefit for users to host content and better sharing for initial launch for others.

I think these features would be rather simple to implement but allow for a better user experience.

Just some thoughts.  Keep up the great project :)

**Comment by tzarebczan** [comment]
Thanks for filing the issue and the ideas!  These are filed under thier respective issues :

https://github.com/lbryio/lbry-desktop/issues/1966 / https://github.com/lbryio/lbry-desktop/issues/4634

https://github.com/lbryio/lbry-desktop/issues/2844
