### ISSUE TITLE
Content re-published without channel not handled properly

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#554]
## The Issue
Related to https://github.com/lbryio/lbry-app/issues/553, if the original published content had a channel but is then re-published anonymously (without a channel), the Publishes page continues to show the channel (even after the file is confirmed). It actually doesn't show Pending confirmation until after going to Developer > Reload. When I did this, the file was already confirmed and it seems to stay in the pending confirmation state. If I clear the cache, the file disappears completely from the Publishes page and is instead shown on the Downloads page (still with the channel). 

### Steps to reproduce
1. Publish content to a channel
2. Edit content by going back to Publish, typing in the URL and clicking "Use data from my existing claim" option. Change the title
3. Republish content without a channel
4. Publishes page will show the content as published, but changes are not reflected (still shows channel name and old title). Does not go into "pending confirmation" state. 
5. Developer> Reload - now the file shows "Pending confirmation" even though it's confirmed
6. Restart app - the file disappears from Publishes area and shows up in Downloads instead. 

### Expected behaviour
Should go into pending confirmation state without the channel and with updated title

### Actual behaviour
Does not update on Publishes and then shows up in Downloads 

## System Configuration

 

- LBRY Daemon version: 0.15.2
- LBRY App version: 0.15.1
- LBRY Installation ID:
- Operating system: Windows

## Screenshots

![channel1](https://user-images.githubusercontent.com/8120721/30299566-4801aaae-971e-11e7-9fc8-90c1b71786ca.JPG)

![channel2](https://user-images.githubusercontent.com/8120721/30299573-51a70a22-971e-11e7-861c-cfa01a15a293.JPG)
![channel3](https://user-images.githubusercontent.com/8120721/30299585-5d5de9bc-971e-11e7-8d6d-06c032ed22d5.JPG)
![channel4](https://user-images.githubusercontent.com/8120721/30299629-89b33530-971e-11e7-9726-632da7c47803.JPG)
![channel5](https://user-images.githubusercontent.com/8120721/30299633-8cfee77a-971e-11e7-9bee-9fececb0d272.JPG)

**Comment by liamcardenas** [comment]
@tzarebczan can you try this again?

**Comment by tzarebczan** [comment]
There's still an issue on how this scenario is handled. Pretty much need to clear cache and access the claim's non-channel URL for it to pick up the publish correctly.

Just refreshing causes the publish to stay in a "waiting for confirmation" state. And if you click on it, it tries to resolve the previous URL which has the channel on it and fails because it's no longer a valid location. If you clear cache, it then disappears from the publishes area (but shows in downloads). It's not until you go back into the claim from the downloads page (or the direct URL) that it shows correctly in Publishes.
