### ISSUE TITLE
Clicking edit on a claim and then clicking Cancel is broken

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-desktop#5550]
To reproduce:

- click Edit on your claim
- click Cancel

Instead of closing the Edit screen, it says 

> You already have a claim at lbry://brendon-brewer-lbrynomics-trending#8d992b5b42ebbb12c0d7a1320f9c96fae3ea64d2. Publishing will update (overwrite) your existing claim.

**Comment by infinite-persistence** [comment]
Potentially related: #4217

**Comment by lyoshenka** [comment]
duplicate of #4217
