### ISSUE TITLE
Inputs have no borders on light mode

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-desktop#5551]
You don't know they can be clicked or edited. Even if you do, you don't know where to click.

![KNxlEun](https://user-images.githubusercontent.com/362784/108422626-cf66f980-7204-11eb-93b7-14f8e3d98e10.png)

**Comment by DanielaNarvaez** [comment]
Hi, I will be working on this issue if that's ok :)

**Comment by jessopb** [comment]
Great!

**Comment by DanielaNarvaez** [comment]
Hi, I have use this color: Var(--color-gray-3)
![image](https://user-images.githubusercontent.com/16692007/147247044-751222c0-7408-4bc2-a36d-fd4e9ecca16a.png)
is it ok?

**Comment by jessopb** [comment]
I think this is tricky because it makes the attached buttons seem like they need a border too.
I think the darkening of the first line is good and the separator, but I"m not sure about the outer border.

**Comment by DanielaNarvaez** [comment]
How about this?
Then:
![image](https://user-images.githubusercontent.com/16692007/147262429-a11e72fe-6f54-4132-9db1-40f3676457ea.png)

Now:
![image](https://user-images.githubusercontent.com/16692007/147262227-f6d1dcbd-ca76-4c80-a9ce-5452f49e5a9a.png)

**Comment by DanielaNarvaez** [comment]
Hi, Merry Christmas 🎄. Just let you know that I'm still waiting for feedback 🙃. Thanks!
