### ISSUE TITLE
Video: loading circle sometimes does not appear until 2nd click

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#5554]
This happens on Desktop, Live Site and local builds.

1. Enable "Autoplay" in settings.
2. Clicked on a video.
    - The expected behavior is that the video container would start the loading circle and eventually play the video.
3. Occasionally, the loading circle doesn't appear until either `(a)` I clicked on the large play button again `(b)` the player has gotten the data to play the video.
    - It's probably not noticeable if your region's server is fast, but for my slower region (i.e. long buffering), it looks odd that I need to click Play twice.

In the example below:
https://www.youtube.com/watch?v=Esr2-nBxFls
- I waited until 0:30 to to perform `(a)`.
- I then loaded another video, and patiently waited until 1:26 to get `(b)`, although it ended up buffering again (typical situation for me).

**Comment by tzarebczan** [comment]
I've seen some really strange quirks related to the player, hopefully the indraft PR fixes them. Can you try on that branch?

**Comment by infinite-persistence** [comment]
Not seeing the issue on that branch -- looks good.

**Comment by infinite-persistence** [comment]
I take that back.  That branch only had aesthetic changes, so is probably unrelated.  If I merged it with the latest `master`, then the issue occurs.  
I think some commit ahead of that PR (maybe `0fff2542: Add custom quality selector plugin`) is the culprit.
