### ISSUE TITLE
Opening video makes app crash, build with latest source build

### ISSUE THREAD

**Issue by keikari** [lbryio/lbry-desktop#5557]
**Bug**
Clicking video crashes the app. 

**To Reproduce**
1. Go to https://odysee.com/@El-Has-The-Problem:0/Emptying-the-Bag-Full:8
1.1 Same error happens if using latest source for building the app
2. Website should show error screen

**Expected behavior**
App/website doesn't crash and shows page with video.

**Screenshots**
I hope instructions in "to reproduce" will be enough.

**System Configuration**

     

App | 0.49.4 - Changelog
Daemon (lbrynet) | 0.88.0
Connected Email | \<here was my email\> Update mailing preferences
Reward Eligible | Yes
Platform | Linux (Linux-5.4.92-gentoo-x86_64-AMD_FX-tm-6300_Six-Core_Processor-with-gentoo-2.7)
Installation ID | 6fCyyi4wTNGME7AGM8jTf9L8Hb1eBqsdBVCQeDqpY7vb3AfrcRtjtM8MGM4bAoq7px

 {
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "desktop": "Unknown",
    "distro": {
      "codename": "",
      "id": "gentoo",
      "like": "",
      "version": "2.7",
      "version_parts": {
        "build_number": "",
        "major": "2",
        "minor": "7"
      }
    },
    "lbrynet_version": "0.88.0",
    "os_release": "5.4.92-gentoo",
    "os_system": "Linux",
    "platform": "Linux-5.4.92-gentoo-x86_64-AMD_FX-tm-6300_Six-Core_Processor-with-gentoo-2.7",
    "processor": "AMD FX(tm)-6300 Six-Core Processor",
    "python_version": "3.7.9",
    "version": "0.88.0"
  }
}

**Additional context**
Seems to only happen with long videos. Checking console shows something about infinite loop.
Doesn't happen with latest release. Only with websites and if app is build from latest source.

**Comment by tzarebczan** [comment]
Thanks for filing. We spotted this yesterday and it will be fixed soon. 

Another URL: https://odysee.com/@PandemicParallaxView:6/Rocco-Galati-on-Constitutional-Rights-Centre-Lockdown-Lawsuit:2

**Comment by infinite-persistence** [comment]
`-- Close --`
Sean has reverted `remark-breaks` and the underlying issue has been logged separately in 5561
