### ISSUE TITLE
lbry.tv is confused about password being set or not.

### ISSUE THREAD

**Issue by er013** [lbryio/lbry-desktop#5559]
Set password at odysee. Went to lbry.tv, settings. This says I have no password set. Clicking set button, entering password, submit. Response is that now all of the sudden I do actually have password set and to change it, I should use password reset api. Odysee shows me a button to "update your password". Havent tried to click on that one yet...

![2021-02-22-033907-import](https://user-images.githubusercontent.com/60119125/108647003-38c66100-74c0-11eb-9420-6df9ec1ba44a.png)

**Comment by tzarebczan** [comment]
It's probably just an issue with refreshing that status on that page. Can you confirm it has the right status if you ctrl-r on lbry.tv before hand?

I don't think this is a common case so going to close for now.

**Comment by er013** [comment]
Thought so, did refresh at that time, changed nothing. Today, after browser has been restarted, it says update your password on the button.

**Comment by er013** [comment]
Whats not common? Programs behavior should make sense. Nevermind how user got that form, If he enters password and only after does program discover that password is already set, then go update damn password, how about that innovative idea? Instead of that weak failure and error message that serves only to confuse a regular folk...
