### ISSUE TITLE
Long blank screen after clicking on a video

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#5562]
Lately, on both the live sites as well as Desktop, I often get a blank screen after clicking on a video.  The duration of that blank screen varies from 5 seconds to 55 seconds (the longest that I've recorded; there could be longer ones).  Nothing suspicious in the console.

The usual/expected behavior is that the blank video container, Related and Comments structure is loaded somewhat quickly while the inner data is being fetched.

**Comment by tzarebczan** [comment]
Can you try to narrow down what it's waiting for via the network tab? It could just be a temporary hiccup on the web SDKs  (or even local) which causes slowness in the calls.

**Comment by infinite-persistence** [comment]
Still learning how to use `Network`, but is it due to `list_blocked`?  
In the example below, I switched to incognito (no blocked channels, hoping it'd be faster), but it's still the same. 
When claim pages do load quickly/normally, I don't see `list_blocked` in the Network Tab.

https://lbry.tv/@Alojz:f/tamaguino-soldered-and-battery-powered:4

![image](https://user-images.githubusercontent.com/64950861/108811836-f64c7380-75e8-11eb-8f69-4801f883bd49.png)

----
Aside (most likely incorrect):
Another potential culprit is the video poster? https://thumbnails.lbry.com/nI4fCdZDMbY loaded slowly in the browser for me. Not sure if videojs is currently using a blank poster while waiting or not (I think it does, though).

**Comment by infinite-persistence** [comment]
`Close`
- I think Sean fixed using https://github.com/lbryio/lbry-desktop/commit/3fba7f07978b3b0aa7987ee812c22b3cd3f18a18
