### ISSUE TITLE
Show "URL already used" msg when publishing

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#5575]
Was trying to publish something and got confused on why the final 'Upload' button remained disabled -- I've already filled in everything.  Later, I realized that the entered URL was already used.

I vaguely recall there was an error message for this situation near the URL field in the past.

**Comment by tzarebczan** [comment]
It used to force an edit i believe. Probably related to that other bug you recently fixed.

We should really move towards https://github.com/lbryio/lbry-desktop/issues/3704 - would you be interested in working on it?
