### ISSUE TITLE
LBRY associates itself with html files on GNU/Linux without asking

### ISSUE THREAD

**Issue by kodxana** [lbryio/lbry-desktop#5577]
**Bug**

**To Reproduce**
"Each time when I start LBRY it sets HTML file
association to itself. I really don't want to open HTML files on my
computer with LBRY. This behavior is annoying."

**System Configuration**
- Operating system: Debian 10 and Debian 11
- Latest app from Deb file

**Additional context**
Reported by user via email

**Comment by infinite-persistence** [comment]
Duplicate of #4729
