### ISSUE TITLE
[Desktop] Stop auto-seeding all viewed content; add option to re-seed in content view UI

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [lbryio/lbry-desktop#5591]
I recently had a critically low storage notification from my operating system during a system update. A disk scan showed that the LBRY desktop app had stored, and not temporarily-stored, all viewed content and was utilizing more than 60% of all possible space on my storage drive. And it did so without my consent; nor even my knowledge.

Granted, my storage drive small, but that's intentional. Do you have any idea how hard it is to find sub-64GB storage drives these days???

1. Immediately stop automatically storing and re-seeding all viewed content.
2 Viewed (downloaded) content should be placed in a temporary cache which is flushed at regular intervals and at application close.
3. Place a new UI element in the content-view display, giving a user the option to re-seed if they choose. If/when user intentionally chooses to re-seed content, that individual content item can then be relocated to seeding directory in the filesystem.

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. The goal is to add max size settings for these and allow other options in the future. There are tickets already filed for this and it's covered in FAQs.

**Comment by ParaplegicRacehorse** [comment]
Well, that's a start. If I may ask, for how long has this goal been on the roadmap (web site is 12+ months out of date)
