### ISSUE TITLE
[lbry.tv] Stop scanning my computer outside of web-cache space. It's illegal in my jurisdiction.

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [lbryio/lbry-desktop#5592]
**Bug**
The scan required to determine this is a violation of numerous laws in my country. It is electronic intrusion and can be penalized by up to 20 years in prison _per each verifiable occurrence_.

![image](https://user-images.githubusercontent.com/7605896/109402039-fc02cb80-78fe-11eb-857d-b0458dc482a7.png)

**To Reproduce**
1. Go to any page at lbry.tv
2. Look at the bottom of your browser window.
  * Assumes you have ever had the desktop app installed and your config dir structure exists (I think? I don't actually know what the code is looking for, or how it does it. I just know it's snooping in my filesystem in places I did not give it permission to look.)

Disabling the browser function which allows this scan breaks the entire site and no content can be displayed. You are literally requiring that I permit you to snoop around my filesystem if I want to view content via your service.

**Expected behavior**
I expect LBRY to respect my privacy and personal electronic space. Just because modern web technology and default browser settings make this possible does not mean there is any possible justification for doing so without my explicit invitation (as when using one of those web-based virus-scanning tools.)

I strongly suspect this also happens at odysse.com but, because it hasn't yet reached UI-feature parity with lbry.tv, I have not verified.

I was unable to find any mention of this in the Terms of Service, or Privacy policies, or FAQ.

**Comment by seanyesmunt** [comment]
We don't snoop on your file system.

If you have a desktop app installed and choose to share data with us we make a record of it in our database. Then when you use the same email on one of the web apps, we show that message.

**Comment by ParaplegicRacehorse** [comment]
I _used_to_have_ the desktop app installed (removed when I discovered it was -- without my knowledge or consent -- storing every bit content viewed and re-seeding.)

I never volunteered to share data with LBRY. There does not appear to be an option in preferences (lbry.tv; can't check desktop because I removed it) to either opt-in or opt-out of data sharing.

**Comment by tzarebczan** [comment]
The first prompt when you run the Desktop app asks for permission to share data. 

Lbry.tv does not have these options since you already are sharing by signing into the website.
