### ISSUE TITLE
Why is Lbry downloading each video to my iMac ??

### ISSUE THREAD

**Issue by sollymil** [lbryio/lbry-desktop#5593]
I'm using the app on my iMac and each video gets downloaded to my local iMac !!!

I certainly do not want this.  How do I stop it?

Many thanks

**Comment by sollymil** [comment]
Just seen the help menu in 'Settings' Hmmm.... If a download message had not appeared for each video, I would have been oblivious that Libry was using my iMac and (limited) bandwidth for it's own purposes.  I think you need to be a bit more clear on doing this.  It feels like resource usage by Stealth.

**Comment by tzarebczan** [comment]
This is the default mode and can be changed in settings.
