### ISSUE TITLE
redux devtools load  unreliably in electron app dev mode

### ISSUE THREAD

**Issue by jessopb** [lbryio/lbry-desktop#5612]
Repro:
yarn dev
open devtools, close devtools, and reload until you see redux devtools tab missing

**Comment by infinite-persistence** [comment]
## Notes
- Potentially related: `https://github.com/facebook/react/issues/19002`
- Happens depending on when you open the devtools during app load.  But toggling the panel seems to reload the tab.
- Potential workaround:
    - Locally, clear or reduce `rowData` in `homepage.js` to just `RECENT_FROM_FOLLOWING`.  The Redux DevTools tab seems to always appear for this case.
        - Maybe something in the processing of the homepage is causing the extension to not load.

**Comment by jessopb** [comment]
This is much less of a problem now.
