### ISSUE TITLE
Fix bugs related to web socket version of comment list

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#5614]

**Comment by DispatchCommit** [comment]
I believe this is resolved, @seanyesmunt can you confirm?

**Comment by seanyesmunt** [comment]
I fixed the issue where first comments aren't showing up until refresh. I'm trying to figure out how you can get connected to the websocket twice now

**Comment by seanyesmunt** [comment]
Fixed with #5692
