### ISSUE TITLE
The embed end screen should allow for restarting the playback

### ISSUE THREAD

**Issue by stefansundin** [lbryio/lbry-desktop#5615]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I reach the end of a video in an embedded player and I see the following:

<img width="340" alt="Screen Shot 2021-03-03 at 19 19 24" src="https://user-images.githubusercontent.com/1991151/109906463-609e8d00-7c55-11eb-8aa7-19e77fcc7bfe.png">

The button opens a new window to the video. There is no obvious way to just restart the playback in the embedded player instead (actually, there is a workaround described below).

**Describe the solution you'd like**

The main call to action should be to rewatch the video in the embed player. There could be two buttons, one that restarts the video in the embed player, and one that opens the video in a new window. But I think it is important that the button to restart in the embed player is **the primary button**.

There could also be an X in the top right corner that just removes the overlay and grants access to the player buttons, allowing the user to restart the playback or seek to a particular position in the video.

**Describe alternatives you've considered**

I actually found a workaround while messing around. The keybindings are still active, so it is possible to press the space key (or the left/right arrow keys) to "get out of" the end screen.

**Additional context**

If you think this is an ok change, then I may attempt it myself. But I'd like an 👍  or 👎  on what the LBRY team thinks. Thank you!

**Comment by jessopb** [comment]
Not really relevant anymore? Reopen if so.
