### ISSUE TITLE
Configurable auto-follow // Mark Odysee as auto-followed (if feature exists)

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#5620]
And add @ odysee, @ odyseehelp to odysee instance

**Comment by kauffj** [comment]
some questions if this is working 100% of the time, passing to @tzarebczan to validate

**Comment by tzarebczan** [comment]
It's broken because it tries to follow before the sync is setup, so you get a message that says "finishing setting up accuont"
