### ISSUE TITLE
UX: Browser should display image downloads

### ISSUE THREAD

**Issue by jsigwart** [lbryio/lbry-desktop#563]
## The Issue
Currently the LBRY-app player displays thumbnail images for videos, but no preview for image files. Images are represented by file folder icon on a gray window, and it is not obvious a user needs to click on the file folder icon to view the image.
### Steps to reproduce
1. Download lbry://lbry-app-ui#a54b46b501f23f77599d6b4c6c80854bda31d520 in the app. 
2. Notice there is no preview, just the file icon on the gray background.

### Expected behavior
We should see the image rendered in the preview area, scaled to fit either horizontally or vertically (but not stretched). 

### Actual behavior
We see file icon on gray background

## System Configuration

 

{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "lbrynet_version": "0.15.2",
    "lbryschema_version": "0.0.10",
    "lbryum_version": "3.1.6",
    "os_release": "15.6.0",
    "os_system": "Darwin",
    "platform": "Darwin-15.6.0-x86_64-i386-64bit",
    "processor": "i386",
    "python_version": "2.7.13"
  }
}

**Comment by tzarebczan** [comment]
If a thumbnail was provided for the image, it would show the thumbnail there.

Seems to display in the app for me after clicking the preview. But when you go out, and come back into the claim, it goes back to preview mode. So I guess the requested enhancement here would be to auto show the file in the app if its already downloaded (any bypass any thumbnail if it exists)?

**Comment by jsigwart** [comment]
Tom can see images in his browser, but this is what I see for every image file download: 
<img width="1267" alt="screen shot 2017-09-14 at 11 13 41 am" src="https://user-images.githubusercontent.com/1363664/30446870-409f58b0-993f-11e7-93fe-1c6670553fe0.png">

**Comment by MSFTserver** [comment]
@tzarebczan nope not working on windows
![no-thumbnail-issue](https://spee.ch/58b96882af68087bc4da60d0f050d05c3e19480d/no-thumbnail-issue.gif)

**Comment by tzarebczan** [comment]
It's doing exactly what it's intended to - see my UX comments in other post. The question I guess is should we auto-preview the file (skipping the thumbnail) if someone has it downloaded. And then the next question is, what types of content do we do this for? 

The same scenario happens with videos. When you go to the page, you see the uploaded thumbnail. If you click download, it downloads the file, but does not stream (as expected). Clicking the thumbnail starts the stream.

**Comment by jsigwart** [comment]
I would think for video content, it should show the thumbnail (if available), and if it is an image file format, it should show a scaled version of the content in the preview window.

**Comment by tzarebczan** [comment]
@jsigwart can you edit the original issue with the new information and what your suggestion for the UX improvement would be?

**Comment by jsigwart** [comment]
Updated description.

**Comment by btzr-io** [comment]
@jsigwart  I published that on `spee.ch` 
( there isn't an option for thumbnails there ) :stuck_out_tongue: ^^

> If a thumbnail was provided for the image, it would show the thumbnail there.

You can use a gif too:

<img src="https://user-images.githubusercontent.com/14793624/30517220-e221f940-9b15-11e7-9396-5ff5b84d58e9.gif" width=500 />

I think this issue belongs here -> https://github.com/lbryio/spee.ch/issues/

**Comment by btzr-io** [comment]
> Automatically showing the file

I guess it depends on the file type and the user, 
maybe add an option in settings to toggle this feature ...

But this seems to be a different issue...

**Comment by kauffj** [comment]
I'n not sure we can do this without downloading the actual image (which may just be okay?)

However, I agree the UX is poor here regardless.

**Comment by jsigwart** [comment]
The more I think about this, I think there is a bigger issue here that won't be a quick fix. When you upload a video to YouTube, the file is processed on the backend to create optimized video files for different devices plus a thumbnail (unless you upload a thumbnail file - available on certain YouTube accounts). This raises questions about the app creating additional files to be stored on the user's hard drive, and whether this creates multiple claims, etc. I think this deserves some further thought.

**Comment by tzarebczan** [comment]
@jsigwart can we close this in favor or #620?
