### ISSUE TITLE
Disable video previews in comments/posts made by channels below a certain channel staked level

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#5636]
We would like to start disabling video/image previews in comments if the creator of the comment has < x LBC staked to their channel. This is the first feature that will be turned on based on LBC staked so some things will need to be moved around.

- [This function](https://github.com/lbryio/lbry-desktop/blob/master/ui/component/channelStakedIndicator/view.jsx#L17-L36) should be moved to a selector `makeSelectStakedLevelForChannelUri` and added to `redux/selectors/claims.js` in lbry-redux.

- MarkdownPreview should accept a new prop `displayClaimPreviews` that is defaulted to false, and only true when the creator channel is at level 4 or greater. 

- When a claim preview can't be displayed because of insufficient staked amount, just render a regular link with a tooltip. The tooltip can say something like "This channel isn't staking enough :LBC: for link previews".

- The UI for lbry.tv/desktop should not show anything about a channels "level". Levels are only for odysee.

**Comment by kauffj** [comment]
@seanyesmunt will flesh out and hand to @infinite-persistence

**Comment by seanyesmunt** [comment]
@infinite-persistence I updated this issue. Let me know if you have any questions.
