### ISSUE TITLE
Form component should block submit if form fields have errors

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry-desktop#564]
## The Issue
Some forms submit data even when input shows an error or it's empty.

### Steps to reproduce
1. Go to invites.
2. Type an invalid email address, see error: `email: must be a valid email address`.
3. Click submit.

### Expected behaviour
Don't allow form submission until `validation == true`

### Actual behaviour
An error shows in the console, because there isn't a real validation:
```
POST https://api.lbry.io/user/invite 400 (Bad Request)
(anonymous) @ lbryio.js:102
```

**Comment by btzr-io** [comment]
Related issue: https://github.com/lbryio/lbry-app/issues/551#issuecomment-329342925

**Comment by kauffj** [comment]
This is a real issue (e.g. try entering an invalid amount on a wallet page), but note that we sometimes encounter 400s as part of typical/proper usage (e.g. in the case of rewards, we frequently just try to claim them and can receive a 400 if not allowed).

**Comment by tzarebczan** [comment]
Here's another one on the tip screen: 
https://monosnap.com/file/cA6G6iBcPkzzazOYHQ1pIOk6KTe7NN

We use a placeholder, and if no value is entered, you get the above.

**Comment by vv181** [comment]
Trying to reproduce the issue, does not occur. Kindly close it.
