### ISSUE TITLE
unable to configure Automatic transcoding

### ISSUE THREAD

**Issue by liveconvinced** [lbryio/lbry-desktop#5649]
When I set the path to the ffmpeg, it is not recognized or saved.
Perhaps there is another version that's expected? How would I know how to proceed?

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. Have you followed https://lbry.com/faq/video-publishing-guide carefully? You can send us more details about which OS you are on, what you've tried at hello@lbry.com
