### ISSUE TITLE
"Your account" popup in mobile goes off-screen

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#5652]
I had a 40+ character email as my login (I'm guessing this is causing problems)

1. The popup pushes the button offscreen
2. There is an odd animation of the popup slowly going in the left direction.  (when emulating mobile on desktop browser, the animation just keeps looping)

![image](https://user-images.githubusercontent.com/64950861/110581103-dd28f280-81a4-11eb-8861-1e013e0290e5.png)

**Comment by klomontes** [comment]
I’m looking into this and will submit a PR shortly.

**Comment by klomontes** [comment]
@infinite-persistence this issue can be closed.
