### ISSUE TITLE
Flatpak blob files path

### ISSUE THREAD

**Issue by ClodoaldoPinto** [lbryio/lbry-desktop#5655]
I want do help the lbry network but not using my system ssd. In instead I want to use an hdd. But I can't find the blob files path in the Linux Flatpak version. Where is it?

**Comment by tzarebczan** [comment]
Try searching your file system for a file called lbrynet.log and this should lead you to the folder where the blob files are. Usually it's some internal structure setup by the flatpak.

**Comment by ClodoaldoPinto** [comment]
> Try searching your file system for a file called lbrynet.log and this should lead you to the folder where the blob files are. Usually it's some internal structure setup by the flatpak.

There is no lbrynet.log file. I can find a lbrynet binary file in /var/lib/flatpak/app/io.lbry.lbry-app/x86_64/stable/5595355b785f08c0068e6802acfae92dbb98fb59bea0940eb4302ca7ec5c8135/files/lbry-app/resources/static/daemon:

-rwxr-xr-x. 2 root root  17833744 Dec 31  1969 lbrynet
