### ISSUE TITLE
Lbry writes cache in the ~/.config file instead of ~/.cache

### ISSUE THREAD

**Issue by RubenKelevra** [lbryio/lbry-desktop#5665]
**Bug**
Under Linux, the cache of applications is usually written to `~/.cache` while the `~/.config` directory shouldn't keep large amounts of temporary data.

Lbry writes unexpectedly its cache into the `~/.config` directory:

```
$ cd ~
$ du -chd1 .config/lbry/Cache/
64K	.config/lbry/Cache/index-dir
189M	.config/lbry/Cache/
189M	total
```

**To Reproduce**
1. Run lbry
2. check ~/.config/lbry directory for cache entries

**Expected behavior**
Lbry should only write cached data to `~/.cache`.

**System Configuration**

- LBRY Daemon version: 0.88.0
- LBRY App version: 0.49.5 
- Operating system: Linux (Linux-5.11.2-arch1-1-x86_64-with-arch)

**Comment by tzarebczan** [comment]
This is a bug in the electron framework we use and it hasn't been addressed yet. https://github.com/electron/electron/issues/8124

If it's different, please reopen.
