### ISSUE TITLE
Reposts are all listed under "Annoymous"

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#5673]
Under the "Uploads" page, all on my reports are listed under "Annoymous".  I'm pretty sure it was under a channel, and was displaying the channel correctly before this.

![image](https://user-images.githubusercontent.com/64950861/111102179-6fa30a80-8586-11eb-86cb-612f5b587ce7.png)

The component is looking for `claim.signing_channel.canonical_url`, which doesn't exist.

----

However, `canonical_url` exists for the same claim under the Channels Page, so the repost author is displayed correctly there.

**Comment by tzarebczan** [comment]
Maybe --resolve is not passed? It should be there. Maybe it's looking at the reposted claim and not the claim itself...think this broke around the time we made some improvements around reposts from the search page. 

There's also https://github.com/lbryio/lbry-desktop/issues/4563
