### ISSUE TITLE
Content reports (dmca and others)

### ISSUE THREAD

**Issue by e4drcf** [lbryio/lbry-desktop#5676]
**LBRY needs to process content reports**
API is available at [reports.lbry.com](https://reports.lbry.com)

**Additional context**
link with specification of API
https://docs.google.com/spreadsheets/d/1CXUO0b6uU7hCNureMb0F-ruzrtqZyADNjk_JrKmaZzs/edit?usp=sharing

**Comment by kauffj** [comment]
@infinite-persistence this is likely to be assigned to you on Monday. API side ticket is https://github.com/lbryio/internal-apis/issues/1308 and PR is https://github.com/lbryio/internal-apis/issues/1588

**Comment by e4drcf** [comment]
there some discussion under pr, but it haven't been merged into internal-api, we made a different service called Rick.

**Comment by infinite-persistence** [comment]
@e4drcf, when the GUI PR gets approved, should we deploy it or wait until further notice?

**Comment by e4drcf** [comment]
@infinite-persistence sure it can be deployed
