### ISSUE TITLE
[mobile] page cut off on certain claims

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#5680]
See https://odysee.com/@HighImpactFlix:ca/ObamaClintonBushBigPharma:c on mobile 

![image](https://user-images.githubusercontent.com/8120721/111194303-708d6980-8591-11eb-9b9d-ccc964d4707d.png)

**Comment by tzarebczan** [comment]
Pushed up a fix for description issues, but still think they exist on other areas: 
![image](https://user-images.githubusercontent.com/8120721/118523386-13d23a80-b70b-11eb-97a6-70412b107038.png)

**Comment by icehazard** [comment]
Hi, so in the description area of the page, I tried on my browser putting the CSS property 'overflow-wrap: anywhere;' on  the element with the class name of 'card__main-actions', which seems to fix the overflow issue, at least on the video page i tested it on.

**Comment by icehazard** [comment]
issue is that in the comments, there is 1 comment '@celesteplantagenet-york 2 months ago' which is an inline element. These two elements are too long next to each other in mobile view and exceed the width of the parent container.

**Comment by mayeaux** [comment]
Also happens on: https://odysee.com/@timcast:c9/biden-admin-seeks-to-fire-fauci-amid:1 on iOS

**Comment by ElectronEsq** [comment]
I have this issue all the time. Makes the mobile experience pretty poor.
This worked in Chrome Dev Tools, but I've not tried it on a live site as rendered code.

```css
@media only screen and (max-width: 375px) {
.file-page__secondary-content {
    transform: scale(0.8);
    transform-origin: top;
}}
```
Probably not the best approach, but if it works live, might be a good solution for now.
\* That's just for the iPhone X size. Needs calibrating for all sizes that are affected.
