### ISSUE TITLE
pass param for notitication drop down

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#5694]
Can pass the param to apis so that it only returns the relevant types, and actually return data. Right now we limit notifications to 50 so you won't get back any data if it's not in the last 50, but will increase back to 200 once I can finish some testing with larger resolves or we don't have to resolve channels/claims in notifications.

https://github.com/lbryio/internal-apis/commit/237c01715a2f01d30fdb70bec3690701358f45ea

We should group the daily watch ones under "Other". The filter value is "default"

the others are followers, comments, comment_replies and new_content respectively.

**Comment by infinite-persistence** [comment]
I attempted this last week and found some complications, both in behavior and code maintenance.  Sean agreed that it's not worth handling these cases, and expanding back to the larger limit later should be a sufficient fix.

For now, I'll try to group up the _daily watch_ items -- agreed that it's a bit messy being split.

**Comment by tzarebczan** [comment]
We still won't increase the limit past 200 due to other bugs we encountered. Still think this is worth doing, whatever the right way is.
