### ISSUE TITLE
static live stream URL (i.e. odysee.com/@channel/live)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#5698]
This would look up the most recent live stream claim and show the page

Right now channels can just use their channel URL.

**Comment by henk717** [comment]
As a workaround i used a claim called /live which i update and renamed when i did test streams, if you can upload the vod of a stream as a new claim streamers can choose if they want a static URL they always stream to, or a unique URL for that stream.
The biggest downsides to this approach is that it does not count the stream as recent, and it is less intuitive for the user in the current ways the system are setup.
