### ISSUE TITLE
Editing comment stops playback

### ISSUE THREAD

**Issue by dakontiva** [lbryio/lbry-desktop#5702]
**Bug**
Clicking edit comment while the video is playing causes the playback to stop

**To Reproduce**
1. Start playing some video
2. Make a comment
3. Select edit comment
4. Video playback will stop

**Expected behavior**
Video playback should continue even when editing comment

**System Configuration**

```
{
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "desktop": "GNOME",
    "distro": {
      "codename": "groovy",
      "id": "ubuntu",
      "like": "debian",
      "version": "20.10",
      "version_parts": {
        "build_number": "",
        "major": "20",
        "minor": "10"
      }
    },
    "lbrynet_version": "0.88.0",
    "os_release": "5.8.0-45-generic",
    "os_system": "Linux",
    "platform": "Linux-5.8.0-45-generic-x86_64-with-Ubuntu-20.10-groovy",
    "processor": "x86_64",
    "python_version": "3.7.9",
    "version": "0.88.0"
  }
}
```
- LBRY Daemon version: 0.88.0
- LBRY App version: 0.49.5
- LBRY Installation ID: 8s67debqsLbXxRbgNnfYHdnoNzbgbw1Vgjj7iFFsR9dcs942gew7NcQGvEPE87GFrV
- Operating system: Ubuntu 20.10

**Comment by seanyesmunt** [comment]
This is fixed and will be included in the next desktop release (tomorrow or Friday)
