### ISSUE TITLE
Changelog modal should have a max-height

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#5707]
When we have so many items in the changelog, it extends beyond the height of the app, and makes it so you can't upgrade unless you zoom way out, or make your app very tall.

![](https://cdn.discordapp.com/attachments/363087331475062785/822216040246411274/Screenshot_from_2021-03-18_16-12-38.png)

**Comment by tzarebczan** [comment]
TOO MANY CHANGES! SLOW DOWN.
