### ISSUE TITLE
Missing reposts on channel

### ISSUE THREAD

**Issue by fte378** [lbryio/lbry-desktop#5714]
After upgrading to 0.50.1 the reposts of the last days went away in one channel.
The search still reveals them but they are not visible in any view.

**Comment by tzarebczan** [comment]
Can you check your settings to see if you've hidden reposts? If not, please email us at hello@lbry.com with the details.

**Comment by tzarebczan** [comment]
We've found the issue with new reposts and will get a fix out later today.

**Comment by fte378** [comment]
@tzarebczan  Sorry - but the fix did only fix this on lbry.tv.  The desktop client is still affected.

Even new reposts from today are not appearing.
