### ISSUE TITLE
Edit: channel-selector should re-populate with original channel

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#5720]
From Discord:
>_Japhet — Today at 4:28 AM
Was wonding how my video become unlinked from my channel.  I realized that I'd edited the thumbnail and by default, the edit form does not keep the channel name.  The default value of the "channel" field is "Anonymous!"  I suggest changing that to be the channel it's currently on.  (Encountered in 0.50.1 Linux and in Android)._

Steps: 
1. Repost something using `Anonymous`
2. Edit one of your content.  The channel-select is selecting last value (`Anonymous`)

**Comment by tzarebczan** [comment]
Ah, so that's how it happens...

Also happens if channel list is not returned in time and edit is clicked.
