### ISSUE TITLE
bad post menu design (add confirmation on remove)

### ISSUE THREAD

**Issue by Tcll** [lbryio/lbry-desktop#5723]
I'd initially noticed this on odysee before I updated the desktop app:
![Screenshot_2021-03-19_10-35-20](https://user-images.githubusercontent.com/773959/111908961-9e5f2c00-8a31-11eb-92d0-a3d8c7e307ca.png) ![Screenshot_2021-03-21_08-55-12](https://user-images.githubusercontent.com/773959/111908974-b20a9280-8a31-11eb-96b0-1bfe601e5c60.png)
the problem with this layout happens whenever mouse debouncing decides not to work
your post will be deleted before the menu opens

this hasn't affected me until recent because I've been using an old version of the desktop app that didn't have this issue:
![Screenshot_2021-03-21_10-10-42](https://user-images.githubusercontent.com/773959/111909018-e8e0a880-8a31-11eb-998e-949609b8acdb.png)

I didn't think the app would fail to see the poor design choice on odysee

**Comment by tzarebczan** [comment]
Thanks for filing. In what situation does mouse debouncing not work?

**Comment by Tcll** [comment]
> Thanks for filing. In what situation does mouse debouncing not work?

it's basically you click once and the click event registers up to 4 times, or potentially more depending on the button's material-resonance...
debouncing is supposed to detect this driver side and smooth this to just 1 click, since the resonance time-frame is way too fast for a human to repeatedly click within...
but as is often the case with linux, this commonly doesn't work.

it's happened to me on numerous occasions across many mice, and it doesn't matter which button.
for example, in Minecraft, I've had it place 4 blocks in 1 click

so the next best thing we can do is deal with it...
if you don't want to flip the menu order back to the way it was, then you can put up a "are you sure you want to remove" dialog.

personally I like Edit being at the top because when debouncing doesn't work, it only makes it faster to edit
but if I want to delete, I can just cancel the bounced edit and re-open the menu to click delete.

---

currently it's rather annoying to make sure I click only the top dot of the menu as not to have my mouse delete my post

**Comment by tzarebczan** [comment]
We should at least add a confirmation on comment removal - have heard a few complaints about this.  @saltrafael wanna take a shot?

**Comment by Tcll** [comment]
I would've preferred just swapping the menu layout since that's better than just up and removing
(and a smarter layout)

but I won't deny, at least confirmation helps
