### ISSUE TITLE
Purple accent in dark mode isn't consistent with branding colours

### ISSUE THREAD

**Issue by julianchandra** [lbryio/lbry-desktop#5736]
In light mode, the pink accent is consistent with Odysee brand colours.
In dark mode, we are using a purple accent as you hover your mouse over the search/menu -- this seems to clash with overall palette

**Comment by seanyesmunt** [comment]
Most of the colors are derived from this image. Is there something specific you think looks wrong? I'm not sure what you are referencing about the search/menu hover color

<img width="1210" alt="Screen Shot 2021-04-13 at 1 52 41 PM" src="https://user-images.githubusercontent.com/16882830/114598137-8d37c280-9c5f-11eb-8b71-ed10b04e3da8.png">
