### ISSUE TITLE
force videojs player on IOS devices - give speed controls, quality secltion

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#5737]
Re-opening from an old issue that wasn't fully solved. 

Right now you get the native player which is missing the playback rate controls.

**Comment by mayeaux** [comment]
This is what I was referencing. When on iOS just a stock player is used it doesn't look great and it definitely doesn't give the frontend justice. Also doesn't allow for the changing of playback speed.

<img src="https://user-images.githubusercontent.com/7200471/119371129-61741780-bcb6-11eb-9c6e-a87dc9c6991b.jpg" width="250">
<img src="https://user-images.githubusercontent.com/7200471/119371125-6042ea80-bcb6-11eb-8268-d7121816fb50.jpg" width="250">
<img src="https://user-images.githubusercontent.com/7200471/119371120-5faa5400-bcb6-11eb-9fbc-d749656583ad.jpg" width="250">

**Comment by mayeaux** [comment]
I should note that I noticed quality selection still wasn't available on Safari either iOS or desktop, which warrants some investigation.
