### ISSUE TITLE
Daemon exits on load if user has custom downloads path - Windows

### ISSUE THREAD

**Issue by ElectronEsq** [lbryio/lbry-desktop#5759]
## **Bug**
If a new user isn't using the default downloads path, the app fails to load after installing (see below error message).

## **To Reproduce**

1. Change default download path
2. Start application.
3. See error

## **Expected behavior**
Check system defaults for the correct download path.

## **Screenshots**
![image](https://user-images.githubusercontent.com/29914179/112416949-611cd600-8d72-11eb-92d3-20f242d0c403.png)

## **System Configuration**
Windows 10
Latest version of the app.

## **Additional Info**
I am unsure if the user had changed the download path on their system after installing. However, after uninstalling and then reinstalling, the problem continued.

**Comment by tzarebczan** [comment]
This is a bug on the SDK side, thought we should surface the errors to here when possible. Believe there are issues for it, and if not, I'll file.

Added the workaround to the startup troubleshooting steps, thank you!

**Comment by ElectronEsq** [comment]
Sorry. I always get confused which one it should go in.
I had a quick check but didn't find any other issues listed. Maye because I was looking in the wrong place.

**Comment by ElectronEsq** [comment]
I think it's kind of filed here:
https://github.com/lbryio/lbry-sdk/issues/1970#issuecomment-480417753
