### ISSUE TITLE
Theme switcher and LBRY classic dark theme on Odysee

### ISSUE THREAD

**Issue by alojzjakob** [lbryio/lbry-desktop#5769]
**Is your feature request related to a problem? Please describe.**
would be nice to have lbry.tv dark theme available on odysee (call it lbry classic), i like it more than odysee dark.

**Describe the solution you'd like**
a theme switcher submenu instead of light/dark option in menu

**Comment by infinite-persistence** [comment]
> _i like it more than odysee dark._

+1. My eyes have a hard time differentiating dark purple objects over black background.
