### ISSUE TITLE
installed the new LBRY from downloaded .deb, but still get question about upgrade?!?

### ISSUE THREAD

**Issue by baeverjo** [lbryio/lbry-desktop#5784]
I downloaded the new  LBRY_0.50.0.deb file and installed on my very much updated Linux Mint. Computer info:
System:    Kernel: 5.11.0-10.1-liquorix-amd64 x86_64 bits: 64 compiler: N/A 
           Desktop: Cinnamon 4.8.6 wm: muffin dm: LightDM Distro: Linux Mint 20.1 Ulyssa 
           base: Ubuntu 20.04 focal 
Machine:   Type: Laptop System: Packard Bell product: EasyNote TE11HC v: V1.07 serial: <filter> 
           Chassis: type: 10 v: 1.07 serial: <filter> 
           Mobo: Packard Bell model: EG50_HC_HR v: Type2 - Board Version serial: <filter> 
           UEFI [Legacy]: Packard Bell v: 1.07 date: 05/11/2012 
When I restart LBRY it continue to ask me to upgrade the software? 
Look at picture ->
![Screenshot from 2021-03-26 22-40-42-2](https://user-images.githubusercontent.com/64325360/112695649-c3fe9200-8e84-11eb-9056-74d4b5e4f8f3.png)
I am not sure if it will help uninstall and reinstall the deb-file. Since I already have done that.

**Comment by tzarebczan** [comment]
There was a patch after that update...and if your PC received the first one, it does not skip it.

**Comment by baeverjo** [comment]
> There was a patch after that update...and if your PC received the first one, it does not skip it.
I downloaded this .deb 5 minutes ago... So very fast update :+1: Happy when things get fixed so fast :)
