### ISSUE TITLE
symbolic links to ~/Downloads prevents lbry desktop to start

### ISSUE THREAD

**Issue by emanuelserpa** [lbryio/lbry-desktop#5786]
**Bug**
App doesn't start when ~/Downloads is a symbolic link

**To Reproduce**
1. Do a symbolic link of a folder named 'Downloads' on ~

**Expected behavior**
App opens and recognize the ~/Downloads link as a folder

**System Configuration**
Arch Linux, using the flatpak version

Output:
❯ io.lbry.lbry-app
[3 preload-host-spawn-strategy] Running: /app/bin/zypak-helper child - /app/lbry-app/lbry-app --type=zygote
Gtk-Message: 05:35:27.744: Failed to load module "xapp-gtk3-module"
Gtk-Message: 05:35:27.744: Failed to load module "appmenu-gtk-module"
Gtk-Message: 05:35:27.744: Failed to load module "canberra-gtk-module"
Gtk-Message: 05:35:27.744: Failed to load module "appmenu-gtk-module"
Starting SDK
Sandbox listening on port 5278.
Daemon: [93] Failed to execute script cli

Daemon: Traceback (most recent call last):
  File "lbry/extras/cli.py", line 336, in <module>
  File "lbry/extras/cli.py", line 295, in main
  File "lbry/extras/cli.py", line 228, in ensure_directory_exists
  File "pathlib.py", line 1273, in mkdir
FileExistsError: [Errno 17] File exists: '/home/user/Downloads'

**Comment by tzarebczan** [comment]
Sorry to hear. We'll move this to the SDK repo, but can you confirm it breaks in the aur package also?

**Comment by emanuelserpa** [comment]
> Sorry to hear. We'll move this to the SDK repo, but can you confirm it breaks in the aur package also?

Works fine on the AUR package. Seems like Flatpak specific, but I use Telegram and many others that make use of ~/Downloads and works fine.

**Comment by tzarebczan** [comment]
I wonder if the flatpak itself needs special permissions to that folder to read the symlink properly. Not sure how to fix this at this time. Can you open this on https://github.com/flathub/io.lbry.lbry-app and see what else you can find? 

Can we show you some [appreciation](https://lbry.com/faq/appreciation) for the report and effort?
