### ISSUE TITLE
comment notifications (comments only, optional video)

### ISSUE THREAD

**Issue by Tcll** [lbryio/lbry-desktop#5787]
this is kinda a 2 in 1 for both odysee and lbry (easier to write and makes more sense)

---

as I mainly use the lbry appimage for downloading videos
and odysee for notifications only (can't download without playing)

I've not too recently found I I've not been getting notified of all comments made to me

### so I'd like to request 2 things:
- comment notifications in general on the LBRY appimage
- having the ability to be notified of all comments without being notified of videos

the second is not the same as selecting comments only on the view filter
as I'll only be shown a minor skew of comments out of the entire notification history
I'd prefer **the entirety of the notification history** be nothing but comments...
in fact I'd prefer to see the first comment I've ever recieved.

I already get notified of new videos when I click the "Following" list, so I don't need to be alerted of video notifications ;)

---

if you're afraid of notifications directing people away from odysee, don't be...
not everyone wants to open the desktop app to see comment notifications, including me ;)

**Comment by tzarebczan** [comment]
This will most likely come at a later time via Odysee mode in the desktop app. The new filter will work a bit better in a few days, still post processing notification data. Also want to have a dedicated comment area, which is filed under a separate issue. 

Email me your email at tom at lbry.com and we'll enable the comments for you on desktop with our experimental tag.

**Comment by Tcll** [comment]
oh I see
alright, if it's already being worked on, then I have nothing to say :)
other than I'm glad of course XD

but anyways, I can wait, thanks for the offer though, good to know things are already being done to resolve this :+1:
