### ISSUE TITLE
WARNING: KYC is a major security threat.

### ISSUE THREAD

**Issue by Tcll** [lbryio/lbry-desktop#5797]
just to mention why this seemingly out of place issue is a bug report:
not following security is a major bug as LBRY is supposed to be secure.

I understand saving crypto and all, which I'm for
the only crypto worth saving is Monero, and everyone should be using it

but what really bothers me here is a comment from the recent email sent out yesterday:
`LBRY has sought to comply with Know Your Customer`
basically you're saying you don't want to be secure as you want to undermine crypto by tracking everyone (giving them a digital identity tied to an IRL identity), thus supporting the digital dystopia.

I got on LBRY to get away from the dystopia
if you want to bring the dystopia to LBRY, it will surely fail

I've already reposted videos talking about how evil KYC is
if you continue to comply with it, I will start warning people LBRY seeks to become evil.

**Comment by kauffj** [comment]
I hate KYC. It's morally abhorrent. Nonetheless, part of running this company with my name on it means following the law.

No current laws require KYC to use LBRY Desktop, so it won't be added there.
