### ISSUE TITLE
Rewards verification over email

### ISSUE THREAD

**Issue by Tcll** [lbryio/lbry-desktop#5801]
I've recently invited a friend who had issues with the verification process where he says you told him to verify through discord

what happened to the plans to add email verification you said you would add back when I verified my rewards??
I can pull up the old email if you really want me to

currently the only 3 options you have for rewards verification are horrible:
- Discord (why? matrix is better)
- Phone (why?, you guys should know tieing your phone is an insecurity)
- I forget the third option, but it was no better

why don't we have verification through Matrix??
why don't we have verification through email??
why don't we have options that aren't evil??

**Comment by tzarebczan** [comment]
We are looking into other methods right inside the app. The program is heavily abused and cannot be done over email.

There is also verification via credit card.

**Comment by Tcll** [comment]
I see, also thanks for informing on the 3rd option, I'll correct that

hopefully the improvement doesn't require anything too intrusive that's actually possible

I don't use anything evil, and I hope the solution doesn't either
I wish I could use gitlab or gitea for these issues as well
