### ISSUE TITLE
This is how it writes when playing a video - The media could not be loaded, either because the server or network failed or because the format is not supported. -you have so

### ISSUE THREAD

**Issue by esn076** [lbryio/lbry-desktop#5809]
**Bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Configuration**

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Additional context**

**Comment by tzarebczan** [comment]
We're looking into some streaming failures on certain files/regions. Please check back again in a couple hours.
