### ISSUE TITLE
mac code sign issue in 0.50.2

### ISSUE THREAD

**Issue by core-code** [lbryio/lbry-desktop#5821]
all recent releases were fully code-signed by

`LBRY Inc (66QQKUW9TB)`

the new release 0.50.2 is not code signed at all.

is this a legit release or has your account been hacked?

**Comment by tzarebczan** [comment]
It's a known issue we are looking into (and why auto update didn't work).

**Comment by tzarebczan** [comment]
This should be fixed now!
