### ISSUE TITLE
Support creator controlled commenting settings (mainly muted word list for now)

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#5833]
See current list at https://github.com/lbryio/commentron/commit/1822ad2a34524746c98bc021160c44b4fc9412ef#diff-6f94b0243c2495a65018f234fb8fe042534b2804dea30e5631acef38f13ab902R4

- muted words
- min tip to comment (needs super chats)
- commenting enable/disable global 
- slow chat mode (need to add to commentron)

**Comment by kauffj** [comment]
This can be a component in settings. Add a button that says "Add Suggested Words", which will be a list provided to you.

**Comment by infinite-persistence** [comment]
Any desired list of "suggested words"? I found one online, but don't think the list is good.
https://www.cs.cmu.edu/~biglou/resources/bad-words.txt

**Comment by tzarebczan** [comment]
It will start with a blank list and creators add whatever words they want.
