### ISSUE TITLE
Performance investigation

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#5834]
The two tests I'm concerned with are:

- homepage, how long until interactable and above the fold thumbnails loaded
- file pages, how long until interactable, site loaded, and video plays

For direct loads and on navigation after load.

If your investigation reveals tractable issues, begin work. Otherwise, write report.

**Comment by kauffj** [comment]
Next task here is probably back button slowness

**Comment by infinite-persistence** [comment]
Closing this and using "Investigate low Core Web Vitals score from google #6057" instead, since it's the same objective.
