### ISSUE TITLE
Private stream ability (for a creator's patrons)

### ISSUE THREAD

**Issue by julianchandra** [lbryio/lbry-desktop#5843]
Ability for a creator to livestream but it's only accessible via code.

This way a creator can do something special for their patrons or just for select people, or host paid courses and shit.

**Comment by kauffj** [comment]
@julianchandra please do not assign people and instead label consider soon and it will be discussed on the next weekly meeting

**Comment by robd003** [comment]
What about just charging LBC for access rather than limiting it to specific users?

**Comment by tzarebczan** [comment]
The charge case would be something we want to support, but a different use case.

For this one, it's probably enough to have a client-side checking for the password.
