### ISSUE TITLE
Content lists timing out

### ISSUE THREAD

**Issue by Tcll** [lbryio/lbry-desktop#5853]
I've been putting up with this issue over the past 7 days over the past 3 versions of the appimage client
(would've reported sooner, but I kept getting sidetracked) :P

no error is reported in console:
![Screenshot_2021-04-08_15-02-38](https://user-images.githubusercontent.com/773959/114082333-9bf73180-987b-11eb-9a9f-6c29e5a8d8a5.png)

**Comment by tzarebczan** [comment]
Sorry to hear - haven't seen this mentioned anywhere yet. Does it work on the web or non-appimage? Does it work if you leave the page and come back? Does it keep retrying or gets stuck there? Are you following/blocking lots of channels? Send us an email at hello@lbry.com with the log file (see help page) + additional info and we'll take a closer look. 

Once we get more details, we'll file an issue on the lbry-sdk repo responsible for claims if it's indeed an issue there.

**Comment by Tcll** [comment]
I wish you'd work with me for a conclusion before closing the issue :P

odysee works fine, it's just harder to download and doesn't seed re-posted content like I use the appimage for...
