### ISSUE TITLE
Just to do my part.

### ISSUE THREAD

**Issue by Tcll** [lbryio/lbry-desktop#5856]
Despite all of the shortcomings I know I'm pestering you guys with :)
I just want to let you know I'm actually very appreciative of everything you guys have been working so hard to achieve. ;D

So in this brief instance of time
I want to take a deep moment to say

## **Thank you all for all of your hard work!**

I hope you all continue to give us your best
and provide us with the best decentralized video platform possible :+1:

I personally couldn't ask for better
and hope you'll all continue to work to make great strides for the better: :D
- Move from Bitcoin for more freedom with security on Monero
- Move from Microsoft GitHub for more freedom with security on GitLab, Gitea, or IPFS
- Move from Discord for more freedom with security on Matrix
- Move from Google Electron for more security in C/OpenGL

Thank you all for everything!

**Comment by tzarebczan** [comment]
Thanks for the feedback and support, I've passed it onto the team!
