### ISSUE TITLE
Support for tabs in LBRY

### ISSUE THREAD

**Issue by ole-tange** [lbryio/lbry-desktop#5864]
When using YouTube I often have multiple tabs open on YouTube. Often it is different videos, but it could also be looking at peoples' profiles.

LBRY lacks this. It would be really nice if you could have multiple tabs and windows open.

Today I wanted to tip a person for his insightful comment, but it was hard to open his profile and get back to the comment thread. This would have been trivial, if I could open multiple tabs.

**Comment by tzarebczan** [comment]
Thanks for the feedback and opening the issue! We've got a similar request filed here: https://github.com/lbryio/lbry-desktop/issues/1926
