### ISSUE TITLE
 CORS issue from not local domain

### ISSUE THREAD

**Issue by demianortizgutierrez** [lbryio/lbry-desktop#5868]
Hello!

While working on a local environment over localhost i can consume the LBRY API without problem.
When pushing it to my hosting i get an Invalid Host/Domain error and i'm not able to use the app at all due to some CORS error i'm getting.

Is there any way to submit my domain to a white list or something... or should i be updating the code in favor to avoid this issue?
Any help is much appreciated!

Thanks in advance!

**Comment by tzarebczan** [comment]
Hey there, thanks for reaching out and looking into the dev side of things! Right now the web dev setup does not support requests to our production apis. We'll figure out a way to do this via proxy + local dev, but in the meantime the best bet would be to use the desktop mode (i.e. yarn dev) to connect.

**Comment by demianortizgutierrez** [comment]
Thank you so much for your answer, this is a wonder to work with... :)

I will try compiling it into desktop to see if the mods work that way.
Thanks again!
