### ISSUE TITLE
Odysee lbry.tv sunset missing features

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#5901]
- [x] ability to toggle non video/audio content display everywhere (i.e. homepages, categories) - this would enable it in search too
- [ ] ability to toggle reposts
- [x] Download button on content page
- [ ] Tag management page
- [ ] Filtering options on Wild west / tag pages / following? 
- [ ] mature content fixes (https://github.com/lbryio/lbry-desktop/issues/5794)
- [ ] purchase history https://github.com/lbryio/lbry-desktop/issues/5798 
- [ ] "Search only in this language by default" setting to apply site wide (might be strange with EN homepages?)

**Comment by jessopb** [comment]
redirects lbry.tv content to odysee
