### ISSUE TITLE
I can't sync my YouTube videos, I always get the message transfer complete but nothing happens.

### ISSUE THREAD

**Issue by winuxwinfree** [lbryio/lbry-desktop#5906]
Whenever I click on the sync button with YouTube the Transfer Complete message appears because I synced my videos to another channel, but I got the name wrong and deleted the channel and the videos. Now I always hit the add another channel button, put the name of an existing channel or a made up one and it says transfer complete immediately, it doesn't sync anything.

Screenshots: 
https://ibb.co/hskQSdF
This appears automatically, even if I clear the cache... 
https://ibb.co/CnT30cm
https://ibb.co/3p6Xs1M
It says complete transfer but does nothing: 
https://ibb.co/MchYnwK

**Comment by tzarebczan** [comment]
Please send us an email at hello@lbry.com with the details

**Comment by winuxwinfree** [comment]
Not working yet
