### ISSUE TITLE
Chat and hyper chat overlays

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#5918]
Users have been enquiring on how to get their chats (and later hyper chats) up on their stream. Today there is a community solution at https://www.lbrylytics.com/tools-and-extras/livestream-chat-overlays/

I could see some wanting a separate one that just displays hyperchats too

**Comment by belikor** [comment]
tuxfoo is also working on it.

https://odysee.com/@tuxfoo:e/overlays0-0-5:6

https://github.com/tuxfoo/odysee-simple-alerts-connector/releases
