### ISSUE TITLE
Channel Search failure + sometimes stuck at previous results

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#5922]
Open in Incognito so that we are using the same settings.
https://odysee.com/@dr-lorraine-day-md:2?order=new

- [ ] Only 2 videos, both of which contains the word "day".  Typing "day" (or anything) in the channel search bar results in nothing.

----
Aside (minor issue):

- [ ] On another channel where channel-search works, sometimes it is stuck showing the previous results even after I pressed a series of backspaces to clear the search bar.  It depends on the timing of the backspaces, as most of the time it does work (full list revealed).

**Comment by tzarebczan** [comment]
We found a bunch of claims with the wrong state in chainquery / light house....fixing them up over the next few hours so hopefully those are then searchable.

**Comment by infinite-persistence** [comment]
`Close`
- Issue no longer present
