### ISSUE TITLE
Replace recaptcha with hcaptcha

### ISSUE THREAD

**Issue by 9mido** [lbryio/lbry-desktop#5941]
For odysee, replace recaptcha with hcaptcha.

https://www.hcaptcha.com/

**Comment by robd003** [comment]
Three benefits:

1. No Google spy tracking
2. Additional revenue stream for Odysee
3. You actually help solve real world problems when verify users

**Comment by 9mido** [comment]
The only problem is it is a bit tougher / more time consuming to solve than recaptcha if you use the free version. But you could pay for hcaptcha and it does the same thing as recaptcha v3 invisibly and helps with the bounce rate. Additional revenue won't be for the paid version, only the free version. But the privacy benefit alone is worth it the toughness / time consumption.

**Comment by tzarebczan** [comment]
We have an issue filed for this internally as is does not live in this repo. Something we're considering down the road, thank you for the poke!
