### ISSUE TITLE
OG messed up if '$' is in title

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#5951]
https://odysee.com/@hamzatech:9/1-10-coingain:5

- Live site and `dev:web-server`:
    - Order looks incorrect
    - `VARIABLE_HEAD_BEGIN` not in the right place, plus it appeared several times (not in screenshot)
    - ![image](https://user-images.githubusercontent.com/64950861/116046199-6d63be00-a6a5-11eb-858d-8071741aad4f.png)

- Looks ok in `dev:web` (what's the difference with "server" that causing this?):
    - ![image](https://user-images.githubusercontent.com/64950861/116046504-bae02b00-a6a5-11eb-8d51-2dfb31c83a6f.png)

**Comment by marko-lorentz** [comment]
Even though I have not been able to reproduce it on our local machines, I tested a lot of different claim titles to understand when the effect is likely to appear. It seems that having `$"` in the claim's title breaks something that leads to a recursive replacement in `html.js`, but only on the initial load. 

However, can't confirm correlation with RTL.

**Comment by infinite-persistence** [comment]
> _It seems that having $" in the claim's title breaks something that leads to a recursive replacement in html.js, but only on the initial load._

@marko-lorentz, thanks a lot for finding the root-cause.  Looks like there's a parsing problem at the bottom of `getHtml()`

> _Even though I have not been able to reproduce it on our local machines_ 

Need to run `yarn dev:web-server` and `localhost:1337`, instead of the usual `yarn dev`.

> _but only on the initial load._

Yeah, the OG only gets loaded on entry, and not on navigation.
