### ISSUE TITLE
Add video length and size metadata

### ISSUE THREAD

**Issue by wilsonk** [lbryio/lbry-desktop#597]
## The Issue
Consider adding to:
file tiles (at least length?)
file details (both length and size?)

We also have file name, but don't think we need to show that before downloading?

## System Configuration

 

- LBRY Daemon version:
```
 "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "lbrynet_version": "0.15.2",
    "lbryschema_version": "0.0.10",
    "lbryum_version": "3.1.6",
    "os_release": "4.4.0-93-generic",
    "os_system": "Linux",
    "platform": "Linux-4.4.0-93-generic-x86_64-with-Ubuntu-16.04-xenial",
    "processor": "x86_64",
    "python_version": "2.7.12"
```

- LBRY App version: 0.15.1
- LBRY Installation ID:26bru4Kjp3i3VM5KTFVV3ESEkDWEb9CCA2ate4L9XJYTr8PHUK4jPDQqz4JsG73Wfr
- Operating system: Linux (Linux-4.4.0-93-generic-x86_64-with-Ubuntu-16.04-xenial)

## Anything Else

If this information can't be placed on the opening page thumbnails then hopefully it can at least be placed in the video information under the 'published on' information?

**Comment by tzarebczan** [comment]
@wilsonk thanks for the feature suggestion!  Check out https://lbry.io/faq/tips

I'll probably have to open up a complimentary issue on the [lbry protocol](https://github.com/lbryio/lbry-app/issues/) side so that this data is captured during upload.

**Comment by KamilPiekutowski** [comment]
I added another element to the table. I am still learning the code, but I added Length section. Not sure how to access the data for the length.

Here is the photo. Let me know if this what you guys had in mind. 

![screenshot from 2017-09-29 23-26-05](https://user-images.githubusercontent.com/13041293/31042447-e9bf8980-a56d-11e7-9327-e897420f8751.png)

**Comment by kauffj** [comment]
@KamilPiekutowski thanks for your efforts here!

Unfortunately, there's no data to access :/

This will require a much deeper modification to both `lbryschema` and `lbry` before this can be supported.

**Comment by KamilPiekutowski** [comment]
Is there any app architecture documentation or something that would lead to how lbry,lbry-app and lbryschema are connected?

**Comment by btzr-io** [comment]
@KamilPiekutowski I hope you found something useful :slightly_smiling_face: 
https://lbry.io/faq/contributing
https://lbryio.github.io/lbry/cli/

**Comment by KamilPiekutowski** [comment]
How does hex_encoded_003 get generated in test_data.py?
generate_test_data.py ommits it and makes testing fail.
