### ISSUE TITLE
Comments and CommentMenuList issues

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#5970]
If you have multiple channels and made several comments using those channels:

- [ ] (1) In this case there's nothing for the menu-list to do (the other channel is yours too, so not showing "Block | Mute".  Not sure what to do  ... maybe just don't show the menu button at all.
- [ ] (2) The comment-menu-list popup doesn't dismiss when another menu is clicked. 

![image](https://user-images.githubusercontent.com/64950861/116446263-5aa9de80-a889-11eb-8157-05584f93b2e6.png)

**Comment by kauffj** [comment]
I don't think it's necessary for the system to be aware other channels are yours, unless it's extremely easy to do this. If I'm signed into two accounts on Twitter, one can block the other.
