### ISSUE TITLE
notifications marked as read when clicking bell

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#5976]
I could have sworn I've filed this but could not find it.  When I clicked the bell, it marked all notifications after the 11th one as read.  It made the call twice also. 

![image](https://user-images.githubusercontent.com/8120721/116601572-a9db2800-a8f8-11eb-8588-33107240743b.png)

**Comment by tzarebczan** [comment]
Seeing this happen more where all are marked as read (and I definitely haven't read all of them).

**Comment by infinite-persistence** [comment]
- It seems like notifications are dead today, at least for "comments" and "replies".  Had to use a dormant account to get the sample "unseen" data below.
- The data received from `list` is already "read" before clicking the bell.
```JSON
      "is_app_readable": true,
      "is_read": true,  //<--------- ???
      "is_emailed": true,
      "is_device_notified": true,
      "active_at": "2021-06-23T10:37:18Z",
      "created_at": "2021-06-23T10:37:18Z",
      "updated_at": "2021-06-23T10:47:40Z",
      "is_seen": false,  //<--------- haven't clicked
      "is_deleted": false
```
- Other than the double-call, the screenshot looks correct -- it's sending `is_seen` instead of `is_read`.

**Comment by infinite-persistence** [comment]
The "all read" behavior seem to coincide with the notifications parallel-processing change?

**Comment by tzarebczan** [comment]
Yea, it was related to device notification process - there was a bug where it would set it to read if it sent the device notification. Since the device notifications were delayed, I'd only see some stuff as read, and newer stuff would be fine. When we added the multiprocessing, everything was read because it was processed so much faster.

Mark fixed, and now it should be fine! Thanks for pointing me in the right direction..that was silly of me.
