### ISSUE TITLE
Somebody messed up Odysee quotes. 

### ISSUE THREAD

**Issue by JYamihud** [lbryio/lbry-desktop#5984]
**Bug**
Then I use a quote in an article. 
> like this

`> like this`

In the dark more it's the theme is too bright. And with the white text you can't read nothing. Please fix it.

**To Reproduce**
1. Go to https://odysee.com/@blenderdumbass:f/what-if:2
2. Scroll down to where I have quotes 

**Expected behavior**
I should be able to read it. In the bright theme everything is visible. But I want to use the dark theme.

**Screenshots**
![](https://notabug.org/jyamihud/update_manager/raw/master/generalpurposeimages/odysee-theme-bug.png)

**System Configuration**

- LBRY App version: Odysee . com 
- Browser: GNU IceCat
- Operating system: GNU/Linux

**Comment by tzarebczan** [comment]
Thank you for the report!

**Comment by seanyesmunt** [comment]
Thanks for reporting @JYamihud 

fixed with f89f0126177216436f5b69906e16678562d4d477
