### ISSUE TITLE
Allow sending directly to a channel (or content?) address

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#5985]
Modify the `<WalletSend>` component to allow the user to enter a channel handle and/or LBRY URL to allow sending to, instead of just an address.

**Comment by tzarebczan** [comment]
Do you want the SDK to support this or the desktop app to resolve. 

My only concern is for channels that are not yet claimed on YT sync, we don't have a process to transfer extra Lbc outside of tips.

**Comment by saltrafael** [comment]
@tzarebczan should close this?

**Comment by tzarebczan** [comment]
Yep, thanks for the poke!
