### ISSUE TITLE
Audio player suggestions. 

### ISSUE THREAD

**Issue by JYamihud** [lbryio/lbry-desktop#5987]
I see that there was [this](https://github.com/lbryio/lbry-desktop/pull/5897) commit merged. Making it more possible to upload audio. Even tho you could technically upload audio even before that. 

I have a few suggestions to the audio player:

 - **Slim Player**. There is no video. So an entire 16:9 player frame for an audio file is unnecessary. Instead something like a slim thing. Like a strip of audio with a tiny album image on the side. This would be a way better design. Or at least. Make it like so when I embed audio into text posts. 

 - **Download link / button**. I use LBRY Desktop to download videos and audios. But sometimes I want to give my songs for use to somebody else. Who uses only Odysee.com. With video it's easy. You press right mouse button. Then copy the location of the video. It works like this on [this ogg](https://odysee.com/@J.Y.AmihudMusic:c/J.Y.Amihud---Little-Naomi-Full-Album-2020-(-OGG-):9) audio file. But not on [this mp3](https://odysee.com/@J.Y.AmihudMusic:c/Blender-Dumbass:7) audio file. Maybe bringing the old download button from LBRY.TV would be nice.

**Comment by tzarebczan** [comment]
Thanks for opening the issue. You can add these suggestions to: https://github.com/lbryio/lbry-desktop/issues/2757

The download link was covered under a separate discussion and probably not changing from it's current position.
