### ISSUE TITLE
Features from LBRY.TV that ODYSEE needs. 

### ISSUE THREAD

**Issue by JYamihud** [lbryio/lbry-desktop#5988]
Let's look at [this](https://odysee.com/@J.Y.AmihudMusic:c/Blender-Dumbass:7) publication on Odysee. Here is how it looks:

![](https://notabug.org/jyamihud/update_manager/raw/master/generalpurposeimages/odtv-01.png)

Let's compare it to lbry.tv:

![](https://notabug.org/jyamihud/update_manager/raw/master/generalpurposeimages/odtv-02.png)

2 very important features are missing. The Download button and the License. 

# Bring them back, please

A lot of people want to use stuff I make in their videos. And since they don't see those two options they can't download them. Or see what the license is. So they avoid it instead of using it. At least bringing them back would be amazing. 

# Even better design

I often do articles with images. Or other things. That are hosted on the LBRY protocol too. But since I need usually the direct link to the file. I can't use the `lbry://` link. I need an `https://cdn.lbryplayer.xyz/api/v4/streams/free/` link instead. Maybe on text posts on odysee when embedding and image like `![](lbry://@Channel/Image-url)` could be done.  But I need them to work in different software. That doesn't know how to read `lbry://` urls. 

![](https://notabug.org/jyamihud/update_manager/raw/master/generalpurposeimages/odtv-03.png)

My proposal would be like this:
 - **HTTPS link**. Somewhere hidden in the description for power users. So I could embed the files directly into other things. 
 - **License Logo**. In a **visible** spot. Perhaps like a logo of the license. So people would find it immediately. Also add Software Licenses to it. Such as GNU GPL. I upload a few little software packages to the LBRY protocol too. 
 - **Donwload button**. Bring back the normal download button for people who just want to get a copy. And are not interested in embedding it.

**Comment by tzarebczan** [comment]
Thank you for the issue. We have a similar one filed here: https://github.com/lbryio/lbry-desktop/issues/5901 

Some things are removed to reduce complexity for Odysee users. Users who want these features can use the LBRY Desktop app.
