### ISSUE TITLE
facebook on lbry chain?

### ISSUE THREAD

**Issue by captainerd** [lbryio/lbry-desktop#5995]
Im just wondering if there is any possibility that lbry could be used for a facebook alternative social media?

**Comment by JYamihud** [comment]
I  could be used as an alternative to HTTP. Making a whole new, separate networking protocol. And web sites implemented in this way could resemble the functionality of facebook.

**Comment by tzarebczan** [comment]
Not something we will be working on, but do plan to give more prominence to text posts via a feed feature.
