### ISSUE TITLE
Theme color problems

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#5998]
<details>
  <summary>=== Fixed items ===</summary>

- **Odysee Light**
    - [X] Snack invisible.
        - _Closed by #5989_
    - [x] I think the upload progress bar color is always at 100%.
- **Odysee Dark**
    - [x] Snack in the wrong color
        - Orange feels wrong.  Previously, it was green.
    - [x] Nag bar color seems inversed with Light -- too dim in Light, too jarring in Dark.
        - ![image](https://user-images.githubusercontent.com/64950861/117562991-6c835100-b0d5-11eb-9440-18e81c05632c.png)
        - ![image](https://user-images.githubusercontent.com/64950861/117563009-86bd2f00-b0d5-11eb-8a61-ee6561507714.png)
- **Desktop Dark**
    - [x] "Banner" title.
        - ![image](https://user-images.githubusercontent.com/64950861/116858267-b0d3a480-ac30-11eb-9984-3e54a4c5c89f.png)
    - [x] Loading bar
        - ![image](https://user-images.githubusercontent.com/64950861/117775108-bf434100-b26c-11eb-9037-2fd391ebe13a.png)
    - [x] Nag bar text not legible.
        - ![image](https://user-images.githubusercontent.com/64950861/116858351-cf39a000-ac30-11eb-9a46-8b29151ad33c.png)
    - [x] Any error/red text (`error__text`) over the dark body.
        - ![image](https://user-images.githubusercontent.com/64950861/117595238-dc93e480-b172-11eb-8223-5a4c1d95fc23.png)
    - [x] #6006 [- dark theme on LBRY desktop is now blueish?](https://github.com/lbryio/lbry-desktop/issues/6006)
    - [x] Checkbox (or at least the tick mark) is a bit dim; feels like grayed out.
        - ![image](https://user-images.githubusercontent.com/64950861/117594562-e9173d80-b170-11eb-96fd-92c1656cf15f.png)
- **Desktop Light**
    - [x] Invisible nag
        - ![image](https://user-images.githubusercontent.com/64950861/117665776-c408e600-b1d5-11eb-91fd-141df89da5a4.png)  
</details>

- **Others**
    - [ ] Checkbox gap lost (checkbox touching the formfield)
        - Not related to theme, but seem to happen after then theme cleanup?
        - ![image](https://user-images.githubusercontent.com/64950861/117598592-ae1a0780-b17a-11eb-831f-4c8753845066.png)

**Comment by kauffj** [comment]
Please make sure to cover #6006 too

**Comment by tzarebczan** [comment]
Seeing the theme go blue when a modal pops up: 
![image](https://user-images.githubusercontent.com/8120721/118860340-431eae00-b8a9-11eb-94e8-fccf9826bf8c.png)

**Comment by infinite-persistence** [comment]
## Desktop Dark
- [ ] FormField border lost
  - ![image](https://user-images.githubusercontent.com/64950861/119445973-3c3be380-bd60-11eb-8070-9f1d13e7d5af.png)
- [ ] Unread notifications are the same color as the backdrop.  Use another color.

**Comment by saltrafael** [comment]
Not color but leaving it here:

- [ ] Related tabs position:
![](https://i.postimg.cc/mrQcFxLS/image.png)

- [ ] Long names don't fit:
![](https://i.postimg.cc/NMdj1BWR/image.png)

**Comment by infinite-persistence** [comment]
### Close
Created separate issue for remaining non-color related items
`https://github.com/lbryio/lbry-desktop/issues/6290`
