### ISSUE TITLE
4K display + livestreams - display not centered

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#6005]
Xander also noticed and reported this earlier 
![image](https://user-images.githubusercontent.com/8120721/116905976-af44b500-ac0d-11eb-9f40-cd1c1554ee8f.png)

**Comment by saltrafael** [comment]
maybe related: #5940  ?

**Comment by tzarebczan** [comment]
Yes, but it should work outside of a theatre like mode and just be centered better.

**Comment by DispatchCommit** [comment]
This might be fixed now? I don't know who / what fixed it, but they appear centered for me now.
