### ISSUE TITLE
hyperchat send display issues with GIF profiles

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#6010]
On send, it shows a larger placeholder/no first frame:
![image](https://user-images.githubusercontent.com/8120721/116930690-11adad80-ac2e-11eb-9dc5-637719c2360c.png)

On view, you won't see the first frame until you mouse over.

**Comment by infinite-persistence** [comment]
This affects all places where we freeze the GIFs (`FreezeFrameWrapper`). 

Depending on the timing, `FreezeFrameWrapper` won't have a `src` to freeze until the lazy-loader loads the actual `src`.  

Need to delay the freeze effect until the gif has been loaded.  Or revert the lazy-load.
