### ISSUE TITLE
Frontend for account linking

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#6011]
UI side of https://github.com/lbryio/internal-apis/issues/1685#issuecomment-830734698

**Comment by tzarebczan** [comment]
See my other comments in https://github.com/lbryio/lbry-desktop/issues/6001#issue-874691645 which I'll close

**Comment by tzarebczan** [comment]
Issue moved to [OdyseeTeam/odysee-frontend #541](https://github.com/OdyseeTeam/odysee-frontend/issues/541) via [**ZenHub**](https://www.zenhub.com/)
