### ISSUE TITLE
comments only pull last 200

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#6016]
not sure when this broke - maybe with some live stream chat changes? 

See https://odysee.com/@SaltyCracker:a/jeopardy-winner-holds-up-3-fingers:6?lc=ceaf814d0ba927e897f47befa5dc81fbb3a7e1fd04724fa34fc59f344bd53ca2 -  there are 253 comments per the API, but the top shows 200 comments.

Users are clicking their notifications and can't find the missing comments.

**Comment by tzarebczan** [comment]
Turns out we are only returning 200 from the comment server at a time. We'll need to confirm the server can handle threads/etc. 

The goal here would then be to properly paginate comments by calling additional pages. 

https://github.com/lbryio/commentron/blob/bcab958d0c5d039db3e8cf46cdbec51ca9675cfd/commentapi/comment.go#L126

**Comment by infinite-persistence** [comment]
`CLOSE`
Using [#6158 Support Comment Pagination ](https://github.com/lbryio/lbry-desktop/issues/6158)
