### ISSUE TITLE
2 Notification Bugs

### ISSUE THREAD

**Issue by JYamihud** [lbryio/lbry-desktop#6020]
# 1. Multiple Tabs

When I receive a notification. I usually have multiple tabs of Odysee open. I go into the notifications in one of the tabs. And in that tab the number goes to Zero. But in the other tabs the number stays what ever it was. 

I need to then go to every tab and click on the notifications and click on the mark all as read button. To make the tab respond to the changes. 

I use GNU IceCat browser

# Replies give 2 identical notifications

When somebody replies to me on a comment on my publication. I receive 2 notifications. One for the reply. And one for the comment on my publication. But it's the same exact comment. Maybe it could be grouped somehow into one notification. Because I see 2. But I read only 1 comment. Since it's a duplicate notification.

**Comment by tzarebczan** [comment]
Thanks for opening the issue. We don't refresh the notification list in the multiple tab scenario. If you just refresh, this should fix it. The web service only supports new notifications at this time, and not marking as read, we may consider this in the future but that's covered in a different repo. 

The 2nd bug is covered in our notifications repository.
