### ISSUE TITLE
Can't scroll down in certian categories

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#6030]
Since we're appending live streams and potentially when this happens https://github.com/lbryio/lbry-desktop/issues/5795, sometimes you can't infinite scroll - see https://odysee.com/$/news now, or pages with live streams

**Comment by infinite-persistence** [comment]
Hm ... wasn't able to replicate this.  Infinite scroll is still based on the original query's result count, not the appended result's count.  It must be due to something else?

**Comment by tzarebczan** [comment]
I commented on Slack about this. It goes back to the blocking / moderation calls and since I have lots of channels, nothing loads on refresh until those calls completed and new claim searches run. That's a battle for another day...
