### ISSUE TITLE
Option to speed up videos on iOS as well as on mobile browers (e.g. 1.5x etc)

### ISSUE THREAD

**Issue by julianchandra** [lbryio/lbry-desktop#6040]
You can only speed up videos on desktop, but not on the iphone app or in safari on iPad etc.

**Comment by julianchandra** [comment]
You can only speed up videos on desktop, but not on the iphone app or in safari on iPad etc.

**Comment by tzarebczan** [comment]
This is filed under https://github.com/lbryio/lbry-desktop/issues/5737 - will add this to title also.
