### ISSUE TITLE
Can't Uninstall LBRY Desktop on WINDOWS

### ISSUE THREAD

**Issue by Aninuscsalas** [lbryio/lbry-desktop#6046]
I have unistalled the latest version (0.50.2) but lbry still starts!
It is not in programs but still starts at startup and runs in the backround.(But i cant open it)

I cannot provide more info because the program is uninstalled.

**Comment by tzarebczan** [comment]
Sorry to hear. Can you check if you have other versions of it installed also? You can delete the LBRY folder in program files if not and disable the startup option to remove it manually.

You can also try reinstalling and uninstalling again. 

We'll confirm that it does uninstall cleanly.
