### ISSUE TITLE
Readme link 404s

### ISSUE THREAD

**Issue by mayeaux** [lbryio/lbry-desktop#6058]
![Screen Shot 2021-05-12 at 20 40 08](https://user-images.githubusercontent.com/7200471/118027489-46beac00-b362-11eb-9323-32a9cf9f1ec4.jpg)

Currently in this section of the readme, when you click on the `web server we use in production` link, it leads to a URL which no longer exists and 404s. I'm poking around the source and will submit a PR if I see where the correct path would be.

https://github.com/lbryio/lbry-desktop/blob/master/src/platforms/web/server.js

**Comment by DispatchCommit** [comment]
Should be this now: https://github.com/lbryio/lbry-desktop/blob/master/web/index.js
