### ISSUE TITLE
Livestream viewer counts come from sockety now

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbry-desktop#6059]
The UI element should be adjusted on that type of message. 

![Screen Shot 2021-05-10 at 10 36 47 PM](https://user-images.githubusercontent.com/3402064/118035105-c6d01c00-b338-11eb-9ce2-430af1df7c32.png)

See the message coming in on the websocket. 

We no longer need to connect to the other websocket now @DispatchCommit

**Comment by lyoshenka** [comment]
this is done
