### ISSUE TITLE
Comment overhaul — decentralised commenting and liking infrastructure

### ISSUE THREAD

**Issue by erkinalp** [lbryio/lbry-desktop#6062]
**Is your feature request related to a problem? Please describe.**
The current centralised comment infrastructure is not sustainable. Therefore I put forward my new comment system proposal:

**Describe the solution you'd like**

1. Ephemeral comments

This is the kind of comments that will only be visible to people that view that content at the time the comment is sent. (requires background connection while viewing content, and this will pave the groundwork for decentralised livestreaming too: treat a livestream as a combination of a real-time published ephemeral claim and its persistent archival copy). Ephemeral comments will not allow payment to be attached.

2. Payment attached comments

This will be the only type of comment that will persist in this new comment system. Each commentator will need to stake OR tip to uploader at least as much as the uploader's stake to publish a persistent comment. Likes and dislikes will be similarly attached to a tip. The transaction structure for payment attached comments should be designed to allow for batch sending multiple comments from unrelated authors in a single block.

**Describe alternatives you've considered**

Only allowing for payment attached comments.

**Comment by tzarebczan** [comment]
Thanks for the issue! We don't plan to do #1 anytime soon.

#2 is already possible on odysee.com, and will be coming to the next desktop app.
