### ISSUE TITLE
Update all Icon components to use consts and add titles

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#607]
#555 switches the `Icon` component to support constants rather than strings.

Additionally, it's worth looking at whether additional icons should have title properties while doing this.

**Comment by liamcardenas** [comment]
Icons should definitely have titles, whoever does this, please add them if they are not already there.

**Comment by alyssaoc** [comment]
@seanyesmunt find any outstanding find/replace and close

**Comment by seanyesmunt** [comment]
All icons use constants now.
