### ISSUE TITLE
sign up / in bug on master + desktop app

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#6071]
Can't focus into sign up/ sign in fields

**Comment by infinite-persistence** [comment]
When signing up in Desktop, just enable the fields and rename `lbry.tv`, or do something else?

- `An account with lbry.tv allows you...`
- `Join lbry.tv`

For the uninitiated Desktop-only user, it feels odd to suddenly see the word "Odysee" (can't co-relate, unlike "lbry.tv" which says "this is the web counterpart")

**Comment by infinite-persistence** [comment]
We also don't have the Odysee .env config variables, strings and logo in this branch, so it'll be somewhat hardcoded in the component.

**Comment by jessopb** [comment]
kept it at lbry.tv but added IS_WEB to the disable.
