### ISSUE TITLE
Transaction List - categorize and fix amount for abandon transactions

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#608]
## The Issue
Currently, a claim or channel abandoning transaction shows as a "Spend" and only displays the fee (twice).  It should be possible to determine when a transaction is an abandon and show the reclaimed LBC (positive) as the Amount.  The claim name should also be shown (even though it's abandoned - it will go to a blank claim) 

Opened https://github.com/lbryio/lbry/issues/946 on the lbry side - this is where the fix/enhancement needs to occur. After we have the amount/data correctly, categorize on the app side. 

### Expected behaviour
Abandon tx should be categorized as such and show amount of deposit returned

### Actual behaviour
Abandon tx treated as a spend and shows fee as amount - can't tell how many credits came back to the wallet. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
@hackrush01 good one for you?

**Comment by tzarebczan** [comment]
![abandon](https://user-images.githubusercontent.com/8120721/31454386-4953468e-ae83-11e7-9b47-3914f49b4183.JPG)

**Comment by tzarebczan** [comment]
Issue moved to [lbryio/lbry #946](https://github.com/lbryio/lbry/issues/946) via [**ZenHub**](https://www.zenhub.com/)

**Comment by kauffj** [comment]
Blocked by https://github.com/lbryio/lbryum/pull/159

**Comment by kauffj** [comment]
App will need to use new `balance_delta` field provided by LBRY API.

**Comment by tzarebczan** [comment]
@kauffj what terminology should we use to categorize these in the tx list/filter? Abandon? Revoke? Delete?  

This applies to tips/supports/claims/channels that are abandoned.

**Comment by kauffj** [comment]
Not delete, since this is mildly erroneous (nothing is ever deleted from the blockchain).

I think abandon (abandoned?) is good.

**Comment by kauffj** [comment]
Revoke is also good though.

**Comment by lyoshenka** [comment]
This is waiting on daemon 0.19

**Comment by tzarebczan** [comment]
Reopening
@daovist  - Please add this to the filter dropdown on the transaction history page and ensure that the export feature works with it as well.
