### ISSUE TITLE
Notifications: Reward Approval Prompt

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbry-desktop#6091]
```go
Device: deviceNotification{
	Title:          "A Welcome 🎁",
	Text:           "Receive free credits for using LBRY",
	Type:           "reward",
	Target:         "lbry://?rewards",
	AnalyticsLabel: "reward",
},
```

Let me know if specific information is needed for this. It is sent to users 3 days after signing up that have not gotten rewards approved.

**Comment by tzarebczan** [comment]
Added in https://github.com/lbryio/lbry-desktop/commit/b8c5a0ed2926d87872cfa02ec764bc14afc1f560
