### ISSUE TITLE
Channel Create:  Sanitize URL-based thumbnail like in Claim Create

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#6097]
<sub>Original:  [#4481 Issues with new Channel Creation page](https://github.com/lbryio/lbry-desktop/issues/4481) </sub>

The thumbnail-uploader in the Channel Creation page allows URL-based thumbnails, but doesn't check if the URL is valid.  We currently do that for Claim thumbnails, so I think the same method can be repeated here.

Not sure if we current crawl Channel claims or not, but a bad thumbnail would lower the score / make it look bad.

**Comment by tzarebczan** [comment]
Ran into this also, would be nice to get the connected PR in. I'll re-test the recent changes again soon.
