### ISSUE TITLE
To post gifs and stickers in comments

### ISSUE THREAD

**Issue by julianchandra** [lbryio/lbry-desktop#6099]
The gifs from https://giphy.com/ are great.
Also the sticker sets you can get from wechat and whatsapp are excellent.
Would be nice to post this sort of stuff in comments

**Comment by tzarebczan** [comment]
FYI, you also wanted a restriction for higher-level accounts to post images which is in effect.

**Comment by kauffj** [comment]
If we're going in this direction we should explore ingesting them into LBRY itself

**Comment by julianchandra** [comment]
Gifs and stickers are pretty SFW though vs the images
