### ISSUE TITLE
"Watched" overlay for videos you've already seen

### ISSUE THREAD

**Issue by Victor239** [lbryio/lbry-desktop#6100]
**Is your feature request related to a problem? Please describe.**
It's a simple Quality of Life feature for keeping track of what videos you've already seen, which helps especially when going through a channel's videos. 

**Describe the solution you'd like**
Similar UI to how it is in a YouTube-specific app I use (FreeTube):
![](https://i.imgur.com/JZOA1FD.png)

**Describe alternatives you've considered**
N/A

**Additional context**
The 'star' button is also useful because it allows users to add videos to a personal playlist #1982.

**Comment by tzarebczan** [comment]
Thanks for opening the issue. This is on our radar and logged under https://github.com/lbryio/lbry-desktop/issues/3614
