### ISSUE TITLE
Wallet: "Tips" shown as "Support" for anonymous claims

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#6103]
I have an anonymous Post and received some tips for it. In the Wallet Page, it shows up as "Support" and the button is "Abandon Support".  I think it should be "Unlock Tips".

![image](https://user-images.githubusercontent.com/64950861/119067840-88f88500-ba15-11eb-83ac-ef50d5e7381a.png)

On the claim's page itself, it does show "Unlock Tips" correctly.

**Comment by tzarebczan** [comment]
Does it fix itself after a refresh? There's a known issue on the SDK side where this can happen randomly. This designation comes from the SDK, so let me know what you see there an I can try to reproduce.

**Comment by infinite-persistence** [comment]
Refresh doesn't help for that existing item.
But I couldn't reproduce on a new Post -- must be the same random SDK bug.
