### ISSUE TITLE
WARNING: Malicious services detected on Odysee

### ISSUE THREAD

**Issue by Tcll** [lbryio/lbry-desktop#6105]
![Screenshot_2021-05-21_10-52-07](https://user-images.githubusercontent.com/773959/119156830-99632c80-ba22-11eb-91fc-a44679994357.png)

Google should be evaded where possible.

**Comment by tzarebczan** [comment]
Odysee is a centralized service that may run Google ads on some content. Google analytics are not used unless you are on a live stream, which will be removed soon. If you are using Chrome, try on another browser if you see something similar.

**Comment by Tcll** [comment]
looks like soon can't come soon enough:
![odysee](https://user-images.githubusercontent.com/773959/143449840-f33fffb0-fe0c-4284-a066-b50e7e7c80e0.png)

malicious domains still used on odysee.

**Comment by tzarebczan** [comment]
Free to block em 😜

**Comment by Tcll** [comment]
I don't see how that helps anyone :/

if you're gonna sell us all to google with a big :middle_finger: to our faces
you could at least be more clear about telling us you don't care about us.

but I guess that doesn't matter to you either
you flushed your core values down the toilet when you smelled that google money
and that E privacy rating means absolutely nothing to you
[![](https://shields.tosdr.org/en_2391.svg)](https://tosdr.org/en/service/2391)

how do you expect to grow when you're actively saying "F you" to your user-base??

come on man >.<

**Comment by joell29** [comment]
They, Odysee/LBRY, are still decentralized which I believe is rather their core values and not taking some Google ad revenue to support building out a video hosting platform of their own, a very very expensive undertaking with very little profit especially in the early days of development.

Be civil and maybe they will address your concerns. Else move on if you still have a problem.

**Comment by Tcll** [comment]
@joell29 this issue has gone on since at least January/February of 2021 and they've been addressed numerous times including email about the issue

yes the LBRY app still holds their core values *for now anyways*, but how long until that turns around
given you're now forced to have at least 2 social media accounts to activate rewards.

if they truly cared, this wouldn't've gone on for over a year, nor would the malice be getting worse
Discord is bad, but for some reason they still activate rewards through it, despite how insecure it is
not to mention how Bitcoin (LBC) is a social credit system

why should I have to give up my freedom to watch what used to be good go down the drain into malice
I'll bet they haven't even set up a self-hosted GiTea server yet and are still forcing you to give up your freedom on here.

all of this stuff has been addressed numerous times, and is only getting worse.
how many more years do I have to remain civil while they shove the platform down the toilet??

when I start seeing the removal of malware on the platform, I'll start becoming more civil
but if they're gonna enforce more malware (like activating rewards with social credit systems like Discord, Facebook, Twitter, or a bank account) then yeah I'll continue doing what I'm doing and warning how Odysee is becoming YouTube with the malicious social credit tracking.

I'm sick of addressing the issues if I'm going to be ignored.
