### ISSUE TITLE
Channel description with HTML

### ISSUE THREAD

**Issue by AlguienSama** [lbryio/lbry-desktop#6109]
**Bug**
Unable to see channel description with html code on desktop. In the mobile app is a raw code

**To Reproduce**
Set channel description with tags HTML

**Expected behavior**
See an html structure maybe

**Screenshots**
![image](https://user-images.githubusercontent.com/46720729/119279269-e6b1ea80-bc2a-11eb-9b44-3f9e4016507f.png)
![image](https://user-images.githubusercontent.com/46720729/119279323-41e3dd00-bc2b-11eb-8c9a-9d4f30ad6df4.png)

**Comment by tzarebczan** [comment]
We don't support HTML in descriptions, only Markdown syntax.
