### ISSUE TITLE
Channel avatars displayed in side menu

### ISSUE THREAD

**Issue by julianchandra** [lbryio/lbry-desktop#6111]
Can we include the avatars next to the channel name?

![image](https://user-images.githubusercontent.com/67612037/119292633-e5bd9f00-bca4-11eb-8641-a5509e7935ae.png)

**Comment by tzarebczan** [comment]
Duplicate of https://github.com/lbryio/lbry-desktop/issues/4512, closing so it's bumped up.

**Comment by tzarebczan** [comment]
This is now live
