### ISSUE TITLE
LBRY Desktop Upload Is Broken

### ISSUE THREAD

**Issue by bypiffa** [lbryio/lbry-desktop#6115]
I'm using the LBRY Desktop app too upload the recording of the Stream I had on Odysee. It's 5 hour long stream. And the file is 13 GB, more or Less. Odysee didn't let me upload it, since it's too big. So I'm using the LBRY app. 

 - **Confirmed before uploaded.** It's already confirmed. But the file is apparently still uploading. Since my Internet Upload Usage is high. If I go to the video player from the LBRY Desktop, I see the video. But it's probably playing the local file. In Odysee it gives errors. Apparently the file is not uploaded yet. But already confirmed. Which is confusing. Especially for the people who want to watch it via Odysee.
 - **No Upload Status Bar**. If it's still uploading the file. I don't have any status bar. Or any indication to know when it's finished uploading and when the video will be ready to watch. Please add some UI so I would know what's even going on. 

Few fix ideas:

 - Add a status bar on Odysee so the viewers that want to see the video would know that it's not ready yet. And when it's ready.
 - Add a status bar in the app. So I would know where is it in the uploading process.
 - Add a setting to chose whether I want to confirm before or after the uploading is finished.

**Comment by tzarebczan** [comment]
Sorry for the trouble. There should be a progress indicator as soon as you upload, but we don't show it anywhere else. I believe there's another issue to improve this already. 

There's an issue filed for web / desktop users to alert them if the file isn't completed. If the file is web optimized, it would play before fully uploaded. 

There's also a known bug with files over 10gb which causes them not to fully upload...a fix is in progress. You'd know if you ran into it if the file still doesn't play after leaving the app open for some time. Shoot us an email at hello@lbry.com with the log files to confirm too. 

It's not possible to confirm after upload via the desktop application or SDK at this time.
