### ISSUE TITLE
Sometimes cloudflare caches bad js files in some regions, requires rebuild

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#6117]
This came up again recently over the weekend, and has plagued us every few weeks. Most notably, this happened to the Quebec region a few months ago which was a larger outage. Otherwise, it seems to happens in specific regions where cloudflare caches some bad data - i.e. a bad / cut off JS file that results in a white screen on odysee.com

The solution is to push up a dummy change which forces a rebuild. 

Maybe we can setup a tool to detect this and redploy - or re-deploy every few hours (which may lead to making this happen more often?). 

Don't expect us to look into this right away, but filing for awareness.

**Comment by DispatchCommit** [comment]
Part of the deployment script is an API call to CF to cache clear. This happens after build completes (regardless of if build is successful).

Instead of cache clearing on CF, we could modify webpack to hash build files and then we would never need to even think about cache status.
