### ISSUE TITLE
Creator Settings: beyond "Muted Words"

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#6119]
Continuation of [#5833 Support creator controlled commenting settings (mainly muted word list for now) ](https://github.com/lbryio/lbry-desktop/issues/5833);  mostly just reminders of things to take care of.

- [ ] (Tom) for the comment tip setting, I think the intention was to force all comments to have tips in order to be posted - which would be an anti spam mechanism. That should be made clearer and ensure tiger5226 enforces. That would apply to hyperchats as well. So that setting is more global and forces tips, whereas the other is a min when a tip is used.
- [x] (Tom) anyone with `comments-disabled` channel tag should have setting defaulted to 0 comments enabled
  - In my previous discussion with Mark, we think this should just be removed.  Anyway, we can re-decide this when `setting.CommentsEnabled` is implemented.
- [ ] (KP) Handle LBC vs. satoshi changes
  - There was back-and-forth about where the satoshi-conversion should take place.  We've decided to do this in the app.
- [ ] (KP) Debounce numerical controls
  - Currently, only the "muted words" tag component is being debounced. Any numerical control-change would result in many `setting.Update` calls.

**Comment by tzarebczan** [comment]
Took care of #2 here. 

We don't have the ability to set comments disabled on a per claim level, that's filed on commentron. We did used to allow this with the experimental tag.

**Comment by tzarebczan** [comment]
We can add slow mode setting - has been requested by 2 large creators.

**Comment by kauffj** [comment]
@tzarebczan will update this ticket and comment before it is workable.

**Comment by infinite-persistence** [comment]
Notes:
"Min tip" depends on `[lbryio/commentron] Api to tell UI what properties a channel has (#54)`
