### ISSUE TITLE
Download button doesn't create a file, if all blobs already downloaded.

### ISSUE THREAD

**Issue by keikari** [lbryio/lbry-desktop#6133]
**Bug**
Clicking "download icon" does nothing, if all the blobs of the file are downloaded. 
Can't see any "get" api calls in "network" tab. 

**To Reproduce**
1. Download all the blobs of some video, but don't create the actual file from them.
2. Go to the video's page and click "download button". 
3. Nothing happens.

**Expected behavior**
When clicking "download button" of the file which I have all the blobs of. The file should get created in the download directory.

**System Configuration**

- LBRY Daemon version: 0.92.0
- LBRY App version: 0.50.3-rc.1
- LBRY Installation ID: 6fCyyi4wTNGME7AGM8jTf9L8Hb1eBqsdBVCQeDqpY7vb3AfrcRtjtM8MGM4bAoq7px
- Operating system: Linux

**Comment by Ruk33** [comment]
Hello @keikari , I'm not sure how can I `download all the blobs of some video`. I tried watching a video fully, then clicking on download and it creates the file just fine. Could you elaborate on how to reproduce this issue please? Thanks!

**Comment by keikari** [comment]
Seems to be working now here too.  
(I think watching video fully, and then clicking download-btn, didn't do the `get` call that created file in the past.)
