### ISSUE TITLE
Simple static page for downtime on web

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#6136]
Add a simple switch for setting the site to serve a static downtime page with a custom message.

When the switch is flipped, the site serves a single HTML page with a message that can be injected into it. No API or external dependencies.

**Comment by kauffj** [comment]
@lyoshenka need to discuss proper design for this with you

**Comment by lyoshenka** [comment]
which site is this for, and how early in the stack do you want the page to be?

the design depends on which pieces are "behind" the page

**Comment by tzarebczan** [comment]
Odysee.com

use cases: 
- if we know something is totally down, we'd put up this page
- upgrades across sdks/hubs
- api upgrades/migrations
