### ISSUE TITLE
Filter Out Channels/Videos That Don't Match Selected Language

### ISSUE THREAD

**Issue by ourichermath** [lbryio/lbry-desktop#6137]
Under Settings, I've got my language set to English and the "Search only in this language by default" checked.  Yet, when browsing channels/videos, I see things in other languages.  If someone's set a specific language and checked that box, things not in that language should be filtered out of browsing, too.

**Comment by tzarebczan** [comment]
Thank for filing. We have some known bugs around this. Can you give us an example of where you are it and which content? 

If the content doesn't have a language set, we still show it under EN also.

**Comment by ourichermath** [comment]
In the LBRY app under Discover, I see quite a few videos in some Asian language (I'm assuming some form of Chinese) Spanish and French.  Some current examples from Discover sorted by New:

https://open.lbry.com/@Informaci%C3%B3n.:b/Virus:e
https://open.lbry.com/@JUAVIMAX:0/Bajo-Bandera-Falsa-EXCELENTE-DOCUMENTAL-sobre-el-11-de-setiembre-2001(Unter-falscher-Flagge)-1-:0
https://open.lbry.com/@Maskahiphop:8/Instinto-de-supervivencia-(Pelicula-completa)_360P:b
https://open.lbry.com/@jimakudaio:9/Sucharit-Bhakdi-Vaccine-Appeal:7
https://open.lbry.com/@RedPillPusher:3/teteaparkrp:4
https://open.lbry.com/@untungbatutimbul:c/mega888-dr-fortuno-hantaran-5-hasilnya:e

There are just tons of these there.

On the Odysee web site in my Brave browser, I see quite a bit of Asian, Spanish, French and Russian in Wild West (I was seeing these in other categories, but they're currently not showing there).  Some current examples:

https://odysee.com/@Monk%27s:e/kramericast18:1
https://odysee.com/@RadioLoupDi:9/Le-JournaLoup-79:4
https://odysee.com/@CallOfDutyClips:74/calculo:6
https://odysee.com/@GTAVClips:7/hab-bmx:9
https://odysee.com/@BboySendo:5/BITCOIN-GRATIS-RUBLOS-ADBTC:5
https://odysee.com/@BboySendo:5/ALIENWORLDS-NEWS:8

etc., etc..  I don't know what's actually in these things since I'd never view them (as I can't read the descriptions).

**Comment by tzarebczan** [comment]
Thanks for the additional info! We're not currently passing to the discover / wild west page and we have that covered under https://github.com/lbryio/lbry-desktop/issues/6031. Added a tag so we take a look at it soon.
