### ISSUE TITLE
Prevention of CORS makes mobile development testing more difficult (Allow CORS from *.ngrok.io?)

### ISSUE THREAD

**Issue by mayeaux** [lbryio/lbry-desktop#6146]
To test local software across different devices, there is a need to access the site easily on mobile locally

A great tool to accomplish this is [ngrok](https://ngrok.com/), which allows us to access the site via a publicly accessible url while pointed at our local server

The issue arises when we try and make a request to the api.lbry.com API server. Since CORS is disallowed, the browser will block the request.

I tried a couple different proxy server solutions but they ran into trouble with AJAX requests and relative file paths.

On desktop this can easily be prevented by using an Extension to send preflight data allowing CORS in the request. However, on mobile (iOS) no such solution is available in my research.

Possible solutions:

Per this answer it seems you could use a different app as a VPN, and configure it to point to the ip of your local server, though it requires a bit of configuration and is not ideal.

https://apple.stackexchange.com/a/383264/135185

Alternatively, and my suggestion, would be to allow CORS as a wildcard for ngrok subdomains. Example: https://b5722875d8d1.ngrok.io

This would allow a developer to boot the webserver locally, fire up ngrok pointed towards the local http port, and then access the ngrok url provided to test the application natively on the developer's local device

**Comment by tzarebczan** [comment]
We will look at making a static ngrok subdomain that can be whitelisted.

**Comment by ElectronEsq** [comment]
We now also have **CORS** issues on [LBRYnomics](https://lbrynomics.com/sync/).
Could we also get a whitelisting to get the YouTube Sync stats back?
```cmd
(index):1 Access to XMLHttpRequest at 'https://api.lbry.com/yt/queue_status' from origin 'https://lbrynomics.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
![image](https://user-images.githubusercontent.com/29914179/120888858-f8898980-c63d-11eb-8b7f-e93082571568.png)

**Comment by mayeaux** [comment]
@tzarebczan Would be the person to ask in this case , @ElectronEsq . I'm going to close this ticket in the meantime because the original issue was addressed.
