### ISSUE TITLE
2FA for account security not available

### ISSUE THREAD

**Issue by 7astro7** [lbryio/lbry-desktop#6155]
**Is your feature request related to a problem? Please describe.**
2-factor authentication would make user accounts more secure and it's not currently an available option 

**Describe the solution you'd like**
An option within settings to 
1. enable 2fa
2. if 2fa is enabled, option to use a third-party authenticator application like duo https://github.com/duosecurity/duo_python to add a second authentication factor. using a QR code to register a device with the third-party authenticator would be a convenient way to set this up. maybe a quicker yet viable solution would be requiring use of a magic link when 2fa is turned on
3. the "Account Password" section in settings could be changed to "Account Security". keeping "Account Security" ("Account Password") setting where it is now, one the first settings users can change, rather than moving it to advanced settings would be helpful 
4. **Recovery options** including fallback SMS number, recovery codes, recovery tokens: recovery options along the lines of GitHub's would work

**Describe alternatives you've considered**
I've explored whether it's possible to always authenticate via magic link and never with a password but there doesn't seem to be. There's no alternative to an additional factor for authentication in general that I'm aware of 

**Additional context**
odysee.com, lbry.tv, LBRY desktop all appear to not have any 2fa option and it would be beneficial for both users and the LBRY platform generally to have it

**Comment by tzarebczan** [comment]
Thanks for filing. We are tracking this on our authentication repository but don't have an ETA for it at this time. 

If you want us to remove your account password so it forces email login, shoot us an email at hello@lbry.com with the details and reference this post.

**Comment by 7astro7** [comment]
Alright, thanks!
