### ISSUE TITLE
Moonpay in Desktop no longer works

### ISSUE THREAD

**Issue by ole-tange** [lbryio/lbry-desktop#6161]
**To Reproduce**
1. Go to /$/wallet
2. Click on Buy
3. Select Denmark
3. Click continue

The system is now waiting infinitely.

**Expected behavior**

I have earlier bought LBC thru Moonpay thru the app. I had expected I could do this again.

**System Configuration**

About
App	0.50.2 - 
Changelog
Daemon (lbrynet)	0.92.0
Connected Email	none ￼
set email
Reward Eligible	No
Platform	Linux (Linux-5.4.0-72-generic-x86_64-with-Ubuntu-20.04-focal)
Installation ID	AMo4bUQT7W5cpb6DdFDuHB7DrRmVtu353BKmdrehYZrUxtTM8BPEHWaN1LVHgJFepp

~~~
{
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "desktop": "KDE",
    "distro": {
      "codename": "focal",
      "id": "ubuntu",
      "like": "debian",
      "version": "20.04",
      "version_parts": {
        "build_number": "",
        "major": "20",
        "minor": "04"
      }
    },
    "lbrynet_version": "0.92.0",
    "os_release": "5.4.0-72-generic",
    "os_system": "Linux",
    "platform": "Linux-5.4.0-72-generic-x86_64-with-Ubuntu-20.04-focal",
    "processor": "x86_64",
    "python_version": "3.7.10",
    "version": "0.92.0"
  }
}
~~~

**Comment by tzarebczan** [comment]
Thanks for filing. This is covered under https://github.com/lbryio/lbry-desktop/issues/5097 . Right now we'd suggest using lbry.tv or odysee.com to proceed.
