### ISSUE TITLE
Ability to sort based on the initial stake alone

### ISSUE THREAD

**Issue by erkinalp** [lbryio/lbry-desktop#6162]
**Describe the solution you'd like**
Ability to sort the search based on the initial stake alone, in addition to the current options. That way, we would be able to find the content that are promoted by their original creator.

(Maybe under the name "Most self-promoted")

**Comment by tzarebczan** [comment]
I don't think we'll be adding this option as the SDK does not track self supports separately from the total support amount and effective amount (both of which are total sums). If there's a need for this tracking in the future, we may re-consider it.
