### ISSUE TITLE
Support in-app based social verification

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#6163]
@e4drcf will provide endpoint details

https://github.com/lbryio/lbry-verification.go/pull/4/files

**Comment by kauffj** [comment]
This will deprecate https://verify.lbry.com/

**Comment by kauffj** [comment]
Discord verification is no longer a step. User is presented with option for social media verification. User must link two accounts.

Endpoints and the necessary feedback systems for the status of the verification process may be missing. Please raise with internal API team any changes required to support this flow end-to-end.

**Comment by tzarebczan** [comment]
Issue moved to [OdyseeTeam/odysee-frontend #30](https://github.com/OdyseeTeam/odysee-frontend/issues/30) via [**ZenHub**](https://www.zenhub.com/)
