### ISSUE TITLE
channel subscriptions layout, mgmt

### ISSUE THREAD

**Issue by reillysmith** [lbryio/lbry-desktop#618]
## The Issue
Subscriptions in the LBRY app: after this feature is added, how should they display?

### Expected behaviour
Tell us what should happen

**Display**
- Subscribe button on all videos connected to a Channel page, as well as on Channel pages themselves.
- Homepage: Up to 10 rows can be cached on homepage Subscriptions; >10 == "Load more..." button
--> how is load more chosen? by channel with content in latest block?

**Subscription Settings**
- Manage your top 10 (+1)* channel rows
- Manage homepage global row length: 5, 10, 15, or 20 latest videos.
- An *11th row exception: a master feed of latest by block height, feeding from all subscriptions
- Tab to switch between one subscription view and the main LBRY curated view
--> introduce Subscription pages? For example, I have 10 rows of content from gaming channels, or gaming-comedy, in a saved-feed. But i could tab to another subscription state.

**Comment by liamcardenas** [comment]
I guess I didn't include a subscriptions redesign page, but since the subscription page is currently within the homepage, this should be taken into consideration here https://github.com/lbryio/lbry-app/issues/849

**Comment by tzarebczan** [comment]
The subscriptions approach has been reengineered and covered in newly opened issues.
