### ISSUE TITLE
Nestled Content

### ISSUE THREAD

**Issue by reillysmith** [lbryio/lbry-desktop#619]
## The Issue
Feature or curate content that doesn't belong to your channel
### Steps to reproduce
1. N/A

### Expected behaviour
Add a piece of content to your channel/playlists in your channel, but the owner of it is still the original URL bidder. So if someone pays to watch the content from @channelA that belongs to @channelB, @channelB still receives the revenue as if it were on their channel.

This enables curation to thrive, enables custom playlists to be shared in a decentralized way, and it also enables thing like, Netflix master channel hosts content from a show-only channel, e.g. @OrangeIsTheNewBlack, and they nestle it under their master channel.

These show up in feeds to the channel as subscription items, as if the channel published it themselves.

These are Supports, but they are supports spent directly from a channel-bound sender address.

**Comment by liamcardenas** [comment]
@tzarebczan even if this feature is a long way off, do you think we should create a daemon side issue to support this (which will obviously go straight into the ice box :P)?

**Comment by DrAlta** [comment]
Couldn't this be easily added by allowing LBTY names as sources in addition to LBRY sd_hashes, HTP URLs, bittorrent whats its and IPFS paths.

**Comment by kauffj** [comment]
I'm closing this as it isn't a desktop issue and I believe this issue exists in either proposals or lbry.
