### ISSUE TITLE
Rewards Signup

### ISSUE THREAD

**Issue by ToThePeterCopter** [lbryio/lbry-desktop#6192]
This is my first time on Github, pretty sure I'm doing this all wrong so sorry about that.  
I just wanted to post a short video clip of the problem.
As I click on the notification it goes to the other page, but only for a split second as seen in video clip.
I signed up for Odysee a long time ago and have over 100LBC, mostly from watch rewards.  
I don't know anything about code and I'm sure you guys are very busy so no need for a reply, I just wanted to share this.
 
Also, I have never been able to view a live feed.  I won't get into that, just thought I'd add it as I thought maybe it's related somehow.

Browser: Waterfox 78.12.0
OS: Windows 10
Video:  https://user-images.githubusercontent.com/35485882/121387405-e3478000-c907-11eb-803f-1b74b761cd41.mp4

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble - shoot us an email with your email so we can take a look into the account history. Should not be getting those notifications if you are reward approved. Thanks for this report! 

You can also give us the details of the live streaming issues - also maybe try another browser like Chrome/Brave if you see a cookies warning.

**Comment by ToThePeterCopter** [comment]
Thanks tzarebczan, will do.
