### ISSUE TITLE
HTML5 version for broader usability and paranoid users

### ISSUE THREAD

**Issue by JYamihud** [lbryio/lbry-desktop#6197]
# Issue

A lot of people take their privacy and security very seriously. Some use Brave. Some use IceCat with LibreJS that blocks non free JavaScript code. Some use, and this is important, *Tor Browser on the highest level of security.* which **BLOCKS ALL JAVASCRIPT!**.

In such circumstances, websites like Odysee will not load. Since they require a huge amount of JavaScript to work.

# Solution

If you try to load Duckduckgo.com on Tor with Javascript disabled. You will be redirected to a special, minimalistic, javascript free version of the site. It will not have image search or any fancy feature, but the core functionality will be doable from this site. You could search still. And even though they use pure HTML5 to build the web page, they are still able to make a very good looking one. Even though slightly uglier then the JavaScript heavy version.

How about, if the webpage is not being able to be loaded. it will redirect to say `html.odysee.com` which is the same old odysee, but uglier and built only with JavaScript. The main features as reading articles, downloading files and watching videos can be implemented easily with HTML5. You can simply embed a video file into a web page with HTML5 and it will give a standard player. I know it's not going to look very nice. But it will open the platform to a lot more people. 

Perhaps for livestreams and other fancy features a disclaimer could be made that this feature requires to run javascript. But for most site, why not give people the option. 

Also it could be good for people with slower computers. Since basic HTML eats less of processing power then a huge JavaScript application running in each tab.

**Comment by tzarebczan** [comment]
Thank you for the issue and write up. This is not something we plan to do anytime soon since we rely on the open-source videojs framework heavily. We may consider it in the future.
