### ISSUE TITLE
Remember last used playlist choice, show option on menu

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#6205]
YouTube doesn't have this one (yet)...

If I'm adding to a common playlist, I don't want to have to go into "add to lists" every time. Would be nice to show the last used playlist along side the favorites/watch later options.

**Comment by Ruk33** [comment]
Hello @tzarebczan, something like this is ok?

When no collection was used (no change)
![image](https://user-images.githubusercontent.com/1719111/155045446-26de9297-84f8-4362-8d31-824855398d6b.png)

Collection was used (test):
![image](https://user-images.githubusercontent.com/1719111/155045514-49b4c300-e105-41c1-a6f2-a095e55f33ee.png)

Video is already in last used collection:
![image](https://user-images.githubusercontent.com/1719111/155045582-0896d6a9-b2e3-4374-a0e8-47d228d19eb7.png)

**Comment by jessopb** [comment]
I thikn this is a great start. pr?

**Comment by Ruk33** [comment]
Hello @jessopb, sorry for the delay. I just sent the PR. Let me know if you got any comments :+1:
