### ISSUE TITLE
channel names and licensing choice dropdowns blacked out while publishing

### ISSUE THREAD

**Issue by unclejed613** [lbryio/lbry-desktop#621]
## The Issue
when trying to publish, the channel name dropdowns and license dropdowns are blacked out
### Steps to reproduce
1. from a fresh start of the app, publish an item, then try to publish another item
2. when publishing a second or 3rd item the channel name dropdown will be a black rectangle after clicking to open it.  same thing happens to the license dropdown.  when the dropdown is blacked out, no choices can be selected (even if you guess where an item might be and click)
3.exiting and restarting the app will correct the problem, but usually for only one time (had it work twice occasionally)

### Expected behaviour
Tell us what should happen
the channel dropdown should contain a list of user channels, black text with white background. clicking an item in the dropdown populates the choice made
### Actual behaviour
Tell us what happens instead
dropdowns are blacked out, and clicking on the blacked out list returns nothing

## System Configuration

 

App | 0.16.0
-- | --
0.16.1
3.1.8
unclejed613c@yahoo.com
 
Linux (Linux-4.2.0-42-generic-x86_64-with-Ubuntu-15.10-wily)

- LBRY Daemon version:
- LBRY App version:0.16.04
- LBRY Installation ID:4HmHZbnJc572RYCQWxWx1rp8xUc1mFysqNZ42sBbTL9TkpJ3ajtgQSVKJPSUyaLji4
- Operating system:Linux (Linux-4.2.0-42-generic-x86_64-with-Ubuntu-15.10-wily)

**Comment by btzr-io** [comment]
There are some known bugs with electron: https://github.com/lbryio/lbry-app/issues/544#issuecomment-329548859
That can be fixed using a custom `dropdown` component

**Comment by btzr-io** [comment]
Example for reference:
https://github.com/JedWatson/react-select

**Comment by tzarebczan** [comment]
@unclejed613 - thanks for submitting the issue, please check out https://lbry.io/faq/tips :)

**Comment by kauffj** [comment]
I'm not inclined to drop native selects due to an issue in Electron. Let's see if this persists after Electron is updated.

**Comment by tzarebczan** [comment]
@unclejed613 does this still happen in the latest version?

**Comment by liamcardenas** [comment]
Closing, please reopen if its still happening :)

**Comment by tzarebczan** [comment]
Sounds like its still happening to users - but this time on ArchLinux. Going to have the user post a screenshot here.

**Comment by MR4Y** [comment]
On Archlinux, latest AUR build of lbry (0.19.1 app, 0.18.0 daemon, 3.1.11 wallet, Kernel Linux-4.14.5-1-ARCH-x86_64-with-glibc2.3.4, MATE Desktop Environment)

![lighttheme](https://user-images.githubusercontent.com/9355061/34014802-97555806-e103-11e7-9348-c2554534c61c.png)
![darktheme](https://user-images.githubusercontent.com/9355061/34014803-97a21b46-e103-11e7-8be3-9d42961acb1e.png)

**Comment by liamcardenas** [comment]
@seanyesmunt I think this will be taken care of in the redesign... as Jeremy alluded to, I doubt we will use native dropdowns anyway

**Comment by kauffj** [comment]
@liamcardenas the opposite! I would always prefer to use native elements when possible.

However, this seems like it must be a bug in Electron, rather than something we could fix.

**Comment by alyssaoc** [comment]
closed, this has been addressed in the redesign

**Comment by tzarebczan** [comment]
@MR4Y let us know if you are still seeing this on the latest app release. Closing for now.
