### ISSUE TITLE
Desktop App: Add status of connected peers and bandwitch

### ISSUE THREAD

**Issue by kodxana** [lbryio/lbry-desktop#6227]
![image](https://user-images.githubusercontent.com/16674412/121893206-fbf7d180-cd1d-11eb-87ad-16f495e38459.png)

Add status of peers you are connected when using Desktop App P2P.
Provide informations about upload/download speeds.
Create page where you can see stats of your node.

Wanted by many users on Reddit so posting it here :)
https://www.reddit.com/r/lbry/comments/nz9jl0/what_do_you_guys_think_about_adding_this_feature/

**Comment by tzarebczan** [comment]
We've got this covered under https://github.com/lbryio/lbry-desktop/issues/2773
