### ISSUE TITLE
Facebook url block - missing org type

### ISSUE THREAD

**Issue by julianchandra** [lbryio/lbry-desktop#6240]
The odysee.com domain doesn't work on facebook. 
After reviewing: https://themeisle.com/blog/website-blocked-by-facebook/
Ran debug test here: https://developers.facebook.com/tools/debug/?q=odysee.com

We have a warning that needs to be fixed: 
_Missing Properties_
The following required properties are missing: og:type

I think if we fix this our domain will work again. Can someone help?

**Comment by julianchandra** [comment]
I have also sent through a complaint to the ads team saying that i can't run ads while the domain is blocked

**Comment by tzarebczan** [comment]
That's just a warning and doesn't affect the outcome of previews. We can certainly add it ,but it won't fix the issue.
