### ISSUE TITLE
Playlists Bug!

### ISSUE THREAD

**Issue by JYamihud** [lbryio/lbry-desktop#6249]
Trying to add `@J.Y.AmihudMusic:c/Blender-Dumbass:7` to a list. Gives an error page

`Error ID: 2d40c204280341a18158e6aa39e4a8a5`

Using GNU IceCat browser. In Israel. ( I heard some localization problems maybe )

**Comment by JYamihud** [comment]
Still happening. To make it cause an error I go to the publication. ( link provided above ) and I hit the new `+ Save` button. Then it just crashes. Just checked a [different file](https://odysee.com/@J.Y.AmihudMusic:c/Into:f) ( also audio ) crashes as well. 

Also checked video-files. It happening to any publication I try.

**Comment by tzarebczan** [comment]
Please shoot us an email at hello@lbry.com with your account so we can take a closer look. Not getting other reports of this, so it may be specific to your case. 

Please reference this issue.
