### ISSUE TITLE
Weird CORS issue with Lighthouse search

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#6273]
- lbry.tv
- Type `hello` in a normal pace.  Everything works fine (first error is expected):
  - ![image](https://user-images.githubusercontent.com/64950861/122582187-6f854000-d08a-11eb-997e-4086d0e519b0.png)
- Rinse and repeat:  backspace x3 + "llo".
  - ![image](https://user-images.githubusercontent.com/64950861/122582506-d1de4080-d08a-11eb-934b-e7666665ad4d.png)
  - Weird CORS issue (I'm at lbry.tv, and previous same query worked):
    - ![image](https://user-images.githubusercontent.com/64950861/122582657-f76b4a00-d08a-11eb-8c4e-36c9f23c7e26.png)

I'm guessing some spam-checking mechanism is kicking in, but I encountered this while really searching for something.  The steps above is just the fastest way to reproduce the same error.

**Comment by tzarebczan** [comment]
this is a throttle from LH to prevent spam. The right solution would be https://github.com/lbryio/lbry-desktop/issues/6314 

In this case, we can show a message that says "please try your search again in 1 minute"

**Comment by infinite-persistence** [comment]
A PR is coming up to do exactly as 6314.

However, I'm still frustrated at being penalized just for making typos.  Example:  I was searching for the binance dude, "CZ".  Since 2 characters are not allowed, plus I can't recall his exact name, I did some trial-and-error but was penalized by the third attempt.

![image](https://user-images.githubusercontent.com/64950861/123030055-ba011680-d414-11eb-9dbd-7e24cbf36eb9.png)

**Comment by tzarebczan** [comment]
I think once we get that Change in, we can relax the spam  rules. We'd have to see about the 2 word search too...

**Comment by infinite-persistence** [comment]
## Close
Not seeing the lockup anymore, since we are only sending queries 1s after typing idle
