### ISSUE TITLE
Video doesn't switch when floating player is up

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#6278]
In the video below, it's supposed to go back to the wrestling video on the second click, but it got stuck with the interview video:
https://lbry.tv/@ip-test-1:4/video-no-switch:2

Reverting eff948f7864aa7b16960db8798c0f46c5f7cde66 seems to fix it.

**Comment by tzarebczan** [comment]
That revert fixing it is strange..
@jessopb is aware of this one too, but that fix is def needed to better support transcoded videos. I thought it came from the playlist changes.

**Comment by infinite-persistence** [comment]
Actually, just putting back the double `src` call (but using the new `finalSrc` for both) also fixes it.  Not sure why it needed the double src call, but seems like it's crucial.  Maybe Xander knows.

**Comment by infinite-persistence** [comment]
## Re-open
It's back after the ads merge

**Comment by tzarebczan** [comment]
Closing for https://github.com/lbryio/lbry-desktop/issues/6777
