### ISSUE TITLE
Error for Filipino language being selected as a primary/secondary language

### ISSUE THREAD

**Issue by iamflorencejay** [lbryio/lbry-desktop#6286]
**Bug**
There is an "Enum Language has no value defined for name fil" error when I want to select Filipino as a primary/secondary language. it also happens on Odysee too.

**To Reproduce**
1. Go to channels, and click your channel
2. Click on edit
3. Scroll down to primary/secondary language the pick filipino as a language
4. See the error

**Expected behavior**
Of course, you can change it and it work just fine.

**Screenshots**
![Screenshot_2021-06-19-22-10-07-240_com brave browser](https://user-images.githubusercontent.com/24932514/122645223-efbfaa00-d14b-11eb-9078-7bb0df0adb1e.jpg)

**Comment by tzarebczan** [comment]
Nice catch .Gotta figure out what the right code is from https://github.com/lbryio/types/blob/f0b4476ef386b096e99e64c6cf8a7ed20ca92d5f/v2/proto/claim.proto via those standards.

**Comment by iamflorencejay** [comment]
@tzarebczan can you do Tagalog language instead of Filipino? This is the standard of all streaming services right now.

**Comment by iamflorencejay** [comment]
I requested the language request on transifex already @tzarebczan 
![Screenshot_2021-08-24-01-13-25-918_com brave browser](https://user-images.githubusercontent.com/24932514/130489026-fae754e5-3035-4505-b14b-09121cc0ad1b.jpg)

**Comment by iamflorencejay** [comment]
The TL number btw is 162

**Comment by iamflorencejay** [comment]
Now it is good, probably
