### ISSUE TITLE
don't use CDN for GIF thumbnails

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#6301]
I think we used to bypass cdn based on file type. These don't render when we try to. https://odysee.com/@HLC:0

**Comment by infinite-persistence** [comment]
Channel thumbnail, right?  It still works (doesn't go through CDN), at least for 1024LBC channel.

I think this channel uses JPG (or perhaps he temporarily changed it to JPG after reporting):
```
      thumbnail: {
        url: "https://spee.ch/d/5cda15be2ecb2861.jpg"
      },
```

**Comment by tzarebczan** [comment]
Referring to all these: 
![image](https://user-images.githubusercontent.com/8120721/122974610-8a90d200-d360-11eb-892b-9d6ec304f3c8.png)

**Comment by tzarebczan** [comment]
Still seems broken - maybe we lost the change? Request URL: https://lbry2.vanwanet.com/speech/c574ae102b642200:5.gif

**Comment by kauffj** [comment]
@nikooo777, @tzarebczan says you have a server-side fix to make for this

**Comment by nikooo777** [comment]
I asked Nick to fix this, i'll ping him again now

**Comment by kauffj** [comment]
@nikooo777 was this fixed?

**Comment by nikooo777** [comment]
last update I got was yesterday:
```nick  17:06
Big performance upgrade coming in the next week
Still working on expanding capacity but will have a solution for the gif very soon```
