### ISSUE TITLE
Don't allow editing someone else's Channel

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#6308]
"Edit" shouldn't appear for "Channel" that's not yours.  It populated the page with the details, but fortunately the Submit was blocked.

- <img src="https://user-images.githubusercontent.com/64950861/122871459-9e890380-d361-11eb-9769-92dabd55c506.png" width="300">

**Comment by tzarebczan** [comment]
Ty @saltrafael for fixing, we'll get this in today.
