### ISSUE TITLE
Countdown on lists

### ISSUE THREAD

**Issue by saltrafael** [lbryio/lbry-desktop#6321]
Is the countdown here needed?
![](https://i.postimg.cc/qBZsHjTx/image.png)

Youtube only has it for recommended content

**Comment by tzarebczan** [comment]
That's a good point - probably not. 

And more importantly, we need an autoplay next control for lists/related on this page vs the global autoplay in settings (https://github.com/lbryio/lbry-desktop/issues/2902)
