### ISSUE TITLE
Can't close drag and drop 

### ISSUE THREAD

**Issue by saltrafael** [lbryio/lbry-desktop#6322]
Bumped my mouse and got stuck here:

![image12321](https://user-images.githubusercontent.com/76502841/123088808-9500a980-d3fc-11eb-9c19-de3a0ac0dba6.png)

tried clicking outside, clicking ESC, nothing worked had to refresh the page

**Comment by btzr-io** [comment]
Can't reproduce this. Please add more info and describe each step.
What browser ?

**Comment by btzr-io** [comment]
Related issue ? https://github.com/lbryio/lbry-desktop/issues/6456

**Comment by tzarebczan** [comment]
pinged @saltrafael to check if this still happens on your branch.

**Comment by saltrafael** [comment]
Didn't manage to reproduce anymore, might be fixed
the browser was Brave
