### ISSUE TITLE
Notification bell sends wrong toast

### ISSUE THREAD

**Issue by saltrafael** [lbryio/lbry-desktop#6331]
[![image.png](https://i.postimg.cc/L4vDthn6/image.png)](https://postimg.cc/kD6W9JQk)

Clicking the bell shows the Follow toast (Odysee-only action)

**Comment by tzarebczan** [comment]
Good catch, let's get this fixed up!

**Comment by tzarebczan** [comment]
@saltrafael can you take a look at this one soon?

**Comment by saltrafael** [comment]
@tzarebczan just did, forgot Odysee and LBRY desktop's code was the same
