### ISSUE TITLE
[Collaboration] Proposal to Integrate DASH to be used on top of LBC in Odysee.com & LBRY Desktop

### ISSUE THREAD

**Issue by wizlee** [lbryio/lbry-desktop#6341]
### Introduction
- This is an inquiry about a potential collaboration. I am from the Dash Incubator Developer community and I am currently working on creating an alternate frontend to odysee.com. 
- This proposal is created here as a Github issue after looking at the LBRY faq -> https://lbry.com/faq/support

### Motivation
- Before working on create an alternative frontend to Odysee, I am exploring on the possibility on collaborating and contributing to LBRY source code directly.
- The benefits are mainly the two listed below. However more can be listed if we look beyond the immediate gains:
    - For LBRY, this will bring more users into Odysee due to Dash focus on easy to use cash alternative for end users. This work can also be the ground work for future integration of other cryptocurrency or fiat currency in Odysee.
    - For Dash, this will reduce the development time to create a new alternative Odysee frontend.

### Solution Quick Overview
- DASH will be use as a 'wrapper' to LBC. 
    - In the background, LBC is still use to perform all the actions in Odysee. 
- User will be presented a choice in configuration / upon sign up to use DASH as the default credit. 
- Once user choose DASH as the default, the wallet page will show amount and transaction in DASH, together with the following changes:
    - User can still choose to look at the details AKA the actual transaction in LBC, including any conversion that is done between DASH and LBC.
    - User will have additional option to buy. receive and send DASH. Any DASH that the user deposited will be converted into LBC in one go to minimize conversion fees.

**Comment by tzarebczan** [comment]
Thank you for the request and detailed information. Unfortunately we don't think we'll be doing this at any time soon, so we're going to shelve it for now.

**Comment by wizlee** [comment]
Thank you for your reply @tzarebczan.
