### ISSUE TITLE
"Mark all as read" button not work on Desktop App

### ISSUE THREAD

**Issue by kodxana** [lbryio/lbry-desktop#6343]
**Bug**
"Mark all as read" button not turn notification as read you need to manually check them for numbers to go down.
**System Configuration**

- LBRY Daemon version: 0.99.0
- LBRY App version: 0.51.1
- LBRY Installation ID: 53Xs6ysNodWXqFdi6PcifcwtoG919xUWdVKf5bk2Wu5Gp3bUDoTxmiadXoCahLZwNC
- Operating system: Windows 11 Pro x64

**Comment by tzarebczan** [comment]
That's the Seen count - which is reset when you go to the notifications page. If you're on the page already, we may have to handle that differently and not increase count / make sure UI refreshes.

**Comment by infinite-persistence** [comment]
I saw that error as well 4 days ago ... forgot to take the screenshot of the network reply error.

But it worked again the next day, so I think this can be closed.  Probably someone fixed in iapi?

**Comment by kodxana** [comment]
@tzarebczan Also advance settings do not save. I chosen to hide balance it hides balance but when I press done it brings balance in header back.

**Comment by tzarebczan** [comment]
This is actually a bug in the desktop app - sends the notification ids as "{Object Set}" 

Will file a separate issue for that @kodxana .

**Comment by infinite-persistence** [comment]
Desktop Notifications ... that reminded me that I forgot to follow up on https://lbryians.slack.com/archives/C81FGKR51/p1619101431224800?thread_ts=1619101424.224700&cid=C81FGKR51

**Comment by tzarebczan** [comment]
That's probably it!
