### ISSUE TITLE
unable to claim Daily Watch Reward after update

### ISSUE THREAD

**Issue by stevenwong951028** [lbryio/lbry-desktop#6351]
Since updating the desktop LBRY app, I was unable to claim the daily watch reward. 

Been the same for the past 2 days. Just claimed successfully through the online version (odysee)

Please look into this matter.

**Comment by kauffj** [comment]
@jessopb can you investigate this?

**Comment by stevenwong951028** [comment]
update: tried again on LBRY desktop app again today with a successful reward claiming.

**Comment by DispatchCommit** [comment]
Closing as this appears to either not be an issue, or has been resolved by another team.

Let us know if this is not the case and we can reopen this issue and investigate further.

**Comment by jessopb** [comment]
The code is still feeding bad timing data.
