### ISSUE TITLE
RSS feed issues and improvements

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#6369]
- [x] figure out what the total number of items we want to return. Right now it's hardcoded to the last 50. Maybe have a lastest 50 and latest 1K feed? 
- [x] received complaints that RSS readers can't download the content. We can try adding a .mp4 and/or ?download=1 to the media URL : https://cdn.lbryplayer.xyz/api/v4/streams/free/this-hardcore-fps-is-actually-awesome/0325d87d94c858b26089a3ff0dc48a1843d5fcef/5c0f5d.mp4?download=1 
- [x] shorten urls? https://odysee.com/$/rss/@GivesAMinute/2e4c63a39e28e8e2bcac74debece9f7893fc3fe5

**Comment by kauffj** [comment]
- Missing space in the context menu between icon and text
- Copy action should give a success notice

**Comment by kauffj** [comment]
Ensure feeds pass https://validator.w3.org/feed (channel "@ vlad" did not)

**Comment by infinite-persistence** [comment]
## Notes

> _received complaints that RSS readers can't download the content. We can try adding a .mp4 and/or ?download=1 to the media URL : https://cdn.lbryplayer.xyz/api/v4/streams/free/this-hardcore-fps-is-actually-awesome/0325d87d94c858b26089a3ff0dc48a1843d5fcef/5c0f5d.mp4?download=1_

I think the fix will be:
- Move the item's thumbnail from `enclosure` (to free it up) into `description`, appending either at the top.
- Place the content URL (audio|video|image) into `enclosure`.
  - Not sure if the reader is looking at `enclosure` or something else for the auto-download , but that's the only official tag available that's related.

Aside: There's an extended tag `media:xxx` that's not part of the official list.

**Comment by tzarebczan** [comment]
For the shortened URLs, use the canonical channel URL and don't slice 2 chars

**Comment by infinite-persistence** [comment]
- [ ] Need to convert markdown in description to HTML.  Maybe need to strip embeds too?
- [ ] Figure out how to process Posts. Put it as a downloadable enclosure (users will get `.md` file), or copy the content to the Description field of the RSS?
- [ ] Enhancement:  include Lists.  But not sure how to present it.  Just the List Title and a bullet list of items, limited to 5 (terminated with ellipsis)?

**Comment by tzarebczan** [comment]
Here's another good validator i found when trying to add to podcastindex.org: https://castfeedvalidator.com/?url=https://odysee.com/$/rss/@BretWeinstein:f

To add a feed on podcast index, you need to sign up with https://blubrry.com/addpodcast.php and they run this integration test.

**Comment by tzarebczan** [comment]
Another validator. We heard feedback that itunes compatibility is also a must, so there's a few items from above and https://podba.se/validate/?url=https://odysee.com/$/rss/@BretWeinstein:f 

For the high-res cover, maybe we can just hack via url params for now.
