### ISSUE TITLE
Move all modals into ModalRouter and independent modal components

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#637]
Modals should no longer be rendered directly inside of other components.

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by liamcardenas** [comment]
@kauffj most appear to be moved over, do you know off the top of your head which ones are left? If not, I can look and find out.

**Comment by kauffj** [comment]
Search for the following strings:

- `<Modal` appearing anywhere outside of a modal view. Though potentially the ones in `<SplashScreen>` can or have to stay.
- `modal == "` Anywhere a modal is being checked against a string it should be replaced with the appropriate constant from `modal_types.js`.
- `modal: "` Same as above, but for dispatches.

It's probably slightly better to do regexes of the above. There may be another signature to look for, but I think that's probably all of them.

(This is a great example of the type of problem that makes me very pro strong types, immutability, and whatever else makes your code easier to reason about.)

**Comment by alyssaoc** [comment]
@seanyesmunt can you confirm this is done?

**Comment by seanyesmunt** [comment]
There is one modal left, inside of `rewardLink/view.jsx`

Currently if claiming a reward through the reward link fails, we pass an error string into the component. We can just call `doNotify` inside of the redux action.

**Comment by seanyesmunt** [comment]
Finally removed the last one in https://github.com/lbryio/lbry-desktop/pull/2206
