### ISSUE TITLE
Please bring back Repost and playlist in Odysee

### ISSUE THREAD

**Issue by operatordogechan** [lbryio/lbry-desktop#6371]
I was using my Odysee and LBRY sometime ago and I saw some the changes and it pretty darn good actually on what I saw in the Odysee implemented on the Repost and Playlist options in which I like the decision both on the LBRY Desktop app and also the Odysee. However I notice in the past few hours I notice that the Odysee side of things that the Repost and Playlist Feature was being removed. Why is that? It was a good feature I don't understand why it was removed. Are there problems on the feature? Please bring it back since it actually cleans up the users content space between what the user likes and repost and the content that the user uploaded.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jessopb** [comment]
Removal of playlist tab was accidental, and has been restored.
Better sorting features are incoming!
