### ISSUE TITLE
Pinned comments are duplicated

### ISSUE THREAD

**Issue by michaelmitnick** [lbryio/lbry-desktop#6382]
Comments posted on Odysee posts are duplicated. The error is also displayed in the mobile browser version.

![image](https://user-images.githubusercontent.com/33647673/124369926-4397bc00-dc3f-11eb-9ccc-244fcddfb145.png)

**Comment by tzarebczan** [comment]
This is a known bug on the comment server side and will be fixed soon, sorry!

**Comment by tzarebczan** [comment]
It's been fixed!

**Comment by kauffj** [comment]
@tzarebczan missed opportunity not responding "It's been fixed" twice
