### ISSUE TITLE
Advanced settings not persisting

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#6395]
Go to settings > advanced, turn on hide balance header, click done...it shows back up.

**Comment by infinite-persistence** [comment]
Same root-cause as #5974?

**Comment by tzarebczan** [comment]
Don't think so, they don't even seem to trigger a settings set if we're saving them to the wallet.

**Comment by jessopb** [comment]
This is because arriving on settings page triggers sync pull....

**Comment by infinite-persistence** [comment]
`Duplicate`
Closing in favor of [#6363 split settings into separate subareas with navigation](https://github.com/lbryio/lbry-desktop/issues/6363).  "Advanced Settings" will go away, and there will be no double pull.
