### ISSUE TITLE
Video compression for slower networks

### ISSUE THREAD

**Issue by minusfourty** [lbryio/lbry-desktop#6409]
As someone using rural DSL, some of to all of LBRY is unusable with my 1Mb/s network, particularly if anything else is trying to access the network. If some method of video compression could be implemented (such as UDP based streaming), the platform would become usable for many more users. There is currently no cap on upload resolution, and I can personally confirm some higher profile accounts upload at 1080p or higher, rendering the service consistently unusable over rural internet. As youtube and all other major streaming sites have this, LBRY in its current state is boarderline unusable in many cases, please implement this whenever possible!

**Comment by tzarebczan** [comment]
For now, we're experimenting with transcoding on more popular content and creators. You should see the option available on something like : https://odysee.com/@BretWeinstein:f/EvoLensQandA86:b

This is only available via odysee.com at this time. We'll explore other solutions in the future and continue to scale this one out.
