### ISSUE TITLE
Notification: Fiat Tip Notification

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbry-desktop#6421]
A new notification exists that needs to be skinned for the Ui `fiat_tip`.

![Screen Shot 2021-07-07 at 6 23 50 PM](https://user-images.githubusercontent.com/3402064/124836167-819f2380-df50-11eb-98b2-9ab6a977c0ed.png)

**Comment by tiger5226** [comment]
the `$` missing in front of the description has been fixed and deployed.

**Comment by infinite-persistence** [comment]
Closed with #6427
