### ISSUE TITLE
Dark theme without signing up

### ISSUE THREAD

**Issue by Karta775** [lbryio/lbry-desktop#6435]
**Is your feature request related to a problem? Please describe.**
I was surprised when I checked out Odysee to find that you cannot use the dark theme until you sign up, something that even YouTube allows. I really don't care for the crypto integration, comments, recommendations, etc, and would much rather **not** have to make an account with LBRY/Odysee for such a simple thing.

**Describe the solution you'd like**
An implementation of the dark theme control that doesn't force me to sign up for an account, the issue could also be improved upon by Odysee recognising the system theme and applying the correct one.

**Describe alternatives you've considered**
There aren't any proper alternatives, I won't sign up for an account just to change the theme. For now I will find some CSS changer and change this myself.

**Additional context**
It doesn't speak much for LBRY/Odysee's openness when changing the theme to dark requires users to provide personal information to sign up for an account.

**Comment by tzarebczan** [comment]
Right now we'd recommend signing up for an account, you don't even need to comment or have LBC. 

This issue is more generically covered under https://github.com/lbryio/lbry-desktop/issues/4957
