### ISSUE TITLE
Channel page on "List layout" allows editing playlist as a stream

### ISSUE THREAD

**Issue by keikari** [lbryio/lbry-desktop#6439]
**Bug**
Channel page on "List layout" allows editing playlist as a stream. 
(When trying to save changes gives error "Claim at name <collection-claim_name> is not a stream claim.")

**To Reproduce**
1. Go to  one of your channel pages which has playlists and toggle "list layout"
2. Click on 3-dot menu --> "Edit"
3. Opens "stream editor" instead of "playlist editor"

**Expected behavior**
Would expect button to show also on "grid layout" and opening "Playlist editor" when clicking edit on playlists.

**Screenshots**
![lists](https://user-images.githubusercontent.com/34790748/125107876-fb1e4980-e0e9-11eb-834c-b047658b9812.png)

**System Configuration**

- LBRY Daemon version: 0.99.0
- LBRY App version: 0.51.1
- LBRY Installation ID:
- Operating system: Linux

**Additional context**

**Comment by saltrafael** [comment]
Thanks for filling! Just added a fix to it in #6327

**Comment by keikari** [comment]
> Thanks for filling! Just added a fix to it in #6327
Nice, but the menu should be the same on both views, and the option to "edit" should work.(That opinion was from Tom) I guess I should have made that more clear as it wasn't in title, sorry, (I had it in expected behaviour.)

**Comment by saltrafael** [comment]
✔️  Option to edit works
✔️  It is the same on both views 

[![image.png](https://i.postimg.cc/PrbWc7bm/image.png)](https://postimg.cc/vcBxx3NB)
[![image.png](https://i.postimg.cc/yxxNPkTQ/image.png)](https://postimg.cc/GT0r33VG)
