### ISSUE TITLE
Video playback test/QA list

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#6444]
Embed, different browsers, scenarios, desktop, etc.

**Comment by tzarebczan** [comment]
Came up with a few: https://docs.google.com/spreadsheets/d/13jhyOLPQ3xsNXpKN4wkf5FS2ia75Bc9_AOsp3cBcTIQ/edit?usp=sharing

Also added an advanced tab for some related calls that should happen.
