### ISSUE TITLE
Livestream bugs / adjustments (HIGH PRIORITY)

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#6446]
- [x] Streams getting stuck live (the stream shows live, but isn't. This causes confusion and users think a channel is live, but isn't. Creators confused too). Usually happens with re-stream, but there's other examples. 

- [x] Quality selector missing (confusing)
- [x] Hardcoded automated transcoding list (Tom has to keep manually enabling transcoding for VIP streams)
- [x] Limiting replay upload speeds (this is causing buffering when replays are uploaded during a stream)
- [x] improve handling during network disruptions / network switches (i..e wifi to mobile, cdn hiccups, etc) (Xander aware). Playlist calls are made, no new data comes in until refresh. Might be caching related too, not sure. 
- [x] move away from https://api.bitwave.tv/v1/odysee/live and into internal apis endpoint
- [x] server randomly locks up and needs reboot due to io issues (see livestream channel). This kills exisitng streams and prevents new ones.

**Comment by tzarebczan** [comment]
Moved into issues on https://github.com/lbryio/odysee-media-server / https://github.com/lbryio/odysee-livestream-player/issues
