### ISSUE TITLE
Firewall settings for Linux AppImage version of lbry-desktop

### ISSUE THREAD

**Issue by geebotron** [lbryio/lbry-desktop#6450]
I am running the Linux AppImage version of lbry-desktop behind a stringent firewall.
It is restricting both outbound as well as inbound connections.

Which ports / protocols should I request to be allowed to enable lbry-desktop to carry out its usual business?

Thanks.

**Comment by keikari** [comment]
Check used ports from here https://lbry.com/faq/startup-troubleshooting
