### ISSUE TITLE
Better handle both internal and web backend interruptions / downtime

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#6455]
Both APIs and web backend services may go down, usually for short periods of time. When we detect this, we should not crash the page and allow the user to continue in a non-signed in session, with a message to retry connections (similar to what we have for api downtime)

**Comment by lyoshenka** [comment]
given our discussion yesterday i don't think there's anything for me to do here. gonna unassign myself. i'm happy to chat anytime about this. its a big next step for the api

**Comment by tzarebczan** [comment]
Issue moved to [OdyseeTeam/odysee-frontend #39](https://github.com/OdyseeTeam/odysee-frontend/issues/39) via [**ZenHub**](https://www.zenhub.com/)
