### ISSUE TITLE
Library section not deleting entries

### ISSUE THREAD

**Issue by ralmcruz** [lbryio/lbry-desktop#6457]
**Bug**
Some videos just don't disappear from library section. 

**To Reproduce**
1. Go to 'Hamburger' menu
2. Click on 'Library'
3. Click a video play it normally.
4. Click in delete button (Remove from your library) . Mark 'remove from my computer'
5. The video still there in you library.

**Expected behavior**
The entry in your library should disappear. 

**Screenshots**

**System Configuration**

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Additional context**

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. Pretty sure this is the same bug as https://github.com/lbryio/lbry-desktop/issues/4420 but if you give us some examples of what files can't be deleted and your log file from the help page to hello@lbry.com we'll take a closer look. Please reference this issue also.
