### ISSUE TITLE
Inconsistent "delete" modal

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#6463]
- When deleting a claim from the Context Menu:
  - ![image](https://user-images.githubusercontent.com/64950861/125471390-2d0e4826-73cc-40e3-be3c-2873b8de2ab8.png)
- When deleting from inside the claim's page:
  - ![image](https://user-images.githubusercontent.com/64950861/125471479-202ad2a3-7af5-4919-a1cd-eef82fc42040.png)

**Comment by tzarebczan** [comment]
This bug should be fixed by https://github.com/lbryio/lbry-desktop/pull/6327
