### ISSUE TITLE
Add status indicators for messages from creator, delegated moderator, global moderator

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbry-desktop#6467]
![Screen Shot 2021-07-13 at 3 58 19 PM](https://user-images.githubusercontent.com/3402064/125516897-57af4c3f-f57f-42e9-b6c8-b8371ac13c4d.png)

The delta sent in the comment websocket message will include these 3 fields now, if they apply. 

The messages from these types should have special handling and styling.

**Comment by kauffj** [comment]
Add badge next to channel name with text for role, or some other indicator

**Comment by infinite-persistence** [comment]
@tiger5226, this is only available from a websocket delta, yes?

- [ ] Should `comment.List` include this value as well?  If I enter a semi-quiet livestream, I won't see the badges on existing comments.  Putting on `comment.List` would also make it work for regular comments.  Not sure how expensive is this, though.
