### ISSUE TITLE
Comments: CPU maxed out

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#6473]
This applies to pre-pagination version too.

- [ ] 100% CPU when resolving
  1. https://odysee.com/@Odysee:8?view=discussion.
  2. Set zoom to lowest (25%).
  3. Scroll down to load more comments. CPU is pegged at 100% for quite some time.
  <img src="https://user-images.githubusercontent.com/64950861/125552852-245c0b74-dd57-495a-832d-5854fe58788d.png" width="800">

- [ ] 50% CPU when left as is
  1. After the steps above, just leave as is. Notice that CPU fluctuates between 20% to 50%.  It doesn't happen if I navigate back to the homepage.  No idea what's happening here.

----

Culprits (there could be more):
- Lots of resolves to load commenter details.  Maybe need to batch this.
- `remark` processing (parsing channel links, inline timestamps, etc.) on each comment.  I believe it is being ran multiple times per comment (any `remark` experts here to check our implementation?), and also when hovered over.  You can see 100% cpu when moving the mouse over a comment continuously.

**Comment by tzarebczan** [comment]
Was this from the comment react bug is it still happening?

**Comment by infinite-persistence** [comment]
Not related to that -- this screenshot is from pre-pagination.
