### ISSUE TITLE
ffmpeg file location

### ISSUE THREAD

**Issue by seanPhill** [lbryio/lbry-desktop#6479]
LBRY Desktop Version 0.51.1 (0.51.1)

Cannot find the file location for ffmpeg and then ffprobe.

In https://blog.lbry.com/faq/lbry-directories and https://blog.lbry.com/faq/video-publishing-guide it is suggested to put it in an ffmpeg folder under: "~/Library/Application Support/LBRY" but when selecting that folder (by dragging and dropping the folder from Finder into the selection window, it selects that folder but still has an error.

The error is "No such file or directory: '/Users/(username)/Library/Application': '/Users/(username)/Library/Application'"
so it is evidently not dealing with a space in a file path!

I moved them both to ~/Library/ffmpeg/ and they were both found fine!

Please note that the Mac user also needs to okay the execution of these binaries (for security), which is easy, as a dialog pops up allowing the user to immediately do that.

**Comment by tzarebczan** [comment]
Thanks for the feedback! I'll make a link to https://lbry.com/faq/lbry-directories which suggests using the Go To option in finder and mention that also. I believe we do mention the security warning, and if not, I'll update that also. 

Can we show you some [appreciation](https://lbry.com/faq/appreciation) for the feedback?
