### ISSUE TITLE
PWA/Web: Monitor for new app versions and prompt for refresh

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#6484]
Monitor for changes in `ui.xxx.js` using the `serviceWorker` (or something simpler?) and prompt user with "A newer version is available. Please reload.".

This ensures users will get out hot-fixes immediately, and also is a better solution for the "missing chunks" issues (which we currently just auto-reload when a chunk couldn't be found).

**Comment by tzarebczan** [comment]
We can also reload for users automatically: https://developer.mozilla.org/en-US/docs/Web/API/Location
