### ISSUE TITLE
Notifications Improvements

### ISSUE THREAD

**Issue by JYamihud** [lbryio/lbry-desktop#6501]
I know that most of the LBRY Desktop developers are focusing on making the Odysee experience the best it can be. But there are people that do not like Odysee. For instance: There are people that are not agreeing with the Community Guidelines. And want to make for example: pornographic channels. It is possible with an LBRY Desktop App, but impossible through Odysee.com.

The main feature stopping so many of us from just relying on LBRY Desktop app is the lack of Notifications. People communicate using Odysee in the comments, under posts. And to know when the comment is made is very important, in order to reply.

# Problems

 - **Lack Of Notifications on Desktop App**. I just got the latest AppImage of LBRY Desktop from LBRY.com. And it has no option to enable notifications. There is an option to enable desktop notifications for when the post is confirmed. But that's about it. 
 - **Notifications are full screen**. On Odysee, the main annoyance is that Notifications  always open up full screen. Which is not necessary. A pop up menu style of notifications would be better. Since it will not going to get you out of the article you are reading. 

# Fixes

 - **Give an option to enable notifications**. On Desktop, a cool additional thing, could be to make the notifications actually be Desktop notifications. 
- **If it's outside of your vision**... Please point me into a direction of a file, or a setting, that I can edit manually. So I could build an LBRY app with notifications for myself. 
- **Make notifications a pop up menu**. Similar to any other site that has notification icons. It's just a tiny menu.

**Comment by tzarebczan** [comment]
Thanks for the issue. Notifications may come later into the Desktop as a centralized Odysee feature. We can enable them for you now if you shoot us an email at hello@lbry.com and ask for the experimental tag. 

There's a separate issue for drop down notifications filed under https://github.com/lbryio/lbry-desktop/issues/6391
