### ISSUE TITLE
Embed videos without cookies

### ISSUE THREAD

**Issue by 9mido** [lbryio/lbry-desktop#6502]
Now that odysee videos have ads, there needs to be something like https://www.youtube-nocookie.com/embed/ so that users could embed videos on their website without having to worry about cookies and GDPR.

**Comment by kauffj** [comment]
Embeds do not have ads. Embeds always had cookies.

**Comment by 9mido** [comment]
@kauffj 

Okay did not know that about embeds not having ads.

But if embeds have cookies, why not make something like https://www.youtube-nocookie.com/embed/ for odysee?
