### ISSUE TITLE
It should be possible to play a video without navigating to it

### ISSUE THREAD

**Issue by flauc** [lbryio/lbry-desktop#6505]
When looking at a list of videos it would be awesome to be able to hit play (or download) without needing to navigate to it. At the moment you need to click in to the video hit play and then go back but more often then not you'll lose your position and get returned to the top of the page with filters reset making it doubly annoying.

**Comment by JYamihud** [comment]
I think the LBRY Desktop should support some basic Tabs.

**Comment by tzarebczan** [comment]
Thanks for the suggestion. This would be covered under this feature request: https://github.com/lbryio/lbry-desktop/issues/2697
