### ISSUE TITLE
Allow Dark Mode For Logged Out Users On Odysee

### ISSUE THREAD

**Issue by 9mido** [lbryio/lbry-desktop#6519]
Currently dark mode is only allowed for logged in users on odysee. I don't see a point in this. It just irritates users and forces them to make an account just to use dark mode. 

I did not check whether odysee's dark mode mechanism uses cookies or localstorage. It would probably be better to use localstorage as opposed to cookies. 

I would also suggest using CSS prefers-color-scheme so that users don't even need to click the dark mode button and it is automatically done for them based on their operating system settings.

**Comment by stefansundin** [comment]
I was just thinking the exact same thing. Even YouTube lets you turn on dark mode when you aren't signed in. It would be great if this could be supported.

**Comment by tzarebczan** [comment]
Creating an account is free and takes a few seconds, you can even use a fake email. And you won't get ads. 

Otherwise this issue is covered under https://github.com/lbryio/lbry-desktop/issues/4957

**Comment by 9mido** [comment]
Here is a workaround for others who want dark mode when logged out on Odysee:

https://www.howtogeek.com/446198/how-to-force-dark-mode-on-every-website-in-google-chrome/

https://www.pocket-lint.com/apps/news/google/149866-how-to-enable-dark-mode-for-google-chrome

https://www.thetechminute.com/dark-mode-google-chrome/
