### ISSUE TITLE
Every ones in a while video doesn't load

### ISSUE THREAD

**Issue by JYamihud** [lbryio/lbry-desktop#6525]
I'm using a GNU IceCat browser that blocks third party request until I allow them. Every ones in a while, a video is not loading. And it's due to a new domain name appearing in the list. So the server, is probably, redirecting the video link to a bunch of different locations. Which messes up my third party request blocker.

Also it might be an issue, since I'm almost always connected via Tor.

**Comment by tzarebczan** [comment]
Don't think there's much we can do about this on our end.
