### ISSUE TITLE
RSS is BORRING

### ISSUE THREAD

**Issue by JYamihud** [lbryio/lbry-desktop#6526]
I just tried to subscribe to myself through the RSS, and it works. The problem is. The article is not loading. And example:

![image](https://user-images.githubusercontent.com/27649397/126046476-82f3d533-8c82-42e4-a5c0-01b043331d99.png)

I don't think anything like loading articles are yet implemented. But would be nice. I mean, at least for the articles.

**Comment by infinite-persistence** [comment]
Dup #6369
