### ISSUE TITLE
Ads on Odysee

### ISSUE THREAD

**Issue by troler36** [lbryio/lbry-desktop#6527]
Odysee has a lot of ways to earn LBC. Ads have been in works for a while now. This is an idea how this **can** be implimented

There will be 2 different videos when you press on one of the videos. There'll be the main video that you clicked to watch and the ad. Ads will be optional, but if you watch one you'll get a certain amount of LBC (depends how much the advertiser wants to pay the viewer and the author). This is a theoretical design of how it could look like from viewer's point of view

![theorethical design](https://user-images.githubusercontent.com/39880578/126046779-11fcd06d-e768-4672-98ed-e78d0a111180.png)

**Q&A**

> Will it be a centralized service?

No and yes. It will be hosted on Odysee servers, but you'll be able to host it yourself (because the source code will be public)

> Will ads be optional

Yes, you'll be able not to watch them

> Will ads be based upon your interest?

No, as that is privacy introspective. The ads will work similar how DuckDuckGo search engine does. It shows you ads based upon your search, at this case the video your watching.

> Will the author be able to select which ads are shown

Yes, but in a limited capacity. They'll be able to select how much LBC they'll want to earn if a viewer watches the ad. This *should* entice advertisers to pay video authors more so their ads would be seen. 

> How long will ads be

Up to 30 seconds

**Comment by JYamihud** [comment]
I had a slightly more decentralized and different approach, idea about this, whole ads thing. I think LBRY could be an advertising marketplace. A kind of protocol - broker. Between the advertiser and the publisher. And of course they are only an option for the user.

**Comment by troler36** [comment]
> I had a slightly more decentralized and different approach, idea about this, whole ads thing. I think LBRY could be an advertising marketplace. A kind of protocol - broker. Between the advertiser and the publisher. And of course they are only an option for the user.

I was thinking on making as simple as possible. I had considered an advertising marketplace, but that is going be not easy to implement. I personally like this advertising system. As if you are going to give the viewer 0.01 LBC they'll probably won't click to watch the ad. If you give them 2 LBC, even I would click on it. I usually get ~0.4 LBC per day for watching videos (^:

**Comment by tzarebczan** [comment]
We most likely won't pursue an option where you watch ads for LBC. We're exploring other ad situations where creators can force ad watch or users can pay to bypass.
