### ISSUE TITLE
Only allow uploaded videos to be seen on certain domain names

### ISSUE THREAD

**Issue by 9mido** [lbryio/lbry-desktop#6547]
Only allow uploaded videos to be seen on certain domain names when the uploaded videos are embedded into the website that has that domain name. Configure the uploaded video to not be seen on odysee publicly, but instead can only be seen on a certain domain name when embedded.

Vimeo does this and Peertube is decentralized and was able to do this with the `Referrer` header.

**Comment by tzarebczan** [comment]
Thanks for the suggestion, but we won't be doing this. Since the LBRY blockchain and data network are public and open, we can't restrict who can view certain content.
