### ISSUE TITLE
Don't break words in chat + fix text overflow past 3 dot menu

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#6602]
![image](https://user-images.githubusercontent.com/8120721/126401813-929f1d68-4d4b-46f6-9603-198599a5d063.png)

**Comment by btzr-io** [comment]
Works fine for me. I can't reproduce this.

**Comment by btzr-io** [comment]
Is this still an issue ?

**Comment by tzarebczan** [comment]
This is fixed, but this happens now where the text overflows the 3 dot menu. 
![image](https://user-images.githubusercontent.com/8120721/128422240-a7a5a435-dc47-4103-a71b-303c8066e684.png)
