### ISSUE TITLE
Add a live section tab on homepage

### ISSUE THREAD

**Issue by peshemak7** [lbryio/lbry-desktop#6606]
**Is your feature request related to a problem? Please describe.**

Its difficult for a live streamer with no fan base to reach their target audience .and also for a viewer its difficult to find live streamer with good content.

**Describe the solution you'd like**

Just add a live section tab on home page. Which only has livestreams so live streamers can get their target audience easily and vice versa. PFA image use that space and add live section.
![livesection](https://user-images.githubusercontent.com/87746720/126436077-beddb589-a08e-4d11-978b-7672c2665ebf.PNG)

**Describe alternatives you've considered**

**Additional context**

Not only Live section but u can add different categories on home page like music, photos , blogs ,books etc.  PFA image on that space marked

**Comment by tzarebczan** [comment]
Each category, including your following and wild west, show all active live streams.

We won't be adding a separate category for the time being.
