### ISSUE TITLE
Add ability to view previously posted comments from channel

### ISSUE THREAD

**Issue by sauce420** [lbryio/lbry-desktop#6620]
**Is your feature request related to a problem? Please describe.**
- I wanted to view a comment I had previously posted, but I couldn't remember the name of the video.
**Describe the solution you'd like**
- I would like to have a menu on my channel somewhere that allows easy viewing of previously posted comments (like Reddit)
**Describe alternatives you've considered**
- Alternatively, there could be a way to sort through comments on a video to only show ones posted by a certain channel
**Additional context**

**Comment by tzarebczan** [comment]
Thanks for opening the issue and sorry for not replying sooner! We have this filed under https://github.com/lbryio/lbry-desktop/issues/5146
