### ISSUE TITLE
Open in desktop

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry-desktop#6659]
- [x] Make desktop app resolve external `lbry://` ( make electron protocol handler also work in dev mode )
- [x] Add a "open in desktop" button on web version

### Example: Spotify 
![image](https://user-images.githubusercontent.com/14793624/126724417-ff7aef42-d267-4145-b7df-7874de60c2be.png)

**Comment by jessopb** [comment]
I like the idea of dev mode supporting deep links, but I'm not sure if it's feasible. Needs a new issue.
