### ISSUE TITLE
sending an empty tweet

### ISSUE THREAD

**Issue by neofutur** [lbryio/lbry-desktop#6678]
The "share to twitter" button on the lbry-desktop is sending an empty tweet with ONLY the URL , no text, no title , no hashtags
No one does that , every website out there adds at least the title in the tweet intent . 

this is a functionnal bug , hurting the lbry maketing and adoption.
same bug is also true on the lbry.tv and odysee.com websites ( that are probably using the same code) .
same bug is also true for the reddit share, telegram share . . . you send only the URL, no text, no title, no hashtag

1. Go to a video
2. Click on the share button, choose twitter
3. you will be presented an empty tweet with no title and no hastags, no words

the bug is exacty there , line 118 , creating an empty tweet : https://github.com/lbryio/lbry-desktop/blob/60130ec91e5ed13acd7cbea3bbc9c4584cd95d75/ui/component/socialShare/view.jsx#L118 

**Expected behavior**
doing the same as all the websites on the internet, include at least the title of the video in the tweet intent and possibly also the hashtags , to generate many more tweets and hype and keywords

I insist, this is an important marketing and social issue . why do you think 99% of the websites add at least the title ? youtube is even adding "via @youtube" on each tweet intent sent from their platfom .

**Comment by tallship** [comment]
This is a big deal. It's the front facing aspect of LBRY from the public's perspective, and should be afforded attention from the dev team in short order IMO.

**Comment by neofutur** [comment]
I m happy to see this is treated as a bug and theres already a pull request !

 I just need to add that, if its mostly important for twitter, the same fix is also necessary for all the other sharing buttons  ( reddit, linkedin, facebook, )
