### ISSUE TITLE
Open notification links in new tab, use `<a href>` for links to pages, videos, and channels, from `Notifications` page.

### ISSUE THREAD

**Issue by sapioit** [lbryio/lbry-desktop#6691]
**Is your feature request related to a problem? Please describe.**
Problem: I cannot open in new tabs videos from notifications, without leaving the Notifications page or opening multiple Notifications pages and clicking on a different notification in each tab.

**Describe the solution you'd like**
Add an `<a href>` element to both the links to the content, and to the channels about which the notifications are (if they are not system notifications), so we can open them in bulk, from the same page.

**Describe alternatives you've considered**
Add an "open in a new tab" option to the dots-menu. This would, however, make it unable to open videos in incognito windows, from the notifications.

**Additional context**
I am one of the many people who use more tabs than the browsers were intended to. To put things in perspective, I currently have 2872 tabs currently open, in the same window on Chrome, with a measly 4th get laptop i7, 8gb ram, and a mobile Maxwell (Nvidia) graphics card. And I know for a fact that there are many people who open a dozen or so videos at once, and binge-watch them, before opening other links.

**Comment by tzarebczan** [comment]
Thanks for filing, we have this under https://github.com/lbryio/lbry-desktop/issues/5095 and we'll be working on it soon!
