### ISSUE TITLE
candidate app builds require fixed daemon candidate

### ISSUE THREAD

**Issue by jackrobison** [lbryio/lbry-desktop#670]
## The Issue

For example, app 0.17.0rc1 requires daemon 0.17.0rc13 exactly.

### Expected behaviour

Any daemon RC of the same version should work, or at very least every RC >= the bundled daemon (rc14, 15, etc should work).

### Actual behaviour

The app shuts down after saying the daemon is incompatible.

**Comment by liamcardenas** [comment]
@kauffj should we prioritize this issue highly? It would help with future daemon testing

**Comment by kauffj** [comment]
@liamcardenas sure, it's an easy one. Just fix this line:

https://github.com/lbryio/lbry-app/blob/master/ui/js/redux/actions/app.js#L156

However, you need to use a comparison check that can properly handle version numbers, including RCs.

**Comment by alyssaoc** [comment]
closed, this has been fixed

**Comment by tzarebczan** [comment]
Fixed in dev mode, will open a ticket for prod mode.
