### ISSUE TITLE
Desktop app fails to resolve external protocol links (lbry://)

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry-desktop#6703]
**Bug**

External lbry protocol links are ignored by the lbry desktop app.

**To Reproduce**
1. Open browser
2. Type or click on a lbry protocol url ("lbry://") link.
3. Select open with Lbry desktop app

**Expected behavior**
Navigate to the new requested url.

**System Configuration**

- LBRY Daemon version: 0.99.0
- LBRY App version: 0.51.1
- Operating system: Windows 10

**Comment by tzarebczan** [comment]
Thanks for filing - we have it under https://github.com/lbryio/lbry-desktop/issues/4915 too. Will close that one.
