### ISSUE TITLE
I would like to manage the content that I distribute

### ISSUE THREAD

**Issue by lucy2812** [lbryio/lbry-desktop#6704]
**Describe the solution you'd like**

I would like to manage the content that I distribute.

I want to manage:

- To preserve selected content.  There is some content that I want to preserve/archive for historical and anthropology.  I also need to know the file name or folder location of this content so I can make sure I don't delete it, or if I move it, or if I setup another LBRY node.  As an extra, I would like to know the "health" of this content (i.e. how well its distributed).
- To delete content by age duration (e.g. keep content for N number of weeks, months, years, etc).
- To configure storage quota allotment. (I don't want the entire drive to be consumed by LBRY content).
- To configure monthly data limit.
- An algorithm to dynamically distribute content based on the network needs (i.e. region, popularity, load, "liked" content).

If there are privacy/anonymity concerns above, I would like to be aware of those risks.

**Comment by tzarebczan** [comment]
Hey there, thanks for opening the issue and suggestions. Many of these would need separate issues filed under the LBRY SDK, which is the backend service that handles the files. We have a few already know, so I'll circle back and file the others. 

Your content downloads into the download folder you have configured on your Settings page. If you use the SDK directly, the file list call will tell you the exact location of each file (https://lbry.com/faq/how-to-cli / https://lbry.tech/api/sdk) .
