### ISSUE TITLE
Fiat Tip Error message when card is declined

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbry-desktop#6717]
The message when an card is declined will not come through as a precondition failed status with the specific decline message from the merchant provider. These messages can now have a special presentation to the user.

**Comment by mayeaux** [comment]
Beamer let me know when this is supported in the API and I can support it on the frontend as well.

**Comment by tzarebczan** [comment]
This is live on apis, we should try to get this in soon since more people will hopefully be tipping.

**Comment by mayeaux** [comment]
This actually already works with the way I have the code written, tested with a "Card declined" example card from Stripe
