### ISSUE TITLE
In LBRY UI Library pane, I would like a feature to delete downloaded content.

### ISSUE THREAD

**Issue by lucy2812** [lbryio/lbry-desktop#6719]
**Describe the solution you'd like**
In the LBRY UI Library pane, I would like a feature to delete the content that I downloaded. 

Either through the "..." menu, right-click, or select and delete key, or with an X.  Something easy and intuitive.

![delete](https://user-images.githubusercontent.com/85310065/127369583-ef3bcbc7-3e96-4543-b0fc-9bbc677936a6.jpg)

**Comment by tzarebczan** [comment]
Great suggestion, thank you! A good one for @saltrafael
