### ISSUE TITLE
Install to different directory/drive.

### ISSUE THREAD

**Issue by lucy2812** [lbryio/lbry-desktop#6748]
When I install LBRY Desktop on Windows, there is no option to install the application to a different folder/drive.  

This is especially important if after installing there is little to no free storage space on the installed drive, LBRY App becomes unstable and without good information to inform you your drive is full.

**Comment by tzarebczan** [comment]
There's an existing issue for this, but the install itself doesn't take much space. It's the data for the SDK, which this issue still needs work on the backend .

https://github.com/lbryio/lbry-desktop/issues/1966

**Comment by lucy2812** [comment]
This is for the LBRY app that installs to C:\Program Files, not the %APPDATA% folders.
Mine is taking 378 MB.

I'm not sure if this folder grows when used.
