### ISSUE TITLE
Remove File from LBRY?  No, from my Library.

### ISSUE THREAD

**Issue by lucy2812** [lbryio/lbry-desktop#6749]
I downloaded content to my library.
When I select to have the content deleted from my library, the dialog asked me if I want to delete from "LBRY".  This is confusing.  I don't want to delete someone else's content from LBRY, just my personal library.

Rather have the dialog say (especially since I'm in the "Library" pane):
"Are you sure you'd like to remove from your Library?"

![Delete From LBRY](https://user-images.githubusercontent.com/85310065/127748101-c486dbce-bcb2-41b5-a72a-8b2ccbe72b90.png)

**Comment by Eniamza** [comment]
This issue is already addressed and resolved. Expected to be fixed on the next release
![](https://imgur.com/2ugZBTg.png)

**Comment by tzarebczan** [comment]
Thanks @Eniamza !
