### ISSUE TITLE
Unexpected behavior when typing in Japanese

### ISSUE THREAD

**Issue by Newl97** [lbryio/lbry-desktop#675]
## The Issue
Because Japanese uses multiple scripts, an IME (input method editor) is used to provide various kanji and mixed script options. In response to the space key (on a Western keyboard), these options are displayed in a list under the text being typed. The user uses the down arrow to highlight each option until the desired one is found. The enter key is used to confirm. 

When typing in the address bar and performing an IME kanji conversion, the address bar displays underscores instead of the text. Also, pressing "esc" causes the other text in the address bar to disappear.

### Steps to reproduce
1. Type some text in the address bar
2. Type some more text in Japanese and do a kanji conversion (space bar). 

### Expected behaviour
The text displayed in the address bar should reflect the text option currently highlighted as the user goes through them. When you press esc, the unconfirmed text should return to hiragana without affecting the other text.

### Actual behaviour
Underscores are displayed instead of the currently highlighted option. When you press esc, the unconfirmed text returns to hiragana and the other text disappears.

## System Configuration

- LBRY Daemon version: 0.17.0rc13
- LBRY App version: 0.17.0rc1
- LBRY Installation ID: AMJaSDoZNRoBdw6mndFFTTqLoUmRf2roHfaCL9AZm9pCeKqVgRruQRiybZZEaCMbMn
- Operating system: Sierra

**Comment by Newl97** [comment]
Additional information:
 
  "build": "rc",
  "lbrynet_version": "0.17.0rc13",
  "lbryschema_version": "0.0.12rc1",
  "lbryum_version": "3.1.9rc2",
  "os_release": "16.7.0",
  "os_system": "Darwin",
  "platform": "Darwin-16.7.0-x86_64-i386-64bit",
  "processor": "i386",
  "python_version": "2.7.13"

**Comment by kauffj** [comment]
Thanks for reporting this issue @Newl97 and for possibly being the first person to type a Japanese character into the app.

If you'd like a tip for this contribution, [see here](https://lbry.io/faq/tips)

**Comment by Newl97** [comment]
Thanks so much. They already tipped me in the Slack :)

There are other scripts that can cause other problems, like Hebrew/Arabic (right-to-left), Thai and the Devanagari script. 

I don’t see a point it testing those out yet, but will do that once the general script issue has been addressed.

**Comment by alyssaoc** [comment]
accepting PRs for this issue, otherwise closing
