### ISSUE TITLE
Content download status

### ISSUE THREAD

**Issue by lucy2812** [lbryio/lbry-desktop#6750]
When downloading content, I want to see the download status.

- Keep the download status popup active over the thumbnail, instead of hiding when unhovered.
- In the Library pane, show the download status, including any errors, and also have a retry button.
- When you hover over a completed download (like in the Watch Later list), it still shows you the download icon.  I think you can download multiple times, because there's no indication the download has succeeded.
- Downloads appear stuck in the UI (less than 100% downloaded), but they look complete within the folder.
- I have a bunch of fixes with the suffix "-1", which I believe is because I redownloaded the content.

**Comment by tzarebczan** [comment]
Will add your notes to https://github.com/lbryio/lbry-desktop/issues/4623
