### ISSUE TITLE
Current winning amount for name not shown when setting deposit amount for upload

### ISSUE THREAD

**Issue by keikari** [lbryio/lbry-desktop#6751]
**Bug**
Info text under "Deposit" on upload page always shows the "Any amount will give you the highest bid....".
Doesn't matter what claim name used.

Related:
When searching for claim name and choosing "repost here", the winning amount for not-used-names defaults to the original search name's winning bid, when changing the claim name for repost.
(Reposting from video's page does probably correct behaviour: winning amount defaults 0.01 for not-used-names)

**Expected behavior**
The text when choosing the deposit amount, should show winning amount required for name.

**Comment by tzarebczan** [comment]
Thanks for finding and filing. We should fix this soon, I'll give it a shot.
