### ISSUE TITLE
Desktop: bring back "Download" overlay button on Claim tiles?

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#6754]
- <img src="https://user-images.githubusercontent.com/64950861/127794921-c48aa5e0-fe5f-47e2-9619-7e976b8a72be.png" width="300"><img src="https://user-images.githubusercontent.com/64950861/127795070-087c78f2-9d42-47cf-9e93-e4e935351a4f.png" width="300">

Not sure if it was a conscious decision to replace it with "Add to Watch Later" shortcut button, or just an odysee-to-master side effect. But I think the quick-download functionality will be dearly missed, at least on Desktop.

Now, there are 2 ways to add to Watch Later quickly, but 0 ways for quick Download.
- <img src="https://user-images.githubusercontent.com/64950861/127795140-e21273c9-17f3-4594-bc6c-7781d422d674.png" width="100">

Adding "Download" to the context menu is probably not ideal either, given how long the menu has become.  Maybe need to support nested context-menu first?

**Comment by saltrafael** [comment]
whoops it wasn't removed, looks like one is on top of the other

https://github.com/lbryio/lbry-desktop/blob/0214c80544253f89bb4a25d001de6150472a969d/ui/component/claimPreviewTile/view.jsx#L214
