### ISSUE TITLE
Publications All Broken

### ISSUE THREAD

**Issue by JYamihud** [lbryio/lbry-desktop#6782]
I use the GNU IceCat broswer

Yesterday some new updates were probably done, that broke all publication pages on Odysee. The list of publications works fine. But only when I click to read an article or to watch a video it does this:

![image](https://user-images.githubusercontent.com/27649397/128175230-a1bf5bee-7433-44a7-8bbb-d1642548d9d2.png)

On Brave it works. This is probably some new library not supported by the IceCat. I remember seeing similar errors on IceCat in multiple other places. Like when I click to copy the RSS feed. Or try to make a playlist. It's only with the new features. 

It didn't bother me much, since the features were minor. And did not blocked me out of the core functionality. But with this new bug I CANNOT USE ODYSEE ANYMORE. Which is a big problem.

Something had changed recently with how features are implemented that broke support for certain browsers. Please fix it.

**Comment by tzarebczan** [comment]
Please send us an email at hello@lbry.com with a screenshot of the console tab (press ctrl-shift-I, then console tab).

**Comment by JYamihud** [comment]
done
