### ISSUE TITLE
Disk Space Management

### ISSUE THREAD

**Issue by eukreign** [lbryio/lbry-desktop#6783]
SDK will be adding some [disk space management features](https://github.com/lbryio/lbry-sdk/pull/3378) over the next few weeks and we will need to expose those features in the app. This is a request and proposal on exposing those features in the app. This issue will be updated as the SDK side of the features moves forward and especially when the UI work can begin.

The initial version of this feature will include:
1. setting the desired maximum space to be used for the blobs directory (`settings_set` end point).
2. ability to see the maximum space allotment which was set (`settings_get` end point)
3. showing current disk space used by the blobs directory (`status`)

Implementation proposal:
![disk management wireframe](https://user-images.githubusercontent.com/69960/128200683-21ebc8f4-8e72-4625-b95c-2cf87519d74c.png)

**Comment by trymeouteh** [comment]
Being able to see the files one is hosting and seeing how many seeders and peers are in each file (like in a bittorrent client) would also be useful, and the ability to delete file by file. This will allow a user to delete files that they no longer want to host.

The picture in the main post would also be useful to have on desktop and mobile for basic file management settings.
