### ISSUE TITLE
Other RSS issues

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#6786]
Much better now with the recent engagements, but I found a couple more items that come back from validators:

----
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fodysee.com%2F%24%2Frss%2F%40AndyNgo%3A9
https://odysee.com/$/rss/@AndyNgo:9
![image](https://user-images.githubusercontent.com/8120721/128218645-6660873f-fe39-478c-9aaa-1152869bde57.png)

----
https://www.rssboard.org/rss-validator/check.cgi?url=https%3A%2F%2Fodysee.com%2F%24%2Frss%2F%40AndyNgo%3A9

```
Leisure is not one of the predefined iTunes categories or sub-categories
```
- probably not much we can do about this, not sure how strict Itunes is. But at least creators can manage their tags. 

----
```
line 1, column 906: href must be a full URL: https://thumbnails.lbry.com/UCmmfVSRVwMSfHdRf6v3lPxQ (51 occurrences) [help]

... tegory text="Leisure"></itunes:category><itunes:image href="https://thum ...
```

- I think we gotta pass these through the image optimizer..... 

----
```
line 1, column 2078: url must be a full URL: https://cdn.lbryplayer.xyz/content/claims/andy-ngo-goes-undercover-in-new-fox/2fab8afa8e14de535892581444659379c1842fd9/stream (50 occurrences) [help]

... >Wed, 04 Aug 2021 00:54:12 GMT</pubDate><enclosure url="https://cdn.lbry ...
```

we can add the file extention (if exists in metadata) to the end, i.e. https://cdn.lbryplayer.xyz/content/claims/andy-ngo-goes-undercover-in-new-fox/2fab8afa8e14de535892581444659379c1842fd9/stream.mp4.. 

If none exists (old claims), we'd have to assume .mp4 unless there's other metadata that tells us audio vs video

----
```
In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendations.

line 1, column 60539: description should not contain stop attribute [help]

... //www.youtube.com/watch?v=0BhTlgiYyd0]]></description><link>https://odys ...
```
 - not sure what this means

**Comment by infinite-persistence** [comment]
Pretty sure `Leisure` is valid one as I picked it from the itunes site https://help.apple.com/itc/podcasts_connect/#/itc9267a2f12

**Comment by infinite-persistence** [comment]
- [ ] The first and the last item (about `</description>`) should be correct CDATA usage, and only RssBoard is complaining.  I tried https://stackoverflow.com/a/7306706/977819 to put `<description>` itself into CDATA, but that makes other validators that previously passed to fail:
  - <img src="https://user-images.githubusercontent.com/64950861/128276000-66abf603-cbad-4db3-adc0-7703a6f55659.png" width="300">

**Comment by infinite-persistence** [comment]
## RssBoard "Feed Validator" is obsolete
Ok, pretty sure now that RssBoard's "Feed Validator" is just obsolete since it even rejected `<itunes:title>`.
- https://discussions.apple.com/thread/8266095?answerId=32968048022#32968048022
- Regarding "full URL": https://github.com/podlove/podlove-publisher/issues/419#issuecomment-45697967
> _The Feed Validator team continues to refuse to fix this. Nothing we can do about it (except stopping using their service which we probably should do)._

----

I think no action items from this ticket.

**Comment by tzarebczan** [comment]
Some more apple specific requirements: https://podcasters.apple.com/support/823-podcast-requirements 

We'll need to encode player URLs, similar to our share encoding function. 

We'll also need to manually replace characters in titles/descriptions according to their list - don't think encoding would do that. 

I think the big one as to why it's not working today is the lack of file extension on the URL, so I'm gonna try that first. There's also a missing xml tag, will add that.

**Comment by tzarebczan** [comment]
Turns out the file extension was the main issue for Apple, will have that added tomorrow. I still didn't see episode thumbnails, but the channel thumb does work without Extention. The extension will be trickier there for YouTube synced content, but we can see if there's a workaround. 

We'll have to double-check some of their special encoding rules, but the current descriptions seem to work okay. Other readers my not expect the same character encodings.
