### ISSUE TITLE
Multiple Accounts & Anonymous Account

### ISSUE THREAD

**Issue by trymeouteh** [lbryio/lbry-desktop#6791]
Please allow for the ability to login into multiple accounts all at once and to have an offline anonymous account which can act as a incognito mode for the LBRY app which whatever you watch or do in there will not be saved to your device or any account.

**Comment by tzarebczan** [comment]
We don't plan to support a multiaccount feature in the desktop app. See https://lbry.com/faq/privacy-and-data#anonymous on how to use anonymously.
