### ISSUE TITLE
Managing Wallets options

### ISSUE THREAD

**Issue by trymeouteh** [lbryio/lbry-desktop#6792]
Please add the following features for advanced wallet management in LBRY

- Create wallet (by 12 word phrase)
- Delete wallet (by 12 word phrase)
- View balance in each wallet (by 12 word phrase)
- See if wallet is local wallet or linked to LBRY account (by 12 word phrase)
- Get private keys & word seed of wallet

a LBRY wallet seems to be multiple 12 word phrase wallets merged into a file. Please allow us to edit our wallet to create new 12 word wallets on the fly.

**Comment by tzarebczan** [comment]
We don't plan to support this outside the wallet feature available today in the Desktop app. It aggregates all accounts in a single wallet. You can check  the Help page on how to backup the wallet and see the contents inside. For more information, check out hte API: lbry.com/faq/how-to-cli and wallet /account related calls: https://lbry.tech/api/sdk
