### ISSUE TITLE
Media stats and info

### ISSUE THREAD

**Issue by trymeouteh** [lbryio/lbry-desktop#6793]
Please add the following details when viewing a video, audio or document in the LBRY app.

- See how many nodes are hosting the file
- File size
- Transaction ID (WHere in the blockchain the file is stored)
- Magnet Link
- Metadata

**Comment by tzarebczan** [comment]
Many of these are already avaialble on the content page - click more under the description. 

Nodes hosting isn't as straightforward, not all nodes see all other nodes.

**Comment by trymeouteh** [comment]
I cannot find a magnet link anywhere on the content page for the data

By nodes, It would be nice to have a number on how many people are seeding the file and how many peers are there for the file just like in a bittorrent client to determine the strength of the file on the network
