### ISSUE TITLE
Add a scrollbar or expandable functionality to the Confirmation Modal before uploading

### ISSUE THREAD

**Issue by Eniamza** [lbryio/lbry-desktop#6798]
**Bug**
If you have an extra-large claim Url, Or extra-large description that doesn't fit within the screen, The modal will be over stretched and you won't be able to scroll up or down to see the rest of the info

**To Reproduce**
1. Go to 'https://odysee.com/$/upload'
2. Fillup the claim URL field with extra-long characters such as 1000 A
3. Click upload
4. And see the overly stretched Modal

**Expected behavior**
It should be on-demand expandable and scrollable

**Screenshots**
![image](https://user-images.githubusercontent.com/65225917/128535872-8040af5e-6f33-4b82-9255-0d15594d8207.png)

**System Configuration**

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:
**Used Odysee here so not filling up lol**

**Additional context**
That's all

**Comment by tzarebczan** [comment]
I think we should just prevent really long URLs. They cost lots of LBC and the transaction will most likely fail due to too large of a fee (depending on deposit).

**Comment by Eniamza** [comment]
@tzarebczan For science sake, Instead of extra-long URLs, I used an extra-long title which results in the same issue.
![image](https://user-images.githubusercontent.com/65225917/129042565-54cd6390-47cc-439e-b360-36f7047b376a.png)

There should be some kind of title character limit I guess.

**Comment by tzarebczan** [comment]
We added ellipses for this
