### ISSUE TITLE
 Startup error - 'Unable to load your saved preferences'

### ISSUE THREAD

**Issue by darrenmhill** [lbryio/lbry-desktop#6810]
**Bug**
When starting up the client on Mac (latest version of the client as per today), I get an error page with a red notification stating " Unable to load your saved preferences error". If I clear out config and start the app again, it's fine, but it's an issue using the previously logged in user. No ability to logout or refresh the user settings from the app.
**To Reproduce**
Start the client on Mac (High Sierra) from a previously logged in user (all fine on Odysee).

**Expected behavior**
Client should load with no errors.
**Screenshots**

**System Configuration**

- LBRY Daemon version:
- LBRY App version:
- 0.51.1 (0.51.1)
- LBRY Installation ID:
- Operating system:
- MacOS 0.13.6 (High Sierra)

**Additional context**

**Comment by tzarebczan** [comment]
This is a known issue if you've used your account on the IOS app and will be fixed with the next desktop release.  Shooting for early next week. Sorry for the trouble.

Ticket to track: https://github.com/lbryio/lbry-desktop/issues/6553

**Comment by darrenmhill** [comment]
App was previously starting up fine. This started happening a couple of weeks ago and after the latest release (upgrading from the previous release). My account on Odysee is working fine and even after re-saving and toggling preferences from there and trying the desktop client again, it still fails to load up.

**Comment by darrenmhill** [comment]
> This is a known issue if you've used your account on the IOS app and will be fixed with the next desktop release. Shooting for early next week. Sorry for the trouble.

Wow that's a fast response, yes I have. Thanks!

**Comment by darrenmhill** [comment]
Where can I follow this bug report, as I did search for an existing entry to no avail?

**Comment by tzarebczan** [comment]
#6553
