### ISSUE TITLE
UI subscribed/following channels

### ISSUE THREAD

**Issue by snakyjake1** [lbryio/lbry-desktop#6813]
**Problem**
I would like to see a more intuitive feature that shows my subscribed/following channels.  I explain below...

As a user, from the UI, I can't see the channels I follow.  

From this screenshot, you can't see the channels I subscribe/follow:
![image](https://user-images.githubusercontent.com/8312560/128608605-b6023098-7f8c-4e19-a660-97dea594c2d6.png)

When I click "Following", I'm thinking that menu option will show me the channels I follow.  But what it really shows me is all the content of the channels I follow.  

"Following" is confusing because I'm not 100% sure I understand the differences between "Following" versus "Home".  I don't see any differences.

**Describe the solution you'd like**
I want the "Following" pane to show the channels I follow.

**Describe alternatives you've considered**
If you click the hamburger icon, you can see the list:
![image](https://user-images.githubusercontent.com/8312560/128608626-121b73c5-4122-4b27-b17f-b1a30d22090f.png)

But this is not intuitive.
I also still don't like the way "Following" versus "Home" is implemented.
You may also want to completely remove the hamburger feature, or at least until it offers more significant features.

**Comment by tzarebczan** [comment]
Thanks for the feedback and filing the issue. This would be covered under https://github.com/lbryio/lbry-desktop/issues/5959, but until then, you can use the expanded hamburger bar.
