### ISSUE TITLE
"Paid embed" warning links to lbry.tv

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#6816]
https://odysee.com/$/embed/cat/3b89edbe2aac27ae9cb8bb09b4d837882e827cf4

<img src="https://user-images.githubusercontent.com/64950861/128617536-aaaa0e87-d698-4c44-b094-7fa4dcd44876.png">

**Comment by tzarebczan** [comment]
Thanks again @Eniamza , send me a wallet address on Discord for some appreciation.
