### ISSUE TITLE
Clicking notifications icon displays a dropdown, 'See All' brings you to notification page, both use infinite scroll

### ISSUE THREAD

**Issue by mayeaux** [lbryio/lbry-desktop#6823]
Currently, there's a very nice feature where if you're watching a video you will be alerted in live time of a new notification and it will increment the notification amount. Such as: 
![Screen Shot 2021-08-09 at 15 52 04](https://user-images.githubusercontent.com/7200471/128717529-47b92e18-050e-4161-be4d-3ff9197ba95c.jpg)

However, major sites like Facebook and YouTube have the functionality whereby clicking on this notification will simply drop down a dropdown box, at which point the user can see the notification without having to leave their content. This is especially useful if someone is in the middle of viewing content, and with the dopaminergic effect of wanting to click that notification immediately, and also with the fact that users are already used to another flow, we will probably want to just adopt the standard YouTube/Facebook have set rather than train a user to not click the notification button when they get a new notificaiton.

I'd like to suggest a dropdown with infinite scroll, that also has a 'See All' button that links to the current notification page. Currently the existing notification page doesn't have infinite scroll, pagination was suggested for notifications here ( https://github.com/lbryio/lbry-desktop/issues/6510 )  but as infinite scroll is what YouTube and Facebook does and that it feels really natural (and could also be reused in the dropdown functionality) I'd like to suggest the notifications page also uses infinite scroll.

How Facebook looks/functions:
![Screen Shot 2021-08-09 at 15 56 03](https://user-images.githubusercontent.com/7200471/128718606-58d31927-182a-4bab-85b7-610b98b6f880.jpg)

How YouTube looks/functions:
![Screen Shot 2021-08-09 at 16 01 01](https://user-images.githubusercontent.com/7200471/128718861-5bcb10f4-8695-461d-8360-6317befc4520.jpg)

**Comment by tzarebczan** [comment]
Great write up, will close mine at https://github.com/lbryio/lbry-desktop/issues/6391

**Comment by kauffj** [comment]
@tzarebczan please transfer

**Comment by tzarebczan** [comment]
Issue moved to [OdyseeTeam/odysee-frontend #1417](https://github.com/OdyseeTeam/odysee-frontend/issues/1417) via [**ZenHub**](https://www.zenhub.com/)
