### ISSUE TITLE
Clicking video in playlist doesn't keep playlist in place of "next"/"related" videos

### ISSUE THREAD

**Issue by keikari** [lbryio/lbry-desktop#6837]
**Bug**
Clicking video in playlist doesn't keep the playlist in place of "related" videos. 

**To Reproduce**
1. Go to https://odysee.com/$/list/watchlater
2. Click any of the videos you have there
4. You see "Related" instead of your "playlist" under the player. Happens with all lists. (Reloading the page will show correct behavior.)

**Expected behavior**
Clicking video in playlist should show "playlist" the video belongs to in place of "related" videos.

**Comment by tzarebczan** [comment]
This was fixed in: https://github.com/lbryio/lbry-desktop/commit/dcac5ebcc98c2d7fb3d1e5257a7a6f30cc666b64
