### ISSUE TITLE
Don't reload when "Home" or "Logo" is clicked the 2nd time?

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#6841]
If you click on "Home" or "Logo", and click on it again, the site reloads.  This is annoying, especially on Desktop, where my downloads usually get disconnected (the auto-resume doesn't work reliably).  Also, the caches are gone.

I'm guessing the reason for the reload is it wasn't easy to spark a new `claim_search` when returning to the homepage, to refresh the list of tiles..

**Comment by TomasGonzalez** [comment]
@infinite-persistence Can I work on it? I just have one question are all these issues for the main branch, or are they for the Odysee branch?

**Comment by infinite-persistence** [comment]
> _Can I work on it? I just have one question are all these issues for the main branch, or are they for the Odysee branch?_

@TomasGonzalez, sure. Submit your PR on `master`.
