### ISSUE TITLE
category metadata shows in place of creator channel when using vanity URL

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#6849]
i.e. https://odysee.com/@zubymusic goes to music or https://odysee.com/@zubygaming goes to gaming (fake channel name)

Must be somewhere here: https://github.com/lbryio/lbry-desktop/blob/dbaa702888fb073bfbd8982270481f77bd0fc4f7/web/src/html.js#L64

**Comment by btzr-io** [comment]
Is this still a bug ? Works fine for me.

**Comment by tzarebczan** [comment]
Check their metadata on https://cards-dev.twitter.com/validator
