### ISSUE TITLE
stripe issues

### ISSUE THREAD

**Issue by jessopb** [lbryio/lbry-desktop#6865]
style superchat lbc icon
disable cancel button too when waiting for call to come back

**Comment by tzarebczan** [comment]
The cancel button was disabled in a recent PR.

**Comment by tzarebczan** [comment]
- [ ] light mode channel name not shown 
![image](https://user-images.githubusercontent.com/8120721/129243216-b4c49cf5-8724-4273-bcd6-f5ddbff1d661.png)

**Comment by mayeaux** [comment]
Change stripeEnvironment to be the format of : `const STRIPE_ENVIRONMENT = <condition> ? 'live' : 'test';`
