### ISSUE TITLE
Allow deletion of reposts/content from channel page

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#6873]
Maybe this was lost during the last deletion bug fix 

Edit: not seeing it on regular content either.

**Comment by Eniamza** [comment]
It's already there I guess...
![image](https://user-images.githubusercontent.com/65225917/129409746-72a6270a-ce21-4372-b0cd-4516f7f64265.png)

**Comment by tzarebczan** [comment]
Strange, not seeing it here: 
![image](https://user-images.githubusercontent.com/8120721/129764524-1f21ab84-4acc-4f16-a0e3-b904f98b575d.png)

**Comment by Eniamza** [comment]
For me, it wasn't showing unless I change my default interacting channel to the channel I used for reposting.
![image](https://user-images.githubusercontent.com/65225917/129860667-31cefd1f-e10f-4e25-95ea-a15c15cbbc0f.png)

Maybe try after any activity like commenting from that channel?

**Comment by tzarebczan** [comment]
I'm not seeing it on regular content unless I reselected my active channel.
