### ISSUE TITLE
Drop Down channel Switcher 

### ISSUE THREAD

**Issue by Eniamza** [lbryio/lbry-desktop#6885]
**Is your feature request related to a problem? Please describe.**
Currently an user has to go to the comment section of a post and choose preferred channel that he would like to interact as. Necessary for things such as moderation

**Describe the solution you'd like**
A dropdown channel menu on current channel icon in header area on top right 

**Describe alternatives you've considered**
Comment section 

**Additional context**
Not really

**Comment by Eniamza** [comment]
I may give this a try. That'd also help me to dig into the code more

**Comment by tzarebczan** [comment]
Thanks for looking into it. We'd probably want it coupled with: https://github.com/lbryio/lbry-desktop/issues/5195 - closing this once since it's very similar.
