### ISSUE TITLE
Handle bad channel data in notifications 

### ISSUE THREAD

**Issue by ElectronEsq** [lbryio/lbry-desktop#6887]
Notifications stopped working a few days ago.
When I click on notifications tab, the page breaks.
I've tried in other browsers and get the same issue.

![image](https://user-images.githubusercontent.com/29914179/129542872-0ccf8745-fbc1-411f-9856-4e90458bd172.png)

**Comment by infinite-persistence** [comment]
Any clues from the Console or Network Tab in devtools?

**Comment by ElectronEsq** [comment]
> Any clues from the Console or Network Tab in devtools?

![image](https://user-images.githubusercontent.com/29914179/129557917-5b5ab038-6cd9-485e-bbde-55cbfc76bbc1.png)

**Comment by tzarebczan** [comment]
This is a bug on the comment side, will get the data fixed for you.  Shoot me a DM on Discord with which email it's under .

It would be nice to handle this better on the app side, but it should not happen.

**Comment by tzarebczan** [comment]
This should be fixed now for good!
