### ISSUE TITLE
Send clickstream data on page close

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#6892]
per @jbn

**Comment by tzarebczan** [comment]
https://stackoverflow.com/posts/52412486/revisions

**Comment by tzarebczan** [comment]
Testing to see if this is working with player disposal...Sent Johnny a parent UUID that would appear if it worked.

**Comment by tzarebczan** [comment]
Confirmed it's not working with the dispose fix - we need the beacon api or before unload handling.
