### ISSUE TITLE
File price not showing up properly in search results

### ISSUE THREAD

**Issue by Ruk33** [lbryio/lbry-desktop#6912]
**Bug**
The file price isn't showing up properly in the search results.

![image](https://user-images.githubusercontent.com/1719111/130095515-85c6a392-4479-4fe5-872e-623ca1167f96.png)

**To Reproduce**
1. Open app
2. Search for "music"

**Expected behavior**
The file price shouldn't overflow.

**Screenshots**
![image](https://user-images.githubusercontent.com/1719111/130095649-1987f176-4bb2-4d37-91e0-efc4645d5b2d.png)

**System Configuration**

- LBRY Daemon version:
- LBRY App version: 
- LBRY Installation ID: 5rtRpW1S82tCGZZaTvkVrY4L52xZVpsPv8QAVTKRz63TDFzD7y1BVBycrF85GLSANW
- Operating system: Windows 10

**Additional context**

**Comment by tzarebczan** [comment]
Thanks for filing!
