### ISSUE TITLE
Allow comment section to widen the page (for 4th and 5th level replies)

### ISSUE THREAD

**Issue by JYamihud** [lbryio/lbry-desktop#6920]
As you may know from my comment under [this post](https://odysee.com/@Odysee:8/odysee-ama-announcement:f) on the @Odysee channel that anybody using Non-Lbryio implementation of comments **could make a 4th and 5th level reply.**

Example:
![image](https://user-images.githubusercontent.com/27649397/130231878-d0d6df4d-9380-4ccf-a769-d03fdb0e1813.png)

The only problem is. That the system is not handling it well. I know. It's a bit of a design challenge. But look at this one:

![image](https://user-images.githubusercontent.com/27649397/130232110-4e007bac-e6d5-44cf-91b4-fe1962a79929.png)

There is no way for me to scroll sideways to see this comment. Maybe a simple scroll bar to move the whole page sideways could be done? Or something like an automatic move sideways based on the center of the browser. IDK. Do something...

**Comment by tzarebczan** [comment]
That's why we didn't allow more levels, this is covered under https://github.com/lbryio/lbry-desktop/issues/5362 but this is a good use case for it. Ty!
