### ISSUE TITLE
Allow completely disabling mature content on the LBRY applications

### ISSUE THREAD

**Issue by belikor** [lbryio/lbry-desktop#6923]
This is related to #4550 and #5794.

Some users are very religious and really want to avoid looking at mature content. Therefore, they think that in the LBRY Desktop/Android application a simple checkbox that can be used to enable and disable mature content is not good enough. They want something that removes this option completely.

**Describe the solution you'd like**
A user suggested adding a PIN to be able to change the status of the checkbox, basically adding a further lock to the mature content.

Of course, whenever a lock system (PIN, password) is added the question is what happens if you forget that password. Could this information be stored offline, in the preferences, non-encrypted? Will simply re-installing the LBRY application reset it? I think it should not be very hard to reset the PIN as this is not about safety, it's about a personal preference.

**Describe alternatives you've considered**

- One user mentioned that mature content could be blocked by using a DNS firewall, basically blocking servers that provide this type of content. However, this wouldn't work very well in LBRY because users could exchange this content in a peer to peer fashion.
- Another possibility would be compiling a specific LBRY Desktop/Android application with the mature option disabled by default, with no possibility of turning it again. Too much work only for a single option?

**Additional context**
The idea is to make it harder than it is today to access mature content.

One user said, "imagine a person with an alcohol problem living in the same house where there's an alcohol cabinet; as long as he has the key to the cabinet lock, the lock won't stop him". So, the idea is that a partner or parent, keeps the PIN away from the user of the LBRY application (or that mature content can't be unlocked at all, no alcohol at all).

According to this user, this is an absolute requirement so the big Christian and conservative community help LBRY and Odysee grow.

**Comment by tzarebczan** [comment]
Thanks for the issue, we have something similar filed under https://github.com/lbryio/lbry-desktop/issues/2962 

We won't be releasing two different versions

Not really sure what a pin will do - if someone wants to enable, they will.
