### ISSUE TITLE
Missing "Copy RSS URL"

### ISSUE THREAD

**Issue by snakyjake1** [lbryio/lbry-desktop#6926]
**Bug**
Missing pre-existing feature "Copy RSS URL".

**To Reproduce**
1. Click the channel's ![image](https://user-images.githubusercontent.com/8312560/130340825-215d0297-1b52-4ea1-9e11-af23c127e735.png) button.
2. In the list of options, there used to be a option to "Copy RSS URL".

**Expected behavior**
There should be an option to "Copy RSS URL".

The feature exists on Odysee, by not LBRY Desktop.

**Screenshots**
LBRY (missing):
![image](https://user-images.githubusercontent.com/8312560/130340752-1b136225-3fb2-43af-a2e9-8c5546ac6cfd.png)

Odysee (Exists):
![image](https://user-images.githubusercontent.com/8312560/130340780-d4f13b2a-b8ce-441e-8211-1b0f1b461636.png)

**System Configuration**
- LBRY Daemon version:
- LBRY App version: v0.51.2
- Operating system:  Windows

**Comment by tzarebczan** [comment]
This is an Odysee only feature at this time since it uses an Odysee URL.
