### ISSUE TITLE
Drop-down caret too close to the edge

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#6927]
> _the drop-down carrot seems too close to the right side of the box_
<sub>From `https://github.com/lbryio/lbry-desktop/pull/6821#issuecomment-902239678`</sub>

Examples:
- ![image](https://user-images.githubusercontent.com/64950861/130342618-1b84d970-3a82-4224-a822-4d59be401bff.png)
- ![image](https://user-images.githubusercontent.com/64950861/130342731-cf24fbce-ca89-4c0c-9c1e-b05a26addf3f.png)

**Comment by arschrier** [comment]
Working on a fix for this
