### ISSUE TITLE
Cannot view downloaded content in-app that has been abandoned 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#694]
## The Issue
If you download content at a URL which is later abandoned, you cannot view the content via the LBRY app anymore.  Even though it's on the download page, when you click the tile it then takes you to the URL which is no longer valid, so it shows "There's nothing at this location.".  The app should recognize that this claim is in your downloads and continue to show it.  Not sure if we have all the information about the claim if its abandoned.

### Steps to reproduce
1. Upload content on PC1
2. Download content on PC2
3. Abandon content on PC1
4. Check content in-app on PC2 - "There's nothing at this location."

### Expected behaviour
Still be able to view the content without a valid claim - at least the download location if using the typical claim page doesn't make sense. 

### Actual behaviour
Cannot view content in-app, don't see where it downloaded

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by alyssaoc** [comment]
closing for #1203
