### ISSUE TITLE
Linked-comment scroll position is inconsistent

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#6946]
Linked-comment scroll position a hit-and-miss and is annoying.  Several guesses:

- I think the useEffect is missing a dependency on the ref
- a delay in the linked-comment fetch (a separate call) could cause the position-adjustment to be missed. Maybe use a separate ref
- in Posts, the additional css delay in displaying comments (for better CLS score) can cause the position-adjustment to be missed.

**Comment by tzarebczan** [comment]
Have noticed this too. It seems to work after you refresh also.
