### ISSUE TITLE
[concept] Browser extension as alternative to Electron app

### ISSUE THREAD

**Issue by xliiv** [lbryio/lbry-desktop#6979]
**Is your feature request related to a problem? Please describe.**

Opinion: Browser use seems more intuitive and supports a lot of "standard" features out of the box, like
1. tabs
2. find on page (`ctrl+f`)
3. many more

**Describe the solution you'd like**

I'd like to know, what do you think about replacing/extending current LBRY-Desktop Electron app with something like this .. a background service + browser extension client?

Something similar IPFS Team has done. They have
1. [Electron app](https://github.com/ipfs/ipfs-desktop) as LBRY
2. Plus, [background service](http://docs.ipfs.io.ipns.localhost:8080/how-to/command-line-quick-start/#take-your-node-online) & [browser extension](https://github.com/ipfs/ipfs-companion) which consumes the service

Questions
1. Could it be possible with LBRY?
2. What do you think about such idea? Would you merge it?

**Extra Context**
Another benefit of that approach is better interoperability (?), user can run IPFS on BSD, because
1. the CLI tool is ported
2. Browser extension is just a browser extension it needs browser and "should work"

This is just a concept, so I'd like to know your opinion.

**Comment by tzarebczan** [comment]
Thanks for the suggestion but don't think we'll be doing this anytime soon.
