### ISSUE TITLE
spacing / centering live stream + comments section

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#6984]
There's some weird spacing on the right in various screen sizes and on 4K.

**Comment by infinite-persistence** [comment]
<details>
  <summary>[Duplicate]  6869 Livestream: Fix gap between video and chat</summary>

 
The gap at certain zoom level is distracting.

<img src="https://user-images.githubusercontent.com/64950861/129159705-f8cd0230-717a-4e21-ba1c-fcb6ab0645da.png" width="500">

It is also weird when you zoom all the way out (usually things will be centered):

<img src="https://user-images.githubusercontent.com/64950861/129159905-88c965a9-413a-43d3-bb3a-b884feba5a1e.png" width="400">
</details>

**Comment by tzarebczan** [comment]
Sowwie, I knew you had filed something around that.
