### ISSUE TITLE
Add file size information to claim pages

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#699]
## The Issue
As a user of the app, I'd like to see how big the file is that I'm about to download.

**Comment by liamcardenas** [comment]
@tzarebczan please create dependent issue on lbry schema

**Comment by tzarebczan** [comment]
After speaking to Jack, I updated https://github.com/lbryio/lbryschema/issues/20 to include `contentLength`. Adding as a dependency.

**Comment by kauffj** [comment]
lbryio/lbryschema#20 is like 1/10 battle (if that). The trickier change will be adding support to the daemon to fill this value in from the selected file.

**Comment by tzarebczan** [comment]
Closing for https://github.com/lbryio/lbry-desktop/issues/597
