### ISSUE TITLE
can't reply from notifications - claim id cannot be blank

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#6993]
![image](https://user-images.githubusercontent.com/8120721/131530194-a45dbe70-be9d-4dd3-bb21-caf139bdbc7f.png)

@keikari can you try to repro? Maybe it's with a single channel, or multiple + non-active?

**Comment by keikari** [comment]
I seem to be able to repro with these steps:
1. Have a notification about a comment on your content (not on channel claim)
2. Sign out
3. Sign in 
4. Go to notifications
5. Try to replay to comment on your own content and the error appears.

Going to the content's page or page of the channel which has signed content fixes it.

Behavior doesn't seem to happen with comments on channels.
