### ISSUE TITLE
Just change the default web title to Odysee

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#6994]
@AnantGupta384 commented on [Mon Aug 16 2021](https://github.com/lbryio/odysee-api/issues/359)

The default title on the web based client it **odysee.com** to **Odysee**. Just a non emergency issue. Keep up the great work.
![image](https://user-images.githubusercontent.com/71361442/129545021-4b5448b7-6859-41b1-b531-d7f6c7afd02b.png)

**Comment by kauffj** [comment]
subsumed by #7134
