### ISSUE TITLE
Odysee Autoencoding Compression Issues

### ISSUE THREAD

**Issue by ElectronEsq** [lbryio/lbry-desktop#6997]
This is actually a Odysee bug, but because there's no Odysee repo, I thought I'd put it here.

The problem is this. If you are a channel that has been granted auto encoding, you also lose the ability to share the raw file on Odysee - where the majority of views watch the content.

For example. I recently published, via Odysee, a 3D animation which was set in a dark sense. This made it very susceptible to artefacts when compressed. As a result, to get it looking good and steamtable at the same time, I had to adjust some of the more complex compression options (as suggested in the [YouTube tech docs](https://support.google.com/youtube/answer/1722171)), such as encoding with CBR, keyframes under 2, High Profile, and 2 consecutive B frames.

I tweaked each setting, frame rate and data rate multiple times until I got the best video quality vs streamability.

However, when uploaded to Odysee, my already compressed file was compressed again, but without the correct settings, which meant the artefacts returned leaving the video looking blocky and low quality.

While in most cases the auto encoring is great, it would also be nice if there was an option to use the original file too, which channels that don't have the auto encoding feature already use.

![image](https://user-images.githubusercontent.com/29914179/131604295-42ef6258-1abf-4fcc-81c0-00fde112f14e.png)

**Comment by ElectronEsq** [comment]
I uploaded a bigger file, so when it gets compressed, it'll compress better (a common trick used on other social media platforms). However, now it's not auto encoding. Now the viewers can only use a file that doesn't steam well.

**Comment by tzarebczan** [comment]
This is something we're discussing on the transcoder side for odysee services. I've made sure to bring it up a few times. Right now we compress to heavily.
