### ISSUE TITLE
issue lbry

### ISSUE THREAD

**Issue by marcolazzarinibarga** [lbryio/lbry-desktop#7012]
<img width="901" alt="Screenshot 2021-09-02 at 8 58 05 PM" src="https://user-images.githubusercontent.com/90020149/131948653-e1477b9f-2bfe-4db4-b18e-aefecd7061ac.png">

hi there, is more than @ weeks i can open LBRY on my mac

**Comment by tzarebczan** [comment]
Please make sure to update to the latest version at LBRY.com/get and then send us an email with your details if you continue to have issues at hello@lbry.com
