### ISSUE TITLE
Homepage Performance

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbry-desktop#7017]
![Screen Shot 2021-09-03 at 1 42 09 PM](https://user-images.githubusercontent.com/3402064/132048061-8cd26f14-6bed-48e7-8ba3-e142529e34cd.png)

You can see in the lighthouse profile we have 3 groups of actions happening in the app, on loading of the home page. 

The first group, includes internal-api calls and some initial js files. Then there is a gap in time where there are some resource loading issues. These gaps are important because they are serialized, meaning one cannot happen until the previous is completed. 

The second group are the SDK calls for the app on load. Many are parallel now but you can see 2 that are causing a bunch of delay for the third group. This particular call (the first of the 3rd group) holds up most of the rest. 

So I see a first big opportunity with the following calls:

`https://spee.ch/odysee-white-png:f.png`
`https://odysee.com/public/secondary-265cd729bc4adc414306.js`
these two things are delaying a bigger call to:
`https://api.na-backend.odysee.com/api/v1/proxy?m=version`
which then delays the thumbnails because it alone takes 780ms to return. I would think version should be super fast btw, but that's a separate thing to look at for resource loading, since the network call is fast.

Another point to avoid pre-flight impacts is to do the fastest call first, so that subsequent calls will hit the preflight cache that take longer. 

Past notes: https://www.notion.so/Performance-Investigation-3d889a0fbf474f728c8b9dc442c045ec

**Comment by infinite-persistence** [comment]
@tiger5226 

Your plot looks different from what I usually see.  I don't see the initial gap, and my actual gap is always caused by `claim_search`, and later from thumbnails, before we achieve LCP:

![image](https://user-images.githubusercontent.com/64950861/132444517-dd530ee8-fba1-443c-9dbc-1f4f64bddd77.png)

**Comment by infinite-persistence** [comment]
- Remaining task list moved to https://www.notion.so/Performance-Investigation-3d889a0fbf474f728c8b9dc442c045ec.
- Linking to #6057 for future reference.
