### ISSUE TITLE
Transactions History type mismatching 

### ISSUE THREAD

**Issue by JYamihud** [lbryio/lbry-desktop#7018]
![image](https://user-images.githubusercontent.com/27649397/132090939-a3daba9d-fc86-4c73-a15d-86f898d76f6a.png)

I select Purchase and it gives me Payment. Which I suspect they should be all Purchase.

**Comment by tzarebczan** [comment]
This is a bug on the SDK side as it marks those as payments, which they are. Will make sure it's filed there.
