### ISSUE TITLE
Autoplay setting not syncing across sessions

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#7026]
![image](https://user-images.githubusercontent.com/64950861/132240452-59944f06-a36e-4073-b5e8-14ee3fc32456.png)

I think something in redux repo wasn't updated .

**Comment by infinite-persistence** [comment]
Ah, there's already one open @ 7023

**Comment by saltrafael** [comment]
that guy sounds mad




> I think something in redux repo wasn't updated .

you are right, it is due to the autoplay next change:
https://github.com/lbryio/lbry-redux/search?q=autoplay
https://github.com/lbryio/lbry-desktop/search?q=autoplay_media

**Comment by infinite-persistence** [comment]
> _that guy sounds mad_

lol, yeah. :smile:
