### ISSUE TITLE
Follows + preferences can copy over on Firefox on sign up of a new account

### ISSUE THREAD

**Issue by keikari** [lbryio/lbry-desktop#7030]
**Bug**
Follows + preferences copy over to new account on Firefox on sign up. 
Doesn't seem to happen on brave.
If logging in, the wrong follows may flash on screen but don't get permanently copied over.

**To Reproduce**
(Easier to  repro if first account uses ~dark~ light theme​.)
On Firefox:
1. ​​​Log in to some account which has follows
2. ​​Reload page
3. Log out
(Non-logged in page should still show dark theme. This didn't happen on brave)
4. Create a new account
5. Follows + preferences copy over to the new account​​​​.(Wallet accounts don't merge)
​

**Comment by tzarebczan** [comment]
Sounds like FF is not clearing all  the local state. Thanks for digging into this and reproducing.

**Comment by keikari** [comment]
Fixed on Odysee now, and probably not desktop app thing anyway
