### ISSUE TITLE
Possible responsive menu error

### ISSUE THREAD

**Issue by michaelmitnick** [lbryio/lbry-desktop#7033]
A possible context menu error causes an error when displaying to the Library page in LBRY Desktop. When wanting to delete a content when displaying the contextual menu, it executes a menu action without displaying correctly.

I have watched the video in slow motion and it may have been a double click as the video is not mine. But I'll leave it to be evaluated. It does not give me that error, so it may be a slight responsive error or a double click. The VAR will give the answer.

https://user-images.githubusercontent.com/33647673/132338802-733e9d80-52ca-4d8f-819a-2217324a96f0.mp4

**Comment by jessopb** [comment]
https://github.com/lbryio/lbry-desktop/pull/7335
I thikn this is fixed with this pr
