### ISSUE TITLE
Make it clearer that delegated mods can block via Block menu

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#7035]
We used to show a separate option for delegated mods to block, but now it's all under the same Block option. Some were confused they lost the ability. It's not clear you'll have options afterward. 

We should make a note about timed blocking and delegated blocking (when applicable) on that menu option.

**Comment by kauffj** [comment]
@infinite-persistence if it would make sense for you to tackle this during ongoing work, do grab this. Otherwise we'll assign on Monday
