### ISSUE TITLE
In-app player controls lost if app minimized during stream

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#704]
## The Issue
If you minimize the app after starting a stream and then come back, the player controls are lost.

### Steps to reproduce
1. Start stream
2. Minimize
3. Wait for stream to start playing
4. Maximize app
5. Player control is white

### Expected behaviour
Controls should work

### Actual behaviour
Controls are gone

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
@tzarebczan Is this on a specific OS? I see the controls disappear when minimizing, but they come back when hovering over the video.

**Comment by tzarebczan** [comment]
It may be specific for Windows then. I'll have to try it on Linux. 

Did you minimize right after starting to stream and wait for the stream to finish before bringing it back it?

**Comment by seanyesmunt** [comment]
Didn't wait for it to finish, I'll try that.

**Comment by tzarebczan** [comment]
I just tried it on Linux and it happens there also. The trick is that you have to minimize (I didn't try closing to tray) really quickly after clicking play (while its still buffering) - then it can be brought up once the file starts streaming (or when its done) 

Forgot to attach an image of what it looks like initially. 

![unknown](https://user-images.githubusercontent.com/8120721/32803941-36c33dfe-c953-11e7-8502-83be3dc89b75.png)

**Comment by tzarebczan** [comment]
If its an issue with the player itself, there's probably not much we can do at this time. It's a fairly rare use case (minimizing after trying the stream).

**Comment by LavRadis** [comment]
This issue happened on my Win 10 installation also. In addition, I think that video playing should be paused and/or sound turned off. I left a video to download, minimized in the tray, so when it started playing the sound it was when I was in mid-game. Very distracting.

**Comment by alyssaoc** [comment]
closed, this problem has been solved

**Comment by chron0** [comment]
I have exactly this issue with 0.45.1-rc5 on linux desktop-app, no controls on mouse over, they only appear when klicking and pausing and are gone again when playing.

**Comment by tzarebczan** [comment]
@chron0 I'm not able to reproduce it, but if you can, and it happens consistently, please open a new issue with the exact steps. Thank you!

**Comment by chron0** [comment]
@tzarebczan: I could reproduce the issue in 0.45.0 and 0.45.1-rc5 but so far it's working in 0.45.1 release (both floating vid and restored vid from float now react to the mouse hover with controls as they should) - if it ever comes up again (might be some weird 1px quirk during window resizes) I'll open a separate issue for it.
