### ISSUE TITLE
Subtitles

### ISSUE THREAD

**Issue by nalply** [lbryio/lbry-desktop#7042]
Deaf, hard of hearing and non-native language speakers profit from captioning. Therefore Odysee should strive to offer the same captioning service as Youtube. I don't know how Odysee is getting data from Youtube, but perhaps with a subtitle scraper?

Here an example with Veritasium:

![image](https://user-images.githubusercontent.com/172290/132510101-fc8f6d4b-ccc1-4c3a-9680-d9471d68c735.png)

and on Odysee this looks like this:

![image](https://user-images.githubusercontent.com/172290/132510207-7c6a62f5-2a30-4e38-b755-eec0225fb376.png)

Also see: https://github.com/lbryio/lbry-desktop/issues/6825 and https://github.com/lbryio/lbry-desktop/issues/2325

**Comment by tzarebczan** [comment]
Thanks for the issue. This is covered under #6825 as you mentioned. 

When we do YouTube, it will be under a different repo. 

For now, you can try turning on captioning services in Google chrome to help.
