### ISSUE TITLE
Auto-play next doesn't call "preference_set" when toggled on player

### ISSUE THREAD

**Issue by keikari** [lbryio/lbry-desktop#7044]
**Bug**
Auto-play next doesn't call "preference_set" when toggled on player. And "preference_get" resets the change.
Changing autoplay next  from settings works.

**To Reproduce**
1. Go to any video on Odysee
2. Click on "autoplay next toggle" in the player
3. Wait for "preference_get" call
4. The toggle switches to previous state.

Tested on FF and brave

**Comment by tzarebczan** [comment]
Confirmed this is not related to other sync issues where it may be a timing thing (https://github.com/lbryio/lbry-desktop/issues/5931) . It's not triggered at all.
