### ISSUE TITLE
Brazilian Homepage Maintenance (New User Experience)

### ISSUE THREAD

**Issue by VladHZC** [lbryio/lbry-desktop#7084]
# Brazilian New Users Experience Review

## Email Verification

![](https://i.imgur.com/CpRrIJO.png)

The first verification e-mail must be in Portuguese 

![](https://i.imgur.com/pVLlEVv.png)

The second one is in portuguese but has english subject and the "welcome to Odysee" mighty be the cover alt-text

## Sign Up Page 
![](https://i.imgur.com/ekxho73.png)

In the Sign Up page [LBRY] has been changed for ODYSEE already.

But I can't change the suggested channels, **would be very good for growth if we could suggest our best Brazilian channels here** (same for china and spanish) the creators would get more active followers faster and the new user could easily relate to the famous creators we have in the platform

OBS.: Order BR channels through LBC if its possible 

## Verification Page**

![](https://i.imgur.com/GyqZW7Y.png)

We must **remove telephone option** and urgently change the link in **Verification by Chat** option. Nowadays the user must go into LBRY foundation server which is all closed and in English, **the new chat verification should be in Odysee BR Discord Server**

Link: https://discord.gg/V7c5xukx2g

## The first follower by default 

Now a day we dont have subtitles support, so its not helpfull having only @odysee feed as the first thing the user sees. 

![](https://i.imgur.com/EdlCygY.png)

Solution: 
- Changing default to @OdyseeBR and @Ajuda 

## This Sentence could be in portuguese 

![](https://i.imgur.com/p7ARp6k.png)

**Comment by tzarebczan** [comment]
I'll fix the easy ones, but we'll need to open separate issues for these. Rewards text is outside of this repo and is filed internally.

**Comment by tzarebczan** [comment]
The suggested channels one is fixed

**Comment by tzarebczan** [comment]
Left you a note on Slack about the channel list for recommended following - needs to be done on the homepage side. 

Created https://github.com/lbryio/lbry-desktop/issues/7091 / https://github.com/lbryio/internal-apis/issues/1186 (internal) / https://github.com/lbryio/lbry-desktop/issues/7092 / https://github.com/lbryio/lbry-desktop/issues/7093
