### ISSUE TITLE
Collections: Edit page hangs when 'Anonymous' is selected

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#7087]
_Not sure if this is the same issue mentioned in the meeting._

Try to edit ("Update") an already-published List, or "Publish" a local List.  Select "Anonymous" in the Channel Selector, and the page hangs.  

![Screenshot from 2021-09-14 13-58-56](https://user-images.githubusercontent.com/64950861/133203074-f57b795b-4357-4a5a-b2d0-5ff941b4a292.png)

**Comment by jessopb** [comment]
tried this on new app - no issues. Reopen if it happens again.
