### ISSUE TITLE
[Odysee] Autoplay functional while disabled

### ISSUE THREAD

**Issue by Tcll** [lbryio/lbry-desktop#7090]
first off, I'm not certain where to direct odysee.com issues to, but I'm aware the team works on it...

but as you can see here:
![Screenshot_2021-09-14_09-45-27](https://user-images.githubusercontent.com/773959/133271088-a27f6a9e-2885-4b7a-a824-6c6751c65cf6.png)
at the bottom right, you can see the autoplay switch is off
but I also have autoplay disabled in account settings

there's no reason autoplay should be functional.

only reason I'm bringing it up now, is because the switch would be on when I started my browser
but turning it off wouldn't autoplay until I re-opened the browser
... however now the settings seem to be completely ignored, and it's extremely annoying.

**Comment by tzarebczan** [comment]
Thanks for filing, this is the right repo. Maybe some strange state mismatch - seems to work here as expected. Do you get a notification in the bottom right when you turn on off autoplay? If not, press ctrl-shift-R to make sure you're on the latest version of the site.  Then try to toggle it on and off again to see if that helps. 

@saltrafael anything obvious in the code?

**Comment by Tcll** [comment]
hmm, I've just done a refresh in case un-hibernating the tab and clicking on "Following" doesn't change things.
but I'm currently done watching for the day, so we'll see if that fixes things tomorrow ;)

>  Do you get a notification in the bottom right when you turn on off autoplay?

I did not... the switch seems to be aesthetic only...
but I've refreshed, so we'll see how things go tomorrow :+1:

**Comment by tzarebczan** [comment]
Try a refresh with ctrl-shift-R to make sure the latest version is pulled in. When you toggle/untoggle, it should show you a little message (similar to following/unfollowing someone)

**Comment by Tcll** [comment]
well, I did a refresh, but it didn't change much other than getting the message to appear
turns out the switch is just inverted

or if not that, then the default state of the switch is ignored and overridden by the initial page load defaulting to autoplay enabled
where toggling the switch in whatever state it's initially in disables it
(the switch is on currently, but autoplay is disabled, we'll see if my theory is correct tomorrow if turning it off disables it when I open my browser)

**Comment by tzarebczan** [comment]
Which browser are you using? Haven't heard any other complaints about this, which we did when we weren't saving the setting properly, etc cause it would piss people off :)

**Comment by Tcll** [comment]
yep my extended theory was exactly correct, the switch is ignored when the page is first loaded on browser startup with the setting defaulting to "on" ;)
the switch wasn't inverted today, but should be inverted tomorrow if my theory still stands and isn't fixed by then.

> Which browser are you using?

I currently use Vivaldi, but will be switching to Librewolf when I finally delete this old Linux distro (which is actually progressing), so hopefully there's no issues there. >.>
(Librewolf doesn't run on GLIBC 2.23, so I can't currently use it)

don't forget I also block malware, so that could potentially be another issue if you guys use any for maintaining that setting. :)
(such as how I can't upload images or edit posts anymore here because the menu and upload functionality now uses malware to function)
^ you should be self-hosting a GiTea instance so you don't have to deal with Microsoft malware ;)

**Comment by Tcll** [comment]
just want to update it seems to be working fine today :)
the state of the switch was correctly maintained and autoplay functioned as expected

I'll continue testing just to make sure things are final throughout the week...
if I don't respond with any related errors, if anything at all, this issue can be closed. ;)

here's a preemptive thanks unless I do find something funky :+1:

**Comment by tzarebczan** [comment]
Thanks for the update - really not sure what that may have been. Please re-open if it happens again.

**Comment by keikari** [comment]
I noticed the behavior for me on Odysee. I guess the toggle is showing wrong info?
![auto-play-bug](https://user-images.githubusercontent.com/34790748/134800227-fd6928bb-4c4f-44aa-b9d6-3b9531c0a9b5.png)

**Comment by tzarebczan** [comment]
@saltrafael can you look into this?
