### ISSUE TITLE
Autoplay next in floating player doesn't keep following videos in floating player(see screenshot)

### ISSUE THREAD

**Issue by keikari** [lbryio/lbry-desktop#7100]
**Bug**
See screenshot

**To Reproduce**
1. Have autplay next enabled
2. Start to play any video
3. Navigate to home page 
4. Wait for floating player to auto-play next video
5. Video renders on top of home page. (If on some video's page, video from floating player jumps on top of main player in page)

**Expected behavior**
Auto-played video should also stay in floating player.

**Screenshots**
![floating-player](https://user-images.githubusercontent.com/34790748/133403538-cc7b0d83-a109-4bf7-be4a-8b857215ca8e.png)**System Configuration**

Reported on  Edge 93 on Windows 10
Was able to repro on Firefox on Linux

**Comment by saltrafael** [comment]
FIxed here: https://github.com/lbryio/lbry-desktop/pull/7089 👍
