### ISSUE TITLE
Pagination on the posts page

### ISSUE THREAD

**Issue by michaelmitnick** [lbryio/lbry-desktop#7101]
Possibility of integrating pagination on the posts page, perhaps with a standard amount of 30 posts per page.

**Comment by tzarebczan** [comment]
Majority of users have 1 or 2 channels, so i don't think we'll be doing this anytime soon. Even with a bunch on my test account, still seems to work fine.

**Comment by michaelmitnick** [comment]
Is it the correct page? I mean the posts page, where are the videos/audio, etc.

**Comment by tzarebczan** [comment]
Which page exactly? The channel page where it scrolls infinitely?

**Comment by michaelmitnick** [comment]
Yes, the infinite scroll page. For channels with many posts when wanting to explore more posts.

![image](https://user-images.githubusercontent.com/33647673/133447588-550e5b77-04ab-44d2-a7a7-de084dafd7b1.png)

**Comment by tzarebczan** [comment]
We used to do pagination there but did infinite scrolling instead. Don't think we'll bring pagination back. We do plan to add more filtering and oldest first sorting.
