### ISSUE TITLE
Handle resumable file upload

### ISSUE THREAD

**Issue by rnd** [lbryio/lbry-desktop#7116]
To follow up server implementation to improve publishing flow (see: https://github.com/lbryio/odysee-api/issues/202)
We need to make changes on the clients to support resumable file upload.

These are 4 new endpoints implemented on odysee-api to achieve this:

- [POST]    /v2/publish
- [PATCH]  /v2/publish/{file_id}
- [HEAD]   /v2/publish/{file_id}
- [POST]   /v2/publish/{file_id}/notify

The first 3 are the TUS handlers, we can probably use https://github.com/tus/tus-js-client without much customization on the client side. The last endpoint is the endpoint that the client need to call once the file upload is completed.

### Typical Workflow

- Call [POST] /v2/publish -> tell server to create a file and return the file location
```
curl -i -X 'POST' 'http://localhost:8080/api/v2/publish/' \
 -H 'Upload-Length: 9' \ # file byte size
 -H 'X-Lbry-Auth-Token: foo' 

HTTP/1.1 201 Created
Access-Control-Allow-Headers: content-type
Access-Control-Allow-Origin: *
Location: http://localhost:8080/api/v2/publish/3667753ed69809bbf3a194b3159fd54b
Server: api.lbry.tv
Vary: Origin
Date: Fri, 17 Sep 2021 11:43:25 GMT
Content-Length: 0
```

- Call [PATCH] /v2/publish/{file_id} -> to start or resume upload
```
curl -i -X 'PATCH' 'http://localhost:8080/api/v2/publish/3667753ed69809bbf3a194b3159fd54b' \
     -H 'Upload-Offset: 0' \
     -H 'X-Lbry-Auth-Token: foo' \
     -H 'Content-Type: application/offset+octet-stream' \
     -d 'test file'

HTTP/1.1 204 No Content
Access-Control-Allow-Headers: content-type
Access-Control-Allow-Origin: *
Server: api.lbry.tv
Upload-Offset: 9
Vary: Origin
Date: Fri, 17 Sep 2021 12:21:43 GMT
``` 

- Call [HEAD] /v2/publish/{file_id} -> if the upload is paused or failure because of any network connections error, client need to call this endpoint to retrieve file metadata so the client can resume the upload starting from the file offset returned by the server.
```
curl -i -X 'HEAD' 'http://localhost:8080/api/v2/publish/3667753ed69809bbf3a194b3159fd54b' \
     -H 'X-Lbry-Auth-Token: foo'

HTTP/1.1 200 OK
Access-Control-Allow-Headers: content-type
Access-Control-Allow-Origin: *
Cache-Control: no-store
Server: api.lbry.tv
Upload-Length: 9
Upload-Offset: 9
Vary: Origin
Date: Fri, 17 Sep 2021 12:23:06 GMT
```
- Call [POST] /v2/publish/{file_id}/notify -> once the file upload is completed to notify the lbrynet server.
```
curl -i -X 'POST' 'http://localhost:8080/api/v2/publish/3667753ed69809bbf3a194b3159fd54b/notify' \
     -H 'X-Lbry-Auth-Token: foo' \
     -H 'Content-Type: application/json' \
     '{...json_rpc_payload___}

HTTP/1.1 200 OK
Connection: close
Content-Type: text/plain; charset=utf-8

{
  "jsonrpc": "2.0",
  "result": {
    "height": -2,
    "hex": "..truncated..",
    "inputs": [
      {
        "address": "n4SAW6U5NeYRqQTdos4cLMgtbWRBFW8X16",
        "amount": "5.969662",
        "confirmations": 2,
        "height": 213,
        "is_change": true,
        "is_mine": true,
        "nout": 1,
        "timestamp": 1565587608,
        "txid": "8585fd73e301e58e044581e3f4d2d1195a208e333e8632b75363da2f6ec55ab2",
        "type": "payment"
      }
    ],
    ....
}
```

**Comment by kauffj** [comment]
sweet, thanks @rnd!
