### ISSUE TITLE
playlist item thumbnail previews don't show

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#7122]
These preview thumbnails don't show unless you click into the playlist + go back .  https://odysee.com/@thomas.zarebczan:c?view=lists

![image](https://user-images.githubusercontent.com/8120721/133852521-6c433a82-f9d6-4061-886f-3033033252d5.png)
![image](https://user-images.githubusercontent.com/8120721/133852560-3b9f53b0-0760-4136-8145-753ce7227933.png)

**Comment by ismail6172** [comment]
Uploading images won't work for playlists. You need to paste a link. I recommend an Odysee thumbnail link.
