### ISSUE TITLE
infinite scroll on categories / discover stops working randomly

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#7123]
Not sure when this happens but we've seen a few complaints and have  had it  happen to me. Sometimes happens when you go into a file, then back, and then scroll further. 

Othertimes it may be related to how many tiles are shown at the bottom.

**Comment by infinite-persistence** [comment]
I believe this was caused by my "render-pausing" thingie, which I've reverted in 7115 in favor of a better/proper way through `React.memo`.
