### ISSUE TITLE
Video transrating ideas

### ISSUE THREAD

**Issue by troler36** [lbryio/lbry-desktop#7128]
It would be really useful (especially for those with poor cellular connection) when watching a video there would be a button that would download the video file and transrate it do different resolutions.

Or it could be an automatic process (you could turn off this feature in settings), if X amount of people watch the video or the video has X amount of LBC via LBRY desktop (this would not work on Odysee because we'll require your computer processing power) it would transrate the video.

Or it could be done using the LBRY cryptocurrency. If the video should be transrated will be checked based upon views or the video LBC amount

**Comment by tzarebczan** [comment]
Right now we are transcoding any content that gets more than 250 views and those with 1K (level 5) LBC staked. We hope to improve this to do more content. 

Downloads will always be in their original quality for now.
