### ISSUE TITLE
Channel-Page: comments section shouldn't collapse in Medium Layout

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#7150]
#7108 made a change to enable the "Collapse/Expand" button on Medium layout, because Recommended Section got pulled to the bottom.  But this option doesn't make sense in Channel Page, or when there are no other cards below it.

![Screenshot from 2021-09-22 17-10-52](https://user-images.githubusercontent.com/64950861/134316227-5272334f-cd3f-4c76-be96-6300c6aad1c3.png)

**Comment by tzarebczan** [comment]
I think it collapses in all layouts too https://github.com/lbryio/lbry-desktop/issues/7057

**Comment by infinite-persistence** [comment]
`Duplicate`
Didn't know 7057 existed
