### ISSUE TITLE
improve search metadata

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#7166]
![image](https://user-images.githubusercontent.com/8120721/134730188-f8457095-763b-4a31-a017-a475c96503b3.png)

**Comment by infinite-persistence** [comment]
- [x] Description for the homepage was fixed.
- [x] Manual sitemap, containing Log In, Sign In and Categories was added to hopefully influence the SiteLinks a bit.  But given our automated sitelinks containing tons of claims, the algorithm will mostly pick that up instead.
