### ISSUE TITLE
Look into heavy CPU/render usage during comment display

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#7177]
Similar to https://github.com/lbryio/lbry-desktop/issues/7119, @DispatchCommit thinks that chat message processing/re-renders may be stalling the tabs and creating livestream playback issues. 

![image](https://user-images.githubusercontent.com/8120721/135107035-3c27cc4a-d255-4c38-b7d4-bac57debd222.png)

**Comment by infinite-persistence** [comment]
- [#6473 Comments: CPU maxed out](https://github.com/lbryio/lbry-desktop/issues/6473)
- True. The livestream chat suffers even more since the whole list is re-renders on new message, scrolling, etc.
- If there is a `remark` master available to review our implementation, that would be great too.
