### ISSUE TITLE
Minimize to tray issues on Windows

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#719]
## The Issue
On Windows:
1) After starting LBRY and not clicking anywhere inside the app, right-clicking on the tray context menu does nothing. 
 
2) Only time I can get "Hide App" to show in the tray is when restoring from the tray and on the first right click on the tray icon.

3) When the app in a maximized window and then is minimized to the taskbar (not tray) and you double click the tray icon (or show app), it comes back in a non-maximized state. 

4) Sometimes when I right click on the tray icon, I get the context menu for the taskbar which covers up the app context menu. Seems to happen consistently if I have the app open and right click > show app, and then right click again.  

## System Configuration

 

- LBRY Daemon version: 0.18.0rc1
- LBRY App version:0.18rc1
- LBRY Installation ID:
- Operating system: Windows

**Comment by seanyesmunt** [comment]
@tzarebczan Is this fixed?

**Comment by tzarebczan** [comment]
Nope, those were all minor issues we decided to ship the current app with. They still exist, let me know if you have trouble reproducing any of them.

**Comment by alyssaoc** [comment]
@tzarebczan is this still an issue?

**Comment by tzarebczan** [comment]
Yes, still happening on on the latest build.

**Comment by Ruk33** [comment]
Hello, I can confirm this one is still hapenning:

>When the app in a maximized window and then is minimized to the taskbar (not tray) and you double click the tray icon (or show app), it comes back in a non-maximized state.

The rest, I couldn't reproduce. Do you guys mind if I take this one?

**Comment by tzarebczan** [comment]
Sure, give it a shot, thank you!

**Comment by Ruk33** [comment]
Alright, there we go guys https://github.com/lbryio/lbry-desktop/pull/5265. Sorry for the delay. Regards!

**Comment by kauffj** [comment]
Anyone who regards a 23 hour turnaround time on a volunteer effort as a delay is the kind of person I like. Thank you for this contribution @Ruk33. If you link your channel or an LBC address we'd be happy to send you a thank you, and we hope to see you again :)

**Comment by Ruk33** [comment]
Hello @kauffj , thanks for the kind words :), it was my pleasure and sure, I'm already checking on some other issues to tackle.

My wallet is bN2qyj6U7tjhVUEcaM36hYwVWjPQt678Rs (I don't know if it's allowed to post it in here, if not please let me know I'll remove it).

Regards.

**Comment by kauffj** [comment]
I sent some LBC. Some people think it's a good practice to keep wallet addresses private but IMO it's not a big deal. You can always edit your comment to remove it.

Feel free to work on any issue that is not assigned. If you have questions just leave a comment.

**Comment by Ruk33** [comment]
Hey @kauffj thank you for the coins, I really appreciate it!
