### ISSUE TITLE
There is no Windows system notification when the LBC balance changes and LBRY app is minimized in the tray

### ISSUE THREAD

**Issue by LavRadis** [lbryio/lbry-desktop#720]
## The Issue

When the LBRY app is minimized to tray and LBC wallet balance is changed there is no notification of any kind. 
Since this is an important change, there should be some form of notification. 

### Expected behaviour

If the app is minimized there should be a clear system notification that the wallet balance changed (user received or spent LBC).
It should probably be similar to Win notification when the video has finished downloading. 

## System Configuration

Win 10
App  0.18.0rc1
Daemon 0.18.0rc1
Installation ID 7tYN144rHXrspzJG9xLP28fi1JztXnbpKro6DBJEQyzBmXTyDgqRLfYsUvHYFVmMe2

**Comment by tzarebczan** [comment]
Do you think this should be part of an in-app notification (i.e. https://github.com/lbryio/lbry-desktop/issues/695) or show be a System / OS notification?

**Comment by LavRadis** [comment]
I'm not sure. Most wallets show Win system notification when the balance changes.

**Comment by alyssaoc** [comment]
will consider as part of #695
