### ISSUE TITLE
Notifications do not work with Publications upload not via Odysee.com

### ISSUE THREAD

**Issue by JYamihud** [lbryio/lbry-desktop#7217]
I discovered it accidentally. I was making [this script](https://notabug.org/jyamihud/LBRY-Supported-Comments/src/master/lbry_notifications.py) to view Odysee Notifications without running the whole web-page. ( *BTW, the auth-token could be found in LBRY Desktop in Help or in Odysee.com in inspection mode under Appplication > Cookies.* )

# How I Discovered the Bug?

So I asked a few people to send me comments and notifications didn't work. I asked them to reply to some random comment I placed. And it did work. So I scrolled down to the last publication I had uploaded with odysee.com and comments for that gave a notification.  I haven't tried uploading with LBRY Desktop yet. Maybe comments for that will work as well. I was uploading using [FastLBRY Terminal](https://notabug.org/jyamihud/FastLBRY-terminal), which gives a very basic `publish` request to the SDK to upload something.

# What could cause it?

Probably that on upload the Odysee website is sending some kind of request to Odysee's API in order to start listening to comments for that publication. You can think of it as something like [this script](https://notabug.org/jyamihud/LBRY-Supported-Comments/src/master/stream_messages.py) I use when streaming. It connects to a web-socket api, which sends comments in real time to the receiver. 

The problem with this script and by extension with Odysee's Notification's listener is that for each publication a separate `claim_id` should be added to the list of currently connected web-sockets. Meaning that if I didn't do this API call at upload, the notifications for that upload will not function.

**Comment by tzarebczan** [comment]
Notifications are only supported for channels using the login functions and publishing via signed in desktop or Odysee. This is because we link up the publisher with the account system .

Otherwise an internal API call to the publish endpoint needs to be made along side the publish function.

**Comment by JYamihud** [comment]
That's exactly what I mean. Can you fix it?

**Comment by tzarebczan** [comment]
Unfortunately not, notifications are an Odysee only feature at this time. In the future, the SDK may offer its own notification framework. 

I actually may have misspoke about the publish record, but the person receiving the notification must be a follower and have notifications enabled on the account system. .
