### ISSUE TITLE
Windows .zip folder in releases fails to extract. 

### ISSUE THREAD

**Issue by trueauracoral** [lbryio/lbry-desktop#7229]
**Bug**
In the releases I go the lbry-desktop.zip, I download it and then click extract on my windows computer and it doesn't extract. It says nothing is in the .zip.

**To Reproduce**

**Expected behavior**
What is supposed to happen is that I can go to the releases click on the zip, download and extract.

**Screenshots**

**System Configuration**
I am using a windows computer.

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Additional context**

**Comment by jessopb** [comment]
Reopen if there's a good repro - much has changed with new certificate, etc.
