### ISSUE TITLE
LBRY app changes default .html application when opened

### ISSUE THREAD

**Issue by myfirstnameispaul** [lbryio/lbry-desktop#7237]
**Bug**
Every time I open the LBRY application, it changes the default application for opening `.html` files to LBRY.

**To Reproduce**
1. Verify `.html` files open with something other than LBRY (e.g., Firefox)
2. Open LBRY
3. New default `.html` program is LBRY

**Expected behavior**
Never change any user or system defaults when opening LBRY.

**System Configuration**

- LBRY Daemon version: 0.99.0
- LBRY App version: 0.51.2
- LBRY Installation ID: (field empty in app)
- Platform: Linux (Linux-5.4.0-88-generic-x86_64-with-LinuxMint-20.2-uma)

**Additional context**
I consider this malware behavior.

**Comment by tzarebczan** [comment]
Did you have the LBRY app installed from previously? New installs should not do this, so you may need to remove the association. Check out https://github.com/lbryio/lbry-desktop/issues/4729#issuecomment-774550333
