### ISSUE TITLE
How to clear playback history of videos.

### ISSUE THREAD

**Issue by N3tFX** [lbryio/lbry-desktop#7253]
How to clear playback history of videos played? Currently, if you play a video and stop in the middle of it, the app remembers where it was and resumes playback from that point; instead from the beginning of the video. This is also a privacy issue since it shows which videos where played with a specific client. Where is this information stored and how to delete it?
(I am using the Appimage version in Linux)

**Comment by tzarebczan** [comment]
This is stored in your local browser history at this time. You'd need to clear browser data to clear it out.

**Comment by jessopb** [comment]
The desktop app is an electron app which means it's based on a web browser. It has an internal cache.
There is a button on the bottom of the settings page that clears cache.
It may be a good idea to provide more granular clearing buttons.

**Comment by N3tFX** [comment]
I've just tried it (clear the app cache), and it still remembers the timestamp of the video.

As for the privacy thing, it's for the same reasons you clear the history in any browser. It may not concern many people, but for those that it does, I don't see any problem if there was a tool for it.

**Comment by dgarrett01** [comment]
I'm also interested in how play history is recorded. I've added a checkbox to give the user an option to hide content they have already watched. But, play history is not sync'd across devices. My desktop and my laptop don't reflect the same play history.

Where is this data stored?
