### ISSUE TITLE
Add "meh" option, in addition to "thumbs up" and "thumbs down"

### ISSUE THREAD

**Issue by belikor** [lbryio/lbry-desktop#7256]
**Describe the solution you'd like**
Some videos deserve neither thumbs up (fire) nor thumbs down (slime). Therefore a third option is requested, an indifferent one (meh).

**Additional context**
Requested by Odysee users.

https://odysee.com/@Odysee:8/YouTube-Casting-Couch:9
> @yngdeath: Odysee needs a "Meh" button for videos like this.

**Comment by jessopb** [comment]
Thank you for the idea. We are interested in additional emojis, but probably not this one.
