### ISSUE TITLE
Install fails on Debian-based distros

### ISSUE THREAD

**Issue by ItchyBugReporter** [lbryio/lbry-desktop#7277]
**Bug**
Installing the deb package fails on Debian-based distros  due to a missing dependency that is not available through the official distro repositories.

**To Reproduce**
1. Download the deb package for the latest version of LBRY
2. Install the deb package via `dpkg -i`
3. Run `apt-get -f install` to get the missing dependencies installed
4. Confirm whether you want to remove LBRY despite specifying "install" in the aforementioned command.

**Expected behavior**
apt-get installs all dependencies to make LBRY useable.

**Screenshots**
![LBRY](https://user-images.githubusercontent.com/20482407/141651052-8c2cc4bb-c66e-437c-929f-f84b7fdd12d7.png)

**System Configuration**

- LBRY Daemon version: curl: (7) Failed to connect to localhost port 5279: Connection refused
- LBRY App version: 0.51.2
- LBRY Installation ID: Can't open LBRY to find this due to install failure
- Operating system: Devuan 4.0 Chimaera (based on Debian 11.1.0 Bullseye)

**Additional context**
The issue is with the dependency "libappindicator1", which is not available in the distro repositories.

**Comment by jessopb** [comment]
Devuan appears to be ranked #30 in distros. You may have to install libappindicator1 yourself, either from source or otherwise.

**Comment by ItchyBugReporter** [comment]
How Devuan is ranked anywhere has nothing to do with this bug. The fact that libappindicator1 is not available on Debian-based distros is the only relevant thing here. Check: 

https://packages.debian.org/search?searchon=names&keywords=libappindicator

You will see that both Buster and Stretch are referenced in the search, but Bullseye is *not* referenced. Bullseye is the latest *stable* version of Debian.

This is why libappindicator1 is not available on Devuan Chimaera (the latest stable version of Devuan) -- Devuan tries to match Debian as closely as possible without relying on systemd, so if a package is not available on Devuan and has no reason to require systemd, chances are said package is also not in Debian.

In essence, you are saying that because Devuan ranks 30 on some unsourced list of rankings, all users who are using the latest stable version of Debian (or any distro directly based on the latest stable version of Debian that isn't adding back dropped packages) should have to install libappindicator1 themselves, either from source or otherwise. As most people will be trying to install LBRY on the latest stable version version of their distro (rather than an older version that isn't likely to be supported for long, if it's still supported at all), I don't consider installing from source to be a good solution to satisfying the missing dependency -- many people don't know how to compile software from source, and even among those of us that do there are many of us (myself included) who consider dpkg to be a bit of a complicated mystery (no, that's not an attempt at attacking dpkg -- I just find it a bit difficult to work with for making packages), so getting libappindicator1 installed in a way that dpkg (and thus `apt-get -f install`) will recognized may not be an option for every person that wants to used LBRY.

**Comment by jessopb** [comment]
You're right. I have removed this dependency. It will be out in the next release. I apologize.
