### ISSUE TITLE
Large Account History

### ISSUE THREAD

**Issue by jurgen-74** [lbryio/lbry-desktop#7278]
Dear friends,

I haven't used the LBRY desktop for a while because it doesn't work so great with slow internet. 
Now, I am in a bigger city for a few weeks and I wanted to try it again. When I started the app, I got this message:
'Large Account History... Please Wait'
That's what I did. I waited 1.5 days with almost constant internet connection, but it is not loading anything.
My system is Kubuntu 21.10 Plasma 5.23.3.
LBRY_0.51.2.AppImage
Can someone tell me what I might do wrong here?

Blessings,
Jurgen

**Comment by tzarebczan** [comment]
Can you please try to quit the app with Ctrl-q and try again? 

If it happens again, send an email to hello@lbry.com with the log file (https://lbry.com/faq/how-to-find-lbry-log-file)

**Comment by EvgeneKuklin** [comment]
Hello, I have the same problem, endless "Large account history Please wait..."
In log are endless spam of
```python
Traceback (most recent call last):
  File "lbry\wallet\network.py", line 116, in keepalive_loop
  File "asyncio\tasks.py", line 449, in wait_for
concurrent.futures._base.TimeoutError
```
How to force it to run without wallet? I don't need it anyway
Thanks

[lbrynet.log](https://github.com/user-attachments/files/20756373/lbrynet.log)

**Comment by EvgeneKuklin** [comment]
Looks like the problem is my connection with proxy, connecting with VPN (AmneziaWG) helped
