### ISSUE TITLE
Startup error "Daemon has Exited" on 0.52.0 RC releases (Mac - High Sierra)

### ISSUE THREAD

**Issue by darrenmhill** [lbryio/lbry-desktop#7280]
**Bug**
Critical error with modal showing up on startup. The LBRY client does not start-up after dismissing the modal.

**To Reproduce**
1. Start the LBRY RC client on MacOS after upgrading from 0.51.2 (details of setup below)

**Expected behavior**
Should start with no errors

**Screenshots**
Details of UI error upon startup as follows...

Modal Title: "Daemon has Exited"
Modal Description: "The daemon may have encountered an unexpected error, or another daemon instance is already running. 

For more information please visit: 
https://lbry.com/faq/startup-troubleshooting"

**System Configuration**

MacBook Pro (15-inch, Mid 2010)
MacOS 10.13.6

Results as follows...

curl: (7) Failed to connect to localhost port 5279: Connection refused

- LBRY Daemon version:
Not sure where I can see this, but I updated to LBRY client 0.52.0-rc.5 from the lastest production version (0.51.2)
- LBRY App version:
0.52.0-rc.5
- LBRY Installation ID:
?
- Operating system:
MacOS 10.13.6

**Additional context**
Previous production version 0.51.2 was running fine prior to update. Reverting back from a standard .dmc file works fine. I've also attempted a full restart after an RC install, but the same issue is still present. The same issue was also present on RC3 and RC4.

**Comment by darrenmhill** [comment]
Can this be reproduced by others? I first notices this on 0.52.0-rc3, but it's also a problem with rc5.

**Comment by darrenmhill** [comment]
Attaching a screenshot to support the above bug report.
![Screen Shot 2021-11-19 at 21 39 05](https://user-images.githubusercontent.com/7823744/142694889-11072b8b-7e06-4556-ab8b-2cb2339cb1f4.png)

**Comment by darrenmhill** [comment]
Reverting back to the previous production build is fine. No errors reported.

**Comment by jessopb** [comment]
Hi Darren,
LBRY sdk is now being built on a machine newer than high sierra. We realize this is incompatible with older macs which cannot upgrade, so we're still deciding what to do about this. 

In the mean time, if you're technically inclined, you can install the upgrade and manually replace the lbrynet file with one you build yourself. I just tried these instructions on ubuntu 16 vm and it still works.
https://github.com/lbryio/lbry-sdk/blob/master/INSTALL.md

**Comment by jessopb** [comment]
As Mac and Ubuntu no longer support these versions, we cannot easily support them anymore. A note is made in the changelog directing users to manually compile their own SDK.
Consult the faq for where to find your lbrynet SDK. https://lbry.com/faq/how-to-run-lbry

**Comment by darrenmhill** [comment]
Yikes, ok thanks. I guess another reason to go M1 soon! I'm assuming native M1 builds are on the cards, although I realise it will work via Apple emulator, whatever they call it.

**Comment by skabmedia** [comment]
Thousands, if not millions, of people are stuck with High Sierra on older Macs who don't "support" (meaning Apple made them obsolete to get you to buy new stuff from them) the later macOS-es. And I'm totally fine with that, since I severely dislike the Big Sur+ UI and still have some 32-bit programs I like. I use those actually more than LBRY, so the decision would be easy.

If you want to go forward and let us antique Mac users behind, fine, but then don't claim on your own bloody home page that it still works on Sierra upwards!
