### ISSUE TITLE
[Linux] LBRY takes control of all urls

### ISSUE THREAD

**Issue by TheDrawingCoder-Gamer** [lbryio/lbry-desktop#7284]
**Bug**
Opening any URL causes LBRY to "eat" it and open

**To Reproduce**
1. Install LBRY using DEB
2. Open any URL
3. LBRY opens and not your web browser

**Expected behavior**
Opening URL should open web browser

**System Configuration**

- LBRY Daemon version:0.99.0
- LBRY App version: 0.51.2
- LBRY Installation ID: yUoBwxU9QncUgW9D6TtN1NbBsyEKcScUAZL15nb6dBwKjzu48HbTngSVjKf26YWof
- Operating system: Ubuntu 20.04 (with surface patches)

**Comment by myfirstnameispaul** [comment]
I filed an issue on this was told it isn't happening and they closed the issue.

**Comment by tzarebczan** [comment]
Please see https://github.com/lbryio/lbry-desktop/issues/4729#issuecomment-774550333 if you had older versions installed. Newer versions don't do this anymore.

**Comment by myfirstnameispaul** [comment]
@tzarebczan Maybe you could use version numbers? What is new? What is old?

**Comment by myfirstnameispaul** [comment]
0.51.2 is the only version I have installed.

**Comment by tzarebczan** [comment]
And that was your first time installing LBRY?

**Comment by myfirstnameispaul** [comment]
Correct.

**Comment by TheDrawingCoder-Gamer** [comment]
The earliest I could have possibly installed it is last Thursday which I think is 11/18/21. I don't think there would be a major update in that time 😅

**Comment by jessopb** [comment]
can you paste the lbry.desktop file, possibly located at `/usr/share/applications/lbry.desktop` ?

**Comment by jessopb** [comment]
also, what method are you using to "open a URL"?

**Comment by jessopb** [comment]
It looks like the fix from march got rebroken.
It'll be back for the next release.

**Comment by TheDrawingCoder-Gamer** [comment]
Open an URL; I'm doing it from discord; I assume this means that _any_ external app that opens a web browser opens in LBRY.

**Comment by myfirstnameispaul** [comment]
After opening LBRY desktop, I double-click `filename.html` and LBRY desktop will try (and fail) to open the file.

```text
$ cat /usr/share/applications/lbry.desktop 
[Desktop Entry]
Name=LBRY
Exec=/opt/LBRY/lbry %U
Terminal=false
Type=Application
Icon=lbry
StartupWMClass=LBRY
MimeType=x-scheme-handler/lbry;
Comment=A browser for the LBRY network, a digital marketplace controlled by its users.
Categories=AudioVideo;Video;
```

**Comment by OdinVex** [comment]
> It looks like the fix from march got rebroken. It'll be back for the next release.

Why does it happen in the first place? Nothing should ever be opening with LBRY, it's not a web-browser, it's a portal.

**Comment by jessopb** [comment]
The last fix is explained here https://github.com/lbryio/lbry-desktop/pull/5617

**Comment by jessopb** [comment]
after removing it from ~/.config/mimeapps.list and restarting the app, current fix works.

**Comment by myfirstnameispaul** [comment]
@jessopb Is this fixed with a current PR some place?

**Comment by myfirstnameispaul** [comment]
I decided the best fix is to uninstall LBRY. Since the team here believes that a problem reported to the project's issues should just be fixed for the one person locally, I don't trust this project.

Issues are not for fixing a problem on my computer. They are for fixing problems in your software.

**Comment by jessopb** [comment]
https://github.com/lbryio/lbry-desktop/pull/7291 this was the PR. We haven't been able to get the release out for it as we're waiting for the CSC.
I apologize if I was unclear and seemed to be saying it was your problem. By current fix, I meant this PR.
