### ISSUE TITLE
Make channel default language Elvish

### ISSUE THREAD

**Issue by myfirstnameispaul** [lbryio/lbry-desktop#7285]
**Is your feature request related to a problem? Please describe.**
I regularly block channels that are clearly not English language channels but show up in my English language feed because they pollute the feed with content I cannot consume. However, there seems to be nearly always 5-15% of the videos are something other than English.

**Describe the solution you'd like**
Make default language a not real language, such as Elvish. That way people making channels who for whatever reason don't care to set the language will not pollute feeds of English language users.

**Describe alternatives you've considered**
When text entered contains non-English language text and the language is set to the default English, make a very intrusive and annoying pop-up to ask them to configure their default language.

**Comment by jessopb** [comment]
Thanks for the suggestion. It would be best to make sure the default for creation is whatever their browser/machine is. You can create that issue if you like, and I will label it appropriately.
