### ISSUE TITLE
Why not to create a Rest Api for odysee !!

### ISSUE THREAD

**Issue by sajjadhossanshimanto** [lbryio/lbry-desktop#7288]
I have a list of videos that I want to upload and manage from my python script.

**Comment by tzarebczan** [comment]
It's not publicly documented, but you can check out the various calls that Odysee makes in the network tab. They mirror https://twitter.com/RachelBTCsmith/status/1463890124534472712?t=mSQmpqXW6wOdJJo1MjaXrw&s=19 for the most part.

**Comment by sajjadhossanshimanto** [comment]
It would be better if you document it well so that new develop like me find it more easy to use.
