### ISSUE TITLE
The yarn build generated LBRY_0.52.0-rc.6.AppImage doesn't work

### ISSUE THREAD

**Issue by IceGuye** [lbryio/lbry-desktop#7316]
**Bug**
The latest git master version. Using yarn dev works okay. However, the yarn build generated LBRY_0.52.0-rc.6.AppImage doesn't work. The app window shows only white color.

**To Reproduce**
1. cd lbry-desktop
2. git pull
3. yarn
4. yarn build
5. go to "dist/electron"
6. run the "LBRY_0.52.0-rc.6.AppImage"

**Expected behavior**
The app should run same as what "yarn dev" does.

**Screenshots**
![Screenshot from 2021-12-04 19-35-29](https://user-images.githubusercontent.com/7291463/144729043-d61e62fd-c926-4b48-b1fe-dc2e1a965bbb.png)

**System Configuration**

- LBRY Daemon version: 0.106.0
- LBRY App version: 0.52.0-rc.6 (from the git master though.)
- LBRY Installation ID: 3kTYUQxYf4EDt8HdrihddxTQC8V9UegTAr9Lk4pbTp9zL7TYCQodpZcbFuquSZByVH
- Operating system: Linux (Linux-5.15.6-200.fc35.x86_64-x86_64-with-fedora-35-Thirty_Five)

**Comment by jessopb** [comment]
thanks

**Comment by jessopb** [comment]
https://github.com/lbryio/lbry-desktop/commit/5be27a5e2c1d70c8df3eef9d1281daeff8e40702 I think this revert should have fixed it.
