### ISSUE TITLE
Excessive CPU usage while viewing page with paused video

### ISSUE THREAD

**Issue by Vort** [lbryio/lbry-desktop#7322]
**Bug**
When I open this page:
`lbry://@rossmanngroup#a/a-rant-about-odysee-and-lbry#1`
and pause video (or even do not start it) LBRY.exe begins consuming 7% of CPU resources.
Also sawtooth pattern for RAM usage appears. I checked disk and network usage - they are around zero.
It is too much CPU resource consumption for doing nothing.
For example, Vivaldi browser + the same paused video at `https://www.youtube.com/watch?v=oLRl4WpXffg` uses only 0.3% of CPU.

**To Reproduce**
1. Open URL with LBRY.exe;
2. Pause video (or do not start it);
3. Watch CPU load.

**Expected behavior**
< 1% of CPU load would be fine for me. Ideally, < 0.1%.

**Screenshots**
![image](https://user-images.githubusercontent.com/1242858/144760612-1dc33b6a-0b2a-42c8-807e-96d8037a2e10.png)

**System Configuration**
![image](https://user-images.githubusercontent.com/1242858/144760692-2b49a422-04d0-4321-9245-899492d1d777.png)

**Additional context**

**Comment by jessopb** [comment]
cpu load on windows in my test to repro went to 1% or less if video was paused and mouse wasn't moving around interacting with hovers.
cpu is ~3% or less playing while minimized on windows.
Hopefully recent electron upgrades have improved this.
