### ISSUE TITLE
Incorrect description for first transaction

### ISSUE THREAD

**Issue by Vort** [lbryio/lbry-desktop#7323]
**Bug**
When I installed app and started watching first video, app notified me about 0.2 LBC reward.
The problem is that it had "Email Verified" in description.
I thought that app found my e-mail somewhere on my HDD and sent it to your servers without my consent.

**To Reproduce**
Not sure about exact steps.

**Expected behavior**
It is ok to give new users some credits, but description should be correct.

**Screenshots**
![image](https://user-images.githubusercontent.com/1242858/144762021-5252050e-1989-4101-8819-5dc9d7171c17.png)

**System Configuration**
![image](https://user-images.githubusercontent.com/1242858/144760692-2b49a422-04d0-4321-9245-899492d1d777.png)

**Comment by tzarebczan** [comment]
This bug has been fixed on the backend and will require a verified email now.
