### ISSUE TITLE
Duplicate channel name requires CLI

### ISSUE THREAD

**Issue by 01-1** [lbryio/lbry-desktop#7344]
**Bug**
When creating a duplicate channel name, it gives the error You already have a channel under the name '(channel name)'. Use --allow-duplicate-name flag to override.

**To Reproduce**
1. Create a channel through the GUI.
2. Create another channel with the same name.

**Expected behavior**
There should be a way to enable a duplicate channel name in the GUI, but there isn't.

**Screenshots**
![image](https://user-images.githubusercontent.com/33045716/145732492-8c3cb05b-4fc6-4787-8c6e-8e2b7aee8be6.png)

**System Configuration**
I tried this on multiple systems. both on desktop and android, seems like it's across every platform

**Additional context**
I successfully did it through the CLI though.

**Comment by tzarebczan** [comment]
The app doesn't handle duplicate channels well and only 1 will be usable.

**Comment by jessopb** [comment]
Thanks for the idea. This app probably will not implement this.
