### ISSUE TITLE
Can not sign up using the desktop app ("Please wait a bit, we are still getting your account ready.")

### ISSUE THREAD

**Issue by jogc** [lbryio/lbry-desktop#7358]
Can not sign up using the desktop app on MacOS. I get "Please wait a bit, we are still getting your account ready." combined with "Failed to fetch." each time I click the "Sign Up" button after I have filled in email and password. I also get the same message ("Please wait"...) each time I try to follow someone (when using without being signed in). Watching videos, boosting, tipping and reposting still works fine and I have some LRBY in my balance.

LBRY 0.51.2

**Comment by jessopb** [comment]
Interesting. I just tried on the alpha.9 rc - signed up, signed out, signed in again and it seemed to work.
Not saying you're crazy but maybe apis were down at the time.

**Comment by jessopb** [comment]
closing for now - reopen if it happens more.

**Comment by jogc** [comment]
Actually I have concluded the issue is probably my ancient version of MacOS. I'll re-open if it turns out to not be the case once I upgrade. Thank you.
