### ISSUE TITLE
Thumbnails in suggestions missing the video duration info

### ISSUE THREAD

**Issue by keikari** [lbryio/lbry-desktop#7385]
**Bug**
User reported
Thumbnails in suggestions missing the video duration info

**Screenshots**
![duration-missing](https://user-images.githubusercontent.com/34790748/147860302-77d3f829-734e-43d0-b17d-9f8b81d0e7f6.png)

App | 0.52.0 
Daemon (lbrynet) | 0.106.0

**Comment by rahulrajus** [comment]
Working on this
