### ISSUE TITLE
Comment reply button incorrectly disabled

### ISSUE THREAD

**Issue by ProctorSilex** [lbryio/lbry-desktop#7396]
Click reply to one comment then click reply on a second:
the first reply text editor gets a duplicate and the reply to the second comment can not be submitted until the first comment is either submitted or cancelled (entering text does not enable reply button).
App 0.52.0

**Comment by jessopb** [comment]
Thanks, will fix asap

**Comment by ProctorSilex** [comment]
Forgot a screen, but it sounds like jessopb understood.
![commentreply](https://user-images.githubusercontent.com/55763219/147996720-18cb45af-8131-40ae-a31e-f405f2d5f8e4.png)

**Comment by jessopb** [comment]
I think this is solved assuming advanced editor is allowed in all cases.
