### ISSUE TITLE
Can't set network hosting to unlimited

### ISSUE THREAD

**Issue by fartboxmk2** [lbryio/lbry-desktop#7414]
I can't set Network: Allow (GB) back to unlimited after setting a value, I can change it to anything other than 0.

1. Go to settings > system
2. Set a value for Network: Allow (GB)
3. now try setting it back to unlimited with the value 0 or leaving it blank
4. the old set value doesn't change.

**Comment by jessopb** [comment]
I agree the ui needs to be clearer, and there are some bugs in applying the setting. I'll fix them this week.
At this time according to the sdk implementation, you cannot actually set network sharing to infinite.

**Comment by jessopb** [comment]
Changes coming.
