### ISSUE TITLE
Can't find information how LBRY does NAT Traversal- just out of curiosity

### ISSUE THREAD

**Issue by danielkrajnik** [lbryio/lbry-desktop#7426]
I'm curious to know how LBRY traverses NAT when creating peer-to-peer network? Is it something standard or a homegrown solution?

**Comment by kodxana** [comment]
I do not think LBRY works without port forwarding.

**Comment by jessopb** [comment]
https://lbry.com/faq/host-content this is not exactly correct - for instance, we use same port for both udp and tcp now.
The answer is map the ports on your router (set custom settings per computer in the daemon_settings.yml file), or turn on upnp on your router.
