### ISSUE TITLE
Coinbase purchase widget in app - USD>LBC gateway

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#743]
## The Issue
As a non-crypto user, I would like to have a way to purchase LBRY Credits within the app.  

Since Coinbase has gained popularity and provides a widget to purchase BTC/LTC, we could utilize this to automatically convert the coins to LBC via Shapeshift. Shapeshift does require a return address - hopefully the Coinbase API can provide one but if not, we'd have to support otherwise   

Yours.org has a similar process setup for BCH purchasing. 
![screenshot_20171108-232719](https://user-images.githubusercontent.com/8120721/32791948-2b2fa1ee-c930-11e7-8399-66bc405b18cb.png)

**Comment by littlemadhatter** [comment]
Is this still relevant due to the implementation of MoonPay?

**Comment by kauffj** [comment]
no
