### ISSUE TITLE
Automatic Update For Lbry Desktop for Windows Does Not Work for v0.52.0 to v0.52.2

### ISSUE THREAD

**Issue by ted-kal** [lbryio/lbry-desktop#7466]
**Operating System Version**
- Platform → Windows (Windows-10-10.0.19041-SP0)

**Installation ID**
- 2ZcF4zHm5ZSdiRRGLsybuCUjeaVVt5hZx56gj3U3ZkLBoXLd8fNv95bFQbTY9Xj9e6

**Lbry Desktop Version**
- Update from v0.52.0 to v0.52.2

**Bug Description**

While running v0.52.0 of Lbry Desktop, the program started the automatic update process (*for v0.52.2*). However, it seems the program could not get a successful result from the download process and kept restarting the download in what seems like an endless loop. It ate up over 1GB of my bandwidth before I decided close the program and restart it again to see if the update would complete successfully. It ate up another 1GB of bandwidth before I shut it down again.  Unfortunately, there are no controls inside the application that allow you to stop, pause or start an update, so leaving the program running in this state would slow down my home network and eat up a lot of bandwidth.

Automatic updates are ok when they work, but a lot of people have metered bandwidth connections and this endless downloading behavior could pose a problem. The current update behavior is not user friendly. It would be ideal if the application could provide a **notification and user input** *before* starting an update so a user can at least help monitor and assist with the update process.

**Note**

I've noticed this seemingly endless download behavior with the inability to update in the Windows version of this program since the 0.4*x* versions. **The behavior has been intermittent, with some versions being able to update successfully and other versions not being able to.**

**Resolution**

The only solution to get up and running again seemed to be to a manual update, by downloading and installing the latest version (*0.52.2*) of Lbry desktop from the website.

**Comment by jessopb** [comment]
Auto-update needs a few things - including a switch to disable auto download.

I did windows updates on a fresh windows 10 VM, installed Lbry 0.51.2 and waited. Network was quiet after a bit, and I have the pending update installer for 0.52.2 in `Users\me\AppData\Local\lbry-updater\pending`.
Ignored, cancelled, closed, rejected updates a couple times. 
When I finally ran the update, it failed to update the sdk to 0.106 from 0.99.
