### ISSUE TITLE
LBRY Crashes on watching any video after upgrade to 0.52.2

### ISSUE THREAD

**Issue by goatsrcool** [lbryio/lbry-desktop#7467]
**Bug**
Upgraded from 0.39.1 to 0.52.2.
Trying to watch any video causes LBRY 0.52.2 to crash after a second or two, though I can still hear the video playing in the background.

I ran LBRY in command-line mode and got the following:

```
C:\Program Files\LBRY>lbry /?

C:\Program Files\LBRY>
SDK already running
Sandbox listening on port 5278.
[10:36:55.446] [info] Checking for update
[10:36:56.164] [info] Update for version 0.52.2 is not available (latest version
: 0.52.2, downgrade is disallowed).
[10760:0212/103711.355:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncPar
ametersIfAvailable() failed for 1 times!
```

![lbry_crash](https://user-images.githubusercontent.com/99549374/153719446-547735f5-a70f-4fbb-887c-b535d3508942.png)

**System Configuration**

- LBRY App version: 0.52.2
- LBRY Installation ID: 4CndnGTUR7uN5KbGudPJ7LsasV1S8KGZ3CX9T2zd5BbJ53yEqhFpG8fpNC
TfbBcx1i
- Operating system: Windows 7 Pro x64

**Comment by jessopb** [comment]
Thanks for the report - can you make sure the daemon version under help is 0.106?

**Comment by goatsrcool** [comment]
> Thanks for the report - can you make sure the daemon version under help is 0.106?

Yes, seems to be:

Daemon (lbrynet) | 0.106.0

**Comment by jessopb** [comment]
I'll see if I can make a build for you to test this week.

**Comment by jessopb** [comment]
https://github.com/electron/electron/issues/32317 looking at this now.

**Comment by infinitebus** [comment]
I have the same problem, audio runs behind a Windows appcrash message. Running 0.52.2 in Win7 64-bit. Lbry has been working fine since long, this happened after accepting a recent in-app offer for an update.
Went back to 51.1. It now gave message about "incompatible daemon" and continue anyways, which I did. Worked fine, no appcrash when playing a video.
I then accepeted the in-app offer for 52.5, now it crashes again when pressing play.

**Comment by nemo859** [comment]
I've noticed that adding `--disable-cpu` to the command line when launching LBRY.exe will produce a black screen while the app crashes, and --disable-gpu will produce video and audio playing in the background but the app still crashes.

**Comment by rasskden** [comment]
Hello!
I also faced this problem. Version v0.52.5, Windows 7 x64.
But I've noticed that the app doesn't crash, if the video is initially without sound - I uploaded a video made with sound off and it played fine and the app didn't crash. Maybe this will help...

**Comment by jessopb** [comment]
https://www.electronjs.org/releases/stable?version=15#15.3.5 Thanks for finding this - there seems to be a patch in electron 15.3.5 that fixes media crashes in older windows version. we're on 15.3.2. will try asap!

**Comment by nemo859** [comment]
>patch in electron 15.3.5 that fixes... we're on 15.3.2. will try asap!

Great, thanks hope it fixes the issue, personally I wish there was an option to render the video using libVLC with electronjs, which is possible, though it is more readily convenient for developers to use a BrowserWindow to render video from webkit, I guess that's what is being done here as I saw this same error being discussed for other chromium\webkit based projects. 

Check out the wcjs-player & wcjs-prebuilt modules if you want to go this way, they are node wrappers for the webchimera.js video player, which uses VLC in the background. (I'm not affiliated with them, just currently using the modules for something similar in one of my projects with success so far.)

**Comment by nemo859** [comment]
Also I wanted to say VLC has support for MKV and AVI formats which webkit doesn't support, so that'd be nice too because I have to open some videos on LBRY in VLC now even before it started crashing every time.

**Comment by nemo859** [comment]
I can confirm 0.52.6-alpha-2 currently fixes this crash.

I was able to watch videos with no crashes using it, thanks.

**Comment by goatsrcool** [comment]
Yes 0.52.6-alpha-2 confirmed working here too, thank you B)
