### ISSUE TITLE
Logged in to Odysee but cannot send comments

### ISSUE THREAD

**Issue by erkinalp** [lbryio/lbry-desktop#7468]
**Bug**
When I want to comment, it requests me to create a new channel (my Odysee account already has one). Also unable to see my own comment history. Other wallet server features such as video liking and wallet back up works fine.

**To Reproduce**

Attempt to comment in any video

**Screenshots**
![Ekran görüntüsü 2022-02-12 23-50-31](https://user-images.githubusercontent.com/5833034/153727934-f1bdf2e9-aed1-4335-b7eb-7bdc0a8e0d7a.png)

**System Configuration**

Ubuntu 21.10 amd64
LBRY AppImage 0.52.2

**Additional context**
This issue started in 0.52.2

**Comment by jessopb** [comment]
Thanks for the report - is this still your situation?

**Comment by erkinalp** [comment]
I am busy this week. Will try to reproduce in the weekend.

**Comment by fernandosantucci** [comment]
Same issue on:
Ubuntu 21.10 amd64
LBRY .DEB package 0.52.2

I can't post comments and I can't like comments from other users.

**Comment by jessopb** [comment]
Sorry about this - thanks - we'll have another release out soon.

**Comment by oliveiraleo** [comment]
> Same issue on: Ubuntu 21.10 amd64 LBRY .DEB package 0.52.2
> 
> I can't post comments and I can't like comments from other users.

I can confirm that same behavior after 0.52.2 update on Manjaro Linux, I was searching about the problem and found this issue page. The profile picture isn't showing too (screenshot attached below).

![image](https://user-images.githubusercontent.com/25849028/154120138-38682ffb-39e9-4387-a051-53427f717e2c.png)

Part of the log I extracted from the command line:

```
: {
  "processor": "",
  "python_version": "3.7.12",
  "platform": "Linux-5.15.19-1-MANJARO-x86_64-with-arch-Manjaro-Linux",
  "os_release": "5.15.19-1-MANJARO",
  "os_system": "Linux",
  "lbrynet_version": "0.106.0",
  "version": "0.106.0",
  "build": "release",
  "distro": {
    "id": "manjaro",
    "version": "21.2.3",
    "version_parts": {
      "major": "21",
      "minor": "2",
      "build_number": "3"
    },
    "like": "arch",
    "codename": "Qonos"
  },
  "desktop": "MATE"
}
```
If there's anything else I can test here to help, please, just ping me :)

Thanks in advance.

**Comment by jessopb** [comment]
First, Could you clarify - 
Before upgrading:
You were/were not signed in to odysee?
You did/did not have a channel?

Also, could you ctrl+shift+i into devtools, and watch network tab when you control+r reload, 
tell me if channel_list is returning a response
![image](https://user-images.githubusercontent.com/36554050/154138588-2689671c-13c1-456a-856a-9ac247bbe61f.png)

**Comment by oliveiraleo** [comment]
I was already logged in and already had a channel created. I tried logging out and logging in again more than once but it didn't fix the issue.

Regarding the channel_list, I get a 200 OK answer, so it's fine.

![image](https://user-images.githubusercontent.com/25849028/154159873-7c6e4970-c165-4ce5-89b1-7b65f1e602e0.png)

I don't know if it's related, but once I click the like button below the video player, the LBRY API (https://api.lbry.com/reaction/react) is called and answers with a 200 status code too. However, once trying to click the thumbs up icon on a comment, a component called matomo (https://analytics.lbry.com/matomo.php?action_name=[redacted]) doesn't answer (resulting in a 204 status code)

I saw the last release (0.52.3) some yours ago. Should I upgrade or should I hold until further debugging?

**Comment by jessopb** [comment]
Can you verify the response from the channel_list? it should be json with your channel data in it. verify it's not basically no channels

**Comment by oliveiraleo** [comment]
Of course. Yes, it does have my channel data inside it. Should I look for something in special?

![image](https://user-images.githubusercontent.com/25849028/154162809-5f23a4ea-ec05-4b43-986a-b25f89606309.png)

**Comment by jessopb** [comment]
ok, got a repro, thanks

**Comment by oliveiraleo** [comment]
@fernandosantucci @erkinalp I think I found a workaround. I was messing with the app settings and fixed the config.

If you go to Settings > Content settings > Creator settings > on the menu list on the top left, change `Anonymous` to your account's channel name. Done, your profile picture will load then the video comment and thumbs up on comments functionalities will be working again. 

Interestingly, the Anonymous channel disappears from the list once you select your channel.

**Comment by jessopb** [comment]
I just began the release with the fix - the code to make sure you have an active channel was broken.
