### ISSUE TITLE
Header issues in "small layout + zoomed"

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#7469]
Steps
- 0.52.2
- Press Ctrl + 0 to reset zoom
- Press Ctrl + + to zoom one level 
- Change the window width until it becomes the mobile layout (I was just docking it to the left on a small screen)

Issues
- [ ] The header doesn't make sense with 2 search buttons
- [ ] Subjective: The header button arrangement doesn't look nice (buttons touching, some round 1 oval)
- [ ] In the "Following Page", I can't reach the sort tab (blocked by header)

<img width="585" alt="image" src="https://user-images.githubusercontent.com/64950861/153799127-a838ee9a-148b-4e0b-a787-b4a05a7ebfe9.png">

**Comment by ByronEricPerez** [comment]
Hi @infinite-persistence  , is it still happening? i couldn't reproduce it

**Comment by infinite-persistence** [comment]
Nope, issue no longer exists with the new theme/header.
