### ISSUE TITLE
Post: broken video embed + channel parsing

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#7470]
0.52.2
- [ ] video 1 is not showing (it does on Odysee)
- [ ] video 2: The video embed seems broken, with the poster not showing and the big play button aligned to the left
- [ ] channel name with hyphens are not parsed correctly

`lbry://@dev-test#8/test-embed#b`

<img width="661" alt="image" src="https://user-images.githubusercontent.com/64950861/153799625-7107142a-f3a5-4e6b-8bed-bd8973dc5d48.png">

**Comment by jessopb** [comment]
Oh, those embeds slipped my mind. I guess I removed too much.
