### ISSUE TITLE
Fallout bugs (mainly with comments)

### ISSUE THREAD

**Issue by keikari** [lbryio/lbry-desktop#7471]
From user in discord https://discord.com/channels/362322208485277697/363087331475062785/942431240043257906

・I can't pin my own comment
・I can't edit my own comment, just remove option
・The lbry:// url video-box not showing in comment even channel is at lvl 5 
・Markdown Guide button doesn't redirect to browser when user clicks

**Comment by jessopb** [comment]
Got fixes in for the first three.
What is "markdown guide"?

**Comment by keikari** [comment]
The question mark button, when creating post, used to direct to https://www.markdownguide.org/basic-syntax/

![image](https://user-images.githubusercontent.com/34790748/154043997-2b10f552-d138-4ea3-8c24-8b9c9d2fe70c.png)

**Comment by jessopb** [comment]
Not sure why that doesn't work. Opened a new issue.
https://github.com/lbryio/lbry-desktop/issues/7478
