### ISSUE TITLE
Hamburger menu on macOS is partially behind the window buttons

### ISSUE THREAD

**Issue by kekkyojin** [lbryio/lbry-desktop#7472]
**Bug**

**To Reproduce**
1. Try to expand the sidebar by clicking on the hamburger menu
2. The close/minimize/zoom window buttons will appear over the top section of the hamburger icon region

**Expected behavior**
User should not have to check if it is going to click on any of the window buttons instead of the hamburger menu button

**Screenshots**

![Captura de pantalla 2022-02-14 a las 21 29 24](https://user-images.githubusercontent.com/4984239/153941655-0d275c50-3132-4df2-8db0-11b3830a9475.png)

**System Configuration**

- LBRY Daemon version: 0.106.0
- LBRY App version: 0.52.2
- Operating system: macOS 10.15.7

**Comment by jessopb** [comment]
Thanks!
