### ISSUE TITLE
Broken Markdown article rendering (Blockquotes)

### ISSUE THREAD

**Issue by RmbRT** [lbryio/lbry-desktop#7473]
**Bug**
Markdown rendering in the client application is completely broken for articles starting with a blockquote, it seems. At least my article `lbry://@rmbrt:d/cnet-p2p-doc:3` is rendered wrong. Everything is displayed in a giant blockquote, and all other markdown tags are ignored. On Odysee.com, it renders correctly: https://odysee.com/@rmbrt:d/cnet-p2p-doc:3

**To Reproduce**
Visit the two links in the client and browser, respectively. I think it should be caused by a bug in the client's markdown renderer. The document begins with `>` in the first line, so maybe that's a problem? At least if I insert a newline in the beginning of the article, the preview is correct. You might just be able to fix it by prepending a newline to all markdown files when rendering, LOL. But it's still a worrisome bug.

**Expected behavior**
Client should display exactly the same as odysee.com.

**System Configuration**

- LBRY Daemon version: 0.106.0
- LBRY App version: 0.52.2
- LBRY Installation ID: you're tracking me with this, aren't you?
- Operating system: GNU+Linux

**Comment by Ruk33** [comment]
I'll be working on this one if that's ok.

**Comment by jessopb** [comment]
this fix is already in, (I hope).

**Comment by jessopb** [comment]
If you'd like to do something in that area, there's this:
https://github.com/lbryio/lbry-desktop/issues/7475
Minimally, a iframe -> link, better, extract the source, turn it into a lbry:// and insert that.
