### ISSUE TITLE
Livestream page broken in Medium layout

### ISSUE THREAD

**Issue by infinite-persistence** [lbryio/lbry-desktop#7486]
<img width="643" alt="image" src="https://user-images.githubusercontent.com/64950861/154485990-6aec8060-6cd9-4715-9a05-13846a7e0194.png">

**Comment by Ruk33** [comment]
If it's free, I would like to work on this one.

**Comment by infinite-persistence** [comment]
Sure, go ahead :+1:

**Comment by Ruk33** [comment]
Are live streams not available for lbry? I'm trying a few links, but none of them show the chat window nor the video.
Also, trying to search for "Live Chat" in the code, but I get no results.

**Comment by Ruk33** [comment]
Yes, I talked to @jessopb, and he confirmed this may be an odysee only ticket. Will not continue.
Thanks!
