### ISSUE TITLE
Following feed not updating

### ISSUE THREAD

**Issue by darkalleyrambler** [lbryio/lbry-desktop#7499]
Report a bug for:
- App releases: 0.52.5
- Standalone daemon: 0.106.0

**Bug**
Following list to subscribed channels not updating, stuck about a day or so ago (when I last updated the app I believe). Resetting by clicking the LBRY logo, switching between Home and Following, clearing the cache and restarting the app does not resolve the issue. Not having problem with the mobile app.

**To Reproduce**
Check dates on latest videos in Following Feed and check against mobile app/Odysee

**System Configuration**

{
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "desktop": "Unity",
    "distro": {
      "codename": "focal",
      "id": "ubuntu",
      "like": "debian",
      "version": "20.04",
      "version_parts": {
        "build_number": "",
        "major": "20",
        "minor": "04"
      }
    },
    "lbrynet_version": "0.106.0",
    "os_release": "5.13.0-30-generic",
    "os_system": "Linux",
    "platform": "Linux-5.13.0-30-generic-x86_64-with-debian-bullseye-sid",
    "processor": "x86_64",
    "python_version": "3.7.12",
    "version": "0.106.0"
  }
}

Still not sure if it is app or wallet server related, but I tested best I could before my work call came in. :)

**Comment by darkalleyrambler** [comment]
{
  "background_downloader": {
    "available_free_space_mb": 2,
    "ongoing_download": false,
    "running": true
  },
  "blob_manager": {
    "connections": {
      "incoming_bps": {},
      "max_incoming_mbs": 0.0,
      "max_outgoing_mbs": 0.0,
      "outgoing_bps": {},
      "total_incoming_mbs": 0.0,
      "total_outgoing_mbs": 0.0,
      "total_received": 0,
      "total_sent": 0
    },
    "finished_blobs": 918
  },
  "dht": {
    "node_id": "Just going to assume this is best left private for now",
    "peers_in_routing_table": 60
  },
  "disk_space": {
    "content_blobs_storage_used_mb": 0,
    "published_blobs_storage_used_mb": 131372,
    "running": true,
    "seed_blobs_storage_used_mb": 1022,
    "total_used_mb": 132382
  },
  "ffmpeg_status": {
    "analyze_audio_volume": true,
    "available": true,
    "which": "/usr/bin/ffmpeg"
  },
  "file_manager": {
    "managed_files": 723
  },
  "hash_announcer": {
    "announce_queue_size": 0
  },
  "installation_id": "While supply if needed",
  "is_running": true,
  "skipped_components": [],
  "startup_status": {
    "background_downloader": true,
    "blob_manager": true,
    "database": true,
    "dht": true,
    "disk_space": true,
    "exchange_rate_manager": true,
    "file_manager": true,
    "hash_announcer": true,
    "libtorrent_component": true,
    "peer_protocol_server": true,
    "upnp": true,
    "wallet": true,
    "wallet_server_payments": true
  },
  "upnp": {
    "aioupnp_version": "0.0.18",
    "dht_redirect_set": false,
    "external_ip": "##########",
    "gateway": "No gateway found",
    "peer_redirect_set": false,
    "redirects": {}
  },
  "wallet": {
    "available_servers": 1,
    "best_blockhash": "Just going to assume this is best left private for now",
    "blocks": 1119242,
    "blocks_behind": 0,
    "connected": "spv14.lbry.com:50001",
    "connected_features": {
      "daily_fee": 0.0,
      "description": "",
      "donation_address": "",
      "genesis_hash": "Just going to assume this is best left private for now",
      "hash_function": "sha256",
      "hosts": {},
      "payment_address": "",
      "protocol_max": "0.199.0",
      "protocol_min": "0.54.0",
      "pruning": null,
      "server_version": "0.106.0",
      "trending_algorithm": "fast_ar"
    },
    "headers_synchronization_progress": 100,
    "known_servers": 7,
    "servers": [
      {
        "availability": true,
        "host": "spv14.lbry.com",
        "latency": 0.16573058100038907,
        "port": 50001
      }
    ]
  },
  "wallet_server_payments": {
    "max_fee": "0.0",
    "running": false
  }
}

**Comment by amacchietto** [comment]
Hitting this issue as well when running lbrynet standalone or in the desktop app. Claim searches are stuck to around claims made 2+ days ago.
