### ISSUE TITLE
Respect auto save-to-downloads-folder setting for all file types.

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [lbryio/lbry-desktop#7505]
**Bug**
Not all file types respect the "Save all viewed content to your downloads directory" setting in preferences.  Yes, I know, the preference-description tells me this right up front, but it's better if all file types respect this setting because it avoids user surprises.

**To Reproduce**
1. Verify, in preferences, the "Save all viewed content to your downloads directory" is ticked OFF.
2. Visit any text/markdown content.
3. Just visit it. Take no other action.
4. Find the markdown document resident in your designated Downloads directory.

**Expected behavior**
Only explicitly-downloaded content is saved to my designated Downloads directory, even if the app is unable to render it without an external helper.
(keeping temp files in a temp cache, which is then purged on application termination, is different!)

**System Configuration**
Linux AppImage version 0.52.5

**Comment by jessopb** [comment]
https://github.com/lbryio/lbry-sdk/issues/3582 Made this issue. Closing this one for now.
