### ISSUE TITLE
Upgrade to Yarn v3

### ISSUE THREAD

**Issue by tiziodcaio** [lbryio/lbry-desktop#7529]
**Is your feature request related to a problem? Please describe.**
Hi I will soon open a PR about upgrade yarn to v3. I tested all the workflows and it should work. The advantages are a more clean and readable lockfile, avoiding /maybe) the future EOL of yarn classic. PnP not enable to mantain the compatibility with all the deps.

**Describe the solution you'd like**
Upgraded yarn to v3 using the classic migration. You would notice a huge js file, which is in fact the upgraded version of yarn. In fact yarn from now it will be bundled into your repository

**Describe alternatives you've considered**
Migration to npm, keeping things at it is now

**Comment by jessopb** [comment]
thanks, I think we'll do this.

**Comment by tiziodcaio** [comment]
Sure... On https://yarnpkg.com you will find everything

**Comment by tiziodcaio** [comment]
Now I enabled corepack... [Here](https://nodejs.org/dist/latest-v17.x/docs/api/corepack.html) more details
