### ISSUE TITLE
Live Streaming not working

### ISSUE THREAD

**Issue by heroku-miraheze** [lbryio/lbry-desktop#7540]
**Bug**
Live Streaming is not working.

**To Reproduce**
1. Go to 'lbry://@RT:fd/RTlivestream:8.'
2. See error

**Expected behavior**
Live Streaming is not working.

**Screenshots**
![imagen_2022-04-12_105711702](https://user-images.githubusercontent.com/61781343/162922333-e1723b3c-40af-4f52-9126-aa3d78a8c594.png)

**System Configuration**

- LBRY Daemon version: Latest version
- LBRY App version: Latest version
- LBRY Installation ID: i don't know
- Operating system: Windows 11

**Comment by jessopb** [comment]
maybe when we decentralize live streaming. for now, closing.
