### ISSUE TITLE
Comment box hides icon when hovering over button

### ISSUE THREAD

**Issue by Ruk33** [lbryio/lbry-desktop#7564]
**Bug**
When hovering over the ":)" button, the icon dissapears.

**To Reproduce**
1. Go to one of your channels
2. Click on Community
3. Hover over ":)"

**Expected behavior**
The icon should be visible while hovering.

**Screenshots**

![image](https://user-images.githubusercontent.com/1719111/165323587-f0cee93a-311c-4b73-ba59-3fb3e7861f33.png)
![image](https://user-images.githubusercontent.com/1719111/165323659-619c2acf-55f0-4bb8-88cf-03812df16cf1.png)

**System Configuration**

- LBRY Daemon version: 0.107.1
- LBRY App version: 0.53.1
- LBRY Installation ID: 5rtRpW1S82tCGZZaTvkVrY4L52xZVpsPv8QAVTKRz63TDFzD7y1BVBycrF85GLSANW
- Operating system: Windows (Windows-10-10.0.19041-SP0)

**Additional context**

**Comment by ByronEricPerez** [comment]
i'll be working on this ticket
