### ISSUE TITLE
Remove button for purchased items.

### ISSUE THREAD

**Issue by PixsaOJ** [lbryio/lbry-desktop#7577]
**Is your feature request related to a problem? Please describe.**
I tried to remove the item from Library. I was able to delete downloaded content, but not purchased. 

**Describe the solution you'd like**
In `LBRY Desktop > Library > Purchases` there needs to be remove button.

**Additional context**
Please don't respond with, "Why would you want to delete something you brought?". I have things to hide.

**Comment by jessopb** [comment]
I think this is a fair thing to ask but it is dependent on the following,
https://github.com/lbryio/lbry-sdk/issues/3024
and already filed here.
https://github.com/lbryio/lbry-desktop/issues/5469
