### ISSUE TITLE
LBRY Fail to Start for the 1st Time in OSX HighSierra 10.13.6

### ISSUE THREAD

**Issue by juanpc2018** [lbryio/lbry-desktop#7580]
There are No directories.
https://lbry.com/faq/lbry-directories

https://lbry.com/faq/startup-troubleshooting

LBRY.app has No Forbiden Logo...
waste of time...
0.51.2 "works."
but does Not play Live Streams...
Ok for Static Videos.

0.51.2 Failed 2nd time.

**Comment by jessopb** [comment]
https://github.com/lbryio/lbry-desktop/releases/tag/v0.52.0
Mac <= 10.13 (High Sierra) and Ubuntu <= 16 (Xenial) are no longer supported. If you upgrade, you will need to manually build and install your own lbrynet SDK

I'll put a compatibility note somewhere.
