### ISSUE TITLE
Sound can improve. Linux 0.53.3

### ISSUE THREAD

**Issue by juanpc2018** [lbryio/lbry-desktop#7590]
Very Easy:

#1. Download
https://audio.rightmark.org/products/rmaa.shtml
its a SW version of the AudioPrecision HW version.
works in Wine or PlayOnLinux, PlayOnMac.
but... PlayOn needs manual Manage install, automatic scripts are Down.

#2. Generate the Test Waveforms 48Khz.
#3. Make a video, with the Test Waveforms.
Davinci Resolve is preferable in Linux.
& Upload to LBRY.

#4. Connect the Output of the LBRY SW via Virtual Audio Cable to RMAA.

this part is tricky...
Option A) can be done using 2 computers, 2 sound interfaces, 
Digital Only S/pdif or optical Toslink or optical ADAT, or AES/EBU.

Lynx AES16 has AES/EBU Double Wire preferable "Left = 1x AES /EBU, Right 2x AES/EBU" 
Standard AES/EBU is the same as S/PDIF 1 cable 2 signals but with Balanced/Diferential and Higher Voltage.
Lynx AES16 requires a paid drv. for Linux.
OSS Not Alsa.
http://manuals.opensound.com/devlists/Linux.html
http://manuals.opensound.com/devlists/lynxtwo.html
http://www.opensound.com/oss.html
https://en.wikipedia.org/wiki/Open_Sound_System

RME hdsp 9632 is better for Alsa, Free Drv..
USB Focusrite 18i20 mk2  or Clarett 8pre can work but needs Windows or Mac to configure the DSP i/o.
etc...
Play Computer Master Clock
Recording Computer Slave to External Clock.

Option B) use a Loopback Virtual Cable, QJackCtl, jackd2 in Linux.
jackOSX 
https://jackaudio.org/downloads/
https://github.com/jackaudio/jack2-releases/releases
but...
LBRY does Not have Jackd2 support?
https://vb-audio.com/Cable/
https://rogueamoeba.com/freebies/soundflower/
https://vac.muzychenko.net/en/
https://github.com/mattingalls/Soundflower/releases
https://rogueamoeba.com/loopback/buy.php

Option C) Use a Network Audio driver + RJ45 CAT5a or better, or Optical Lc-Lc
similar to Dante or Ravena...
https://my.audinate.com/support/downloads/dante-virtual-soundcard
https://nerds.de/en/loopbeaudio.html
https://www.merging.com/products/alsa_ravenna_aes67_driver
https://www.merging.com/products/aes67_vad_standard

#5. Analyze the Playback Recorded Loopback Audio in RMAA.

P.D. Using Analog Loopback Audio introduces more variables, Not Recommended for this test.

**Comment by jessopb** [comment]
This seems like a tip for users that belongs in a wiki somewhere?
