### ISSUE TITLE
LBRY About goes to https://

### ISSUE THREAD

**Issue by juanpc2018** [lbryio/lbry-desktop#7597]
i think, IF i have LBRY installed,i probably know what is it...

thats Not what im looking for...,
im looking to know the build version number, like all other apps & browsers.

i dont want to close LBRY, open Synaptic or Muon, or App store, or Snap, or Terminal to know what version i have installed.
a waste of time.

**Comment by jessopb** [comment]
I think the Help...About you're looking for is under Help in the top gear menu. We'll review those sidebar footer item.
