### ISSUE TITLE
Problem with verify phone number in cambodia 

### ISSUE THREAD

**Issue by HORKimhab** [lbryio/lbry-desktop#7608]
** Please check verify phone number in Cambodia ** 
Prefix code: **KH +855**. 
I input phone number correctly with prefix 0 or not still can't submit or appear error msg. (e.g 096....4 or 96....4). 

Thank you. 
#HKimhab

**Comment by jessopb** [comment]
This issue should be on [odysee](https://github.com/OdyseeTeam/odysee-frontend) repo.
