### ISSUE TITLE
IPv6 support?

### ISSUE THREAD

**Issue by WillWill56** [lbryio/lbry-desktop#7611]
**Is your feature request related to a problem? Please describe.**
The lbrynet daemon doesn't seem to listen for or accept IPv6 connections. The only exception is that there seems to be a connection between the lbrynet daemon and lbry desktop client that is made using the IPv6 loopback address.

**Describe the solution you'd like**
Ideally, the lbrynet daemon should take advantage of IPv6 where available, to create a much healthier P2P network.

**Describe alternatives you've considered**
Using IPv4 and port forwarding when behind a NAT is feasible for someone who wants to contribute to the P2P network, but IPv4 addresses are in such short supply now that many people end up behind a CGNAT/double-NAT, which makes this impossible.

**Additional context**
n/a

**Comment by EinoHR** [comment]
Since this is about lbrynet, you should close the issue here and move to https://github.com/lbryio/lbry-sdk/issues, the repository for lbrynet aka lbry-sdk.

**Comment by WillWill56** [comment]
Alright, I'll move it over there. Wasn't 100% sure as I didn't notice any descriptions that explicitly pointed out lbry-sdk as being the dedicated daemon for LBRY peer-to-peer stuff. The name itself makes it sound like, well, an sdk, not a daemon/service.
