### ISSUE TITLE
Hosting Directory

### ISSUE THREAD

**Issue by juanpc2018** [lbryio/lbry-desktop#7633]
Content Hosting seems odd,
where are the Files?

System
Download directory
LBRY downloads ?

That folder is Empty.
  
Hosting seems bogus / shady
needs to have a:
Hosting Folder/directory...

**Comment by EinoHR** [comment]
The content you host is in form of so-called encrypted blob files. The directories where the files are located can be found here https://lbry.com/faq/lbry-directories, the item which specifies "encrypted blob files" under your system's name.

Downloading consumed content to your Downloads directory (or any other directory specified) is entirely optional, as is keeping and distributing the blob files.

In the future, please direct your questions about LBRY, which are not bug reports or feature requests or anything of that sort, to either the LBRY Forums (https://forum.lbry.com/) or the LBRY Foundation Discord (https://discord.gg/YWhcC7ftBs), or if Odysee related to the Odysee Discord (https://discord.gg/odysee).

**Comment by jessopb** [comment]
https://github.com/lbryio/lbry-desktop/issues/1966 This issue agrees. Will catch up with sdk team about it.
