### ISSUE TITLE
Thumbnails Should Remain Optional

### ISSUE THREAD

**Issue by ismail6172** [lbryio/lbry-desktop#7641]
There are valid reasons why people wouldn't need thumbnails such as if they are uploading archives. LBRY is a file agnostic client therefore for that reason alone it should be optional.

**Comment by ByronEricPerez** [comment]
I will work on this.

**Comment by jessopb** [comment]
@ByronEricPerez Do you Still intend to do this?

**Comment by ByronEricPerez** [comment]
Hi @ismail6172,  you mean this right?

![image](https://user-images.githubusercontent.com/89370060/187522794-4fb6d6a1-f9b9-4aed-a419-04c83f82d5fe.png)

**Comment by jessopb** [comment]
This is done. Wanted to get it out.

**Comment by ByronEricPerez** [comment]
Hello @jessopb , I did not understand your message, do you ask me if I finished it, or did you tell me that it is already finished?

![image](https://user-images.githubusercontent.com/89370060/191280572-86e53491-7fb5-4e9c-9e74-a5111fa0a33a.png)

**Comment by jessopb** [comment]
It's all set. I wasn't sure when you'd get to it.
