### ISSUE TITLE
LBRY having same problem as Odysee = Super Slow Speed.

### ISSUE THREAD

**Issue by juanpc2018** [lbryio/lbry-desktop#7656]
LBRY official chanel version for Linux v0.53.4
has become incompatible "useless".
Needs update to latest test version v0.53.5
https://github.com/lbryio/lbry-desktop/releases

other ways to access the Network are using other Front Ends.

FastLBRY-GTK
Librarian Instance
https://codeberg.org/librarian/librarian
Madiator.com
https://github.com/libredirect/LibRedirect
etc....

LBRY needs to create a Realtime Network Health Map of the Globe.
something like:
https://bitnodes.io/
https://bitnodes.io/nodes/live-map/
but more 3D
like NOIA:
https://invidious.namazso.eu/watch?v=n1TcRgKuhac
or:
http://covidvisualizer.com

**Comment by kauffj** [comment]
Can you elaborate on what's slow? The app itself, the video playback, something else?

**Comment by juanpc2018** [comment]
the problem in LBRY is solved by installing the latest test version.
most videos play in 3 seconds, some have buffer hiccups.

the problem in Odysee is super long latency to load buffer "play",  waiting...
does Not start loading,
interrupted video "buffer is depleted very fast", low quality / bandwidth, 
like using a Dial-Up 28.8K modem with noisy phone line.
