### ISSUE TITLE
LBRY New SDK Broken Comments

### ISSUE THREAD

**Issue by juanpc2018** [lbryio/lbry-desktop#7661]
Odysee comments are working ok in Odysee website.

LBRY for Linux, does Not load Comments.
New SDK a few versions back broken the comment servers...

is Not Only Odysee coment server,
its also Madiator comments server.

Broken.
LBRY sdk has become incompatible with comments servers.

P.D. im Not banned because i log in to Odysee with same account as LBRY.
Same IP.
Same OS.
Odysee works ok, exept the Video quality in this side of the Network,
if using a VPN, Quality improves... its a Network bottleneck.

Anyway...
When you Type a Banned word in Odysee, Odysee website warns you, that the comment is banned,
very nice,
instead YouTube shadow bans, makes you think the comment was posted.
but only you can see your comment.

Odysee method is much better.

**Comment by keikari** [comment]
Comments seem to load fine here on v0.53.5-t109 when connected to Odysee comment server.  

Does it show any errors for you?  
Can you check if there are any errors in responses to comment related network calls in dev tools (Ctrl + Shift + i)

**Comment by juanpc2018** [comment]
madiator server v2 has Json error = Network Status 502
https://comments.madiator.com/api/v2

since the SDK update.

----

odysee server
400 network erros.

{
    "success": false,
    "error": "Watch more content to get to the next level.",
    "data": null
}
{
    "success": false,
    "error": "the reward is not supposed to be visible to you, but here we are.",
    "data": null
}

**Comment by juanpc2018** [comment]
there is also a lot of wallet balance requests.

**Comment by juanpc2018** [comment]
https://watchman.na-backend.odysee.com/reports/playback
{"name":"invalid_range","id":"K9-TXwOS","message":"body.duration must be lesser or equal than 60000 but got value 766570","temporary":false,"timeout":false,"fault":false}

(anonymous) @ file:///opt/LBRY/resources/app.asar/ui.js:2
u @ file:///opt/LBRY/resources/app.asar/ui.js:2
(anonymous) @ file:///opt/LBRY/resources/app.asar/ui.js:2
(anonymous) @ file:///opt/LBRY/resources/app.asar/ui.js:2
n @ file:///opt/LBRY/resources/app.asar/ui.js:2
l @ file:///opt/LBRY/resources/app.asar/ui.js:2
(anonymous) @ file:///opt/LBRY/resources/app.asar/ui.js:2
(anonymous) @ file:///opt/LBRY/resources/app.asar/ui.js:2
le @ file:///opt/LBRY/resources/app.asar/ui.js:2
(anonymous) @ file:///opt/LBRY/resources/app.asar/ui.js:2
u @ file:///opt/LBRY/resources/app.asar/ui.js:2
(anonymous) @ file:///opt/LBRY/resources/app.asar/ui.js:2
(anonymous) @ file:///opt/LBRY/resources/app.asar/ui.js:2
n @ file:///opt/LBRY/resources/app.asar/ui.js:2
l @ file:///opt/LBRY/resources/app.asar/ui.js:2
(anonymous) @ file:///opt/LBRY/resources/app.asar/ui.js:2
(anonymous) @ file:///opt/LBRY/resources/app.asar/ui.js:2
re @ file:///opt/LBRY/resources/app.asar/ui.js:2
videoIsPlaying @ file:///opt/LBRY/resources/app.asar/ui.js:2
(anonymous) @ file:///opt/LBRY/resources/app.asar/ui.js:2
(anonymous) @ file:///opt/LBRY/resources/app.asar/ui.js:2
r.dispatcher.r.dispatcher @ file:///opt/LBRY/resources/app.asar/ui.js:2
wr @ file:///opt/LBRY/resources/app.asar/ui.js:2
trigger @ file:///opt/LBRY/resources/app.asar/ui.js:2
n.handleTechPause_ @ file:///opt/LBRY/resources/app.asar/ui.js:2
(anonymous) @ file:///opt/LBRY/resources/app.asar/ui.js:2
r.dispatcher.r.dispatcher @ file:///opt/LBRY/resources/app.asar/ui.js:2

fetch("https://watchman.na-backend.odysee.com/reports/playback", {
  "headers": {
    "accept": "application/json",
    "accept-language": "en-US",
    "content-type": "application/json",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "cross-site"
  },
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"rebuf_count\":1,\"rebuf_duration\":1325,\"url\":\"@whatdamath#8/strangest-galaxies-in-the-universe,-ring#a\",\"device\":\"dsk\",\"duration\":766570,\"protocol\":\"stb\",\"player\":\"\",\"user_id\":\"375630884\",\"position\":972000,\"rel_position\":100,\"bitrate\":2278609}",
  "method": "POST",
  "mode": "cors",
  "credentials": "omit"
});

fetch("https://watchman.na-backend.odysee.com/reports/playback", {
  "headers": {
    "accept": "application/json",
    "accept-language": "en-US",
    "content-type": "application/json",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "cross-site"
  },
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"rebuf_count\":1,\"rebuf_duration\":1325,\"url\":\"@whatdamath#8/strangest-galaxies-in-the-universe,-ring#a\",\"device\":\"dsk\",\"duration\":766570,\"protocol\":\"stb\",\"player\":\"\",\"user_id\":\"375630884\",\"position\":972000,\"rel_position\":100,\"bitrate\":2278609}",
  "method": "POST",
  "mode": "cors"
});

curl 'https://watchman.na-backend.odysee.com/reports/playback' \
  -H 'authority: watchman.na-backend.odysee.com' \
  -H 'accept: application/json' \
  -H 'accept-language: en-US' \
  -H 'content-type: application/json' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) LBRY/0.53.5-t109 Chrome/94.0.4606.81 Electron/15.4.0 Safari/537.36' \
  --data-raw '{"rebuf_count":1,"rebuf_duration":1325,"url":"@whatdamath#8/strangest-galaxies-in-the-universe,-ring#a","device":"dsk","duration":766570,"protocol":"stb","player":"","user_id":"375630884","position":972000,"rel_position":100,"bitrate":2278609}' \
  --compressed

**Comment by juanpc2018** [comment]
https://watchman.na-backend.odysee.com/reports/playback

{"message":"rebufferung duration cannot be larger than duration"}

(anonymous) @ file:///opt/LBRY/resources/app.asar/ui.js:2
u @ file:///opt/LBRY/resources/app.asar/ui.js:2
(anonymous) @ file:///opt/LBRY/resources/app.asar/ui.js:2
(anonymous) @ file:///opt/LBRY/resources/app.asar/ui.js:2
n @ file:///opt/LBRY/resources/app.asar/ui.js:2
l @ file:///opt/LBRY/resources/app.asar/ui.js:2
(anonymous) @ file:///opt/LBRY/resources/app.asar/ui.js:2
(anonymous) @ file:///opt/LBRY/resources/app.asar/ui.js:2
le @ file:///opt/LBRY/resources/app.asar/ui.js:2
(anonymous) @ file:///opt/LBRY/resources/app.asar/ui.js:2
u @ file:///opt/LBRY/resources/app.asar/ui.js:2
(anonymous) @ file:///opt/LBRY/resources/app.asar/ui.js:2
(anonymous) @ file:///opt/LBRY/resources/app.asar/ui.js:2
n @ file:///opt/LBRY/resources/app.asar/ui.js:2
l @ file:///opt/LBRY/resources/app.asar/ui.js:2
(anonymous) @ file:///opt/LBRY/resources/app.asar/ui.js:2
(anonymous) @ file:///opt/LBRY/resources/app.asar/ui.js:2
re @ file:///opt/LBRY/resources/app.asar/ui.js:2
videoIsPlaying @ file:///opt/LBRY/resources/app.asar/ui.js:2
(anonymous) @ file:///opt/LBRY/resources/app.asar/ui.js:2
sl @ file:///opt/LBRY/resources/app.asar/ui.js:2
Es @ file:///opt/LBRY/resources/app.asar/ui.js:2
t.unstable_runWithPriority @ file:///opt/LBRY/resources/app.asar/ui.js:2
Gi @ file:///opt/LBRY/resources/app.asar/ui.js:2
xs @ file:///opt/LBRY/resources/app.asar/ui.js:2
(anonymous) @ file:///opt/LBRY/resources/app.asar/ui.js:2
F @ file:///opt/LBRY/resources/app.asar/ui.js:2
x.port1.onmessage @ file:///opt/LBRY/resources/app.asar/ui.js:2

fetch("https://watchman.na-backend.odysee.com/reports/playback", {
  "headers": {
    "accept": "application/json",
    "accept-language": "en-US",
    "content-type": "application/json",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "cross-site"
  },
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"rebuf_count\":1,\"rebuf_duration\":1325,\"url\":\"@whatdamath#8/strangest-galaxies-in-the-universe,-ring#a\",\"device\":\"dsk\",\"duration\":7,\"protocol\":\"stb\",\"player\":\"\",\"user_id\":\"375630884\",\"position\":972000,\"rel_position\":100,\"bitrate\":2278609}",
  "method": "POST",
  "mode": "cors",
  "credentials": "omit"
});

fetch("https://watchman.na-backend.odysee.com/reports/playback", {
  "headers": {
    "accept": "application/json",
    "accept-language": "en-US",
    "content-type": "application/json",
    "sec-fetch-dest": "empty",
    "sec-fetch-mode": "cors",
    "sec-fetch-site": "cross-site"
  },
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": "{\"rebuf_count\":1,\"rebuf_duration\":1325,\"url\":\"@whatdamath#8/strangest-galaxies-in-the-universe,-ring#a\",\"device\":\"dsk\",\"duration\":7,\"protocol\":\"stb\",\"player\":\"\",\"user_id\":\"375630884\",\"position\":972000,\"rel_position\":100,\"bitrate\":2278609}",
  "method": "POST",
  "mode": "cors"
});

curl 'https://watchman.na-backend.odysee.com/reports/playback' \
  -H 'authority: watchman.na-backend.odysee.com' \
  -H 'accept: application/json' \
  -H 'accept-language: en-US' \
  -H 'content-type: application/json' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: cross-site' \
  -H 'user-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) LBRY/0.53.5-t109 Chrome/94.0.4606.81 Electron/15.4.0 Safari/537.36' \
  --data-raw '{"rebuf_count":1,"rebuf_duration":1325,"url":"@whatdamath#8/strangest-galaxies-in-the-universe,-ring#a","device":"dsk","duration":7,"protocol":"stb","player":"","user_id":"375630884","position":972000,"rel_position":100,"bitrate":2278609}' \
  --compressed

**Comment by keikari** [comment]
Do comments work for you on older versions of the app?

**Comment by juanpc2018** [comment]
LBRY[v0.53.3](https://github.com/lbryio/lbry-desktop/releases/tag/v0.53.3)
was working ok until [v0.53.4](https://github.com/lbryio/lbry-desktop/releases/tag/v0.53.4)
SDK change...

i cannot test older versions, because do Not play video.
https://github.com/lbryio/lbry-desktop/issues/7656

[v0.53.3](https://github.com/lbryio/lbry-desktop/releases/tag/v0.53.3)
Play video, but Comments have issues.
Odysee its intermitent issue,
Madiator is permanent issue since 0.53.4

**Comment by keikari** [comment]
Don't think SDK affecting comments (also SDK update in v0.53.4 was very minor) Currently Odysee comments working fine here on 53.4.  
What's the exact issue on Odysee comment server, do you mean that it errors if you send too many requests?  

Madiator probably needs to fix something on his server.  

What do you mean with "Credit / coin counter"? Do you mean that balance shows incorrectly?
In that case, try to add this in your daemon_settings.yml and restart:
```
lbryum_servers:
  - spv16.lbry.com:50001
```

**Comment by juanpc2018** [comment]
Yes, Balance do Not increase, unless i log-in to Odysee Web,
then it jumps.

**Comment by juanpc2018** [comment]
/usr/share/applications/lbry.desktop
```
[Desktop Entry]
Name=LBRY
Exec=/opt/LBRY/lbry %U
Terminal=false
Type=Application
Icon=lbry
StartupWMClass=LBRY
MimeType=x-scheme-handler/lbry;
Comment=A browser for the LBRY network, a digital marketplace controlled by its users.
Categories=AudioVideo;Video;
```

$ whereis lbry
lbry: /usr/bin/lbry

/opt/LBRY/resources/static/daemon

dont know where is daemon_settings.yml

**Comment by juanpc2018** [comment]
Found it..

**Comment by keikari** [comment]
If you are talking about rewards, those were removed from the desktop app.

**Comment by juanpc2018** [comment]
what is the incentive to use the App?

**Comment by keikari** [comment]
I think LBRY app is made so there is a easy/convenient way to use LBRY.
  
What do you mean with "Opening Odysee Web Updates LBRY Desktop balance"? 
Is balance wrong before you open Odysee, and how much is it off?

**Comment by juanpc2018** [comment]
> 
> Madiator probably needs to fix something on his server.
> 

@kodxana

**Comment by kodxana** [comment]
> > Madiator probably needs to fix something on his server.
> 
> only he can know: @kodxana
> 
> i think the problem is LBRY-Desktop

Yes my server is offline working on brining it back.

**Comment by juanpc2018** [comment]
> I think LBRY app is made so there is a easy/convenient way to use LBRY.
> 
> What do you mean with "Opening Odysee Web Updates LBRY Desktop balance"? Is balance wrong before you open Odysee, and how much is it off?

LBRY-Desktop stop updating Balance...
i watch 1 week, 2 week of videos, 
Balance in LBRY Desktop does Not change...

i open Odysee Web, Balance Updates on LBRY Desktop.

**Comment by keikari** [comment]
It sounds like you are talking about rewards. And those don't exist on the LBRY desktop app anymore, so sounds like expected/intended behavior.

**Comment by jessopb** [comment]
App has updates, should be fine now.
