### ISSUE TITLE
Locating downloaded file opens Explorer in minimized state (Windows related) / hyperlinks too

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#768]
## The Issue
When on the claim page and clicking the Download location at the bottom of a claim, the goal is to open the Explorer and locate the file. When this is done on Windows, the explorer Window flashes in the taskbar but doesn't come to focus. 

I also noticed this happens hyperlinks and Edge Browser (Chrome seems to work ok, so does IE), like the FAQ button from Help page.  Seems to occur when LBRY is in full-screen mode. 

### Steps to reproduce
1. Open a downloaded claim
2. Click path to claim from "Downloaded to"
3. Notice the explorer window does not come to the foreground.

### Expected behaviour
Explorer comes to foreground

### Actual behaviour
Flashes in taskbar

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by btzr-io** [comment]
https://github.com/electron/electron/issues/4349#issuecomment-256365499

**Comment by tzarebczan** [comment]
Closing since this is an electron bug - nothing for us to do here.
