### ISSUE TITLE
53.5 upload form bugs

### ISSUE THREAD

**Issue by keikari** [lbryio/lbry-desktop#7687]
* [ ] "name" doesn't auto-fill after selecting a file to upload (53.4 auto-fills with the file name)
* [ ] Need to select file twice for file path to show on the "file" field
* [ ] https://github.com/lbryio/lbry-desktop/issues/7685 (got filed before, just mentioning here)

**Comment by Ruk33** [comment]
Hello @keikari I wasn't able to reproduce the second issue. Did you try the latest changes in `master`?

**Comment by keikari** [comment]
Oh, actually all of the above seems to work in master like expected. Guess this can be closed.
(Only checked 53.5 at the  time)
