### ISSUE TITLE
LBRY_0.53.6.AppImage opens lbrynet.log not lbrynet.log.1

### ISSUE THREAD

**Issue by slrslr** [lbryio/lbry-desktop#7725]
"Log has max file size, once it's full it gets renamed to lbrynet.log.1 and so on."

Yet under Settings wheel / Help / View your log, LBRY_0.53.6.AppImage opens lbrynet.log not lbrynet.log.1

On Linux Debian 11 with up to date KDE (desktop interface) packages.

**Comment by keikari** [comment]
That's not a bug, but expected behavior. The most recent log file is lbrynet.log.

You can find old logs from https://lbry.com/faq/how-to-find-lbry-log-file#manual

**Comment by slrslr** [comment]
Sorry i have not known it, you are right, so this is not a bug.
After opening your link and checking files in that folder:

$ tail -n 1 $HOME/.local/share/lbry/lbrynet/lbrynet.log*
```
==> /home/me/.local/share/lbry/lbrynet/lbrynet.log <==
2022-11-07 11:59:10,367 INFO     lbry.stream.managed_stream:401: stopping inactive download for lbry://video-name-here#longstringhere (string...)

==> /home/me/.local/share/lbry/lbrynet/lbrynet.log.1 <==
2022-11-06 18:37:05,862 INFO     lbry.torrent.tracker:233: Found 3 peers from tracker for 25cd6f2x
```

It is several hours since last line in any of the files. **Do you have idea why it is not logging?**

**Comment by keikari** [comment]
Haven't heard about that before. If you play something in app do there still appear more log entries?

**Comment by slrslr** [comment]
@keikari Thank you, i see that LBRY created 2 config. folders so it is not so easy, issue 7726
