### ISSUE TITLE
Unpublished channels remain stuck in channel sub list with no way to remove

### ISSUE THREAD

**Issue by Sessh22** [lbryio/lbry-desktop#7735]
This is a bug that has been in the LBRY app since I first started using it, so I don't think this is platform/version related. Due to the nature of it, I'm not sure it's easily reproducable either. Here's the deal:

I subscribed to a channel on Odysee (China Uncensored) which was originally not being managed by the CU people, but was being run without permission by someone else. Eventually, that channel was removed/unpubished and the real CU channel came to Odysee. 

The problem is the old unpublished channel is stuck in my channel subs list with no way to remove it. I only get options to "Block" or "Mute" the channel, but not remove/unsubscribe from it. Neither of the given options do much of anything and both the unpublished and legitimate channels appear in my subbed channels list. 

If I go to the Odysee website, the unpubbed channel is not in the list and the legit one is, so seems to be a LBRY issue with the deleted channel not auto-removing itself. This doesn't seem easy to reproduce, but that's the situation.

Here are some screenshots:

![LBRY 1](https://user-images.githubusercontent.com/118076631/201966983-f0078158-b62a-4092-abbd-9a80147aeb58.jpg)

![LBRY 2](https://user-images.githubusercontent.com/118076631/201966996-43ed56d4-f6f6-4441-b3bc-657f4ed907ac.jpg)

If there is a way to do this that I don't know about, let me know.

**Comment by keikari** [comment]
As a work around you can remove that manually from your wallet in .../lbryum/wallets  https://lbry.com/faq/lbry-directories, and restart the app. Besides of just private keys, your followings and preferences are also stored in the wallet file.   

(If you have wallet sync enabled you may need to also update ts(timestamp) in the wallet(I think), so your changes won't get overwritten by version stored on sync server)

**Comment by Sessh22** [comment]
I found that file. There seems to be two sections in there where my subs are listed and I see which one I'd need to remove, but how do you update the ts? I saw one thing (I think) that had "ts" under the first list of subs, but what to update it to?

I will do this if this isn't something that gets fixed in an update.

**Comment by keikari** [comment]
I think ts is used when local version of the wallet is merged to the one on sync server. The most recent preferences/followings will be used. So probably just update it to current time.

**Comment by jessopb** [comment]
fix will be out soon.
