### ISSUE TITLE
Version 0.53.9

### ISSUE THREAD

**Issue by RubenKelevra** [lbryio/lbry-desktop#7748]
Hey @jessopb,

what's up with the v0.53.9 release?

Got a release notification and two “release was updated” notification mails, but every time I looked, the release has disappeared again.

I'm using the source via the tag as well the binaries for packaging for ArchLinux, that's why I'm following the releases so close.

Best regards :)

**Comment by ITwrx** [comment]
@RubenKelevra perhaps this issue can be closed now?
