### ISSUE TITLE
No feed refresh

### ISSUE THREAD

**Issue by coffseducation** [lbryio/lbry-desktop#7753]
**Bug**
The LBRY apps both .deb and appimage no longer update/refresh the video feed.

**To Reproduce**
1. Open LBRY deb or refresh by clicking on LBRY
2. App opens but does not update the feed.
3. Open LBRY appimage
4. App opens but does not update the feed.
5.  Clear all data.
6.  Sign in
7. Feed loads - but is still 5 days old. No new content listed.

**Expected behavior**
Refreshing brings in new video's.
New videos are available in Odysee but do not show in LBRY.

- LBRY Daemon version:
- LBRY App version: Version v0.53.9 
- LBRY Installation ID:
- Operating system: Kubuntu 20.10

**Comment by keikari** [comment]
Try to add this to your [daemon_settings.yml](https://lbry.tech/resources/daemon-settings) and restart the app

```
lbryum_servers:
 - spv18.lbry.com:50001
```

**Comment by coffseducation** [comment]
That worked!
Thank you!
