### ISSUE TITLE
Change Payment Toggled Default

### ISSUE THREAD

**Issue by reillysmith** [lbryio/lbry-desktop#780]
## The Issue
Default of always being alerted of payments is annoying for content that is under a certain threshold.

It also lowers CTR for content that might otherwise be watched.

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Default "alert me" should be $0.05 or $0.10 USD, perhaps even  $0.25, and being alerted for all payments should be the toggle.

### Actual behaviour
No matter what the price is, we're bothered with a pop-up.

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by kauffj** [comment]
One option is:

1. Change default to something like $0.25.
1. The first time a user clicks on a paid video to something less than this value, we show a modal letting them know that videos $0.25 will auto-play, and that this can be changed in Settings.

**Comment by reillysmith** [comment]
I like the modal idea. Let's run with that.

**Comment by alyssaoc** [comment]
current UI fixes this
