### ISSUE TITLE
Default Channel/Identity

### ISSUE THREAD

**Issue by reillysmith** [lbryio/lbry-desktop#787]
## The Issue
Identity/Channel creation on its own page/UX flow, outside of content Publish page [per Sean's Issue](https://github.com/lbryio/lbry-app/issues/786), but also:

- Default channel needs to be selectable as "show me as" when interacting in app via comments/tips or having a default channel to publish content toward
- You cannot use [Comments](https://github.com/lbryio/lbry-app/issues/788) without having an Identity/Channel name claimed and defaulted

**Comment by liamcardenas** [comment]
I closed the previous connected issue and we will do both of these at once:

"As a user, it would be nice to be able to create a channel outside of the current publish flow. Some sort of "Create Channel" page would be really nice."
