### ISSUE TITLE
Automated Error Reporting

### ISSUE THREAD

**Issue by liamcardenas** [lbryio/lbry-desktop#821]
## The Issue

We should log errors to loggly (and maybe amplitude?) and set up some mechanism to notify us / potentially log issues github (probably wouldn't want this) / and provide context for errors to help reproduce them (while preserving privacy).

The first obvious place to do this would be in the error modal. This is more of a brainstorm issue, other any ideas? @kauffj @seanyesmunt @IGassmann @hackrush01 ?

**Comment by tzarebczan** [comment]
This has been implemented and logged to Slack.
