### ISSUE TITLE
More Yarn Dev Settings

### ISSUE THREAD

**Issue by liamcardenas** [lbryio/lbry-desktop#828]
Let's try to make it so that we can turn off flow and/or hot reloading via
`yarn dev:no-flow`
`yarn dev:no-reload`
and `yarn dev:no-flow:no-reload` (is this a thing?) for neither or, if necessary `yarn dev:no-flow-reload`

**Comment by liamcardenas** [comment]
@seanyesmunt do you think we still need this?

**Comment by seanyesmunt** [comment]
I don't see a reason for the `no-flow` script, but a `no-reload` script would be nice

**Comment by liamcardenas** [comment]
it's if someone just wants to run flow separately and doesn't want webpack to say anything about it.

**Comment by IGassmann** [comment]
Opened an issue (electron-userland/electron-webpack#75) for adding this feature.
