### ISSUE TITLE
Allow multiple Referral Rewards to be redeemed

### ISSUE THREAD

**Issue by liamcardenas** [lbryio/lbry-desktop#829]
## The Issue

Currently, the app is not structured in a way that allows for multiple referrals. Let's allow an arbitrary number of referrals to made in the app by simply setting one variable (-1 for infinite).

Of course, whatever number is set will have to be coordinated with the API.

**Comment by tzarebczan** [comment]
@liamcardenas can we get this sized and groomed also? Would be nice to have this capability if we decide to increase the referral reward limit.

**Comment by lyoshenka** [comment]
sean says 
> The app is pretty much ready to handle this. It's just api changes that will be required. There is a check if the inviter already claimed a reward from inviting someone, I think it will mostly be removing code.
