### ISSUE TITLE
Downloaded & Published view should indicate if an associated file is downloaded in the filesystem

### ISSUE THREAD

**Issue by painbank** [lbryio/lbry-desktop#887]
## The Issue

The Downloaded & Published view in the app shows the history of content that has been accessed, but not necessarily what is currently downloaded.  

### Steps to reproduce
1.  Click Folder icon in upper right.  takes you to  the Downloaded & Published view
2. To delete a downloaded content, click on the content.
3. Click Remove.  
4. Click 'delete from computer' box.

### Expected behaviour
In the Downloaded & Published view, it should show that a file is downloaded if there is one on the file system or if it has already been deleted.

### Actual behaviour
Everything works, this is about improving the UX.

## System Configuration

- LBRY Daemon version: 
{
  "id": null,
  "jsonrpc": "2.0",
  "result": {
    "build": "release",
    "ip": "68.43.144.58",
    "lbrynet_version": "0.18.0",
    "lbryschema_version": "0.0.14",
    "lbryum_version": "3.1.11",
    "os_release": "16.7.0",
    "os_system": "Darwin",
    "platform": "Darwin-16.7.0-x86_64-i386-64bit",
    "processor": "i386",
    "python_version": "2.7.13"
  }
}

- LBRY App version:  Version 0.19.1 (0.19.1.2926)
- LBRY Installation ID:
- Operating system: OSX Sierra - 10.12.6

**Comment by tzarebczan** [comment]
@painbank - thanks so much for filing this. I believe the actions on the Published/Download view is covered by https://github.com/lbryio/lbry-app/issues/657 

Can you edit this issue to include only the history aspect or create a new one for that particular feature?

**Comment by painbank** [comment]
Ah yes, I see the secondary actions would allow the deletion.  I'll update this to view of the content should indicate if there is a downloaded file or not.

**Comment by alyssaoc** [comment]
this has been added
