### ISSUE TITLE
Toggle to show LBC / USD price / Both throughout the app

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#893]
## The Issue
Per a suggestion from a community member, it would be nice to have a toggle that would allow content prices to be shown in either LBC or USD (or both?) throughout the LBRY app (this would include any area that currently shows the LBC price)

**Comment by Arrowana** [comment]
How would the LBC price in USD be choosen?
A public API call to cryptomarketcap LBC/USD

**Comment by MSFTserver** [comment]
that's way to unstable and goes down way to often

**Comment by kauffj** [comment]
FYI https://api.lbry.io/lbc/exchange_rate already exists and is used within the app

**Comment by alyssaoc** [comment]
closing, will only show LBC for the near future
