### ISSUE TITLE
Create guided walk-through the LBRY app for new users

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#894]
## The Issue
As a new user of the LBRY app, I'd like to be shown what the various available functions and areas are.  This would be similar to what Discord does when a new user first logs in.

This would include, but not limited to:
Wallet overview, wallet backup, transaction list, rewards, invites, searching, playing a video, publishing content, settings.

Any of the steps should allow being skipped, or "snoozed" (until the user returns to that particular area again?).

**Comment by liamcardenas** [comment]
Great Idea, I would like to implement this as well. @seanyesmunt how can we work this into the redesign?

**Comment by seanyesmunt** [comment]
I was planning on adding this after the redesign is complete. I think there
are a lot of routes we can take. We could add this to the redesign, but it
would be the last thing to add.

**Comment by seanyesmunt** [comment]
I think it will be a pretty substantial feature to get something that
really works well.

**Comment by kauffj** [comment]
Agreed, out of scope for the redesign.

**Comment by seanyesmunt** [comment]
From #1791
> This looks like a good candidate: https://introjs.com

**Comment by alyssaoc** [comment]
closing for micro tutorials
