### ISSUE TITLE
Enhance file remove modal

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#895]
## The Issue
The current file remove modal can be confusing to users:

![file remove](https://user-images.githubusercontent.com/8120721/34314317-5ffa04ae-e740-11e7-9ecd-55e4c5088a63.png)

1) "from LBRY?" should probably be closer to something like "from the app", especially on claims that you don't own. 
2) show the file path/name somewhere
3) rewording of claim abandoning, check on by default. Warn if unchecking - the file is removed from their publishes area and the user can't remove the deposit from the claim page anymore (needs to be deleted via transaction list or redownloaded).

**Comment by Andre-rsfc** [comment]
I'm working on it

**Comment by brentmclark** [comment]
Can I grab this one?

**Comment by kauffj** [comment]
That'd be awesome @brentmclark !

**Comment by brentmclark** [comment]
Thanks @kauffj!  I could use a little help with the verbiage, though.  I'm not particularly familiar with this product.

So far, I have this when checked: 

![state when checked](https://cl.ly/5a67454f9c41/Image%202019-10-14%20at%206.21.41%20PM.png)

and this when unchecked: 

![state when unchecked](https://cl.ly/8fbe0ab3017e/Image%202019-10-14%20at%206.22.53%20PM.png)

**Comment by seanyesmunt** [comment]
@brentmclark Those are looking great!

**Comment by brentmclark** [comment]
Thanks, @seanyesmunt!  I still have some work to do to get the strings into `app-strings.json` and the styles into the SCSS files.  The `app-strings` implementation looks pretty straightforward, but I could use some help finding the optimal place for my styles.

For example, the red copy above.  Can I add a `--color-warning` variable to the `_vars.scss` file or should this be treated as a one-off?

Similarly, for the form field descriptions that rest atop their respective form fields; I see you're using `BEM`.  Does it make sense to extend the `fieldset-section` block with something like `fieldset-section__description` and `fieldset-section__description--subtext`?

**Comment by seanyesmunt** [comment]
The `app-strings` will be populated automatically so you don't need to worry about those.

You can just use `.error-text` for the red text.

For the additional text we should probably just use the `helper` prop, since we use that in other places. Maybe both the error and description text should be passed as `helper`? Not sure how that would look.

**Comment by brentmclark** [comment]
@seanyesmunt Thanks for the quick feedback; I'll give these a shot tonight.

**Comment by brentmclark** [comment]
@seanyesmunt `.error-text` worked great; thanks!

The `helper` prop renders content below the checkbox instead of above the checkbox.  To me, it doesn't read properly when rendered below the checkbox in this instance.  Thoughts?

![helper text rendered below checkbox](https://cl.ly/ef0ed756ff0c/Image%202019-10-15%20at%209.22.42%20PM.png)

**Comment by brentmclark** [comment]
Oh my goodness I'm dense 😛.  How do you feel about this approach instead?

![without error](https://cl.ly/ce0dc261f08e/Image%202019-10-16%20at%201.14.37%20PM.png)

![with error](https://cl.ly/3507f9c5681d/Image%202019-10-16%20at%201.14.43%20PM.png)

**Comment by seanyesmunt** [comment]
That's looking great!

**Comment by brentmclark** [comment]
Awesome. I'll cut the PR tonight.  Thanks for your help!

**Comment by e4drcf** [comment]
may be it's time to close this issue?) 
it's in the master already)
