### ISSUE TITLE
Feature Request : Subscribe notifications

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-desktop#901]
## The Issue
please add the notification feature in LBRY app. so publishers can see who subscribes to his channel. I only have 1 subscriber lupo TV but when I open LBRY APP there is no such notification. here is a screenshot of Lupo Tv that has subscribed my channel.
## System Configuration

 

- LBRY Daemon version: 0.18.0
- LBRY App version: 0.19.2
- LBRY Installation ID: 4HrrogG8zemVjZ4bbuggKehjmeZF6eUuX5pVqQijahpAVFpNrt2iuscGmGMfvwXu6j
- Operating system: Windows (Windows-10-10.0.15063)

## Screenshots

![chris](https://user-images.githubusercontent.com/26609573/34328852-67a39a64-e91e-11e7-952b-e6c5c354e224.jpg)

**Comment by ykris45** [comment]
i referenced this issues #695

**Comment by liamcardenas** [comment]
This is definitely something we want to have in the future, thanks for the suggestion

**Comment by ykris45** [comment]
You welcome sir . thanks for added label for this issues / suggestion
