### ISSUE TITLE
Ability to search through Downloads / Publishes pages

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#907]
## The Issue
As a user, I'd want to be able to search through my downloads and published files. Currently, if you are on any of those pages, the search function will just take you to a regular LBRY search. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by astrolope** [comment]
Hello! 

I just forked and was looking through how the Wunderbar is rendered in relation to the downloads / published file lists. 

Would you only want the files to be searchable from their respective pages? Or, include the results in the auto-suggestion box. Also, should the rendered lists be filterable as a result of the search if you were on one of those pages?

**Comment by tzarebczan** [comment]
Hey @astrolope, welcome to the LBRY GitHub! Have you run the current redesign version from master? The search now includes results from Downloads, but does not go into Publishes. There might be enough room after Downloads to also show search results from Publishes, or we could includes both downloads/publishes in the single column. Maybe @seanyesmunt has some thoughts here. 

Looking forward to your contributions. Check out https://lbry.io/faq/contributing :)

**Comment by astrolope** [comment]
@tzarebczan, thanks for the welcome! Are you referring to the latest updates on the master branch correct? If so, yes. I ran a search for something I downloaded and it listed itself twice in the auto-suggestion box, so that must be the addition of the searchable downloads. Perhaps some text or creating a divider to indicate that it's an already downloaded/published file and available locally? If there was enough room I feel it could make sense to intermingle those respective suggestions.

**Comment by tzarebczan** [comment]
@astrolope not sure if the duplicate was coming from downloads, it could be related to something else (the autocomplete results themselves). 

After entering your search term, select the first item (which is the search term -search) - this will take you to a search page - that's what I was referring to.

**Comment by seanyesmunt** [comment]
Hey @astrolope!

All of the search redux code lives in `lbry-redux`. I think adding autocomplete suggestions from downloads would be great, and your solution sounds like it's going in the right direction. I know an additional change I would like to make is to concat all of the file "parts" (author, description, title) into one string and perform a regex search on it, which would allow partial matches to work. (That should probably be it's own issue though).

I think there are 3 parts to this issue:

1. Add published content to the search page. This would be in the same column as downloads
2. Add downloads/publishes to the autocomplete results in the search bar, we would need to limit them to some number of matches so you don't get 100 results from typing the letter "a" (not sure the best way to do that
3. Add search bars to the "your downloads" and "your publishes" pages. This would just filter the list of cards based on the search query (it would probably go inside the `FileList` component)

**Comment by seanyesmunt** [comment]
Made a separate issue for what I was talking about https://github.com/lbryio/lbry-app/issues/1489

**Comment by astrolope** [comment]
Hey @seanyesmunt 

Thanks for reaching out and detailing how you would like this to get put together. I agree that the partial matches is something that should be addressed. Cleaning up that matching function will make query matcher a bit easier to read as well. :) I also agree that this is definitely a level 3 issue and I'll have to take a little more time to familiarize myself with the app and the associated redux repository before I can make any serious progress. I'll work through it one section at a time and ping you if I have any questions. 

Thanks a ton!

**Comment by seanyesmunt** [comment]
Sounds good! Definitely let me know if you do!

**Comment by daovist** [comment]
I'm gonna work on this feature.

**Comment by kauffj** [comment]
Are we imagining a change to the existing search behavior or a new separate search bar for this feature? My preference would be the former if we can come up with good UX around it
