### ISSUE TITLE
Move "Report" feature to inside of app?

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#909]
## The Issue
The Report feature, which is used to report content for infringement, opens in a separate web page outside of the app.  

Should this be moved to inside the app eventually?

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
I think this should definitely live inside the app. Shouldn't be too difficult.

**Comment by miikkatu** [comment]
Working on this.

**Comment by miikkatu** [comment]
@seanyesmunt @tzarebczan I have an implementation ready, but it's missing the actual submitting of the report. I couldn't figure out how the current web form does the submitting, and there's nothing in the app for this yet.

How this implementation works is:

1. Click the report button on a file page
2. App shows report page and prefills the uri of the file
3. Fill in the form and submit
4. App shows a confirmation with snackbar and navigates back to the file page

This can also be used by itself, for example from the sidebar. Only then the infringing file uri would not be prefilled.

<img width="514" alt="screen shot 2018-04-11 at 12 35 58" src="https://user-images.githubusercontent.com/16205520/38609736-86df3e2a-3d87-11e8-9ff0-2e9a7641a11e.png">

**Comment by kauffj** [comment]
@miikkatu thanks for working on this. Unfortunately, the current end behavior of a DMCA report is just trigger an email (see [here](https://github.com/lbryio/lbry.io/blob/90eae9cbfc7a66dba9b59c51652adf06a63f0718/controller/action/ReportActions.class.php)) and this is not easy to just move into the app.

I filed an issue in our internal-apis project to build an endpoint for receiving these, but I'm afraid this one is blocked until that happens.

Although I suppose you could post to lbry.io/dmca in the interim... that would allow this to be shipped.

**Comment by miikkatu** [comment]
> Although I suppose you could post to lbry.io/dmca in the interim

I was thinking about this too. For this, we would need an URL where to POST, and an object format that it would accept. I couldn't figure those out in the lbry.io/dcma code. Then, a team member could verify if the posted data is proper or not.

Otherwise, we could wait with this until there's an endpoint available. 🙂

**Comment by tzarebczan** [comment]
![post](https://user-images.githubusercontent.com/8120721/38889548-0e68598e-424d-11e8-9735-e7662e5ddedf.jpg)

@miikkatu this is what the post call looks like - should be able to pass the same parameters (might need to URL encode them as well)

**Comment by kauffj** [comment]
@miikkatu we'll likely get this fixed web-side within a week or so. I'm inclined to just allow unrestricted POSTs to lbry.io/dmca.

See https://github.com/lbryio/lbry.io/issues/517

**Comment by maximest-pierre** [comment]
PR has been submitted on lbry.io https://github.com/lbryio/lbry.io/pull/525

**Comment by kauffj** [comment]
@miikkatu CORS change is merged if you want to test this in app. Feel free to spam the endpoint, they only come to a few people and they'll be aware. (@finer9 @tzarebczan)

**Comment by tzarebczan** [comment]
Hmm, @maximest-pierre any thoughts? It was merged here: https://github.com/lbryio/lbry.io/pull/525

**Comment by maximest-pierre** [comment]
Yes it was merge, I look at it quickly this morning. Both GET and POST header shows that its enabled.

**Comment by maximest-pierre** [comment]
Is it still a 405 error or is it a 301 error now. @miikkatu

**Comment by miikkatu** [comment]
@maximest-pierre 405, just like before (screenshot above).

**Comment by maximest-pierre** [comment]
Can you open a PR with your current code so I can recreate your error.

**Comment by miikkatu** [comment]
@maximest-pierre PR opened. The fetch request code is in src/renderer/page/reportcontent/view.jsx. Hopefully you can recreate the error and find out what's going on. 🙂

**Comment by alyssaoc** [comment]
closing, we will keep the webpage and not move into the app
