### ISSUE TITLE
Functionality of "Open" button on claim page confusing at first

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#913]
## The Issue
If a user had a file downloaded or streamed, the Open button shows on the claim page. It's not clear what exactly this button without clicking it first. Some users may think it will open the file in the LBRY app, but it tries to open the file externally. If the file is not available, it just opens the folder (https://github.com/lbryio/lbry-app/issues/586).

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by liamcardenas** [comment]
Maybe this would be better if it said "Show in file system" or on macOS "show in finder". Then we could link to the file but not open it. Thoughts?

**Comment by alyssaoc** [comment]
closing for #1761
