### ISSUE TITLE
Shortcut to jump to search bar?

### ISSUE THREAD

**Issue by seanyesmunt** [lbryio/lbry-desktop#922]
I think it would be nice to be able to use a shortcut to quickly focus on the search bar.

My vote would be on `{cmd,ctrl} + l` which Firefox, Chrome, and Safari use

Thoughts? Should be pretty straight forward.

**Comment by kauffj** [comment]
Probably worth looking at adding a bunch of these.

**Comment by seanyesmunt** [comment]
`{cmd, ctrl} + {left/right}` for page navigation

**Comment by alyssaoc** [comment]
closing for #1395 Keyboard shortcuts, https://github.com/lbryio/lbry-desktop/issues/1395
