### ISSUE TITLE
Linked email management area

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#926]
## The Issue
As a user, I want to be able to manage what email account is connected to the LBRY app. Currently, once you are verified, there is no way to log out or change emails. The closest thing is clearing your authentication token which resets the connected email account. If you decide to change emails, the new account created loses its reward verification status and any other associated API data.  

One example of how this might look/work is: 
https://github.com/settings/emails

This will require API support: https://github.com/lbryio/internal-apis/issues/192

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Comment by alyssaoc** [comment]
closing, implemented elsewhere
