### ISSUE TITLE
Some videos may crash LBRY app / stop playing abruptly 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#937]
## The Issue
Ran into more in-app video player issues trying to stream some of CryptoCandors videos. It may be how they are encoded as I haven't seen this happen with other videos. On first stream, sometimes they play fine - but then if you leave the claim and come back after it downloaded, the playback issues are consistent.  Maybe it has something to do with the file size - some of these are over 2GB. It's either that or encoding parameters. 

On Windows, this crashes the LBRY app to a green/white screen sometimes. You lose the render process:![crash](https://user-images.githubusercontent.com/8120721/34703005-c153faa8-f4be-11e7-8720-a16d60e5a58f.png)

On Linux/Mac, it just stops playing, and sometimes restarts playback and othertimes you get a blank screen.  

Some URLS:
lbry://iota#4abeae398a127337838d1b1985a2012414549d6e
lbry://cardano#63058c2cfd1cca574278c73dc23ff6b41a90e16f
lbry://cryptoterms#9b21249249422245e510f08de5a4a683ed9da432

Her latest streams fine:
lbry://livewithcharleshoskinson#2f3008f9f575e42e058dfdcd590968f0ac71755d

### Steps to reproduce
1. play one of the videos from above
2. If it works the first time, let it download completely and then come back to the claim

## System Configuration

 

- LBRY Daemon version: 0.18.0
- LBRY App version: 0.19.0

- LBRY Installation ID:
- Operating system:

**Comment by seanyesmunt** [comment]
This should be fixed with streaming
