### ISSUE TITLE
Inconsistent modal header appearance

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbry-desktop#940]
@alexliebowitz correctly [pointed out](https://github.com/lbryio/lbry-app/pull/808#discussion_r160289340) that we're inconsistent with our modal stylings.

I think many (most? all?) modals look better with spacing below the header when they have a header. However, several modals that have spacing just inject a `<br/>`, which is probably wrong.

@seanyesmunt please add this to design epic if it makes sense to include this in that.

**Comment by seanyesmunt** [comment]
👍 ill spend some time exploring this
