### ISSUE TITLE
Feature Request : Added Other Language Field Form

### ISSUE THREAD

**Issue by ykris45** [lbryio/lbry-desktop#943]
## The Issue
when I publish the file in LBRY App. and clicking the language selection for the content I publish. it only consists of 7 default languages. but the content that I publish it speak Indonesian. ( lbry: //@Chris45#b9dd2a4f193393b59ceac7a0dedef3bfef7ba82d/reviewlbryapp ) it's my content link. please add "other" option and content box, so other users can fill it in accordance with the language of the content they publish.
my ideas was agreed by Mr Jeremy kauffman via Discord DM . Thanks Awesome LBRY Team.. 
## System Configuration

 

- LBRY Daemon version: 0.18.0
- LBRY App version: 0.19.4
- LBRY Installation ID: 4HrrogG8zemVjZ4bbuggKehjmeZF6eUuX5pVqQijahpAVFpNrt2iuscGmGMfvwXu6j
- Operating system: Windows (Windows-10-10.0.15063)

## Screenshots
https://user-images.githubusercontent.com/26609573/34232082-46111b0c-e611-11e7-8918-ae790541546c.png

**Comment by jkfernan** [comment]
Working toward a solution.

**Comment by seanyesmunt** [comment]
Other languages were added in https://github.com/lbryio/lbry-desktop/pull/2201

For more language support feel free to open a PR.
