### ISSUE TITLE
Cannot select or install new themes

### ISSUE THREAD

**Issue by btzr-io** [lbryio/lbry-desktop#956]
## The Issue
> Sean King - Today at 8:10 PM
For some reason, the theme selector doesn't recognize new themes added to the folder where dark and light are.

### Steps to reproduce
1.  Add a new theme -> `/themes` folder.
2. Go to settings page and use the theme selector.
### Expected behaviour
The theme selector should recognize new themes added to the `/themes` folder.

### Actual behaviour
 The theme selector doesn't recognize new themes.

## Anything Else
Introduced here -> https://github.com/lbryio/lbry-app/pull/865/commits/0852ed033b0532e77c86ef3fe09c8ff0244dba29

**Comment by kauffj** [comment]
I signed off on this (possibly I shouldn't have ;), but IIRC @IGassmann had a reason for making this change.

**Comment by IGassmann** [comment]
@kauffj It was a temporary solution that we discussed on a call. I'll work on it to result in a more reliable code.

**Comment by Arrowana** [comment]
Should be easy to fix adding a search for files *.css in the static/themes folder, let me now @IGassmann if you want me to take this one :).

Themes are currently hardcoded here:
https://github.com/lbryio/lbry-app/blob/c894567eb9ded7f8f6802ec30de415e78c10ac84/src/renderer/redux/actions/settings.js#L49

**Comment by IGassmann** [comment]
@Arrowana there were some problems with the previous solutions. That's why I temporarily hardcoded the themes.
