### ISSUE TITLE
Investigate - streaming non-web optimized MP4s in app

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbry-desktop#980]
## The Issue
Recently noticed that non-web optimized (those that do not have the moov atom / metadata at the beginning of the file) stream immediately (without having to download the entire file) on instant.io which uses the same web player as we do. This behavior is different from what we see in the LBRY app - the entire file must be downloaded before the stream begins. I'm not sure if we stream from the blob files or from the Mp4 itself and instant.io may do it differently, but it's worth investigating. 

Depending on the results of this investigation, we may want to put up a different message on the video player for streams that require the entire file to be downloaded first.  Right now it just shows "waiting for metadata" at the top of the player. 

Instant.io stream - https://instant.io/#69597aeaefcda9f4a268fbee72eca3ba96ab93dc (if this link doesn't work, let me know so I can get it hosted again) 

LBRY app stream - lbry://freecryptocurrencyhowtoclaimrewardsonlbry#592e48c0dd3e309b371956667a80aac8c83a8a60

### Steps to reproduce
1. stream instant.io link - notice it starts playing immediately while the file still downloads
2. stream LBRY app link - notice it doesn't start streaming and wait for the entire file to finish.  

## System Configuration

 

- LBRY Daemon version: 0.18.0
- LBRY App version: 0.19.4
- LBRY Installation ID:
- Operating system:

**Comment by xorgy** [comment]
@tzarebczan Interested in looking at this, if you'd host the offending video again I could get my own seed and take a better look. I don't have any offending MP4s on me.

**Comment by tzarebczan** [comment]
@xorgy I just uploaded the file to https://instant.io/#69597aeaefcda9f4a268fbee72eca3ba96ab93dc again.  If you can't get to it, download it on LBRY: lbry://freecryptocurrencyhowtoclaimrewardsonlbry#592e48c0dd3e309b371956667a80aac8c83a8a60 and then take the mp4 and upload it to instant.io (and then access the URL from a 2nd PC). 

Let me know if you have any questions!

**Comment by xorgy** [comment]
Sweet, I'll investigate a bit and report back anything interesting, patch if I know what I'm doing.

**Comment by seanyesmunt** [comment]
Fixed with new player
