### ISSUE TITLE
Inconsistency with decimal separation of values.

### ISSUE THREAD

**Issue by MR4Y** [lbryio/lbry-desktop#984]
The app displays decimal LBC values separated by period, but the "Send/Receive" part of it only accepts comma separated values instead, but displays a default period separated value. The "Publish" section displays a default value comma separated, but accepts both forms of decimal separation. 

### Steps to reproduce
1. Enter the "Send/Receive" section of the app 
2. Attempt to send a value with the decimal part separated by period

### Expected behaviour
Either use one or the other, or accept both forms for everything.

### Actual behaviour
Specifically in the "Send/Receive" section, any attempt of giving a decimal value separated by period clears the value box

## System Configuration
- Intel Pentium E5300
- 4GB DDR2 RAM
- Radeon HD 5450 1 GB PCIe version

- LBRY Daemon version: 0.18.2
- LBRY App version: 0.20.0
- LBRY Installation ID: 7Buq65n8m7X5PaFQRTnU6QBSPZf3RzAH6z5rqWvU4M6CqhkjoYEtVz1GyxYRZNCHvz
- Operating system: Windows 7 Home Basic SP1 64 bits

![thing](https://user-images.githubusercontent.com/9355061/35646875-d39439ac-06b7-11e8-9608-9c725fb5b302.gif)

**Comment by tzarebczan** [comment]
Thanks for filing this @MR4Y! Sent you a few credits on Discord :)

**Comment by kekkyojin** [comment]
Which is your operating system locale, @MR4Y ?

**Comment by MR4Y** [comment]
At the time of the report, Brazillian Portuguese

**Comment by btzr-io** [comment]
I can't recreate this ^^

**Comment by alyssaoc** [comment]
closing, reopen if it continues to be an issue
