### ISSUE TITLE
Add "log out" link that clears their auth token

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbry-desktop#997]

**Comment by tzarebczan** [comment]
I assume this is the temporary workaround to https://github.com/lbryio/lbry-app/issues/926 ? 

How would this work? Would it reload the app and clear out local storage (so they are prompted for email on next refresh)?

**Comment by tzarebczan** [comment]
This is still a valid issue. If a user mistypes their email, there's no way to clear it out.

**Comment by tzarebczan** [comment]
We added a change email link with instructions on how to clear the token. There's another issue filed for removing the need for a token and to use a cookie instead.
